flutter/plugins

packages/e2e/CHANGELOG.md, packages/e2e/android/build.gradle, packages/e2e/android/src/main/java/dev/flutter/plugins/e2e/E2EPlugin.java, packages/e2e/example/android/app/src/androidTest/java/com/example/e2e_example/EmbedderV1ActivityTest.java, packages/e2e/example/android/app/src/main/AndroidManifest.xml, packages/e2e/example/android/app/src/main/java/com/example/e2e_example/EmbedderV1Activity.java, packages/e2e/example/android/app/src/main/java/com/example/e2e_example/MainActivity.java, packages/e2e/example/android/gradle.properties, packages/e2e/example/pubspec.yaml, packages/e2e/lib/e2e.dart, packages/e2e/pubspec.yaml
Required in order to end-to-end test migrated plugins.
=> [e2e] Update to support new embedder

packages/image_picker/CHANGELOG.md, packages/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.m, packages/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.h, packages/image_picker/pubspec.yaml, script/lint_darwin_plugins.sh
Fix build and analyzer issues.
- Leak
- Nullability
Fixes https://github.com/flutter/flutter/issues/42678.
Fixes https://github.com/flutter/flutter/issues/30556.
=> [image_picker] Fix iOS build and analyzer warnings

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.h, packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m, script/lint_darwin_plugins.sh
- Fix mutable collection being stored immutably.
Slight cleanup of InAppPurchasePlugin since I was editing it anyway:
- Decorated designated initializer to initialize mutable collection ivars on init, then remove (unthreadsafe) getters in favor of synthesized property getters.
- Set ivars instead of properties in initializers.
- Make category properties readonly.
Fixes https://github.com/flutter/flutter/issues/42679.
=> [in_app_purchase] Fix iOS build warning

packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java, packages/webview_flutter/example/android/app/src/main/java/io/flutter/plugins/webviewflutterexample/MainActivity.java
The V2 embedding in webview_flutter depends on an extremely new bugfix
in flutter/engine. This was mentioned in the git log but that's
difficult to find. Add more warnings in the docs surrounding the new
code path.
In general this is an interesting problem. We can't select for the
higher version as a min SDK requirement because the old embedding path
doesn't need this bugfix. Ideally we should figure out a way to
programmatically enforce this constraint instead of relying on developer
documentation. This kind of problem is likely to happen again.
flutter/flutter#41851
flutter/engine#13015
flutter/flutter#42792
Does …
=> [webview_flutter] (Trivial) Add V2 warnings

packages/android_intent/CHANGELOG.md, packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/AndroidIntentPlugin.java, packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/IntentSender.java, packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/MethodCallHandlerImpl.java, packages/android_intent/example/android/app/src/androidTestDebug/java/io/flutter/plugins/androidintentexample/EmbeddingV1ActivityTest.java, packages/android_intent/example/android/app/src/androidTestDebug/java/io/flutter/plugins/androidintentexample/MainActivityTest.java, packages/android_intent/example/android/gradle.properties, packages/android_intent/example/pubspec.yaml, packages/android_intent/example/test_driver/android_intent_e2e.dart, packages/android_intent/example/test_driver/android_intent_e2e_test.dart, packages/android_intent/pubspec.yaml
- Fix minor lint errors in the Java platform code.
- Add a smoke e2e test for the V2 embedding.
- Fully migrate the example app to AndroidX.
flutter/flutter#41831
=> [android_intent] Cleanup the V2 migration

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/ios/Classes/GoogleMapController.h, packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.h, packages/google_maps_flutter/pubspec.yaml
Remove a few compiler warnings (missing nullability specifier) for iOS users.
=> [google_maps_flutter] Add NonNull macro to reduce warnings in iOS

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/android/build.gradle, packages/in_app_purchase/android/gradle.properties, packages/in_app_purchase/pubspec.yaml
After 0.2.2, we introduced a constraint that the app uses the plugin has to be migrated to androidx.
This patch removes the constraint.
=> [in_app_purchase] remove AndroidX constraint

packages/package_info/CHANGELOG.md, packages/package_info/android/build.gradle, packages/package_info/android/gradle.properties, packages/package_info/pubspec.yaml
Android: Use android.arch.lifecycle instead of androidx.lifecycle:lifecycle in build.gradle to support apps that has not been migrated to AndroidX. …
=> [package_info]remove AndroidX constraint

packages/android_intent/CHANGELOG.md, packages/android_intent/android/build.gradle, packages/android_intent/android/gradle.properties, packages/android_intent/pubspec.yaml
We introduced a constraint that the app uses the plugin has to be migrated to androidx.
This patch removes the constraint. …
=> [android_intent]remove AndroidX constraint

packages/flutter_plugin_android_lifecycle/CHANGELOG.md, packages/flutter_plugin_android_lifecycle/example/android/app/src/main/java/io/flutter/plugins/flutter_plugin_android_lifecycle_example/MainActivity.java, packages/flutter_plugin_android_lifecycle/example/pubspec.yaml, packages/flutter_plugin_android_lifecycle/pubspec.yaml
Speculative fix for build redness.
=> [flutter_plugin_android_lifecycle] register the e2e plugin in the example app

packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml, packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart
Fail setting `UrlLauncherPlatform.instance` to something that `implements` (rather than `extends`) `UrlLauncherPlatform`.
I'm not bumping the major version as the breaking change policy for platform interface is that we're only guaranteeing to not break classes that `extend` it.
We leave a backdoor for mockito mocks which can do:
```dart
class MockUrlLauncherPlatform extends Mock
implements UrlLauncherPlatform {}
test('', () {
MockUrlLauncherPlatform mock = MockUrlLauncherPlatform();
when(mock.isMock).thenReturn(true);
UrlLauncherPlatform.instance = mock;
}
```
Does your PR require plugin users to manually update …
=> Forbid `... implements UrlLauncherPlatform`

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/lib/url_launcher.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher/test/url_launcher_test.dart, script/build_all_plugins_app.sh
Forward calls from `package:url_launcher` to the platform-specific implementation declared in `UrlLauncherPlatform.instance`.
=> [url_launcher] Use `url_launcher_platform_interface` to handle calls

packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml, packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart
This is causing issues intenally.
This is also the recommended way in Dart guidelines: https://dart.dev/guides/libraries/create-library-packages#importing-library-files
=> Use package import to import files inside lib/ directory.

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.m
Cast error.code to unsigned long to avoid using NSInteger as %ld format warnings.
=> [google_maps_flutter] Cast error.code to unsigned long to avoid using NSInteger as %ld format warnings.

packages/image_picker/CHANGELOG.md, packages/image_picker/README.md, packages/image_picker/lib/image_picker.dart, packages/image_picker/pubspec.yaml, packages/image_picker/test/image_picker_test.dart
Added documentation for the ImagePicker class.
Added Unit test for pickVideo method.
Removed beta documents in README.
https://github.com/flutter/flutter/issues/44393
=> [image_picker] more documentations and tests.

packages/connectivity/CHANGELOG.md, packages/connectivity/example/README.md, packages/connectivity/lib/connectivity.dart, packages/connectivity/pubspec.yaml
Add more documentations in the plugin.
Fixes https://github.com/flutter/flutter/issues/44386
=> [connectivity] add more documentations, delete example/README

packages/google_maps_flutter/pubspec.yaml
https://github.com/flutter/plugins/pull/2242 added a new CHANGELOG version but did not bump the pubspec version.
Update to 0.5.21+10.
=> Bump google_maps_flutter pubspec version to match CHANGELOG

analysis_options.yaml, packages/android_intent/CHANGELOG.md, packages/android_intent/analysis_options.yaml, packages/android_intent/example/lib/main.dart, packages/android_intent/lib/android_intent.dart, packages/android_intent/lib/flag.dart, packages/android_intent/pubspec.yaml
=> [android_intent] Add missing DartDocs

packages/android_alarm_manager/lib/android_alarm_manager.dart, packages/camera/lib/camera.dart, packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart
35e984fc migrated some deprecated analyzer warnings to the newer
alternatives. These created some failures in unrelated plugins based on
the warnings being slightly different: https://cirrus-ci.com/task/6665202786893824?command=main#L152
Added `ignore`s for now to turn CI green again as soon as possible. The
previous analysis options really should not be used and the majority of
the patch was unrelated, so I prefer ignoring specific already failing cases
to reverting in this case. Including an `analysis_options.yaml` file with
deprecated analyzer rules causes analyzer failures in the including package,
so that patch can't be landed in a way that prevents regressions
without updated rules.
Before you create this PR confirm that it meets all requirements listed below by checking the …
=> [infra] Ignore analyzer issues in CI

packages/quick_actions/CHANGELOG.md, packages/quick_actions/example/ios/Runner.xcodeproj/project.pbxproj, packages/quick_actions/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/quick_actions/pubspec.yaml
=> [quick_actions] Update and migrate iOS example project

packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/example/ios/Runner.xcodeproj/project.pbxproj, packages/shared_preferences/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/shared_preferences/pubspec.yaml
=> [shared_preferences] Update and migrate iOS example project

packages/connectivity/CHANGELOG.md, packages/connectivity/analysis_options.yaml, packages/connectivity/example/lib/main.dart, packages/connectivity/lib/connectivity.dart, packages/connectivity/pubspec.yaml
Missing DartDocs were recently added to this plugin. Add a
package-specific analysis options to make sure that they don't regress
going forward.
flutter/flutter#44386
=> [connectivity] Lint for public DartDocs

packages/image_picker/analysis_options.yaml, packages/image_picker/example/lib/main.dart, packages/image_picker/lib/image_picker.dart
Missing DartDocs were recently added to this plugin. Add a
package-specific analysis options to make sure that they don't regress
going forward.
flutter/flutter#44393
=> [image_picker] Lint for public DartDocs

packages/sensors/CHANGELOG.md, packages/sensors/README.md, packages/sensors/analysis_options.yaml, packages/sensors/example/lib/main.dart, packages/sensors/example/lib/snake.dart, packages/sensors/lib/sensors.dart, packages/sensors/pubspec.yaml, packages/sensors/test/sensors_test.dart
- Add missing dartdoc coverage and expand on existing documentation.
Add an analyzer warning for this package so that public doc coverage
doesn't regress.
- Improve unit test coverage.
- Expand on the existing README.
Fixes flutter/flutter#44402. …
=> [sensors] Documentation and test improvements

packages/path_provider/CHANGELOG.md, packages/path_provider/example/ios/Runner.xcodeproj/project.pbxproj, packages/path_provider/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/path_provider/pubspec.yaml
1. Looks like this was last run with `use_frameworks!`?  Let CocoaPods build as libraries instead of frameworks.
=> [path_provider] Update and migrate iOS example project

packages/video_player/CHANGELOG.md, packages/video_player/android/build.gradle, packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java, packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java, packages/video_player/example/android/app/src/main/AndroidManifest.xml, packages/video_player/example/android/app/src/main/java/io/flutter/plugins/videoplayerexample/EmbeddingV1Activity.java, packages/video_player/example/android/app/src/main/java/io/flutter/plugins/videoplayerexample/MainActivity.java, packages/video_player/example/android/gradle.properties, packages/video_player/example/lib/main.dart, packages/video_player/example/pubspec.yaml, packages/video_player/example/test_driver/video_player_e2e.dart, packages/video_player/example/test_driver/video_player_e2e_test.dart, packages/video_player/pubspec.yaml
- Adds support in the plugin
- Adds a v2 embedding to the example app
- Fixes a broken remote example in the example app
- Increments the Flutter SDK dependency
- Increments the version
- Adds e2e tests for some simple use cases of the plugin
Fixes flutter/flutter#41850. …
=> [video_player] Add v2 embedding support

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/example/ios/Runner/AppDelegate.m, packages/google_maps_flutter/ios/Classes/GoogleMapCircleController.m, packages/google_maps_flutter/ios/Classes/GoogleMapController.h, packages/google_maps_flutter/ios/Classes/GoogleMapController.m, packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.m, packages/google_maps_flutter/ios/Classes/GoogleMapPolygonController.m, packages/google_maps_flutter/ios/Classes/GoogleMapPolylineController.m, packages/google_maps_flutter/ios/google_maps_flutter.podspec, packages/google_maps_flutter/pubspec.yaml, script/lint_darwin_plugins.sh
- Revert https://github.com/flutter/plugins/pull/1734 to support modules.
- Fix 35 analyzer warnings:
```
GoogleMapMarkerController.m:98:7: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
GoogleMapMarkerController.m:106:7: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call …
```
=> [google_maps_flutter] Define clang module for iOS, fix analyzer warnings

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/analysis_options.yaml, packages/url_launcher/url_launcher/example/lib/main.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher/test/url_launcher_test.dart, packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/analysis_options.yaml, packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml
- Add a lint to url_launcher and url_launcher_platform_interface to
prevent undocumented public members.
- Add some unit tests.
Fixes flutter/flutter#44404.
=> [url_launcher] DartDoc and test improvements

packages/battery/CHANGELOG.md, packages/battery/example/ios/Runner.xcodeproj/project.pbxproj, packages/battery/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/battery/pubspec.yaml
1. Looks like this was last run with `use_frameworks!`?  Let CocoaPods build as libraries instead of frameworks.
=> [battery] Update and migrate iOS example project

.cirrus.yml, packages/e2e/example/pubspec.yaml
Also fixed a complier failure after upgrading to xcode11
PRs in plugin repo are failing CIs at the step of creating iOS simulator like https://github.com/flutter/plugins/pull/2083
cirrus console link: https://cirrus-ci.com/task/5575560322875392
=> Update cirrus to create IOS simulator on 13.2 an xCode 11

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart, packages/webview_flutter/lib/platform_interface.dart, packages/webview_flutter/lib/src/webview_method_channel.dart, packages/webview_flutter/lib/webview_flutter.dart, packages/webview_flutter/pubspec.yaml
Previously all navigation decisions needed to be made synchronously in
Dart. The platform layers are already waiting for the MethodChannel
callback, so just changed the return type to be
`FutureOr<NavigationDecision>'.` This is a change to the method signature
of `WebViewPlatformCallbacksHandler#onNavigationRequest`, but that
interface appears to only be meant to be implemented internally to the
plugin.
Fixes flutter/flutter#43271. …
=> [webview_flutter] Add async NavigationDelegates

packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/lib/google_sign_in.dart, packages/google_sign_in/google_sign_in/pubspec.yaml, packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart, script/build_all_plugins_app.sh
* Migrate the 'native' plugin to the Platform Interface
* Adapt tests to the new API
This is required for plugin federation (to implement the Web version in a separate package)
**The `GoogleSignInPlatform.instance` interface is defined (and implemented) in the `google_sign_in_platform_interface` package, [here](https://pub.dev/documentation/google_sign_in_platform_interface/latest/google_sign_in_platform_interface/google_sign_in_platform_interface-library.html).**
https://github.com/flutter/flutter/issues/43775
[issue …
=> [google_sign_in] Port plugin to use the federated Platform Interface

packages/image_picker/CHANGELOG.md, packages/image_picker/ios/Classes/ImagePickerPlugin.m, packages/image_picker/pubspec.yaml
Fixes an issue that could result in a crash when picking videos from gallery on iOS 13 or above. 
[#41046](https://github.com/flutter/flutter/issues/41046)
=> [image_picker] Fix a crash when picking video on iOS 13 and above.

packages/path_provider/CHANGELOG.md, packages/path_provider/analysis_options.yaml, packages/path_provider/example/lib/main.dart, packages/path_provider/lib/path_provider.dart, packages/path_provider/pubspec.yaml
Also adds a lint to prevent future undocumented public APIs.
Fixes flutter/flutter#44398.
=> [path_provider] Add missing DartDocs

packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/README.md, packages/url_launcher/url_launcher_web/pubspec.yaml
Updated dependencies and docs in the package so it can be usable from pub.
=> [url_launcher] Update deps and docs in url_launcher_web

CONTRIBUTING.md
There was a recent contributor who was blocked on trying to run the Java unit tests, since they're not clearly documented anywhere.
=> Fix testing instructions in CONTRIBUTING.md

CONTRIBUTING.md
Removes obsolete recommendations about removing mockito (which is now used in testing federated plugins, see https://github.com/FirebaseExtended/flutterfire/pull/1472).
https://github.com/flutter/flutter/issues/34284
=> Update CONTRIBUTING.md to allow mockito

packages/video_player/analysis_options.yaml, packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/analysis_options.yaml, packages/video_player/video_player/example/lib/main.dart, packages/video_player/video_player/lib/video_player.dart, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player/test/video_player_test.dart
Also adds a lint to prevent undocumented APIs going forward.
Fixes flutter/flutter#44405.
=> [video_player] Improve DartDocs and test coverage

packages/shared_preferences/CHANGELOG.md, packages/shared_preferences/analysis_options.yaml, packages/shared_preferences/example/lib/main.dart, packages/shared_preferences/lib/shared_preferences.dart, packages/shared_preferences/pubspec.yaml
Also adds a lint to prevent further undocumented methods.
Fixes flutter/flutter#44403.
=> [shared_preferences] Add missing DartDoc

packages/share/CHANGELOG.md, packages/share/README.md, packages/share/analysis_options.yaml, packages/share/example/lib/main.dart, packages/share/pubspec.yaml
Adds a little more info on how to use the plugin. Also adds linter
options to prevent any undocumented APIs from being added in the future.
Fixes flutter/flutter#44779.
=> [share] README update

CONTRIBUTING.md
This provides information on how to publish plugins going forward with
the new `flutter_plugin_tools publish-plugin` command.
In addition to that this documents our general process, which is a
general team health issue we've been wanting for awhile.
DO NOT MERGE until flutter/plugin_tools#65 is published.
Related to flutter/flutter#42934.
Helps some points in flutter/flutter#27258. …
=> [none] Add release process to CONTRIBUTING.md

.ci/Dockerfile
Adds Chrome to the Docker image. This is to enable us to run `flutter test --platform=chrome` on web plugins.
Setup for https://github.com/FirebaseExtended/flutterfire/issues/1495
=> Add Chrome to the Docker for CI

packages/video_player/video_player_platform_interface/CHANGELOG.md, packages/video_player/video_player_platform_interface/lib/method_channel_video_player.dart, packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart, packages/video_player/video_player_platform_interface/pubspec.yaml, packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
=> [video_player] Emit correct VideoEventType

packages/google_sign_in/google_sign_in_web/CHANGELOG.md, packages/google_sign_in/google_sign_in_web/ios/google_sign_in_web.podspec, packages/google_sign_in/google_sign_in_web/pubspec.yaml
Add an empty podspec file, so this plugin doesn't break compilation on IOS.
Similar to [this](https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_web/ios).
* https://github.com/flutter/flutter/issues/45571 …
=> [google_sign_in_web] Add empty podspec to plugin.

packages/camera/CHANGELOG.md, packages/camera/analysis_options.yaml, packages/camera/example/lib/main.dart, packages/camera/example/test_driver/camera_e2e.dart, packages/camera/example/test_driver/camera_e2e_test.dart, packages/camera/lib/camera.dart, packages/camera/pubspec.yaml
There's a over a dozen API surfaces that are undocumented still. This
just fixes one of the new pedantic lints.
flutter/flutter#45440
=> [camera] Fix unawaited future errors

script/lint_darwin_plugins.sh
This is a continuation of https://github.com/flutter/plugins/pull/2316
This PR adds the google_sign_in_web plugin to the exclusion list of the darwin lint script. 
https://github.com/flutter/flutter/issues/45571
See also:
https://github.com/flutter/plugins/pull/2177 …
=> [script] Exclude google_sign_in_web from podspec lint.

packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md, packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart, packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
This is a non-breaking change. Quiver is better supported.
=> [google_sign_in] Migrate away from quiver_hashcode

packages/shared_preferences/shared_preferences_platform_interface/lib/shared_preferences_platform_interface.dart, packages/shared_preferences/shared_preferences_platform_interface/test/shared_preferences_platform_interface_test.dart
Throw AssertionError on non-mock implementations in shared_preferences.
=> shared_preferences: throw AssertionError on non-mock implementations

packages/android_alarm_manager/pubspec.yaml
This plugin relies partially on functionality which will be available in the next Flutter release.
=> [android_alarm_manager] Update minimum Flutter version to 1.12.0

packages/shared_preferences/shared_preferences_web/CHANGELOG.md, packages/shared_preferences/shared_preferences_web/LICENSE, packages/shared_preferences/shared_preferences_web/README.md, packages/shared_preferences/shared_preferences_web/lib/shared_preferences_web.dart, packages/shared_preferences/shared_preferences_web/pubspec.yaml, packages/shared_preferences/shared_preferences_web/test/shared_preferences_web_test.dart
Implement Web support for `package:shared_preferences` on top of `window.localStorage`.
Fixes https://github.com/flutter/flutter/issues/35116
=> Web implementation of shared_preferences

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/analysis_options.yaml, packages/in_app_purchase/example/lib/main.dart, packages/in_app_purchase/example/test_driver/test/in_app_purchase_e2e_test.dart, packages/in_app_purchase/lib/src/billing_client_wrappers/purchase_wrapper.dart, packages/in_app_purchase/lib/src/in_app_purchase/app_store_connection.dart, packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart, packages/in_app_purchase/lib/src/in_app_purchase/in_app_purchase_connection.dart, packages/in_app_purchase/lib/src/in_app_purchase/product_details.dart, packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart, packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart, packages/in_app_purchase/pubspec.yaml
None of these fixes should affect functionality. There are dozens of
undocumented public API members that still need to be documented to
completely remove the analysis_options for this package.
flutter/flutter#45440 …
=> [in_app_purchase] Fix most failing pedantic lints

packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/LICENSE, packages/video_player/video_player_web/README.md, packages/video_player/video_player_web/ios/video_player_web.podspec, packages/video_player/video_player_web/lib/video_player_web.dart, packages/video_player/video_player_web/pubspec.yaml, packages/video_player/video_player_web/test/video_player_web_test.dart
Adding video_player_web implementation using the platform interface from https://github.com/flutter/plugins/pull/2273
Fixes https://github.com/flutter/flutter/issues/45290
=> [video_player] Add web implementation using platform interface

packages/android_alarm_manager/pubspec.yaml
Reverts flutter/plugins#2327
Reverting to unblock CI.
@bkonyi not sure if you have a plan for a fix or whether you want to re-publish the reverted plugin, please follow-up.
=> Revert "[android_alarm_manager] Update minimum Flutter version to 1.12.0"

packages/video_player/video_player_platform_interface/CHANGELOG.md, packages/video_player/video_player_platform_interface/analysis_options.yaml, packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart, packages/video_player/video_player_platform_interface/pubspec.yaml, packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
Fixes unawaited_futures. There are still some undocumented members here
that are unclear to me, so unfortunately the analysis_options.yaml is
still there.
flutter/flutter#45440
flutter/flutter#46119
[CLA]: …
=> [video_player_platform_interface] Fix some pedantic lints

analysis_options.yaml, pubspec.yaml
Even non breaking upgrades to package:pedantic can unexpectedly break
our CI based on new linter rules affecting our codebase. Lock our
analysis to a specific ruleset instead.
=> [none] Lock pedantic version

script/incremental_build.sh
This passes our currently failing plugins through to
flutter_plugin_tools to adjust to flutter/plugin_tools#75.
DO NOT MERGE until flutter/plugin_tools#75 has been merged and
published.
flutter/flutter#45440
[CLA]: …
=> [none] Pass --custom-analysis flag through CI

script/incremental_build.sh
Should resolve a simple build warning during CI.
=> adds missing [[ to elif statement in scripts/incremental_build.sh

packages/camera/CHANGELOG.md, packages/camera/example/lib/main.dart, packages/camera/pubspec.yaml
I did some automation tools, and find camera example may have null exception.
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building CameraExampleHome(dirty, state: _CameraExampleHomeState#5438f):
The getter 'isEmpty' was called on null.
Receiver: null
Tried calling: isEmpty
The relevant error-causing widget was: 
CameraExampleHome
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _CameraExampleHomeState._cameraTogglesRowWidget (package:camera_example/main.dart:249:17)
#2      _CameraExampleHomeState.build (package:camera_example/main.dart:111:17)
#3      StatefulElement.build …
```
=> [camera] Resolve example null exception

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapBuilder.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapOptionsSink.java, packages/google_maps_flutter/example/test_driver/google_map_inspector.dart, packages/google_maps_flutter/example/test_driver/google_maps_e2e.dart, packages/google_maps_flutter/ios/Classes/GoogleMapController.h, packages/google_maps_flutter/ios/Classes/GoogleMapController.m, packages/google_maps_flutter/lib/src/google_map.dart, packages/google_maps_flutter/pubspec.yaml, packages/google_maps_flutter/test/fake_maps_controllers.dart, packages/google_maps_flutter/test/google_map_test.dart
- Adds missing property `buildingsEnabled` to the Google Maps Flutter plugin.
[iOS SDK Reference](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view.html#a0167011861fb75c6e8103afe15ac9a37)
> (BOOL) buildingsEnabled [read, write, assign]
> If set, 3D buildings will be shown where available.
>
> Defaults to YES.
> This may be useful when adding a custom tile layer to the map, in order to make it clearer at high > zoom levels. Changing this value will cause all tiles to be briefly invalidated.
None
Does your PR require plugin users to manually update their apps to accommodate …
=> [google_maps_flutter] Adds support for BuildingsEnabled property

.cirrus.yml
To enable using new Flutter features closely before a new release we're temporarily disabling CI on stable.
https://github.com/flutter/flutter/issues/46258 for re-enabling.
cc @jmagman this conflicts with https://github.com/flutter/plugins/pull/2357, we need to disable stable ASAP to unblock endorsing web plugins,  not sure how close is the other PR to landing I'm ok with waiting for the other PR first (or @jmagman if you can land i#2357 with stable disabled already 😄 ).
cc @collinjackson
=> Temporarily disable CI on stable Flutter

.cirrus.yml
Continuation of https://github.com/flutter/plugins/pull/2367 to enable publishing macos plugins with the new pubspec formats.
=> Disable stable for check publish

packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/android/.gitignore, packages/url_launcher/url_launcher_web/android/build.gradle, packages/url_launcher/url_launcher_web/android/gradle.properties, packages/url_launcher/url_launcher_web/android/gradle/wrapper/gradle-wrapper.properties, packages/url_launcher/url_launcher_web/android/settings.gradle, packages/url_launcher/url_launcher_web/android/src/main/AndroidManifest.xml, packages/url_launcher/url_launcher_web/android/src/main/java/io/flutter/url_launcher_web/UrlLauncherWebPlugin.java, packages/url_launcher/url_launcher_web/pubspec.yaml
A bug is preventing applications that use federated web plugins to build for Android.
This is working around that bug by adding an android/ folder with a no-op implementation.
https://github.com/flutter/flutter/issues/46304
=> [url_launcher_web] Add a no-op android/ folder

packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml, packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/pubspec.yaml
This is the minimal Flutter version required for the plugin platforms manifest.
=> [url_launcher_web] bump the minimal flutter requirement to 1.10.0

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/example/web/index.html, packages/video_player/video_player/pubspec.yaml
This PR adds default support for web to the video_player plugin.
It also adds a minimal `web` example, so the example can be run through `flutter run -d chrome`.
* https://github.com/flutter/flutter/issues/46669
[CLA]: …
=> [video_player] Endorse web implementation.

.cirrus.yml
When all plugins are release at once there will be a tag for each of the plugins but each tag will again test all plugins which makes it not optimal.
Discussion on Discord with @amirh 
[CLA]: …
=> [skip ci] don't run Cirrus on tags

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher/test/url_launcher_test.dart, packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml, packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart, script/check_publish.sh
Replace the current mechanism for protecting against implements with the common PlatformInterface class from the plugin_platform_interface package.
Update the unit test to work with the newly used PlatformInterface.
To keep CI green this includes a path dependency override.
This change is going to land and publish with the following sequence:
1. land this PR
2. publish url_launcher_platform_interface
3. land a PR to remove the dependency override from url_launcher, bump it's dependency on url_launcher_platform_interface, and re-enable the publish check for url_launcher
4. publish url_launcher
https://github.com/flutter/flutter/issues/43368
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth …
=> [url_launcher] Use the common PlatformInterface functionality

packages/url_launcher/url_launcher_macos/CHANGELOG.md, packages/url_launcher/url_launcher_macos/android/.gitignore, packages/url_launcher/url_launcher_macos/android/build.gradle, packages/url_launcher/url_launcher_macos/android/gradle.properties, packages/url_launcher/url_launcher_macos/android/gradle/wrapper/gradle-wrapper.properties, packages/url_launcher/url_launcher_macos/android/settings.gradle, packages/url_launcher/url_launcher_macos/android/src/main/AndroidManifest.xml, packages/url_launcher/url_launcher_macos/android/src/main/java/io/flutter/plugins/url_launcher_macos/UrlLauncherMacosPlugin.java, packages/url_launcher/url_launcher_macos/pubspec.yaml
Adding an `android/` folder as a temporary mitigation for:
https://github.com/flutter/flutter/issues/46304
https://github.com/flutter/flutter/issues/46790
=> [url_launcher_macos] add a no-op android implementation

packages/google_sign_in/google_sign_in_web/CHANGELOG.md, packages/google_sign_in/google_sign_in_web/android/build.gradle, packages/google_sign_in/google_sign_in_web/android/gradle.properties, packages/google_sign_in/google_sign_in_web/android/gradle/wrapper/gradle-wrapper.properties, packages/google_sign_in/google_sign_in_web/android/settings.gradle, packages/google_sign_in/google_sign_in_web/android/src/main/AndroidManifest.xml, packages/google_sign_in/google_sign_in_web/android/src/main/java/io/flutter/plugins/google_sign_in_web/GoogleSignInWebPlugin.java, packages/google_sign_in/google_sign_in_web/pubspec.yaml
=> [google_sign_in_web] Add a no-op Android implementation

packages/shared_preferences/shared_preferences_macos/CHANGELOG.md, packages/shared_preferences/shared_preferences_macos/android/.gitignore, packages/shared_preferences/shared_preferences_macos/android/build.gradle, packages/shared_preferences/shared_preferences_macos/android/gradle.properties, packages/shared_preferences/shared_preferences_macos/android/gradle/wrapper/gradle-wrapper.properties, packages/shared_preferences/shared_preferences_macos/android/settings.gradle, packages/shared_preferences/shared_preferences_macos/android/src/main/AndroidManifest.xml, packages/shared_preferences/shared_preferences_macos/android/src/main/java/io/flutter/plugins/shared_preferences_macos/SharedPreferencesMacosPlugin.java, packages/shared_preferences/shared_preferences_macos/example/android/gradle.properties, packages/shared_preferences/shared_preferences_macos/pubspec.yaml, packages/shared_preferences/shared_preferences_web/CHANGELOG.md, packages/shared_preferences/shared_preferences_web/android/.gitignore, packages/shared_preferences/shared_preferences_web/android/build.gradle, packages/shared_preferences/shared_preferences_web/android/gradle.properties, packages/shared_preferences/shared_preferences_web/android/gradle/wrapper/gradle-wrapper.properties, packages/shared_preferences/shared_preferences_web/android/settings.gradle, packages/shared_preferences/shared_preferences_web/android/src/main/AndroidManifest.xml, packages/shared_preferences/shared_preferences_web/android/src/main/java/io/flutter/plugins/shared_preferences_web/SharedPreferencesWebPlugin.java, packages/shared_preferences/shared_preferences_web/pubspec.yaml
Adding an android/ folder as a temporary mitigation for: https://github.com/flutter/flutter/issues/46898
=> [shared_preferences] add a no-op android folder to web/macos packages

packages/url_launcher/url_launcher_macos/android/build.gradle, packages/url_launcher/url_launcher_macos/android/gradle.properties, packages/url_launcher/url_launcher_macos/android/src/main/java/io/flutter/plugins/url_launcher_macos/UrlLauncherMacosPlugin.java, packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/android/build.gradle, packages/url_launcher/url_launcher_web/android/gradle.properties, packages/url_launcher/url_launcher_web/android/src/main/java/io/flutter/url_launcher_web/UrlLauncherWebPlugin.java, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/video_player/video_player_web/android/build.gradle, packages/video_player/video_player_web/android/gradle.properties, packages/video_player/video_player_web/android/src/main/java/io/flutter/plugins/video_player_web/VideoPlayerWebPlugin.java
Removes androidx references from no-op android implementations for: url_launcher_macos, url_launcher_web, and video_player web.
Only url_launcher_web gets a version bump as the others weren't published yet.
https://github.com/flutter/flutter/issues/46898
=> Remove AndroidX references from no-op android implementations

packages/e2e/CHANGELOG.md, packages/e2e/README.md, packages/e2e/example/ios/Runner.xcodeproj/project.pbxproj, packages/e2e/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/e2e/example/ios/RunnerTests/Info.plist, packages/e2e/example/ios/RunnerTests/RunnerTests.m, packages/e2e/ios/Classes/E2EIosTest.h, packages/e2e/ios/Classes/E2EIosTest.m, packages/e2e/ios/Classes/E2EPlugin.h, packages/e2e/ios/Classes/E2EPlugin.m, packages/e2e/ios/e2e.podspec, packages/e2e/pubspec.yaml
* Updates iOS E2EPlugin and add skeleton iOS test case E2EIosTest.
* Adds instructions to README.md about e2e testing on iOS device.
* Applies iOS e2e to example.
- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs. …
=> [e2e] Creates basic support/documentation/example to iOS.

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart, packages/webview_flutter/ios/Classes/FlutterWebView.m, packages/webview_flutter/lib/platform_interface.dart, packages/webview_flutter/lib/src/webview_method_channel.dart, packages/webview_flutter/lib/webview_flutter.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/test/webview_flutter_test.dart
This introduces a boolean for the allowsBackForwardNavigationGestures setting of the WKWebView in iOS. It has no effect on Android.
=> [webview_flutter] add gesture navigation for iOS

packages/plugin_platform_interface/CHANGELOG.md, packages/plugin_platform_interface/README.md, packages/plugin_platform_interface/lib/plugin_platform_interface.dart, packages/plugin_platform_interface/pubspec.yaml, packages/plugin_platform_interface/test/plugin_platform_interface_test.dart
Platform interface tokens must be unique, we've mistakenly used const Objects as a token (and all const Objects are identical).
Thanks @buntagonalprism for noticing and investigating!
We should probably follow-up with the PlatformInterface forcing tokens that are not const Objects (though this will be a breaking change).
I'm not sure whether we can test the failing scenario as it will require running tests in release mode.
https://github.com/flutter/flutter/issues/46941
=> [plugin_platform_interface] Don't use const Object as a token

packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml
See: https://github.com/flutter/plugins/pull/2417
=> [url_launcher] use non static token for platform interface

packages/ios_platform_images/CHANGELOG.md, packages/ios_platform_images/ios/Classes/IosPlatformImagesPlugin.m, packages/ios_platform_images/lib/ios_platform_images.dart, packages/ios_platform_images/pubspec.yaml
Fixed an issue where ios_platform_images wouldn't load images at different scales correctly.
=> [ios_platform_images] Made ios_platform_images set the correct image scale.

packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/lib/google_sign_in.dart, packages/google_sign_in/google_sign_in/pubspec.yaml
The param exists in the platform interface but there was no way to pass anything to clientId through the external interface.
=> [google_sign_in] Pass the client id to the platform interface.

.cirrus.yml
Stable CI was temporarily disabled waiting for the next stable release, now that it's out re-enabling.
https://github.com/flutter/flutter/issues/46258
=> re-enable stable CI

packages/ios_platform_images/CHANGELOG.md, packages/ios_platform_images/pubspec.yaml
Pub was listing android as a supported platform even though the implementation just throws an error.  I removed Android support from the pubspec.
=> Removed android support from the pubspec.

packages/connectivity/CHANGELOG.md, packages/connectivity/pubspec.yaml, packages/connectivity/test/connectivity_test.dart, packages/sensors/CHANGELOG.md, packages/sensors/pubspec.yaml, packages/sensors/test/sensors_test.dart, packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/test/webview_flutter_test.dart
Migrate away from the deprecated `BinaryMessages` to its supported replacement, `ServicesBinding.instance.defaultBinaryMessenger`.
Fixes https://github.com/flutter/flutter/issues/33446
[CLA]: …
=> Migrate away from deprecated `BinaryMessages`

.cirrus.yml
Upgrade to the latest Xcode 11.3
=> [ci] Upgrade to Xcode 11.3

packages/android_alarm_manager/CHANGELOG.md, packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/FlutterBackgroundExecutor.java, packages/android_alarm_manager/pubspec.yaml
If callback lookup was attempted before Flutter was initialized, the callback cache would not yet be populated resulting in a failed callback lookup.
Fixes https://github.com/flutter/flutter/issues/47406
=> [android_alarm_manager] Fixed issue where callback lookup was failing in the background

packages/google_sign_in/google_sign_in_web/CHANGELOG.md, packages/google_sign_in/google_sign_in_web/README.md, packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart, packages/google_sign_in/google_sign_in_web/pubspec.yaml, packages/google_sign_in/google_sign_in_web/test/auth2_test.dart, packages/google_sign_in/google_sign_in_web/test/gapi_load_test.dart, packages/google_sign_in/google_sign_in_web/test/gapi_mocks/gapi_mocks.dart, packages/google_sign_in/google_sign_in_web/test/gapi_mocks/src/auth2_init.dart, packages/google_sign_in/google_sign_in_web/test/gapi_mocks/src/gapi_load.dart
The Auth object that `.init()` returns may not be fully ready by the time we start calling methods on it; however it has a `.then()` method that gets called when it is *really* ready to go.
* Add a completer to signal when Auth2 is ready.
* Move auth2-dependent init to the `then` method.
* onSuccess, complete the auth2 ready future.
* onError, throw a PlatformException. This is normally triggered when the domain:port of the web app hasn't been whitelisted on the google sign in console, and things like that. Useful for debugging.
* https://github.com/flutter/flutter/issues/48527
* https://github.com/flutter/flutter/issues/47832
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick …
=> [google_sign_in_web] Fix race condition on init.

packages/camera/CHANGELOG.md, packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java, packages/camera/android/src/test/java/io/flutter/plugins/camera/CameraPermissionsTest.java, packages/camera/pubspec.yaml
Our listeners are called for every single permissions change, not just
the first one. This resulted in multiple replies being sent to Dart and
fatal crashes. Change to instead manually keep track of responses and
only respond to the first call.
Fixes flutter/flutter#26228 …
=> [camera] Fix crash from changing permissions

CODEOWNERS
Removes @collinjackson from path_provider, quick_actions, shared_preferences since I'm not currently focusing on these.
Adds @collinjackson and @adazh to new package espresso.
Renames instrumentation_adapter to e2e.
=> Updates CODEOWNERS

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/ios/Classes/FlutterWebView.h, packages/webview_flutter/ios/Classes/FlutterWebView.m, packages/webview_flutter/ios/Tests/FLTWebViewTests.m, packages/webview_flutter/pubspec.yaml
IOS sometimes updates the contentInset of the scroll view (for example to incorporate the keyboard) when the frame of the WebView changes.
The contentInset of the scrollview should be reverted to 0 after changing the view's frame so it doesn't interfere with Flutter.
This PR also fixes the XCTest test cases to follow XCTest's naming conventions.
Fixes https://github.com/flutter/flutter/issues/45482 …
=> [webview_flutter] always make sure the contentInset or the sum of contentInset and adjustedContentInset is 0 on iOS.

.gitignore, packages/connectivity/example/macos/Runner.xcworkspace/contents.xcworkspacedata, packages/connectivity/example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, packages/e2e/example/macos/Runner.xcworkspace/contents.xcworkspacedata, packages/e2e/example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, packages/path_provider/example/macos/Runner.xcworkspace/contents.xcworkspacedata, packages/path_provider/example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, packages/shared_preferences/shared_preferences/example/macos/Runner.xcworkspace/contents.xcworkspacedata, packages/shared_preferences/shared_preferences/example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, packages/shared_preferences/shared_preferences_macos/example/macos/Runner.xcworkspace/contents.xcworkspacedata, packages/shared_preferences/shared_preferences_macos/example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, packages/url_launcher/url_launcher/example/macos/Runner.xcworkspace/contents.xcworkspacedata, packages/url_launcher/url_launcher/example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, packages/url_launcher/url_launcher_macos/example/macos/Runner.xcworkspace/contents.xcworkspacedata, packages/url_launcher/url_launcher_macos/example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
A previous PR incorrectly added *.xcworkspace to the repository's
top-level .gitignore, causing all examples added after that
point--notably the addition of macOS to the examples--to incorrectly
omit the necessary Runner.xcworkspace.
This removes the incorrect .gitignore entry, and adds the missing
workspaces.
None …
=> Add missing Xcode workspaces to examples

packages/image_picker/CHANGELOG.md, packages/image_picker/example/android/app/build.gradle, packages/image_picker/example/android/gradle.properties, packages/image_picker/pubspec.yaml
Fixes CI
Fixes https://github.com/flutter/flutter/issues/48943
Maven has changed their access policies as of today: https://support.sonatype.com/hc/en-us/articles/360041287334
The old version of roboelectric is refering to http resources in its POM.  This one is good.
@amirh
=> Bump roboelectric version

packages/shared_preferences/shared_preferences_macos/CHANGELOG.md, packages/shared_preferences/shared_preferences_macos/android/gradle/wrapper/gradle-wrapper.properties, packages/shared_preferences/shared_preferences_macos/pubspec.yaml, packages/shared_preferences/shared_preferences_web/CHANGELOG.md, packages/shared_preferences/shared_preferences_web/android/gradle/wrapper/gradle-wrapper.properties, packages/shared_preferences/shared_preferences_web/pubspec.yaml
Fixes gradle version for shared preferences (macos, web) bug on android
For some reason the version of gradle inside the android folders of the "sub packages" is different than the real one on the real `shared_preferences` plugin.
Even though my project only depends on the main package, I get an error when I try to run it:
```
FAILURE: Build failed with an exception.
* Where:
Build file '<...>/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+2/android/build.gradle' line: 22
* What went wrong:
A problem occurred evaluating root project 'shared_preferences_web'.
> Failed to apply plugin [id 'com.android.library']
> Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in …
```
=> [shared_preferences] Fixes gradle version for shared preferences (macos, web) bug on android

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/example/lib/main.dart, packages/in_app_purchase/pubspec.yaml
The usage example of in-app-purchase contained a few changes for testing purposes that were not meant to be merged to the main code.
flutter/flutter#49083
=> [In_app_purchases] Removing extra testing changes for in-app-purchase example

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/README.md, packages/video_player/video_player/example/.gitignore, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/README.md, packages/video_player/video_player_web/lib/video_player_web.dart, packages/video_player/video_player_web/pubspec.yaml, packages/video_player/video_player_web/test/video_player_web_test.dart
When `videoElement.onError` triggers, we create a `PlatformException` with data coming from the `videoElement.error` object, and add it as an error to the `eventController` Stream.
Before this change, the `Event` passed in to `onError` was passed directly to the Stream (but listeners at the other end are expecting a PlatformException.)
The PR also returns the Future coming from `videoElement.play()` up the stack, so it can be handled properly (especially when it errors). This was causing issues in tests, when that unhandled Future would error unexpectedly.
This also updates the documentation for both `video_player` and `video_player_web` with regards to installation and browser support.
Fixes: https://github.com/flutter/flutter/issues/48884
Before you create this PR confirm that it meets …
=> [video_player, video_player_web] PlatformException fix

packages/espresso/CHANGELOG.md, packages/espresso/example/lib/main.dart, packages/espresso/pubspec.yaml, packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/example/lib/main.dart, packages/in_app_purchase/pubspec.yaml
This PR fixes the CI errors that says some example apps are using deprecated API on master.
We can land this on error if there are no other new errors introduced in this PR.
=> Fix ci error: deprecated api

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/README.md, packages/google_maps_flutter/pubspec.yaml
This PR replaces `UIApplicationLaunchOptionsKey` with `UIApplication.LaunchOptionsKey` in example for swift because first one doesn't longer work due to https://github.com/flutter/flutter/pull/35763
Here is a description of compile error which occurs when using `UIApplicationLaunchOptionsKey`:
https://stackoverflow.com/questions/59365426/flutter-google-maps-ios-build-fail
=> [google_maps_flutter] fix swift example in readme

.github/workflows/branch-guard.yml
This should add a presubmit that's block PR from landing while the tree is red.
https://github.com/flutter/flutter/issues/28921
=> Configure Cirrus Branch Guard

packages/connectivity/ios/Classes/FLTConnectivityPlugin.m, packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java, packages/google_maps_flutter/example/lib/map_ui.dart, packages/google_maps_flutter/example/test_driver/google_maps_e2e.dart, packages/google_maps_flutter/pubspec.yaml
Toggling the traffic layer for a google map on Android wouldn't update the map. The map now get's updated.
flutter/flutter#47895
flutter/flutter#43740
flutter/flutter#42346
=> [google_maps_flutter] Fixes toggling traffic layer not working on Android

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java, packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart, packages/webview_flutter/ios/Classes/FlutterWebView.h, packages/webview_flutter/ios/Classes/FlutterWebView.m, packages/webview_flutter/pubspec.yaml
Right now, flutter webview on Android will open href's with target="_blank", but iOS will not. This PR fixes this.
https://github.com/flutter/flutter/issues/28875
=> [webview_flutter] Fix iOS WebView not opening href with target="_blank"

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart, packages/in_app_purchase/pubspec.yaml, packages/in_app_purchase/test/billing_client_wrappers/purchase_wrapper_test.dart, packages/in_app_purchase/test/store_kit_wrappers/sk_product_test.dart
When purchasing the _pendingCompletePurchase flag is always set to false as we were not using the setter that was setting _pendingCompletePurchase to true when purchasing status was true.
flutter/flutter#49083
[CLA]: …
=> [in_app_purchase] Fix wrong _pendingCompletePurchase flag value

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/README.md, packages/google_maps_flutter/pubspec.yaml
People seem to have trouble stepping up Google Map SDKs(issue here: https://github.com/flutter/flutter/issues/30649). We should make our set up guide clearer.
=> [google_maps_flutter] Add steps to set up google map sdk on each platform in readme.

packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/android/build.gradle, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/CircleBuilder.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/CircleController.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/CirclesController.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/PolygonBuilder.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/PolygonController.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/PolygonsController.java, packages/google_maps_flutter/android/src/test/java/io/flutter/plugins/googlemaps/CircleBuilderTest.java, packages/google_maps_flutter/android/src/test/java/io/flutter/plugins/googlemaps/CircleControllerTest.java, packages/google_maps_flutter/android/src/test/java/io/flutter/plugins/googlemaps/PolygonBuilderTest.java, packages/google_maps_flutter/android/src/test/java/io/flutter/plugins/googlemaps/PolygonControllerTest.java, packages/google_maps_flutter/android/src/test/java/io/flutter/plugins/googlemaps/PolylineBuilderTest.java, packages/google_maps_flutter/android/src/test/java/io/flutter/plugins/googlemaps/PolylineControllerTest.java, packages/google_maps_flutter/android/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, packages/google_maps_flutter/pubspec.yaml
Stroke width of Polygon and Circles on Android is not independent of the screen density
flutter/flutter#39476
- [-] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
=> [google_maps_flutter] Fix circle and polygon stroke width

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java, packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/MethodCallHandlerImpl.java, packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/MethodCallHandlerTest.java, packages/in_app_purchase/example/lib/main.dart, packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart, packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
Fixes a bug that the plugin disconnect the billing client at an inappropriate place. Also fixed some minor compiling warnings.
https://github.com/flutter/flutter/issues/33210
=> [in_app_purchases] Android: make sure properly disconnect the billing client object.

packages/e2e/CHANGELOG.md, packages/e2e/example/pubspec.yaml, packages/e2e/example/test_driver/failure_e2e.dart, packages/e2e/example/test_driver/failure_e2e_test.dart, packages/e2e/pubspec.yaml
Adds a skipped integration test for flutter/flutter#48601.
Will be fixed by https://github.com/flutter/plugins/pull/2465
Note: Right now the plugins CI only runs e2e driver tests on iOS. However, this should be sufficient to exercise the fix for flutter/flutter#48601.
https://github.com/flutter/flutter/issues/48601
=> [e2e] Test multiple failure behavior

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/pubspec.yaml
As the Flutter SDK does not follow semver, an upper bound has no semantic meaning.
Using this plugin as a canary to check if anything breaks when we remove this bound.
=> [webview_flutter] Remove the upper bound from the Flutter SDK constraint

packages/connectivity/connectivity_platform_interface/CHANGELOG.md, packages/connectivity/connectivity_platform_interface/README.md, packages/connectivity/connectivity_platform_interface/lib/connectivity_platform_interface.dart, packages/connectivity/connectivity_platform_interface/pubspec.yaml
Fix README broken link and removes unnecessary TODO comment.
=> [connectivity_platform_interface] Fix README

AUTHORS, packages/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/MarkerController.java, packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/MarkersController.java, packages/google_maps_flutter/example/test_driver/google_maps_e2e.dart, packages/google_maps_flutter/ios/Classes/GoogleMapController.m, packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.h, packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.m, packages/google_maps_flutter/lib/src/controller.dart, packages/google_maps_flutter/pubspec.yaml
I needed to programmatically show marker's infowindow when a user tapped a polyline, so i've implemented those method and i'm currently using them and trying to maintain my repo current with this one.
I want a opinion on this implementation, because i don't think it's the optimal. I've tried to use a method channel for each `Marker` so i would be able to call `marker.showInfoWindow()`, but i can't create method channel's on the fly. 
flutter/flutter#29899
flutter/flutter#33481
flutter/flutter#19647 …
=> [google_maps_flutter] Add methods to programmatically show/hide marker's infowindow

CODEOWNERS
Add matthew-carroll to reviewers
=> Add matthew-carroll to reviewers

script/build_all_plugins_app.sh
Includes `connectivity_platform_interface` `connectivity_macos` `connectivity_web` to avoid build failures caused by path dependencies.
https://github.com/flutter/flutter/issues/46307
=> Exclude connectivity packages

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/example/test_driver/google_maps_e2e.dart, packages/google_maps_flutter/google_maps_flutter/lib/src/controller.dart, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Added getZoomLevel method to the Google map controller
It was implemented in the ios and android side but not yet exposed
None
=> [google_maps_flutter] getZoomLevel for map controller

analysis_options.yaml, packages/camera/CHANGELOG.md, packages/camera/example/pubspec.yaml, packages/camera/pubspec.yaml, packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/example/pubspec.yaml, packages/in_app_purchase/pubspec.yaml, pubspec.yaml
The `./pubspec.yaml` doesn't ensure dependency for individual plugins. The `./pubspec.yaml` is not used anywhere, this PR remove the file.
`camera` and `in_app_purchase` needs to depend on `pedantic` because they implement custom rules which overrides the `./analysis_options.yaml`.
https://github.com/flutter/flutter/issues/45440 …
=> [camera][in_app_purchase] Fix pedantic dependency. Remove `pubspec.yaml` in root folder.

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m, packages/video_player/video_player/pubspec.yaml
For add-to-app users of video_player, the plugin doesn't clean up its resources, like it's display link which causes a crash.  This handles the event that we are detaching the plugin and cleans everything up as a result.
https://github.com/flutter/flutter/issues/50761 …
=> [video_player] Made the video_player clean up after itself on iOS.

packages/e2e/CHANGELOG.md, packages/e2e/README.md, packages/e2e/pubspec.yaml
The readme documentation has for the `e2e` package has a code snippet on how to create a test using Flutter driver. Copying the code snippet there doesn't work as it is incomplete due to missing imports and doesn't declare a variable that is referenced later on.
=> [e2e] fix flutter driver code snippet in readme and improve formatting of code snippets

packages/path_provider/path_provider_macos/lib/path_provider.dart, packages/path_provider/path_provider_platform_interface/CHANGELOG.md, packages/path_provider/path_provider_platform_interface/LICENSE, packages/path_provider/path_provider_platform_interface/README.md, packages/path_provider/path_provider_platform_interface/lib/path_provider_platform_interface.dart, packages/path_provider/path_provider_platform_interface/lib/src/enums.dart, packages/path_provider/path_provider_platform_interface/lib/src/method_channel_path_provider.dart, packages/path_provider/path_provider_platform_interface/pubspec.yaml, packages/path_provider/path_provider_platform_interface/test/method_channel_path_provider_test.dart
Creates a platform_interface for path_provider. Second step for federation outlined in https://github.com/flutter/flutter/issues/46307#issuecomment-589301237
https://github.com/flutter/flutter/issues/46307
=> [path_provider] Create platform interface

script/build_all_plugins_app.sh
Includes `path_provider_platform_interface` `path_provider_macos` `path_provider_web` to avoid build failures caused by path dependencies.
https://github.com/flutter/flutter/issues/46307
=> Exclude path_provider packages

packages/connectivity/connectivity_platform_interface/CHANGELOG.md, packages/connectivity/connectivity_platform_interface/lib/src/enums.dart, packages/connectivity/connectivity_platform_interface/lib/src/utils.dart, packages/connectivity/connectivity_platform_interface/pubspec.yaml
Some platforms might not be able to determine the connectivity status of
the device on which the app is running (like some desktop Web browsers).
This allows users of the `connectivity` plugin to distinguish between
"no connectivity" and "connectivity couldn't be determined".
This requires a Major Version bump for users of the plugin who may be
switch/case on ConnectivityResult values, since Dart forces users to be
exhaustive in those cases (if they don't have a "default" entry, this
new value becomes a compilation error in their code).
This will also cause a Major Version bump in the core `connectivity`
plugin itself. This change will happen in a separate PR.
Needed for: https://github.com/flutter/plugins/pull/2545
Before you create this PR confirm that it meets all requirements listed …
=> [connectivity_platform_interface] Add `ConnectivityResult.unknown`.

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/example/lib/main.dart, packages/url_launcher/url_launcher/example/pubspec.yaml, packages/url_launcher/url_launcher/example/test/url_launcher_example_test.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher_macos/CHANGELOG.md, packages/url_launcher/url_launcher_macos/example/lib/main.dart, packages/url_launcher/url_launcher_macos/pubspec.yaml
updated _launchUniversalLinkIos  to launch the url passed. It could also be done that we remove the url argument passed and open the hardcoded url. Either of the case needs to be done.
[CLA]: …
=> [url_launcher] fix: url_launcher - updated _launchUniversalLinkIos and Added Tests

packages/path_provider/path_provider_platform_interface/CHANGELOG.md, packages/path_provider/path_provider_platform_interface/lib/path_provider_platform_interface.dart, packages/path_provider/path_provider_platform_interface/lib/src/enums.dart, packages/path_provider/path_provider_platform_interface/lib/src/method_channel_path_provider.dart, packages/path_provider/path_provider_platform_interface/pubspec.yaml, packages/path_provider/path_provider_platform_interface/test/method_channel_path_provider_test.dart
Rename back for backwards compatibility
=> [path_provider_platform_interface] Rename back to StorageDirectory 

packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/pubspec.yaml
Remove unused plugin class name
=> [path_provider] Remove plugin class

packages/device_info/CHANGELOG.md, packages/device_info/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java, packages/device_info/android/src/main/java/io/flutter/plugins/deviceinfo/MethodCallHandlerImpl.java, packages/device_info/example/lib/main.dart, packages/device_info/lib/device_info.dart, packages/device_info/pubspec.yaml
There's a variety of scenarios where checking at runtime which system
features are available is useful.  System features are device
capabilities that do not change at runtime (for example, FEATURE_BLUETOOTH
is always present if the device has a bluetooth radio, even if Bluetooth
is presently disabled), so DeviceInfo seems like the right place to put
this.
N/A …
=> [device_info] add PackageManager's SystemFeatures to AndroidDeviceInfo

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, packages/webview_flutter/pubspec.yaml
The workspace setting was somehow checked in which forced local machine to use the legacy build setting. It makes building the example app fail on some system.
=> [webview_flkutter] remove  ios workspace setting

packages/android_intent/CHANGELOG.md, packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/IntentSender.java, packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/MethodCallHandlerImpl.java, packages/android_intent/android/src/test/java/io/flutter/plugins/androidintent/MethodCallHandlerImplTest.java, packages/android_intent/lib/android_intent.dart, packages/android_intent/pubspec.yaml, packages/android_intent/test/android_intent_test.dart
Android Intents can also be constructed with just the component name like so:
```
final Intent intent = new Intent();
intent.setComponent(componentName);
context.startActivity(intent);
```
Effectively, if the developer knows the target component, it can be called directly.
Preparation work for https://github.com/flutter/flutter/issues/51942, which adds a "canResolve" method.
[Flutter …
=> [android_intent] Make action optional, as Intents can also resolve with just the component name

packages/e2e/CHANGELOG.md, packages/e2e/README.md, packages/e2e/android/src/main/java/dev/flutter/plugins/e2e/FlutterRunner.java, packages/e2e/android/src/main/java/dev/flutter/plugins/e2e/FlutterTestRunner.java, packages/e2e/example/android/app/src/androidTest/java/com/example/e2e_example/EmbedderV1ActivityTest.java, packages/e2e/example/android/app/src/androidTest/java/com/example/e2e_example/MainActivityTest.java, packages/e2e/pubspec.yaml
Fixes a flake where `FlutterRunner` didn't always launch properly.
Instead we are opting out of the Android test rule's auto-launch and having the runner do it manually.
Also renamed `FlutterRunner` to `FlutterTestRunner` to avoid conflict with Fuchsia.
=> Make FlutterRunner launch deterministic when running other tests.

packages/connectivity/connectivity/CHANGELOG.md, packages/connectivity/connectivity/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, packages/connectivity/connectivity/pubspec.yaml, packages/connectivity/connectivity_macos/CHANGELOG.md, packages/connectivity/connectivity_macos/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, packages/connectivity/connectivity_macos/pubspec.yaml
The workspace setting sets the ios example app to use the legacy build system, which is incompatible with cirrus. This patch fixes that.
=> [connectivity] remove ios workspace setting for example app.

packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md, packages/google_sign_in/google_sign_in_platform_interface/lib/google_sign_in_platform_interface.dart, packages/google_sign_in/google_sign_in_platform_interface/lib/src/method_channel_google_sign_in.dart, packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml, packages/google_sign_in/google_sign_in_platform_interface/test/method_channel_google_sign_in_test.dart
Adds two new methods, `hasGrantedScope` and `requestScope`, to the `GoogleSginInPlatform` class and the method channel implementation.
I have a second [branch](https://github.com/flutter/plugins/compare/master...emerssso:scope-apis-mobile) queued up for the implementations, but my understanding of the federated plugin design is that this has to be merged and pushed to pub first?
* flutter/flutter#50208 …
=> [google_sign_in] Add new Oauth scope methods to google_sign_in_platform_interface.

packages/battery/CHANGELOG.md, packages/battery/README.md, packages/battery/pubspec.yaml
Announce that the package is going to be compatible with 1.0.0 and encourage users to set their constraints accordingly.
@collinjackson @csells after we're happy with the wording here I'll apply it to more plugins we want to upgrade to 1.0.0
=> [battery] Announce API stability and compatibility with 1.0.0

packages/package_info/CHANGELOG.md, packages/package_info/README.md, packages/package_info/pubspec.yaml, packages/sensors/CHANGELOG.md, packages/sensors/README.md, packages/sensors/pubspec.yaml
Announce that the package is going to be compatible with 1.0.0 and encourage users to set their constraints accordingly.
This is similar to https://github.com/flutter/plugins/pull/2597
=> [package_info, sensors] Announce API stability and compatibility with 1.0.0

packages/android_alarm_manager/CHANGELOG.md, packages/android_alarm_manager/example/android/app/src/androidTest/java/io/plugins/androidalarmmanager/DriverExtensionActivity.java, packages/android_alarm_manager/example/android/app/src/androidTest/java/io/plugins/androidalarmmanager/MainActivityTest.java, packages/android_alarm_manager/pubspec.yaml
Following up https://github.com/flutter/plugins/commit/899744f38216ad4f8fed1bbd8126139d7d054c4c
The `MainActivity` was removed but there were still references left. 
fix ci.
=> [android_alarm_manager] remove MainActivity references 

packages/e2e/CHANGELOG.md, packages/e2e/README.md, packages/e2e/example/test_driver/example_e2e_test.dart, packages/e2e/example/test_driver/failure_test.dart, packages/e2e/lib/common.dart, packages/e2e/lib/e2e.dart, packages/e2e/lib/e2e_driver.dart, packages/e2e/pubspec.yaml
Adding failure details for driver tests.
**Before the change the failure output was something like:**
```
[+2616 ms] result fail
[  +88 ms] Stopping application instance.
[        ] Stopping application.
[   +2 ms] "flutter drive" took 22,861ms.
```
**The updated output:**
```
[+2782 ms] Failure Details:
[        ] Failure in method: verify text
[        ] ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
[   +1 ms] The following TestFailure object was thrown running a test:
[        ]   Expected: <3>
[        ]   Actual: <2>
[        ] When the exception was thrown, this was the stack:
[        ]     at Object.wrapException (http://localhost:36633/main.dart.js:3646:17)
[        ]     at Object.throwExpression (http://localhost:36633/main.dart.js:3659:15)
[        ]     at …
```
=> [e2e] Adding failure details for driver tests

AUTHORS, packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/lib/src/circle.dart, packages/google_maps_flutter/google_maps_flutter/lib/src/marker.dart, packages/google_maps_flutter/google_maps_flutter/lib/src/polygon.dart, packages/google_maps_flutter/google_maps_flutter/lib/src/polyline.dart, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter/test/circle_updates_test.dart, packages/google_maps_flutter/google_maps_flutter/test/marker_updates_test.dart, packages/google_maps_flutter/google_maps_flutter/test/polygon_updates_test.dart, packages/google_maps_flutter/google_maps_flutter/test/polyline_updates_test.dart
Currently, all attributes of map elements are taken into account when computing which one have changed and needs to be rebuilt. This causes changes in attributes that are not related to the platform (like `onTap` or `onDragEnd`) to trigger an unnecessary rebuild of the element. This is especially problematic as new instances of closures are often used in those handlers resulting in lots of unnecessary rebuilds.
This PR address that problem by ensuring attributes not related to the platform are ignored when comparing elements for change.
This PR reduces drastically performance problems explained in this issue:
https://github.com/flutter/flutter/issues/41731
However, this is only one part of the problem, so this issue still needs some love <3
Does your PR require plugin users to manually …
=> [google_maps_flutter] Avoid unnecessary map element updates (performance)

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/example/lib/animate_camera.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/main.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/map_click.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/map_coordinates.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/map_ui.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/marker_icons.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/move_camera.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/padding.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/page.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/place_circle.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/place_marker.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/place_polygon.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/place_polyline.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/scrolling_map.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/snapshot.dart, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
https://github.com/flutter/flutter/commit/a206bf7e2f3d64fb4453d87bad80f8e7acddcf0a introduced a `Page` API in the framework and it has conflicts with the example app of the plugin.
=> [google_maps_flutter] Rename 'Page' in the example app to avoid type conflict with the Flutter Framework.

packages/path_provider/path_provider/android/src/test/java/io/flutter/plugins/pathprovider/StorageDirectoryMapperTest.java
Fixes https://github.com/flutter/flutter/issues/53557
=> [path_provider] Fix misaligned enum values in StorageDirectoryMapperTest

script/build_all_plugins_app.sh
Includes `shared_preferences_windows` in the  to avoid build failures caused by path dependencies.
https://github.com/flutter/flutter/issues/44918
=> [scripts] Exclude shared_preferences_windows package

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java, packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart, packages/webview_flutter/ios/Classes/FLTWKNavigationDelegate.m, packages/webview_flutter/lib/platform_interface.dart, packages/webview_flutter/lib/src/webview_method_channel.dart, packages/webview_flutter/lib/webview_flutter.dart, packages/webview_flutter/pubspec.yaml
This adds the feature where the webview can report an error when loading page resources. 
After looking for error reporting in the `Webview` implementation of each platform I found Android uses [onReceivedError](https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedError(android.webkit.WebView,%20android.webkit.WebResourceRequest,%20android.webkit.WebResourceError)) in its `WebviewClient` and iOS uses [webView:didFailNavigation:withError:](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455623-webview?language=objc) and [webView:didFailProvisionalNavigation:withError:](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455637-webview?language=objc) in its `WKNavigationDelegate`. 
However, each platform handles error codes …
=> [webview_flutter] Add onReceivedError callback 

packages/e2e/CHANGELOG.md, packages/e2e/android/src/main/java/dev/flutter/plugins/e2e/FlutterTestRunner.java, packages/e2e/example/android/app/src/androidTest/java/com/example/e2e_example/MainActivityWithPermissionTest.java, packages/e2e/pubspec.yaml
Fixes the issue outlined in flutter/flutter#53660.
Fixes flutter/flutter#53660.
=> [e2e] Replaces the check for ActivityTestRule

packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/analysis_options.yaml, packages/video_player/video_player_web/pubspec.yaml, script/incremental_build.sh
flutter/plugins is currently red because inline analysis checks are no longer honored, as described here: https://github.com/flutter/flutter/issues/52899.
`video_player_web` used a web-only API that was being flagged (correctly) by the analyzer, but suppressed inline via `// ignore` comments.
Now that `// ignore` comments don't work, the tree has gone red.
The fix for `video_player_web` will take longer than acceptable to unblock the flutter/plugins tree, so we're putting this mitigation so work can continue normally.
This patch will be removed, once the affected APIs can be accessed without triggering analyzer errors.
* https://github.com/flutter/flutter/issues/52899
* https://github.com/flutter/flutter/issues/41563
Before you create this PR confirm that it meets all requirements listed …
=> [video_player_web] Add a custom analysis_options file to video_player_web.

packages/e2e/CHANGELOG.md, packages/e2e/android/src/main/java/dev/flutter/plugins/e2e/FlutterTestRunner.java, packages/e2e/example/android/app/src/androidTest/java/com/example/e2e_example/MainActivityWithPermissionTest.java, packages/e2e/pubspec.yaml
=> Reland: [e2e] Replaces the check for ActivityTestRule (#2633)

packages/google_sign_in/google_sign_in_web/CHANGELOG.md, packages/google_sign_in/google_sign_in_web/lib/src/utils.dart, packages/google_sign_in/google_sign_in_web/pubspec.yaml, packages/google_sign_in/google_sign_in_web/test/gapi_mocks/src/google_user.dart, packages/google_sign_in/google_sign_in_web/test/gapi_utils_test.dart
This change ensures that not signed-in users are returned as `null`, **not as an object with all its properties set to null!**
The core plugin assumes that a not-authenticated user is being returned as `null` from the platform code, but the web implementation is currently returning a null-object (as in [the pattern](https://en.wikipedia.org/wiki/Null_object_pattern)).
**WHY did the above prevented creating sign-in popups?**
Because of [this](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart#L291). The call to signIn is marked as `canSkipCall`, assuming that there's a non-null user known by the plugin, returning that directly.
In some cases, the user would never be properly cleared (or a null-User-object would be returned from the …
=> [google_sign_in_web] Ensure not-signed-in users are returned as `null`.

.cirrus.yml, packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/ios/Runner.xcodeproj/project.pbxproj, packages/webview_flutter/ios/Tests/FLTWebViewTests.m, packages/webview_flutter/pubspec.yaml
1. OCMock doesn't define a modulemap, so `@import` fails when the pod is generated as a library instead of a framework (without `use_frameworks!`).  Use `#import` instead of module `@import`.
2. [Migrate example project to support Xcode 11.4](https://flutter.dev/docs/development/ios-project-migration).
=> [webview_flutter] OCMock module import -> #import

.cirrus.yml
`pod repo update` is not needed as of [CocoaPods 1.8](http://blog.cocoapods.org/CocoaPods-1.8.0-beta/).  Remove from Cirrus scripts.
=> Remove out of date pod repo update from Cirrus

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java
Works around a crash in Android tablets running a Chromium version older than `67.0.3367.0`
Before [afb450](https://source.chromium.org/chromium/chromium/src/+/afb450fc02dfef4995a87c62b82d6cc0ed27be84?originalUrl=https%2F%2F:%2F%2F%2F%2Fcs.chromium.org%2F), on tablets Chromium used a `ListPopupWindow` to show select drop downs. `ListPoupWindow` is using `DropDownListView` which internally is using a [ListDropDownWindow](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/widget/DropDownListView.java#28), which partially hijacks view focus (most importantly it [overrides isFocused](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/widget/DropDownListView.java#337) to return true, which causes …
=> [webview_flutter] Workaround old Android tablets select drop down crash

packages/webview_flutter/pubspec.yaml
A recent `pub publish` check warns when requiring a non release Dart SDK, bumping the requirement so we don't get the warning.
This change is a no-op as the minimally required Flutter version (`1.12.13+hotfix.5`) already requires Dart `2.7.0`.
=> [webview_flutter] Bump the Dart SDK requirement to 2.7.0

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.h, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
As outlined in https://github.com/flutter/plugins/commit/821a5c4e761e55347452960a5b0568b6d5a915c5#r38618278, GoogleMapController shipped with an invalid method definition.
=> [google_maps_flutter] Removes setZoomControlsEnabled from GoogleMapController.h

packages/android_intent/CHANGELOG.md, packages/android_intent/ios/android_intent.podspec, packages/android_intent/pubspec.yaml
Fix android_intent pod lib lint warnings:
```
-> android_intent (0.3.7)
...
[!] android_intent did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [android_intent] Fix pod lint warnings

packages/android_alarm_manager/CHANGELOG.md, packages/android_alarm_manager/ios/android_alarm_manager.podspec, packages/android_alarm_manager/pubspec.yaml
Fix android_alarm_manager pod lib lint warnings:
```
-> android_alarm_manager (0.0.1)
...
[!] android_alarm_manager did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [android_alarm_manager] Fix pod lint warnings

packages/battery/CHANGELOG.md, packages/battery/ios/battery.podspec, packages/battery/pubspec.yaml
Fix battery pod lib lint warnings:
```
-> battery (0.0.1)
[!] battery did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [battery] Fix pod lint warnings

packages/connectivity/connectivity/CHANGELOG.md, packages/connectivity/connectivity/ios/connectivity.podspec, packages/connectivity/connectivity_macos/CHANGELOG.md, packages/connectivity/connectivity_macos/macos/connectivity_macos.podspec
Fix connectivity and connectivity_macos pod lib lint warnings:
```
-> connectivity (0.0.1)
...
[!] connectivity did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
```
-> connectivity_macos (0.0.1)
- WARN  | [OSX] swift: The validator used Swift `4.0` by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_versions` …
```
=> [connectivity] Fix pod lint warnings

packages/device_info/CHANGELOG.md, packages/device_info/ios/device_info.podspec, packages/device_info/pubspec.yaml
Fix device_info pod lib lint warnings:
```
-> device_info (0.0.1)
...
[!] device_info did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [device_info] Fix pod lint warnings

packages/espresso/CHANGELOG.md, packages/espresso/ios/espresso.podspec
Fix espresso pod lib lint warnings:
```
-> espresso (0.0.1)
...
[!] espresso did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [espresso] Fix pod lint warnings

packages/e2e/CHANGELOG.md, packages/e2e/e2e_macos/macos/e2e_macos.podspec, packages/e2e/ios/e2e.podspec
Fix e2e pod lib lint warnings:
```
-> e2e (0.0.1)
...
[!] e2e did not pass validation, due to 2 warnings (but you can use `--allow-warnings` to ignore them).
```
```
-> e2e_macos (0.0.1)
- WARN  | [OSX] file patterns: The `public_header_files` pattern did not match any file.
- WARN  | [OSX] swift: The validator used Swift `4.0` by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_versions` attribute in your podspec. Note that …
```
=> [e2e] Fix pod lint warnings

packages/flutter_plugin_android_lifecycle/CHANGELOG.md, packages/flutter_plugin_android_lifecycle/ios/flutter_plugin_android_lifecycle.podspec
Fix flutter_plugin_android_lifecycle pod lib lint warnings:
```
-> flutter_plugin_android_lifecycle (0.0.1)
...
[!] flutter_plugin_android_lifecycle did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [flutter_plugin_android_lifecycle] Fix pod lint warnings

packages/image_picker/CHANGELOG.md, packages/image_picker/ios/image_picker.podspec, packages/image_picker/pubspec.yaml
Fix image_picker pod lib lint warnings:
```
-> image_picker (0.0.1)
...
[!] image_picker did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [image_picker] Fix pod lint warnings

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/ios/in_app_purchase.podspec, packages/in_app_purchase/pubspec.yaml
Fix in_app_purchase pod lib lint warnings:
```
-> in_app_purchase (0.0.1)
...
[!] in_app_purchase did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [in_app_purchase] Fix pod lint warnings

packages/package_info/CHANGELOG.md, packages/package_info/ios/package_info.podspec
Fix package_info pod lib lint warnings:
```
-> package_info (0.0.1)
...
[!] package_info did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [package_info] Fix pod lint warnings

packages/ios_platform_images/CHANGELOG.md, packages/ios_platform_images/ios/ios_platform_images.podspec
Fix image_picker pod lib lint warnings:
```
-> ios_platform_images (0.0.1)
...
[!] ios_platform_images did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [ios_platform_images] Fix pod lint warnings

packages/local_auth/CHANGELOG.md, packages/local_auth/ios/Classes/FLTLocalAuthPlugin.m, packages/local_auth/ios/local_auth.podspec
Fix in_app_purchase implicit-retain-self warning and pod lib lint warnings:
```
-> local_auth (0.0.1)
- WARN  | [iOS] xcodebuild:  /Users/m/Projects/plugins/packages/local_auth/ios/Classes/FLTLocalAuthPlugin.m:117:33: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
- WARN  | [iOS] xcodebuild:  /Users/m/Projects/plugins/packages/local_auth/ios/Classes/FLTLocalAuthPlugin.m:118:33: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior …
```
=> [local_auth] Fix retain self warning and pod lint warnings

packages/sensors/CHANGELOG.md, packages/sensors/ios/sensors.podspec
Fix sensors pod lib lint warnings:
```
-> sensors (0.0.1)
...
[!] sensors did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [sensors] Fix pod lint warnings

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/ios/video_player.podspec
Fix video_player pod lib lint warnings:
```
-> video_player (0.0.1)
...
[!] video_player did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [video_player] Fix pod lint warnings

packages/share/CHANGELOG.md, packages/share/ios/share.podspec
Fix share pod lib lint warnings:
```
-> share (0.5.2)
...
[!] share did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [share] Fix pod lint warnings

packages/shared_preferences/shared_preferences/CHANGELOG.md, packages/shared_preferences/shared_preferences/ios/shared_preferences.podspec, packages/shared_preferences/shared_preferences_macos/CHANGELOG.md, packages/shared_preferences/shared_preferences_macos/macos/shared_preferences_macos.podspec, packages/shared_preferences/shared_preferences_macos/pubspec.yaml
Fix shared_preferences pod lib lint warnings:
```
-> shared_preferences_macos (0.0.1)
...
[!] shared_preferences_macos did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
```
-> shared_preferences (0.0.1)
...
[!] shared_preferences did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to …
```
=> [shared_preferences] Fix pod lint warnings

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/ios/url_launcher.podspec, packages/url_launcher/url_launcher_macos/CHANGELOG.md, packages/url_launcher/url_launcher_macos/macos/url_launcher_macos.podspec
Fix url_launcher pod lib lint warnings:
```
-> url_launcher_macos (0.0.1)
...
[!] url_launcher_macos did not pass validation, due to 2 warnings (but you can use `--allow-warnings` to ignore them).
```
```
-> url_launcher (0.0.1)
...
[!] url_launcher did not pass validation, due to 2 warnings (but you can use `--allow-warnings` to ignore them).
```
Before you create this PR …
=> [url_launcher] Fix pod lint warnings

packages/quick_actions/CHANGELOG.md, packages/quick_actions/ios/Classes/FLTQuickActionsPlugin.m, packages/quick_actions/ios/quick_actions.podspec
Fix quick_actions UIApplicationShortcutItem availability warnings, slightly cleaned up FLTQuickActionsPlugin (though [I'm not convinced this plugin is working](https://github.com/flutter/flutter/labels/p%3A%20quick_actions)). 
Also fix pod lib lint warnings:
```
-> quick_actions (0.0.1)
- WARN  | [iOS] xcodebuild:  /Users/m/Projects/plugins/packages/quick_actions/ios/Classes/FLTQuickActionsPlugin.m:44:35: warning: 'UIApplicationShortcutItem' is only available on iOS 9.0 or newer [-Wunguarded-availability]
- WARN  | [iOS] xcodebuild: …
```
=> [quick_actions] Fix UIApplicationShortcutItem availability and pod lint warnings

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.m, packages/google_maps_flutter/google_maps_flutter/ios/google_maps_flutter.podspec, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Fix google_maps_flutter UIKit availability warnings introduced in https://github.com/flutter/plugins/pull/2607.  Also fix pod lib lint warnings:
```
-> google_maps_flutter (0.0.1)
- WARN  | [iOS] xcodebuild:  /Users/m/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.m:176:7: warning: 'UIGraphicsImageRendererFormat' is only available on iOS 10.0 or newer [-Wunguarded-availability]
- WARN  | [iOS] xcodebuild:  /Users/m/Projects/plugins/packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.m:176:78: …
```
=> [google_maps_flutter] Fix UIKit availability and pod lint warnings

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/ios/webview_flutter.podspec, packages/webview_flutter/pubspec.yaml
Fix webview_flutter pod lib lint warnings:
```
-> webview_flutter (0.0.1)
...
[!] webview_flutter did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```
=> [webview_flutter] Fix pod lint warnings

packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/ios/path_provider.podspec, packages/path_provider/path_provider_macos/CHANGELOG.md, packages/path_provider/path_provider_macos/macos/path_provider_macos.podspec, packages/path_provider/path_provider_macos/pubspec.yaml
Fix path_provider pod lib lint warnings:
```
-> path_provider_macos (0.0.1)
...
[!] path_provider_macos did not pass validation, due to 4 warnings (but you can use `--allow-warnings` to ignore them).
```
```
-> path_provider (0.0.1)
...
[!] path_provider did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
``` …
=> [path_provider] Fix pod lint warnings

packages/local_auth/CHANGELOG.md, packages/local_auth/pubspec.yaml
When https://github.com/flutter/plugins/pull/2685 was [merged](https://github.com/flutter/plugins/commit/a0a39103c55ebf0a2d7f87c39f04ce6596774f07) the published version was 0.6.1+3 and the pubspec was 0.6.2, so I added appended to the 0.6.2 CHANGELOG.  However, local_auth was published on the [commit immediately before it](https://github.com/flutter/plugins/releases/tag/local_auth-v0.6.2) and therefore isn't really in 0.6.2.
Bump the version and change the CHANGELOG to reflect this.
https://github.com/flutter/plugins/pull/2685
=> [local_auth] Bump version

.cirrus.yml
Camera and google_sign_in are the last two packages with linter warnings.  Temporarily skip camera until https://github.com/flutter/plugin_tools/pull/97 is merged and we can swap the `--skip` to `--ignore-warnings`.
=> Skip linting camera

.cirrus.yml
https://github.com/flutter/plugin_tools/pull/97 is published with the new `--ignore-warnings` flag.  Instead of skipping camera, just ignore the [warnings](https://github.com/flutter/flutter/issues/20708).
Fixes https://github.com/flutter/flutter/issues/55245
https://github.com/flutter/flutter/issues/20708
https://github.com/flutter/plugin_tools/pull/97
=> Run camera linter, skip warnings

packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
This change is required to make the package publishable (versions 1.0.0 to 1.0.0+5 were development versions that shouldn't have been published).
I didn't realize that the package had been published to pub while it was in PR.
* https://github.com/flutter/plugins/pull/2577 …
=> [google_maps_flutter_platform_interface] Bump to 1.0.1 version.

.cirrus.yml, packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj, packages/google_sign_in/google_sign_in/ios/Tests/GoogleSignInPluginTest.m, packages/google_sign_in/google_sign_in/ios/google_sign_in.podspec, packages/google_sign_in/google_sign_in/pubspec.yaml
1. OCMock doesn't define a modulemap, so `@import` fails when the pod is generated as a library instead of a framework (without `use_frameworks!`).  Use `#import` instead of module `@import`.
2. [Migrate example project to support Xcode 11.4](https://flutter.dev/docs/development/ios-project-migration).
3. Fix pod lib lint issues and un-skip linting during presubmit. 
```
-> google_sign_in (0.0.1)
...
[!] google_sign_in did not pass validation, due to 2 warnings (but you can use `--allow-warnings` to ignore them).
```
flutter/flutter#55245
Before you create this PR confirm that it meets all requirements listed below by checking the …
=> [google_sign_in] OCMock module import -> #import, pod lint warnings

packages/video_player/video_player/README.md
updates to call out web is also supported for this plugin.
Explicitly tells users not to use the constructor when using the plugin for web.
flutter/flutter#55340
- [≈ ] No, this is *not* a breaking change.
=> [video_player] Update README to mention web support.

packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/lib/navigator.dart, packages/url_launcher/url_launcher_web/lib/src/navigator.dart, packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/url_launcher/url_launcher_web/test/url_launcher_web_test.dart
Users using this plugin on iOS PWAs are experiencing blank screens when a url is opened on another app and then they try to go back. It seems to be an well known issue on iOS [1] and [2] as reference. In the meantime we can overcome this limitation by modifying the target to "_top" according to [2] (solution manually verified). This PR does exactly that, verifies if the user is running a PWA in iOS and if so it will open the url with "_top" as target.
[1] https://stackoverflow.com/questions/55517297/mailto-doesnt-work-when-website-launched-from-ios-home-screen/56153685#56153685
[2] https://stackoverflow.com/questions/56220862/ios-pwa-open-maps-returns-to-blank-screen
flutter/flutter#51461
Before you create this PR confirm that it meets all requirements listed below by checking the …
=> [url_launcher] Open url in same window when browser is in standalone mode.

AUTHORS, packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md, packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart, packages/google_sign_in/google_sign_in_platform_interface/lib/src/utils.dart, packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml, packages/google_sign_in/google_sign_in_platform_interface/test/method_channel_google_sign_in_test.dart
Add attribute `serverAuthCode` to, the `GoogleSignInTokenData` class.
serverAuthCode is used in this [pr](https://github.com/flutter/plugins/pull/2116).
https://github.com/flutter/plugins/pull/2116
[CLA]: …
=> [google_sign_in] Add serverAuthCode attribute to google_sign_in_platform_interface

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/example/test_driver/google_maps_e2e.dart, packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.m, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Instead of workaround in the first delegate callback. We reset the camera location when we know the frame of the `GMSMapView` is changed. This prevents any unwanted artifacts introduced due to the previous workaround.
https://github.com/flutter/flutter/issues/53428
https://github.com/flutter/flutter/issues/27550 …
=> [google_maps_flutter] Fix the visual jarring during the first gesture on the map

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/pubspec.yaml
Follow-up to #2533 - we got the version bump wrong in the original PR (a new feature should bump the minor version and not the patch version)
=> [webview_flutter] Fix the version update for #2533

packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java, packages/google_sign_in/google_sign_in/example/android/app/src/test/java/io/flutter/plugins/googlesignin/GoogleSignInPluginTests.java, packages/google_sign_in/google_sign_in/pubspec.yaml
Make sure the stored `result` field is cleared if `requestScopes` exits early, otherwise subsequent calls to the plugin will get a "concurrent call" `PlatformException`.
flutter/flutter#55410
[CLA]: …
=> [google_sign_in] Fix issue with repeated calls to requestScopes.

packages/connectivity/connectivity_platform_interface/CHANGELOG.md, packages/connectivity/connectivity_platform_interface/lib/src/method_channel_connectivity.dart, packages/connectivity/connectivity_platform_interface/pubspec.yaml
Even though the code path never hits web targets, having `dart:io` imports in the MethodChannel implementation in the platform_interface package breaks the `pana` analysis of federated implementations for platforms where those imports are forbidden (like web), with something similar to this:
```
$~/connectivity/experimental_connectivity_web does not support flutter with runtime: flutter-web because of import violation at: 
package:experimental_connectivity_web/experimental_connectivity_web.dart,
package:experimental_connectivity_web/src/network_information_api_connectivity_plugin.dart,
package:experimental_connectivity_web/src/utils/connectivity_result.dart,
package:connectivity_platform_interface/connectivity_platform_interface.dart, …
```
=> [connectivity_platform_interface] Remove Platform asserts.

packages/battery/CHANGELOG.md, packages/battery/README.md, packages/battery/pubspec.yaml
An [ecosystem pre-migration](https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0) has been performed (https://github.com/amirh/bump_to_1.0/projects/1).
=> [battery] Bump to 1.0.0

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java, packages/image_picker/image_picker/example/android/app/build.gradle, packages/image_picker/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/FileUtilTest.java, packages/image_picker/image_picker/lib/image_picker.dart, packages/image_picker/image_picker/pubspec.yaml
For some historical reason, we have separated the diverged the code to different paths when handling different types of image data. Really, we should always handle the picked image through an URI like what we have been doing for remote images. 
This way we can make sure the image picked from URI is definitely usable in the APP. 
We don't seem to have a good way to test changes around this code base. I will keep looking into ways to test with JUnit 
I have manually tested with downloaded images, images taken from camera, and images from google driver.
Tested with pixel a3 android 11, and some older android builds in emulators. 
b/155138680
https://github.com/flutter/flutter/issues/41459
Before you create this PR confirm that it meets all requirements listed below by checking the relevant …
=> [image_picker] Handle all images through URI

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
The `web` platform was endorsed by mistake in a prior push, and it is confusing users. This removes that endorsement from the pubspec.
* https://github.com/flutter/flutter/issues/56122
[CLA]: …
=> [google_maps_flutter] Remove endorsement of web platform.

packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/pubspec.yaml
This is a necessary precondition for https://github.com/flutter/plugins/pull/2544 to pass CI.  video_player has a dependency on video_player_web and you can't update video_player's video_player_platform_interface without updating it also for video_player_web.
https://github.com/flutter/flutter/issues/32930 …
=> [video_player]: updated video_player_web to use the new video_player_platform_interface

packages/video_player/video_player_platform_interface/CHANGELOG.md, packages/video_player/video_player_platform_interface/pubspec.yaml, packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
This fixes the unit tests.  They were broken from the migration from pigeon.  This is a step to get https://github.com/flutter/plugins/pull/2544 merged and the tree fixed.
=> [video_player]: fixed platform_interface unit tests

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/README.md, packages/in_app_purchase/lib/src/in_app_purchase/in_app_purchase_connection.dart, packages/in_app_purchase/pubspec.yaml
Make the documentation and README more explicit about `completePurchase`
https://github.com/flutter/flutter/issues/51902
=> [in_app_purchase] update docs to warn about `completePurchase`

packages/android_alarm_manager/CHANGELOG.md, packages/android_alarm_manager/pubspec.yaml
https://github.com/flutter/flutter/issues/56930
=> [android_alarm_manager] update dart deps lower bound to 2.1.0

packages/battery/CHANGELOG.md, packages/battery/pubspec.yaml
https://github.com/flutter/flutter/issues/56930
=> [battery] update dart deps lower bound to 2.1.0

packages/camera/CHANGELOG.md, packages/camera/pubspec.yaml
https://github.com/flutter/flutter/issues/56930
=> [camera] Update lower bound of dart dependency to 2.1.0.

.ci/Dockerfile-LinuxDesktop, .cirrus.yml
Flutter plugin tests don't necessarily run in headless mode; this adds a virtual display when running Linux tests so that they will run in normal mode.
Fixes https://github.com/flutter/flutter/issues/55327
[CLA]: …
=> Use Xvfb for Linux desktop tests

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/lib/url_launcher.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher/test/url_launcher_test.dart
The value of previousAutomaticSystemUiAdjustment is set to true in launch method before statusBarBrightness is checked. This change prevents the automaticSystemUiAdjustment of the renderView from being set to null after statusBarBrightness is checked. This ensures that _updateSystemChrome() is called before window rendering.
Fixes flutter/flutter#43373 …
=> [url_launcher] Initialize previousAutomaticSystemUiAdjustment in launch

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/README.md, packages/image_picker/image_picker/pubspec.yaml
Add documentation for configuring external storage permissions on Android devices. The requestLegacyExternalStorage attribute needs to be set to true on Android Q, or else ImagePicker cannot select an image from OneDrive. This causes a null value to be returned instead of a valid file path.
flutter/flutter#47240 …
=> [image_picker] Add documentation for Android external storage permissions

.cirrus.yml
I believe all the plugins are migrated and can not check publish on master, and the workaround in https://github.com/flutter/plugins/pull/2250 can be reverted.
This will also enable us to catch potential publish issues with newer dart version as early as possible.
=> Run the publish with the pub version from flutter master

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m, packages/image_picker/image_picker/ios/Tests/ImagePickerPluginTests.m, packages/image_picker/image_picker/pubspec.yaml
Sometimes double click cancel button will crash.
=> [image_picker] fix bug, sometimes double click cancel button will crash

packages/e2e/CHANGELOG.md, packages/e2e/android/build.gradle, packages/e2e/android/src/main/java/dev/flutter/plugins/e2e/E2EPlugin.java, packages/e2e/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/48701
ConcurrentFuture is only available in API24 and above. This imports a support package with an implementation compatible down to our lowest supported API level, 16.
=> [e2e] Use CompletableFuture from package for lower API level support

packages/image_picker/image_picker_platform_interface/CHANGELOG.md, packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart, packages/image_picker/image_picker_platform_interface/lib/src/platform_interface/image_picker_platform.dart, packages/image_picker/image_picker_platform_interface/lib/src/types/lost_data_response.dart, packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/base.dart, packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/html.dart, packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/io.dart, packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/lost_data.dart, packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/picked_file.dart, packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/unsupported.dart, packages/image_picker/image_picker_platform_interface/lib/src/types/types.dart, packages/image_picker/image_picker_platform_interface/pubspec.yaml, packages/image_picker/image_picker_platform_interface/test/assets/hello.txt, packages/image_picker/image_picker_platform_interface/test/method_channel_image_picker_test.dart, packages/image_picker/image_picker_platform_interface/test/new_method_channel_image_picker_test.dart, packages/image_picker/image_picker_platform_interface/test/picked_file_html_test.dart, packages/image_picker/image_picker_platform_interface/test/picked_file_io_test.dart
This change modifies the platform_interface to introduce the `PickedFile` type and the new APIs that make use of it.
This also deprecates the old APIs, pointing people to the new ones.
This is the first step to release https://github.com/flutter/plugins/pull/2767
* https://github.com/flutter/flutter/issues/36281
* https://github.com/flutter/flutter/issues/53283
Note: this is not a breaking change, but it requires users to migrate to non-deprecated methods. …
=> [image_picker_platform_interface] Introduce new PickedFile APIs.

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/pubspec.yaml
Publishing v1.1.0 of the platform_interface before the core plugin was ready to accept it (ignoring deprecation warnings) has caused breakage.
This PR locks the version of the platform interface to 1.0.0 so end users of the plugin (still) don't see the deprecation warnings themselves.
https://github.com/flutter/plugins/pull/2791 …
=> [image_picker] Pin version of platform_interface.

packages/e2e/CHANGELOG.md, packages/e2e/android/build.gradle, packages/e2e/example/android/app/src/androidTest/java/com/example/e2e_example/FlutterActivityWithPermissionTest.java, packages/e2e/example/android/build.gradle, packages/e2e/example/android/gradle/wrapper/gradle-wrapper.properties, packages/e2e/pubspec.yaml
Currently, android build creates the warning message:
=> [e2e] Android: Remove warning, bump AGP

packages/e2e/CHANGELOG.md, packages/e2e/README.md, packages/e2e/pubspec.yaml
The first code snippet for the e2e plugin's readme invokes the `exit` that uses the value of a `result` variable that doesn't exist. I'm assuming there's some confusion where `result` stored the output of calling `request_data` that isn't used in the context of the code snippet. This PR is to remove that line of code.
Does your PR require plugin …
=> [e2e] fixed code snippet in readme that referenced a non-existent variable

packages/e2e/lib/e2e.dart
Fixes flutter/flutter#51885
Fixes flutter/flutter#57623
On versions of Flutter containing https://github.com/flutter/flutter/pull/58210, this will make sure we don't automatically register the test text input and httpoverrides.
This will also default the window size to whatever the device or browser actually thinks it should be, rather than forcing it to start at 800x600. We can, if needed, still alter the size in a test using the binding's `setSurfaceSize` from within a test.
/cc @chunhtai since you helped review the upstream PR related to this.
=> [e2e] Avoid overriding http, textinput, window size

packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/README.md, packages/path_provider/path_provider/pubspec.yaml
Updated documentation reflecting changes needed for testing federated plugins
This PR addresses this [comment](https://github.com/flutter/plugins/pull/2789#issuecomment-638949311)
The recent federation of the Linux path provider might break tests, this updates the README.md to address those changes and direct the users how to mock the plugin in their tests.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick …
=> [path_provider] Updated documentation reflecting changes needed for testing

packages/connectivity/connectivity/ios/Classes/FLTConnectivityPlugin.m, packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/ios/Classes/FIAPaymentQueueHandler.m, packages/in_app_purchase/ios/Tests/InAppPurchasePluginTest.m, packages/in_app_purchase/ios/Tests/PaymentQueueTest.m, packages/in_app_purchase/ios/Tests/Stubs.m, packages/in_app_purchase/lib/src/in_app_purchase/app_store_connection.dart, packages/in_app_purchase/lib/src/in_app_purchase/in_app_purchase_connection.dart, packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart, packages/in_app_purchase/pubspec.yaml, packages/in_app_purchase/test/in_app_purchase_connection/app_store_connection_test.dart, packages/in_app_purchase/test/store_kit_wrappers/sk_test_stub_objects.dart
1. Fix assertion error on SKPaymentQueueWrapper init.
2. Make sure `queryPastPurchases()` won't block transaction updates. When the client apps calls `queryPastPurchases()` right after app launch, they should still receive transaction updates in the `purchaseUpdatedStream` for transactions with state != restored.
3. Update fake data to match reality. Only purchased and restored transactions have a transaction identifier.
https://github.com/flutter/flutter/issues/53534 …
=> [In_App_Purchase]queryPastPurchases() shouldn't block transaction updates.

packages/e2e/CHANGELOG.md, packages/e2e/lib/e2e.dart, packages/e2e/pubspec.yaml
Fix the device pixel ratio for e2e. 
According to https://api.flutter.dev/flutter/flutter_test/TestViewConfiguration-class.html the size of `TestViewConfiguration` constructor is  in logical pixels. 
flutter/flutter#59880 …
=> [e2e] Fix e2e pixel ratio

packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/url_launcher/url_launcher_web/test/url_launcher_web_test.dart
Adds the ability to open `tel` URLS in web
* Fixes https://github.com/flutter/flutter/issues/58553
* Fixes https://github.com/flutter/flutter/issues/60293
=> [url_launcher_web] Add tel URL support

packages/e2e/CHANGELOG.md, packages/e2e/android/build.gradle, packages/e2e/android/src/main/java/dev/flutter/plugins/e2e/E2EPlugin.java
This unblocks the import of the plugin internally.
b/160208320
Breaking change if users depend on `E2EPlugin.testResults` as an instance of `CompletableFuture`.
=> [e2e] Use SettableFutures instead of CompletableFuture

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/example/lib/main.dart, packages/image_picker/image_picker/pubspec.yaml, packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/lib/video_player.dart, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player/test/video_player_test.dart, packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/lib/video_player_web.dart, packages/video_player/video_player_web/pubspec.yaml
While testing the image_picker_web plugin, I noticed that video playback was a little bit flaky. This PR addresses some of the subtle bugs in the image_picker example app, video_player plugin and video_player_web implementation.
n/a
All changes are minor and independent, so no need to split this PR in several different ones. This all should be mergeable and publishable in parallel. …
=> [video_player] Miscellaneous fixes to improve video player in web.

AUTHORS, packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/ios/image_picker.podspec, packages/image_picker/image_picker/pubspec.yaml
Currently the Image Picker plugin no longer works on Xcode 11.4.1 in the iPhone simulator. I updated the podspec to set the VALID_ARCHS to match other plugins in this project.
Fixes https://github.com/flutter/flutter/issues/51395 …
=> [image_picker] updated VALID_ARCHS to support iPhone simulator

packages/shared_preferences/shared_preferences_linux/CHANGELOG.md, packages/shared_preferences/shared_preferences_linux/ios/shared_preferences_linux.podspec, packages/shared_preferences/shared_preferences_linux/pubspec.yaml
Add missing iOS stub to shared_preferences_linux
None
=> [shared_preferences_linux] Add iOS stub

packages/e2e/CHANGELOG.md, packages/e2e/lib/common.dart, packages/e2e/lib/e2e.dart, packages/e2e/pubspec.yaml, packages/e2e/test/binding_test.dart, packages/e2e/test/response_serialization_test.dart
Added an extra field `extraInfo` in `lib/common.dart`. Use case is to use the field to report performance. E.g. in flutter/flutter#61509, I'm migrating one existing test to an e2e based performance test. The use case is not complete because I still need to add other performance metrics but for a demo of the use case it's sufficient. 
I'm not naming it to performance because in some of our device lab test the reported value is not for performance. 
Resolves flutter/flutter#61490 …
=> [e2e] add support to report extra information

packages/path_provider/path_provider_linux/CHANGELOG.md, packages/path_provider/path_provider_linux/lib/path_provider_linux.dart, packages/path_provider/path_provider_linux/pubspec.yaml
Use the application ID in the application support path. The existing code uses the binary name, which is not necessarily unique. Application IDs were recently added to the Linux shell.
https://github.com/flutter/flutter/issues/59234 …
=> [path_provider] Use the application ID in the application support path

packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/example/android/app/src/androidTest/java/MainActivityTest.java, packages/path_provider/path_provider/pubspec.yaml, packages/path_provider/path_provider_linux/CHANGELOG.md, packages/path_provider/path_provider_linux/lib/path_provider_linux.dart, packages/path_provider/path_provider_linux/pubspec.yaml
Reverts flutter/plugins#2845
This broke master - Linux is consistently timing out after this.
TBR @robert-ancell @stuartmorgan 
/cc @ditman
=> Revert "[path_provider] Use the application ID in the application support path"

packages/e2e/CHANGELOG.md, packages/e2e/lib/e2e.dart, packages/e2e/pubspec.yaml, packages/e2e/test/binding_fail_test.dart, packages/e2e/test/data/README.md, packages/e2e/test/data/fail_test_script.dart, packages/e2e/test/data/pass_test_script.dart, packages/e2e/test/data/pass_then_fail_test_script.dart
For example, the following test will result in an error reported for the first test case.
```
void main() {
testWidgets('a test that passes', (tester) async {
expect(true, true);
});
testWidgets('a test that fails', (tester) async {
expect(true, false);
});
}
```
We need to reset `reportTestException` back to the previous value after completion of `runTest`, or repeated failures will cause the exception handler for a previous test to be invoked, as they "stack". Instead of reseting it, however, do this once in the constructor because the test description is already provided by the function signature. …
=> [e2e] Fix incorrect test results when one test passes then another fails

packages/e2e/README.md
A few lines update to readme about how to run e2e tests on firebase test lab. 
Update for kotlin is still a to-do.
N/A
=> Clarify e2e readme for running on firebase test lab

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m, packages/in_app_purchase/ios/Tests/InAppPurchasePluginTest.m, packages/in_app_purchase/pubspec.yaml
*Fix one-letter typo*
https://github.com/flutter/plugins/pull/2812#pullrequestreview-436931714
=> [in_app_purchases] Fixed typo 'manuelly' for 'manually'

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/example/lib/marker_icons.dart, packages/google_maps_flutter/google_maps_flutter/example/lib/place_polyline.dart, packages/google_maps_flutter/google_maps_flutter/lib/google_maps_flutter.dart, packages/google_maps_flutter/google_maps_flutter/lib/src/google_map.dart, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter/test/map_creation_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/bitmap.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
This PR adds some small modifications to the core maps plugin and its platform interface, so the web version is doable.
It allows people using the experimental branch of google_maps_flutter_web to keep using it, without having to override many packages (and will also simplify the final merge of google_maps_flutter_web, so it only touches one package!)
This PR touches two packages, but both changes should be independent, and backwards compatible, so test should pass, and they can be merged and published in any order.
* Pass a constant `creationMapId` to `platform.buildView`, so web can return a cached widget DOM when flutter attempts to repaint there.
* Modify some examples slightly so they're more web-friendly (remove dart:io imports, pass a size to the bitmap used as a custom Icon, so it …
=> [google_maps_flutter(_platform_interface)] Make the plugin friendlier to the web implementation.

packages/e2e/CHANGELOG.md, packages/e2e/example/test_driver/example_e2e_test.dart, packages/e2e/lib/e2e_driver.dart, packages/e2e/lib/e2e_perf.dart, packages/e2e/pubspec.yaml, packages/e2e/test/frame_timing_summarizer_test.dart
These are utilities for implementing e2e-based performance test. e.g.flutter/flutter#61509 
These codes will be shared among most of such test cases. 
flutter/flutter#58789
=> [e2e] Add new e2e_driver for handling response data and performance watcher

packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/method_channel/method_channel_google_maps_flutter.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_flutter_platform.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
The current version of the plugin does not have the ability to dispose of the resources that it grabs natively (I suppose the native side is able to clean itself up effectively).
The web implementation is not able to do so, and it needs a `dispose` method to dispose of the resources it grabs.
This PR adds a `dispose` method to the platform interface package of google_maps_flutter, and a noop implementation for its MethodChannel implementation.
The new method will be called on `dispose` of the current GoogleMap widget, as seen here: #2909 
Does your PR require plugin users to manually update their apps to accommodate …
=> [google_maps_flutter_platform_interface] Add dispose method.

packages/camera/CHANGELOG.md, packages/camera/android/src/main/java/io/flutter/plugins/camera/MethodCallHandlerImpl.java, packages/camera/pubspec.yaml
If camera permissions are not granted, the plugin currently throws an exception in Java:
```
E/MethodChannel#plugins.flutter.io/camera(22476): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(22476): java.lang.ClassCastException: android.hardware.camera2.CameraAccessException cannot be cast to java.lang.RuntimeException
E/MethodChannel#plugins.flutter.io/camera(22476): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.handleException(MethodCallHandlerImpl.java:172)
E/MethodChannel#plugins.flutter.io/camera(22476): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$MethodCallHandlerImpl(MethodCallHandlerImpl.java:66)
E/MethodChannel#plugins.flutter.io/camera(22476): 	at io.flutter.plugins.camera.-$$Lambda$MethodCallHandlerImpl$OMU5dV7VCKXKBT37_ …
```
=> [camera] Improving handling when camera permissions are not granted.

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/ios/google_maps_flutter.podspec, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
GoogleMaps 3.10 seems to have increased the minimum requirement for XCode beyond what our test infra can handle (undocumented?).
This change pins the GoogleMaps podspec to <3.10 until the situation clears, to unblock the build trees of both flutter/plugins and flutter/flutter.
**Why are our apps resolving to 3.10, when our Podspec states that ios 8.0 needs to be supported?** 
Apps were resolving to 3.10 because `flutter create` now creates apps that have a minimum iOS version of 9.0 (instead of 8.0).
**Why did 3.10 break us?**
3.10 breaks us because they're using some APIs only available in XCode 11.4 and our infra is in 11.3.1. (However, as @jmagman pointed out, they should check for the availability of these APIs or a runtime error will happen in devices running iOS < 13.4.)
* …
=> [google_maps_flutter] Pin GoogleMaps cocoapod dep to last good known version

.cirrus.yml, packages/camera/CHANGELOG.md, packages/camera/ios/Classes/CameraPlugin.m, packages/camera/ios/camera.podspec, packages/camera/pubspec.yaml
~~The build is failing on this plugin in an unrelated PR currrently due to these issues.~~ This doesn't fail the build because we're specifically ignoring these warnings, so instead I'm enabling the warnings. This does cause crashes for users on older iOS versions, see linked bug.
This does make me wonder if we really should claim to support this plugin on iOS 8.0.  Currently, you can't take a picture with the camera plugin on anything lower than iOS 10 - it would cause a runtime crash (now it will just result in an exception that should be recoverable).
Fixes https://github.com/flutter/flutter/issues/20708
=> Fix unguarded availability in Camera plugin

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/Messages.java, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerOptions.java, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java, packages/video_player/video_player/example/lib/main.dart, packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m, packages/video_player/video_player/ios/Classes/messages.h, packages/video_player/video_player/ios/Classes/messages.m, packages/video_player/video_player/lib/video_player.dart, packages/video_player/video_player/pigeons/messages.dart, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player/test/video_player_test.dart
This is a replacement PR for #1174 because I lost access to the original repository I created the PR from.
How do I make the tests work? Unfortunately, I also had to modify the interface package.
@cyanglaz Pinging you like promised and maybe you can also help me out making the tests green and stuff :) But I have to say this new pigeon method of communicating with the native side is pretty awesome 👍 
The only "dirty" thing was that when I created the new dart files, I lost some API test files that apparently were committed to the auto-generated file. I guess that is something that should be moved into a file that is not generated 😄
=> [video_player] Set audio mix options

packages/local_auth/CHANGELOG.md, packages/local_auth/pubspec.yaml, packages/path_provider/path_provider_platform_interface/CHANGELOG.md, packages/path_provider/path_provider_platform_interface/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/63441
package:platform required a breaking change in the behavior of FakePlatform in order to enable null safety, but there will be no other breaking changes in 3.X Since this does not affect path provider or local_auth, the pubspec constraint can be increased.
=> [versions] increase package:platform constraint

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/Messages.java, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerOptions.java, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java, packages/video_player/video_player/example/lib/main.dart, packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m, packages/video_player/video_player/ios/Classes/messages.h, packages/video_player/video_player/ios/Classes/messages.m, packages/video_player/video_player/lib/video_player.dart, packages/video_player/video_player/pigeons/messages.dart, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player/test/video_player_test.dart
=> Reland "[video_player] Set audio mix options (#2922)"

.cirrus.yml, script/incremental_build.sh
Shard some tests that have been timing out some more.
Specifically, increase the shard count of build-apks+java-test+firebase-test-lab from 2 to 4.
=> MORE SHARDS MEANS MORE CI

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/test/README.md, packages/google_maps_flutter/google_maps_flutter_web/test/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/test/run_test, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/google_maps_controller_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/google_maps_controller_integration_test.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/google_maps_plugin_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/google_maps_plugin_integration_test.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/marker_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/marker_integration_test.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/markers_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/markers_integration_test.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/shape_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/shape_integration_test.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/shapes_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/shapes_integration_test.dart
e2e is now integration_test.
Move the e2e tests on this package to be integration_tests, also ensure we depend on integration_test from path.
* https://github.com/flutter/plugins/pull/2918
[CLA]: …
=> [google_maps_flutter_web] Port e2e tests to integration_test package.

packages/path_provider/path_provider_macos/example/pubspec.yaml, packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/pubspec.yaml
It *seems* the `./script/incremental_build.sh analyze` script is failing to analyze some random packages, and failing CI. 
It *seems* `pub get` is not downloading the latest versions of some dependencies, and this is causing analyzer problems (missing classes, etc).
This change fixes a couple of pubspec.yaml files to ensure pub is downloading the appropriate packages for the packages I saw failing on my machine (`path_provider_macos/example` and `video_player`).
* Maybe similar to: https://github.com/flutter/plugins/pull/2948 ?
Does your PR require plugin users to manually update their apps to accommodate your …
=> [path_provider, video_player] Tweak pubspecs to pass bulk analysis.

packages/integration_test/android/src/main/java/dev/flutter/plugins/integration_test/IntegrationTestPlugin.java, packages/integration_test/lib/common.dart, packages/integration_test/lib/integration_test_driver.dart
- Doc typos
- Unused Java variables
=> [integration_test] Minor cleanup

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/README.md, packages/image_picker/image_picker/pubspec.yaml
Updating documentation to be in sync with example. The value returned is never null. This is already done correclty in the
example app.
-
=> [image_picker] Updating documentation to use isEmpty check.

packages/battery/CHANGELOG.md, packages/battery/README.md, packages/battery/pubspec.yaml
In this pr, I have changed `battery` variable to private variable as it was used as private variable in one of it's example.
=> [battery] Updated README.md

packages/video_player/video_player_platform_interface/CHANGELOG.md, packages/video_player/video_player_platform_interface/lib/messages.dart, packages/video_player/video_player_platform_interface/pubspec.yaml, packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
The test api method channel was not set, which causes test failures
=> [video_player_platform_interface] fix `setMixIWithOthers` test channel

packages/integration_test/CHANGELOG.md, packages/integration_test/android/src/main/java/dev/flutter/plugins/integration_test/FlutterTestRunner.java, packages/integration_test/ios/Classes/IntegrationTestIosTest.m, packages/integration_test/lib/common.dart, packages/integration_test/lib/integration_test.dart, packages/integration_test/pubspec.yaml, packages/integration_test/test/binding_fail_test.dart
We keep things simple for now, because this might change once we have a proper test reporter.
=> [integration_test] Show stack trace of widget test errors on the platform side

packages/integration_test/CHANGELOG.md, packages/integration_test/README.md, packages/integration_test/example/README.md, packages/integration_test/ios/Classes/IntegrationTestPlugin.m
Fix channel name for iOS, docs
I haven't published `0.8.1` yet, will do so after this PR to get the fix for the channel name in.
=> [integration_test] Fix channel name for iOS, docs

packages/integration_test/CHANGELOG.md, packages/integration_test/example/test_driver/example_integration_io.dart, packages/integration_test/lib/integration_test.dart, packages/integration_test/pubspec.yaml, packages/integration_test/test/binding_test.dart
Add `traceTimeline` and `traceAction` to `IntegrationTestWidgetsFlutterBinding` for getting the timeline. 
Resolves flutter/flutter#58789
=> [integration_test] add support to get timeline

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/pubspec.yaml
The latest changes to the url_launcher added a new web-only parameter to the platform interface API. However, it didn't update the dependencies of the other url_launcher packages to the right version of the platform interface.
In cases where the app has previously resolved some of its dependencies (pubspec.lock is present), pub might not download the latest versions of all packages, causing errors with this new parameter being added.
This PR addresses the issue by bumping the minimal versions of the packages that fulfill the correct APIs, bringing everything up to speed.
* https://github.com/flutter/flutter/issues/64863
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review …
=> [url_launcher, url_launcher_web] Fix API dependencies.

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolylineController.h, packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolylineController.m, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Polylines in iOS are not curved based on the earth's curvature even if we set geodesic true in flutter dart code. This is because this property passed to the plugin native code isn't used. I have set this property after GMSPolyline Objc instance created
flutter/flutter#49189 …
=> Geodesic Polyline support in iOS

packages/battery/battery/CHANGELOG.md, packages/battery/battery/lib/battery.dart, packages/battery/battery/pubspec.yaml, packages/battery/battery/test/battery_test.dart
In this PR, I have ported `battery` to use `battery_platform_package` .
=> [battery] Port battery to use platform interface

script/incremental_build.sh
Allow running incremental_build.sh on Windows under Git Bash. Longer
term this script should be re-written in Dart (#64025), but for now this
allows running the script on Windows bots.
https://github.com/flutter/flutter/issues/56143 …
=> Support Windows in incremental_build.sh

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java, packages/url_launcher/url_launcher/pubspec.yaml
The url_launcher overrides the deprecated `shouldOverrideUrlLoading(WebView view, String url)` method to be backwards compatible with versions before Android API 24. This however currently displays the warning "WebViewActivity.java uses or overrides a deprecated API." when building for Android. This is causing some problems for developers who treat these warnings as errors as part of their build configuration.
This PR addresses this issue by annotating the `shouldOverrideUrlLoading(WebView view, String url)` method with the `@SuppressWarnings("deprecation")` attribute.
This PR also adds the `@RequiresApi(Build.VERSION_CODES.N)` annotation to the `shouldOverrideUrlLoading(WebView view, WebResourceRequest request)` method, which gives the Android/ Java tooling an indication this method …
=> [url_launcher] Suppress deprecation warning in WebViewActivity

packages/device_info/device_info_platform_interface/CHANGELOG.md, packages/device_info/device_info_platform_interface/lib/device_info_platform_interface.dart, packages/device_info/device_info_platform_interface/pubspec.yaml
In this PR, I have fixed the documentation error i made while writing it.
=> [device_info_platform_interface] Typo in doc fixed

packages/image_picker/image_picker_for_web/CHANGELOG.md, packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart, packages/image_picker/image_picker_for_web/pubspec.yaml
This PR attempts [#58532](https://github.com/flutter/flutter/issues/58532) and solves video selecting issues when using the image_picker plugin in safari. This issue comes from the webkit and apples own MIMETypes. ([see](https://trac.webkit.org/browser/trunk/Source/WebCore/platform/MIMETypeRegistry.cpp))
Following video file types can be selected(others not tested):
- .mp4
- .3gp
- .avi
- .mov
* fixes https://github.com/flutter/flutter/issues/58532
[Contributor …
=> [image_picker_for_web] Can't select some video file types (3gp, mp4, possibly others...)

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/example/lib/map_ui.dart, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Fixed typo in google_maps_flutter/example/map_ui.dart
=> [google_maps_flutter] Fix typo in google_maps_flutter/example/map_ui.dart

packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/url_launcher/url_launcher_web/test/url_launcher_web_test.dart
Fix a typo in a test name and fix quote consistency.
=> [url_launcher_web] Fix a typo in a test name and fix quote consistency

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/markers_integration.dart
The current conversion of our `Marker` type to `gmaps.Marker` assumes that `marker.icon` is never null ([internally, it defaults to `BitmapDescriptor.defaultMarker`](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart#L165)), however users can break the default by creating a marker like so:
```dart
Marker(markerId: MarkerId('boom'), icon: null);
```
This PR makes the `Marker` to `gmaps.Marker` conversion resilient to the case where the passed `icon` is `null`.
* Fixes https://github.com/flutter/flutter/issues/64938
Does your PR …
=> [google_maps_flutter_web] Allow Markers with icon:null

packages/shared_preferences/shared_preferences_linux/example/linux/flutter/generated_plugin_registrant.cc, packages/shared_preferences/shared_preferences_linux/example/linux/my_application.cc, packages/url_launcher/url_launcher/example/linux/flutter/generated_plugin_registrant.cc, packages/url_launcher/url_launcher/example/linux/my_application.cc, packages/url_launcher/url_launcher_linux/example/linux/flutter/generated_plugin_registrant.cc, packages/url_launcher/url_launcher_linux/example/linux/my_application.cc
A new version of the formatter or something might have rolled in, causing CI to break
=> Fix formatting

.clang-format, packages/url_launcher/url_launcher_windows/.gitignore, packages/url_launcher/url_launcher_windows/.metadata, packages/url_launcher/url_launcher_windows/CHANGELOG.md, packages/url_launcher/url_launcher_windows/LICENSE, packages/url_launcher/url_launcher_windows/README.md, packages/url_launcher/url_launcher_windows/example/.gitignore, packages/url_launcher/url_launcher_windows/example/.metadata, packages/url_launcher/url_launcher_windows/example/README.md, packages/url_launcher/url_launcher_windows/example/lib/main.dart, packages/url_launcher/url_launcher_windows/example/pubspec.yaml, packages/url_launcher/url_launcher_windows/example/test_driver/url_launcher_e2e.dart, packages/url_launcher/url_launcher_windows/example/test_driver/url_launcher_e2e_test.dart, packages/url_launcher/url_launcher_windows/lib/url_launcher_windows.dart, packages/url_launcher/url_launcher_windows/pubspec.yaml, packages/url_launcher/url_launcher_windows/windows/.gitignore, packages/url_launcher/url_launcher_windows/windows/CMakeLists.txt, packages/url_launcher/url_launcher_windows/windows/include/url_launcher_windows/url_launcher_plugin.h, packages/url_launcher/url_launcher_windows/windows/url_launcher_plugin.cpp
Adds a federated Windows implementation of url_launcher (not yet endorsed).
Since this is the first C++ plugin, this also adds a .clang-format file to the repo root for formatting C++ plugins.
Part of https://github.com/flutter/flutter/issues/41721 (will need follow-up to endorse it in url_launcher)
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-r …
=> Add url_launcher_windows

packages/android_alarm_manager/pubspec.yaml
https://github.com/flutter/plugins/pull/3020 had a unmatched version between changelog and pubspec.yaml
=> [android_alarm_manager] version fix

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/README.md, packages/url_launcher/url_launcher/example/test_driver/url_launcher_e2e.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher_windows/CHANGELOG.md, packages/url_launcher/url_launcher_windows/README.md, packages/url_launcher/url_launcher_windows/ios/url_launcher_windows.podspec, packages/url_launcher/url_launcher_windows/pubspec.yaml
Endorses url_launcher_windows so that Windows is supported automatically.
Fixes https://github.com/flutter/flutter/issues/41721
=> [url_launcher] Endorse Windows implementation

CODEOWNERS
Because of federated plugins, no reviews are requested automatically when opening a PR.
For example, https://github.com/flutter/plugins/pull/3032 should have probably automatically requested @iskakaushik and @cyanglaz, however, that did not happen because the paths for federated plugins are not covered at the moment.
=> [all] Update CODEOWNERS to properly request reviews

packages/camera/CHANGELOG.md, packages/camera/android/build.gradle, packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java, packages/camera/pubspec.yaml
- Handle deprecation & unchecked warning as error
- Avoiding uses or overrides a deprecated API in CameraPlugin.java
A message is displayed when building for android: 
```
flutter build apk
Running "flutter pub get" in example...                            38,2s
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK
size.
To generate an app bundle, run:
flutter build appbundle --target-platform android-arm,android-arm64,android-x64
Learn more on: https://developer.android.com/guide/app-bundle
To split the APKs per ABI, run:
flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
Learn more on: …
```
=> [camera] CameraPlugin.java uses or overrides a deprecated API

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/android/build.gradle, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java, packages/video_player/video_player/pubspec.yaml
- Handle deprecation & unchecked warning as error
- Avoiding uses or overrides a deprecated API in VideoPlayerPlugin.java
A message is displayed when building for android: 
```
flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK
size.
To generate an app bundle, run:
flutter build appbundle --target-platform android-arm,android-arm64,android-x64
Learn more on: https://developer.android.com/guide/app-bundle
To split the APKs per ABI, run:
flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure …
```
=> [video_player] VideoPlayerPlugin.java uses or overrides a deprecated API

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/lib/image_picker.dart, packages/image_picker/image_picker/pubspec.yaml, packages/image_picker/image_picker_platform_interface/CHANGELOG.md, packages/image_picker/image_picker_platform_interface/lib/src/platform_interface/image_picker_platform.dart, packages/image_picker/image_picker_platform_interface/pubspec.yaml
Updated the documentation of getImage() in image_picker.dart and image_picker_platform.dart about Android's disability to preference front/rear camera, because this wasn't specified and caused confusion for people wondering why it didn't work.
[Issue 55644](https://github.com/flutter/flutter/issues/55644) …
=> [image_picker] Updated docs getImage() about preference rear front not working on Android

packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/pubspec.yaml, packages/path_provider/path_provider_windows/ios/path_provider_windows.podspec
- Adds missing iOS podspec to path_provider_windows, which was necessary to publish it (since path_provider doesn't require 1.20+)
- Requires path_provider_windows 0.0.2, not 0.0.1, in path_provider endorsement.
flutter/flutter#41715 …
=> [path_provider] Path provider windows updates

packages/path_provider/path_provider_windows/CHANGELOG.md, packages/path_provider/path_provider_windows/pubspec.yaml
Older versions of Flutter (still supported by path_provider) need a
'pluginClass: none' to avoid "Invalid plugin specification" errors
when parsing a Dart-only desktop plugin like this one.
Fixes https://github.com/flutter/flutter/issues/66158 …
=> [path_provider] Add missing pluginClass: none to path_provider_windows

packages/shared_preferences/shared_preferences_windows/CHANGELOG.md, packages/shared_preferences/shared_preferences_windows/ios/shared_preferences_windows.podspec, packages/shared_preferences/shared_preferences_windows/pubspec.yaml
shared_preferences supports versions older than 1.18, so this plugin
needs the iOS stub to prevent breaking iOS projects via transitive
dependencies when shared_preferences endorses the Windows implementation.
flutter/flutter#41719 …
=> [shared_preferences] Add iOS stub to shared_preferences_windows

packages/connectivity/connectivity_macos/CHANGELOG.md, packages/connectivity/connectivity_macos/macos/Classes/ConnectivityPlugin.swift, packages/connectivity/connectivity_macos/macos/Classes/IPHelper.h, packages/connectivity/connectivity_macos/pubspec.yaml
The source headers were mistakenly marked as Apache rather than the BSD license the plugin carries.
=> [Connectivity] Fix mistake in license headers

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/README.md, packages/image_picker/image_picker/pubspec.yaml
New example code for image_picker.dart plugin as per flutter/flutter#65914
Added new example code to the README.md file for the image_picker.dart plugin which was earlier throwing an error when the image was not selected.
Resolves flutter/flutter#65914 …
=> [image_picker] Updated README.md with new example

packages/path_provider/path_provider_macos/CHANGELOG.md, packages/path_provider/path_provider_macos/macos/Classes/PathProviderPlugin.swift, packages/path_provider/path_provider_macos/pubspec.yaml
MacOS source headers were mistakenly marked as Apache license rather than BSD.
=> [path_provider] Fix mistake in license headers

packages/path_provider/path_provider_windows/CHANGELOG.md, packages/path_provider/path_provider_windows/lib/path_provider_windows.dart, packages/path_provider/path_provider_windows/lib/src/folders_stub.dart, packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart, packages/path_provider/path_provider_windows/lib/src/path_provider_windows_stub.dart, packages/path_provider/path_provider_windows/pubspec.yaml
The fake didn't have getFolder, so if a test of something using
path_provider_windows (such as shared_preferences_windows) had a fake
that overrode getFolder, the analyzer would complain about overriding a
non-existent method. This adds it to avoid that analyzer warning.
It also fixes a minor issue introduced in the previous change, where
folder.dart was accidentally made internal rather than public.
None …
=> [path_provider_windows] Add missing method to fake

packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/pubspec.yaml
path_provider_windows 0.0.2 causes issues both for web projects and for
projects built with Flutter 1.17 or earlier. This requires 0.0.4+ to
ensure fixes for both issues are included.
https://github.com/flutter/flutter/issues/66158
https://github.com/flutter/flutter/issues/66143 …
=> [path_provider] Update endorsed Windows version

packages/flutter_plugin_android_lifecycle/CHANGELOG.md, packages/flutter_plugin_android_lifecycle/android/build.gradle, packages/flutter_plugin_android_lifecycle/example/android/app/build.gradle, packages/flutter_plugin_android_lifecycle/pubspec.yaml
Update android sdk to 29. This plugin is a dependency of other plugins, so it has to be updated and published before updating other plugins.
part of https://github.com/flutter/flutter/issues/64396
[CLA]: …
=> [flutter_plugin_android_lifecycle] update to android 29

packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/url_launcher/url_launcher_web/test/README.md, packages/url_launcher/url_launcher_web/test/lib/main.dart, packages/url_launcher/url_launcher_web/test/pubspec.yaml, packages/url_launcher/url_launcher_web/test/run_test, packages/url_launcher/url_launcher_web/test/test_driver/url_launcher_web_integration.dart, packages/url_launcher/url_launcher_web/test/test_driver/url_launcher_web_integration_test.dart, packages/url_launcher/url_launcher_web/test/web/index.html
This change removes the dependency that url_launcher_web has in package:platform_detect to achieve a [null-safe gallery app](https://github.com/flutter/flutter/issues/66395).
It also migrates the unit tests to run with `flutter drive`, instead of flutter test with --platform.
* Fixes https://github.com/flutter/flutter/issues/66385 …
=> [url_launcher_web] Remove package:platform_detect

packages/connectivity/connectivity/ios/Classes/FLTConnectivityPlugin.m, packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/android/build.gradle, packages/path_provider/path_provider/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java, packages/path_provider/path_provider/pubspec.yaml
All `path` operations in the Android implementation access disk so they need to be done off the UI thread as per Android best practices.
=> [path_provider_android] Move Path operations to background thread

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/lib/url_launcher.dart, packages/url_launcher/url_launcher/pubspec.yaml
This PR adds extra documentation to the `canLaunch` method, explaining that (from Android API 30) `false` is returned when the package visibility is not managed properly. 
Starting from Android API 30, apps should explicitly list which other apps it wants to query or interact with, by specifying them in the AndroidManifest.xml file. More information can be found in the [Manage package visibility](https://developer.android.com/training/basics/intents/package-visibility) article in the Android documentation. 
flutter/flutter#63727
- [] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors …
=> [url_launcher] Document why canLaunch can return false on Android API 30

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player/test/video_player_test.dart
This should just have been part of https://github.com/flutter/plugins/pull/3031 instead, my bad!
cc @ditman 
* https://github.com/flutter/plugins/pull/3081#discussion_r495296875
* https://github.com/flutter/plugins/pull/3032#issuecomment-699199586
This prepares a smooth transition for an upcoming PR instead of locking to an older version 👍 
=> [video_player] Fix tests

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/example/lib/main.dart, packages/in_app_purchase/pubspec.yaml
Documentation typo.
Fixed a typo in an inline comment.
=> [in_app_purchase] Update typo in example main.dart

packages/connectivity/connectivity_for_web/CHANGELOG.md, packages/connectivity/connectivity_for_web/pubspec.yaml
Fix broken homepage URI in pubspec. Also switches from using `homepage` to `repository` – a bit more accurate.
Similar to https://github.com/flutter/flutter/issues/66844
=> [connectivity_for_web] Fix homepage in pubspec.yaml

packages/plugin_platform_interface/CHANGELOG.md, packages/plugin_platform_interface/pubspec.yaml
Fix broken homepage URI in pubspec. Also switches from using `homepage` to `repository` – a bit more accurate.
Fixes https://github.com/flutter/flutter/issues/66844
=> [plugin_platform_interface] Fix homepage in pubspec.yaml

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/README.md, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Bumps the minimally required Flutter SDK to 1.22, starting this version platform views are no longer in developers preview, so the plugin also gets out of developers preview as well.
We also bump the version to 1.0.0 as API stability has been reached.
=> [google_maps_flutter] Out of developers preview, bump to 1.0.0

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/README.md, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
=> [google_maps_flutter] Fix headline in the readme

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m, packages/in_app_purchase/ios/Tests/InAppPurchasePluginTest.m, packages/in_app_purchase/pubspec.yaml
There is a way to send null down to objective-c for the simulatesAskToBuyInSandbox parameter which causes a crash.  This just interprets null as a false.
Related PR: https://github.com/flutter/plugins/pull/3086 - this PR tried to fix things on the Dart side, this one uses the objective-c side.
flutter/flutter#65767 …
=> in_app_purchase: started supported null as a parameter for the simulatesAskToBuyInSandbox

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/lib/platform_interface.dart, packages/webview_flutter/pubspec.yaml
Adding missing doc on public api
=> [webview_flutter] add public documentation.

packages/connectivity/connectivity/test/connectivity_test.dart, packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart, packages/shared_preferences/shared_preferences/test/shared_preferences_test.dart, packages/url_launcher/url_launcher/test/url_launcher_test.dart, packages/video_player/video_player/test/video_player_initialization_test.dart, packages/video_player/video_player/test/video_player_test.dart
This change tells the dart compiler to opt-out of null-safety for the tests of the affected packages (see related issue), until they've been properly migrated.
Fixes https://github.com/flutter/flutter/issues/67332
[CLA]: …
=> [multiple] Opt-out of null-safety

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/google_maps_controller_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/shapes_integration.dart
This PR addresses two issues.
The first issue is that initial Polylines/Polygons (passed through the Map Widget) were not being parsed correctly because of a run-time type error when converting their array of `LatLng` points.
While investigating the above issue, I found out that the code was not parsing correctly the Colors passed by the user for polygons, polylines and circles, and fixed that too.
* Fixes https://github.com/flutter/flutter/issues/65152
* Fixes https://github.com/flutter/flutter/issues/67032 …
=> [google_maps_flutter_web] Fix convert.dart issues

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/CustomSSLSocketFactory.java, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java, packages/video_player/video_player/pubspec.yaml
- Enable TLSv1.1 & TLSv1.2 in low API version.
flutter/flutter#62748
=> [video_player] Fix SSLProtocolException for low API version

packages/integration_test/CHANGELOG.md, packages/integration_test/lib/integration_test.dart, packages/integration_test/pubspec.yaml
Add a `watchPerformance` method to `IntegrationTestWidgetsFlutterBinding` to implement performance metric collection as we do on `flutter_driver` test by `traceAction` and `TimelineSummary`. This is also to reland #2906 (revert #2917)
This is the first step of flutter/flutter#63537
[pub …
=> [integration_test] Add watchPerformance

.cirrus.yml, analysis_options.yaml, packages/plugin_platform_interface/CHANGELOG.md, packages/plugin_platform_interface/lib/plugin_platform_interface.dart, packages/plugin_platform_interface/pubspec.yaml, packages/plugin_platform_interface/test/plugin_platform_interface_test.dart, script/incremental_build.sh
Migration to null safety.
Companion PR: https://github.com/flutter/plugin_tools/pull/110
https://github.com/flutter/flutter/issues/66395
=> [plugin_platform_interface] Migrate to null safety

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/example/integration_test/video_player_test.dart, packages/video_player/video_player/lib/video_player.dart, packages/video_player/video_player/pubspec.yaml
Currently, when `play` is called twice, i.e. `play` is called again before `pause`, the `_timer` leaks, which can create very frequent calls of listener **and** more importantly will never stop notifying, even when the video is paused.
I would say that this is a pretty severe issue as calling `play` on a controller can easily happen more than once and should not have side effects.
I tried to add the following integration test:
```dart
testWidgets('cancels timers', (WidgetTester tester) async {
await _controller.initialize();
var eventCount = 0;
final listener = () => eventCount++;
_controller.addListener(listener);
// Play for a second, then pause, and then wait a second.
await _controller.play();
// Call play twice to test if timers leak.
await _controller.play();
await …
```
=> [video_player] fix Timer Leak

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/example/ios/Podfile, packages/in_app_purchase/example/ios/Runner.xcodeproj/project.pbxproj, packages/in_app_purchase/pubspec.yaml
Test target wasn't building in example app because it wasn't inheriting search paths from the Runner target (which allows the linker to find the plugin frameworks, plus Flutter framework).  Also add OCMock dependency to match test_spec podspec.
Fixes https://github.com/flutter/flutter/issues/67175
=> [in_app_purchase] Add example test target to Podfile, add OCMock dependency

analysis_options.yaml, packages/plugin_platform_interface/analysis_options.yaml, script/incremental_build.sh
This PR reverts the current behavior, which applies the `non-nullable` analysis to all the plugins.
=> Configure analyzer for plugins that are migrated to nnbd

packages/share/CHANGELOG.md, packages/share/android/build.gradle, packages/share/android/src/main/java/io/flutter/plugins/share/Share.java, packages/share/example/android/app/build.gradle, packages/share/example/android/build.gradle, packages/share/pubspec.yaml
- Replace deprecated `Environment.getExternalStorageDirectory()` call on Android.
- Upgrade to Android Gradle plugin 3.5.0 & target API level 29.
https://github.com/flutter/flutter/issues/68011
https://github.com/flutter/flutter/issues/66513 …
=> [share] Replace deprecated Environment.getExternalStorageDirectory() call on Android.

packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/analysis_options.yaml, packages/url_launcher/url_launcher_platform_interface/lib/method_channel_url_launcher.dart, packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml, packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart, script/incremental_build.sh
Migration of "url_launcher_platform_interface" to null safety.
Note: I had to pin the "plugin_platform_interface" package to the git repo since version 1.1.0-nullsafety is not yet released (see companion PR #3115). I have decorated the line with a `# TODO (mvanbeusekom):` comment. Please let me know if I should solve this in a different way.
flutter/flutter#66395 …
=> [url_launcher] Url launcher platform interface null safety

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/markers_integration.dart
This change wraps the `sanitizeHtml` call in a helper function that provides a default implementation for a new parameter that was recently added to its API.
* Fixes: https://github.com/flutter/flutter/issues/67854
* Root cause: https://github.com/google/dart-neats/issues/71 …
=> [google_maps_flutter_web] Fix InfoWindow snippets.

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/lib/url_launcher.dart, packages/url_launcher/url_launcher/pubspec.yaml
Added a clear documentation of the fact that the `headers` parameter at the `launch` method is not fully supported when using an external browser.
[Issue 61332](https://github.com/flutter/flutter/issues/61332). 
[CLA]: …
=> [url_launcher] Improved documentation of the `headers` parameter.

packages/device_info/device_info/pubspec.yaml, packages/device_info/device_info_platform_interface/pubspec.yaml
Updated the dependencies from local to git.
=> [device_info][device_info_platform_interface] update to git deps

packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/lib/link.dart, packages/url_launcher/url_launcher_platform_interface/lib/method_channel_url_launcher.dart, packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml, packages/url_launcher/url_launcher_platform_interface/test/link_test.dart, packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart
- **[THIS] Prepare url_launcher for the Link widget.**
- [PENDING] [web] Implement Link for web (https://github.com/flutter/plugins/pull/3155).
- [COMING] Implement Link for native platforms (link TBD).
- [COMING] Update url_launcher example to show usage of Links (link TBD).
The design has been discussed in:
1. https://flutter.dev/go/link-widget
1. https://flutter.dev/go/link-widget-2
Issues:
- https://github.com/flutter/flutter/issues/59690
- https://github.com/flutter/flutter/issues/44865
- https://github.com/flutter/flutter/issues/54281
=> Prepare url_launcher for the Link widget

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/analysis_options.yaml, packages/video_player/video_player/example/integration_test/video_player_test.dart, packages/video_player/video_player/example/lib/main.dart, packages/video_player/video_player/example/pubspec.yaml, packages/video_player/video_player/example/test_driver/integration_test.dart, packages/video_player/video_player/example/test_driver/video_player.dart, packages/video_player/video_player/example/test_driver/video_player_test.dart, packages/video_player/video_player/lib/src/closed_caption_file.dart, packages/video_player/video_player/lib/src/sub_rip.dart, packages/video_player/video_player/lib/video_player.dart, packages/video_player/video_player/pigeons/messages.dart, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player/test/sub_rip_file_test.dart, packages/video_player/video_player/test/video_player_initialization_test.dart, packages/video_player/video_player/test/video_player_test.dart, packages/video_player/video_player_platform_interface/CHANGELOG.md, packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart, packages/video_player/video_player_platform_interface/pubspec.yaml, packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart, packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/analysis_options.yaml, packages/video_player/video_player_web/lib/video_player_web.dart, packages/video_player/video_player_web/pubspec.yaml, packages/video_player/video_player_web/test/video_player_web_test.dart, script/incremental_build.sh
Migrates video player to null safety.
I made some API changes like the use of `Duration.zero`/`Size.zero` instead of `null` for defaults in `VideoPlayerValue` and `Caption`.
=> [video_player] Migrate video player to null safety

packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/analysis_options.yaml, packages/url_launcher/url_launcher_web/lib/link.dart, packages/url_launcher/url_launcher_web/lib/src/link.dart, packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/url_launcher/url_launcher_web/test/test_driver/url_launcher_web_integration.dart, script/incremental_build.sh
- [COMPLETE] Prepare url_launcher for the Link widget (https://github.com/flutter/plugins/pull/3154).
- **[THIS] [web] Implement Link for web.**
- [COMING] Implement Link for native platforms (link TBD).
- [COMING] Update url_launcher example to show usage of Links (link TBD).
The design has been discussed in:
1. https://flutter.dev/go/link-widget
1. https://flutter.dev/go/link-widget-2
Issues:
Fixes https://github.com/flutter/flutter/issues/68545
- https://github.com/flutter/flutter/issues/59690
- https://github.com/flutter/flutter/issues/44865
- https://github.com/flutter/flutter/issues/54281
=> [web] Implement Link for web

packages/camera/CHANGELOG.md, packages/camera/example/lib/main.dart, packages/camera/pubspec.yaml, packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/lib/main.dart, packages/webview_flutter/pubspec.yaml
Fixes the ci failure:
```
Checking project camera...
info - 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. at example/lib/main.dart:275:31 - (deprecated_member_use)
```
https://cirrus-ci.com/task/4518227873103872?command=main#L292
This only fix the deprecation warning in camera and webview_flutter, the error in url_launcher_web should be fixed with https://github.com/flutter/plugins/pull/3155
=> Fix deprecation warning in ci failure

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java, packages/url_launcher/url_launcher/pubspec.yaml
The url_launcher overrides the deprecated `shouldOverrideUrlLoading(WebView view, String url)` method to be backwards compatible with versions before Android API 24. This however currently displays the warning `WebViewActivity.java uses or overrides a deprecated API.` when building for Android. This is causing some problems for developers who treat these warnings as errors as part of their build configuration.
This PR addresses this issue by annotating the `shouldOverrideUrlLoading(WebView view, String url)` method with the @SuppressWarnings("deprecation") attribute.
[Issue 60986](https://github.com/flutter/flutter/issues/60986)
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick …
=> [url_launcher] suppress a `uses or overrides a deprecated API` warning in WebViewActivity

packages/connectivity/connectivity/ios/Classes/FLTConnectivityPlugin.m, packages/connectivity/connectivity/test/connectivity_test.dart, packages/device_info/device_info/example/integration_test/device_info_test.dart, packages/device_info/device_info/example/test_driver/integration_test.dart, packages/device_info/device_info_platform_interface/test/method_channel_device_info_test.dart, packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart, packages/shared_preferences/shared_preferences/test/shared_preferences_test.dart, packages/url_launcher/url_launcher/example/integration_test/url_launcher_test.dart, packages/url_launcher/url_launcher/example/lib/main.dart, packages/url_launcher/url_launcher/example/linux/flutter/generated_plugin_registrant.cc, packages/url_launcher/url_launcher/example/test/url_launcher_example_test.dart, packages/url_launcher/url_launcher/example/test_driver/integration_test.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher/test/url_launcher_test.dart, packages/url_launcher/url_launcher_linux/CHANGELOG.md, packages/url_launcher/url_launcher_linux/pubspec.yaml, packages/url_launcher/url_launcher_macos/CHANGELOG.md, packages/url_launcher/url_launcher_macos/pubspec.yaml, packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/analysis_options.yaml, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/url_launcher/url_launcher_windows/CHANGELOG.md, packages/url_launcher/url_launcher_windows/pubspec.yaml, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player_web/pubspec.yaml
* Cleans up some of the code, so it's consistent.  
* Fixes some checks. (hopefully all)
=> [nnbd] Various fixes

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/pubspec.yaml
This pull request adds to the work of @panmari (#2965) and @Gioxxy (#2871) and adds a null reference check to make sure the `pictureImageReader` is not null before accessing. It also adds additional documentation to the README.md file explaining about managing App lifecycle changes in relation to the camera plugin (required since release 0.5.0 of the plugin). 
These changes have been discussed in [issue flutter/flutter#19595](https://github.com/flutter/flutter/issues/19595#issuecomment-700930124).
- Fixes flutter/flutter#19595
- Closes #2871 
- Closes #2965 
Does your PR require plugin users to manually update their …
=> [camera] Add null check before starting preview

packages/url_launcher/url_launcher_linux/CHANGELOG.md, packages/url_launcher/url_launcher_linux/linux/url_launcher_plugin.cc, packages/url_launcher/url_launcher_linux/pubspec.yaml
The plugin code uses strcmp, so should include cstring. Currently this
works only due to transitive includes that we can't count on being
present.
None
=> [url_launcher_linux] Add missing #include

packages/connectivity/connectivity/CHANGELOG.md, packages/connectivity/connectivity/example/lib/main.dart, packages/connectivity/connectivity/example/test_driver/integration_test/connectivity_test.dart, packages/connectivity/connectivity/integration_test/connectivity_test.dart, packages/connectivity/connectivity/ios/Classes/FLTConnectivityPlugin.m, packages/connectivity/connectivity/lib/connectivity.dart, packages/connectivity/connectivity/pubspec.yaml, packages/connectivity/connectivity/test/connectivity_test.dart
Bump the version to 1.0.0, announce deprecations to all wifi related APIs
=> [connectivity] announce 1.0, deprecate wifi APIs

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/lib/link.dart, packages/url_launcher/url_launcher/lib/src/link.dart, packages/url_launcher/url_launcher/lib/url_launcher.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher/test/link_test.dart
- [COMPLETE] Prepare url_launcher for the Link widget (https://github.com/flutter/plugins/pull/3154).
- [COMPLETE] [web] Implement Link for web (https://github.com/flutter/plugins/pull/3155).
- **[THIS] Implement Link for native platforms.**
- [COMING] Update url_launcher example to show usage of Links (link TBD).
The design has been discussed in:
1. https://flutter.dev/go/link-widget
1. https://flutter.dev/go/link-widget-2
Issues:
Fixes https://github.com/flutter/flutter/issues/59690
Fixes https://github.com/flutter/flutter/issues/44865
Fixes https://github.com/flutter/flutter/issues/54281
=> Implement Link for native platforms

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart, packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_controller.dart, packages/google_maps_flutter/google_maps_flutter_web/lib/src/marker.dart, packages/google_maps_flutter/google_maps_flutter_web/lib/src/markers.dart, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/google_maps_controller_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/markers_integration.dart
This PR addresses:
* InfoWindows don't render their 'snippet' when loaded as Initial Geometry (passed to the GoogleMap Widget directly)
* InfoWindows don't propagate click events (turns out, the JS SDK doesn't offer that event, so we need to fake it)
* GoogleMapController.getLatLng() returns a bogus LatLng (turns out, we weren't using the right formula in that method!).
In order to synthesize the click event on the InfoWindow contents, this PR migrates the InfoWindow contents from being an HTML string to being something generated with dart:html. I had to update a previous test slightly to account for this difference.
Fixes https://github.com/flutter/flutter/issues/67854
Fixes https://github.com/flutter/flutter/issues/67289
Fixes https://github.com/flutter/flutter/issues/67606
Before you …
=> [google_maps_flutter_web] Fix InfoWindows and getLatLng.

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/MethodCallHandlerImpl.java, packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncher.java, packages/url_launcher/url_launcher/android/src/test/java/io/flutter/plugins/urllauncher/MethodCallHandlerImplTest.java, packages/url_launcher/url_launcher/pubspec.yaml
Currently on android when you call the `launch` method with an URL of wich there isn't any app installed that can open this URL,  java will throw an `ActivityNotFoundException`. The user can't catch this exception savely in flutter because it was never catched in java.
This PR catches this Exception in java (wich is recommended in the documentation[ here](https://developer.android.com/training/basics/intents/package-visibility-use-cases#open-urls-browser-or-other-app)).
It gives the user the ability to savely catch this exception in flutter.
[Issue 66826](https://github.com/flutter/flutter/issues/66826)
Does your PR …
=> [url_launcher] Handling the ActivityNotFoundExeption.

packages/url_launcher/url_launcher/lib/src/link.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher/test/link_test.dart, packages/url_launcher/url_launcher_platform_interface/lib/link.dart, packages/url_launcher/url_launcher_platform_interface/lib/method_channel_url_launcher.dart, packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart, packages/url_launcher/url_launcher_platform_interface/test/link_test.dart
Null safety migration for https://github.com/flutter/plugins/pull/3177
=> [url_launcher] Migrates Link to null safety

.cirrus.yml
Enable XCTest in cirrus. 
**This PR will be merged to the xctest branch first.**
As it for now, it skips all the plugins.
Presubmit xctests was successful in https://github.com/flutter/plugins/pull/3188, which tests a UITest in share plugin.
I wanted to land this to test post submit, especially testing if skipping works properly.
=> enable xctest in .cirrus.yml

packages/android_alarm_manager/example/lib/main.dart
`display1` is deprecated.
so we should change to `headline4`. …
=> [android_alarm_manager] deprecated display1

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/android/build.gradle, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java, packages/video_player/video_player/example/android/app/build.gradle, packages/video_player/video_player/example/android/build.gradle, packages/video_player/video_player/example/android/gradle/wrapper/gradle-wrapper.properties, packages/video_player/video_player/pubspec.yaml
- Android: Upgrade ExoPlayer to 2.12.1.
https://github.com/flutter/flutter/issues/36375
=> [video_player] Upgrade ExoPlayer

packages/android_alarm_manager/CHANGELOG.md, packages/android_alarm_manager/example/test_driver/integration_test.dart, packages/android_alarm_manager/pubspec.yaml
This workaround is no longer necessary after https://github.com/flutter/flutter/pull/65703
=> Remove unnecessary work around from test in prep for vm_service migration

.gitignore
This should also be updated in the Flutter tool templates
=> Exclude generated_plugin_registrant.cc

packages/wifi_info_flutter/wifi_info_flutter/CHANGELOG.md, packages/wifi_info_flutter/wifi_info_flutter/android/src/main/java/io/flutter/plugins/wifi_info_flutter/WifiInfoFlutterPlugin.java, packages/wifi_info_flutter/wifi_info_flutter/pubspec.yaml
In this PR, I have fixed the method channel in the android implementation of the plugin.
In platform interface it is : `plugins.flutter.io/wifi_info_flutter`
In Android implementation it was : `plugins.flutter.io/wifi_flutter_info`
In Android implementation it is now : `plugins.flutter.io/wifi_info_flutter`
Fixes https://github.com/flutter/flutter/issues/69073 …
=> [wifi_info_flutter] Method channel name fixed for android

packages/camera/CHANGELOG.md, packages/camera/README.md, packages/camera/pubspec.yaml
To make sure no developers try to find out why the a video with audio on an Android emulator isn't working properly, I added it to the README.md.
[Issue 42309](https://github.com/flutter/flutter/issues/42309#)
[CLA]: …
=> [camera] Added documentation about video not working correctly on Android emulators

packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
Fixes issue with video_player plugins throws error when playing an asset file on android.
[flutter/flutter#66627](https://github.com/flutter/flutter/issues/66627)
=> Fixes Playing video from asset on Android

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapBuilder.java, packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java, packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapFactory.java, packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java, packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/LifecycleProvider.java, packages/google_maps_flutter/google_maps_flutter/example/android/app/src/test/java/io/flutter/plugins/googlemaps/GoogleMapControllerTest.java, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Overhaul lifecycle management in GoogleMapsPlugin.
GoogleMapController is now uniformly driven by implementing DefaultLifecycleObserver. That observer is registered to a lifecycle passed via the new LifecycleProvider interface, which has 3 implementations:
1. For v2 plugin registration, GoogleMapsPlugin implements the interface and holds the lifecycle in a field, which is itself controlled by ActivityAware methods.
2. For v1 plugin registration, if the activity implements LifecycleOwner, it's lifecycle is used directly.
3. For v1 plugin registration, if the activity does not implement LifecycleOwner, a proxy lifecycle is created via ActivityLifecycleCallbacks.
I'm suspicious that there may still be a bug where a GoogleMapController instance can be shared across multiple activities and …
=> [google_maps_flutter] Overhaul lifecycle management in GoogleMapsPlugin

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/pubspec.yaml
Follow-up for https://github.com/flutter/plugins/pull/3220 (forgot to bump in that PR).
=> [in_app_purchase] Bump version

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/lib/src/markers.dart, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/markers_integration.dart
Currently google_maps_flutter_web shows multiple infoWindow . This PR will make it show only single infoWindow.
Fixes flutter/flutter#67380
=> [google_maps_flutter_web] show only single infoWindow

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/lib/src/closed_caption_file.dart, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player/test/closed_caption_file_test.dart, packages/video_player/video_player/test/video_player_test.dart
This is causing a failure in https://github.com/flutter/flutter/pull/69344
=> [video_player] Add toString() to Caption

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java, packages/video_player/video_player/example/android/app/build.gradle, packages/video_player/video_player/example/android/app/src/test/java/io/flutter/plugins/videoplayerexample/FlutterActivityTest.java, packages/video_player/video_player/example/integration_test/video_player_test.dart, packages/video_player/video_player/pubspec.yaml
- Android: Dispose video players when app is closed.
https://github.com/flutter/flutter/issues/69605
=> [video_player] Android: Dispose video players when app is closed

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/lib/webview_flutter.dart, packages/webview_flutter/pubspec.yaml
See issue: https://github.com/flutter/flutter/issues/53490
Fix: https://github.com/flutter/flutter/issues/67541
=> [webview_flutter] update documentation to indicate gesture handling issues on iOS 13.4 and 13.5

packages/camera/CHANGELOG.md, packages/camera/lib/camera.dart, packages/camera/pubspec.yaml, packages/camera/test/camera_test.dart
Currently when you call `CameraController.Dispose()` there is no way of knowing whether you disposed that CameraController.
With this PR, the user can check if that CameraController has been disposed, by getting `CameraController.isDisposed`.
Since the current `test/camera_test.dart` file contains test for the `CameraController` class located in the `lib/new/src/camera_controller.dart` I have moved it into the `test/new/camera_test.dart` sub folder. 
I have added a new `test/camera_test.dart` file which contains the unit tests covering the new `isDisposed` property which was added to the `CameraController` class located in the current `lib/camera.dart` implementation.
Additionally I have added unit tests to the `test/new/camera_test.dart` file to ensure the `isDisposed` property (already) …
=> [Camera] Made CameraController.isDisposed publicly accessible. Added unit Tests for the new implementation.

packages/file_selector/file_selector_platform_interface/CHANGELOG.md, packages/file_selector/file_selector_platform_interface/lib/src/types/x_type_group/x_type_group.dart, packages/file_selector/file_selector_platform_interface/pubspec.yaml, packages/file_selector/file_selector_platform_interface/test/x_type_group_test.dart
This was restricted under the assumption that there was no reason for an
empty group to exist, but that's not actually true; on platforms with
selectable groups in the native UI, it may be useful to provide
specific options as well as a fallback option (e.g., "Text files" and
"All files").
None …
=> [file_selector] Allow empty type groups

packages/device_info/device_info_platform_interface/CHANGELOG.md, packages/device_info/device_info_platform_interface/lib/model/android_device_info.dart, packages/device_info/device_info_platform_interface/lib/model/ios_device_info.dart, packages/device_info/device_info_platform_interface/pubspec.yaml, packages/device_info/device_info_platform_interface/test/method_channel_device_info_test.dart
Based on the discussion. `baseOS`, `previewSdkInt`, and `securityPatch` are indeed nullable depending on the Android API level. 
=> [device_info_platform_interface] Remove default types and correct nullable types

packages/integration_test/README.md
This is the correct link: https://github.com/flutter/plugins/blob/master/packages/integration_test/example/test_driver/extended_integration_test.dart
=> Fix broken link

packages/integration_test/CHANGELOG.md, packages/integration_test/README.md, packages/integration_test/pubspec.yaml, packages/shared_preferences/shared_preferences/CHANGELOG.md, packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/shared_preferences/pubspec.yaml, packages/shared_preferences/shared_preferences_linux/CHANGELOG.md, packages/shared_preferences/shared_preferences_linux/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/shared_preferences_linux/pubspec.yaml, packages/shared_preferences/shared_preferences_windows/CHANGELOG.md, packages/shared_preferences/shared_preferences_windows/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/shared_preferences_windows/pubspec.yaml, packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/example/integration_test/url_launcher_test.dart, packages/url_launcher/url_launcher/pubspec.yaml, packages/url_launcher/url_launcher_linux/CHANGELOG.md, packages/url_launcher/url_launcher_linux/example/integration_test/url_launcher_test.dart, packages/url_launcher/url_launcher_linux/pubspec.yaml, packages/url_launcher/url_launcher_macos/CHANGELOG.md, packages/url_launcher/url_launcher_macos/example/integration_test/url_launcher_test.dart, packages/url_launcher/url_launcher_macos/pubspec.yaml, packages/url_launcher/url_launcher_windows/CHANGELOG.md, packages/url_launcher/url_launcher_windows/example/integration_test/url_launcher_test.dart, packages/url_launcher/url_launcher_windows/pubspec.yaml
Only `testWidgets` is supported for testing for `package:integration_test`. Errors thrown in other declarers will not be caught and reported.
Also added a note to mention this in the README for `package:integration_test`
flutter/flutter#60943
=> Use testWidgets instead of test to fix failures not surfacing on CI

packages/android_alarm_manager/README.md, packages/android_alarm_manager/example/android/app/src/main/AndroidManifest.xml
fix AndroidManifest.xml for android lint issue "XML tag has empty body" on example project and README.md
=> [android_alarm_manager] fix AndroidManifest.xml for android lint issue "XML tag has empty body"

packages/integration_test/CHANGELOG.md, packages/integration_test/pubspec.yaml
Bumps Integration test to 1.0.0
=> bump integration test to 1.0.0

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/pubspec.yaml
This plugin uses deprecated APIs if targeting Android 30:
```
Device has been deprecated
cameraDevice.createCaptureSession(surfaceList, callback, null);
^
1 warning
```
Fixes https://github.com/flutter/flutter/issues/69883 …
=> [camera] Support Android 30

packages/camera/camera_platform_interface/CHANGELOG.md, packages/camera/camera_platform_interface/LICENSE, packages/camera/camera_platform_interface/README.md, packages/camera/camera_platform_interface/lib/camera_platform_interface.dart, packages/camera/camera_platform_interface/lib/src/events/camera_event.dart, packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart, packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart, packages/camera/camera_platform_interface/lib/src/types/camera_description.dart, packages/camera/camera_platform_interface/lib/src/types/camera_exception.dart, packages/camera/camera_platform_interface/lib/src/types/resolution_preset.dart, packages/camera/camera_platform_interface/lib/src/types/types.dart, packages/camera/camera_platform_interface/lib/src/utils/utils.dart, packages/camera/camera_platform_interface/pubspec.yaml, packages/camera/camera_platform_interface/test/camera_platform_interface_test.dart, packages/camera/camera_platform_interface/test/events/camera_event_test.dart, packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart, packages/camera/camera_platform_interface/test/types/camera_description_test.dart, packages/camera/camera_platform_interface/test/types/camera_exception_test.dart, packages/camera/camera_platform_interface/test/types/resolution_preset_test.dart, packages/camera/camera_platform_interface/test/utils/method_channel_mock.dart, packages/camera/camera_platform_interface/test/utils/utils_test.dart
Adds CameraPlatform which can be overridden to implement camera on other platforms (which may not want to use MethodChannels).
The PR is marked as draft so it can serve as a starting point on discussing the platform interface for the camera plugin. I have followed the article "How To Write a Flutter Web Plugin: Part 2" as a guide on which steps to take to migrate the camera plugin to the federated architecture. Below is an overview of steps: …
=> [camera] Add `camera_platform_interface` package

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/DartMessengerTest.java, packages/camera/camera/pubspec.yaml
Suppresses the unchecked cast warning that is generated in the `DartMessengerTest` class when forcing the outcome of the `decodeEnvelope` method to `Map<String, String>`. This is currently blocking users from running the JAVA unit tests since the won't compile due to the `-Werror` switch, treating warnings as errors and not letting the test class be compiled.
flutter/flutter#71709 …
=> [camera] Suppress unchecked cast warning in java test

analysis_options.yaml
With NNBD `assert(foo != null)` for a non nullable `foo` generates an analysis error.
However as long as we support mixed-mode we want these asserts it, so disabling the check.
=> Update analysis options for nnbd

packages/camera/camera_platform_interface/CHANGELOG.md, packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart, packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart, packages/camera/camera_platform_interface/pubspec.yaml, packages/camera/camera_platform_interface/test/camera_platform_interface_test.dart, packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart
Adds the required methods necessary to implement zoom support to the camera_platform_interface. Once this PR has landed packages implementing the camera_platform_interface will be able to add zoom support to the camera implementations.
This PR is a start to implement zoom support as requested in issue: flutter/flutter#28694 …
=> [camera] Add zoom support to platform interface

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/README.md, packages/url_launcher/url_launcher/pubspec.yaml
the code sample at this [link](https://pub.dev/packages/url_launcher#example) and reported below is clearly broken
```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
void main() {
runApp(Scaffold(
body: Center(
child: RaisedButton(
onPressed: _launchURL,
child: Text('Show Flutter homepage'),
),
),
));
}
_launchURL() async {
const url = 'https://flutter.dev';
if (await canLaunch(url)) {
await launch(url);
} else {
throw 'Could not launch $url';
}
}
```
please consider replacing it with the following
```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
const _url = 'https://flutter.dev';
void main() => runApp(
const MaterialApp(
home: Material(
child: Center(
child: RaisedButton(
onPressed: _launchURL, …
```
=> [documentation] [url_launcher] fix for readme code sample

script/build_all_plugins_app.sh, script/incremental_build.sh, script/nnbd_plugins.sh
Mechanism for disabling the checks on Flutter stable. This needs a PR to the tool.
=> Exclude null-safe plugins from testing on stable

packages/image_picker/image_picker_platform_interface/CHANGELOG.md, packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/html.dart, packages/image_picker/image_picker_platform_interface/pubspec.yaml
Prepare for https://github.com/dart-lang/http/issues/375
=> Pass a Uri to package:http APIs

packages/android_alarm_manager/CHANGELOG.md, packages/android_alarm_manager/pubspec.yaml, packages/android_intent/CHANGELOG.md, packages/android_intent/pubspec.yaml, packages/battery/battery/CHANGELOG.md, packages/battery/battery/pubspec.yaml, packages/battery/battery_platform_interface/CHANGELOG.md, packages/battery/battery_platform_interface/pubspec.yaml, packages/camera/camera/CHANGELOG.md, packages/camera/camera/pubspec.yaml, packages/camera/camera_platform_interface/CHANGELOG.md, packages/camera/camera_platform_interface/pubspec.yaml, packages/connectivity/connectivity/CHANGELOG.md, packages/connectivity/connectivity/pubspec.yaml, packages/connectivity/connectivity_macos/CHANGELOG.md, packages/connectivity/connectivity_macos/pubspec.yaml, packages/connectivity/connectivity_platform_interface/CHANGELOG.md, packages/connectivity/connectivity_platform_interface/pubspec.yaml, packages/cross_file/CHANGELOG.md, packages/cross_file/pubspec.yaml
Align plugins with new templates, removing unused upper constraint
https://github.com/flutter/flutter/pull/68437
=> Update Flutter SDK constraint to match templates; plugins A-C

packages/device_info/device_info/CHANGELOG.md, packages/device_info/device_info/pubspec.yaml, packages/device_info/device_info_platform_interface/CHANGELOG.md, packages/device_info/device_info_platform_interface/pubspec.yaml, packages/espresso/CHANGELOG.md, packages/espresso/pubspec.yaml, packages/file_selector/file_selector/CHANGELOG.md, packages/file_selector/file_selector/pubspec.yaml, packages/file_selector/file_selector_platform_interface/CHANGELOG.md, packages/file_selector/file_selector_platform_interface/pubspec.yaml, packages/flutter_plugin_android_lifecycle/CHANGELOG.md, packages/flutter_plugin_android_lifecycle/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml, packages/google_sign_in/extension_google_sign_in_as_googleapis_auth/CHANGELOG.md, packages/google_sign_in/extension_google_sign_in_as_googleapis_auth/pubspec.yaml, packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/pubspec.yaml, packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md, packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml, packages/google_sign_in/google_sign_in_web/CHANGELOG.md, packages/google_sign_in/google_sign_in_web/pubspec.yaml
Align plugins with new templates, removing unused upper constraint
https://github.com/flutter/flutter/pull/68437
=> Update Flutter SDK constraint to match templates; plugins D-G

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/lib/platform_interface.dart, packages/webview_flutter/lib/src/webview_android.dart, packages/webview_flutter/lib/src/webview_cupertino.dart, packages/webview_flutter/lib/src/webview_method_channel.dart, packages/webview_flutter/lib/webview_flutter.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/test/webview_flutter_test.dart, script/nnbd_plugins.sh
Migrate webview_flutter to nnbd.
=> [webview_flutter] Migrate to nnbd

packages/share/CHANGELOG.md, packages/share/lib/share.dart, packages/share/pubspec.yaml, packages/share/test/share_test.dart, script/nnbd_plugins.sh
Migrate share plugin to null safety.
=> [share] Migrate to null-safety

packages/android_intent/CHANGELOG.md, packages/android_intent/lib/android_intent.dart, packages/android_intent/pubspec.yaml, packages/android_intent/test/android_intent_test.dart, script/nnbd_plugins.sh
Migrate android_intent plugin to nnbd.
=> [android_intent] Migrate to nnbd

packages/camera/camera_platform_interface/CHANGELOG.md, packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart, packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart, packages/camera/camera_platform_interface/lib/src/types/flash_mode.dart, packages/camera/camera_platform_interface/pubspec.yaml, packages/camera/camera_platform_interface/test/types/flash_mode_test.dart
This PR adds the additional `torch` value to the `FlashModes` enum, which when implemented should turn on the flash light and keep it on until it is manually turned-off.
flutter/flutter#19845
flutter/flutter#37853
[CLA]: …
=> [camera_platform_interface] Add torch definition to the FlashModes enum 

packages/camera/camera/CHANGELOG.md, packages/camera/camera/README.md, packages/camera/camera/pubspec.yaml
Updated the README about the minimum iOS version as proposed [here](https://github.com/flutter/plugins/pull/2753). 
PR #2753 should be closed after merging this PR.  
=> [camera] Ios support documentation 

.cirrus.yml
Add `sudo gem install cocoapods` to Cirrus to stay on latest CocoaPods.
https://github.com/flutter/flutter/pull/71170 caused
```
Warning: CocoaPods minimum required version 1.9.0 or greater not installed. Skipping pod install.
CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
CocoaPods not installed or not in valid state.
```
https://cirrus-ci.com/task/5814750833541120?command=build#L51
=> Upgrade CocoaPods in Cirrus

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m, packages/image_picker/image_picker/pubspec.yaml
Fix pod lint error.
This is a temporary fix. Ideally, the plugin should not display a UI with fixed messaging.
=> [image_picker] use LocalizedString to fix lint error.

packages/camera/camera/CHANGELOG.md, packages/camera/camera/ios/Classes/CameraPlugin.m, packages/camera/camera/pubspec.yaml
Added implementation of the `didFinishProcessingPhoto` on iOS which allows saving image metadata (EXIF) on iOS 11 and up. On iOS 10 and below the camera plugin still relies on the `didFinishProcessingBufferSample` method which doesn't provide any metadata. In this case we manually try to determine image orientation based on the accelerometer.
flutter/flutter#39070
[Flutter Style …
=> [camera] Add implementation of didFinishProcessingPhoto callback (iOS)

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/build.gradle, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraZoom.java, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/MethodCallHandlerImpl.java, packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/CameraZoomTest.java, packages/camera/camera/example/android/build.gradle, packages/camera/camera/example/android/gradle/wrapper/gradle-wrapper.properties, packages/camera/camera/example/lib/main.dart, packages/camera/camera/ios/Classes/CameraPlugin.m, packages/camera/camera/lib/src/camera_controller.dart, packages/camera/camera/pubspec.yaml, packages/camera/camera/test/camera_test.dart
Adds zoom support to the camera implementations for Android and iOS. It implements the interfaces defined #3312.
This PR is currently still in draft state, as it still depends on:
- #3302 General platform implementations being merged.
- #3312 Updated `camera_platform_interface` being published to pub.dev.
- flutter/flutter#28694 …
=> [camera] Zoom functionality for Android and iOS

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/lib/image_picker.dart, packages/image_picker/image_picker/pubspec.yaml, packages/image_picker/image_picker/test/image_picker_test.dart
We fixed this in g3 but forgot to push upstream.
We encourage overriding the platform implementation in google3 for tests. The pattern `image_picker` is currently using makes this difficult since there are two sources of truth for the platform instance where there should be one. …
=> [image_picker] Do not copy a static field into another static field

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/lib/url_launcher.dart, packages/url_launcher/url_launcher/pubspec.yaml
The current comment on `launch` method dictates:
```
/// [forceSafariVC] is only used in iOS with iOS version >= 9.0. By default (when unset), the launcher
/// opens web URLs in the Safari View Controller, anything else is opened
/// using the default handler on the platform. If set to true, it opens the
/// URL in the Safari View Controller. If false, the URL is opened in the
/// default browser of the phone.
```
Each value has distinct behavior. The null-safe code defaults this parameter to true which means all apps that are not passing a value to this parameter and trying to open a non-web URL would crash. This PR makes the parameter nullable as it was intended.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). …
=> [url_launcher] forceSafariVC should be nullable to avoid breaking change

packages/camera/camera/CHANGELOG.md, packages/camera/camera/lib/src/camera_controller.dart, packages/camera/camera/pubspec.yaml
The signature of the `CameraController.takePicture` method was updated in version 0.6.0, however the API documentation still described the old `path` parameter which has been removed.
Resolves flutter/flutter#72653
[CLA]: …
=> [camera] Fix API documentation of the `CameraController.takePicture` method

packages/cross_file/CHANGELOG.md, packages/cross_file/lib/src/types/base.dart, packages/cross_file/lib/src/types/html.dart, packages/cross_file/lib/src/types/io.dart, packages/cross_file/pubspec.yaml
Make sure the `saveTo` method returns a `Future` making it clear to users that the method can be awaited. Previous version was marked `async` only which could still be awaited but this is not clear to most users.
Resolves flutter/flutter#72652 …
=> [cross_file] Make sure saveTo returns a Future

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/types/FlashMode.java, packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/types/FlashModeTest.java, packages/camera/camera/example/lib/main.dart, packages/camera/camera/ios/Classes/CameraPlugin.m, packages/camera/camera/pubspec.yaml, packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart
Adds implementations for torch mode for Android and iOS. It implements the interfaces defined in #3326.
~~This PR is currently still in draft state, as it still depends on:~~
- ~~#3326 Updated camera_platform_interface being published to pub.dev.~~
- ~~#3314 Flash mode implementations being merged.~~
flutter/flutter#19845
flutter/flutter#37853 …
=> [camera] Add implementations for the torch flash mode.

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/PictureCaptureRequest.java, packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/PictureCaptureRequestTest.java, packages/camera/camera/pubspec.yaml
This PR fixes the new flash & torch functionality not currently working for some Android devices, causing picture capture to break.
It has been tested to work with the following devices:
- OnePlus 6T
- LG Nexus 5X
- Samsung Galaxy Tab A 10.5
- flutter/flutter#72649 …
=> [camera] Fix flash/torch not working on some Android devices.

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/pubspec.yaml
Currently, finishing a video recording throws a null pointer exception on Android when a picture has not yet been taken before. This PR fixes the issue, allowing video recordings to be made without taking a picture first.
- flutter/flutter#72649 …
=> [camera] Fix video recording exception on Android

packages/camera/camera_platform_interface/CHANGELOG.md, packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart, packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart, packages/camera/camera_platform_interface/pubspec.yaml, packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart
Adds maxVideoDuration to startVideoRecording for implementation of a maximum video recording length. 
[#23414](https://github.com/flutter/flutter/issues/23414)
- [] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision). …
=> [camera] Added maxVideoDuration to startVideoRecording

packages/camera/camera/CHANGELOG.md, packages/camera/camera/pubspec.yaml, packages/camera/camera/test/camera_test.dart
Updated the dependency on the camera_platform_interface package to `^1.2.0` and solved the analysis warnings in the tests which are mocking the interfaces. This was causing problems in the flutter framework tree (see flutter/flutter#73059).
Resolved flutter/flutter#73059 …
=> [camera] Update camera_platform_interface dependency to 1.2.0

packages/camera/camera/CHANGELOG.md, packages/camera/camera/pubspec.yaml, packages/camera/camera/test/camera_test.dart
Currently, the camera plugin can no longer initialize due to an update to the platform interface. 
This PR fixes this issue by depending on a lower version of the platform interface until the camera plugin itself is updated as well.
- flutter/flutter#73059
- Resolves flutter/flutter#73088
[pub …
=> [camera] Revert platform interface dependency to lower version

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/pubspec.yaml
This pull request fixes a bug with setting auto focus (necessary for the flash feature) which made it impossible on most Android devices to take a picture with the front facing camera.
It also resolves an issue were the preview of the front facing camera is very dark, which had to do with the configured FPS range.
- Resolves flutter/flutter#73160 …
=> [camera] disable auto focus when using front facing camera on Android

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/pubspec.yaml
There's no way to set Camera for Android's `useAutoFocus` property to `true` and it is `false` by default so auto focusing is not working in preview mode. This change sets the `useAutoFocus` property to `true` by default because the changes in the related pull request (#3383) prior to this one ensures the check for auto focus capability and handles it accordingly. 
Follow-up patch for [flutter/flutter#73160](https://github.com/flutter/flutter/issues/73160) …
=> [camera] set useAutoFocus to true by default

packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart, packages/in_app_purchase/lib/src/billing_client_wrappers/enum_converters.g.dart, packages/in_app_purchase/pubspec.yaml, packages/in_app_purchase/test/billing_client_wrappers/billing_client_wrapper_test.dart
Sometimes Google Play will return a response -3 which was not supported causing a crash. This fixes it. This was based off of https://github.com/flutter/plugins/pull/2248 from NikitaZhelonkin with tests added.
Fixes flutter/flutter#43969 …
=> [in_app_purchase] Added serviceTimeout code

packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart
This is needed to unblock the engine -> framework roll
```
Checking project path_provider_windows...
info - 'addressOf' is deprecated and shouldn't be used. Hold on to the pointer backing a struct instead. at lib/src/path_provider_windows_real.dart:126:25 - (deprecated_member_use)
1 issue found; analyzed 11 source files in 6.6s.
```
=> Ignore deprecated_member_use analysis lint

packages/battery/battery_platform_interface/CHANGELOG.md, packages/battery/battery_platform_interface/lib/method_channel/method_channel_battery.dart, packages/battery/battery_platform_interface/pubspec.yaml, packages/battery/battery_platform_interface/test/method_channel_battery_test.dart, script/nnbd_plugins.sh
Migrate battery_plugin_interface to null safety.
=> [battery] Migrate battery_plugin_interface to null safety

.github/PULL_REQUEST_TEMPLATE.md
This is part of a wider contributor docs simplification effort.
=> Sync the PR template to the new style

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player/test/video_player_test.dart, packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
This migrates calls to `defaultBinaryMessenger` to use `ServicesBinding.instance.defaultBinaryMessenger`
The deprecated `defaultBinaryMessenger` is scheduled to be removed in https://github.com/flutter/flutter/pull/73750 …
=> [video_player] Migrate deprecated api

packages/battery/battery/CHANGELOG.md, packages/battery/battery/example/lib/main.dart, packages/battery/battery/example/pubspec.yaml, packages/battery/battery/integration_test/battery_test.dart, packages/battery/battery/pubspec.yaml, packages/battery/battery/test/battery_test.dart, script/nnbd_plugins.sh
Migrate battery to null safety.
=> [battery] Migrate battery to null safety

packages/file_selector/file_selector_web/CHANGELOG.md, packages/file_selector/file_selector_web/ios/file_selector_web.podspec, packages/file_selector/file_selector_web/pubspec.yaml
When attempting to publish the `file_selector_web` plugin, the tool complained that it didn't have an `ios` directory (or a much more recent version of the flutter sdk as a minimum bound):
```
pubspec.yaml allows Flutter SDK version prior to 1.20.0, which does not support having no `ios/` folder.
Please consider increasing the Flutter SDK requirement to ^1.20.0 or higher (environment.sdk.flutter) or create an `ios/` folder.
See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin
pub finished with exit code 1
Publish failed. Exiting.
```
This PR adds the `ios` directory, so the plugin is publishable. …
=> [file_selector_web] Add dummy ios directory.

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/PictureCaptureRequest.java, packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/PictureCaptureRequestTest.java, packages/camera/camera/pubspec.yaml
Taking a picture with the camera plugin causes the app to crash on some Huawei devices.
This is due to Huawei devices triggering the `onCaptureFailed` callback for seemingly irrelevant frames and the plugin handling this as a failure for capture request, even though `onCaptureCompleted` is called afterwards without a problem.
This PR fixes this by ignoring this particular error ([`CaptureFailure.REASON_ERROR`](https://developer.android.com/reference/android/hardware/camera2/CaptureFailure#REASON_ERROR)) and adding a timeout to the picture request, in the unlikely case `onCaptureCompleted` is never called.
Resolves:
- flutter/flutter#73336 …
=> [camera] Fix picture capture causing a crash on some Huawei devices.

packages/camera/camera/CHANGELOG.md, packages/camera/camera/example/lib/main.dart, packages/camera/camera/lib/src/camera_controller.dart, packages/camera/camera/pubspec.yaml, packages/camera/camera/test/camera_image_stream_test.dart, packages/camera/camera/test/camera_test.dart
Currently, when starting a camera in the camera example app on iOS, the user's permission is asked the first time.
This causes the app to become inactive during camera initialization, causing the camera controller to be disposed.
As the camera controller is disposed during initialization, some properties cannot be fetched, resulting in an error being shown to the user.
This PR fixes this issue in the example app, and slightly improves the error feedback given by the camera controller.
- flutter/flutter#73783 …
=> [camera] Fix initialization error in camera example on iOS

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/pubspec.yaml
Fixes NullPointerException when using inner camera on Android Pixel 3 XL.
* https://github.com/flutter/flutter/issues/73922
Crashes in 0.6.4+3 and later versions. 
- This is crash on actual devices, I did not add tests.
NullPointerException on the following line in `Camera.getRegionBoundaries`:
```java
// Get the current distortion correction mode
Integer distortionCorrectionMode =
captureRequestBuilder.get(CaptureRequest.DISTORTION_CORRECTION_MODE);
```
Does not crash with the outer camera. Probably to return under the previous conditions `supportsDistortionCorrection`.
```java
// No distortion correction support
if (android.os.Build.VERSION.SDK_INT < VERSION_CODES.P || !supportsDistortionCorrection()) {
return cameraManager
.getCameraCharacteristics(cameraDevice.getId()) …
```
=> [camera] Fixes crash with using inner camera on some Android devices.

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/pubspec.yaml
Make sure the configured zoom scale is copied over to the final capture builder on Android. Fixes the issue where the preview is zoomed but the final picture is not.
- Resolves #flutter/flutter#73471 …
=> [camera] Copy zoom settings from preview to final capture builder on Android

packages/file_selector/file_selector_platform_interface/CHANGELOG.md, packages/file_selector/file_selector_platform_interface/pubspec.yaml
Bump the [cross_file][1] dependency to use its latest version.  …
=> [file_selector_platform_interface] Bump the cross_file version.

packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/integration_test/google_sign_in_test.dart, packages/google_sign_in/google_sign_in/lib/google_sign_in.dart, packages/google_sign_in/google_sign_in/lib/src/common.dart, packages/google_sign_in/google_sign_in/lib/testing.dart, packages/google_sign_in/google_sign_in/lib/widgets.dart, packages/google_sign_in/google_sign_in/pubspec.yaml, packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart, packages/google_sign_in/google_sign_in/test_driver/integration_test.dart, packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md, packages/google_sign_in/google_sign_in_platform_interface/lib/google_sign_in_platform_interface.dart, packages/google_sign_in/google_sign_in_platform_interface/lib/src/method_channel_google_sign_in.dart, packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart, packages/google_sign_in/google_sign_in_platform_interface/lib/src/utils.dart, packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml, packages/google_sign_in/google_sign_in_platform_interface/test/google_sign_in_platform_interface_test.dart, packages/google_sign_in/google_sign_in_platform_interface/test/method_channel_google_sign_in_test.dart
Migrate google_sign_in interface and the frontend to nnbd.
This is a draft PR. I have not migrated web and frontend seems to depend on it as such I suspect the pub resolution won't work.
[CLA]: …
=> [google_sign_in] Migrate to nnbd

packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/pubspec.yaml, packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/pubspec.yaml
Add some documentation to the CHANGELOG to mention that the plugin doesn't support web in the current prerelease state.
Fixes https://github.com/flutter/flutter/issues/72239
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking …
=> [google_sign_in, url_launcher] Document unendorsement of web.

packages/plugin_platform_interface/CHANGELOG.md, packages/plugin_platform_interface/lib/plugin_platform_interface.dart, packages/plugin_platform_interface/pubspec.yaml, packages/plugin_platform_interface/test/plugin_platform_interface_test.dart
=> [plugin_platform_interface] Use Mockito nnbd

packages/shared_preferences/shared_preferences_windows/CHANGELOG.md, packages/shared_preferences/shared_preferences_windows/pubspec.yaml
shared_preferences_windows depends on path_provider_windows, and both
use 'ffi'. This relaxes the 'ffi' version constraint on
shared_preferences_windows to allow path_provider_windows to be migrated
to null-safety (which requires updating to the nullsafe version of ffi).
Part of https://github.com/flutter/flutter/issues/70229
[CLA]: …
=> Windows nullsafety prep

packages/path_provider/path_provider_windows/CHANGELOG.md, packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart, packages/path_provider/path_provider_windows/lib/src/path_provider_windows_stub.dart, packages/path_provider/path_provider_windows/pubspec.yaml, packages/path_provider/path_provider_windows/test/path_provider_windows_test.dart
Migrates path_provider_windows to null-safety.
Part of https://github.com/flutter/flutter/issues/70229
=> [path_provider] Migrate path_provider_windows to nullsafety

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/DartMessenger.java, packages/camera/camera/pubspec.yaml
channel.invokeMethod may only be called from the main thread. This is in the camera plugin not always the case, which causes a crash of the application. This change ensures that all calls to channel.invokeMethod are done from the main thread.
Issue fixed by this PR: [camera] [crash] Methods marked with @UiThread must be executed on the main thread #72340
https://github.com/flutter/flutter/issues/72340
=> [camera] Ensure that channel.invokeMethod runs on the main thread

packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/method_channel/method_channel_google_maps_flutter.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_flutter_platform.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/tile.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/tile_overlay.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/tile_overlay_updates.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/tile_provider.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/types.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/utils/tile_overlay.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/platform_interface/google_maps_flutter_platform_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/tile_overlay_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/tile_overlay_updates_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/tile_test.dart, packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
This is the platform interface change required to add custom tile support. A fork from https://github.com/flutter/plugins/pull/2077 (CC @otopba )
This Pr also added tests for the platform interface, which were not added in https://github.com/flutter/plugins/pull/2077.
There are also some sutle documentation updates and variable access level updates.
related to flutter/flutter#25942 …
=> [google_maps_flutter_platform_interface] add custom tile support

packages/integration_test/CHANGELOG.md, packages/integration_test/pubspec.yaml
Needed for https://github.com/flutter/flutter/pull/74671
=> bump vmservice

packages/cross_file/CHANGELOG.md, packages/cross_file/lib/src/types/html.dart, packages/cross_file/pubspec.yaml
The next version of `package:http` expects `URI`s. See https://github.com/dart-lang/http/pull/507
=> Support breaking http change

packages/cross_file/CHANGELOG.md, packages/cross_file/lib/src/types/base.dart, packages/cross_file/lib/src/types/html.dart, packages/cross_file/lib/src/types/interface.dart, packages/cross_file/lib/src/types/io.dart, packages/cross_file/lib/src/web_helpers/web_helpers.dart, packages/cross_file/pubspec.yaml, packages/cross_file/test/x_file_html_test.dart, packages/cross_file/test/x_file_io_test.dart, script/build_all_plugins_app.sh, script/nnbd_plugins.sh
This PR migrates `cross_file` to null-safety.
To do so, it adapts the code to be null-safe, **and** removes the dependency in `package:http` which is still not migrated.
According to our tests (which didn't require any significant changes), this seems to be an API compatible change too:
```
~/github/plugins/packages/cross_file$ flutter test
00:01 +10: All tests passed!                                                                                                       
~/github/plugins/packages/cross_file$ flutter test --platform=chrome
00:04 +11: All tests passed!                                                                                                       
```
* Fixes https://github.com/flutter/flutter/issues/74541
* Closes https://github.com/flutter/plugins/pull/3462
If you …
=> [cross_file] Migrate to null-safety.

packages/cross_file/test/x_file_io_test.dart, packages/image_picker/image_picker_platform_interface/CHANGELOG.md, packages/image_picker/image_picker_platform_interface/pubspec.yaml, packages/image_picker/image_picker_platform_interface/test/picked_file_io_test.dart
Fixes where we load the asset file in tests. See: https://github.com/flutter/flutter/pull/74622
[pub …
=> [image_picker_platform_interface] fix test asset file location

packages/cross_file/CHANGELOG.md, packages/cross_file/lib/src/types/base.dart, packages/cross_file/lib/src/types/html.dart, packages/cross_file/lib/src/types/interface.dart, packages/cross_file/lib/src/types/io.dart, packages/cross_file/lib/src/web_helpers/web_helpers.dart, packages/cross_file/pubspec.yaml, packages/cross_file/test/x_file_html_test.dart, packages/cross_file/test/x_file_io_test.dart, script/build_all_plugins_app.sh, script/nnbd_plugins.sh
This reverts commit ca9921196a7ae96edad91a9cd7b7d8fe9f5689ff.
The current tree is failing in CI. This is attempting to rule out bugs introduced by this change.
=> Revert "[cross_file] Migrate to null-safety. (#3452)"

packages/integration_test/CHANGELOG.md, packages/integration_test/pubspec.yaml, packages/integration_test/test/binding_fail_test.dart
There was a change in `flutter master` on how machine readable output is reported (https://github.com/flutter/flutter/pull/74176). It required a change to integration_test in the SDK, but that wasn't patched to the plugins repo. This PR does that.
=> [integration_test] Fix tests from changes to `flutter test` machine output

packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/lib/src/link.dart, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/url_launcher/url_launcher_web/test/lib/main.dart, packages/url_launcher/url_launcher_web/test/test_driver/url_launcher_web_integration.dart, packages/url_launcher/url_launcher_web/test/test_driver/url_launcher_web_integration_test.dart
The Link widget builds a Stack on the web. The Stack by default [loosens](https://master-api.flutter.dev/flutter/widgets/Stack/fit.html) the constraints passed by the parent. This is what was causing the misalignment.
In order to fix it, we just need to pass `fit: StackFit.passthrough` to the Stack.
Fixes https://github.com/flutter/flutter/issues/70053
=> [url_launcher_web] Fix Link misalignment issue

packages/local_auth/CHANGELOG.md, packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java, packages/local_auth/pubspec.yaml
This breaks internal lints when imported, because the switch case continues to the next case. I'm not familiar with the code, but I assume that since the error is handled in `completionHandler.onError` this `case` is complete and we should `break`,
=> [local_auth] Fix incorrect switch fallthrough

packages/path_provider/path_provider_windows/CHANGELOG.md, packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart, packages/path_provider/path_provider_windows/pubspec.yaml
Fixes flutter/flutter#75050. When ffi 0.2.0-nullsafety.2 lands, the `calloc` method will be provided by ffi itself, which might trigger another set of changes, but this change will ensure that path_provider_windows works on current null safety builds.  …
=> [path_provider_windows] Resolve FFI stabilization changes

packages/connectivity/connectivity_macos/CHANGELOG.md, packages/connectivity/connectivity_macos/lib/connectivity_macos.dart, packages/connectivity/connectivity_macos/pubspec.yaml, packages/path_provider/path_provider_macos/CHANGELOG.md, packages/path_provider/path_provider_macos/lib/path_provider_macos.dart, packages/path_provider/path_provider_macos/pubspec.yaml
When these federated plugins were created, plugins had to have at least
one Dart file to avoid issues with the analyzer, so were created with a
stub file since all the code is native. The analyzer no longer has this
limitation, so the stub is no longer necesssary.
=> Remove Dart stubs from macOS plugins

packages/shared_preferences/shared_preferences_platform_interface/CHANGELOG.md, packages/shared_preferences/shared_preferences_platform_interface/lib/method_channel_shared_preferences.dart, packages/shared_preferences/shared_preferences_platform_interface/lib/shared_preferences_platform_interface.dart, packages/shared_preferences/shared_preferences_platform_interface/pubspec.yaml, packages/shared_preferences/shared_preferences_platform_interface/test/method_channel_shared_preferences_test.dart, script/nnbd_plugins.sh
Migrate to null safety.
- [] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
[breaking …
=> Migrate shared_preferences_platform_interfaces to null safety

.github/labeler.yml
Tags PRs with platform-* labels based on the platform(s) being edited.
This will allow filtering open PRs by OS (e.g., to allow someone
focusing on a single platform's plugin implementations to easily find
all relevant PRs).
=> Automatically add platform labels

AUTHORS, packages/camera/camera/CHANGELOG.md, packages/camera/camera/README.md, packages/camera/camera/pubspec.yaml
Example link updated
from https://github.com/flutter/plugins/tree/master/packages/camera/example
to https://github.com/flutter/plugins/tree/master/packages/camera/camera/example
=> [camera] Fix example reference in camera's doc

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/build.gradle, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/DeviceOrientationManager.java, packages/camera/camera/example/android/app/build.gradle, packages/camera/camera/pubspec.yaml
Reverts the `compileSdkVersion` back to 29 (was 30) and make code compatible with this Android version as this is causing problems with Apps using the add-to-app feature. The add-to-app feature overrides the `compileSdkVersion` and sets it to 29, which results in a compile error.
Resolves flutter/flutter#74915 …
=> [camera] Revert compileSdkVersion back to 29

CODEOWNERS
Removing myself from some of the plugins that I won't have time to promptly check requested reviews.
=> Remove cyanglaz from CODEOWNER: google_sign_in, connectivity, package_info, video_player

.cirrus.yml, script/build_all_plugins_app.sh, script/check_publish.sh, script/common.sh, script/incremental_build.sh
I moved the logic to the script as it's easier to follow than the cirrus schema given the test matrices, etc...
=> Run pub global activate before pub global run

script/check_publish.sh
Should fix the presubmit failure from https://cirrus-ci.com/task/6389683376619520
=> Run activate before run

packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
The version should be 1.2.0. see https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
=> [google_maps_flutter_platform_interface ]fix version

packages/shared_preferences/shared_preferences_macos/CHANGELOG.md, packages/shared_preferences/shared_preferences_macos/pubspec.yaml
macOS federated plugin implementations that contain no Dart code just
need their Dart SDK bumped in order to be considered nullsafe.
Part of https://github.com/flutter/flutter/issues/74876
[pub …
=> [shared_preferences] Update macOS for NNBD

CONTRIBUTING.md
Adds a prominent note to CONTRIBUTING.md about the new policy regarding PRs for plugins for which there is a Flutter Community Plus Plugins equivalent.
=> Add a note about Plus plugins to CONTRIBUTING.md

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/pubspec.yaml
use same behavior for setting point of focus in android and iOS. 
In iOS, the landscape mode is used to calculate the point, but in android it doesn't.
https://github.com/flutter/plugins/blob/712dcc184380188522ca80b56e9b5b11651541ce/packages/camera/camera/ios/Classes/CameraPlugin.m#L985
https://github.com/flutter/plugins/blob/712dcc184380188522ca80b56e9b5b11651541ce/packages/camera/camera/ios/Classes/CameraPlugin.m#L1000
=> [camera] Clockwise rotation of focus point in android

packages/file_selector/file_selector_platform_interface/CHANGELOG.md, packages/file_selector/file_selector_platform_interface/lib/src/method_channel/method_channel_file_selector.dart, packages/file_selector/file_selector_platform_interface/lib/src/platform_interface/file_selector_interface.dart, packages/file_selector/file_selector_platform_interface/lib/src/types/x_type_group/x_type_group.dart, packages/file_selector/file_selector_platform_interface/lib/src/web_helpers/web_helpers.dart, packages/file_selector/file_selector_platform_interface/pubspec.yaml, packages/file_selector/file_selector_web/pubspec.yaml, script/nnbd_plugins.sh
Migrating `file_selector_interface` to null-safety
https://github.com/flutter/flutter/issues/75235
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breakin …
=> [file_selector_platform_interface] File selector nnbd

packages/camera/camera_platform_interface/CHANGELOG.md, packages/camera/camera_platform_interface/lib/src/events/camera_event.dart, packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart, packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart, packages/camera/camera_platform_interface/lib/src/types/camera_description.dart, packages/camera/camera_platform_interface/lib/src/types/camera_exception.dart, packages/camera/camera_platform_interface/lib/src/types/exposure_mode.dart, packages/camera/camera_platform_interface/lib/src/types/focus_mode.dart, packages/camera/camera_platform_interface/pubspec.yaml, packages/camera/camera_platform_interface/test/camera_platform_interface_test.dart, packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart, packages/camera/camera_platform_interface/test/utils/method_channel_mock.dart, script/build_all_plugins_app.sh, script/nnbd_plugins.sh
This PR migrates the `camera_platform_interface` package to null safety.
flutter/flutter#75228
flutter/flutter#75247
[Discord]: …
=> [camera_platform_interface] Migrate to null safety

packages/file_selector/file_selector_web/pubspec.yaml
(Introduced by mistake in https://github.com/flutter/plugins/pull/3509)
A couple of dependencies were rolled forward a little bit too early. This reverts the change.
* https://github.com/flutter/plugins/pull/3509/files/52fc320a31dd6d04567686cbc8601fe1b4f3f0ce#r572360322
=> [file_selector_web] Fix typo in pubspec.

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/README.md, packages/webview_flutter/pubspec.yaml
Plugin wiki section for https://github.com/flutter/flutter/issues/73093 …
=> Add section about how to use Material components in an app using WebView

.cirrus.yml, .gitmodules, script/check_publish.sh, script/common.sh
This is the first step toward moving the plugin tools over to this repo. 
For the time being, this will allow you to change the plugin tools, and test the changes directly without the need to publish to the tool to pub.
=> Add plugin tools as a git submodule and depend on it directly

.github/post_merge_labeler.yml, .github/workflows/pull_request_label.yml
Adds a post merge labeler that adds the `needs-publishing` label to any PR that changes a plugin
`pull_request_target` doesn't have a merge type, so this labeler runs when a PR is closed and `merged == true`.
Resource: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target …
=> Add post merge labeler

packages/path_provider/path_provider_windows/CHANGELOG.md, packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart, packages/path_provider/path_provider_windows/pubspec.yaml
Bump `ffi` to 1.0.0, `win32` to `2.0.0-nullsafety.12`. …
=> Bump ffi dependencies

.gitmodules, script/common.sh, script/tool/README.md, script/tool/lib/src/analyze_command.dart, script/tool/lib/src/build_examples_command.dart, script/tool/lib/src/common.dart, script/tool/lib/src/create_all_plugins_app_command.dart, script/tool/lib/src/drive_examples_command.dart, script/tool/lib/src/firebase_test_lab_command.dart, script/tool/lib/src/format_command.dart, script/tool/lib/src/java_test_command.dart, script/tool/lib/src/lint_podspecs_command.dart, script/tool/lib/src/list_command.dart, script/tool/lib/src/main.dart, script/tool/lib/src/publish_plugin_command.dart, script/tool/lib/src/test_command.dart, script/tool/lib/src/version_check_command.dart, script/tool/lib/src/xctest_command.dart, script/tool/pubspec.yaml
Moves the files from plugin_tools over.
=> Move plugin tools code

packages/image_picker/image_picker_for_web/CHANGELOG.md, packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart, packages/image_picker/image_picker_for_web/pubspec.yaml, packages/image_picker/image_picker_for_web/test/image_picker_for_web_test.dart
Migrate` image_picker_web to null-safety`
closes flutter/flutter#75162 …
=> [image_picker] Migrate image_picker_web to null-safety

packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/pubspec.yaml, packages/video_player/video_player_web/test/video_player_web_test.dart
This is a partial landing of https://github.com/flutter/plugins/pull/3281. …
=> [video_player] Update video_player_web to point to new video_player_interface

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/DeviceOrientationManager.java, packages/camera/camera/pubspec.yaml
* Added a fallback to UI Orientation when the orientation value is not available. 
* Fixes issue [#75133](https://github.com/flutter/flutter/issues/75133) …
=> [camera] Fixes crash on takePicture()

script/build_all_plugins_app.sh, script/nnbd_plugins.sh, script/tool/lib/src/common.dart
build_all_plugins_app.sh contains an exclusion list, which currently contains almost all of the non-app-facing plugins. However, the script those exclusions are passed to expects federated plugin exclusions to be of the form `plugin_name/plugin_name_subplugin_name`, not just `plugin_name_subplugin_name`, so in practice almost nothing on that list has actually been doing anything.
This fixes the script to allow either mode of exclusion (since clearly people expect using just the name to work), and scrubs everything from the list that clearly wasn't actually needed.
=> Fix the build-all exclusion list

packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/pubspec.yaml
Earlier versions are subject to issues with breaking changes in `ffi` and `win32`, so we should ensure that people don't accidentally end up with them. …
=> [path_provider] Update Windows implementation version

packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/camera.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/camera_test.dart
The nullability conversion added a type check when recreating a
CameraPosition from JSON that was too restrictive, and regressed the
app-facing package. This relaxes that assertion, and adds a test to
catch the issue.
Part of flutter/flutter#75236 …
=> [google_maps_flutter] Fix CameraPosition regression

packages/file_selector/file_selector_web/README.md
This PR updates the dependency versions in [file_selector_web readme.md](https://github.com/flutter/plugins/blob/master/packages/file_selector/file_selector_web/README.md)
Fixes [flutter/flutter#76067](https://github.com/flutter/flutter/issues/76067) …
=> [file_selector_web] update documentation #76067

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/pubspec.yaml
Now that the `url_launcher_web` plugin has been migrated to null-safety, re-endorse it.
Fixes https://github.com/flutter/flutter/issues/72239
Fixes https://github.com/flutter/flutter/issues/73679
Fixes https://github.com/flutter/flutter/issues/75244 …
=> [url_launcher] Re-endorse null-safe web implementation.

packages/video_player/video_player/README.md
The android simulator is throwing an error on http calls now. Changing to https fixes the error and is better for several other reasons.
```
I/ExoPlayerImpl( 3419): Init 896a4d7 [ExoPlayerLib/2.12.1] [generic_x86_arm, AOSP on IA Emulator, Google, 28]
E/ExoPlayerImplInternal( 3419): Playback error
E/ExoPlayerImplInternal( 3419):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal( 3419):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 3419):       at android.os.Looper.loop(Looper.java:193)
E/ExoPlayerImplInternal( 3419):       at …
```
=> [video_player] Update video_player readme to change sample video to https

packages/camera/camera/CHANGELOG.md, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java, packages/camera/camera/pubspec.yaml, packages/camera/camera/test/camera_test.dart
Added a timeout to the Android pre-capture sequence to prevent hard crashes when the camera is unable to acquire a focus lock. The solution is inspired by the [Android Camera2 Raw](https://github.com/googlearchive/android-Camera2Raw/blob/8ef76bbc26ff44e5dd7584efbc763d58803bf45c/Application/src/main/java/com/example/android/camera2raw/Camera2RawFragment.java#L473) example App which uses a similar solution. 
- Fixes flutter/flutter#74645 …
=> [camera] Added timeout to Android pre-capture sequence

packages/plugin_platform_interface/CHANGELOG.md, packages/plugin_platform_interface/pubspec.yaml
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
[CLA]: …
=> [plugin_platform_interface] Migrate  to v2 stable, null-safe

packages/in_app_purchase/example/pubspec.yaml, packages/shared_preferences/shared_preferences/CHANGELOG.md, packages/shared_preferences/shared_preferences/lib/shared_preferences.dart, packages/shared_preferences/shared_preferences/pubspec.yaml, packages/shared_preferences/shared_preferences/test/shared_preferences_test.dart
The type of List could be converted to `dynamic` when coming from method channel. We needs to initially treat it as dynamic then convert back to `Object`
See: https://github.com/flutter/plugins/pull/3555#issuecomment-781616325 …
=> [shared_preferences] fix crash when list type is dynaimc

packages/shared_preferences/shared_preferences/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/shared_preferences/example/lib/main.dart, packages/shared_preferences/shared_preferences/example/pubspec.yaml, packages/shared_preferences/shared_preferences/example/test_driver/integration_test.dart, packages/shared_preferences/shared_preferences_linux/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/shared_preferences_linux/example/lib/main.dart, packages/shared_preferences/shared_preferences_linux/example/pubspec.yaml, packages/shared_preferences/shared_preferences_linux/example/test_driver/integration_test.dart, packages/shared_preferences/shared_preferences_macos/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/shared_preferences_macos/example/lib/main.dart, packages/shared_preferences/shared_preferences_macos/example/macos/Runner.xcodeproj/project.pbxproj, packages/shared_preferences/shared_preferences_macos/example/macos/Runner.xcworkspace/contents.xcworkspacedata, packages/shared_preferences/shared_preferences_macos/example/pubspec.yaml, packages/shared_preferences/shared_preferences_macos/example/test_driver/integration_test.dart, packages/shared_preferences/shared_preferences_macos/pubspec.yaml, packages/shared_preferences/shared_preferences_windows/example/integration_test/shared_preferences_test.dart, packages/shared_preferences/shared_preferences_windows/example/lib/main.dart, packages/shared_preferences/shared_preferences_windows/example/pubspec.yaml, packages/shared_preferences/shared_preferences_windows/example/test_driver/integration_test.dart
Migrate all examples to NNBD so that the example apps will run in strong mode.
Converts macOS example to use the platform interface to remove circular dependencies (code is based on the Linux and Windows versions which already use essentially that approach).
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-c …
=> [shared_preferences] Migrate examples to NNBD

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/README.md, packages/video_player/video_player/pubspec.yaml, packages/video_player/video_player_platform_interface/CHANGELOG.md, packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart, packages/video_player/video_player_platform_interface/pubspec.yaml, packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/README.md, packages/video_player/video_player_web/lib/video_player_web.dart, packages/video_player/video_player_web/pubspec.yaml, packages/video_player/video_player_web/test/video_player_web_test.dart
This option can't be implemented in the web platform, so it is better to just ignore it as there is no other alternative when running in web.
The documentation is updated to note this option will be silently ignored in web.
Fixes https://github.com/flutter/flutter/issues/75493.
=> [video_player] Ignore setting mixWithOthers in web

packages/image_picker/image_picker_for_web/CHANGELOG.md, packages/image_picker/image_picker_for_web/README.md, packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart, packages/image_picker/image_picker_for_web/pubspec.yaml
While attempting to update @devj3ns' PR with the latest master, I did the wrong thing and ended up locking myself out of his PR (probably for the better).
This PR relands the same code that @devj3ns was attempting to land in his PR (#3551)
---
The arguments `maxWidth`, `maxHeight` and `imageQuality` of `pickImage()` and the argument `maxDuration` of `pickVideo()` are not supported in web version of the image_picker package.
I added some doc comments to point out that specifying these argument does not change anything on the pickedFile.
=> [image_picker_for_web] Add doc comments to point out that some arguments aren't supported on the web

packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml, packages/url_launcher/url_launcher_platform_interface/test/link_test.dart, packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart
Also enables null safety for the unit tests, which had been opted out.
=> [url_launcher] Bump platform interface package to stable NNBD

packages/package_info/CHANGELOG.md, packages/package_info/example/integration_test/package_info_test.dart, packages/package_info/example/lib/main.dart, packages/package_info/example/macos/Runner.xcodeproj/project.pbxproj, packages/package_info/example/pubspec.yaml, packages/package_info/example/test_driver/integration_test.dart, packages/package_info/lib/package_info.dart, packages/package_info/pubspec.yaml
Includes:
- Migrating the example to NNBD
- Bullet-proofing against null values from the native code; at least the ObjC code can theoretically return nulls. …
=> [package_info] Bump version for NNBD stable

packages/image_picker/image_picker_platform_interface/CHANGELOG.md, packages/image_picker/image_picker_platform_interface/pubspec.yaml
=> [image_picker_platform_interface] Bump NNBD version to stable

packages/flutter_plugin_android_lifecycle/pubspec.yaml
Pub requires 1.20 or greater for plugins without ios/ folders.
=> [flutter_plugin_android_lifecycle-sdk] Update Flutter SDK constraint

packages/image_picker/image_picker/pubspec.yaml
Landing this to fix CI.
This change will get published with https://github.com/flutter/plugins/pull/3579
=> [image_picker] use nnbd version of deps to resolve ci failure

packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md, packages/url_launcher/url_launcher_platform_interface/pubspec.yaml
The lower end of the SDK range was wrong due to a bad copy/paste.
=> [url_launcher] Fix SDK copypasta in platform interface

packages/camera/camera/CHANGELOG.md, packages/camera/camera/example/lib/main.dart, packages/camera/camera/ios/Classes/CameraPlugin.m, packages/camera/camera/pubspec.yaml
Initial version of the zoom feature used the `rampToVideoZoomFactor:withRate` method on iOS to update the zoom scale. This method introduces smooth transition at the specified rate, which is ideal when jumping in large zoom increments (e.g. directly zooming from factor 1 to factor 5). 
However in most use cases you would zoom in very small increments (using pinch to zoom or a slider). Using the `rampToVideoZoomFactor:withRate` method would cause an annoying delay in zoom functionality. Especially since the `rate` parameter is hardcoded since it is not cross platform compatible. Therefore this PR updates the iOS implementation to use the `videoZoomFactor` property instead which jumps directly to the desired zoom level. 
Added benefit is that this now behaves the same way on Android and …
=> [camera] Solves delay when using the zoom feature on iOS.

packages/sensors/CHANGELOG.md, packages/sensors/example/lib/main.dart, packages/sensors/example/lib/snake.dart, packages/sensors/example/pubspec.yaml, packages/sensors/example/test_driver/test/integration_test.dart, packages/sensors/pubspec.yaml
Includes migrating example to null-safety. …
=> [sensors] Update to NNBD stable

packages/cross_file/CHANGELOG.md, packages/cross_file/pubspec.yaml
Moves the cross_file package to stable null safety.
This will open the road to also move the `camera` and `file_selector` plugins to stable null safety release. …
=> [cross_file] Stable null safety release

packages/shared_preferences/shared_preferences_linux/CHANGELOG.md, packages/shared_preferences/shared_preferences_linux/example/pubspec.yaml, packages/shared_preferences/shared_preferences_linux/pubspec.yaml, packages/shared_preferences/shared_preferences_macos/CHANGELOG.md, packages/shared_preferences/shared_preferences_macos/example/pubspec.yaml, packages/shared_preferences/shared_preferences_macos/pubspec.yaml, packages/shared_preferences/shared_preferences_web/CHANGELOG.md, packages/shared_preferences/shared_preferences_web/pubspec.yaml, packages/shared_preferences/shared_preferences_windows/CHANGELOG.md, packages/shared_preferences/shared_preferences_windows/example/CHANGELOG.md, packages/shared_preferences/shared_preferences_windows/example/pubspec.yaml, packages/shared_preferences/shared_preferences_windows/pubspec.yaml
Updates all the platform implementation packages to stable null-safety.
=> [shared_preferences] Bump platform versions to NNBD stable

packages/url_launcher/url_launcher_linux/CHANGELOG.md, packages/url_launcher/url_launcher_linux/example/integration_test/url_launcher_test.dart, packages/url_launcher/url_launcher_linux/example/lib/main.dart, packages/url_launcher/url_launcher_linux/example/pubspec.yaml, packages/url_launcher/url_launcher_linux/example/test_driver/integration_test.dart, packages/url_launcher/url_launcher_linux/pubspec.yaml, packages/url_launcher/url_launcher_macos/CHANGELOG.md, packages/url_launcher/url_launcher_macos/example/integration_test/url_launcher_test.dart, packages/url_launcher/url_launcher_macos/example/lib/main.dart, packages/url_launcher/url_launcher_macos/example/pubspec.yaml, packages/url_launcher/url_launcher_macos/example/test_driver/integration_test.dart, packages/url_launcher/url_launcher_macos/pubspec.yaml, packages/url_launcher/url_launcher_web/CHANGELOG.md, packages/url_launcher/url_launcher_web/example/pubspec.yaml, packages/url_launcher/url_launcher_web/pubspec.yaml, packages/url_launcher/url_launcher_windows/CHANGELOG.md, packages/url_launcher/url_launcher_windows/example/integration_test/url_launcher_test.dart, packages/url_launcher/url_launcher_windows/example/lib/main.dart, packages/url_launcher/url_launcher_windows/example/pubspec.yaml, packages/url_launcher/url_launcher_windows/example/test_driver/integration_test.dart, packages/url_launcher/url_launcher_windows/pubspec.yaml
Updates all versions to stable.
Converts all desktop examples to null-safety, and migrates Linux and
macOS to use platform interface for examples rather than app-facing
package to eliminate circular dependencies (implementation copied
directly from Windows).
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-c …
=> [url_launcher] Update platforms to NNBD stable

packages/path_provider/path_provider/CHANGELOG.md, packages/path_provider/path_provider/example/pubspec.yaml, packages/path_provider/path_provider/lib/path_provider.dart, packages/path_provider/path_provider/pubspec.yaml, packages/path_provider/path_provider/test/path_provider_test.dart
Bumps the versions in the app-facing package to make it stable NNBD.
Changes the interface of four core methods to non-nullable, and adds a new exceptions if they aren't provided by the platform implementations. The list is somewhat arbitrary, but these seem like the four that are core enough that any implementation should either provide them, or explicitly say they don't have such a concept via `UnsupportedError`, since there isn't an obvious way for a developer to fall back if they are unexpectedly missing. …
=> [path_provider] Update to stable NNBD

packages/share/CHANGELOG.md, packages/share/example/lib/image_previews.dart, packages/share/example/lib/main.dart, packages/share/example/pubspec.yaml, packages/share/example/test_driver/test/integration_test.dart, packages/share/pubspec.yaml
Includes migrating example to null safety
=> [share] Bump version for NNBD stable

packages/android_intent/CHANGELOG.md, packages/android_intent/example/integration_test/android_intent_test.dart, packages/android_intent/example/pubspec.yaml, packages/android_intent/example/test_driver/integration_test.dart, packages/android_intent/pubspec.yaml
Includes migrating example to null safety. …
=> [android_intent] Bump version for NNBD stable

packages/shared_preferences/shared_preferences/CHANGELOG.md, packages/shared_preferences/shared_preferences/example/pubspec.yaml, packages/shared_preferences/shared_preferences/pubspec.yaml
Completes the shared_preferences migration to stable null safety.
=> [shared_preferences] Bump app-facing version for NNBD stable

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/example/pubspec.yaml, packages/url_launcher/url_launcher/pubspec.yaml
Completes the null-safety migration of url_launcher.
=> [url_launcher] Bump app-facing version for NNBD stable

packages/file_selector/file_selector_platform_interface/CHANGELOG.md, packages/file_selector/file_selector_platform_interface/pubspec.yaml, packages/file_selector/file_selector_platform_interface/test/file_selector_platform_interface_test.dart
Required for the migration to stable null safety of file_selector. …
=> [file_selector_platform_interface] null safety stable release

packages/local_auth/CHANGELOG.md, packages/local_auth/example/pubspec.yaml, packages/local_auth/pubspec.yaml
Resolves the bizarre version situation this plugin was in; https://github.com/flutter/plugins/pull/2489 set the changelog version to a 1.1.0 prerelease but not the pubspec version, and then apparently it was published with a local modification to the pubspec to correct that which was never checked in. Subsequent *later* changes added new 1.0.0-nullsafety.x releases to the changelog and updated the version accordingly, but were presumably never published.
The minor version bump of the prerelease ideally shouldn't have happened, but we shouldn't go backwards in published versions so we're stuck with 1.1.0. …
=> [local_auth] Bump version for NNBD stable

packages/quick_actions/CHANGELOG.md, packages/quick_actions/example/integration_test/quick_actions_test.dart, packages/quick_actions/example/lib/main.dart, packages/quick_actions/example/pubspec.yaml, packages/quick_actions/example/test_driver/integration_test.dart, packages/quick_actions/pubspec.yaml
Release the null safety version as stable and move the example app to null safety.
=> [quick_action] null safety stable release

packages/ios_platform_images/CHANGELOG.md, packages/ios_platform_images/example/ios/Runner.xcodeproj/project.pbxproj, packages/ios_platform_images/example/ios/Runner.xcworkspace/contents.xcworkspacedata, packages/ios_platform_images/example/pubspec.yaml, packages/ios_platform_images/pubspec.yaml
Includes migrating the sample app.
iOS project changes are the result of automatic project migrations done by the Flutter build.
=> [ios_platform_images] Bump version for stable NNBD

packages/espresso/CHANGELOG.md, packages/espresso/example/lib/main.dart, packages/espresso/example/pubspec.yaml, packages/espresso/pubspec.yaml, script/nnbd_plugins.sh
This plugin doesn't have any Dart code, but changing the SDK requirement
will prevent potential user confusion from it not showing up as
null-safe on Pub. …
=> [espresso] Update SDK requirement for null-safety

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/example/lib/place_marker.dart, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
In _onMarkerTapped function we were changing markers[markerId] to defaultMarker and than again markers[markerId] to hueGreen marker, while instead we should have changed markers[selectedMarker] to defaultMarker first instead of markers[markerId]
This PR fixes issue [#76492](https://github.com/flutter/flutter/issues/76492)
[CLA]: …
=> [google_maps_flutter] fixed a small bug in example app.

packages/google_sign_in/google_sign_in_web/lib/src/generated/gapi.dart, packages/google_sign_in/google_sign_in_web/lib/src/generated/gapiauth2.dart
This is breaking the rolls!
Fixes: https://github.com/flutter/flutter/issues/76625 …
=> [google_sign_in_web] Ignore analyzer checks in generated files.

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/pubspec.yaml, packages/webview_flutter/pubspec.yaml
Release the null safety version to stable
=> [webview_flutter] null safety stable release

packages/camera/camera/CHANGELOG.md, packages/camera/camera/README.md, packages/camera/camera/pubspec.yaml
This PR updates the outdated example code listed in the camera [README.md](https://github.com/flutter/plugins/blob/master/packages/camera/camera/README.md) file.
- Resolves flutter/flutter#76537
[CLA]: …
=> [camera] Fix example from README.md

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/example/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
=> [google_maps_flutter] Bump app-facing version for NNBD stable

packages/video_player/video_player_web/CHANGELOG.md, packages/video_player/video_player_web/pubspec.yaml, packages/video_player/video_player_web/test/video_player_web_test.dart
This PR will re-version the video_player_web as a 'preview version' with null safety enabled by default.
~(video_player_platform_interface needs to land first: https://github.com/flutter/plugins/pull/3578)~
Fixes https://github.com/flutter/flutter/issues/75493 …
=> [video_player_web] Bump version for NNBD stable

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/example/pubspec.yaml, packages/video_player/video_player/pubspec.yaml
=> [video_player] Bump app-facing version for NNBD stable

packages/file_selector/file_selector_web/CHANGELOG.md, packages/file_selector/file_selector_web/example/integration_test/file_selector_web_test.dart, packages/file_selector/file_selector_web/lib/file_selector_web.dart, packages/file_selector/file_selector_web/pubspec.yaml
Null indicates cancelation on other platforms, so returning null here makes using this in a cross-platform way very awkward.
=> [file_selector] Return a non-null value from getSavePath on web

packages/cross_file/CHANGELOG.md, packages/cross_file/lib/src/types/base.dart, packages/cross_file/pubspec.yaml
Without this, the dummy ("interface") XFile implementation of these properties has different nullability than the others, and the analyzer doesn't match what the runtime actually sees. …
=> [cross_file] Fix base class nullability

AUTHORS, packages/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/README.md, packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/MethodCallHandlerImpl.java, packages/in_app_purchase/example/README.md, packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/MethodCallHandlerTest.java, packages/in_app_purchase/example/lib/main.dart, packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart, packages/in_app_purchase/lib/src/billing_client_wrappers/enum_converters.dart, packages/in_app_purchase/lib/src/billing_client_wrappers/enum_converters.g.dart, packages/in_app_purchase/lib/src/in_app_purchase/app_store_connection.dart, packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart, packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart, packages/in_app_purchase/pubspec.yaml, packages/in_app_purchase/test/billing_client_wrappers/billing_client_wrapper_test.dart, packages/in_app_purchase/test/billing_client_wrappers/purchase_wrapper_test.dart
This pull request adds support for Upgrading/Downgrading an existing InApp subscription on Android. This does not require any changes on iOS since iTunesConnect provides a way to create a 'subscription group'.
Ref: https://developer.android.com/google/play/billing/billing_subscriptions#Allow-upgrade
Also, this supports Proration Mode that handles the user's existing subscription.
Ref: https://developer.android.com/google/play/billing/billing_subscriptions#set-proration-mode
While changing the subscription, this uses the old 'PurchaseDetails' object, rather than using 'ProductDetails' or just the 'oldSku' id itself, because, In the latest versions of the Play Billing Library, setOldSku() is deprecated (https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.B …
=> [in_app_purchase] Add support for InApp subscription upgrade/downgrade

packages/camera/camera_platform_interface/CHANGELOG.md, packages/camera/camera_platform_interface/pubspec.yaml
This PR bumps the version of the `camera_platform_interface` package to prepare it for stable NNBD release.
- [] I listed at least one issue that this PR fixes in the description above.
- [] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
[C++, Objective-C, Java style …
=> [camera_platform_interface] Stable null safety release.

packages/google_maps_flutter/google_maps_flutter/example/ios/Runner/Info.plist
The [release notes](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md#100---out-of-developer-preview--) state that `io.flutter.embedded_views_preview` is not required since version `1.0.0`.
Thus removed this from the example, to keep things clean and tidy ✨
=> [google_maps_flutter] embedded_views_preview not required since v1.0.0

packages/image_picker/image_picker_for_web/README.md
=> Fix typo in image_picker_for_web README.md

.gitignore, packages/shared_preferences/shared_preferences/CHANGELOG.md, packages/shared_preferences/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java, packages/shared_preferences/shared_preferences/pubspec.yaml
This should be an instance property instead.
=> Make executor an instance property

packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/example/lib/main.dart, packages/google_sign_in/google_sign_in/example/pubspec.yaml, packages/google_sign_in/google_sign_in/pubspec.yaml
Includes migrating the example app.
=> [google_sign_in] Bump app-facing version for NNBD stable

packages/file_selector/file_selector/CHANGELOG.md, packages/file_selector/file_selector/pubspec.yaml
Endorses the web implementation of file_selector. This also fixes the issue of it being considered a package, rather than a plugin, and thus showing support for all platforms on pub.dev
[pub …
=> [file_selector] Endorse web

packages/image_picker/image_picker_for_web/CHANGELOG.md, packages/image_picker/image_picker_for_web/pubspec.yaml
This PR will re-version the image_picker_for_web as a 'preview version' with null safety enabled by default. …
=> [image_picker_for_web] Bump version for NNBD stable

packages/shared_preferences/shared_preferences/CHANGELOG.md, packages/shared_preferences/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/MethodCallHandlerImpl.java, packages/shared_preferences/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java, packages/shared_preferences/shared_preferences/pubspec.yaml
=> [shared_preferences] Don't create additional Handler when method channel is called.

packages/connectivity/connectivity/CHANGELOG.md, packages/connectivity/connectivity/pubspec.yaml, packages/connectivity/connectivity/test/connectivity_test.dart
Migrate unit tests to null safety. This is mistakenly left out in the 3.0.0 release.
=> [connectivity] migrate unit tests to null safety

.github/workflows/pull_request_label.yml
Making labeler pointing to a fixed git ref
=> Update pull_request_label.yml to make actions pointing to refs

packages/camera/camera/CHANGELOG.md, packages/camera/camera/example/integration_test/camera_test.dart, packages/camera/camera/example/lib/main.dart, packages/camera/camera/example/pubspec.yaml, packages/camera/camera/example/test_driver/integration_test.dart, packages/camera/camera/pubspec.yaml
Stable NNBD release for the camera package. 
With this PR I also migrated the example App to sound null safe. Note that I didn't update the dev-dependency on `mockito: ^5.0.0-nullsafety.7` since the stable version causes a conflict with the current flutter_driver dependency. I have marked the dependency in the pubspec.yaml with a `# TODO(mvanbeusekom)` comment to remind me to remove it when the conflict is resolved.
Conflict details:
```text
Because mockito >=5.0.0 depends on analyzer ^1.0.0 which depends on crypto ^3.0.0, mockito >=5.0.0 requires crypto ^3.0.0.
And because every version of flutter_driver from sdk depends on crypto 2.1.5, mockito >=5.0.0 is incompatible with flutter_driver from sdk.
So, because camera depends on both flutter_driver any from sdk and mockito ^5.0.0, version …
```
=> [camera] Stable release for null safety.

packages/share/CHANGELOG.md, packages/share/pubspec.yaml, packages/share/test/share_test.dart
This PR migrates package:share unit tests to null-safety.
This removes mockito for a simpler Fake that just logs calls to the method channel.
[Discord]: …
=> [share] Migrate unit tests to null-safety.

packages/device_info/device_info_platform_interface/test/method_channel_device_info_test.dart
Removes the opt-out now that the underlying issue is fixed
=> [device_info] Enable NNBD for unit test

.gitignore, packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/example/ios/Podfile, packages/image_picker/image_picker/example/ios/Runner.xcodeproj/project.pbxproj, packages/image_picker/image_picker/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, packages/image_picker/image_picker/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/image_picker/image_picker/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/RunnerUITests.xcscheme, packages/image_picker/image_picker/ios/image_picker.podspec, packages/image_picker/image_picker/pubspec.yaml
`pod lib lint` has been used to run iOS unit tests and the static analyzer.  Unfortunately due to [Flutter not supporting ARM iOS simulators](https://github.com/flutter/flutter/issues/64502) and the fact that we [can't tell the `pod` command to skip analyzing on that architecture](https://github.com/flutter/plugins/pull/3653), this has prevented the plugins CI from migrating to Xcode 12 and is blocking Flutter from [increasing the Xcode minimum version to 12](https://github.com/flutter/flutter/pull/77025).
Now that we have a full-fledged [xctest_command](https://github.com/flutter/plugins/blob/master/script/tool/lib/src/xctest_command.dart) we can migrate some of the value we were getting from `pod lib lint`.
Migrate `image_picker` package to run all the unit tests as part of the …
=> [image_picker] Run CocoaPods iOS tests in RunnerUITests target

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
Since the plugin doesn't have an iOS folder, it is required that the min sdk version is 1.20.0
Also, it looks like the last 0.1.2 version was a mistake (made in https://github.com/cyanglaz/plugins/commit/6fa2ead23e8d58de047f38c0f90ce5e218ef8ea5) and has been published, so i only updated the changelog.
=> [google_maps_flutter_web] update min flutter sdk version to 1.20.0

.cirrus.yml, CONTRIBUTING.md, script/tool/lib/src/lint_podspecs_command.dart, script/tool/lib/src/xctest_command.dart, script/tool/test/lint_podspecs_command_test.dart, script/tool/test/xctest_command_test.dart
`pod lib lint` has been used to run iOS unit tests and the static analyzer.  Unfortunately due to [Flutter not supporting ARM iOS simulators](https://github.com/flutter/flutter/issues/64502) and the fact that we [can't tell the `pod` command to skip analyzing on that architecture](https://github.com/CocoaPods/CocoaPods/issues/10476), this has prevented the plugins CI from migrating to Xcode 12 and is blocking Flutter from [increasing the Xcode minimum version to 12](https://github.com/flutter/flutter/pull/77025).
Now that we have a full-fledged [xctest_command](https://github.com/flutter/plugins/blob/master/script/tool/lib/src/xctest_command.dart) we can migrate the static analyzer from `pod lib lint` to the custom test runner.
1. Run static analyzer as part of `xctest`. Automatically …
=> Run static analyzer during xctest

packages/path_provider/path_provider_windows/CHANGELOG.md, packages/path_provider/path_provider_windows/example/lib/main.dart, packages/path_provider/path_provider_windows/example/pubspec.yaml, packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart, packages/path_provider/path_provider_windows/pubspec.yaml, packages/path_provider/path_provider_windows/test/path_provider_windows_test.dart
Anything with a transitive dependency on `path_provider` (which is a
lot) is broken on Flutter 1.26 due to Dart FFI changes. path_provider
2.0.0 doesn't have this problem, but for transitive dependencies that
means users need to force an override in their pubspec (and more
importantly, know that they need to do so).
This creates a new minor release to path_provider_windows that uses a
1.26-friendly version of FFI, but has the null safety changes and major
version bump backed out, so that transitive dependencies can safely
resolve to this working version just by doing a pub update.
Should help avoid issues like https://github.com/flutter/flutter/issues/76705 …
=> [path_provider] Make a 0.0.5 for Dart 2.12 compat

.cirrus.yml, script/tool/lib/src/lint_podspecs_command.dart, script/tool/test/lint_podspecs_command_test.dart
Adopt Xcode 12 for all Cirrus tasks.
Add `--configuration=Debug` option ([available as of CocoaPods 1.10](https://github.com/CocoaPods/CocoaPods/pull/9760)) to `pod lib lint` CI script so the build only targets the supported x86_64 simulator, not the unsupported (by Flutter) arm64 simulator.
See also https://github.com/flutter/plugins/pull/3304.
=> Adopt Xcode 12 for podspec lints

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart, packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_controller.dart, packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_flutter_web.dart, packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/google_maps_controller_integration.dart, packages/google_maps_flutter/google_maps_flutter_web/test/test_driver/google_maps_plugin_integration.dart, script/nnbd_plugins.sh
google_maps_flutter_web NNBD migration is currently blocked, but this is an attempt to make a non-NNBD version that's uses the NNBD version of all dependencies for compatibility with the latest versions of other plugins.
* Tested manually in google_maps_flutter example app, with `// @dart=2.9` in its main.dart file.
* All tests pass:
<details>
<summary>Output</summary>
```
plugins/packages/google_maps_flutter/google_maps_flutter_web/test$ ./run_test
chromedriver is running.
No target specified, running all tests...
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
flutter drive -d web-server '--web-port=7357' '--browser-name=chrome' '--target=test_driver/marker_integration.dart'
Running "flutter pub get" in test... …
```
=> [google_maps_flutter_web] Make google_maps_flutter_web work with latest plugins 

packages/image_picker/image_picker/example/ios/RunnerUITests/ImagePickerFromGalleryUITests.m
Removed `otherElements` reference that was waiting to be removed in XCUITests.
Closes https://github.com/flutter/flutter/issues/71927
[Discord]: …
=> [image_picker] fix flutter/flutter#71927

packages/google_maps_flutter/google_maps_flutter_web/example/pubspec.yaml
Mockito 5 + integration_test from SDK in stable are not compatible:
```
google_maps_flutter_web/example$ flutter analyze
Because every version of integration_test from sdk depends on crypto 2.1.5 and analyzer >=1.0.0 depends on crypto ^3.0.0, integration_test from sdk is incompatible with analyzer >=1.0.0.
And because mockito 5.0.0 depends on analyzer ^1.0.0 and no versions of mockito match >5.0.0 <6.0.0, integration_test from sdk is incompatible with mockito ^5.0.0.
So, because google_maps_flutter_web_integration_tests depends on both mockito ^5.0.0 and integration_test any from sdk, version solving failed.
Running "flutter pub get" in example...                                 
pub get failed (1; So, because google_maps_flutter_web_integration_tests depends on both mockito ^5.0.0 and …
```
=> [google_maps_flutter_web] Downgrade mockito in example app.

packages/camera/camera/test/utils/method_channel_mock.dart, packages/camera/camera_platform_interface/test/utils/method_channel_mock.dart, packages/in_app_purchase/test/in_app_purchase_connection/app_store_connection_test.dart, packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart, packages/sensors/test/sensors_test.dart
The service mocks are going to move from services.dart to flutter_test/.
See https://github.com/flutter/flutter/pull/76288
[Discord]: …
=> [various] Import flutter_test for future compatibility

packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md, packages/google_sign_in/google_sign_in_platform_interface/lib/src/method_channel_google_sign_in.dart, packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml, packages/google_sign_in/google_sign_in_platform_interface/test/method_channel_google_sign_in_test.dart
This PR adds support to https://github.com/flutter/plugins/pull/3640 by parametrizing `clientId` property in `MethodChannelGoogleSignIn`
Same issues as https://github.com/flutter/plugins/pull/3640 …
=> [google_sign_in] Updates google_sign_in_platform_interfaces adding parametrized `clientId`

packages/google_sign_in/extension_google_sign_in_as_googleapis_auth/lib/extension_google_sign_in_as_googleapis_auth.dart, packages/google_sign_in/extension_google_sign_in_as_googleapis_auth/test/extension_google_sign_in_as_googleapis_auth_test.dart
Replaces deprecated import with current version.
Fixes https://github.com/flutter/flutter/issues/77610
=> [extension_google_sign_in_as_googleapis_auth] Update import

packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart
https://github.com/flutter/plugins/pull/3686 introduced new params in google_sign_in, which broke the tests after publishing. This PR fixes it. version update is probably not required because no user facing feature is changed. And it should be picked up in a soon to be land PR: https://github.com/flutter/plugins/pull/3640
[CLA]: …
=> [google_sign_in] fix test

packages/video_player/video_player/CHANGELOG.md, packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java, packages/video_player/video_player/pubspec.yaml
exoPlayer.setAudioStreamType has been deprecated. Remove it from the video_player plugin.
Doc: https://developer.android.com/reference/android/media/MediaPlayer#setAudioStreamType(int) …
=> [Video_Player] Remove the deprecated API reference.

script/tool/lib/src/lint_podspecs_command.dart, script/tool/test/lint_podspecs_command_test.dart
Now that the `xctest` command runs the `webview_flutter` #3664 and `image_picker` #3663 unit tests, skip them in the `pod lib lint` test to avoid doubling the work.
See https://github.com/flutter/plugins/pull/3667
Fixes https://github.com/flutter/flutter/issues/77661 (well, avoids it entirely).
=> Skip pod lint tests

.cirrus.yml
- Hoist common properties like `only_if`, `use_compute_credits`, and `env` to top of tasks, out of root template.
- Rename `ROOT_TASK_TEMPLATE` to `FLUTTER_UPGRADE_TEMPLATE`.
- Pull `lint_darwin_plugins` out from the other macOS tasks and don't apply `FLUTTER_UPGRADE_TEMPLATE` since it doesn't use `flutter` tooling, so shouldn't waste the 40 seconds and I/O upgrading.
- Remove `lint_darwin_plugins` subsharding.  Each subshard takes about 4 minutes, so combining them together the 8 minutes is well within the time length of other tests (especially now that they won't upgrade flutter), and avoid scheduling a second Mac machine. https://cirrus-ci.com/task/6550328981061632
- Pull `tool_setup_script` out of `flutter_upgrade_template` so it can be used directly by the `lint_darwin_plugins` task. …
=> Skip flutter upgrade for pod linting Cirrus task

packages/in_app_purchase/example/lib/main.dart
Just fixing typos in the comments in the example code.
=> [in_app_purchase] Typos in comments

packages/shared_preferences/shared_preferences/CHANGELOG.md, packages/shared_preferences/shared_preferences/pubspec.yaml
Fix https://github.com/flutter/flutter/issues/78007 …
=> [shared_preferences] Fix missing declaration of windows' default_package

packages/connectivity/connectivity/CHANGELOG.md, packages/connectivity/connectivity/pubspec.yaml
Fix: https://github.com/flutter/flutter/issues/68669
- [ x All existing and new tests are passing.
[pub …
=> [connectivity] re-endorse connectivity_for_web

.github/PULL_REQUEST_TEMPLATE.md
...so that they are listed in more or less the likely order that people will do them in. …
=> Reorder the checkboxes in the PR template

packages/image_picker/image_picker/CHANGELOG.md, packages/image_picker/image_picker/pubspec.yaml
This PR endorses image_picker_for_web in image_picker_plugin
https://github.com/flutter/flutter/issues/78297 …
=> [image_picker] endorse image_picker_for_web in image_picker plugin

packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/method_channel/method_channel_google_maps_flutter.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/camera.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/circle.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/maps_object.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/polygon.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/polyline.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/tile_overlay.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/camera_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/maps_object_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/maps_object_updates_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/test_maps_object.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/tile_overlay_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/tile_overlay_updates_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/tile_test.dart
=> [google_maps_flutter_platform_interface] Mark constructors as const for ids

packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java, packages/google_sign_in/google_sign_in/example/lib/main.dart, packages/google_sign_in/google_sign_in/ios/Classes/FLTGoogleSignInPlugin.m, packages/google_sign_in/google_sign_in/pubspec.yaml, packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart
This PR introduces the ability to send `clientId` as a parameter in `google_sign_in` plugin. It priorizes the parameterized `clientId` in iOS and Android platforms. If it wasn't send, then they try to fetch it from `GoogleService-info.plist` and `google-services.json` respectively.
- [#66005](https://github.com/flutter/flutter/issues/66005) …
=> [google_sign_in] Adds support to send `clientId` as a parameter

packages/url_launcher/url_launcher/CHANGELOG.md, packages/url_launcher/url_launcher/README.md, packages/url_launcher/url_launcher/pubspec.yaml
Add instructions for iOS, for targeting iOS 9.0 and higher. 
Note:
All new projects 1.22+ targets iOS 9.0 by default 
Related to https://github.com/flutter/flutter/issues/65936
=> [url_launcher] Update readme for URL schemes on iOS

.cirrus.yml
Use flutter-cirrus for Cirrus Linux tasks in the plugins repository.
Bug: https://github.com/flutter/flutter/issues/77624
[Discord]: …
=> Use flutter gcp project for linux tasks.

packages/quick_actions/quick_actions/CHANGELOG.md, packages/quick_actions/quick_actions/example/lib/main.dart, packages/quick_actions/quick_actions/pubspec.yaml
Title now gets replaced immediately after getting set. This way we can't actually see if the plugin works. This fixes this problem by checking if the String has been changed, before setting the "actions ready" value. …
=> [quick_actions] example fix

packages/in_app_purchase/example/README.md
Changed Biling in 'Google Play Biling Overview' to Billing
Changed Biling in 'Google Play Biling Overview' to Billing in the README.md
No related issues.
=> Updated README.md typo

packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/DartMessenger.java, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/MethodCallHandlerImpl.java, packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/DartMessengerTest.java, script/tool/lib/src/java_test_command.dart, script/tool/test/java_test_command_test.dart
The current implementation of the `JavaTestCommand` only looks for a `test` folder under the `./example/android/app/src` folder for a plugin. There are plugins that have their Java tests defined as part of the plugin implementation code (on path `./android/src/test`) and don't have a `test` folder as part of the `./example/android/app/src` path. This means these tests are currently not executed by the plugin CI. Some examples would be:
- camera plugin
- flutter_plugin_android_lifecycle
- path_provider
- url_launcher
We discovered this issue when we where trying to move the Java tests of the "in_app_purchase" plugin from the `./example/android/app/src/test` folder to the `./android/src/test` folder and noticed that the CI suddenly doesn't execute Java tests anymore (see PR #3732).
Note …
=> [flutter_plugin_tools] Also look for Java tests in plugin path

script/incremental_build.sh, script/tool/lib/src/analyze_command.dart, script/tool/test/analyze_command_test.dart
The current incremental_script.sh is invoking the analyze_command incorrectly (passing an empty value to the `--custom-analysis` parameter)
This is causing the analysis not to run correctly in CI.
Related to https://github.com/flutter/flutter/issues/78994
[breaking …
=> [ci] Do not use empty exclude directories in analyze_command.

packages/in_app_purchase/in_app_purchase/AUTHORS, packages/in_app_purchase/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/in_app_purchase/lib/src/in_app_purchase/app_store_connection.dart, packages/in_app_purchase/in_app_purchase/pubspec.yaml, packages/in_app_purchase/in_app_purchase/test/in_app_purchase_connection/app_store_connection_test.dart
Fixes the error message when trying to consume a "consumable product" on iOS. On iOS consuming products manually is not supported and therefore the `consumePurchase` method on iOS will result in a `UnsupportedError`. Unfortunately the error message of the error mentioned the "Android" platform:
> consume purchase is not available on Android
This PR updates the error message and also extended the unit test to ensure the correct platform is mentioned.
The problem is mentioned as part of issue flutter/flutter#60763 (see this [comment](https://github.com/flutter/flutter/issues/60763#issuecomment-796968009))
If you need help, consider asking for advice on the …
=> [in_app_purchase] Fix error message when trying to consume purchase on iOS

packages/in_app_purchase/in_app_purchase/AUTHORS, packages/in_app_purchase/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/in_app_purchase/lib/src/in_app_purchase/app_store_connection.dart, packages/in_app_purchase/in_app_purchase/pubspec.yaml, packages/in_app_purchase/in_app_purchase/test/in_app_purchase_connection/app_store_connection_test.dart
Reverts flutter/plugins#3750
Reverting this PR since I updated with the wrong version number (should have been `0.5.1+1` instead of `0.5.2`). Will resubmit the PR with the correct version number.
=> Revert "[in_app_purchase] Fix error message when trying to consume purchase on iOS"

packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/method_channel/method_channel_google_maps_flutter.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/method_channel/method_channel_google_maps_flutter_test.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/platform_interface/google_maps_flutter_platform_test.dart
During the null-safety migration I accepted the auto-migrator use of `as Future<T>` to handle `invokeMethod<T>` returning a `T?`. I didn't realize that `as` does not actually do that kind of casting, and will fail with `type 'Future<T?>' is not a subtype of type 'Future<T>' in type cast`.
There were no tests that exercised these methods in any way, so automated tests didn't catch the bug. This adds a minimal test that calls all of the non-void methods to ensure that they don't explode (and a TODO to backfill full unit tests of the entire method channel).
Fixes https://github.com/flutter/flutter/issues/78426
Fixes https://github.com/flutter/flutter/issues/78856 …
=> [google_maps_flutter] Fix handling of non-nullable invokeMethod return types

packages/quick_actions/quick_actions/README.md
=> [quick_actions] Update "eponymous concept" link.

packages/google_sign_in/google_sign_in_web/lib/src/generated/gapi.dart, packages/in_app_purchase/in_app_purchase/lib/src/in_app_purchase/in_app_purchase_connection.dart
Question marks used with `dynamic` are redundant and are flagged by dart analysis tools as of https://dart-review.googlesource.com/c/sdk/+/190041.
Plugin code need to be analysis-clean.
Fixes https://github.com/flutter/flutter/issues/79089
=> Drop redundant question marks used with dynamic.

packages/android_intent/README.md
When using `dart:io`, the `Platform` class is capitalised in the latest stable Flutter release. This PR fixes this minor issue in the README, where this class was previously uncapitalised. I've briefly looked at the other docs available and I don't think this mistake exists anywhere else.
=> Capitalise Platform class in README

packages/flutter_plugin_android_lifecycle/CHANGELOG.md, packages/flutter_plugin_android_lifecycle/android/build.gradle, packages/flutter_plugin_android_lifecycle/android/proguard.txt, packages/flutter_plugin_android_lifecycle/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/78625
Fixes https://github.com/flutter/flutter/issues/69820
Fixes https://github.com/flutter/flutter/issues/58479
Fixes https://github.com/flutter/flutter/issues/77622
=> Make sure androidx.lifecycle classes aren't R8'ed away when using flutter_plugin_android_lifecycle

script/build_all_plugins_app.sh, script/tool/lib/src/create_all_plugins_app_command.dart, script/tool/test/create_all_plugins_app_command_test.dart, script/tool/test/util.dart
Flutter master now creates NNBD code when running 'flutter create', so
the generated pubspec for build_all needs to use a compatible SDK
version. This updates from 2.0.0 to 2.12.0.
Also includes a test for this, which involved setting up tests for the
file, and doing some refactoring to make the command testable. As a
result, this fixes https://github.com/flutter/flutter/issues/61049
(although more test backfill is needed).
[CLA]: …
=> Update build-all test for null-safe template

packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/tile_overlay.dart, packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml, packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/tile_overlay_test.dart
TileOverlay was not copying its TileProvider. During the NNBD migration,
map object updates were refactored to share code, and in that
refactoring TileOverlay update construction was aligned with other map
objects to use clones, so certain operations involving TileOverlays
started dropping the TileProvider.
Fixes https://github.com/flutter/flutter/issues/77500 …
=> [google_maps_flutter] Fix TileOverlay cloning

packages/google_maps_flutter/google_maps_flutter_web/example/pubspec.yaml
This version of mockito is too new to solve with null safe test deps, but not new enough where it works with the latest versions of everything. Allow older versions so that we can guarantee a version solve once https://github.com/flutter/flutter/pull/79099 rolls in
Work towards https://github.com/flutter/flutter/issues/77856
=> let google_maps_flutter_web version solve for older mockito

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/example/lib/tile_overlay.dart, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
The TileOverlay portion of the example app incorrectly constructed a
Set<TileOverlay?> and then attempted to cast it to a Set<TileOverlay>,
rather than making a set of non-nullable types as required by the API.
Fixes https://github.com/flutter/flutter/issues/79242 …
=> [google_maps_flutter] Fix NNBD migration mistake in example

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/lib/src/webview_android.dart, packages/webview_flutter/pubspec.yaml, packages/webview_flutter/test/webview_flutter_test.dart
Fixes a bug where scroll bars on the Android non-hybrid WebView are rendered on the wrong side of the screen.
https://github.com/flutter/flutter/issues/79312 …
=> [webview_flutter] Fix scroll bar position for Android non-hybrid WebViews

packages/local_auth/CHANGELOG.md, packages/local_auth/android/build.gradle, packages/local_auth/pubspec.yaml
The plugin was still using several beta version of Jetpack libraries
from 2 years ago. Updates to the latest stable version of each.
No new test as this is not intended to be a behavioral change.
Fixes https://github.com/flutter/flutter/issues/52742 …
=> [local_auth] Update Jetpack dependencies

script/tool/lib/src/common.dart, script/tool/lib/src/publish_plugin_command.dart, script/tool/test/publish_plugin_command_test.dart
Refactoring publish plugin command to get ready for a new feature to publish and tag release based on git diff.
See https://github.com/flutter/plugins/pull/3776#issuecomment-811574215
behavioral change: The command now validate the git remote first before checking package directory. Because when we change this command later to run multiple publishes, the git remote validation only needs to happen once.
=> [tool] refactor publish plugin command

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md, packages/google_maps_flutter/google_maps_flutter/README.md, packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Improves wording of the Getting Started chapter in the google maps flutter readme.
Fixes https://github.com/flutter/flutter/issues/79633
I assume no changelog entry is needed for this change?
=> [google_maps_flutter] Reword README

packages/webview_flutter/CHANGELOG.md, packages/webview_flutter/example/integration_test/webview_flutter_test.dart, packages/webview_flutter/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, packages/webview_flutter/ios/Classes/FlutterWebView.m, packages/webview_flutter/pubspec.yaml
This PR fixes the `allowsInlineMediaPlayback` flag ignored on iOS.
This PR also enables some tests that were failing before, as well as the test for `allowsInlineMediaPlayback`
Fixes: https://github.com/flutter/flutter/issues/73768
Fixes: https://github.com/flutter/flutter/issues/72572 …
=> [flutter_webview] Fix `allowsInlineMediaPlayback` ignored on iOS

packages/in_app_purchase/in_app_purchase/CHANGELOG.md, packages/in_app_purchase/in_app_purchase/example/README.md, packages/in_app_purchase/in_app_purchase/example/ios/Runner.xcodeproj/project.pbxproj, packages/in_app_purchase/in_app_purchase/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, packages/in_app_purchase/in_app_purchase/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/in_app_purchase/in_app_purchase/example/ios/Runner/Configuration.storekit, packages/in_app_purchase/in_app_purchase/pubspec.yaml
Configured example app to use StoreKit Testing on iOS 14 and higher. 
- Fixes flutter/flutter#79286 …
=> [in_app_purchase] Configured example app to use StoreKit Testing on iOS 14

packages/google_sign_in/google_sign_in/CHANGELOG.md, packages/google_sign_in/google_sign_in/ios/Classes/FLTGoogleSignInPlugin.m, packages/google_sign_in/google_sign_in/ios/Tests/GoogleSignInPluginTest.m, packages/google_sign_in/google_sign_in/pubspec.yaml
iOS Google Sign-in flow was always forcing user to fill email and password, the null check fixes the account picker, so the flow suggest Google Accounts already signed-in on iOS device.
Fixes: flutter/flutter#48602 …
=> [google_sign_in] Fix "pick account" on iOS

packages/quick_actions/quick_actions/CHANGELOG.md, packages/quick_actions/quick_actions/example/ios/Runner/AppDelegate.m, packages/quick_actions/quick_actions/example/ios/RunnerUITests/RunnerUITests.m, packages/quick_actions/quick_actions/ios/Classes/FLTQuickActionsPlugin.m, packages/quick_actions/quick_actions/pubspec.yaml
According to Apple's documentation (see the "Discussion" section [here](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623032-application?language=objc)) the `application:performActionForShortcutItem:` method is not executed when the `willFinishLaunchingWithOptions:` or the `didFinishLaunchingWithOptions:` return `NO`. In these cases the `willFinishLaunchingWithOptions:` or `didFinishLaunchingWithOptions:` method are responsible for handling quick actions.
Basic Flutter applications will always return `YES` for the `willFinishLaunchingWithOptions:` and `didFinishLaunchingWithOptions:` methods, however in more advanced cases developers might override these methods and provide custom implementations which might result in one of these method to return `NO`. In these …
=> [quick_actions] handle cold start on iOS correctly

packages/path_provider/path_provider_windows/CHANGELOG.md, packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart, packages/path_provider/path_provider_windows/pubspec.yaml
Failures to get a known folder that don't throw Windows exceptions need
to return null.
Fixes flutter/flutter#80712
=> Path provider windows crash fix

packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraProperties.java, packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/CameraFeature.java, packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/CameraPropertiesImplTest.java
Introduces some base classes in the Android Camera implementation which will allow us to separate specific feature logic from the `Camera` class into specific feature classes. This has the following benefits (basically all benefits of the Separation of Concerns principle):
- It allows for focussed feature classes making it easier to maintain the implementation of the feature;
- It will reduce the amount of code currently in the `Camera` class, making it easier to maintain the `Camera` class;
- It will be easier to write unit-tests to cover the feature logic.
This is the first PR in a series of pull-requests which will gradually introduce changes from PR #3651, making it easier to review the code (as discussed with @stuartmorgan).
*If you had to change anything in the [flutter/tests] repo, …
=> [camera] android-rework part 1: Base classes to support Android Camera features
