- script/tool/lib/src/common.dart
- script/tool/lib/src/version_check_command.dart
- script/tool/test/version_check_test.dart
Allow versions for new packages. Skip version check if master version is null.
Failure here: https://cirrus-ci.com/task/6433272113659904
[Discord]: …
> [tools] fix version check command not working for new packages

- packages/google_sign_in/google_sign_in/lib/google_sign_in.dart
See https://github.com/flutter/flutter/issues/80905
> Add a todo WRT correctly setting the X-Goog-AuthUser header

- packages/path_provider/path_provider/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider/integration_test/path_provider_test.dart
- packages/path_provider/path_provider/lib/path_provider.dart
- packages/path_provider/path_provider_linux/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider_macos/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider_windows/example/integration_test/path_provider_test.dart
The upcoming linter release includes a fix to sort_directives that will trigger a host of new violations in plugins. 
See, e.g., https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8849192101410026592/+/u/flutter_test_flutter_plugins/stdout
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutte …
> [path_provider_*] code cleanup: sort directives

- packages/in_app_purchase/in_app_purchase_platform_interface/lib/src/types/product_details.dart
- packages/in_app_purchase/in_app_purchase_platform_interface/test/src/types/product_details_test.dart
Adds the `rawPrice` and `currencyCode` fields to the `ProductDetails` class defined in the "in_app_purchase_platform_interface" package. 
These fields were added to the "in_app_purchase" package as part of PR #3794, but never made it in the initial definition of the "in_app_purchase_platform_interface". …
> [in_app_purchase_platform_interface] Added additional fields to ProductDetails

- script/tool/lib/src/common.dart
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/lib/src/format_command.dart
- script/tool/lib/src/lint_podspecs_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/publish_plugin_command_test.dart
- script/tool/test/util.dart
`runAndExitOnError` is just a sub version of `run`, this PR combines then into a single method, which also separates the functionality of throw error and log error. …
> [tool] combine run and runAndExitOnError

- CONTRIBUTING.md
To fix grammatical errors in CONTRIBUTING.md
> Fix grammatical error in contributing guide

- packages/in_app_purchase/in_app_purchase_platform_interface/lib/src/types/purchase_details.dart
While implementing the new `in_app_purchase_platform_interface` I noticed that the `PurchaseDetails.status` property was migrated as a nullable field while the implementations always consider it as a mandatory (non-nullable) field. 
This PR corrects this mistakes and makes sure the `PurchaseDetails.status` field doesn't accept a `null` value and when a new instance is created a status value has to be supplied.
The original migration PR can be found here: #3781  …
> [in_app_purchase] Make PurchaseDetails.status mandatory

- script/tool/lib/src/analyze_command.dart
- script/tool/test/analyze_command_test.dart
This PR switches from using `tuneup` to analyze the repository plugins to using `dart analyze`. 'dart analyze' works the same (it uses the analysis server) but is a more modern implementation of compared to tuneup.
- [-] I listed at least one issue that this PR fixes in the description above.
- [-] I updated CHANGELOG.md to add a description of the change. …
> switch from using 'tuneup' to analyze to 'dart analyze' [infra]

- script/tool/CHANGELOG.md
- script/tool/bin/flutter_plugin_tools.dart
- script/tool/pubspec.yaml
This should have been re-added in #3836 but was missed, so it doesn't
work correctly via `pub global`.
[pub …
> Re-add bin/ to flutter_plugin_tools

- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/publish_plugin_command_test.dart
- script/tool/test/util.dart
Add a new `all` flag  to the `publish plugin` command does the following:
1. Look for all the pubspec changes in the current commit and determine what plugin(s) need to be released.  If the new version is lower than the existing latest tagged version, skip. 
1. Release the plugin as how `publish-plugin` works: publishing to pub, git tag release etc. 
Add a new `dry-run` flag to dry-run the publish and tag release process. This is for testing locally and ci without actually publishing or git tag anything.
This command is going to be part of auto-publish workflow.
part of https://github.com/flutter/flutter/issues/79830 …
> [tool] add `all` and `dry-run` flags to publish-plugin command

- script/tool/CHANGELOG.md
- script/tool/lib/src/license_check_command.dart
- script/tool/pubspec.yaml
- script/tool/test/license_check_command_test.dart
In preparation for enabling license checks in flutter/packages, update
the allowed licenses:
- Allow our license, for cases where we've locally added files
- Allow the license used by the bsdiff package …
> Update third_party license checking

- packages/connectivity/connectivity_macos/CHANGELOG.md
- packages/connectivity/connectivity_macos/pubspec.yaml
- packages/path_provider/path_provider/lib/path_provider.dart
- packages/path_provider/path_provider_linux/CHANGELOG.md
- packages/path_provider/path_provider_linux/lib/path_provider_linux.dart
- packages/path_provider/path_provider_linux/pubspec.yaml
- packages/path_provider/path_provider_linux/test/path_provider_linux_test.dart
- packages/path_provider/path_provider_macos/CHANGELOG.md
- packages/path_provider/path_provider_macos/pubspec.yaml
- packages/path_provider/path_provider_windows/CHANGELOG.md
- packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart
- packages/path_provider/path_provider_windows/lib/src/path_provider_windows_stub.dart
- packages/path_provider/path_provider_windows/pubspec.yaml
- packages/path_provider/path_provider_windows/test/path_provider_windows_test.dart
- packages/shared_preferences/shared_preferences/lib/shared_preferences.dart
- packages/shared_preferences/shared_preferences_linux/CHANGELOG.md
- packages/shared_preferences/shared_preferences_linux/lib/shared_preferences_linux.dart
- packages/shared_preferences/shared_preferences_linux/pubspec.yaml
- packages/shared_preferences/shared_preferences_linux/test/shared_preferences_linux_test.dart
- packages/shared_preferences/shared_preferences_macos/CHANGELOG.md
- packages/shared_preferences/shared_preferences_macos/pubspec.yaml
- packages/shared_preferences/shared_preferences_windows/CHANGELOG.md
- packages/shared_preferences/shared_preferences_windows/lib/shared_preferences_windows.dart
- packages/shared_preferences/shared_preferences_windows/pubspec.yaml
- packages/shared_preferences/shared_preferences_windows/test/shared_preferences_windows_test.dart
Partially relands the changes required to get auto registration working.
Related issue: https://github.com/flutter/flutter/issues/81421
>  Add implement and registerWith method to plugins

- script/tool/lib/src/common.dart
- script/tool/test/common_test.dart
- script/tool/test/util.dart
flutter/packages has two packages in third_party/packages/, which wasn't something our tooling recognized, so no package-based CI checks are running on them. This adds knowledge that there can be a third_party/packages/ directory as a sibling of the primary packages directory.
Also migrates common_tests off of the shared (now deprecated) mock filesystem and onto a test-local mock filesystem.
Fixes https://github.com/flutter/flutter/issues/81570 …
> Add support for third_party packages in Dart code

- .cirrus.yml
- script/incremental_build.sh
- script/tool/lib/src/common.dart
Switch incremental_build.sh from using the older check_changed_packages
implemented in bash to the newer (tested/testable) Dart implementation
via --run-on-changed-packages.
Also clarifies in help that the flag runs on all packages when nothing
has changed.
[breaking …
> Move incremental_build.sh to run-on-changed-packages

- packages/image_picker/image_picker/CHANGELOG.md
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
[CLA]: …
> [image_picker]Fix the description

- .cirrus.yml
ios_platform_images does not currently have an integration test, and file_chooser does not have a web integration test, so both must be explicitly excluded due to recent tooling changes.
See:
https://github.com/flutter/flutter/issues/82208
https://github.com/flutter/flutter/issues/82211 …
> Exclude some missing integration tests

- packages/in_app_purchase/in_app_purchase_platform_interface/lib/in_app_purchase_platform_interface.dart
- packages/in_app_purchase/in_app_purchase_platform_interface/lib/src/errors/errors.dart
- packages/in_app_purchase/in_app_purchase_platform_interface/lib/src/errors/in_app_purchase_exception.dart
- packages/in_app_purchase/in_app_purchase_platform_interface/test/src/errors/in_app_purchase_exception_test.dart
This PR adds the `InAppPurchaseException` class to the in_app_purchase_platform_interface exception as discussed in this comment: https://github.com/flutter/plugins/pull/3841#discussion_r625234328
When this is merged I will remove the `InAppPurchaseException` from the in_app_platform_android implementation that is currently part of PR #3841.
This PR is part of the effort to migrate the in_app_purchase plugin to the Federated plugin architecture: flutter/flutter#78525
- This change will be part of version 1.0.0 which is already merged into master but not yet published. 
- This change will be part of version 1.0.0 which is already merged into master but not …
> [in_app_purchase] Add InAppPurchaseException to platform interface

- packages/in_app_purchase/in_app_purchase/README.md
This PR adds a warning to the readme file for the `in_app_purchase` plugin. It informs the user that conflicts might occur if they choose to depend on the billing client library in their own app in addition to the dependency added by the plugin itself. 
Related issue:
- flutter/flutter#59400 …
> [in_app_purchase] Add warning in readme for double import of the Android billing client library

- .github/post_merge_labeler.yml
If a PR didn't change pubspec.yaml, then it doesn't need to be published.
Should reduce false-positives on the label.
> Only mark PRs for publishing that change pubspec

- packages/camera/camera/test/camera_image_stream_test.dart
- packages/video_player/video_player/test/video_player_initialization_test.dart
Use TestWidgetsFlutterBinding.ensureInitialized(); to make sure necessary resources are initliazed.
This partially fix the currently broken CI. 
[Discord]: …
> [video_player][camera] fix video_player camera tests

- CONTRIBUTING.md
Rewrites to point to documentation that has been move to the Flutter wiki so that the main document is much shorter, and better matches the flutter/flutter and flutter/engine CONTRIBUTING.md. …
> Overhaul CONTRIBUTING.md

- script/tool/README.md
Updates to better reflect that this tooling is still used in flutter/packages, and how that differs from the flutter/plugins usage.
Part of an overall overhaul of flutter/plugins and flutter/packages docs.
> Update tool README for packages use

- script/tool/lib/src/analyze_command.dart
- script/tool/lib/src/build_examples_command.dart
- script/tool/lib/src/drive_examples_command.dart
- script/tool/lib/src/format_command.dart
- script/tool/lib/src/java_test_command.dart
- script/tool/lib/src/license_check_command.dart
- script/tool/lib/src/list_command.dart
- script/tool/lib/src/test_command.dart
- script/tool/test/analyze_command_test.dart
- script/tool/test/build_examples_command_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/java_test_command_test.dart
- script/tool/test/license_check_command_test.dart
- script/tool/test/list_command_test.dart
- script/tool/test/mocks.dart
- script/tool/test/test_command_test.dart
Now that individual commands can be migrated, migrate several commands
that are trivially migratable (along with their tests).
Part of https://github.com/flutter/flutter/issues/81912
[pub …
> Migrate some tool commands to NNBD

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/README.md
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
Added a reference to the in-app purchase codelab in the README.md file, as discussed per offline discussion.
**Note:** this PR should not be published before the actual codelab has been published.
[CLA]: …
> [in_app_purchase] Add reference to the codelab in the README

- packages/espresso/CHANGELOG.md
- packages/espresso/analysis_options.yaml
- packages/espresso/example/lib/main.dart
- packages/espresso/example/test_driver/example.dart
- packages/espresso/pubspec.yaml
- Stop using the legacy analysis options
- Switch from "homepage" to "repository" in pubspec.yaml (and fix the link)
- Add a specific issue query as "issue_tracker" in pubspec.yaml
[pub …
> [espresso] Minor cleanup

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/android/build.gradle
- packages/url_launcher/url_launcher/example/android/build.gradle
- packages/url_launcher/url_launcher/pubspec.yaml
url_launcher part of https://github.com/flutter/flutter/issues/82847
> [url_launcher] Migrate maven repo from jcenter to mavenCentral

- packages/battery/battery/CHANGELOG.md
- packages/battery/battery/android/build.gradle
- packages/battery/battery/example/android/build.gradle
- packages/battery/battery/pubspec.yaml
battery part of https://github.com/flutter/flutter/issues/82847
> [battery] Migrate maven repo from jcenter to mavenCentral

- packages/device_info/device_info/CHANGELOG.md
- packages/device_info/device_info/android/build.gradle
- packages/device_info/device_info/example/android/build.gradle
- packages/device_info/device_info/pubspec.yaml
device_info part of https://github.com/flutter/flutter/issues/82847
> [device_info] Migrate maven repo from jcenter to mavenCentral

- packages/connectivity/connectivity/CHANGELOG.md
- packages/connectivity/connectivity/android/build.gradle
- packages/connectivity/connectivity/example/android/build.gradle
- packages/connectivity/connectivity/pubspec.yaml
connectivity part of https://github.com/flutter/flutter/issues/82847
> [connectivity] Migrate maven repo from jcenter to mavenCentral

- packages/path_provider/path_provider/CHANGELOG.md
- packages/path_provider/path_provider/android/build.gradle
- packages/path_provider/path_provider/example/android/build.gradle
- packages/path_provider/path_provider/pubspec.yaml
path_provider part of https://github.com/flutter/flutter/issues/82847
> [path_provider] Migrate maven repo from jcenter to mavenCentral

- packages/espresso/CHANGELOG.md
- packages/espresso/android/build.gradle
- packages/espresso/example/android/build.gradle
- packages/espresso/pubspec.yaml
espresso part of https://github.com/flutter/flutter/issues/82847
> [espresso] Migrate maven repo from jcenter to mavenCentral

- packages/sensors/CHANGELOG.md
- packages/sensors/android/build.gradle
- packages/sensors/example/android/build.gradle
- packages/sensors/pubspec.yaml
sensors part of https://github.com/flutter/flutter/issues/82847
> [sensors] Migrate maven repo from jcenter to mavenCentral

- packages/flutter_plugin_android_lifecycle/CHANGELOG.md
- packages/flutter_plugin_android_lifecycle/android/build.gradle
- packages/flutter_plugin_android_lifecycle/example/android/build.gradle
- packages/flutter_plugin_android_lifecycle/pubspec.yaml
flutter_plugin_android_lifecycle part of https://github.com/flutter/flutter/issues/82847
> [flutter_plugin_android_lifecycle] Migrate maven repo from jcenter to mavenCentral

- packages/wifi_info_flutter/wifi_info_flutter/CHANGELOG.md
- packages/wifi_info_flutter/wifi_info_flutter/android/build.gradle
- packages/wifi_info_flutter/wifi_info_flutter/example/android/build.gradle
- packages/wifi_info_flutter/wifi_info_flutter/pubspec.yaml
wifi_info_flutter part of https://github.com/flutter/flutter/issues/82847
> [wifi_info_flutter] Migrate maven repo from jcenter to mavenCentral

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/android/build.gradle
- packages/google_maps_flutter/google_maps_flutter/example/android/build.gradle
- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
google_maps_flutter part of https://github.com/flutter/flutter/issues/82847
> [google_maps_flutter] Migrate maven repo from jcenter to mavenCentral

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/android/build.gradle
- packages/google_sign_in/google_sign_in/example/android/build.gradle
- packages/google_sign_in/google_sign_in/pubspec.yaml
google_sign_in part of https://github.com/flutter/flutter/issues/82847
> [google_sign_in] Migrate maven repo from jcenter to mavenCentral

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/android/build.gradle
- packages/android_alarm_manager/example/android/build.gradle
- packages/android_alarm_manager/pubspec.yaml
android_alarm_manager part of https://github.com/flutter/flutter/issues/82847
> [android_alarm_manager] Migrate maven repo from jcenter to mavenCentral

- packages/android_intent/CHANGELOG.md
- packages/android_intent/android/build.gradle
- packages/android_intent/example/android/build.gradle
- packages/android_intent/pubspec.yaml
android_intent part of https://github.com/flutter/flutter/issues/82847
> [android_intent] Migrate maven repo from jcenter to mavenCentral

- packages/package_info/CHANGELOG.md
- packages/package_info/android/build.gradle
- packages/package_info/example/android/build.gradle
- packages/package_info/pubspec.yaml
package_info part of https://github.com/flutter/flutter/issues/82847
> [package_info] Migrate maven repo from jcenter to mavenCentral

- packages/shared_preferences/shared_preferences/CHANGELOG.md
- packages/shared_preferences/shared_preferences/android/build.gradle
- packages/shared_preferences/shared_preferences/example/android/build.gradle
- packages/shared_preferences/shared_preferences/pubspec.yaml
shared_preferences part of https://github.com/flutter/flutter/issues/82847
> [shared_preferences] Migrate maven repo from jcenter to mavenCentral

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/android/build.gradle
- packages/video_player/video_player/example/android/build.gradle
- packages/video_player/video_player/pubspec.yaml
video_player part of https://github.com/flutter/flutter/issues/82847
> [video_player] Migrate maven repo from jcenter to mavenCentral

- packages/path_provider/path_provider/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider/example/test_driver/integration_test.dart
- packages/path_provider/path_provider_linux/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider_linux/example/test_driver/integration_test.dart
- packages/path_provider/path_provider_macos/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider_macos/example/test_driver/integration_test.dart
- packages/path_provider/path_provider_windows/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider_windows/example/test_driver/integration_test.dart
Updates #3644 from the branch where we were experimenting with null-safe integration tests for changes on master.
> [path_provider] Migrate all integration tests to NNBD

- .cirrus.yml
- packages/sensors/CHANGELOG.md
- packages/sensors/ios/Classes/FLTSensorsPlugin.m
- packages/sensors/pubspec.yaml
Keep the Xcode version to latest available Cirrus image.
Fix new sensor plugin analyzer warning.  This is already tested by the analyzer linters.
Fixes https://github.com/flutter/flutter/issues/82953
> [sensors] Update Cirrus image to Xcode 12.5, fix sensors analyzer warning 

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/android/build.gradle
- packages/camera/camera/example/android/build.gradle
- packages/camera/camera/pubspec.yaml
Remove `exoplayer` workaround introduced in #977.  See also https://github.com/google/ExoPlayer/issues/5246.
Remove trailing whitespace from CHANGELOG and pubspec.
camera part of https://github.com/flutter/flutter/issues/82847
> [camera] Migrate maven repo from jcenter to mavenCentral

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m
- packages/image_picker/image_picker/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/82959.  Warning introduced in #3881.  There are already tests for this failing on master (I'm not sure why it succeeded on presubmit, `GCC_TREAT_WARNINGS_AS_ERRORS` is set to `YES`).
https://api.cirrus-ci.com/v1/task/6726759736410112/logs/xctest.log
> [image_picker] Fix camera alert localization analyzer warning

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/ios/Classes/messages.m
- packages/video_player/video_player/pubspec.yaml
Fix `Converting a pointer value of type 'NSNumber * _Nullable' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue` analyzer warnings.
Fixes https://github.com/flutter/flutter/issues/82958
> [video_player] Fix pointer value to boolean conversion analyzer warnings

- packages/connectivity/connectivity/CHANGELOG.md
- packages/connectivity/connectivity/example/ios/Podfile
- packages/connectivity/connectivity/pubspec.yaml
- packages/connectivity/connectivity_macos/CHANGELOG.md
- packages/connectivity/connectivity_macos/example/macos/Podfile
- packages/connectivity/connectivity_macos/pubspec.yaml
Suppress Reachability dependency warning in iOS and macOS example app.
Fixes https://github.com/flutter/flutter/issues/82964
> [connectivity] Ignore Reachability pointer to int cast warning

- packages/wifi_info_flutter/wifi_info_flutter/example/ios/Podfile
Suppress Reachability dependency warning in iOS example app.
This is https://github.com/flutter/plugins/pull/3941 but applied to wifi_info_flutter …
> [wifi_info_flutter] Ignore Reachability pointer to int cast warning

- script/tool/CHANGELOG.md
- script/tool/lib/src/common.dart
- script/tool/pubspec.yaml
- script/tool/test/common_test.dart
Changes to some files (e.g., CI scripts) have the potential to cause
failures in any packages, without changes to those packages themselves.
This updates the --run-on-changed-packages to consider all packages as
changed if any of those files are changed, to avoid issues where a
change that changes both some repo-level files and some package-specific
files only run presubmit tests on the packages that are directly
changed, causing post-submit-only failures.
Fixes https://github.com/flutter/flutter/issues/82965 …
> Make run-on-changed-packages flag handle repo-level changes

- packages/url_launcher/url_launcher/lib/src/link.dart
- packages/url_launcher/url_launcher/pubspec.yaml
- packages/url_launcher/url_launcher/test/link_test.dart
One of the Link tests relied on internal implementation details of
url_launcher_platform_interface that have changed, so started failing
when the new version of that plugin was published.
This replaces that test with a test that the relevant
url_launcher_platform_interface function is called, without asserting
anything about how it works internally. …
> [url_launcher] Fix Link test

- packages/webview_flutter/example/integration_test/webview_flutter_test.dart
The native view's scroll position is not always settled by the time the
first set call is made, so that change can be stomped. This adds an
initial fetch of the scroll position to give the view time to stabilize.
This is not a guaranteed fix, since it's not clear why the position is
changing and thus what (if anything) we could reliably listen to
post-load, but in practice appears to fix the race. …
> [webview_flutter] Fix race in test

- packages/share/CHANGELOG.md
- packages/share/android/build.gradle
- packages/share/example/android/build.gradle
- packages/share/pubspec.yaml
share part of https://github.com/flutter/flutter/issues/82847
> [share] Migrate maven repo from jcenter to mavenCentral

- packages/url_launcher/url_launcher_web/example/integration_test/link_widget_test.dart
Replace the per-platform-view shadow dom query with a top-level shadow dom query.
Fixes breakage from https://github.com/flutter/engine/pull/25747 …
> [url_launcher] Fix Link test breakage from shadow DOM changes

- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/InAppPurchasePlugin.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Tests/InAppPurchasePluginTest.m
- packages/webview_flutter/ios/Classes/FLTWKProgressionDelegate.m
- packages/webview_flutter/ios/Classes/FlutterWebView.m
Replaces the harder-to-read and more-error-prone
dictionaryWithObjectsAndKeys: and dictionaryWithObject:forKey: with
modern dictionary literals.
Also replaces numberWith*: with boxed literal syntax.
[Discord]: …
> Use collection and box literals in ObjC code

- packages/url_launcher/url_launcher/test/link_test.dart
- packages/url_launcher/url_launcher_platform_interface/test/link_test.dart
Combines https://github.com/flutter/plugins/pull/3965 and https://github.com/flutter/plugins/pull/3963:
* This test broke because it relies on implementation details that are no longer valid. We believe it is redundant with the test above it and the test in the interface package at this point.
* ChannelBuffers is actually async so we have to run the test using runAsync otherwise the future will never complete. …
> [url_launcher] and [url_launcher_platform_interface] Fix tests broken my ChannelBuffers migration

- packages/quick_actions/quick_actions/example/integration_test/quick_actions_test.dart
- packages/quick_actions/quick_actions/example/test_driver/integration_test.dart
- packages/quick_actions/quick_actions/pubspec.yaml
Reverts the quick_action portion of:
"Move integration test to null safety for multiple plugins (#3932)"
(commit a864de25001baaea6596420cf2a3b79948e01825) since it seems to have
broken XCUITests. …
> [quick-actions] Revert migrating integration tests to NNBD

- script/tool/lib/src/publish_check_command.dart
- script/tool/test/publish_check_command_test.dart
pub publish --dry-run always prints output on stderr, so the output of
the tool's publish check was printing "Packages has 0 warnings." as if
it were an error. This fixes that to highlight it as a success message
instead of an error.
[Discord]: …
> Fix publish-check output

- packages/battery/battery_platform_interface/pubspec.yaml
- packages/camera/camera/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_web/example/pubspec.yaml
- packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
- packages/google_sign_in/google_sign_in_web/example/pubspec.yaml
- packages/image_picker/image_picker/example/pubspec.yaml
- packages/image_picker/image_picker/pubspec.yaml
- packages/in_app_purchase/in_app_purchase/example/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_platform_interface/pubspec.yaml
- packages/plugin_platform_interface/pubspec.yaml
- packages/sensors/pubspec.yaml
- packages/shared_preferences/shared_preferences_windows/example/pubspec.yaml
- packages/url_launcher/url_launcher/example/pubspec.yaml
- packages/url_launcher/url_launcher_platform_interface/pubspec.yaml
- packages/url_launcher/url_launcher_web/example/pubspec.yaml
- Standardize on mockito 5.0 now that the conflicts with SDK packages is
resolved on stable.
- Removes overrides that were only needed for Flutter 2.0
- Update a -nullsafe inter-package dependency
- Update some older federated examples that used dependency_overrides to
depend on its encloding package by path to the now-standard option of
listing that path-based dependency directly.
Does not update versions since these changes are all to dev_dependencies and/or examples, so don't need to be published. …
> Clean up cruft in pubspec.yaml files

- packages/video_player/video_player/example/integration_test/video_player_test.dart
- packages/video_player/video_player/example/test_driver/integration_test.dart
- packages/video_player/video_player/example/test_driver/video_player.dart
- packages/video_player/video_player/example/test_driver/video_player_test.dart
Enables null safety for integration tests now that it is supported on master.
> [video_player] Migrate integration tests to NNBD

- packages/camera/camera/example/android/build.gradle
- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/android/build.gradle
- packages/video_player/video_player/example/android/build.gradle
- packages/video_player/video_player/pubspec.yaml
JCenter has the older version of ExoPlayer that the plugin currently uses, but Google's maven server doesn't so we need to add a workaround in the short term for the removal of JCenter in #3924 to avoid breaking clients of video_player.
This was not caught in presubmit because the video_player example had this same workaround left over from an issue several years ago that caused JCenter not to have that version either; that issue was since fixed, but the workaround was never removed. This removes the example-level workaround so the example won't mask exoplayer maven issues in the future.
(Also temporarily re-adds the workaround to the camera example, which broke post-publishing, to fix the tree. All example workarounds should be removable once this change is published.)
[Contributor …
> [video_player] Add URL for exoplayer to maven for all dependents

- packages/local_auth/CHANGELOG.md
- packages/local_auth/android/build.gradle
- packages/local_auth/example/android/build.gradle
- packages/local_auth/pubspec.yaml
local_auth part of https://github.com/flutter/flutter/issues/82847
> [local_auth] Migrate maven repo from jcenter to mavenCentral

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/build.gradle
- packages/webview_flutter/example/android/build.gradle
- packages/webview_flutter/pubspec.yaml
wifi_info_flutter part of https://github.com/flutter/flutter/issues/82847
> [webview_flutter] Migrate maven repo from jcenter to mavenCentral

- packages/quick_actions/quick_actions/CHANGELOG.md
- packages/quick_actions/quick_actions/android/build.gradle
- packages/quick_actions/quick_actions/example/android/build.gradle
- packages/quick_actions/quick_actions/pubspec.yaml
quick_actions part of https://github.com/flutter/flutter/issues/82847
> [quick_actions] Migrate maven repo from jcenter to mavenCentral

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/example/android/build.gradle
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/android/build.gradle
- packages/in_app_purchase/in_app_purchase_android/example/android/build.gradle
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
in_app_purchase part of https://github.com/flutter/flutter/issues/82847
> [in_app_purchase] Migrate maven repo from jcenter to mavenCentral

- script/tool/CHANGELOG.md
- script/tool/lib/src/version_check_command.dart
- script/tool/pubspec.yaml
- script/tool/test/version_check_test.dart
If a new version is lower than the current checked-in version, and the
transition from the new version to the old version is valid (indicating
that it could have been the previous version), allow the change.
This prevents the version check from failing when reverting a PR.
This is not fool-proof (e.g., it would allow a revert of an
already-published PR); if we have issues in practice we can further
restrict the check (by checking that the new version is the current pub
version, for instance). …
> Allow reverts when checking versions

- packages/camera/camera/example/android/build.gradle
- packages/camera/camera/example/pubspec.yaml
- packages/image_picker/image_picker/android/build.gradle
- packages/image_picker/image_picker/example/pubspec.yaml
Now that video_player includes this workaround at the plugin level, it's no longer necessary in the examples that use it.
> Remove exoplayer workaround from everything but video_player

- script/tool/lib/src/analyze_command.dart
This PR switches the CI to calling `flutter pub get` for both Dart and Flutter packages (previously, we'd call `dart pub get` for non-Flutter packages). This normalizes the output in CIs a bit - `dart pub get` lists all the packages and versions that were resolved, while `flutter pub get` just emits one line of stdout. See https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8846322703236505168/+/u/analyze_flutter_plugins/stdout for an example of the existing CI output.
This work is generally in service to https://github.com/dart-lang/sdk/issues/45873 (which itself is part of https://github.com/dart-lang/sdk/issues/46075).
- some work towards https://github.com/dart-lang/sdk/issues/45873
*If …
> [scripts/tool] use 'flutter pub get' for both dart and flutter packages

- packages/path_provider/path_provider/README.md
Since the plugin is already supposed to support Windows, I think it should mention it as well.
> Added Windows to the description

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/example/ios/Podfile
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerTests/GoogleMapsTests.m
- packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerTests/Info.plist
- packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerUITests/GoogleMapsUITests.m
- packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerUITests/Info.plist
Add `RunnerTests` XCTest and `RunnerUITest` XCUITest iOS targets to example app.
- Add unit test that creates the plugin and asserts it's not nil, proving linking is set up correctly.
- Add UI test that navigates around, checks for a maps platform view, and handles the location permission popup.
google_maps_flutter part of https://github.com/flutter/flutter/issues/83357
Passing presubmit tests: https://cirrus-ci.com/task/6672684797919232
```
Test Case '-[GoogleMapsUITests testUserInterface]' passed (11.633 seconds).
Test Suite 'GoogleMapsUITests' passed at 2021-05-25 16:00:22.642.
Executed 1 test, with 0 failures (0 unexpected) in 11.633 (11.634) seconds
Test Suite 'RunnerUITests.xctest' passed at 2021-05-25 16:00:22.644.
Executed 1 test, with 0 failures (0 unexpected) in 11.633 (11.636) …
```
> [google_maps_flutter] Add iOS unit and UI tests

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAObjectTranslator.m
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_product_wrapper.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_product_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_product_test.dart
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_test_stub_objects.dart
Reverts changes made in PR #3897 as per discussion with @stuartmorgan (see [here](https://github.com/flutter/plugins/pull/3897#issuecomment-847978648)).
- PR #3897 …
> [in_app_purchase] Revert changes from PR 3897

- script/tool/lib/src/analyze_command.dart
- script/tool/test/analyze_command_test.dart
This PR speeds up the `analyze` command for the plugins tool. We were running pub get twice for all 42 example directories (flutter pub get automatically runs pub get for an example/ child directory when running pub get for the parent). The analyze command was spending 60% of it's time running flutter pub get; after this change the overall command should be about 25% faster.
- work towards https://github.com/flutter/flutter/issues/83261 (and https://github.com/dart-lang/sdk/issues/45873)
- [-] I updated pubspec.yaml with an appropriate new version according to the [pub versioning …
> [script/tool] speed up the pub get portion of the analyze command

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/README.md
- packages/video_player/video_player/pubspec.yaml
Remove `www` from video sample url because of issue with ssl certificate.
Question on Stack Overflow https://stackoverflow.com/q/67675317/1891712
[Discord]: …
> [video_player] Update README.md

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/android/build.gradle
- packages/image_picker/image_picker/example/android/build.gradle
- packages/image_picker/image_picker/pubspec.yaml
Remove `exoplayer` workaround introduced in #977.  See also https://github.com/google/ExoPlayer/issues/5246.
Remove trailing whitespace from CHANGELOG and pubspec.
image_picker part of https://github.com/flutter/flutter/issues/82847
> [image_picker] Migrate maven repo from jcenter to mavenCentral

- analysis_options.yaml
- packages/espresso/example/pubspec.yaml
- packages/path_provider/path_provider/example/pubspec.yaml
- packages/path_provider/path_provider/pubspec.yaml
- packages/path_provider/path_provider_linux/example/pubspec.yaml
- packages/path_provider/path_provider_macos/example/pubspec.yaml
- packages/path_provider/path_provider_windows/example/pubspec.yaml
Enables the dependencies sorting link in analysis_options.yaml (which
applies only to the directories that have migrated off the legacy
options already), and fixes the resulting new analysis issues.
Part of flutter/flutter#82913
[Discord]: …
> Enable pubspec dependency sorting lint

- script/tool/lib/src/test_command.dart
- script/tool/test/test_command_test.dart
Because I'm new to dart and flutter, I never had a `pub` binary installed. Running `dart run script/tool/lib/src/main.dart test` crashed on the `plugin_platform_interface` tests because that package doesn't qualify as a `flutter` package. The log message at the point of failure hinted at the cause:
```
RUNNING plugin_platform_interface tests...
Running command: "pub get" in /Users/aj/dev/flutter_plugins/packages/plugin_platform_interface
Unhandled exception:
ProcessException: No such file or directory
Command: pub get
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      ProcessRunner.runAndStream (package:flutter_plugin_tools/src/common.dart:540:49)
#3      TestCommand.run …
```
> [script/tool] Use 'dart pub' instead of deprecated 'pub'

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/example/ios/Podfile
- packages/url_launcher/url_launcher/example/ios/Runner.xcodeproj/project.pbxproj
- packages/url_launcher/url_launcher/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- packages/url_launcher/url_launcher/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/url_launcher/url_launcher/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- packages/url_launcher/url_launcher/example/ios/RunnerTests/Info.plist
- packages/url_launcher/url_launcher/example/ios/RunnerTests/URLLauncherTests.m
- packages/url_launcher/url_launcher/example/ios/RunnerUITests/Info.plist
- packages/url_launcher/url_launcher/example/ios/RunnerUITests/URLLauncherUITests.m
- packages/url_launcher/url_launcher/example/linux/flutter/generated_plugin_registrant.cc
Add `RunnerTests` XCTest and `RunnerUITest` XCUITest iOS targets to example app.
- Add unit test that creates the plugin and asserts it's not nil, proving linking is set up correctly.
- Add UI test that launches different example web views.
url_launcher part of https://github.com/flutter/flutter/issues/83357
> [url_launcher] Add iOS unit and UI tests

- .cirrus.yml
- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_controller.dart
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/example/lib/main.dart
- packages/url_launcher/url_launcher/pubspec.yaml
- packages/url_launcher/url_launcher_web/CHANGELOG.md
- packages/url_launcher/url_launcher_web/lib/src/link.dart
- packages/url_launcher/url_launcher_web/pubspec.yaml
- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/example/README.md
- packages/video_player/video_player_web/example/integration_test/video_player_web_test.dart
- packages/video_player/video_player_web/example/lib/main.dart
- packages/video_player/video_player_web/example/pubspec.yaml
- packages/video_player/video_player_web/example/run_test.sh
- packages/video_player/video_player_web/example/test_driver/integration_test.dart
- packages/video_player/video_player_web/example/web/index.html
- packages/video_player/video_player_web/lib/video_player_web.dart
- packages/video_player/video_player_web/pubspec.yaml
- packages/video_player/video_player_web/test/README.md
- packages/video_player/video_player_web/test/tests_exist_elsewhere_test.dart
Similarly to https://github.com/flutter/packages/pull/364, this PR adapts the HtmlElementView-based web plugins to the new incoming changes in master:
* Ensure HtmlElementView root is 100% width/height of the space allocated by the framework.
(Part of https://github.com/flutter/flutter/issues/80524)
And opportunistically fixes some issues "while we're there":
* URL Launcher:
* Add a `Link` widget to the example app (there used to be an issue, can't find it)
* Video Player:
* Migrate tests so they run in CI (with integration_test, Part of: https://github.com/flutter/flutter/issues/81982)
* ~~Google Maps:~~
* ~~Endorse web plugin~~: _Removed because of problems in the google_maps_flutter integration tests, that need some extra code to work on the Web._
If you need help, consider asking for …
> [multiple_web] Adapt web PlatformView widgets to work slotted.

- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/lib/video_player_web.dart
- packages/video_player/video_player_web/pubspec.yaml
Set autoplay to false during web video initialization to address issues of video not playing in Chrome and Safari on iOS. Tested on both iOS Chrome and Safari and the fix appears to work.
Part of: https://github.com/flutter/flutter/issues/47030
[C++, …
> [video_player_web] fix: set autoplay to false during initialization

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
- packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerDelegateTest.java
- packages/image_picker/image_picker/pubspec.yaml
It was [pointed out](https://github.com/flutter/plugins/pull/3956#discussion_r643121136) that since the image picker plugin relies on the `ACTION_VIDEO_CAPTURE` and `ACTION_IMAGE_CAPTURE` intents for accessing the camera, it is [not required](https://developer.android.com/training/permissions/evaluating#take-photo) to request the camera permission.
This PR removes the request for camera permissions.
The permission requests for reading and writing external storage were already removed, and since after that the camera permission was the only remaining permission being requested by the plugin, I took out everything related to permissions as well. 
**Relevant issue:**
- flutter/flutter#83789
> [image_picker] Removed redundant request for camera permission

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- script/tool/README.md
When working on the plugins I encountered some very minor issues in the documentation.
A wrongly formatted url
A missing dot:
A broken link in the PR template: the plugin_tool format links to https://github.com/flutter/plugins/script/tool/README.md#format-code …
> Some small documentation fixes

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/pubspec.yaml
cc @Hixie @stuartmorgan I explained [here](https://github.com/flutter/plugins/pull/3954#issuecomment-852856099) why ~a breaking change was handled inproperly and this is why~ we need to specify the dependency that is at least `2.0.3`.
Before that version, the method head of `pushRouteNameToFramework` was different, which means that `^2.0.0` for the platform interface is a lie - any version before `2.0.3` is incompatible. …
> [url_launcher] Fix breaking change version conflict

- packages/quick_actions/quick_actions/example/ios/RunnerUITests/RunnerUITests.m
This PR will hopefully fixes the flaky `testQuickActionWithFreshStart` iOS UI test (see flutter/flutter#83483).
Since I wasn't able to reproduce the issue on my local environment it is difficult to determine if this really resolves the problem. However the test was launching and terminating the app under test and I think this was interfering to the point where the app is terminated right before the test to check for the "action-two" screen shows up.
I have restructured the test script to ensure the app under test is terminated after each test so the environment should start in a fresh state for each of the tests.
Added benefit is that is makes the UI Test logic easier to read and understand and less prone to mistakes when additional tests are added.
- flutter/flutter#83483
*If you had to …
> [quick_actions] Optimised UI test to prevent flaky CI failures

- packages/path_provider/path_provider/example/linux/flutter/generated_plugin_registrant.cc
- packages/path_provider/path_provider/example/linux/flutter/generated_plugin_registrant.h
- packages/path_provider/path_provider/example/windows/flutter/generated_plugin_registrant.cc
- packages/path_provider/path_provider/example/windows/flutter/generated_plugin_registrant.h
- packages/path_provider/path_provider_linux/example/linux/flutter/generated_plugin_registrant.cc
- packages/path_provider/path_provider_linux/example/linux/flutter/generated_plugin_registrant.h
- packages/path_provider/path_provider_windows/example/windows/flutter/generated_plugin_registrant.cc
- packages/path_provider/path_provider_windows/example/windows/flutter/generated_plugin_registrant.h
- packages/shared_preferences/shared_preferences/example/linux/flutter/generated_plugin_registrant.cc
- packages/shared_preferences/shared_preferences/example/linux/flutter/generated_plugin_registrant.h
- packages/shared_preferences/shared_preferences/example/windows/flutter/generated_plugin_registrant.cc
- packages/shared_preferences/shared_preferences/example/windows/flutter/generated_plugin_registrant.h
- packages/shared_preferences/shared_preferences_linux/example/linux/flutter/generated_plugin_registrant.cc
- packages/shared_preferences/shared_preferences_linux/example/linux/flutter/generated_plugin_registrant.h
- packages/shared_preferences/shared_preferences_windows/example/windows/flutter/generated_plugin_registrant.cc
- packages/shared_preferences/shared_preferences_windows/example/windows/flutter/generated_plugin_registrant.h
- packages/url_launcher/url_launcher/example/linux/flutter/generated_plugin_registrant.cc
- packages/url_launcher/url_launcher/example/linux/flutter/generated_plugin_registrant.h
- packages/url_launcher/url_launcher/example/windows/flutter/generated_plugin_registrant.cc
- packages/url_launcher/url_launcher/example/windows/flutter/generated_plugin_registrant.h
- packages/url_launcher/url_launcher_linux/example/linux/flutter/generated_plugin_registrant.cc
- packages/url_launcher/url_launcher_linux/example/linux/flutter/generated_plugin_registrant.h
- packages/url_launcher/url_launcher_windows/example/windows/flutter/generated_plugin_registrant.cc
- packages/url_launcher/url_launcher_windows/example/windows/flutter/generated_plugin_registrant.h
The Flutter-generated C++ plugin registrants use a format that doesn't
match what this repo's clang-format settings wanted, so every time they
were regenerated it created a local diff that couldn't be checked in
without failing the CI format check.
The templates are now generated with a directive to disable
clang-format; this checks in that version of all of the files to avoid
the local edit problem in the future. …
> Check in regenerated C++ example registrants

- packages/shared_preferences/shared_preferences/CHANGELOG.md
- packages/shared_preferences/shared_preferences/example/ios/Podfile
- packages/shared_preferences/shared_preferences/example/ios/Runner.xcodeproj/project.pbxproj
- packages/shared_preferences/shared_preferences/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/shared_preferences/shared_preferences/example/ios/Runner.xcworkspace/contents.xcworkspacedata
- packages/shared_preferences/shared_preferences/example/ios/RunnerTests/Info.plist
- packages/shared_preferences/shared_preferences/example/ios/RunnerTests/SharedPreferencesTests.m
Add `RunnerTests` XCTest iOS target to example app that creates the plugin and asserts it's not nil, proving linking is set up correctly.
shared_preferences part of https://github.com/flutter/flutter/issues/83357
https://cirrus-ci.com/task/5671640303403008?logs=xctest#L1544
```
Test Suite 'SharedPreferencesTests' passed at 2021-06-03 18:31:54.382.
Executed 1 test, with 0 failures (0 unexpected) in 0.003 (0.004) seconds
Test Suite 'RunnerTests.xctest' passed at 2021-06-03 18:31:54.383.
Executed 1 test, with 0 failures (0 unexpected) in 0.003 (0.007) seconds
```
> [shared_preferences] Add iOS unit tests

- script/tool/test/analyze_command_test.dart
- script/tool/test/build_examples_command_test.dart
- script/tool/test/common_test.dart
- script/tool/test/create_all_plugins_app_command_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/firebase_test_lab_test.dart
- script/tool/test/java_test_command_test.dart
- script/tool/test/lint_podspecs_command_test.dart
- script/tool/test/list_command_test.dart
- script/tool/test/publish_check_command_test.dart
- script/tool/test/publish_plugin_command_test.dart
- script/tool/test/pubspec_check_command_test.dart
- script/tool/test/test_command_test.dart
- script/tool/test/util.dart
- script/tool/test/version_check_test.dart
- script/tool/test/xctest_command_test.dart
Eliminates the global test filesystem and global test packages directory, in favor of local versions. This guarantees that each test runs with a clean filesystem state, rather than relying on cleanup. It also simplifies understanding the tests, since everything is done via params and return values instead of needing to know about the magic global variables and which methods mutate them.
- [x ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format]) …
> [flutter_plugin_tools] Remove global state from tests

- script/tool/CHANGELOG.md
- script/tool/README.md
- script/tool/lib/src/xctest_command.dart
- script/tool/pubspec.yaml
- script/tool/test/xctest_command_test.dart
Removes the `xctest` flag `--skip`, at it is redundant with the general `--exclude` flag.
Part of https://github.com/flutter/flutter/issues/83413 …
> [flutter_plugin_tools] Remove xctest's --skip

- script/tool/lib/src/xctest_command.dart
- script/tool/test/mocks.dart
- script/tool/test/xctest_command_test.dart
Migrates the `xctest` command and its test. Includes tightening down the
use of `dynamic` when extracting data from JSON, since `dynamic`
eliminates much of the safety of NNBD.
Part of https://github.com/flutter/flutter/issues/81912
[Discord]: …
> [flutter_plugin_tools] Migrate xctest command to NNBD

- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_methodchannel_apis_test.dart
Using `Future<T>.value()` with a non-nullable `T` is a guaranteed runtime error, which is why I'm [adding an analysis warning](https://dart-review.googlesource.com/c/sdk/+/202622) for it.
This repo currently has one such usage in a test (it looks like the offending constructor never gets called??).
Related to https://github.com/flutter/flutter/issues/84137 …
> [in_app_purchase] Avoid nullable Future.value

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/example/ios/RunnerTests/ImageUtilTests.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m
- packages/image_picker/image_picker/pubspec.yaml
This PR fixes a rotation problem where when the camera is chosen as a source and additional parameters are added. This change is related to [#3873](https://github.com/flutter/plugins/pull/3873). `isMetadataAvailable` parameter is used to handle the rotation problem for limited access to the photo library and it should be `YES` for all other occasions.
Related issues:
- Fixes [flutter/flutter#74014](https://github.com/flutter/flutter/issues/74014) …
> [image_picker] Fix rotation when camera is a source

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/README.md
- packages/video_player/video_player/pubspec.yaml
video_player was promoted to 1.0 a while ago, so should no longer have language in the README suggesting that it's in an unfinished/beta state. …
> [video_player] Remove pre-stable warning from README

- .github/PULL_REQUEST_TEMPLATE.md
The plugins repo contributor's guide mostly defers to the main one, which it links to, but includes repository-specific information.
Also simplifies the section on style guides, while making it more comprehensive, by linking to the style section of the contributor guide.
> Link to this repo's guide in the PR template

- script/tool/lib/src/common.dart
- script/tool/lib/src/publish_check_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/lib/src/version_check_command.dart
- script/tool/test/common_test.dart
- script/tool/test/publish_check_command_test.dart
- script/tool/test/version_check_test.dart
Migrates publish-check and version-check commands to NNBD.
Reworks the version-check flow so that it's more consistent with the other commands: instead of immediately exiting on failure, it checks all plugins, gathers failures, and summarizes all failures at the end. This ensures that we don't have failures in one package temporarily masked by failures in another, so PRs don't need to go through as many check cycles.
Part of https://github.com/flutter/flutter/issues/81912 …
> [flutter_plugin_tools] Migrate publish and version checks to NNBD

- script/tool/CHANGELOG.md
- script/tool/bin/flutter_plugin_tools.dart
- script/tool/lib/src/main.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/publish_plugin_command_test.dart
Migrates the publish command to NNBD.
This is the last command, so the top-level files are migrated as well, allowing the tool to run in strong mode.
Fixes https://github.com/flutter/flutter/issues/81912 …
> [flutter_plugin_tools] Complete migration to NNBD

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/InAppPurchasePluginTests.m
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/Stubs.h
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/Stubs.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAPaymentQueueHandler.h
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAPaymentQueueHandler.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/InAppPurchasePlugin.m
- packages/in_app_purchase/in_app_purchase_ios/lib/src/in_app_purchase_ios_platform.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/test/fakes/fake_ios_platform.dart
- packages/in_app_purchase/in_app_purchase_ios/test/in_app_purchase_ios_platform_test.dart
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_methodchannel_apis_test.dart
At the moment `[_paymentQueueHandler startObservingPaymentQueue];` is called during the initialisation of the plugin. This means potentially iOS can directly start sending transaction updates. On the Dart side the _TransactionObserver is made with a broadcast stream, which means that any transaction received before anyone is listening will be lost.
I removed `[_paymentQueueHandler startObservingPaymentQueue];` from the plugin initialisation and added 2 method channel methods: `startObservingTransactionQueue` and `stopObservingTransactionQueue`. `startObservingTransactionQueue` is called when the first listener subscribes to the `purchaseStream` and `stopObservingTransactionQueue` when there are no longer any listeners subscribed.
This PR fixes flutter/flutter#83018 and the solution is …
> [in_app_purchase] Only register transactionObservers when someone is listening to purchaseUpdates

- packages/integration_test/README.md
`integration_test` has moved into the Flutter SDK at `flutter/packages/integration_test`.  However, the "old instructions" `iOS Device Testing` instructions are wrong, which is confusing users who find the README through a Google search.
Update the README to match the instructions in https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing.  This is not for `pub` publication so won't update https://pub.dev/packages/integration_test instructions.
https://github.com/flutter/flutter/issues/72876
> [integration_test] Update README installation instructions

- script/tool/lib/src/build_examples_command.dart
- script/tool/lib/src/common/core.dart
- script/tool/lib/src/common/plugin_utils.dart
- script/tool/lib/src/drive_examples_command.dart
- script/tool/lib/src/xctest_command.dart
- script/tool/test/analyze_command_test.dart
- script/tool/test/build_examples_command_test.dart
- script/tool/test/common/plugin_command_test.dart
- script/tool/test/common/plugin_utils_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/firebase_test_lab_test.dart
- script/tool/test/java_test_command_test.dart
- script/tool/test/lint_podspecs_command_test.dart
- script/tool/test/list_command_test.dart
- script/tool/test/publish_check_command_test.dart
- script/tool/test/publish_plugin_command_test.dart
- script/tool/test/pubspec_check_command_test.dart
- script/tool/test/test_command_test.dart
- script/tool/test/util.dart
- script/tool/test/version_check_test.dart
- script/tool/test/xctest_command_test.dart
createFakePlugin is used extensively in tests, but has become more and more complex over time. This substantially refactors it and related test utilities:
- Extracts a createFakePackage for the cases where we want non-plugin packages (allowing the removal of isFlutter from createFakePlugin).
- Makes most things created automatically instead of being opt-in, so that tests are operating on things that look more like actual packages/plugins unless they specifically override that behavior:
- Version is added by default.
- An example/ directory is added by default.
- A CHANGELOG is added (it can be deleted manually if we ever need to test for that).
- Combines the two different ways of defining the example format.
- Replaces the list of platform boolean with a map of platform name to details. …
> [flutter_plugin_tool] Refactor createFakePlugin

- script/tool/test/analyze_command_test.dart
- script/tool/test/build_examples_command_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/firebase_test_lab_test.dart
- script/tool/test/java_test_command_test.dart
- script/tool/test/lint_podspecs_command_test.dart
- script/tool/test/test_command_test.dart
- script/tool/test/util.dart
- script/tool/test/xctest_command_test.dart
Rather than taking a list of list of path elements, just accept a list
of Posix-style paths. In practice, the API was already being partially
used that way. …
> [flutter_plugin_tools] Simplify extraFiles in test utils

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/core.dart
- script/tool/lib/src/common/package_looping_command.dart
- script/tool/lib/src/common/plugin_command.dart
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/lib/src/xctest_command.dart
- script/tool/test/common/package_looping_command_test.dart
- script/tool/test/pubspec_check_command_test.dart
- script/tool/test/xctest_command_test.dart
Most of our commands are generally of the form:
```
for (each plugin as defined by the tool flags)
check some things for success or failure
print a summary all of the failing things
exit non-zero if anything failed
```
Currently all that logic not consistent, having been at various points copied and pasted around, modified, in some cases rewritten. There's unnecessary boilerplate in each new command, and there's unnecessary variation that makes it harder both to maintain the tool, and to consume the test output:
- There's no standard format for separating each plugin's run to search within a log
- There's no standard format for the summary at the end
- In some cases commands have been written to ToolExit on failure, which means we don't actually get the rest of the runs
This makes a new …
> [flutter_plugin_tools] Add a new base command for looping over packages

- .github/PULL_REQUEST_TEMPLATE.md
People commonly think this doesn't apply to their PR when it does; this adds a link to a new explanation of when and why it's needed on the wiki.
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README …
> Add link to the version update entry

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java
- packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/MethodCallHandlerImpl.java
- packages/in_app_purchase/in_app_purchase_android/android/src/test/java/io/flutter/plugins/inapppurchase/MethodCallHandlerTest.java
- packages/in_app_purchase/in_app_purchase_android/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform_addition.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/billing_client_wrapper_test.dart
- packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_addition_test.dart
This PR adds a launchPriceChangeConfirmationFlow function in the BillingClientWrapper and the platform additions.
In the android example of the in_app_purchase I replaced the checkmark for subscriptions with an arrow up, this now checks for price changes. I could not get a real price change showing in the test environment.
Fixes flutter/flutter#85038 …
> [in_app_purchase] billingClient launchPriceChangeConfirmationFlow

- .github/workflows/pull_request_label.yml
Now that auto-releasing is enabled, the manual process this label was used for is no longer necessary.
> Disable the "needs publishing" auto-labeler

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/ios/Classes/FlutterWebView.m
- packages/webview_flutter/pubspec.yaml
On master the project is auto-updated to iOS 9, causing CI failures on
this deprecation warning (due to -Werrror), but still needs to support
iOS 8 for current stable.
Also adds an iOS 9-specific codepath to future-proofing when iOS 8
is dropped.
Fixes the tree.
Fixes flutter/flutter#76370
[pub …
> [webview_flutter] Suppress iOS 9 deprecation warnings

- script/tool/CHANGELOG.md
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/publish_plugin_command_test.dart
This PR removes a TODO where we used to check if a release should happen against git tags, instead, we check against pub. 
Also, when auto-publish and the package is manually released, the CI will continue to fail without this change. 
Fixes https://github.com/flutter/flutter/issues/81047 …
> [flutter_plugin_tools] `publish-plugin` check against pub to determine if a release should happen

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/lib/image_picker.dart
- packages/image_picker/image_picker/pubspec.yaml
Updated `pickImage` and `pickVideo` docs to expose the possible errors that can be thrown as a `PlatformException`. The reason I want the docs to be updated with this information is due to developers not being aware of the errors that can be thrown when reading the plugin documentation.
Continuation of #2662 
- [] I listed at least one issue that this PR fixes in the description above.
- [] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
If you need help, consider asking for advice on the #hackers-new channel on …
> [image_picker] Updated pickImage and pickVideo docs to expose the possible errors that can be thrown

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/example/ios/RunnerUITests/URLLauncherUITests.m
On iOS 15 the `ShareButton` button identifier has been renamed to `MoreOptionsButton`. Switch the check to the common `Share` label that works on both versions.
Fixes https://github.com/flutter/flutter/issues/85161
> [url_launcher] Fix test button check for iOS 15

- .cirrus.yml
The image should already have cocoapods installed.
> Don't install cocoapods during CI runs

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/plugin_command.dart
- script/tool/lib/src/lint_podspecs_command.dart
- script/tool/test/lint_podspecs_command_test.dart
Switches `podspec` to the new base command that handles the boilerplate of looping over target packages.
Includes test improvements:
- Adds failure tests; previously no failure cases were covered.
- Captures output using the standard mechanism instead of using a custom
`_print`, simplifying the command code.
Also removes `--skip`, which is redundant with `--exclude`. …
> [flutter_plugin_tools] Migrate podspec to new base command

- script/tool/CHANGELOG.md
- script/tool/pubspec.yaml
Release 0.3.0 so all the new feature are available for other repos. …
> [flutter_plugin_tools] release 0.3.0

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/example/ios/Podfile
- packages/in_app_purchase/in_app_purchase_ios/example/ios/Runner.xcodeproj/project.pbxproj
- packages/in_app_purchase/in_app_purchase_ios/example/ios/Runner/Configuration.storekit
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/FIAPPaymentQueueDeleteTests.m
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/InAppPurchasePluginTests.m
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/Stubs.h
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/Stubs.m
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/TranslatorTests.m
- packages/in_app_purchase/in_app_purchase_ios/example/lib/example_payment_queue_delegate.dart
- packages/in_app_purchase/in_app_purchase_ios/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAObjectTranslator.h
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAObjectTranslator.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAPPaymentQueueDelegate.h
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAPPaymentQueueDelegate.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAPaymentQueueHandler.h
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAPaymentQueueHandler.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/InAppPurchasePlugin.m
- packages/in_app_purchase/in_app_purchase_ios/lib/src/channel.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/in_app_purchase_ios_platform_addition.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_payment_queue_delegate_wrapper.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_storefront_wrapper.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_storefront_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/store_kit_wrappers.dart
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_methodchannel_apis_test.dart
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_payment_queue_delegate_api_test.dart
Enables developers to register a custom implementation of the `SKPaymentQueueDelegateWrapper` class and control how changes regarding subscriptions should be processed. 
Fixes flutter/flutter#85129 …
> [in_app_purchase] Add support for SKPaymentQueueDelegate and showPriceConsentIfNeeded

- script/tool/lib/src/java_test_command.dart
- script/tool/test/java_test_command_test.dart
Switches `java-test` to the new base command that handles the boilerplate of looping over target packages.
Includes test improvements:
- Adds failure tests; previously no failure cases were covered.
- Captures output so test output isn't spammed with command output. …
> [flutter_plugin_tools] Migrate java-test to new base command

- .cirrus.yml
It is much easier to use the results UI for Cirrus tasks when each major
portion of the script is its own script section, since that causes it to
be displayed separately (with its own timing, logs, etc.)
This has already been done for many tasks; this applies it to some that
were missing it.
[pub …
> Split some Cirrus script steps

- script/tool/lib/src/common/core.dart
- script/tool/lib/src/common/package_looping_command.dart
- script/tool/lib/src/common/plugin_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/lib/src/version_check_command.dart
- script/tool/test/version_check_command_test.dart
Combines the two different aspects of version-checking into a single looping structure based on plugins, using the new base command, rather than one operating on plugins as controlled by the usual flags and the other operating on a git list of changed files.
Also simplifies the determination of the new version by simply checking the file, rather than querying git for the HEAD state of the file. Tests setup is simplified since we no longer need to set up nearly as much fake `git` output.
Minor changes to base commands:
- Move indentation up to PackageLoopingCommand so that it is consistent across commands
- Add a new post-loop command for any cleanup, which is needed by version-check
- Change the way the GitDir instance is managed by the base PluginCommand, so that it's always cached even …
> [flutter_plugin_tools] Restructure version-check

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/example/lib/main.dart
- packages/image_picker/image_picker/pubspec.yaml
This PR updates the example app to support the multi-image feature.
Related issues:
- [flutter/flutter#16054](https://github.com/flutter/flutter/issues/16054) …
> [image_picker]Update example app

- packages/google_sign_in/google_sign_in/android/build.gradle
- packages/google_sign_in/google_sign_in/android/src/test/java/io/flutter/plugins/googlesignin/GoogleSignInTest.java
- packages/local_auth/android/build.gradle
- packages/local_auth/android/src/test/java/io/flutter/plugins/localauth/LocalAuthTest.java
- packages/shared_preferences/shared_preferences/android/build.gradle
- packages/shared_preferences/shared_preferences/android/src/test/java/io/flutter/plugins/sharedpreferences/SharedPreferencesTest.java
- packages/video_player/video_player/android/build.gradle
- packages/video_player/video_player/android/src/test/java/io/flutter/plugins/videoplayer/VideoPlayerTest.java
- packages/webview_flutter/android/build.gradle
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java
- packages/webview_flutter/android/src/test/java/io/flutter/plugins/webviewflutter/WebViewTest.java
https://github.com/flutter/flutter/issues/83358
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format- …
> Add Basic Junit Tests to some plugins

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/InAppPurchasePluginTests.m
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/Stubs.h
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/Stubs.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAPReceiptManager.m
- packages/in_app_purchase/in_app_purchase_ios/lib/src/in_app_purchase_ios_platform_addition.dart
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_methodchannel_apis_test.dart
Missing App Store receipt can happen for different scenarios, thus shouldn't trigger an exception.
Reboot of PR #2862
https://github.com/flutter/flutter/issues/43957
- [ x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ x ] All existing and new tests are passing.
- [ x ] I updated/added relevant documentation (doc comments with `///`).
- [ x ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ x ] I read and followed the …
> [in_app_purchase] Fix app exceptions caused by missing App Store receipt

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
- packages/image_picker/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerDelegateTest.java
- packages/image_picker/image_picker/pubspec.yaml
Currently, the image picker plugin throws an IOException when trying to pick an image, if the cache directory does not exist. 
This PR makes it so the cache directory is created in case it does not exist.
Relevant issue:
- flutter/flutter#84251
> [image_picker] Fixed IOException when cache directory is removed

- script/tool/lib/src/license_check_command.dart
- script/tool/test/license_check_command_test.dart
Eliminates the custom printer in the command, and updates the tests to use the repo-standard `runCapturingPrint`.
This avoids unnecessary divergence of test styles, and simplifies the command itself. It was only written the other way in the first place because I wasn't aware of `runCapturingPrint`. …
> [flutter_plugin_tools] Move license-check tests to runCapturingPrint

- .cirrus.yml
- script/tool/CHANGELOG.md
- script/tool/lib/src/build_examples_command.dart
- script/tool/test/build_examples_command_test.dart
Switches build-examples to the new base command that handles the boilerplate of looping over target packages.
While modifying the command, also does some minor cleanup:
- Extracts a helper to reduce duplicated details of calling `flutter build`
- Switches the flag for iOS to `--ios` rather than `--ipa` since `ios` is what is actually passed to the build command
- iOS no longer defaults to on, so that it behaves like all the other platform flags
- Passing no platform flags is now an error rather than a silent pass, to ensure that we never accidentally have CI doing a no-op run without noticing.
- Rewords the logging slightly for the versions where the label for what is being built is a platform, not an artifact (which is now everything but Android). …
> [flutter_plugin_tools] Migrate build-examples to new base command

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/example/ios/Podfile
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
Workaround https://github.com/flutter/flutter/issues/85713 to unblock the tree.
Exclude `arm64` for all pods, as well as the app itself.
> Exclude arm64 simulators from google_maps_flutter example project

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/example/ios/Podfile
- packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj
Workaround https://github.com/flutter/flutter/issues/85713 to unblock the tree.
Exclude `arm64` for all pods, as well as the app itself.
See also https://github.com/flutter/plugins/pull/4127.
> Exclude arm64 simulators from google_sign_in example project

- script/tool/CHANGELOG.md
- script/tool/lib/src/analyze_command.dart
- script/tool/lib/src/build_examples_command.dart
- script/tool/lib/src/common/core.dart
- script/tool/lib/src/common/package_looping_command.dart
- script/tool/lib/src/drive_examples_command.dart
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/lib/src/java_test_command.dart
- script/tool/lib/src/lint_podspecs_command.dart
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/lib/src/version_check_command.dart
- script/tool/lib/src/xctest_command.dart
- script/tool/test/common/package_looping_command_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/firebase_test_lab_command_test.dart
- script/tool/test/java_test_command_test.dart
- script/tool/test/lint_podspecs_command_test.dart
- script/tool/test/xctest_command_test.dart
Add a summary to the end of successful runs for everything using the new looping base command, similar to what we do for summarizing failures. This will make it easy to manually check results for PRs that we know should be changing the set of run packages (adding a new package, adding a new test type to a package, adding a new test type to the tool), as well as spot-checking when we see unexpected results (e.g., looking back and why a PR didn't fail CI when we discover that it should have).
To support better surfacing skips, this restructures the return value of `runForPackage` to have "skip" as one of the options. As a result of it being a return value, packages that used `printSkip` to indicate that *parts* of the command were being skipped have been changed to no longer do that.
Fixes …
> [flutter_plugin_tools] Add a summary for successful runs

- script/tool/CHANGELOG.md
- script/tool/lib/src/analyze_command.dart
- script/tool/lib/src/drive_examples_command.dart
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/lib/src/lint_podspecs_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/lib/src/xctest_command.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/firebase_test_lab_command_test.dart
- script/tool/test/lint_podspecs_command_test.dart
- script/tool/test/util.dart
The intent of package-looping commands is that we always want to run them for all the targeted packages, accumulating failures, and then report them all at the end, so we don't end up with the problem of only finding errors one at a time. However, some of them were using `exitOnError: true` for the underlying commands, causing the first error to be fatal to the test.
This PR:
- Removes all use of `exitOnError: true` from the package-looping commands. (It's still used in `format`, but fixing that is a larger issue, and less important due to the way `format` is currently structured.)
- Fixes the mock process runner used in our tests to correctly simulate `exitOrError: true`; the fact that it didn't was hiding this problem in test (e.g., `drive-examples` had a test that asserted that all …
> [flutter_plugin_tools] Remove most exitOnError:true usage

- script/tool/lib/src/common/package_looping_command.dart
- script/tool/lib/src/publish_check_command.dart
- script/tool/test/common/package_looping_command_test.dart
- script/tool/test/publish_check_command_test.dart
To support this command's `--machine` flag, which moves all normal output into a field in a JSON struct, adds a way of capturing output and providing it to the command subclass on completion.
[the …
> [flutter_plugin_tools] Migrate publish-check to the new base command

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_payment_queue_delegate_api_test.dart
Makes sure that `SKError.fromJson()` gets the correct data type as argument.
*List which issues are fixed by this PR. You must list at least one issue.* 
https://github.com/flutter/flutter/issues/85534
> [in_app_purchase] Initialize SKError with correct data type

- script/tool/lib/src/analyze_command.dart
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/lib/src/java_test_command.dart
- script/tool/lib/src/version_check_command.dart
- script/tool/test/analyze_command_test.dart
- script/tool/test/build_examples_command_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/firebase_test_lab_command_test.dart
- script/tool/test/java_test_command_test.dart
- script/tool/test/lint_podspecs_command_test.dart
- script/tool/test/mocks.dart
- script/tool/test/publish_check_command_test.dart
- script/tool/test/test_command_test.dart
- script/tool/test/xctest_command_test.dart
Many commands had insufficient failure testing. This adds new tests that
ensure that for every Process call, at least one test fails if a failure
from that process were ignored (with the exception of calls in the
`publish` command, which has a custom process mocking system, so was out
of scope here; it already has more coverage than most tests did though.)
For a few existing failure tests, adds output checks to ensure that they
are testing for the *right* failures.
Other changes:
- Adds convenience constructors to MockProcess for the common cases of a
mock process that just exits with a 0 or 1 status, to reduce test
verbosity.
- Fixes a few bugs that were found by the new tests.
- Minor test cleanup, especially cases where a mock process was being
set up just to make all calls succeed, …
> [flutter_plugin_tool] Add more failure test coverage

- script/tool/CHANGELOG.md
- script/tool/README.md
- script/tool/lib/src/common/plugin_command.dart
- script/tool/test/common/plugin_command_test.dart
- script/tool/test/list_command_test.dart
Most of the tool operates on packages in general, and the targetting
done currently by the `--plugins` flag is not actually restricted to
plugins, so this makes the name less confusing.
`--plugin` will continue to work for now to minimize disruption to
scripts and workflows.
Part of https://github.com/flutter/flutter/issues/83413
- [x ] All existing and new tests are passing. …
> [flutter_plugin_tools] Add --packages, and deprecated --plugins

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/lib/url_launcher.dart
- packages/url_launcher/url_launcher/pubspec.yaml
- packages/url_launcher/url_launcher/test/url_launcher_test.dart
- packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md
- packages/url_launcher/url_launcher_platform_interface/lib/link.dart
- packages/url_launcher/url_launcher_platform_interface/pubspec.yaml
Since plugins also have to work with the stable branch, we can't actually take advantage of the changes right away, so we muddle the issue in the meantime.
Prep for https://github.com/flutter/flutter/pull/83843 …
> [url_launcher] Prepare plugin repo for binding API improvements.

- script/tool/lib/src/test_command.dart
- script/tool/test/test_command_test.dart
Migrates `test` to the new package looping base command.
Refactors the bulk of the logic to helpers for easier understanding of the flow. …
> [flutter_plugin_tools] Migrate 'test' to new base command

- script/tool/CHANGELOG.md
- script/tool/lib/src/drive_examples_command.dart
- script/tool/test/drive_examples_command_test.dart
Strip off any unexpected output before parsing `flutter devices
--machine` output. Works around a bug in the Flutter tool that can
result in banners being printed in `--machine` mode.
Fixes https://github.com/flutter/flutter/issues/86052 …
> [flutter_plugin_tools] Work around banner in drive-examples

- packages/battery/battery_platform_interface/test/method_channel_battery_test.dart
- packages/camera/camera/example/lib/main.dart
- packages/connectivity/connectivity_platform_interface/test/method_channel_connectivity_test.dart
- packages/sensors/test/sensors_test.dart
- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player/pubspec.yaml
- packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
- packages/webview_flutter/test/webview_flutter_test.dart
Since plugins also have to work with the stable branch, we can't actually take advantage of the changes right away, so we muddle the issue in the meantime.
Prep for flutter/flutter#83843
See also https://github.com/flutter/plugins/pull/4136
[Discord]: …
> [various] Prepare plugin repo for binding API improvements

- packages/plugin_platform_interface/CHANGELOG.md
- packages/plugin_platform_interface/README.md
- packages/plugin_platform_interface/pubspec.yaml
Fix broken link for federated flutter plugins.
rel:
- https://github.com/flutter/plugins/pull/2888
- https://github.com/flutter/plugins/pull/3038 …
> [plugin_platform_interface] Fix README broken link

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/InAppPurchasePluginTests.m
- packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/Stubs.m
- packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAPReceiptManager.m
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
It seems like the app is crashing because it can't send `receiptError.userInfo` over the methodchannel in a FlutterError. This PR uses the existing error mapper to parse the error to something that can be send over the methodchannel.
Fixes flutter/flutter#85943 
Fixes flutter/flutter#85960 …
> [in_app_purchase] Fix crash when retrieveReceiptWithError gives an error.

- script/tool/lib/src/analyze_command.dart
- script/tool/test/analyze_command_test.dart
Makes validating that there are no unexpected analysis_options.yaml
files part of the per-package loop, rather than a pre-check, so that it
only runs against the target packages. This makes it easier to run
locally on specific packages, since it's not necessary to pass the allow
list for every package when targeting just one package.
This also means that the command will run all the way to the end even
if one package fails that check, rather than exiting immediately and
not analyzing other packages. …
> [flutter_plugin_tools] Only check target packages in analyze

- script/tool/lib/src/format_command.dart
- script/tool/test/format_command_test.dart
- Adds unit tests, as there are currently none.
- Adds more graceful failure handling.
- Adds an internal ignore list to skip files that don't need to be
formatted that showed up during local testing.
- Adds a note explaining that it's intentially not using the new base
command due to performance issues.
[Discord]: …
> [flutter_plugin_tools] Improve and test 'format'

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/lib/src/types/app_store_product_details.dart
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/test/fakes/fake_ios_platform.dart
- packages/in_app_purchase/in_app_purchase_ios/test/in_app_purchase_ios_platform_test.dart
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_product_test.dart
- packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_test_stub_objects.dart
This PR adds the existing iOS price currency symbol to the platform interface object ProductDetails.
The symbol is not expected to be empty, but if it is it has a fallback to the currency code, just like Android has.
iOS implementation of #4115
Last part of flutter/flutter#83984.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-break …
> [in_app_purchase] Add iOS currency symbol to ProductDetails

- script/tool/CHANGELOG.md
- script/tool/lib/src/format_command.dart
- script/tool/pubspec.yaml
- script/tool/test/format_command_test.dart
Allows `format` to run successfully on Windows:
- Ensures that no calls exceed the command length limit.
- Allows specifying a `java` path to make it easier to run without a system Java (e.g., by pointing to the `java` binary in an Android Studio installation).
- Adds clear error messages when `java` or `clang-format` is missing since it's very non-obvious what's wrong otherwise.
Bumps the version, which I intended to do in the previous PR but apparently didn't push to the PR. …
> [flutter_plugin_tools] Support format on Windows

- script/tool/CHANGELOG.md
- script/tool/lib/src/license_check_command.dart
- script/tool/test/license_check_command_test.dart
Currently each type of check handles its output in isolation, which
creates confusing output when the last check succeeds but an earlier
check fails, since the end of the output will just be a success message.
This makes the output follow the same basic approach as the package
looper commands, where all failures are collected, and then a final
summary is presented at the end, so the last message will always reflect
the important details.
It also adopts the colorized output now used by most other commands. …
> [flutter_plugin_tools] Improve license-check output

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/ios/RunnerTests/CameraExposureTests.m
- packages/camera/camera/example/ios/RunnerTests/CameraFocusTests.m
- packages/camera/camera/example/ios/RunnerTests/CameraUtilTests.m
- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/camera/camera/pubspec.yaml
As of right now, the setFocusPoint and setExposurePoint methods in the camera plugin do not correctly rotate the supplied coordinates according to the UI orientation, causing them to only show correct behaviour in one orientation.
This PR fixes this issue on iOS. 
The fix for Android has been included in the part 9 PR of the android refactor (#4059).
Relevant issue:
- flutter/flutter#86468 …
> [camera] Fix coordinate rotation for setting focus- and exposure points on iOS

- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/README.md
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
The `google_maps_flutter_web` package `README.md` lists old versions in the usage description. This is confusing to users attempting to use Google Maps in Flutter for web apps.
fixes: https://github.com/flutter/flutter/issues/86631 …
> [google_maps_flutter_web]: Update instructions to reflect current versions

- packages/image_picker/image_picker_for_web/AUTHORS
- packages/image_picker/image_picker_for_web/CHANGELOG.md
- packages/image_picker/image_picker_for_web/example/integration_test/image_picker_for_web_test.dart
- packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart
- packages/image_picker/image_picker_for_web/pubspec.yaml
Add support for picking multiple image , and store name and other properties in XFile
Fixes https://github.com/flutter/flutter/issues/86525
Fixes https://github.com/flutter/flutter/issues/58764 …
> [image_picker_for_web] Support multiple pick. Store name and other local file properties in XFile.

- script/tool/CHANGELOG.md
- script/tool/lib/src/format_command.dart
- script/tool/pubspec.yaml
- script/tool/test/format_command_test.dart
Some versions of Java, incuding the one currently installed on Cirrus
macOS machines, don't accept `--version`.
Fixes https://github.com/flutter/flutter/issues/86675 …
> [flutter_plugin_tools] Use -version with java

- packages/camera/camera_web/example/integration_test/camera_test.dart
- packages/camera/camera_web/lib/src/camera.dart
- packages/camera/camera_web/lib/src/shims/dart_ui.dart
- packages/camera/camera_web/lib/src/shims/dart_ui_fake.dart
- packages/camera/camera_web/lib/src/shims/dart_ui_real.dart
- packages/camera/camera_web/lib/src/types/camera_error_codes.dart
- packages/camera/camera_web/lib/src/types/types.dart
Adds `Camera` to `camera_web` plugin. It is used to play/stop the video stream and take a picture. May be constrained with [`CameraOptions`](https://github.com/flutter/plugins/pull/4164).
Part of https://github.com/flutter/flutter/issues/45297 …
> [camera_web] Add `Camera` used to play/stop the video stream and take a picture

- packages/webview_flutter/webview_flutter/android/build.gradle
- packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewFactory.java
- packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewBuilder.java
- packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java
- packages/webview_flutter/webview_flutter/android/src/test/java/io/flutter/plugins/webviewflutter/FlutterWebViewTest.java
- packages/webview_flutter/webview_flutter/android/src/test/java/io/flutter/plugins/webviewflutter/WebViewBuilderTest.java
Currently the constructor of the Java `FlutterWebView` is populated with several lines of code that initialise and configure the Android WebView control. This has two major drawback:
1. The code becomes difficult to understand;
2. The code is extremely hard to test as there is no good way to mock the WebView control.
This PR solves this problem by introducing a `WebViewBuilder` which is responsible for correctly creating the right Android WebView control and applying the necessary configuration. 
The following PRs will directly benefit from this change:
- #4169 
- #4165
- No release needed as nothing changed in the behaviour of the plugin. Simply a …
> [webview_flutter] Refactored creation of Android WebView for testability.

- packages/camera/camera_platform_interface/lib/src/types/resolution_preset.dart
- packages/camera/camera_web/example/integration_test/camera_settings_test.dart
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera_settings.dart
- packages/camera/camera_web/lib/src/camera_web.dart
- packages/camera/camera_web/lib/src/types/camera_error_codes.dart
Adds `createCamera` implementation of the camera platform interface.
- Added `mapFacingModeToCameraType` to `CameraSettings`.
- Maps the [camera facing mode](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/facingMode) to a [camera type](https://github.com/flutter/plugins/blob/master/packages/camera/camera_web/lib/src/types/camera_options.dart#L131), used when creating a camera.
- Added `mapResolutionPresetToSize` to `CameraSettings`.
- Maps the [resolution preset](https://github.com/flutter/plugins/blob/master/packages/camera/camera_platform_interface/lib/src/types/resolution_preset.dart#L8) to a size, used when creating a camera.
- Uses the same sizes as on Android.
- Added `createCamera` implementation.
- Uses camera metadata initialized in `availableCameras` to …
> [camera_web] Add `createCamera` implementation

- packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart
- packages/camera/camera_web/example/integration_test/camera_test.dart
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/example/integration_test/helpers/mocks.dart
- packages/camera/camera_web/lib/src/camera.dart
- packages/camera/camera_web/lib/src/camera_web.dart
Adds `initializeCamera` implementation of the camera platform interface.
- Added `getVideoSize` to `Camera`.
- Returns a size of the camera video based on its first video track size.
- Added `initializeCamera` and `onCameraInitialized` implementation.
- Initializes and starts playing the camera stream.
- Adds a `CameraInitializedEvent` to the camera events stream controller. The event is emitted on the `onCameraInitialized` stream and includes a camera id, video size, default exposure and focus modes (auto).
- Replaced an HTTP stream with a blank canvas stream in tests that use a video element. In this way, tests are not reliant on the network and the video size can be easily adjusted. …
> [camera_web] Add `initializeCamera` implementation

- .cirrus.yml
- script/configs/custom_analysis.yaml
- script/tool/test/analyze_command_test.dart
Adds a unit test and comments intended to avoid accidental breakage of
the Dart repo's run of analysis against this repository.
Addresses https://github.com/flutter/plugins/pull/4183#issuecomment-885767597 …
> [flutter_plugin_tools] Test and comment Dart analysis

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/test/firebase_test_lab_command_test.dart
CI tends to either fail due to a flaky test in `webview_flutter` or the test times out.  …
> Skip a flaky webview_flutter integration test and extend firebase testlab timeout

- packages/webview_flutter/webview_flutter/example/android/app/src/main/AndroidManifest.xml
According to the logs from Firebase Test Lab, the tests have this error on timeouts:
```
07-26 23:28:25.498: I/flutter(19917): (The following exception is now available via WidgetTester.takeException:)
07-26 23:28:25.547: I/flutter(19917): â•â•â•¡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK â•žâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
07-26 23:28:25.547: I/flutter(19917): The following PlatformException was thrown running a test:
07-26 23:28:25.547: I/flutter(19917): PlatformException(error, Neither user 10223 nor current process has android.permission.WAKE_LOCK.,
07-26 23:28:25.547: I/flutter(19917): null, java.lang.SecurityException: Neither user 10223 nor current process …
```
> wake lock permission

- packages/camera/camera/example/lib/main.dart
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/example/integration_test/helpers/mocks.dart
- packages/camera/camera_web/lib/src/camera_web.dart
Adds `takePicture` implementation of the camera platform interface.
- Calls `takePicture` on the `Camera` with the given id. …
> [camera_web] Add `takePicture` implementation

- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
- packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart
- packages/camera/camera_platform_interface/pubspec.yaml
- packages/camera/camera_platform_interface/test/camera_platform_interface_test.dart
- packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart
This PR adds `pausePreview` and `resumePreview` methods to the camera plugin's platform interface, to support the (un)pausing of the camera preview.
Android & iOS implementations for these methods can be found in #4192.
Related issues:
- flutter/flutter#34997
- flutter/flutter#27079
> [camera_platform_interface] Expand camera platform interface to support pausing the camera preview.

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/lib/src/camera_preview.dart
- packages/camera/camera/pubspec.yaml
Currently, the preview widget does not always rebuild when a device orientation change occurs. This PR fixes this by having the widget rebuild when the `CameraValue`, which contains the device orientation, is updated.
Relevant issue: 
- flutter/flutter#87108
- No new public members
- If this is something that has to be tested let me know. It's a small change that does not affect any current tests and I don't feel like it warrants writing a new one.
> [camera] Fix camera preview not always rebuilding on orientation change

- packages/in_app_purchase/in_app_purchase_ios/README.md
Removed the code block start tag which broke the formatting of the README markdown.
Fixes flutter/flutter#87185
- Not necessary to release a separate version for this small documentation change.
- Not necessary to release a separate version for this small documentation change.
- Small documentation fix which doesn't require unit-tests.
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.m …
> Correct mistake with markdown in README.md

- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera_web.dart
Adds `dispose` implementation of the camera platform interface.
- Calls `dispose` on the `Camera` with the given id.
- Removes that camera from the list of cameras managed by the camera plugin. …
> [camera_web] Add `dispose` implementation

- packages/google_maps_flutter/google_maps_flutter/example/android/app/src/androidTest/java/io/flutter/plugins/googlemapsexample/GoogleMapsTest.java
This test currently has an out-of-band failure on master. Ignoring to
re-open the tree.
See https://github.com/flutter/flutter/issues/87566
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#fo …
> [google_maps_flutter] Temporarily disable googleMapsPluginIsAdded

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/example/ios/RunnerTests/MetaDataUtilTests.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.h
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.m
- packages/image_picker/image_picker/pubspec.yaml
Reworks the logic in updateMetaData:toImage: to correctly handle the
possibility of null return values from intermediate steps. Also renames
it to have a more idiomatic ObjC name.
Speculative fix for https://github.com/flutter/flutter/issues/80429
Since the case this would likely fix is bad image data, this may simply
move problems to another part of the plugin, but this is definitely a
correctness improvement here, and if it does move the issue elsewhere we
can tackle that once we have more information. …
> [image_picker] Check for failure in iOS metadata updates

- .cirrus.yml
This command isn't intended for CI use, and is also slower due to
downloading artifacts that will be immidately discarded.
Cirrus portion of https://github.com/flutter/flutter/issues/86037 …
> Don't use 'flutter upgrade' on Cirrus

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/README.md
- packages/image_picker/image_picker/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/87634
In the API Docs for [pickMultiImage](https://pub.dev/documentation/image_picker/latest/image_picker/ImagePicker/pickMultiImage.html) or [code sample](https://github.com/flutter/plugins/blob/60100908443fffee28df82735a9c4019cf549227/packages/image_picker/image_picker/example/lib/main.dart#L94), there is no `source` parameter in pickMultiImage …
> [image_picker] Fix README example

- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera_web.dart
Adds `onCameraResolutionChanged` implementation to the web camera platform.
- Emits an empty stream as there is no event corresponding to a change in the camera resolution on the web. …
> [camera_web] Add `onCameraResolutionChanged` implementation

- packages/camera/camera_web/example/integration_test/camera_settings_test.dart
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/example/integration_test/helpers/mocks.dart
- packages/camera/camera_web/lib/src/camera_settings.dart
- packages/camera/camera_web/lib/src/camera_web.dart
- packages/camera/camera_web/lib/src/types/camera_error_code.dart
- packages/camera/camera_web/lib/src/types/orientation_type.dart
- packages/camera/camera_web/lib/src/types/types.dart
- packages/camera/camera_web/test/types/camera_error_code_test.dart
Adds support for device orientation to the web camera platform.
- Added `OrientationType` representing a screen orientation type of the browser ([`ScreenOrientation.type`](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/type)).
- Added `lockCaptureOrientation` implementation.
- Requests the full-screen mode as it may be required to modify the device orientation ([Interaction with Fullscreen API](https://w3c.github.io/screen-orientation/#interaction-with-fullscreen-api)).
- Locks the orientation to the given device orientation with [`ScreenOrientation.lock`](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock).
- Throws a `PlatformException` when the screen orientation API is not supported.
- Added `unlockCaptureOrientation` implementation.
- Requests …
> [camera_web] Add support for device orientation

- packages/camera/camera_web/example/integration_test/camera_test.dart
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera.dart
- packages/camera/camera_web/lib/src/camera_web.dart
- packages/camera/camera_web/lib/src/types/camera_error_code.dart
- packages/camera/camera_web/test/types/camera_error_code_test.dart
Adds support for a flash mode to the web camera platform.
- Added `setFlashMode` to `Camera`.
- Saves the flash mode in the camera.
- Enables the torch mode video constraint if the flash mode is `torch` (otherwise disables).
- Throws a `CameraWebException` if the torch mode is not supported in the current browser or the camera has not been initialized or started.
- The camera stream can now be accessed through the `Camera.stream` property.
- Updated `takePicture` in `Camera`.
- Enables the torch mode video constraint when taking a picture if the flash mode is either `auto` or `always`.
- Added `setFlashMode` implementation to the camera plugin.
- Calls `setFlashMode` on the camera with the given id. …
> [camera_web] Add support for a flash mode

- packages/camera/camera_web/example/integration_test/camera_settings_test.dart
- packages/camera/camera_web/example/integration_test/camera_test.dart
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera.dart
- packages/camera/camera_web/lib/src/camera_settings.dart
- packages/camera/camera_web/lib/src/camera_web.dart
- packages/camera/camera_web/lib/src/types/camera_error_code.dart
- packages/camera/camera_web/lib/src/types/types.dart
- packages/camera/camera_web/lib/src/types/zoom_level_capability.dart
- packages/camera/camera_web/pubspec.yaml
- packages/camera/camera_web/test/helpers/mocks.dart
- packages/camera/camera_web/test/types/camera_error_code_test.dart
- packages/camera/camera_web/test/types/zoom_level_capability_test.dart
Adds support for a zoom level to the web camera platform.
- Added `getZoomLevelCapabilityForCamera` to `CameraSettings`.
- Returns the zoom level capability for the given camera. Includes the minimum and maximum zoom levels and the video track capable of configuring the zoom level.
- Throws a `CameraWebException` if the zoom level is not supported or the camera has not been initialized or started.
- Added `getMaxZoomLevel`, `getMinZoomLevel` and `setZoomLevel` to `Camera` and `CameraPlugin`.
- Each method uses `CameraSettings.getZoomLevelCapabilityForCamera` to access the camera zoom level capability.
- `setZoomLevel` throws a `CameraWebException` if the zoom level is invalid (not in the valid range). …
> [camera_web] Add support for a zoom level

- .ci.yaml
Add the information necessary to no longer require the starlark code in flutter/infra
https://github.com/flutter/flutter/issues/85803
See https://flutter-review.googlesource.com/c/infra/+/16742 for the auto-generated diff
> [ci.yaml] Auto-generate LUCI configs

- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera_web.dart
Removes requesting full-screen mode in `unlockCaptureOrientation` as suggested in https://github.com/flutter/plugins/pull/4219#discussion_r684561974. …
> [camera_web] Don't request full-screen mode in `unlockCaptureOrientation`

- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera_web.dart
Added handling of camera errors in `takePicture`. The method may throw a `CameraWebException` after changes introduced in https://github.com/flutter/plugins/pull/4222. The exception is handled by throwing a `PlatformException` and emitting a camera error event on the `onCameraError` stream. …
> [camera_web] Handle camera errors in `takePicture`

- packages/camera/camera_web/example/integration_test/camera_service_test.dart
- packages/camera/camera_web/example/integration_test/helpers/mocks.dart
- packages/camera/camera_web/lib/src/camera_service.dart
- packages/camera/camera_web/lib/src/shims/dart_js_util.dart
Fixed `getCapabilities` not supported error thrown when selecting a camera on Firefox. 
Before, the method was always called and an exception was thrown on Firefox with its runtime type checked against `JSNoSuchMethodError`. This caused issues as the runtime type was different depending on the build mode (release, profile, staging). Now, the method is called only if it is available on the video track (checked with `JsUtil.hasProperty`). …
> [camera_web] Fix `getCapabilities` not supported error thrown when selecting a camera on Firefox

- packages/camera/camera_web/example/integration_test/camera_web_test.dart
Added missing `CameraPlugin.setFlashMode` test to verify if the method is called on the `Camera` with the given id. …
> [camera_web] Add missing `setFlashMode` test

- packages/camera/camera/example/lib/main.dart
Fixes a disposed `CameraController` error thrown when changing the camera in the camera example. 
The error is thrown by the `ValueListenableBuilder` in the `CameraPreview`. Changing a camera disposes the previous `CameraController` before the widget state is updated causing the `ValueListenableBuilder` to listen to the disposed controller. This PR solves the issue by disposing the previous `CameraController` after the new one is initialized.
Error:
```
The following assertion was thrown building CameraPreview:
A CameraController was used after being disposed.
Once you have called dispose() on a CameraController, it can no longer be
used.
The relevant error-causing widget was:
CameraPreview
file:///Users/.../Projects/plugins/packages/camera/camera/example/lib/main.dart:188:16
``` …
> [camera] Fix a disposed `CameraController` error thrown when changing a camera

- packages/camera/camera_web/example/integration_test/camera_test.dart
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera.dart
- packages/camera/camera_web/lib/src/camera_web.dart
- packages/camera/camera_web/pubspec.yaml
Adds support for pausing and resuming the camera preview to the web camera platform.
- Added `pause` to `Camera`.
- Pauses the video element stream ([HTMLMediaElement.pause](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause)).
- Added `pausePreview` implementation.
- Calls `pause` on the camera with the given id.
- Throws a `PlatformException` if the camera throws a `DomException`.
- Added `resumePreview` implementation.
- Calls `play` on the camera with the given id.
- Throws a `PlatformException` if the camera throws either a `DomException` or a `CameraWebException`.
Relates to https://github.com/flutter/plugins/pull/4191. …
> [camera_web] Add support for pausing and resuming the camera preview

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/README.md
- packages/video_player/video_player/pubspec.yaml
Video Player  is functional on iOS simulators ,so i have removed this warning.
https://user-images.githubusercontent.com/30950893/129403561-28551551-8e2d-47db-9087-7989e20e13c1.mp4
Reference: https://github.com/flutter/flutter/issues/14647
[Discord]: …
> [video_player] removed video player is not functional on ios simulators warning

- packages/quick_actions/quick_actions/android/build.gradle
- packages/quick_actions/quick_actions/android/src/test/java/io/flutter/plugins/quickactions/QuickActionsTest.java
Add unit tests to `quick_actions` plugin
> Add unit tests to `quick_actions` plugin

- script/tool/CHANGELOG.md
- script/tool/lib/src/version_check_command.dart
- script/tool/test/version_check_command_test.dart
The special "NEXT" entry in a CHANGELOG should never be present in a
commit that bumped the version. This validates that this is true even if
the CHANGELOG would be correct for a non-version-change state, to catch
someone incorrectly resolving a merge conflict by leaving both parts of
the conflict, rather than folding the 'NEXT' entry's list into the new
version's notes.
Fixes https://github.com/flutter/flutter/issues/85584 …
> [flutter_plugin_tool] Don't allow NEXT on version bumps

- packages/camera/camera_web/CHANGELOG.md
- packages/camera/camera_web/pubspec.yaml
- packages/connectivity/connectivity_for_web/CHANGELOG.md
- packages/connectivity/connectivity_for_web/pubspec.yaml
- packages/connectivity/connectivity_macos/CHANGELOG.md
- packages/connectivity/connectivity_macos/pubspec.yaml
- packages/file_selector/file_selector_web/CHANGELOG.md
- packages/file_selector/file_selector_web/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
- packages/image_picker/image_picker_for_web/CHANGELOG.md
- packages/image_picker/image_picker_for_web/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
- packages/shared_preferences/shared_preferences_web/CHANGELOG.md
- packages/shared_preferences/shared_preferences_web/pubspec.yaml
- packages/url_launcher/url_launcher_web/CHANGELOG.md
- packages/url_launcher/url_launcher_web/pubspec.yaml
- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/pubspec.yaml
- script/tool/CHANGELOG.md
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/test/pubspec_check_command_test.dart
The federated plugin spec calls for implementation packages to include an `implements` entry in the `plugins` section of the `pubspec.yaml` indicating what app-facing package it implements. Most of the described behaviors of the `flutter` tool aren't implemented yet, and the pub.dev features have `default_plugin` as a backstop, so we haven't noticed that they are mostly missing (or in one case, incorrect).
To better future-proof the plugins, and to provide a better example to people looking at our plugins as examples of federation, this adds a CI check to make sure that we are correctly adding it, and fixes all of the missing/incorrect values it turned up.
Fixes https://github.com/flutter/flutter/issues/88222 …
> Fix and test for 'implements' pubspec entry

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
- packages/ios_platform_images/CHANGELOG.md
- packages/ios_platform_images/pubspec.yaml
- packages/quick_actions/quick_actions/CHANGELOG.md
- packages/quick_actions/quick_actions/pubspec.yaml
- script/tool/CHANGELOG.md
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/test/pubspec_check_command_test.dart
Ensures that the full relative path in the 'repository' link is correct,
not just the last segment. This ensure that path-level errors (e.g.,
linking to the group directory rather than the package itself for
app-facing packages) are caught.
Also fixes the errors that this improved check catches, including
several cases where a previously unfederated package wasn't fixed when
it was moved to a subdirectory. …
> [flutter_plugin_tools] Improve 'repository' check

- script/tool/test/analyze_command_test.dart
- script/tool/test/build_examples_command_test.dart
- script/tool/test/common/gradle_test.dart
- script/tool/test/common/xcode_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/firebase_test_lab_command_test.dart
- script/tool/test/format_command_test.dart
- script/tool/test/lint_android_command_test.dart
- script/tool/test/lint_podspecs_command_test.dart
- script/tool/test/mocks.dart
- script/tool/test/native_test_command_test.dart
- script/tool/test/publish_check_command_test.dart
- script/tool/test/publish_plugin_command_test.dart
- script/tool/test/test_command_test.dart
- script/tool/test/util.dart
- script/tool/test/xcode_analyze_command_test.dart
The mock process runner used in most of the tests had poor handling of
stdout/stderr:
- By default it would return the `List<int>` output from the mock
process, which was never correct since the parent process runner
interface always sets encodings, thus the `dynamic` should always be
of type `String`
- The process for setting output on a `MockProcess` was awkward, since
it was based on a `Stream<Lint<int>>`, even though in every case what
we actually want to do is just set the full output to a string.
- A hack was at some point added (presumably due to the above isssues)
to bypass that flow at the process runner level, and instead return a
`String` set there. That meant there were two ways of setting output
(one of which that only worked for one of the ways of running
processes)
- That …
> [flutter_plugin_tools] Improve process mocking

- script/tool/lib/src/analyze_command.dart
- script/tool/lib/src/build_examples_command.dart
- script/tool/lib/src/common/package_looping_command.dart
- script/tool/lib/src/common/plugin_command.dart
- script/tool/lib/src/common/plugin_utils.dart
- script/tool/lib/src/common/pub_version_finder.dart
- script/tool/lib/src/common/repository_package.dart
- script/tool/lib/src/create_all_plugins_app_command.dart
- script/tool/lib/src/drive_examples_command.dart
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/lib/src/lint_android_command.dart
- script/tool/lib/src/lint_podspecs_command.dart
- script/tool/lib/src/list_command.dart
- script/tool/lib/src/native_test_command.dart
- script/tool/lib/src/publish_check_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/lib/src/test_command.dart
- script/tool/lib/src/version_check_command.dart
- script/tool/lib/src/xcode_analyze_command.dart
- script/tool/test/common/package_looping_command_test.dart
- script/tool/test/common/plugin_command_test.dart
- script/tool/test/common/plugin_utils_test.dart
- script/tool/test/common/pub_version_finder_test.dart
- script/tool/test/common/repository_package_test.dart
- script/tool/test/format_command_test.dart
- script/tool/test/util.dart
Packages are the primary conceptual object in the tool, but currently they are represented simply as Directory (or occasionally a path string). This introduces an object for packages and:
- moves a number of existing utility methods into it
- sweeps the code for the obvious cases of using `Directory` to represent a package, especially in method signatures and migrates them
- notes a few places where we should migrate later, to avoid ballooning the size of the PR
There are no doubt other cases not caught in the sweep, but this gives us a foundation both for new code, and to migrate incrementally toward as we find existing code that was missed. …
> [flutter_plugin_tools] Introduce a class for packages

- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/publish_plugin_command_test.dart
Finishes the migration of tool tests to `runCapturingPrint`. This makes
the tests much less verbose, and makes it match the rest of the tool
tests.
Also adds the use of `printError` for error output, now that it's
trivial to do so. …
> [flutter_plugin_tool] Migrate publish_plugin_command_test to runCapturingPrint

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java
- packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraCaptureCallback.java
- packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/types/CameraCaptureProperties.java
- packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/CameraCaptureCallbackStatesTest.java
- packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/CameraCaptureCallbackTest.java
- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/camera/camera/lib/src/camera_image.dart
- packages/camera/camera/pubspec.yaml
- packages/camera/camera/test/camera_image_test.dart
(Resubmission of #4170)
This PR adds additional properties to the CameraImage DTO:
- `lensAperture`
- `sensorExposureTime`
- `sensorSensitivity`
Relevant issue:
- flutter/flutter#73250
This PR adds no breaking changes.
> [camera] Expand CameraImage DTO with properties for lens aperture, exposure time and ISO. 

- script/tool/CHANGELOG.md
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/publish_plugin_command_test.dart
Replaces the `publish`-command-specific `--package` flag with support for `--packages`, and unifies the flow with the existing looping for `--all-changed`.
This better aligns the command's API with the rest of the commands, and reduces divergence in the two flows (e.g., `--package` would attempt to publish and fail if the package was already published, whereas now using `--packages` will use the flow that pre-checks against `pub.dev`). It also sets up a structure that will allow easily converting it to the new base package looping command that most other commands now use, which will be done in a follow-up.
Since all calls now attempt to contact `pub.dev`, the tests have been adjusted to always mock the HTTP client so they will be hermetic.
Part of …
> [flutter_plugin_tools] Switch 'publish' from --package to --packages

- .github/workflows/release.yml
Relands https://github.com/flutter/plugins/pull/4262 as the white list has been updated to allow the newer wait-on-check version.
Fixes https://github.com/flutter/flutter/issues/85127#issuecomment-907557132
> Reland "[ci] update wait-on-check version and set verbose to false"

- packages/camera/camera_web/example/integration_test/camera_test.dart
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera.dart
- packages/camera/camera_web/lib/src/camera_web.dart
Before, the video was flipped on all cameras making a video incorrectly mirrored when taken from a back camera. Now, the video is not flipped on the back camera.
[the …
> [camera_web] Do not flip the video on the back camera

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/file_utils.dart
- script/tool/lib/src/common/plugin_utils.dart
- script/tool/lib/src/native_test_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/common/file_utils_test.dart
- script/tool/test/common/plugin_utils_test.dart
- script/tool/test/native_test_command_test.dart
- script/tool/test/util.dart
Implements support for `--windows` in `native-test`, for unit tests only. The structure of the new code has most of the new functionality in a generic utility for running GoogleTest test binaries, so that it can be trivially extended to Linux support in a follow-up once the Linux test PoC has landed.
This runs the recently-added `url_launcher_windows` unit test. However, it's not yet run in CI since it needs LUCI bringup; that will be done one this support is in place.
Requires new logic to check if a plugin contains native code, and some new test utility plumbing to generate plugins whose pubspecs indicate that they only contain Dart code to test it, to allow filtering filtering out the FFI-based Windows plugins.
Part of flutter/flutter#82445 …
> [flutter_plugin_tool] Add support for running Windows unit tests

- script/tool/lib/src/common/package_looping_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/publish_plugin_command_test.dart
Moves `publish` to PackageLoopingCommand, giving it the same
standardized output and summary that is used by most other commands in
the tool.
Adds minor new functionality to the base command to allow it to handle
the specific needs of publish:
- Allows fully customizing the set of packages to loop over, to support
--all-changed
- Allows customization of a few more strings so the output better
matches the functionality (e.g., using 'published' instead of 'ran' in
the summary lines).
Fixes https://github.com/flutter/flutter/issues/83413
[CLA]: …
> [flutter_plugin_tool] Migrate 'publish' to new base command

- .cirrus.yml
- packages/url_launcher/url_launcher_linux/example/linux/CMakeLists.txt
- packages/url_launcher/url_launcher_linux/example/linux/flutter/CMakeLists.txt
- packages/url_launcher/url_launcher_linux/linux/CMakeLists.txt
- packages/url_launcher/url_launcher_linux/linux/test/url_launcher_linux_test.cc
- packages/url_launcher/url_launcher_linux/linux/url_launcher_plugin.cc
- packages/url_launcher/url_launcher_linux/linux/url_launcher_plugin_private.h
- script/tool/CHANGELOG.md
- script/tool/lib/src/native_test_command.dart
- script/tool/test/native_test_command_test.dart
- Adds a minimal unit test to url_launcher_linux as a proof of concept. This uses almost exactly the same CMake structure as the Windows version that was added recently.
- Adds Linux support for unit tests to `native-test`, sharing almost all of the existing Windows codepath.
- Fixes the fact that it it was running the debug version of the unit tests, but `build-examples` only builds release. (On other platforms we run debug unit tests, but on those platforms the test command internally builds the requested unit tests, so the mismatch doesn't matter.)
- Enables the new test in CI.
Also opportunistically fixes some documentation in `native_test_command.dart` that wasn't updated as more platform support was added.
Linux portion of https://github.com/flutter/flutter/issues/82445
[Contributor …
> [flutter_plugin_tools] Add Linux support to native-test

- script/tool/CHANGELOG.md
- script/tool/lib/src/format_command.dart
- script/tool/pubspec.yaml
- script/tool/test/format_command_test.dart
Per discussion on Discord, this adds a way to opt-out of the formatting.
> [tool] Add a way to opt a file out of formatting

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java
- packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/CameraTest.java
- packages/camera/camera/example/lib/main.dart
- packages/camera/camera/pubspec.yaml
Since version 0.9.0 the Android `setExposureOffset` method doesn't return the newly configured offset after updating the exposure offset. This will cause a `Unhandled Exception: Null check operator used on a null value` error in the camera_platform_interface as it does expect a result. 
This PR fixes the problem by correctly returning the newly configured exposure offset on Android.
Resolves flutter/flutter#89281 …
> [camera] Ensure setExposureOffset returns new value on Android

- .ci.yaml
- .ci/scripts/build_examples_win32.sh
- .ci/scripts/drive_examples_win32.sh
- .ci/scripts/prepare_tool.sh
- .ci/targets/windows_build_and_platform_tests.yaml
See https://github.com/flutter/flutter/issues/89373 for context. This
sets up the script and config file to replicate the current plugins.py
recipe's behavior using the planned generic recipe.
These are currently unused, but are being landed first so that the
generic recipe has something to test against.
Part of https://github.com/flutter/flutter/issues/89373
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-ch …
> Add scripts for Windows LUCI recipe

- .ci.yaml
This enables testing flutter/recipes changes to these builders
> [ci.yaml] Add builders to recipes cq

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/google_sign_in/pubspec.yaml
- packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart
Adds an optional paramter to the signInSilently method which allows the application using the plugin to decide whether re-authentication should be attempted.
Fixes [#88556](https://github.com/flutter/flutter/issues/88556) 
[the …
> [google_sign_in] adds option to re-authenticate on google silent sign in

- packages/camera/camera_web/CHANGELOG.md
- packages/camera/camera_web/README.md
- packages/camera/camera_web/pubspec.yaml
This PR gets the `camera_web` package ready to publish into pub.dev, as v0.2.0
(Partially addresses https://github.com/flutter/flutter/issues/45297)
* Clarify in the README that the plugin is not endorsed yet.
* Tweak the list of not-supported operations
* Call this v0.2.0
Thanks @bselwe!! …
> [camera_web] Make plugin publishable for the first time.

- script/tool/CHANGELOG.md
- script/tool/lib/src/build_examples_command.dart
- script/tool/pubspec.yaml
- script/tool/test/build_examples_command_test.dart
> [plugin_tools] build-examples .pluginToolsConfig.yaml support

- script/tool/lib/src/common/git_version_finder.dart
- script/tool/lib/src/common/plugin_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/common/plugin_command_test.dart
- script/tool/test/publish_plugin_command_test.dart
Moves diff logging out of a helper, which would not be expected to do
logging, and into specific commands where logging the diff base is
useful.
Fixes some log spam during tests as a side effect. …
> [flutter_plugin_tools] Adjust diff logging

- packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart
- packages/image_picker/image_picker_platform_interface/CHANGELOG.md
- packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart
- packages/image_picker/image_picker_platform_interface/lib/src/platform_interface/image_picker_platform.dart
- packages/image_picker/image_picker_platform_interface/pubspec.yaml
- packages/image_picker/image_picker_platform_interface/test/new_method_channel_image_picker_test.dart
Splitting interface portion from #3264 per https://github.com/flutter/plugins/pull/3264#issuecomment-907328067
Make iOS 11+ permissions requests optional per https://developer.apple.com/forums/thread/653414.
PHAssets aren't actually required and there was already some fallback code in place.
To keep this as a non-breaking change, I added an optional parameter of `forceFullMetadata` with a default of `true`.
Setting this to false will disable any permissions checking on iOS and simply display the image picker.
> [image_picker] add forceFullMetadata to interface

- packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart
- packages/image_picker/image_picker_platform_interface/CHANGELOG.md
- packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart
- packages/image_picker/image_picker_platform_interface/lib/src/platform_interface/image_picker_platform.dart
- packages/image_picker/image_picker_platform_interface/pubspec.yaml
- packages/image_picker/image_picker_platform_interface/test/new_method_channel_image_picker_test.dart
Reverts flutter/plugins#4288
FYI @cpboyd 
This commit appears to be breaking the framework tree somehow: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_plugins/3301/overview
```
Running command: "dart analyze --fatal-infos" in /b/s/w/ir/x/t/flutter_plugins.DYUYDK/packages/image_picker/image_picker_for_web
Analyzing image_picker_for_web...
error - lib/image_picker_for_web.dart:51:22 - 'ImagePickerPlugin.pickImage' ('Future<PickedFile> Function({int? imageQuality, double? maxHeight, double? maxWidth, CameraDevice preferredCameraDevice, required ImageSource source})') isn't a valid override of 'ImagePickerPlatform.pickImage' ('Future<PickedFile?> Function({bool forceFullMetadata, int? imageQuality, double? maxHeight, double? maxWidth, CameraDevice preferredCameraDevice, …
```
> Revert "[image_picker] add forceFullMetadata to interface"

- .github/workflows/release.yml
It's possible for jobs to conclude in a "neutral" state; see https://github.com/flutter/plugins/runs/3534917860 for instance. Currently this causes "release" to be red when it shouldn't be. …
> [ci] Allow neutral conclusion in publishing check

- .ci.yaml
- .ci/scripts/build_all_plugins.sh
- .ci/scripts/build_examples_uwp.sh
- .ci/scripts/create_all_plugins_app.sh
- .ci/scripts/native_test_win32.sh
- .ci/scripts/plugin_tools_tests.sh
- .ci/targets/build_all_plugins.yaml
- .ci/targets/plugin_tools_tests.yaml
- .ci/targets/uwp_build_and_platform_tests.yaml
- .ci/targets/windows_build_and_platform_tests.yaml
- .cirrus.yml
Uses the new generic plugins recipe to add a number of new Windows tests
that have recently gained tool support, but not yet added to the LUCI
builds:
- New targets:
- The "build all plugins" test (master and stable)
- UWP build tests (master only, since UWP is not on stable yet)
- Tool tests (master only with existing tool tests on Linux)
- Replacement versions of the existing builders but with names that
match the Cirrus naming to make the parallels in testing easier
to understand in the GitHub UI and configs.
- Modification of existing targets:
- Adds Windows native unit tests to the existing script.
All but the modification change are in bringup mode, so won't affect the repo until a follow-up
removes that flag.
Part of https://github.com/flutter/flutter/issues/86113
Part of …
> Bring up new Windows test targets

- .ci.yaml
- .cirrus.yml
Fixes the target names in LUCI to not use '+', since it's not supported.
To better align the names between the two different infrastructures,
also updates the task naming in cirrus.yml to not use +. It also
standardizes the naming form across both systems as:
`<Host platform> <target platform>-<test_name> <extra info>`
where:
- `<Host platform>` is always there on LUCI, where required, but only
added where it's potentially ambiguous on Cirrus
- `<target platform>' is omitted when the test is not target-platform
specific
- `<test_name>' uses underscores, which is consistent with
flutter/flutter (and with Cirrus step naming).
- `<extra info>` is only explicitly set (to the channel) on LUCI; Cirrus
automatically adds channel info there due to the way `matrix` works. …
> [ci] Fix and standardize target/task names

- .github/workflows/release.yml
Similar to flutter/packages/pull/461, this PR updates the version of lewagon/wait-on-check-action on the release workflow so it waits for more than 30 checks.
Fixes: flutter/flutter#88120 …
> [ci] Update lewagon/wait-on-check-action to latest version.

- .ci.yaml
- script/tool/test/drive_examples_command_test.dart
Now that the builders have propagated, enable all the new tests and remove the obsolete versions.
Fixes one unit test that was failing on Windows so that new target will be green.
Fixes https://github.com/flutter/flutter/issues/82729
Fixes https://github.com/flutter/flutter/issues/86113
Fixes https://github.com/flutter/flutter/issues/88294
[Discord]: …
> [ci] Enable the new Windows targets

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player/pubspec.yaml
- packages/video_player/video_player/test/video_player_test.dart
- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/example/integration_test/video_player_web_test.dart
- packages/video_player/video_player_web/lib/video_player_web.dart
- packages/video_player/video_player_web/pubspec.yaml
Interface change https://github.com/flutter/plugins/pull/4307 caused flutter/flutter analysis failure https://github.com/flutter/flutter/issues/89792 and failed on [plugins master](https://cirrus-ci.com/task/4582367093325824).  https://github.com/flutter/plugins/pull/4261 needs to be rebased and merged ASAP to unblock the tree.
It unfortunately has merge conflicts on #4300 and the relative paths need to be removed from the pubspec, but I don't have permissions on @byunme's branch to push the fixes there.  So I need to create a new PR.
Also adopted the new interface for `video_player_web`.
Fixes flutter/flutter#88130
The following is copied from https://github.com/flutter/plugins/pull/4261, authored by @byunme.
_________________
This PR adds playback from contentUri support for the …
> [video_player] add support for content-uri based videos

- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterDownloadListener.java
- packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java
- packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewBuilder.java
- packages/webview_flutter/webview_flutter/android/src/test/java/io/flutter/plugins/webviewflutter/FlutterDownloadListenerTest.java
- packages/webview_flutter/webview_flutter/android/src/test/java/io/flutter/plugins/webviewflutter/FlutterWebViewClientTest.java
- packages/webview_flutter/webview_flutter/android/src/test/java/io/flutter/plugins/webviewflutter/FlutterWebViewTest.java
- packages/webview_flutter/webview_flutter/android/src/test/java/io/flutter/plugins/webviewflutter/WebViewBuilderTest.java
- packages/webview_flutter/webview_flutter/pubspec.yaml
This PR adds a download listener to the Android webview and sends that url to the navigation delegate. The Dart code can in turn manage the download. By (bad) luck this is already the way it works on iOS, so this PR makes the behaviour between Android and iOS the same.
Fixes flutter/flutter#89657
I also tested these changes in a complete app. …
> [webview_flutter] Add download listener to Android webview

- script/tool/lib/src/publish_plugin_command.dart
This is a getter; it shouldn't be randomly logging one of its intermediate values as a side effect in normal usage. Presumably this was local debugging for development that was accidentally left in. …
> [flutter_plugin_tools] Remove an unnecessary logging message

- .cirrus.yml
- packages/quick_actions/quick_actions/example/ios/Podfile
- packages/quick_actions/quick_actions/example/ios/Runner.xcodeproj/project.pbxproj
- packages/quick_actions/quick_actions/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/quick_actions/quick_actions/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- packages/quick_actions/quick_actions/example/ios/RunnerTests/Info.plist
- packages/quick_actions/quick_actions/example/ios/RunnerTests/RunnerTests.m
- packages/share/example/ios/Podfile
- packages/share/example/ios/Runner.xcodeproj/project.pbxproj
- packages/share/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- packages/share/example/ios/RunnerTests/Info.plist
- packages/share/example/ios/RunnerTests/RunnerTests.m
- script/configs/exclude_native_ios.yaml
- script/tool/CHANGELOG.md
- script/tool/lib/src/native_test_command.dart
- script/tool/test/native_test_command_test.dart
Brings iOS and macOS into alignment with the other platforms, where
having unit tests set up is required.
- For deprecated plugins with no tests, `--exclude`s them, as on other platforms
- For `quick_actions` and `share`, which have integration tests but no unit tests,
sets up the unit test scaffolding. (This is done for `share` even though it's
deprecated since unlike other platforms, iOS/macOS runs both native tests in the 
same command, and setting up a special way to exclude just units tests for that
one case would be much more effort.)
Fixes flutter/flutter#85469 …
> [flutter_plugin_tools] Make no unit tests fatal for iOS/macOS

- packages/path_provider/path_provider_linux/CHANGELOG.md
- packages/path_provider/path_provider_linux/lib/path_provider_linux.dart
- packages/path_provider/path_provider_linux/pubspec.yaml
- packages/path_provider/path_provider_linux/test/path_provider_linux_test.dart
TMPDIR is a standard variable on UNIX/Linux systems, and is often used in containers such as Flatpak to redirect to a temporary folder inside a sandbox. This allows not to make hard bindings to the /tmp directory
Fixes https://github.com/flutter/flutter/issues/87742 …
> [path_provider_linux] Using TMPDIR env as a primary temporary path

- .cirrus.yml
There is a special instruction in Cirrus for that https://cirrus-ci.org/guide/writing-tasks/#background-script-instruction
Might be related to https://github.com/flutter/flutter/issues/90078 …
> [ci] use background script

- .cirrus.yml
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/test/firebase_test_lab_command_test.dart
This PR try migrating firebase test to run in `flutter-cirrus` project, instead of `flutter-infra` project.
Context: b/197632425
> Run firebase test in flutter-cirrus

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/README.md
- packages/image_picker/image_picker/pubspec.yaml
*issues fixed by this PR*
- https://github.com/flutter/flutter/issues/89722 …
> [image_picker] Update README for image_picker's retrieveLostData() to support multiple files

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/example/integration_test/controller_swap_test.dart
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player/pubspec.yaml
When switching to a different `VideoPlayerController` in the `VideoPlayer` widget, the `VideoPlayer.didUpdateWidget` method will try to remove its own listener from the previous controller, which by this point has already been disposed.
Fixes https://github.com/flutter/flutter/issues/90046.
[pub …
> [video_player] Fix a disposed `VideoPlayerController` throwing an exception when being replaced in the `VideoPlayer`

- packages/camera/camera_web/CHANGELOG.md
- packages/camera/camera_web/README.md
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera_web.dart
- packages/camera/camera_web/pubspec.yaml
The camera stream used to request video and audio permissions is now released before accessing available camera devices. This solves a `cameraNotReadable` error thrown when requesting a camera stream that is already in use.
Fixes https://github.com/flutter/flutter/issues/90040. …
> [camera_web] Release the camera stream used to request video and audio permissions

- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/README.md
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
Fixes non-existing URL to the `google_sign_in` package in the web plugin README.
> [google_sign_in_web] Update URL to `google_sign_in` package in README

- packages/quick_actions/quick_actions/CHANGELOG.md
- packages/quick_actions/quick_actions/example/ios/Flutter/AppFrameworkInfo.plist
- packages/quick_actions/quick_actions/example/ios/Runner.xcodeproj/project.pbxproj
- packages/quick_actions/quick_actions/ios/Classes/FLTQuickActionsPlugin.m
- packages/quick_actions/quick_actions/ios/quick_actions.podspec
- packages/quick_actions/quick_actions/pubspec.yaml
Flutter apps run on 2.4.0-0.0.pre and later [will be upgraded to a minimum of iOS 9.0](https://github.com/flutter/flutter/pull/85174).  Now that Flutter 2.5 has hit stable and [iOS 8 support has been dropped](https://flutter.dev/go/rfc-ios8-deprecation), change the plugin minimum iOS version to `9.0`.  
- Bump the Flutter and dart version constraints to 2.5 and 2.14 respectively to enforce that the iOS 9.0 migration has happened on the app side, because an older 8.0 app won't build with a 9.0 plugin.
- Remove `@available(iOS 9.0, *)` checks.
- Remove reference to deprecated `VALID_ARCHS` Xcode build setting.  Confirmed this plugin builds for arm64 simulators.
- Let CocoaPods edit the Xcode project.
Users on Flutter versions lower than the current stable 2.5 will not be able to upgrade …
> [quick_actions] Bump minimum Flutter version and iOS deployment target

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/README.md
- packages/google_maps_flutter/google_maps_flutter/example/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter/ios/google_maps_flutter.podspec
- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Flutter apps run on 2.4.0-0.0.pre and later [will be upgraded to a minimum of iOS 9.0](https://github.com/flutter/flutter/pull/85174).  Now that Flutter 2.5 has hit stable and [iOS 8 support has been dropped](https://flutter.dev/go/rfc-ios8-deprecation), change the plugin minimum iOS version to `9.0`.  
Bump the Flutter and dart version constraints to 2.5 and 2.14 respectively to enforce that the iOS 9.0 migration has happened on the app side, because an older 8.0 app won't build with a 9.0 plugin.  I believe the last time this was done was a few months ago for null safety adoption https://github.com/flutter/plugins/pull/3324 (there's recent precedent).
Users on Flutter versions lower than the current stable 2.5 will not be able to upgrade this plugin past this version. …
> [google_maps_flutter] Bump minimum Flutter version and iOS deployment target

- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart
- packages/camera/camera_platform_interface/lib/src/types/resolution_preset.dart
- packages/camera/camera_platform_interface/pubspec.yaml
This PR is the platform_interface part of: https://github.com/flutter/plugins/pull/4240.
```
git cherry-pick 52b8608f61f230ba89ef0e4acbfee0e0f6cce47b
git cherry-pick ad5057472e07df63604489ec344c6a47d2de02a5
```
It adds information relevant to the web to the platform interface docs.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-bre …
> [camera_platform_interface] Add web-relevant docs

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/camera/camera/pubspec.yaml
This iOS 9.0 availability check should have been removed as part of https://github.com/flutter/plugins/pull/4327.  It is no longer needed now that the minimum iOS version is 9.0.
Part of flutter/flutter#84198
> [camera] Remove iOS 9 availability check around ultra high capture sessions

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/sku_details_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/sku_details_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/sku_details_wrapper_test.dart
Due to a typo the `SkuDetailsWrapper.introductoryPriceMicros` field wasn't populated correctly with the values send from the native side. 
The first [commit](https://github.com/flutter/plugins/commit/1b1ec27222107eee976faae18476bf088502b1d0) of this PR updates the existing unit tests to prove the existence of the issue. The second [commit](https://github.com/flutter/plugins/commit/77e2c6ddaae95600b1b93f9d51350fb155a045f9) fixes the implementation of the `SkuDetailsWrapper` class so the tests succeed and populate the field correctly.
Fixes flutter/flutter#90244 …
> [in_app_purchase] Ensure the `introductoryPriceMicros` field is populated correctly.

- packages/camera/camera_web/AUTHORS
- packages/in_app_purchase/in_app_purchase_android/AUTHORS
- packages/in_app_purchase/in_app_purchase_ios/AUTHORS
- packages/in_app_purchase/in_app_purchase_platform_interface/AUTHORS
- packages/quick_actions/quick_actions/AUTHORS
- packages/quick_actions/quick_actions_platform_interface/AUTHORS
- script/tool/CHANGELOG.md
- script/tool/lib/src/publish_check_command.dart
- script/tool/test/list_command_test.dart
- script/tool/test/publish_check_command_test.dart
- script/tool/test/util.dart
Adds a check to `publish-check` that there is an AUTHORS file present,
since our license refers to "The Flutter Authors", so we want to have a
file distributed with each package that says who the AUTHORS are (vs.
just having a top-level repo AUTHORS file, which is not part of package
distribution).
Adds AUTHORS files to packages that have been created since the
earlier one-time fix that added them, but didn't add a check to prevent
future issues.
Also updates the `publish-check` failure tests to include checks for
specific output so that we know that they are failing for the reasons
the test is expecting, bringing them up to current repo standards for
failure tests.
Fixes flutter/flutter#89680
[Tree …
> Require authors file

- packages/camera/camera_web/CHANGELOG.md
- packages/camera/camera_web/README.md
- packages/camera/camera_web/pubspec.yaml
The usage documentation of `camera_web` was updated as the package has been endorsed.
> [camera_web] Update usage documentation

- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
- packages/google_sign_in/google_sign_in/pubspec.yaml
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/test/pubspec_check_command_test.dart
Updates plugins to pass the new publish check against leaking secrets, and adds the new `false_secrets` section to the enforced section ordering in the tool. This prevents future unrelated failures when trying to publish these plugins.
Fixes https://github.com/flutter/flutter/issues/90477
[pub …
> Add false secret lists, and enforce ordering

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/README.md
- packages/google_sign_in/google_sign_in/example/pubspec.yaml
- packages/google_sign_in/google_sign_in/ios/google_sign_in.podspec
- packages/google_sign_in/google_sign_in/pubspec.yaml
Flutter apps run on 2.4.0-0.0.pre and later [will be upgraded to a minimum of iOS 9.0](https://github.com/flutter/flutter/pull/85174).  Now that Flutter 2.5 has hit stable and [iOS 8 support has been dropped](https://flutter.dev/go/rfc-ios8-deprecation), change the plugin minimum iOS version to `9.0`.  
Bump the Flutter and dart version constraints to 2.5 and 2.14 respectively to enforce that the iOS 9.0 migration has happened on the app side, because an older 8.0 app won't build with a 9.0 plugin.  I believe the last time this was done was a few months ago for null safety adoption https://github.com/flutter/plugins/pull/3324 (there's recent precedent).
Users on Flutter versions lower than the current stable 2.5 will not be able to upgrade this plugin past this version.  
google_sign_in …
> [google_sign_in] Bump minimum Flutter version and iOS deployment target

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/lib/url_launcher.dart
- packages/url_launcher/url_launcher/pubspec.yaml
- packages/url_launcher/url_launcher/test/url_launcher_test.dart
Uri.parse cannot parse some app scheme URLs.
Use try-catch to handle errors. …
> [url_launcher] Error handling when URL cannot be parsed with Uri.parse

- script/tool/CHANGELOG.md
- script/tool/lib/src/version_check_command.dart
- script/tool/test/version_check_command_test.dart
Catches invalid CHANGELOG formats and logs useful error messages for them,
rather than throwing FormatExceptions.
> [flutter_plugin_tools] Improve version check error handling

- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/events/map_event.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/method_channel/method_channel_google_maps_flutter.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_flutter_platform.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/marker.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/method_channel/method_channel_google_maps_flutter_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/types/marker_test.dart
Add events to track start of drag and position during drag to platform interface
Implementation in PR: https://github.com/flutter/plugins/pull/2838
https://github.com/flutter/flutter/issues/26117
> [google_maps_flutter] Marker dragging events

- packages/cross_file/analysis_options.yaml
- packages/flutter_plugin_android_lifecycle/analysis_options.yaml
- packages/flutter_plugin_android_lifecycle/example/integration_test/flutter_plugin_android_lifecycle_test.dart
- packages/flutter_plugin_android_lifecycle/example/lib/main.dart
- packages/flutter_plugin_android_lifecycle/example/pubspec.yaml
- packages/plugin_platform_interface/analysis_options.yaml
- packages/plugin_platform_interface/pubspec.yaml
- packages/plugin_platform_interface/test/plugin_platform_interface_test.dart
- script/configs/custom_analysis.yaml
Remove a few of the trivial-to-fix legacy analysis option files that were bulk added in the transition to matching flutter/flutter's analysis options. …
> Remove some trivial custom analysis options files

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
Tests that load https://www.google.com and then assert that that's the
current URL are failing, because Google is redirecting our tests to a
"suspicious activity" page. Switch to example.com, as a domain that is
less likely to do traffic-based redirection. …
> [webview_flutter] Adjust integration test domains

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/enum_converters.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/enum_converters.g.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/sku_details_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/enum_converters.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/enum_converters.g.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_payment_transaction_wrappers.g.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_product_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_storefront_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
Regenerate output
Also put in a pointer to the json_serializable issue related to creating
stand-alone enum converters
> [in_app_purchase] Bump dependencies on json_serializable, build_runner

- .cirrus.yml
Temporary run the publish task on the Flutter stable channel as the
current master channel is experiencing a bug (see
https://github.com/dart-lang/pub/issues/3152).
dart-lang/pub#3152
- This is a change to the CI configuration to move tree back to green and doesn't require plugin to be published.
- This is a change to the CI configuration to move tree back to green and doesn't require plugin to be published.
[relevant …
> [ci] Temporary run publish task on Flutter stable channel.

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/android/build.gradle
- packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java
- packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
- packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/MethodCallHandlerImpl.java
- packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/CameraTest.java
- packages/camera/camera/android/src/test/java/io/flutter/plugins/camera/MethodCallHandlerImplTest.java
- packages/camera/camera/pubspec.yaml
This PR removes the lifecycle hooks from the Android implementation. I have a feeling these were added by accident during the recent refactor, as the example app already [puts this responsibility on the user of the plugin](https://github.com/flutter/plugins/blob/master/packages/camera/camera/example/lib/main.dart#L116). 
This is also described in the readme: https://github.com/flutter/plugins/tree/master/packages/camera/camera#handling-lifecycle-states
This should fix the issue with the IllegalStateException being thrown when switching to a different activity, for example when using `camera` in combination with `image_picker`, as can be seen in the issue linked below:
Relevant issues:
- Fixes flutter/flutter#89352
- Fixes flutter/flutter#89815
- Fixes flutter/flutter#89431
- No new public …
> [camera] Fix IllegalStateException being thrown in Android implementation when switching activities.

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/example/lib/main.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
Make sure the navigation controls in the example App are loaded immediately, but only enable when the WebViewController is available. This is the same behaviour as in the example App from the main webview_flutter package.
Related to issue flutter/flutter#90597 …
> [webview_flutter_android] Load example App's navigation controls immediately.

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
This was already done in the example app for Android.
Related issue:
- flutter/flutter#89950
> [in_app_purchase] Handle restored purchases in iOS example app

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
Make sure purchases that arrive on the `InAppPurchase.purchaseStream`
with the status `PurchaseStatus.restored` are handled correctly.
Related issue: flutter/flutter#89950
> [in_app_purchase] Handle `PurchaseStatus.restored` correctly in example.

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
Added the Overrides since the pr on which it was depending has landed to stable 
*List which issues are fixed by this PR.*
[#90939](https://github.com/flutter/flutter/issues/90939) …
> [webview_flutter] Fixed todos in FlutterWebView.java

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/pubspec.yaml
- packages/espresso/CHANGELOG.md
- packages/espresso/pubspec.yaml
- packages/file_selector/file_selector/CHANGELOG.md
- packages/file_selector/file_selector/pubspec.yaml
- packages/plugin_platform_interface/CHANGELOG.md
- packages/plugin_platform_interface/pubspec.yaml
- packages/wifi_info_flutter/wifi_info_flutter/CHANGELOG.md
- packages/wifi_info_flutter/wifi_info_flutter/pubspec.yaml
- script/tool/CHANGELOG.md
- script/tool/lib/src/common/repository_package.dart
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/test/common/repository_package_test.dart
- script/tool/test/pubspec_check_command_test.dart
pub.dev deducts points for having a pubspec.yaml `description` that is too short or too long; several of our plugins are losing points on this. To ensure that we are following—and modeling—best practices, this adds a check that our `description` fields meet pub.dev expectations.
Fixes our existing violations. Two are not published even though this only takes effect once published:
- camera: We change this plugin pretty frequently, so this should go out soon without adding a release just for this trivial issue.
- wifi_info_flutter: This is deprecated, so we don't plan to release it. It has to be fixed to allow the tool change to land though. …
> [flutter_plugin_tools] Validate pubspec description

- packages/file_selector/file_selector_platform_interface/test/file_selector_platform_interface_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/platform_interface/google_maps_flutter_platform_test.dart
- packages/google_sign_in/google_sign_in_platform_interface/test/google_sign_in_platform_interface_test.dart
- packages/quick_actions/quick_actions_platform_interface/test/quick_actions_platform_interface_test.dart
- packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart
- packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
Fixes all instance of an anti-pattern that was cloned among many of our
platform interfaces, where one test asserts that the static instance is
of a specific class, but other tests change that static instance, such
that the initial test fails if not run first.
Fixes https://github.com/flutter/flutter/issues/52690
Fixes https://github.com/flutter/flutter/issues/52689
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-brea …
> Fix order-dependant platform interface tests

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/method_channel/webview_method_channel.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/web_settings.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/src/method_channel/webview_method_channel_test.dart
Since `webview_flutter` was recently updated to be a Federated Plugin, this PR is part of the [instructions on changing Federated Plugins](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins). 
This is the first-step task to add a `zoomEnabled` param on the `WebView` widget.
If this is approved, merged, and published, it will be fast-followed by two other small PRs updating `webview_flutter_wkwebview` and `webview_flutter_android`.
I have been maintaining https://github.com/flutter/plugins/pull/3325 for a decent chunk of time and I'm hoping following these new Federated plugin guidelines can get this puppy over the finish line and we can get off our Forked version of this plugin.
*List which issues are fixed by this PR. You must list at …
> [webview_flutter] Add zoomEnabled to webview flutter platform interface

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/android/build.gradle
- packages/android_intent/CHANGELOG.md
- packages/android_intent/android/build.gradle
- packages/connectivity/connectivity/CHANGELOG.md
- packages/connectivity/connectivity/android/build.gradle
Now that the default Flutter app template uses a newer compile SDK on Android, the build_all test (which generates an application) is subject to new out-of-band deprecation warnings. For plugins with `-Werror` specified, these are errors, which break CI.
To prevent this, remove `-Werror` from the Android builds of all the deprecated plugins that used it. …
> Remove -Werror from deprecated plugin Android builds

- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
Adds a pedantic dependency to in_app_purchase_android and in_app_purchase_ios
Fixes https://github.com/flutter/flutter/issues/92983
This has no effect on users as it is only a dev dependency. …
> [in_app_purchase] add pedantic as a dependency to in_app_purchase plugins

- packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerUITests/GoogleMapsUITests.m
Temporarily disables the only XCUITest for Maps until the cause of
https://github.com/flutter/flutter/issues/93325 is found and fixed, in
order to re-open the tree. …
> [google_maps_flutter] Disable XCUITest

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player/pubspec.yaml
- packages/video_player/video_player/test/video_player_test.dart
Fixes a regression introduced by #3727 where scrubbing a progress
indicator to the end of the video while playing would unexpectedly
restart playback from the start of the video. Restarting is an
intentional behavior under the assumption that `play` is called for a
deliberate user action to start playback, but in the case of scrubbing
it is a programatic pause/play pair where the decision to call `play`
again should account for scrubbing to the end.
Fixes https://github.com/flutter/flutter/issues/92658 …
> [video_player] Don't restart when scrubbing to end

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/plugin_command.dart
- script/tool/lib/src/test_command.dart
- script/tool/lib/src/version_check_command.dart
- script/tool/pubspec.yaml
- script/tool/test/analyze_command_test.dart
- script/tool/test/common/plugin_command_test.dart
- script/tool/test/pubspec_check_command_test.dart
- script/tool/test/version_check_command_test.dart
Treat `main` the same as `master` for branch-based switching, in
preparation for switching the branch names in Flutter repositories.
Also updates all of the tests that used `master` as the explicit base to
use `main` instead; what the tests use is arbitrary, so they can be
switched now even though the repo itself hasn't switched.
Part of https://github.com/flutter/flutter/issues/90476 …
> [flutter_plugin_tools] Add 'main' support

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/ios/Runner.xcodeproj/project.pbxproj
- packages/webview_flutter/webview_flutter_wkwebview/example/ios/RunnerTests/FLTWebViewTests.m
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/main.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/web_view.dart
- packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FlutterWebView.h
- packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FlutterWebView.m
- packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FlutterWebView.modulemap
- packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FlutterWebView_Test.h
- packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/webview-umbrella.h
- packages/webview_flutter/webview_flutter_wkwebview/ios/webview_flutter_wkwebview.podspec
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
This PR is a partial resubmission of my colleague's PR: #4169. 
It implements the `loadRequest` method added in #4450 for the iOS package.
Related issue:
- flutter/flutter#27730
> [webview_flutter] Implement loadRequest in iOS package.

- packages/package_info/CHANGELOG.md
- packages/package_info/example/android/app/build.gradle
Bumps package_info example app compileSdkVersion to 30 to match highest compileSdkVersion of dependencies.
> [package_info] Bump SDK version of example app

- packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerUITests/GoogleMapsUITests.m
- packages/google_maps_flutter/google_maps_flutter/example/lib/map_click.dart
This PR adds 2 new XCUITests that doesn't require permissions.
Due to some issue with the permission popup in XCUITests, the only test in the plugin was disable. This leaves the plugin untested. This PR won't fix the permission popup issue, but can at least provide some tests for the plugin.
related to: https://github.com/flutter/flutter/issues/93325 …
> [google_maps_flutter] Add new XCUITests that do not require permissions.

- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/lib/src/webview.dart
- packages/webview_flutter/webview_flutter/pubspec.yaml
This is a follow-up PR to https://github.com/flutter/plugins/pull/3325. After updating our repo to use version 3.2.0, I realized that in order to actually **disable** zoom on iOS, we have to set  `javascriptMode: JavascriptMode.unrestricted` as iOS uses javascript to disable zoom.
This PR just updates the documentation to reflect this.
https://github.com/flutter/flutter/issues/75196 …
> [webview_flutter] Update webview_flutter documentation

- .ci.yaml
Creates `main` versions of the existing `master` CI builders, as the
first half of switching LUCI tests over to the `main` branch.
Part of https://github.com/flutter/flutter/issues/90476 …
> [ci] Add 'main' builders in bringup mode

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java
- packages/url_launcher/url_launcher/android/src/test/java/io/flutter/plugins/urllauncher/WebViewActivityTest.java
- packages/url_launcher/url_launcher/pubspec.yaml
Adds null check for extracting browser headers.
Fixes https://github.com/flutter/flutter/issues/72863
> [url_launcher] Add null check for extracting browser headers

- .github/PULL_REQUEST_TEMPLATE.md
Links to the newly-documented standard style for CHANGELOG updates. …
> Add link to CHANGELOG style in PR template

- packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
PR #4458 was merged without having the version updated and the functionality is now published as part of in_app_purchase_ios version 0.2.0 (that was release with PR #4094). 
This PR adds a belated correction to version 0.2.0 in the CHANGELOG to ensure the changes made in #4458 don't go undocumented.
- Only a documentation change in the CHANGELOG.md and a corresponding version bump in pubspec.yaml. So no new tests were added. …
> [in_app_purchase] Fix CHANGELOG for 0.2.0.

- .ci.yaml
Reverts flutter/plugins#4473
That PR was a silly mistake; `channel` here isn't the flutter/plugins branch, it's the Flutter (flutter/flutter) channel. So this wasn't at all testing what I meant to test; these builders aren't useful.
> Revert "[ci] Add 'main' builders in bringup mode"

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/method_channel/webview_method_channel.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_interface/webview_platform_callbacks_handler.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/src/method_channel/webview_method_channel_test.dart
Reverts https://github.com/flutter/plugins/pull/4509, which is ecosystem-breaking since it adds a new method to the interface that no existing code implements.
Note that while this PR is technically a breaking change, it is deliberately versioned as a non-breaking change so that people will automatically pick up the fix for the previous accidentally-breaking change. (In practice, this revert would only breaking if someone implemented this new method in an unendorsed webview implementation sometime in the last ~12 hours that the change was live). …
> [webview_flutter] Revert addition of onUrlChanged

- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
The test 'can open new window and go back' periodically times out on
iOS, often for all runs that happen within a certain period. This is
flaking often enough to have a noticable effect on tree greenness, so is
being disabled until we can investigate further.
While changing the skip logic in this file, removes logic and comments related
to an Android-only issue that was copied over during the federation of the
plugin (set to false during the copy to make it a no-op).
See https://github.com/flutter/flutter/issues/90976
[CLA]: …
> [webview_flutter] Disable flaky test on iOS

- packages/shared_preferences/shared_preferences/CHANGELOG.md
- packages/shared_preferences/shared_preferences/pubspec.yaml
Restores the app-facing package to publishable state, pointing at the
newly-published federated Android and iOS implementation packages.
Part of Part of flutter/flutter#68498 …
> [shared_preferences] Publish fully federated version

- packages/flutter_plugin_android_lifecycle/CHANGELOG.md
- packages/flutter_plugin_android_lifecycle/android/build.gradle
- packages/flutter_plugin_android_lifecycle/pubspec.yaml
- packages/path_provider/path_provider_android/CHANGELOG.md
- packages/path_provider/path_provider_android/android/build.gradle
- packages/path_provider/path_provider_android/pubspec.yaml
- packages/shared_preferences/shared_preferences_android/CHANGELOG.md
- packages/shared_preferences/shared_preferences_android/android/build.gradle
- packages/shared_preferences/shared_preferences_android/example/android/app/build.gradle
- packages/shared_preferences/shared_preferences_android/pubspec.yaml
Precursor to https://github.com/flutter/plugins/pull/4533
On master channel, plugin unit tests must now build with SDK version 31.
These plugins are transitive dependencies of other plugins' examples,
which causes unit test failures in those plugins's unit test builds, so
these need to be landed and publish in order for that PR to pass
presubmit. …
> Update some plugins' targetSdkVersions to 31

- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
The getTitle test has been flaking on iOS, for reasons that are not
clear. This is a highly speculative attempted fix, in case the issue is
that the futere is completing too early (e.g., if 'about:blank' is
triggering a completion).
Fixes https://github.com/flutter/flutter/issues/94117
[pub …
> [webview_flutter] Adjust getTitle test

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
Attempts to fix the getTitle flake by running JS before accessing the
title, to force the page to be fully processed by the native code.
No CHANGELOG change: Description would be the same as something that is
already in the NEXT section.
Speculative fix for https://github.com/flutter/flutter/issues/94117
[Discord]: …
> [webview_flutter] Speculative getTitle fix

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/analysis_options.yaml
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/main.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/navigation_request.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/web_view.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/pubspec.yaml
- script/configs/custom_analysis.yaml
Migrates the webview_flutter_wkwebview package from using `analysis_options_legacy.yaml` to the more strict `analysis_options.yaml`.
No version change: only updates to the more strict analysis_options.yaml and doesn't make any functional changes that would require a new version to be published. I added a line to the already existing "NEXT" section of the CHANGELOG.md.
Related to flutter/flutter#76229
> [webview_flutter] Migrate webview_flutter_wkwebview to analysis_options.yaml

- analysis_options.yaml
- analysis_options_legacy.yaml
Excludes files generated by Pigeon and matches the `**/*.pigeon.dart` pattern from static code analysis. 
This change would make it easier to get changes to the webview_flutter_android package passed. It now needs manual editing of the *.pigeon.dart files each time they are generated.
> [ci] Exclude files generated by Pigeon from analysis.

- packages/webview_flutter/webview_flutter_android/example/lib/web_view.dart
- packages/webview_flutter/webview_flutter_android/test/webview_android_widget_test.dart
This will pre-emptively ignore the `prefer_const_constructor` warning to make it possible to migrate the webview_flutter_platform_interface without breaking changes to the more strict analysis_options.yaml (see issue flutter/flutter#76229).
A cleanup issue also exist as a reminder to remove the temporary ignore statements and can be found here: flutter/flutter#94311
No version change: this is a temporary change and only necessary to land on master not to break the build when merging #4549. These changes will be undone as part of flutter/flutter#94311 as soon as #4549 lands.
No CHANGELOG change: this is a temporary change and only necessary to land on master not to break the build when merging #4549. These changes will be undone as part of flutter/flutter#94311 as soon as #4549 lands.
> [webview_flutter] Pre-emptively ignore prefer_const_constructor warning.

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/web_view.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
Updates to the latest version of the webview_flutter_platform_interface and fix one analysis warning caused by this update. This will also fix the tree.
No version change: code changes don't affect client usage and purely ensure code is compliant with new code analysis rules.
> [webview_flutter] Updates webview_flutter_platform_interface to version 1.5.2

- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/analysis_options.yaml
- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter/example/lib/main.dart
- packages/webview_flutter/webview_flutter/example/pubspec.yaml
- packages/webview_flutter/webview_flutter/lib/src/webview.dart
- packages/webview_flutter/webview_flutter/pubspec.yaml
- packages/webview_flutter/webview_flutter/test/webview_flutter_test.dart
- script/configs/custom_analysis.yaml
Removes the legacy analysis options for all `webview_flutter` package, and fixes all resulting violations. Most fixes are automatic `dart fix` changes.
Related to flutter/flutter#76229
No version change: The changes are to code that don't affect clients.
> [webview_flutter] Migrate webview_flutter package to analysis_options.yaml

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_interface/webview_platform.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
Reverts the deprecation of `clearCookies` in the platform interface from #4555, as it broke the tree.
Relevant comment: https://github.com/flutter/plugins/pull/4555#discussion_r761123734
> [webview_flutter] Revert deprecation of clearCookies

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/method_channel/webview_method_channel.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/types/creation_params.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/src/method_channel/webview_method_channel_test.dart
This PR add an option to set a transparent background for the webview.
Original PR (app-facing package, iOS, Android, platform interface): https://github.com/flutter/plugins/pull/3431
Part of https://github.com/flutter/flutter/issues/29300
[Discord]: …
> [webview_flutter] Add a backgroundColor option to the webview platform interface

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/method_channel/webview_method_channel.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_interface/webview_platform_controller.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/src/method_channel/webview_method_channel_test.dart
Adds the `loadFlutterAsset` method to the platform interface. This method, when implemented, is responsible for correctly loading HTML content that  is part of the Flutter asset bundle.
flutter/flutter#27086
> [webview_flutter] Adds the `loadFlutterAsset` method to the interface.

- packages/path_provider/path_provider_macos/CHANGELOG.md
- packages/path_provider/path_provider_macos/lib/path_provider_macos.dart
- packages/path_provider/path_provider_macos/macos/Classes/PathProviderPlugin.swift
- packages/path_provider/path_provider_macos/pubspec.yaml
- packages/path_provider/path_provider_macos/test/path_provider_macos_test.dart
Eliminates the path_provider_macos reliance on the default, shared method channel implementation, in favor of an in-package implementation.
Now that it's trivial to do so, also moves the creation of directories when necessary to the Dart side, and unit tests it there.
Part of https://github.com/flutter/flutter/issues/94224
[Discord]: …
> [path_provider] Switch macOS to an internal method channel

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/ios/RunnerUITests/FLTWebViewUITests.m
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/main.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/lib/web_view.dart
- packages/webview_flutter/webview_flutter_wkwebview/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FlutterWebView.m
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
This PR add an option to set the background color of the iOS webview.
Original PR :
https://github.com/flutter/plugins/pull/3431
It fixes this issue :
https://github.com/flutter/flutter/issues/29300
[pub …
> [webview_flutter] Add a backgroundColor option to the iOS webview

- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/example/assets/www/index.html
- packages/webview_flutter/webview_flutter/example/assets/www/styles/style.css
- packages/webview_flutter/webview_flutter/example/lib/main.dart
- packages/webview_flutter/webview_flutter/example/pubspec.yaml
- packages/webview_flutter/webview_flutter/lib/src/webview.dart
- packages/webview_flutter/webview_flutter/pubspec.yaml
- packages/webview_flutter/webview_flutter/test/webview_flutter_test.dart
Adds app facing implementation of the `loadFlutterAsset` method.
~~DRAFT: waiting for #4582 to land and be published. Afterwards the dependency on webview_flutter_wkwebview needs to be updated.~~
Resolves flutter/flutter#27086
> [webview_flutter] Implements the loadFlutterAsset in the app facing package.

- packages/path_provider/path_provider/CHANGELOG.md
- packages/path_provider/path_provider/lib/path_provider.dart
- packages/path_provider/path_provider/pubspec.yaml
The plugin requires Flutter 2.5, which supports auto-registration of
Dart implementation code in platform packages, and the packages already
do auto-registration. This registration is therefore not needed, so can be
removed.
[exempt …
> [path_provider] Remove platform registration

- packages/shared_preferences/shared_preferences/CHANGELOG.md
- packages/shared_preferences/shared_preferences/lib/shared_preferences.dart
- packages/shared_preferences/shared_preferences/pubspec.yaml
The plugin requires Flutter 2.5, which supports auto-registration of
Dart implementation code in platform packages, and the packages already
do auto-registration. This registration is unused, so can be removed.
Fixes https://github.com/flutter/flutter/issues/81421 …
> [shared_preferences] Remove platform registration

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FlutterWebView.h
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
This PR changes the import of `FLTCookieManager.h` in `FlutterWebView.h` to a relative import, to hopefully fix it picking up the header across modules. 
@stuartmorgan I cannot reproduce the problem in the issue below, but I'm assuming this is the correct fix. Would you please be able to verify?
Related issue:
- flutter/flutter#94903
- Only an import change.
- Only an import change. …
> [webview_flutter] Change import of FLTCookieManager.h to relative import

- packages/camera/analysis_options.yaml
- packages/camera/camera/analysis_options.yaml
- packages/camera/camera_platform_interface/analysis_options.yaml
- packages/camera/camera_web/analysis_options.yaml
- packages/camera/camera_web/pubspec.yaml
- packages/google_maps_flutter/analysis_options.yaml
- packages/google_maps_flutter/google_maps_flutter/analysis_options.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/analysis_options.yaml
- packages/google_maps_flutter/google_maps_flutter_web/analysis_options.yaml
- packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml
- packages/google_sign_in/analysis_options.yaml
- packages/google_sign_in/google_sign_in/analysis_options.yaml
- packages/google_sign_in/google_sign_in_platform_interface/analysis_options.yaml
- packages/google_sign_in/google_sign_in_web/analysis_options.yaml
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
- packages/image_picker/analysis_options.yaml
- packages/image_picker/image_picker/analysis_options.yaml
- packages/image_picker/image_picker_for_web/analysis_options.yaml
- packages/image_picker/image_picker_for_web/pubspec.yaml
- packages/image_picker/image_picker_platform_interface/analysis_options.yaml
- packages/video_player/analysis_options.yaml
- packages/video_player/video_player/analysis_options.yaml
- packages/video_player/video_player_platform_interface/analysis_options.yaml
- packages/video_player/video_player_web/analysis_options.yaml
- packages/video_player/video_player_web/pubspec.yaml
- script/configs/custom_analysis.yaml
When the legacy analysis options were bulk-added to the repository to
allow transitioning incrementally to the Flutter analysis options, they
were added to top-level plugin groups. This makes it harder to migrate
incrementally, and also means that when we add a new sub-package (e.g, a
web or desktop implementation) it's automatically using the legacy
options.
This moves all the legacy option files into each individual package, and
updates the allow list for the tool accordingly, so that migration can
be done package by package.
No version change: Only affects development
No CHANGELOG change: no conceptual change that's interesting to document, since the analysis options for all plugins are still the same. …
> Move custom analysis options into sub-packages

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_test.dart
This PR is for updating the bug of upgrading subscription by deferred mode on android, the purchaseStream of PurchaseStatus will return error.
Related issues:
Fixes [flutter/flutter#94439] …
> [in_app_purchase] Fix upgrading subscription by deferred proration mode on android.

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/README.md
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
This will resolve flutter/flutter#93837 & this work is just the follow-up from #4527 PR.
We need to update the documentation in the README.md of the in_app_purchase package to remove the instruction of initialization with the deprecated `InAppPurchaseAndroidPlatformAddition.enablePendingPurchases` method.
Fixes https://github.com/flutter/flutter/issues/94977
[breaking …
> [in_app-purchase] Updated the ReadMe to remove the deprecated `InAppPurchaseAndroidPlatformAddition.enablePendingPurchases ` method

- packages/path_provider/path_provider_linux/CHANGELOG.md
- packages/path_provider/path_provider_linux/lib/src/get_application_id_real.dart
- packages/path_provider/path_provider_linux/pubspec.yaml
- packages/path_provider/path_provider_linux/test/get_application_id_test.dart
The lookup of application ID was handling `null` (Dart null), but not
`nullptr` (Dart representation of a C null pointer), so was throwing an
exception in applications without an application ID.
Refactors the FFI calls into a wrapper so that they can be faked for
unit testing.
This includes the `shared_preferences_linux` example application, so
this fixes tree breakage.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling- …
> [path_provider] Fix handling of null application ID

- script/tool/lib/src/lint_android_command.dart
Fix a typo in tools: lint_android_command
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packa …
> [tools] fix typo in tools

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/example/integration_test/video_player_test.dart
The 'reports buffering status' test was written in an unnecessary complicated way that used pairs of completers and booleans that tracked the same thing, and more importantly had a bug (hidden by the fact that this package is still on legacy analysis options) where the `await` statements weren't actually doing anything, because they were not actually `await`ing futures.
This fixes the lack of awaits—which should fix the flake—and removes the unnecessary booleans.
Fixes https://github.com/flutter/flutter/issues/94775
[CLA]: …
> [video_player] Fix a flaky test

- .cirrus.yml
The old cirrus GCP key expired. We have updated the key in https://github.com/flutter/plugins/pull/4592, but the firebase test lab also needs an update.
> Update firebase test key

- .cirrus.yml
Follow up of https://github.com/flutter/plugins/pull/4615.
Task level key should not be the same as the org level GCP key: https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables.
> update firebase key

- script/tool/CHANGELOG.md
- script/tool/lib/src/firebase_test_lab_command.dart
- script/tool/test/firebase_test_lab_command_test.dart
Currently the flake situation for Firebase Test Lab tests is very bad,
and the task running those tests are some of the slowest tasks in the
CI. Re-running failed tests is slow, manual work that is signficantly
affecting productivity.
There are plans to actually address the flake in the short-to-medium
term, but in the immediate term this will improve the CI situation, as
well as reducing the drag on engineering time that could be spent on the
root causes.
Part of https://github.com/flutter/flutter/issues/95063
[CLA]: …
> [flutter_plugin_tools] Auto-retry failed FTL tests

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/lib/webview_android_widget.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/test/webview_android_widget_test.dart
The `webview_flutter_android` plugin was setting the `UserAgentString` to the default value whenever it was rebuilt. This should only be done when it was rebuilt with a `null` value.
Fixes: https://github.com/flutter/flutter/issues/94847
[Discord]: …
> Prevent setting user agent string to default value on every rebuild

- .cirrus.yml
This task's memory usage is very close to the 4GB limit of the light-workload machines, and sometimes goes over and causes flaky failures.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins …
> [ci] Move Android build-all CI to heavy workload

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/camera/camera/example/ios/RunnerTests/ThreadSafeEventChannelTests.m
- packages/camera/camera/example/ios/RunnerTests/ThreadSafeMethodChannelTests.m
- packages/camera/camera/example/ios/RunnerTests/ThreadSafeTextureRegistryTests.m
- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/camera/camera/ios/Classes/FLTThreadSafeEventChannel.h
- packages/camera/camera/ios/Classes/FLTThreadSafeEventChannel.m
- packages/camera/camera/ios/Classes/FLTThreadSafeMethodChannel.h
- packages/camera/camera/ios/Classes/FLTThreadSafeMethodChannel.m
- packages/camera/camera/ios/Classes/FLTThreadSafeTextureRegistry.h
- packages/camera/camera/ios/Classes/FLTThreadSafeTextureRegistry.m
- packages/camera/camera/ios/Classes/camera-umbrella.h
The engine APIs used in camera plugin are required to be run on platform thread. Some of these APIs have explicit asserts (e.g. `MethodChannel`) and some have warning instructions in documentation (e.g. `TextureRegistry`). However, in camera plugin we are currently calling these APIs in background thread, causing the crash. 
There's already a `FLTThreadSafeFlutterResult` wrapper to invoke `FlutterResult` in main thread. This PR created similar "thread safe wrappers" for `EventChannel`, `MethodChannel` and `TextureRegistry`. 
This PR should fix the crash, but we should start looking into simplifying the threading logic in this plugin when we get time. I also wrote up [some ideas here](https://github.com/flutter/plugins/pull/4619).  
Note that there's a separate crash due to race condition, …
> [camera]Fix crash due to calling engine APIs from background thread

- packages/path_provider/path_provider_android/CHANGELOG.md
- packages/path_provider/path_provider_android/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java
- packages/path_provider/path_provider_android/lib/path_provider_android.dart
- packages/path_provider/path_provider_android/pubspec.yaml
- packages/path_provider/path_provider_android/test/path_provider_android_test.dart
Eliminates the path_provider_android reliance on the default, shared method channel implementation, in favor of an in-package implementation.
Part of https://github.com/flutter/flutter/issues/94224
[pub …
> [path_provider] Switch Android to an internal method channel

- packages/path_provider/path_provider_android/CHANGELOG.md
- packages/path_provider/path_provider_android/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java
- packages/path_provider/path_provider_android/lib/path_provider_android.dart
- packages/path_provider/path_provider_android/pubspec.yaml
- packages/path_provider/path_provider_android/test/path_provider_android_test.dart
PR #4617 added a dependency on Dart auto-registration, but forgot to
bump the SDK requirement to 2.8 (where that feature was introduced for
Android). In order to fix older versions, this restores the previous
channel name so that the implementation here is compatible with the
default method channel registration used by Flutter 2.5 and earlier.
A follow-up will restore the package-specific channel name, but also
change the SDK requirement to >=2.8. This must be published first so
that the last published version that claims 2.5 compatibility actually
works with 2.5.
Fixes https://github.com/flutter/flutter/issues/95706
[relevant style …
> [path_provider] Fix Android compatibility with 2.5

- packages/plugin_platform_interface/CHANGELOG.md
- packages/plugin_platform_interface/lib/plugin_platform_interface.dart
- packages/plugin_platform_interface/pubspec.yaml
- packages/plugin_platform_interface/test/plugin_platform_interface_test.dart
- Introduce `verify`, a more future-proof name. It throws `AssertionError` if `const Object()` used as the instance's token. 
- Soft-deprecate `verifyToken` with a comment. It will actually deprecated in a future release, to avoid breaking tests with this minor change.
- Update documentation for `PlatformInterface` to show new usage of `verify` and other cosmetic fixes.
- Add a test for the new assertion.
Fixes https://github.com/flutter/flutter/issues/96178.
> [plugin_platform_interface] Add a new method `verify` that prevents use of `const Object()` as token.

- .github/workflows/mirror.yml
This is required to be able to close the repo during the default branch
migration.
Bug: https://github.com/flutter/flutter/issues/90476
[exempt …
> Change the token used for mirroring.

- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart
- packages/camera/camera_platform_interface/pubspec.yaml
- packages/file_selector/file_selector_platform_interface/CHANGELOG.md
- packages/file_selector/file_selector_platform_interface/lib/src/platform_interface/file_selector_interface.dart
- packages/file_selector/file_selector_platform_interface/pubspec.yaml
- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_flutter_platform.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/pubspec.yaml
- packages/image_picker/image_picker_platform_interface/CHANGELOG.md
- packages/image_picker/image_picker_platform_interface/lib/src/platform_interface/image_picker_platform.dart
- packages/image_picker/image_picker_platform_interface/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_platform_interface/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_platform_interface/lib/src/in_app_purchase_platform.dart
- packages/in_app_purchase/in_app_purchase_platform_interface/pubspec.yaml
- packages/path_provider/path_provider_platform_interface/CHANGELOG.md
- packages/path_provider/path_provider_platform_interface/lib/path_provider_platform_interface.dart
- packages/path_provider/path_provider_platform_interface/pubspec.yaml
- packages/quick_actions/quick_actions_platform_interface/CHANGELOG.md
- packages/quick_actions/quick_actions_platform_interface/lib/platform_interface/quick_actions_platform.dart
- packages/quick_actions/quick_actions_platform_interface/pubspec.yaml
- packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md
- packages/url_launcher/url_launcher_platform_interface/lib/url_launcher_platform_interface.dart
- packages/url_launcher/url_launcher_platform_interface/pubspec.yaml
- packages/video_player/video_player_platform_interface/CHANGELOG.md
- packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
- packages/video_player/video_player_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_interface/webview_cookie_manager.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
#4640 (reviewed by @stuartmorgan) updated `plugin_plugin_interface` to 2.1.0, soft-deprecating `verifyToken` and introducing its replacement, `verify`.
Now that 2.1.0 has been [published](https://pub.dev/packages/plugin_platform_interface/versions/2.1.0), this PR updates all of the first-party plugins that used `verifyToken` to use `verify` and depend on `^2.1.0`:
- camera
- file_selector
- google_maps_flutter
- image_picker
- in_app_purchase
- path_provider
- quick_actions
- url_launcher
- video_player
- webview_flutter
It is a follow-on fix for https://github.com/flutter/flutter/issues/96178
This PR has no new tests because it's not possible to test; there was no semantic change to the above plugins. They are not using `const Object()` as their token so a test cannot cause the new …
> Update all plugins that use `verifyToken` to use `verify` instead

- packages/plugin_platform_interface/CHANGELOG.md
- packages/plugin_platform_interface/lib/plugin_platform_interface.dart
- packages/plugin_platform_interface/pubspec.yaml
- packages/plugin_platform_interface/test/plugin_platform_interface_test.dart
The new `verify` method worked with `Mock` (since `_instanceToken`
returns a stub function in that case), but not `Fake` or a manual fake
since it was unconditionally accessing `_instanceToken`. This fixes that
new check to be gated behind the `MockPlatformInterfaceMixin` test, and
adds a unit test that covers `Fake` so this can't regress in the future.
Fixes post-publish breakage in the tree. …
> [plugin_platform_interface] Fix 'verify' for Fakes

- CONTRIBUTING.md
The plugins repository is now aligned with normal Flutter review process. There are no longer any open issues with the `backlog` label, and the intent is not to use it going forward due to the issues (bitrot, authors no longer being available, duplication of work) caused by leaving PRs open in limbo for a long period of time.
[Discord]: …
> Remove the PR review section

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/camera/camera/example/ios/RunnerTests/QueueHelperTests.m
- packages/camera/camera/example/ios/RunnerTests/ThreadSafeEventChannelTests.m
- packages/camera/camera/example/ios/RunnerTests/ThreadSafeFlutterResultTests.m
- packages/camera/camera/example/ios/RunnerTests/ThreadSafeMethodChannelTests.m
- packages/camera/camera/example/ios/RunnerTests/ThreadSafeTextureRegistryTests.m
- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/camera/camera/ios/Classes/FLTThreadSafeEventChannel.h
- packages/camera/camera/ios/Classes/FLTThreadSafeEventChannel.m
- packages/camera/camera/ios/Classes/FLTThreadSafeFlutterResult.h
- packages/camera/camera/ios/Classes/FLTThreadSafeFlutterResult.m
- packages/camera/camera/ios/Classes/FLTThreadSafeMethodChannel.h
- packages/camera/camera/ios/Classes/FLTThreadSafeMethodChannel.m
- packages/camera/camera/ios/Classes/FLTThreadSafeTextureRegistry.h
- packages/camera/camera/ios/Classes/FLTThreadSafeTextureRegistry.m
- packages/camera/camera/ios/Classes/QueueHelper.h
- packages/camera/camera/ios/Classes/QueueHelper.m
- packages/camera/camera/ios/Classes/camera-umbrella.h
- packages/camera/camera/pubspec.yaml
This PR is part of a larger project to fix the thread model for iOS camera plugin. The formal proposal can be found [here](https://docs.google.com/document/d/1Znjp-BduXIb1Ix3JOE1YKyJi1Z0d6rB-2q6Lt7j8xSo/edit#)
The engine APIs used in camera plugin are required to be run on platform thread. Some of these APIs have explicit asserts (e.g. MethodChannel) and some have warning instructions in documentation (e.g. TextureRegistry). However, in camera plugin we are currently calling these APIs in background thread, causing the crash.
There's already a FLTThreadSafeFlutterResult wrapper to invoke FlutterResult in main thread. This PR created similar "thread safe wrappers" for EventChannel, MethodChannel and TextureRegistry.
flutter/flutter#94723
flutter/flutter#52578
- [] I updated `pubspec.yaml` …
> [camera]call engine API in main thread to fix a crash

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/ios/Classes/CameraPlugin.m
Rename the queue to be aligned with [the proposal](https://docs.google.com/document/d/1Znjp-BduXIb1Ix3JOE1YKyJi1Z0d6rB-2q6Lt7j8xSo/edit#). 
I am keeping this PR small and only scoped to renaming. 
Since it's just renaming, I think it's exempt from version bump and unit test
Issue: 
https://github.com/flutter/flutter/issues/96429
No version change: Because it's only renaming …
> [camera]rename dispatchQueue to captureSessionQueue

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/example/ios/RunnerTests/VideoPlayerTests.m
- packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m
- packages/video_player/video_player/pubspec.yaml
In https://github.com/flutter/plugins/pull/4438 the `AVPlayerItem` `presentationSize` and `duration` properties are KVO observed, but the observation was not removed when the texture is disposed.  Remove the observer.  
Also clean up a few things in the plugin, like using `BOOL` instead of `bool`, lightweight generics, rename `players` dictionary to the more descriptive `playersByTextureId`, prefer `NS_INLINE` to `static inline`.
Fixes https://github.com/flutter/flutter/issues/96849 …
> [video_player] Remove KVO observer on AVPlayerItem on iOS

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/README.md
- packages/video_player/video_player/pubspec.yaml
Removes the suggestion to just use the strongly-discouraged-by-Apple `NSAllowsArbitraryLoads`, and instead links to Apple's docs about the various options.
This removes the example entirely since there's no one-size-fits-all case; some clients would just need `NSExceptionDomains` (this seems likely to be the more common case?), others `NSAllowsArbitraryLoadsForMedia`, others `NSAllowsArbitraryLoadsForMedia`+` NSAllowsArbitraryLoads` (to support iOS 9). And of course hopefully these days most people are using https and don't need anything at all. Given that the narrowest option that works for someone is the best option, having them actually research the options is the best thing to steer people toward, even if that's not as simple as "copy and paste the following".
Also opportunistically …
> [video_player] Update iOS README section

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera/example/ios/RunnerTests/CameraCaptureSessionQueueRaceConditionTests.m
- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/camera/camera/ios/Classes/CameraPlugin_Test.h
- packages/camera/camera/pubspec.yaml
This PR fixed a crash due to race condition of `_captureSessionQueue` ivar. This kind of race condition is annoying and hard to fix because it takes tons of luck to reproduce (I accidentally touched iPhone's home bar, causing the app to become active and then immediately inactive, forming a race condition). 
**Crash**
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureAudioDataOutput setSampleBufferDelegate:queue:] NULL queue passed'
terminating with uncaught exception of type NSException
```
**Reproduce**
(1) In sample app, start video recording then stop it. 
(2) Swipe home bar just a bit on iPhone X, so the app becomes inactive and immediately regain active. 
(3) Tap the video button again and observe this crash. 
**Root Cause** …
> [camera]fix crash due to race condition in dispatch queue

- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
- script/tool/README.md
No CHANGELOG change: refactoring tests
> [webview_flutter] Remove dependency on flutter.dev and google.com

- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
- packages/camera/camera_platform_interface/pubspec.yaml
- packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart
More details here https://github.com/flutter/flutter/issues/96405. The problem is that we are not using `await` for `invokeMapMethod` in the `MethodChannelCamera.initializeCamera` method:
https://github.com/flutter/plugins/blob/9aca084f4e02b8a887130e3a8cced87fb218cbf0/packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart#L118-L132
The solution to is to asynchronously catch `PlatformException` and passing it to `_completer`.
Fix https://github.com/flutter/flutter/issues/96405 …
> [camera_platform_interface] Fix asynchronous exceptions handling of the `initializeCamera` method

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera/example/ios/RunnerTests/SampleBufferQueueTests.m
- packages/camera/camera/ios/Classes/CameraPlugin.modulemap
- packages/camera/camera/ios/Classes/FLTCam.m
- packages/camera/camera/ios/Classes/FLTCam_Test.h
- packages/camera/camera/pubspec.yaml
As discussed in [the proposal](https://docs.google.com/document/d/1Znjp-BduXIb1Ix3JOE1YKyJi1Z0d6rB-2q6Lt7j8xSo/edit#heading=h.kv8nn0uaxog6): 
> SampleBuffer callback on the session queue
> SampleBuffer callback is triggered whenever a new video frame or a new audio sample is arrived. This callback powers live previews, image streaming and video recording. 
> Currently SampleBuffer callback is invoked on either main queue or session queue. It should always be run on the session queue. 
Issue here: https://github.com/flutter/flutter/issues/96429
[relevant …
> [camera] Sample buffer handling on session queue

- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/example/ios/RunnerTests/VideoPlayerTests.m
The native iOS tests load network resources, so need longer timeouts to
avoid flake. …
> [video_player] Adjust iOS test timeouts

- .cirrus.yml
These tests crash on stable due to
https://github.com/flutter/flutter/issues/96661 now that 2.10 has been
released to stable.
Fixes out-of-band tree closure from the 2.10 release. …
> [ci] Skip Android webview FTL tests on stable

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera/example/ios/RunnerTests/FLTSavePhotoDelegateTests.m
- packages/camera/camera/ios/Classes/CameraPlugin.modulemap
- packages/camera/camera/ios/Classes/FLTCam.m
- packages/camera/camera/ios/Classes/FLTSavePhotoDelegate.h
- packages/camera/camera/ios/Classes/FLTSavePhotoDelegate.m
- packages/camera/camera/ios/Classes/FLTSavePhotoDelegate_Test.h
- packages/camera/camera/ios/Classes/camera-umbrella.h
- packages/camera/camera/pubspec.yaml
Writing photo files on background queue. A performance improvement similar to the previous PR that moves sample buffer handling to capture session queue. 
Very interesting learning related to mocking NSData: It turned out that we can't `OCMClassMock` NSData because XCTest infrastructure itself uses NSData (e.g. `XCTRunnerIDESession::logDebugMessage:`), which runs on a private queue (`com.apple.dt.xctest.default-debug-log-handler`). The race condition is pretty common and makes the test very fragile. Took me a while to debug. 
Issue: 
https://github.com/flutter/flutter/issues/96429 …
> [camera]writing file on background queue

- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/example/ios/Runner.xcodeproj/project.pbxproj
- packages/video_player/video_player_avfoundation/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/video_player/video_player_avfoundation/example/ios/RunnerTests/VideoPlayerTests.m
- packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
- packages/video_player/video_player_avfoundation/pubspec.yaml
flutter/plugins#4639 introduced playing audio-only files with `video_player`, detected with `[asset tracksWithMediaType:AVMediaTypeVideo]`.  Unfortunately HTTPS Live Streaming files (m3u8) are video files, but never load tracks.  Allow initialization of "video" files with no tracks of any kind, `AVMediaTypeVideo` or otherwise.
Fixes https://github.com/flutter/flutter/issues/97206
Test with https://github.com/flutter/assets-for-api-docs/pull/178
[CLA]: …
> [video_player] Wait to initialize m3u8 videos on iOS until size is set

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/example/ios/Runner.xcodeproj/project.pbxproj
- packages/image_picker/image_picker/example/ios/RunnerTests/PhotoAssetUtilTests.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerImageUtil.h
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerImageUtil.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m
- packages/image_picker/image_picker/ios/Classes/FLTPHPickerSaveImageToPathOperation.m
- packages/image_picker/image_picker/pubspec.yaml
Instead of assigning NSNull to NSNumber ivars, which is a type violation
that requires confusing and error-prone code elsewhere, convert to nil
before assignment. …
> [image_picker] Fix NSNull handling on iOS

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/ios/RunnerTests/CameraOrientationTests.m
- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/camera/camera/ios/Classes/CameraPlugin_Test.h
- packages/camera/camera/pubspec.yaml
This PR moves iOS camera's orientation updates to the session queue.
As discussed in [the proposal](https://docs.google.com/document/d/1Znjp-BduXIb1Ix3JOE1YKyJi1Z0d6rB-2q6Lt7j8xSo/edit#) under "Overview" section: 
> **Session queue**: handles all camera operations, including capture session setup, sample buffer processing, camera state management (for example, isRecording, isStreamingImages)
and under the list of violation of the "Thread safety for state access" section: 
> Multiple orientation related states are mutated in both session queue and main queue
Issue here: https://github.com/flutter/flutter/issues/96429 …
> [camera]manages ios camera's orientation states on capture session queue

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/example/ios/RunnerTests/ImagePickerPluginTests.m
- packages/image_picker/image_picker/example/ios/RunnerTests/ImageUtilTests.m
- packages/image_picker/image_picker/example/ios/RunnerTests/MetaDataUtilTests.m
- packages/image_picker/image_picker/example/ios/RunnerTests/PhotoAssetUtilTests.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin.m
- packages/image_picker/image_picker/ios/Classes/FLTImagePickerPlugin_Test.h
- packages/image_picker/image_picker/ios/Classes/ImagePickerPlugin.modulemap
- packages/image_picker/image_picker/ios/Classes/image_picker-umbrella.h
- packages/image_picker/image_picker/ios/image_picker.podspec
- packages/image_picker/image_picker/pubspec.yaml
Refactored the existing unit tests to expose private interfaces in a separate test header instead of an inline interface. This was first introduced in the google_sign_in plugin (#4157) and after that also applied in the camera plugin (#4426) and the webview_flutter plugin (#4480).
I have moved this refactoring out of the changes I am working on for issue flutter/flutter#96903 and PR #4718.
> [image_picker] Refactored tests to expose private interface in separate test header.

- packages/shared_preferences/shared_preferences/test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences_android/CHANGELOG.md
- packages/shared_preferences/shared_preferences_android/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java
- packages/shared_preferences/shared_preferences_android/lib/shared_preferences_android.dart
- packages/shared_preferences/shared_preferences_android/pubspec.yaml
- packages/shared_preferences/shared_preferences_android/test/shared_preferences_android_test.dart
- packages/shared_preferences/shared_preferences_ios/CHANGELOG.md
- packages/shared_preferences/shared_preferences_ios/ios/Classes/FLTSharedPreferencesPlugin.m
- packages/shared_preferences/shared_preferences_ios/lib/shared_preferences_ios.dart
- packages/shared_preferences/shared_preferences_ios/pubspec.yaml
- packages/shared_preferences/shared_preferences_ios/test/shared_preferences_ios_test.dart
- packages/shared_preferences/shared_preferences_linux/CHANGELOG.md
- packages/shared_preferences/shared_preferences_linux/example/integration_test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences_linux/example/lib/main.dart
- packages/shared_preferences/shared_preferences_linux/lib/shared_preferences_linux.dart
- packages/shared_preferences/shared_preferences_linux/pubspec.yaml
- packages/shared_preferences/shared_preferences_linux/test/shared_preferences_linux_test.dart
- packages/shared_preferences/shared_preferences_macos/CHANGELOG.md
- packages/shared_preferences/shared_preferences_macos/lib/shared_preferences_macos.dart
- packages/shared_preferences/shared_preferences_macos/macos/Classes/SharedPreferencesPlugin.swift
- packages/shared_preferences/shared_preferences_macos/pubspec.yaml
- packages/shared_preferences/shared_preferences_macos/test/shared_preferences_macos_test.dart
- packages/shared_preferences/shared_preferences_windows/CHANGELOG.md
- packages/shared_preferences/shared_preferences_windows/example/integration_test/shared_preferences_test.dart
- packages/shared_preferences/shared_preferences_windows/example/lib/main.dart
- packages/shared_preferences/shared_preferences_windows/lib/shared_preferences_windows.dart
- packages/shared_preferences/shared_preferences_windows/pubspec.yaml
This PR eliminates the use of the shared method channel implementation in each of the native packages for the shared_preferences plugin.
This PR's contents are based on the steps outlined in the following issue: 
- flutter/flutter#94224
No CHANGELOG change: The main package only has one of its tests changed.
> [shared_preferences] Move away from shared method channel implementation in native packages.

- packages/url_launcher/url_launcher_linux/CHANGELOG.md
- packages/url_launcher/url_launcher_linux/pubspec.yaml
- packages/url_launcher/url_launcher_macos/CHANGELOG.md
- packages/url_launcher/url_launcher_macos/pubspec.yaml
- packages/url_launcher/url_launcher_windows/CHANGELOG.md
- packages/url_launcher/url_launcher_windows/pubspec.yaml
https://github.com/flutter/plugins/pull/4719 converted the url_launcher implementations to Dart-based versions. This should have been completely transparent to clients, but there is a latent bug in `url_launcher` where the `default_package` entries for Linux, macOS, and Windows are incorrect. This went unnoticed until now because currently the only client-facing effect of `default_package` is in resolving which implementation to run Dart registration for. Because of the typos in the `default_package` entries, the resolution in the `flutter` tool doesn't recognize the registration for these packages as needing to run, causing them to be broken at runtime.
The affected versions have been retracted to fix the breakage in the short term. This is PR is the first half of the long-term fix; it …
> [url_launcher] Major version bump for desktop Dart-based url_launcher implementations

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/ios/Runner/main.m
I noticed that during unit tests there are some code in app delegate that eventually setup the FLTCam in background thread, which runs concurrently with normal unit tests in main thread, making breakpoint a bit confusing when debugging. 
This PR skips unnecessary `didFinishLaunching` setups for unit tests. 
No version change: only affect Runner app's unit tests. 
No unit tests: I don't think OCMock supports stubbing global functions. Just manually tested.  …
> [camera]skip app delegate during unit test

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/analysis_options.yaml
- packages/camera/camera/example/integration_test/camera_test.dart
- packages/camera/camera/example/lib/main.dart
- packages/camera/camera/example/pubspec.yaml
- packages/camera/camera/example/test_driver/integration_test.dart
- packages/camera/camera/lib/camera.dart
- packages/camera/camera/lib/src/camera_controller.dart
- packages/camera/camera/lib/src/camera_image.dart
- packages/camera/camera/lib/src/camera_preview.dart
- packages/camera/camera/pubspec.yaml
- packages/camera/camera/test/camera_image_stream_test.dart
- packages/camera/camera/test/camera_image_test.dart
- packages/camera/camera/test/camera_preview_test.dart
- packages/camera/camera/test/camera_test.dart
- packages/camera/camera/test/camera_value_test.dart
- packages/camera/camera/test/utils/method_channel_mock.dart
- script/configs/custom_analysis.yaml
> [camera] Switch app-facing package to new analysis options

- script/tool/CHANGELOG.md
- script/tool/lib/src/lint_podspecs_command.dart
- script/tool/pubspec.yaml
- script/tool/test/lint_podspecs_command_test.dart
This option is unused in our CI, so we no longer need to support it.
Closes https://github.com/flutter/flutter/issues/41444
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#v …
> [flutter_plugin_tool] Remove podspec --allow-warnings

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/lib/webview_android_widget.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/test/android_webview_test.dart
- packages/webview_flutter/webview_flutter_android/test/instance_manager_test.dart
- packages/webview_flutter/webview_flutter_android/test/webview_android_widget_test.dart
The recent Dart rewrite accidentally dropped a parameter value in the
call chain, causing disabling debugging to enabled it instead.
This fixes the issue, and adds testing of that portion of the call
chain (which was entirely missing), as well as adding testing of `false`
at various other points just for added coverage.
As opportunistic cleanup, changes the test group naming, as the pattern
of using `'$FooClass'` breaks test result display in VSCode.
Fixes https://github.com/flutter/flutter/issues/98521 …
> [webview_flutter] Fix debuggingEnabled on Android

- script/tool/lib/src/build_examples_command.dart
- script/tool/lib/src/common/core.dart
- script/tool/lib/src/common/plugin_utils.dart
- script/tool/lib/src/drive_examples_command.dart
- script/tool/lib/src/lint_android_command.dart
- script/tool/lib/src/native_test_command.dart
- script/tool/lib/src/test_command.dart
- script/tool/lib/src/xcode_analyze_command.dart
- script/tool/test/build_examples_command_test.dart
- script/tool/test/common/plugin_utils_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/lint_android_command_test.dart
- script/tool/test/native_test_command_test.dart
- script/tool/test/test_command_test.dart
- script/tool/test/util.dart
- script/tool/test/xcode_analyze_command_test.dart
Fixes capitalization of iOS and macOS in Dart names to match the Dart
naming rules for two-letter abbreviations, bringing the tool code into
compliance with the recent updates to the Flutter style guide:
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#capitalize-identifiers-consistent-with-their-spelling
Since this touched two of the `kPlatform...` constants already, I
opportunistically fixed the long-standing naming mistake of those using
a `k` prefix, which isn't done in Dart style. …
> [flutter_plugin_tool] Fix iOS/macOS naming

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/analysis_options.yaml
- packages/image_picker/image_picker/example/lib/main.dart
- packages/image_picker/image_picker/example/pubspec.yaml
- packages/image_picker/image_picker/pubspec.yaml
- packages/image_picker/image_picker/test/image_picker_deprecated_test.dart
- packages/image_picker/image_picker/test/image_picker_test.dart
- packages/image_picker/image_picker_for_web/CHANGELOG.md
- packages/image_picker/image_picker_for_web/analysis_options.yaml
- packages/image_picker/image_picker_for_web/example/integration_test/image_picker_for_web_test.dart
- packages/image_picker/image_picker_for_web/example/integration_test/image_resizer_test.dart
- packages/image_picker/image_picker_for_web/example/lib/main.dart
- packages/image_picker/image_picker_for_web/example/pubspec.yaml
- packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart
- packages/image_picker/image_picker_for_web/lib/src/image_resizer.dart
- packages/image_picker/image_picker_for_web/lib/src/image_resizer_utils.dart
- packages/image_picker/image_picker_for_web/pubspec.yaml
- packages/image_picker/image_picker_for_web/test/image_resizer_utils_test.dart
- script/configs/custom_analysis.yaml
Also opportunistically fixes one potential null safety issue highlighted by the warnings. …
> [image_picker] Update app-facing and web analysis options

- packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md
- packages/google_sign_in/google_sign_in_platform_interface/analysis_options.yaml
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/method_channel_google_sign_in.dart
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/utils.dart
- packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
- packages/google_sign_in/google_sign_in_platform_interface/test/google_sign_in_platform_interface_test.dart
- packages/google_sign_in/google_sign_in_platform_interface/test/method_channel_google_sign_in_test.dart
- script/configs/custom_analysis.yaml
Switches platform interface package from legacy analysis options to
current analysis options, fixing all analysis issues it exposed. …
> [google_sign_in] Update platform interface analysis options

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/lib/src/camera_controller.dart
- packages/camera/camera/pubspec.yaml
https://github.com/flutter/plugins/pull/4808 accidentally broke
compatibility with pre-2.10 version of Flutter (without a corresponding
min version change). This restores compatibility, since doing so is
trivial.
Fixes https://github.com/flutter/flutter/issues/98660 …
> [camera] Restore compatibility with older Flutter

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
Updates the dependency on the in_app_purchase_storekit to version 0.3.0+1 to ensure the `restorePurchases` method will return an empty list of purchases on the `purchaseUpdates` stream when there are no purchases to restore.
This update was supposed to go out with version 2.0.0 of the in_app_purchase package, but we missed it which unfortunately means we have to rollout another breaking change.
Resolves flutter/flutter#98113
[CLA]: …
> [in_app_purchase] Updates the dependency on in_app_purchase_storekit.

- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/lib/src/webview.dart
- packages/webview_flutter/webview_flutter/pubspec.yaml
The fix is self-explainable ;) Just two lines of doc. …
> [webview] Fix comments (accidentially mixed `//` with `///`)

- packages/path_provider/path_provider_android/CHANGELOG.md
- packages/path_provider/path_provider_android/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java
- packages/path_provider/path_provider_android/lib/path_provider_android.dart
- packages/path_provider/path_provider_android/pubspec.yaml
- packages/path_provider/path_provider_android/test/path_provider_android_test.dart
Reverts the channel name reversion from 2.0.11, so that it is using a
different channel name from the shared method channel (to avoid
confusion if they diverge over time), as originally intended.
Includes the update to 2.8 as a minimum Flutter version, which was
forgotten in the original change. …
> [path_provider] Use a different Android channel name

- packages/path_provider/path_provider_ios/CHANGELOG.md
- packages/path_provider/path_provider_ios/ios/Classes/FLTPathProviderPlugin.m
- packages/path_provider/path_provider_ios/lib/path_provider_ios.dart
- packages/path_provider/path_provider_ios/pubspec.yaml
- packages/path_provider/path_provider_ios/test/path_provider_ios_test.dart
Eliminates the path_provider_ios reliance on the default, shared method channel implementation, in favor of an in-package implementation.
Now that it's trivial to do so, also moves the creation of directories when necessary to the Dart side, and unit tests it there.
Part of https://github.com/flutter/flutter/issues/94224
[Discord]: …
> [path_provider] Switch iOS to an internal method channel

- .cirrus.yml
Replaces the expired key with the updated key so that Android tests work again.
Fixes https://github.com/flutter/flutter/issues/99703
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and- …
> [ci] Update FTL key

- script/tool/CHANGELOG.md
- script/tool/lib/src/analyze_command.dart
- script/tool/lib/src/common/plugin_command.dart
- script/tool/lib/src/make_deps_path_based_command.dart
- script/tool/pubspec.yaml
- script/tool/test/analyze_command_test.dart
- script/tool/test/make_deps_path_based_command_test.dart
Fixes a regression in `analyze` when packages have non-example
subpackages. Restructuring in 0.8.0 accidentally caused them not to have
their dependencies fetched, causing analysis failures.
Unblocks rolling flutter/packages to the latest tooling. …
> [flutter_plugin_tools] Fix subpackage analysis

- packages/video_player/video_player_platform_interface/CHANGELOG.md
- packages/video_player/video_player_platform_interface/lib/method_channel_video_player.dart
- packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
- packages/video_player/video_player_platform_interface/pubspec.yaml
- packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
Platform interface changes required for https://github.com/flutter/plugins/pull/3820#pullrequestreview-835892052
https://github.com/flutter/flutter/issues/60327 …
> [video_player] Platform interface changes to fix Android rotation for videos recorded in landscapeRight

- script/install_chromium.sh
This brings the version of Chrome that we use for integration web tests in line with the one used by flutter/flutter and flutter/engine.
No Issue (that I could find); at first I thought this would help with a test that I'm writing for an unrelated issue, but then I thought that the improvements to the script might be interesting (we might want to rollback the chromium build_id to what was there before?) …
> [ci] Update Chrome install script and version.

- script/tool/CHANGELOG.md
- script/tool/README.md
While doing a manual release of a plugin, I found the docs of the `publish-plugin` tool slightly outdated.
This is a quick fix for the relevant MD file. …
> [tool] Fix typo in `publish-plugin` readme

- packages/espresso/CHANGELOG.md
- packages/espresso/android/build.gradle
- packages/espresso/pubspec.yaml
- packages/image_picker/image_picker/example/pubspec.yaml
Updates the guava version in `espresso` to use the latest stable version: https://github.com/google/guava
In https://github.com/flutter/plugins/pull/5011, the `exoplayer` version in `video_player` was increased. This made it incompatible with the `espresso` plugin. And this broke `image_picker` which depends on `espresso` and `video_player`.
For `image_picker`:
No version change: Only updating `espresso` `dev_dependeny` for CI.
No CHANGELOG change: Only updating `espresso` `dev_dependeny` for CI. …
> [espresso] [video_player] Update espresso guava version

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/example/ios/RunnerTests/TranslatorTests.m
- packages/in_app_purchase/in_app_purchase_storekit/ios/Classes/FIAObjectTranslator.m
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
Starting from iOS 15.4 the Store Kit framework sends back underlying errors as part of the `[NSError userInfo]` field. This results in a crash because the `[FIAObjectTranslator getMapFromNSError]` method doesn't know how to handle this. 
This PR updates the `[FIAObjectTranslator getMapFromNSError]` method to add support for underlying errors and also catches future unsupported type in a way that doesn't immediately crash the consuming app and instead returns an error string that can be handled on the client side.
Resolves flutter/flutter#100458 …
> [in_app_purchase] Make sure unsupported userInfo doesn't crash App

- packages/local_auth/local_auth_platform_interface/CHANGELOG.md
- packages/local_auth/local_auth_platform_interface/lib/local_auth_platform_interface.dart
- packages/local_auth/local_auth_platform_interface/lib/types/types.dart
- packages/local_auth/local_auth_platform_interface/pubspec.yaml
This PR exports the externally required types in local_auth's platform interface package directly from the interface file. 
This PR is a precursor to #5195.
Relevant issues:
- flutter/flutter#68498
- flutter/flutter#94224
[Discord]: …
> [local_auth_platform_interface] Export externally used types from local_auth_platform_interface.dart directly.

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/pubspec.yaml
Restores the app-facing package to a publishable state, switch to the
newly published federated mobile versions. …
> [google_sign_in] Publish federation

- packages/local_auth/local_auth_ios/CHANGELOG.md
- packages/local_auth/local_auth_ios/lib/local_auth_ios.dart
- packages/local_auth/local_auth_ios/pubspec.yaml
- packages/local_auth/local_auth_ios/test/local_auth_test.dart
This PR changes the new iOS implementation of `local_auth` to return `false` instead of throwing an `UnimplementedError`.
It is a precursor to #4701. 
Relevant "issue":
- https://github.com/flutter/plugins/pull/4701#discussion_r848542820
> [local_auth] Change stopAuthentication to return false instead of throwing on iOS.

- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/example/integration_test/auth2_test.dart
- packages/google_sign_in/google_sign_in_web/example/integration_test/gapi_mocks/src/auth2_init.dart
- packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart
- packages/google_sign_in/google_sign_in_web/lib/src/generated/gapiauth2.dart
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
This change ensures that a `plugin_name` attribute with a known value is passed to the `init` call of the current Web implementation of Google Sign In JS SDK.
This allows "new applications to continue using the plugin after April 30th, 2022".
Mitigates: https://github.com/flutter/flutter/issues/88084
See also: https://github.com/flutter/flutter/issues/101004
//FYI @brdaugherty @kevmoo …
> [google_sign_in_web] Add `plugin_name` to `init` call.

- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/example/integration_test/utils.dart
- packages/video_player/video_player_web/example/integration_test/video_player_test.dart
- packages/video_player/video_player_web/example/integration_test/video_player_web_test.dart
- packages/video_player/video_player_web/lib/src/video_player.dart
- packages/video_player/video_player_web/lib/video_player_web.dart
- packages/video_player/video_player_web/pubspec.yaml
The plugin used to remove the "buffering" state of the player when the browser reported [`canPlay`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplay_event). That event means that the browser can start playback, but doesn't guarantee (with the current network conditions) that the video can be successfully played to completion without additional buffering.
This change removes the "buffering" state when the browser reports [`canPlayThrough`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplaythrough_event), which ensures that the browser will be able to playback the whole video without additional buffering.
In order to properly test the above, this change separates the old `_VideoPlayer` private class into its own file under `src`, and adds …
> [video_player_web] Stop buffering when browser canPlayThrough.

- CODEOWNERS
Follow up on go/flutter-android-triage
> Add owners for Android implementations

- script/tool/CHANGELOG.md
- script/tool/lib/src/custom_test_command.dart
- script/tool/pubspec.yaml
- script/tool/test/custom_test_command_test.dart
When running a Dart test script for `custom-test`, `pub get` needs to be
run first in order for it to work in a clean environment such as CI.
This will unblock enabling Pigeon's Dart tests in flutter/packages.
[exempt from version …
> [flutter_plugin_tools] Run pub get for custom-test

- packages/local_auth/local_auth_ios/CHANGELOG.md
- packages/local_auth/local_auth_ios/example/ios/Runner.xcodeproj/project.pbxproj
- packages/local_auth/local_auth_ios/example/ios/RunnerTests/FLTLocalAuthPluginTests.m
- packages/local_auth/local_auth_ios/example/lib/main.dart
- packages/local_auth/local_auth_ios/ios/Classes/FLTLocalAuthPlugin.m
- packages/local_auth/local_auth_ios/lib/local_auth_ios.dart
- packages/local_auth/local_auth_ios/pubspec.yaml
- packages/local_auth/local_auth_ios/test/local_auth_test.dart
This PR adds a custom implementation for `deviceSupportsBiometrics` to return true  when biometric hardware is present, but not enrolled, as per the current documentation. 
Additionally, it removes the confusing `undefined` value from `getEnrolledBiometrics`.
These are the same changes that happened for `local_auth_android` in:
- #5309
Semi-related to flutter/flutter#45497.
Relevant discussion: https://github.com/flutter/plugins/pull/5309#discussion_r854476644
> [local_auth] Fix deviceSupportsBiometrics returning false on iOS when present biometric hardware is not enrolled.

- script/tool/CHANGELOG.md
- script/tool/lib/src/make_deps_path_based_command.dart
- script/tool/test/make_deps_path_based_command_test.dart
Allows `make-deps-path-based` to run multiple times on the same PR
without failing, which will allow `pathified_analyze` to run on
first-stage multi-package federated plugin PRs that are made with
`make-deps-path-based` (per our instructions).
Fixes https://github.com/flutter/flutter/issues/102522 …
> [flutter_plugin_tool] Allow re-pathifying dependencies

- packages/url_launcher/url_launcher_android/CHANGELOG.md
- packages/url_launcher/url_launcher_android/example/lib/main.dart
- packages/url_launcher/url_launcher_android/lib/url_launcher_android.dart
- packages/url_launcher/url_launcher_android/pubspec.yaml
- packages/url_launcher/url_launcher_android/test/url_launcher_android_test.dart
[url_launcher] Add canLaunch fallback for web on Android
If `canLaunch` returns false for a web URL on Android, re-queries with a
generic URL, since this can happen if there is a custom handler for the
queried URL (e.g,. YouTube or Google Maps urls), but the plugin client
application doesn't have permission to see that application.
Fixes https://github.com/flutter/flutter/issues/93765 …
> [url_launcher] Add canLaunch fallback for web on Android

- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/example/ios/RunnerUITests/VideoPlayerUITests.m
- packages/video_player/video_player_avfoundation/pubspec.yaml
The accessibility label for tool tip seems change in one of the recent flutter updates(https://github.com/flutter/flutter/pull/87684), which results failure in this particular XCUITest. This is blocking the flutter to plugins roll.
Fixes: https://github.com/flutter/flutter/issues/102698 …
> [video_player] Fix XCUITest based on the new tooltip accessibility label

- .cirrus.yml
- packages/camera/camera/README.md
- packages/espresso/README.md
- packages/file_selector/file_selector/README.md
- packages/file_selector/file_selector_macos/README.md
- packages/google_sign_in/google_sign_in_web/README.md
- packages/url_launcher/url_launcher/README.md
- script/configs/temp_exclude_excerpt.yaml
- script/tool/CHANGELOG.md
- script/tool/lib/src/readme_check_command.dart
- script/tool/pubspec.yaml
- script/tool/test/readme_check_command_test.dart
Updates `readme-check` to:
- Require that a language annotation to be added to any code block.
- Optionally require that any Dart (for now; we could eventually extend to other
languages) code block use the `code-excerpt`.
Adds CI to validate that all packages are using `code-excerpt`, with a
temporary opt-out list for all of the packages with existing code blocks,
so that we can adopt it incrementally but prevent any new violations.
In order to land the language tag requirement, fixes a couple of blocks
that were missing the annotation.
No version change: The addition of a language block tag is too minor to be worth releasing.
No CHANGELOG change: The addition of a language block tag is too minor to be worth noting.
Part of https://github.com/flutter/flutter/issues/102679
If you need …
> [flutter_plugin_tools] Validate code blocks in readme-check

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/core.dart
- script/tool/lib/src/common/package_looping_command.dart
- script/tool/lib/src/common/plugin_utils.dart
- script/tool/lib/src/common/repository_package.dart
- script/tool/lib/src/drive_examples_command.dart
- script/tool/lib/src/federation_safety_check_command.dart
- script/tool/lib/src/make_deps_path_based_command.dart
- script/tool/lib/src/publish_check_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/lib/src/readme_check_command.dart
- script/tool/lib/src/test_command.dart
- script/tool/lib/src/version_check_command.dart
- script/tool/test/common/repository_package_test.dart
- script/tool/test/create_all_plugins_app_command_test.dart
- script/tool/test/drive_examples_command_test.dart
- script/tool/test/list_command_test.dart
- script/tool/test/pubspec_check_command_test.dart
- script/tool/test/util.dart
Currently `drive-examples` determines what plaforms a package supports by looking at plugin metadata, which means it only works for plugins. This change skips that check for platforms, and adds per-example filtering based on what platforms the example itself supports.
This should allow enabling `drive-examples` in flutter/packages.
Also does some minor refactoring of existing utilities to leverage the newer `RepositoryPackage` class, which will make repeated checks in this logic more efficient since `RepositoryPackage` caches parsed pubspec data.
Part of https://github.com/flutter/flutter/issues/102851 …
> [flutter_plugin_tools] Support non-plugin packages for `drive-examples`

- .github/dependabot.yml
Adds dependabot for Gradle dependencies.
Unfortunately, dependabot doesn't support globs patterns in directory.
cc @stuartmorgan
> Add dependabot for Gradle dependencies

- packages/google_sign_in/google_sign_in_platform_interface/AUTHORS
- packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md
- packages/google_sign_in/google_sign_in_platform_interface/lib/google_sign_in_platform_interface.dart
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/method_channel_google_sign_in.dart
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart
- packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
- packages/google_sign_in/google_sign_in_platform_interface/test/method_channel_google_sign_in_test.dart
This is the platform interface companion to https://github.com/flutter/plugins/pull/3356.
*  flutter/flutter#17813
* flutter/flutter#14245
* flutter/flutter#15796
* flutter/flutter#45847 …
> [google_sign_in] Add forceCodeForRefreshToken parameter (and new SignInInitParameters class)

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart
Fixes `main`
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-upd …
> [google_sign_in] Fix tests to recognize new request attribute.

- packages/ios_platform_images/CHANGELOG.md
- packages/ios_platform_images/lib/ios_platform_images.dart
- packages/ios_platform_images/pubspec.yaml
We need to ignore this deprecation notice, that is incoming here:
* https://github.com/flutter/flutter/pull/103496
This PR ensures that the one above can be landed without breaking the `Linux flutter_plugins` check.
- [~] I listed at least one issue that this PR fixes in the description above. …
> [ios_platform_images] Ignore ImageProvider.load deprecation.

- packages/ios_platform_images/CHANGELOG.md
- packages/ios_platform_images/lib/ios_platform_images.dart
- packages/ios_platform_images/pubspec.yaml
We need to ignore this deprecation notice, that is incoming here:
* https://github.com/flutter/flutter/pull/103496
[This PR](https://github.com/flutter/plugins/pull/5701) attempted to ensure that the one above could be landed without breaking the `Linux flutter_plugins` check, however it didn't because the problem was actually happening in a *documentation* line.
This PR moves the `// ignore` statement to the correct place that is triggering the problem. To verify this'd fix the issue, I used the `flutter` version from @jonahwilliams' branch.
```
dit@dit:~/github/plugins/packages/ios_platform_images$ flutter --version
Flutter 3.1.0-0.0.pre.691 • channel use_immutable_buffer • git@github.com:jonahwilliams/flutter.git
Framework • revision 7aa17dfc78 (89 minutes ago) • 2022-05-12 14:12:51 …
```
> [ios_platform_images] Ignore ImageProvider.load deprecation

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/plugin_command.dart
- script/tool/lib/src/publish_plugin_command.dart
- script/tool/test/publish_plugin_command_test.dart
Makes `getStringListArg` safer, by preventing accidental modification of
the arg parser results themselves. Also changes the way `publish` works
to determine the flags to pass once, rather than once per package, since
they don't change on each run.
Either fixes the accumulation of `--force` flags when publishing
multiple packages. The former is a general safety fix for the internal
utility API, and the latter is a minor cleanup that is no longer
necessary, but avoids pointless duplicate work. …
> [tools] Fix `publish` flag calculation

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/README.md
- packages/camera/camera/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/camera/example/ios/RunnerTests/CameraCaptureSessionQueueRaceConditionTests.m
- packages/camera/camera/example/ios/RunnerTests/CameraMethodChannelTests.m
- packages/camera/camera/example/ios/RunnerTests/CameraPermissionTests.m
- packages/camera/camera/example/lib/main.dart
- packages/camera/camera/example/lib/readme_full_example.dart
- packages/camera/camera/ios/Classes/CameraPermissionUtils.h
- packages/camera/camera/ios/Classes/CameraPermissionUtils.m
- packages/camera/camera/ios/Classes/CameraPlugin.m
- packages/camera/camera/ios/Classes/CameraPlugin.modulemap
- packages/camera/camera/ios/Classes/CameraPlugin_Test.h
- packages/camera/camera/ios/Classes/FLTThreadSafeFlutterResult.h
- packages/camera/camera/ios/Classes/FLTThreadSafeFlutterResult.m
- packages/camera/camera/pubspec.yaml
This PR adds camera access permission handling logic in iOS camera plugin. This fixes a red screen crash when first time using the camera. 
In the future we should clean up all errors. Ideally there should be a header with a list of all errors, so that it's easier to refer to. But to limit the scope of this PR, I only added permission errors following existing conventions. 
Issue [here](https://github.com/flutter/flutter/issues/97199)
Proposal [here](https://docs.google.com/document/d/1t_5FYzOTlBWC6arHc4_8VuG0BUOtIyP9xWvbDER5Y9I/edit)
[relevant style …
> [camera]handle iOS camera access permission

- packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart
- packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
- packages/google_sign_in/google_sign_in_platform_interface/test/google_sign_in_platform_interface_test.dart
Split PR From https://github.com/flutter/plugins/pull/5642 because of https://github.com/flutter/plugins/pull/5642#discussion_r868219111 (To keep federated safety) …
> [google_sign_in_platform_interface] Add availability to mock models

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
Since we're excluding arm64 for this plugin at the podspec level, we have to exclude it for the native unit tests as well.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#ve …
> [google_maps_flutter] Fix native unit tests on M1

- CODEOWNERS
- Provides desktop coverage, for consistency with our new platform review management strategy
- Provides more complete non-platform coverage to start standardizing division of reviews there
These owners will change over time, but this ensures that we have an initial set of owners for all major areas.
> Add more CODEOWNERS

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/example/ios/Podfile
- packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/example/ios/Podfile
- packages/google_sign_in/google_sign_in_ios/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_sign_in/google_sign_in_ios/example/ios/RunnerTests/GoogleSignInTests.m
- packages/google_sign_in/google_sign_in_ios/ios/Classes/FLTGoogleSignInPlugin.m
- packages/google_sign_in/google_sign_in_ios/ios/google_sign_in_ios.podspec
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
Adopt [GoogleSignIn 6.2](https://github.com/google/GoogleSignIn-iOS/releases/tag/6.2.0) (also [published in CocoaPods](https://cocoapods.org/pods/GoogleSignIn#620-2022-5-18)), which supports arm64 simulators.
GoogleSignIn 6+ is not backwards compatible, so adopt the new APIs with async callbacks.  Adopt 6.2 specifically since it supports requested scopes during initialization, which matches the old API.
Fixes https://github.com/flutter/flutter/issues/86436
Fixes https://github.com/flutter/flutter/issues/86660
Removes workaround https://github.com/flutter/plugins/pull/4128
See also https://github.com/google/GoogleSignIn-iOS/issues/23 and https://github.com/google/GoogleSignIn-iOS/pull/30
[Contributor …
> [google_sign_in] Upgrade to GoogleSignIn 6.2, support arm64 simulators

- packages/path_provider/path_provider/CHANGELOG.md
- packages/path_provider/path_provider/example/integration_test/path_provider_test.dart
Recent versions of macOS prompt for access to the Downloads directory
when trying to use it, even with the permission set in the entitlements,
causing the test that validates that the directory can be used to fail
on some CI.
This switches to a less comprehensive test for that directory on macOS,
which doesn't require permissions.
[Discord]: …
> [path_provider] Fix integration tests on macOS

- packages/google_sign_in/google_sign_in_android/CHANGELOG.md
- packages/google_sign_in/google_sign_in_android/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/google_sign_in_android/pubspec.yaml
Part of https://github.com/flutter/flutter/issues/91221
There is already a [SuppressWarnings](https://github.com/flutter/plugins/blob/0d5cf74c437e7f922ae27b82bb580e5043f57ceb/packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L63)
This PR adds three more, so at least the error message are removed.
I guess removing v1 embedding is something else.
[relevant …
> [google_sign_in] Suppress `deprecation` warnings

- packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/google_maps_controller_test.dart
- packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/google_maps_plugin_test.dart
Fix tests with new analysis options warnings.
See https://github.com/flutter/flutter/issues/104453 …
> [google_maps_flutter] Fix prefer_const_literals_to_create_immutables

- .cirrus.yml
This adopts the new Apple silicon images for:
- macOS platform tests
- iOS build-all
This gives us build coverage across both architectures for both iOS and
macOS.
Ideally we would use ARM for iOS platform tests instead of build-all,
but driving the iOS tests currently has flaky hangs on ARM. See
https://github.com/flutter/plugins/pull/5693 for details. Completing
that part of the migration is left as a TODO.
> [ci] Initial migration to Cirrus Apple silicon

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/google_maps_flutter/android/src/test/java/io/flutter/plugins/googlemaps/GoogleMapControllerTest.java
- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Android platform views that are displayed as a texture after Flutter v3.0.0.
require that the view hierarchy is notified after all drawing operations have been flushed.
Since the gmscore GL renderer doesn't use standard Android views, and instead uses TextureView,
we notify the view hierarchy by invalidating the view.
Unfortunately, when OnMapLoadedCallback is fired, the texture may not have been updated yet.
To workaround this limitation, wait two frames.
This ensures that at least the frame budget (16.66ms at 60hz) have passed since the
drawing operation was issued.
Ideally, `google_maps_flutter` is rendered a texture, so there's a single mode for platform views, and there's fewer surprises when combined with other platform views like WebView or AdMobView.
I will work on updating the …
> Fix issue where map updates don't take effect in Flutter v3.0.0

- packages/ios_platform_images/CHANGELOG.md
- packages/ios_platform_images/lib/ios_platform_images.dart
- packages/ios_platform_images/pubspec.yaml
This was added to the deprecations of https://github.com/flutter/flutter/pull/103496
> [ios_platform_images] ignore DecoderCallback deprecation

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/foundation/foundation_api_impls.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/ui_kit/ui_kit_api_impls.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit/web_kit.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit/web_kit_api_impls.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit_webview_widget.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
Updating the minimum versions introduces new lint warnings, so this fixes the warnings with the version bump. …
> [webview_flutter_wkwebview] Raise minimum Dart and Flutter version to 2.17 and 3.0.0, respectively.

- packages/path_provider/path_provider_windows/CHANGELOG.md
- packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart
- packages/path_provider/path_provider_windows/pubspec.yaml
- packages/path_provider/path_provider_windows/test/path_provider_windows_test.dart
Fixes https://github.com/flutter/flutter/issues/99486
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugi …
> [path_provider] Support unicode encoded version info values

- packages/camera/camera_web/CHANGELOG.md
- packages/camera/camera_web/example/integration_test/camera_error_code_test.dart
- packages/camera/camera_web/lib/src/types/camera_error_code.dart
- packages/camera/camera_web/pubspec.yaml
As discussed in the [proposal](https://docs.google.com/document/d/1t_5FYzOTlBWC6arHc4_8VuG0BUOtIyP9xWvbDER5Y9I/edit#), we want to use `CameraAccessDenied` to be consistent with other platforms. 
Since both web and Android will have breaking changes, we should land them together as one single major version bump to minimize headache for developers. 
https://github.com/flutter/flutter/issues/97199 …
> [camera_web] Use CameraAccessDenied for permission error

- packages/path_provider/path_provider_linux/CHANGELOG.md
- packages/path_provider/path_provider_linux/pubspec.yaml
- packages/path_provider/path_provider_windows/CHANGELOG.md
- packages/path_provider/path_provider_windows/example/windows/flutter/generated_plugins.cmake
- packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart
- packages/path_provider/path_provider_windows/pubspec.yaml
Bump package:ffi dependency to 2.0.0. No new tests added since there is no logic change in this PR. …
> [path_provider_windows] Update to ffi 2.0.0

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerTests/FLTGoogleMapJSONConversionsConversionTests.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/FLTGoogleMapJSONConversions.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/FLTGoogleMapJSONConversions.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/FLTGoogleMapTileOverlayController.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/FLTGoogleMapTileOverlayController.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/FLTGoogleMapsPlugin.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/FLTGoogleMapsPlugin.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapCircleController.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapCircleController.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapMarkerController.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapMarkerController.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolygonController.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolygonController.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolylineController.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolylineController.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/JsonConversions.h
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/JsonConversions.m
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/google_maps_flutter-umbrella.h
- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Objective-C code cleanup. See: https://github.com/flutter/flutter/issues/102597
fixes https://github.com/flutter/flutter/issues/102597
It has a lot of re-naming, let me know if it is hard to review. I can try separate it to smaller patches. 
[Discord]: …
> [google_maps_flutter] Objective-C code clean up

- packages/image_picker/image_picker_android/android/build.gradle
- packages/image_picker/image_picker_android/example/android/gradle.properties
Fixes https://github.com/flutter/flutter/issues/105182
Only Jetifier needs to be removed, but keeping `enableUnitTestBinaryResources` would print out:
```
> Configure project :image_picker_android
WARNING: The option setting 'android.enableUnitTestBinaryResources=true' is experimental and unsupported.
The current default is 'false'.
```
No version change: Only updates gradle properties for example app
No CHANGELOG change: Only updates gradle properties for example app
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md …
> [image_picker_android] Remove `jetifier` and `enableUnitTestBinaryResources` from gradle properties

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/v4/src/types/load_request_params.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
Following up on #5852 for changes in `webview_flutter_platform_interface`.
This PR will prevent warnings once https://github.com/flutter/flutter/pull/104231 has landed.
> ignore upcoming warnings in webview_flutter_platform_interface

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/foundation/foundation.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
Following up on #5852 for changes in webview_flutter_wkwebview.
This PR will prevent warnings once https://github.com/flutter/flutter/pull/104231 has landed.
> ignore upcoming warnings in  webview_flutter_wkwebview.

- packages/image_picker/image_picker_android/CHANGELOG.md
- packages/image_picker/image_picker_android/android/build.gradle
- packages/image_picker/image_picker_android/example/android/app/build.gradle
- packages/image_picker/image_picker_android/example/android/build.gradle
- packages/image_picker/image_picker_android/example/android/gradle.properties
- packages/image_picker/image_picker_android/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/image_picker/image_picker_android/pubspec.yaml
Follow up from https://github.com/flutter/plugins/pull/5889. Jetifier is still used when creating a new Flutter app with `flutter create`. This ensures that the example app still runs with `jetifier` and `video_player_android`.
[Discord]: …
> [image_picker_android] Add jetifier back with gradle and androidx upgrades

- .cirrus.yml
The filter will run post-submit tests only on main branch and all the
PRs. …
> Update filter to run tasks only on PRs and main branch.

- .cirrus.yml
Re-adding filter removed in https://github.com/flutter/plugins/pull/5883 per [discussion](https://github.com/flutter/plugins/pull/5883/files#r887442326) …
> [ci] Re-add Cirrus tag filter

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/lib/src/camera_image.dart
- packages/camera/camera/test/camera_image_test.dart
- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/method_channel/type_conversion.dart
- packages/camera/camera_platform_interface/lib/src/types/camera_image_data.dart
- packages/camera/camera_platform_interface/test/method_channel/type_conversion_test.dart
- packages/camera/camera_platform_interface/test/types/camera_image_data_test.dart
- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/lib/google_maps_flutter.dart
- packages/google_maps_flutter/google_maps_flutter/test/map_creation_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/method_channel/method_channel_google_maps_flutter.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/platform_interface/google_maps_flutter_platform.dart
- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/example/integration_test/video_player_test.dart
- packages/webview_flutter/webview_flutter/CHANGELOG.md
- packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart
This PR will prevent warnings once https://github.com/flutter/flutter/pull/104231 has landed.
In previous PRs (https://github.com/flutter/plugins/pull/5852, https://github.com/flutter/plugins/pull/5855, 
https://github.com/flutter/plugins/pull/5856, and https://github.com/flutter/plugins/pull/5922) I misread the log and forgot other packers
No version change: only import cleanup.
> Ignore upcoming warnings

- packages/path_provider/path_provider/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider_android/example/integration_test/path_provider_test.dart
- script/tool/CHANGELOG.md
- script/tool/lib/src/drive_examples_command.dart
- script/tool/test/drive_examples_command_test.dart
Ensures that tests in integration test files are written with
`testWidgets` instead of `test`, as the latter won't correctly report
failures in an integration test.
No CHANGELOG change: Only affects tests when run in our CI, so not worth mentioning.
See https://github.com/flutter/flutter/issues/105055 …
> [tools] Check integration tests for `test`

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/pubspec.yaml
Re-enables publishing of `camera` now that the mobile federated
implementation packages have been published.
Part of flutter/flutter#68498
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and …
> [camera] Publish federated implementations

- .cirrus.yml
Differences between stable and master will almost always show up at the Dart level (analysis, Dart unit tests) or in the native build (which has secondary coverage via build-all-plugins). That means that running the most expensive tests—`*-platform_tests`—on both stable and master in presubmit is not a good use of compute resources.
This will skip these tests on stable. By using `skip` rather than `only_if`, they will show up in the results and can be manually triggered in cases where we specifically want to run them.
Web is currently exempt from this change since runtime differences in web plugins may be more common. We can revisit this later if that's not turning out to be the case.
Fixes https://github.com/flutter/flutter/issues/105187 …
> [ci] Skip expensive native tests on stable in presubmit

- packages/url_launcher/url_launcher_web/CHANGELOG.md
- packages/url_launcher/url_launcher_web/example/integration_test/link_widget_test.dart
- packages/url_launcher/url_launcher_web/lib/src/link.dart
- packages/url_launcher/url_launcher_web/pubspec.yaml
@kristoffer-zliide found [a very subtle issue with the current `Link` implementation](https://github.com/flutter/flutter/issues/102741): it may call `onPlatformViewCreated` after it's been `dispose`d by the framework.
The problem is a race condition between the time a Link `controller` initializes and it notifies the framework that it's completely created, because the `PlatformViewLink` widget that is being used as a base for the Platform View of the widget doesn't allow for `async` Platform View Creation callbacks.
The web initialization, however, _needs_ an `async` callback, because of the way that Platform Views are created there. Since the creation callback cannot be async, the current `factory` method creates the Link widget `controller` and calls its `init` as an "unawaited" future …
> [url_launcher] Fixes call to setState after dispose.

- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
Ignore body_might_complete_normally_catch_error violation
No version change: Ignore directives do not affect plugin clients.
Related to https://github.com/flutter/flutter/issues/105750 …
> [camera] Ignore body_might_complete_normally_catch_error violation

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/example/lib/main.dart
- packages/camera/camera_android/pubspec.yaml
- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/lib/main.dart
- packages/camera/camera_avfoundation/pubspec.yaml
A couple of instances of `styleFrom` in the camera plugins were missed in #5945. I ran the full analysis script on this, so it should be the last of them.
See: https://github.com/flutter/flutter/issues/105724 and https://github.com/flutter/flutter/pull/105291 for more details.
> Added ignore deprecation comments to `styleFrom` button APIs (cont)

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/lib/src/android_camera.dart
- packages/camera/camera_android/pubspec.yaml
- packages/camera/camera_android/test/android_camera_test.dart
- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/lib/src/avfoundation_camera.dart
- packages/camera/camera_avfoundation/pubspec.yaml
- packages/camera/camera_avfoundation/test/avfoundation_camera_test.dart
Fixes a regression from an unintented change in behavior during the
conversion to an in-app method channel for Android and iOS. Although the
Dart code for their implementations is almost identical to the shared
method channel version, the differences in initialization paths caused
the platform versions to try to use the widget bindings before they had
been set up: The constructor for a `dartPluginClass` is called during
`registerWith`, which is before `main`, but the constructor for the
default implementation isn't called until `CameraPlatform.instance` is
called, since Dart automatically does lazy static class initialization.
To avoid the issue without forcing bindings to be initialized early,
this makes setting up the platform channel listener lazily.
Fixes …
> [camera] Fix exception in registerWith

- .cirrus.yml
- .github/dependabot.yml
- script/tool/CHANGELOG.md
- script/tool/lib/src/dependabot_check_command.dart
- script/tool/lib/src/main.dart
- script/tool/test/dependabot_check_command_test.dart
Adds a new `dependabot-check` command to the repo tooling to validate that the Dependabot configuration matches our actual repository state. For now it only covers Gradle, since that's all we've enabled dependabot for on a per-package level so far.
Enables the new check in CI, and fixes all of the issues it found.
Fixes https://github.com/flutter/flutter/issues/102878
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaki …
> [ci] Ensure complete dependabot coverage

- packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/method_channel_google_sign_in.dart
- packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart
- packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
- packages/google_sign_in/google_sign_in_platform_interface/test/method_channel_google_sign_in_test.dart
This PR is a prerequisite for implementing https://github.com/flutter/plugins/pull/5250.
It adds support for passing a server client ID to platform implementations when initializing them. …
> [google_sign_in_platform_interface] Add support for `serverClientId`

- packages/google_maps_flutter/google_maps_flutter/example/integration_test/google_maps_test.dart
See: https://github.com/flutter/flutter/issues/106750
No version change: Only fixes a test.
No CHANGELOG change: Only fixes a test.
[exempt from …
> [google_maps_flutter] Temporary fix for initial coordinate when the surface is changed

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/package_looping_command.dart
- script/tool/pubspec.yaml
- script/tool/test/common/package_looping_command_test.dart
- script/tool/test/util.dart
Adds a `skip-if-not-supporting-dart-version` corresponding to the
existing `skip-if-not-supporting-dart-version` but for packages without
Flutter constraints. The need for this has come up several times in
flutter/packages.
This uses a new flag instead of adding a Flutter->Dart version mapping
because it means that we can continue to update the legacy test
configurations just by adjusting the CI scripts, rather than needing to
make a new tool change to update the mapping every time we roll the
legacy tests forward a version.
Fixes https://github.com/flutter/flutter/issues/100389 …
> [tools] Allow skipping packages by Dart version

- packages/image_picker/image_picker_ios/CHANGELOG.md
- packages/image_picker/image_picker_ios/pubspec.yaml
Replace `video_picker` with `image_picker` in the pubspec description …
> [image_picker_ios] fix wrong plugin name

- packages/google_sign_in/google_sign_in_android/CHANGELOG.md
- packages/google_sign_in/google_sign_in_android/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/google_sign_in_android/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInWrapper.java
- packages/google_sign_in/google_sign_in_android/android/src/test/java/io/flutter/plugins/googlesignin/GoogleSignInTest.java
- packages/google_sign_in/google_sign_in_android/example/lib/main.dart
- packages/google_sign_in/google_sign_in_android/example/pubspec.yaml
- packages/google_sign_in/google_sign_in_android/pubspec.yaml
- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/example/ios/RunnerTests/GoogleSignInTests.m
- packages/google_sign_in/google_sign_in_ios/example/lib/main.dart
- packages/google_sign_in/google_sign_in_ios/example/pubspec.yaml
- packages/google_sign_in/google_sign_in_ios/ios/Classes/FLTGoogleSignInPlugin.m
- packages/google_sign_in/google_sign_in_ios/ios/Classes/FLTGoogleSignInPlugin_Test.h
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
- packages/google_sign_in/google_sign_in_web/CHANGELOG.md
- packages/google_sign_in/google_sign_in_web/README.md
- packages/google_sign_in/google_sign_in_web/example/integration_test/auth2_legacy_init_test.dart
- packages/google_sign_in/google_sign_in_web/example/integration_test/gapi_load_legacy_init_test.dart
- packages/google_sign_in/google_sign_in_web/example/pubspec.yaml
- packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart
- packages/google_sign_in/google_sign_in_web/pubspec.yaml
This PR lands the platform implementations of #5250.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-an …
> [google_sign_in] Implement Dart-based configuration and `serverClientId`

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/README.md
- packages/google_sign_in/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/google_sign_in/pubspec.yaml
- packages/google_sign_in/google_sign_in/test/google_sign_in_test.dart
This PR removes the requirement to add a `GoogleService-Info.plist` file for iOS apps and instead allows for configuration though Dart. 
To this end, a new parameter (`serverClientId`) is added to the `GoogleSignIn` constructor. <strike>This necessitates a breaking change in `google_sign_in_platform_interface`. </strike>
While working on this PR, I noticed that on Android `clientId` was interpreted as a server client ID as opposed to an app client ID, like on iOS and Web. On Android, app client IDs are not required/supported. To provide an API that is consistent across platforms, passing a non-null value for `clientId` now <strike>throws</strike> logs a warning on Android and `serverClientId` is used as `clientId` was previously.
Closes https://github.com/flutter/flutter/issues/96391 …
> [google_sign_in] Support Dart-based configuration and `serverClientId`

- packages/video_player/video_player/test/video_player_test.dart
Add an epsilon to the matrix value comparison. 
Fixes: https://github.com/flutter/flutter/issues/107324
No CHANGELOG change:
This PR only updates tests. …
> [video_player] Use epislon to compare values in matrix in test

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
Rolls `json_serializable` forward to pick up a fix to generated code.
Rolls `json_annotation` forward as well due to version mismatch warnings with the newer `json_serializable`.
Fixes https://github.com/flutter/flutter/issues/107374 …
> [in_app_purchase] Update json_serializable

- packages/file_selector/file_selector_platform_interface/CHANGELOG.md
- packages/file_selector/file_selector_platform_interface/lib/src/types/x_type_group/x_type_group.dart
- packages/file_selector/file_selector_platform_interface/pubspec.yaml
- packages/file_selector/file_selector_platform_interface/test/x_type_group_test.dart
It's come up several time in implementations that we want to identify
wildcard groups in order to handle them specially. The logic for it is
somewhat cumbersome, especially since the collections were unfortunately
made nullable (meaning there's two different ways for them to be empty),
and it's also not future-proof as other types could potentially be added
in the future.
This consolidates that logic into the group itself, so that it can be
updated centrally in the future.
Part of https://github.com/flutter/flutter/issues/107469
[CLA]: …
> [file_selector] Add `allowsAny` to `XTypeGroup`

- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/example/ios/RunnerTests/FWFWebViewHostApiTests.m
- packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FWFWebViewHostApi.m
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
It looks like these lines were missed when creating the new implementation: https://github.com/flutter/plugins/blob/bdec9bad73da186c30f42eb105b84e6b17eeaf31/packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FlutterWebView.m#L128-L133
This PR adds them to `FWFWebView` and adds the tests from the old implementation to verify these settings.
Fixes: https://github.com/flutter/flutter/issues/107639 …
> [webview_flutter_wkwebvew] Fix UIScrollView regression for inset behavior

- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/android/build.gradle
- packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
- packages/video_player/video_player_android/pubspec.yaml
Rolls all exoplayer packages to 2.18, and updates for deprecation
warnings.
[following repository …
> [video_player] Update ExoPlayer to 2.18.0

- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/example/integration_test/duration_utils_test.dart
- packages/video_player/video_player_web/example/integration_test/utils.dart
- packages/video_player/video_player_web/example/integration_test/video_player_test.dart
- packages/video_player/video_player_web/example/pubspec.yaml
- packages/video_player/video_player_web/lib/src/duration_utils.dart
- packages/video_player/video_player_web/lib/src/video_player.dart
- packages/video_player/video_player_web/pubspec.yaml
Videos that report `Infinity` duration are breaking the initialization event of the video player on the web.
This PR modifies the function that prepares the init event, to handle the `Infinity` duration value gracefully by using `isFinite` instead of `!isNaN` when deciding what to do with it.
_(In Dart, a number can be only one of: `isFinite`, `isNaN`, `isInfinite`, so `double.infinity.isNaN` returns **false!**)_
* Fixes: https://github.com/flutter/flutter/issues/105649
* Maybe: https://github.com/flutter/flutter/issues/100257
* Maybe: https://github.com/flutter/flutter/issues/90038
* Maybe: https://github.com/flutter/plugins/pull/3167 …
> [video_player_web] Improve handling of "Infinite" videos.

- script/tool/CHANGELOG.md
- script/tool/lib/src/version_check_command.dart
- script/tool/test/version_check_command_test.dart
Dependabot PRs currently always need manual intervention to add either
version/CHANGELOG bumps, or overriddes so that they can be landed
without them, which adds friction to landing those PRs.
Several commonly-updated dependencies are only for internal testing, so
never need version or CHANGELOG changes. This adds an explict allow-list
for Dependabot PRs for those packages to automatically bypass the usual
checks for missing updates, to make them easier to land.
Fixes https://github.com/flutter/flutter/issues/107942
[CLA]: …
> [tool] Bypass version/changelog checks for some PRs

- packages/file_selector/file_selector/CHANGELOG.md
- packages/file_selector/file_selector/README.md
- packages/file_selector/file_selector/lib/file_selector.dart
- packages/file_selector/file_selector/pubspec.yaml
Picks up the breaking changes to each implementation that includes
throwing `ArgumentError`s for unsupported type groups, and updates the
documentation accordingly. This is a breaking change for the app-facing
package.
Fixes https://github.com/flutter/flutter/issues/107469 …
> [file_selector] Enable ArgumentErrors for type groups

- script/tool/lib/src/version_check_command.dart
- script/tool/test/version_check_command_test.dart
Follow-up to https://github.com/flutter/plugins/pull/6124; that version
works if the tooling actually gets the PR description, but due to
https://github.com/cirruslabs/cirrus-ci-docs/issues/1029 we may get the
commit message instead, so we need to detect that as well.
Part of https://github.com/flutter/flutter/issues/107942
[Discord]: …
> [tool] Handle dependabot commit messages

- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/README.md
- packages/video_player/video_player_web/pubspec.yaml
We've had a number of reports that "scrubbing on a video doesn't work", where the root cause is the server that is being used by the user to deliver said videos not supporting range requests.
This change documents this known limitation, adds a couple more links to relevant information about auto-play, and re-formats the file to more-or-less conform to 80 columns.
* Documents: https://github.com/flutter/flutter/issues/107281
* Documents: https://github.com/flutter/flutter/issues/93486
* Documents: https://github.com/flutter/flutter/issues/49360
* (and maybe others) …
> [video_player_web] Document video scrubbing and range requests.

- packages/camera/camera_windows/CHANGELOG.md
- packages/camera/camera_windows/pubspec.yaml
- packages/camera/camera_windows/windows/camera.cpp
- packages/camera/camera_windows/windows/camera.h
- packages/camera/camera_windows/windows/camera_plugin.cpp
- packages/camera/camera_windows/windows/capture_controller.cpp
- packages/camera/camera_windows/windows/capture_controller.h
- packages/camera/camera_windows/windows/test/camera_plugin_test.cpp
- packages/camera/camera_windows/windows/test/camera_test.cpp
- packages/camera/camera_windows/windows/test/capture_controller_test.cpp
- packages/camera/camera_windows/windows/test/mocks.h
*My C++ is incredibly rusty. Please feel free to provide any and all suggestions kindly 😄*
Currently, a camera becomes "stuck" in a bad state if a camera fails to initialize once on Windows. For example, you will need to relaunch your app if the camera fails to initialize due to a permissions error - you cannot enable camera access and retry creating the camera.
This issue happens because the plugin incorrectly keeps cameras even if they failed to initialize: https://github.com/flutter/plugins/blob/28eff0a8c167d146d73d62aa21a7d93d95bc2578/packages/camera/camera_windows/windows/camera_plugin.cpp#L401-L403
Fixes https://github.com/flutter/flutter/issues/107858 …
> [camera_windows] Allow retrying after initialization failure

- script/tool/CHANGELOG.md
- script/tool/lib/src/make_deps_path_based_command.dart
- script/tool/pubspec.yaml
- script/tool/test/make_deps_path_based_command_test.dart
When pathifying dependencies using `make-deps-path-based`, consider
`dev_dependencies` in addition to `dependencies`. This handles cases
such as `go_router`/`go_router_builder`.
The lack of this caused https://github.com/flutter/flutter/issues/108274
to slip through presubmit tests. …
> [tool] Include `dev_dependencies` in `make-deps-path-based`

- packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter/example/ios/Podfile
- packages/google_maps_flutter/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_maps_flutter/google_maps_flutter/example/ios/RunnerUITests/GoogleMapsUITests.m
- packages/google_maps_flutter/google_maps_flutter/example/lib/map_coordinates.dart
- packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/google_maps_flutter/pubspec.yaml
Avoid the visible region of the Map wiggling around during scrolling by setting `kGMSMapViewPaddingAdjustmentBehaviorNever` as suggested by @erdnj in https://github.com/flutter/flutter/issues/107913#issuecomment-1190452082
Update the example app to allow the **Map coordinates** page to be scrollable, which reproduces the issue before this PR.  Change the visible region UI from a button to a constantly-updating text label.
Before:
https://user-images.githubusercontent.com/682784/180588745-74069b72-ce64-450e-b3ad-38fc23e8ec0c.mov
After:
https://user-images.githubusercontent.com/682784/180588750-fa54b2d5-43ab-4d77-9725-1e5f6b0da162.mov
Add a native test to validate.  I tried to reproduce this from the dart tests instead of the example app …
> Avoid map shift when scrolling on iOS

- packages/camera/camera_windows/CHANGELOG.md
- packages/camera/camera_windows/lib/camera_windows.dart
- packages/camera/camera_windows/pubspec.yaml
- packages/camera/camera_windows/windows/camera.cpp
- packages/camera/camera_windows/windows/camera.h
- packages/camera/camera_windows/windows/capture_controller.cpp
- packages/camera/camera_windows/windows/photo_handler.h
- packages/camera/camera_windows/windows/preview_handler.h
- packages/camera/camera_windows/windows/record_handler.cpp
- packages/camera/camera_windows/windows/record_handler.h
- packages/camera/camera_windows/windows/test/camera_test.cpp
- packages/camera/camera_windows/windows/test/capture_controller_test.cpp
- script/tool/README.md
- script/tool/lib/src/common/package_state_utils.dart
This change improves `camera_windows`'s error handling:
* `CaptureControllerImpl`'s destructor no longer tries to stop recording even if recording has already stopped.
* An error is now reported if stop record fails
* Pause/resume/stop preview now fails properly if preview wasn't started
Part of https://github.com/flutter/flutter/issues/102098 …
> [camera_windows] Improve several error handling scenarios

- packages/camera/camera_windows/CHANGELOG.md
- packages/camera/camera_windows/pubspec.yaml
- packages/camera/camera_windows/windows/camera.cpp
- packages/camera/camera_windows/windows/camera.h
- packages/camera/camera_windows/windows/capture_controller.cpp
- packages/camera/camera_windows/windows/capture_controller.h
- packages/camera/camera_windows/windows/capture_controller_listener.h
- packages/camera/camera_windows/windows/photo_handler.cpp
- packages/camera/camera_windows/windows/photo_handler.h
- packages/camera/camera_windows/windows/preview_handler.cpp
- packages/camera/camera_windows/windows/preview_handler.h
- packages/camera/camera_windows/windows/record_handler.cpp
- packages/camera/camera_windows/windows/record_handler.h
- packages/camera/camera_windows/windows/test/camera_test.cpp
- packages/camera/camera_windows/windows/test/capture_controller_test.cpp
- packages/camera/camera_windows/windows/test/mocks.h
The camera plugin reports issues to the Flutter app by throwing [`CameraException`](https://pub.dev/documentation/camera_platform_interface/latest/camera_platform_interface/CameraException-class.html)s. As per [this proposal](https://docs.google.com/document/d/1t_5FYzOTlBWC6arHc4_8VuG0BUOtIyP9xWvbDER5Y9I/edit), we would like to standardize the `CameraException`'s `code` value so that common errors can be handled consistently across platforms.
This change makes the Windows camera plugin set the error code to `CameraAccessDenied` when camera permissions were denied. This is a breaking change as previously the error code would've been `camera_error` or `capture_error`. …
> [camera_windows] Use `CameraAccessDenied` error code for camera permission errors

- packages/image_picker/image_picker_platform_interface/CHANGELOG.md
- packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart
- packages/image_picker/image_picker_platform_interface/lib/src/platform_interface/image_picker_platform.dart
- packages/image_picker/image_picker_platform_interface/lib/src/types/types.dart
- packages/image_picker/image_picker_platform_interface/pubspec.yaml
- packages/image_picker/image_picker_platform_interface/test/new_method_channel_image_picker_test.dart
This is a fix for https://github.com/flutter/plugins/pull/5914, where newly added types (`ImageOptions` and `MultiImagePickerOptions`) haven't been exported outside of the interface package.
flutter/flutter#65995
[exempt from …
> [image_picker] Add missing exports for multi image picking types

- packages/url_launcher/url_launcher/lib/src/link.dart
Fix diagnostics that will get flagged in the next Dart SDK roll.
See breakage:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8806923775196938257/+/u/flutter_test_flutter_plugins/stdout
Source Linter DEP bump: https://dart-review.googlesource.com/c/sdk/+/253501
/cc @a14n @srawlins  …
> [url_launcher] fix noop toString() diagnostics

- packages/path_provider/path_provider_windows/CHANGELOG.md
- packages/path_provider/path_provider_windows/pubspec.yaml
The usage https://github.com/flutter/plugins/blob/b0bfab678f83bebd49e9f9d0a83fe9b40774e853/packages/path_provider/path_provider_windows/lib/src/path_provider_windows_real.dart#L195 of the `wsalloc` function stipulates at least v2.1.0 of `package:win32`
- see https://github.com/timsneath/win32/commit/1ef183040381d89ed2cf27daf5d86afe403ee79c#diff-17db63ed2e34bd40b2bf89c04f997ba760e4fd75b04e6cf03f58349bd458477dR35 where `wsalloc` was introduced
- also see https://pub.dev/documentation/win32/2.1.0/win32/wsalloc.html and https://pub.dev/documentation/win32/2.0.5/win32/wsalloc.html (`wsalloc` not present in v2.0.5 of `package:win32`)
[relevant …
> [path_provider_windows] bump dependency version of package:win32 in path_provider_windows

- script/tool/lib/src/common/package_looping_command.dart
Fix diagnostics that will get flagged in the next Dart SDK roll.
See breakage:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8806899813430732209/+/u/analyze_flutter_plugins/stdout
Source Linter DEP bump: https://dart-review.googlesource.com/c/sdk/+/253501
/cc @a14n @srawlins  …
> [script] fix script noop interpolated toString()s

- packages/quick_actions/quick_actions_ios/CHANGELOG.md
- packages/quick_actions/quick_actions_ios/example/ios/Runner.xcodeproj/project.pbxproj
- packages/quick_actions/quick_actions_ios/example/ios/RunnerTests/FLTQuickActionsPluginTests.m
- packages/quick_actions/quick_actions_ios/ios/Classes/FLTQuickActionsPlugin.m
- packages/quick_actions/quick_actions_ios/ios/Classes/PrivateHeaders/FLTQuickActionsPlugin_Test.h
- packages/quick_actions/quick_actions_ios/pubspec.yaml
Note that a few private APIs are not covered yet. We could expose them using test headers, however, a better approach is a pre-migration refactor to move these private APIs to a separate component (as discussed in the proposal [here](https://docs.google.com/document/d/1XsaulkJA6_ZSpM7chkQLhQY25sQqhEMiqHMYzw8H85o/edit?resourcekey=0-_cUjF1c0iBvRLKfV-3gK5A#heading=h.24hjfzhkz2dj)), 
Since we want this quick_actions migration to be a "demo" migration, we will go with the refactor approach and add more tests in the next PR, which should remove the need of exposing private APIs. 
https://github.com/flutter/flutter/issues/108750
*If you had to change anything in the [flutter/tests] repo, include a link to the migration …
> [quick_actions] backfill some unit tests for `FLTQuickActionsPlugin` class

- .cirrus.yml
- packages/image_picker/image_picker_android/CHANGELOG.md
- packages/image_picker/image_picker_android/pubspec.yaml
- packages/local_auth/local_auth_android/CHANGELOG.md
- packages/local_auth/local_auth_android/pubspec.yaml
- packages/local_auth/local_auth_ios/CHANGELOG.md
- packages/local_auth/local_auth_ios/pubspec.yaml
- packages/local_auth/local_auth_windows/CHANGELOG.md
- packages/local_auth/local_auth_windows/pubspec.yaml
- packages/url_launcher/url_launcher_web/CHANGELOG.md
- packages/url_launcher/url_launcher_web/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
- script/tool/CHANGELOG.md
- script/tool/lib/src/analyze_command.dart
- script/tool/pubspec.yaml
- script/tool/test/analyze_command_test.dart
Since our CI always runs on clean projects, they always get the latest resolved versions of dependencies, so won't catch the easy-to-make mistake of introducing use of a new dependency API without updating the minimum version of that dependency to the version that introduced that API.
This adds a new `--downgrade` flag to `analyze` to run `flutter pub downgrade` before analyzing, and adds a new CI step to run in that mode. (This won't catch runtime mistakes, but as with the "legacy analyze" runs this catches the most common type of mistake at a fraction of the CI cost of running all tests again.)
Also fixes all the existing violations flagged by the new step.
Fixes https://github.com/flutter/flutter/issues/108992 …
> [ci] Run analyze with minimum resolved packages

- packages/google_maps_flutter/google_maps_flutter_ios/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios/RunnerTests/GoogleMapsTests.m
- packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/google_maps_flutter_ios/pubspec.yaml
Previously, every MapView creation would reinitialize the underlying Google Maps services:
```
21.00 ms   10.1%	0 s	 	                -[GMSMapView initWithFrame:camera:]
21.00 ms   10.1%	0 s	 	                 +[GMSServices sharedServicesSync]
16.00 ms    7.7%	0 s	 	                  -[GMSAsyncInitServices services]
16.00 ms    7.7%	0 s	 	                   CompleteInit(GMSAsyncInitServices*)
16.00 ms    7.7%	0 s	 	                    invocation function for block in CompleteInit(GMSAsyncInitServices*)
15.00 ms    7.2%	0 s	 	                     -[GMSServices initWithDisplayLink:resourceCache:clearcutClient:dataURL:cachesURL:options:]
4.00 ms    1.9%	0 s	 	                      -[GMSClientParameters startWithCompletionHandler:]
4.00 ms    1.9%	0 s …
```
> [google_maps_ios] Cache `+[GMSServices sharedServices]` when first map is created

- packages/path_provider/path_provider_android/CHANGELOG.md
- packages/path_provider/path_provider_android/android/build.gradle
- packages/path_provider/path_provider_android/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/109397 after large gradle bump in https://github.com/flutter/plugins/pull/6189
> [path_provider] Bump kotlin to 1.7.10

- packages/camera/camera_platform_interface/test/camera_platform_interface_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/platform_interface/google_maps_flutter_platform_test.dart
- packages/google_sign_in/google_sign_in_platform_interface/test/google_sign_in_platform_interface_test.dart
- packages/in_app_purchase/in_app_purchase_platform_interface/test/in_app_purchase_platform_test.dart
- packages/quick_actions/quick_actions_platform_interface/test/quick_actions_platform_interface_test.dart
- packages/url_launcher/url_launcher_platform_interface/test/method_channel_url_launcher_test.dart
- packages/webview_flutter/webview_flutter_platform_interface/test/src/v4/platform_navigation_delegate_test.dart
- packages/webview_flutter/webview_flutter_platform_interface/test/src/v4/platform_webview_controller_test.dart
- packages/webview_flutter/webview_flutter_platform_interface/test/src/v4/platform_webview_widget_test.dart
- packages/webview_flutter/webview_flutter_platform_interface/test/src/v4/webview_platform_test.dart
Currently, in some circumstances where a subclasses of
`PlatformInterface` erroneously uses `implements` rather than
`extends`, a `NoSuchMethodError` will be thrown (in spite of the
documentation at
https://pub.dev/documentation/plugin_platform_interface/latest/plugin_platform_interface/PlatformInterface/verify.html
claiming that `AssertionError` will be thrown).
After https://github.com/flutter/flutter/issues/109339 is fixed, the
correct type of exception will be thrown.  To avoid tests breakages
when the fix happens, we need to modify these tests so that they don't
care what kind of exception is thrown. …
> Prepare for fix to https://github.com/flutter/flutter/issues/109339.

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/v4/src/platform_webview_widget.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/src/v4/platform_webview_widget_test.dart
Part of https://github.com/flutter/flutter/issues/94051
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins …
> [webview_flutter_platform_interface] Adds missing build params for WebViewWidget 

- packages/google_sign_in/google_sign_in/example/integration_test/google_sign_in_test.dart
- packages/google_sign_in/google_sign_in/example/test_driver/integration_test.dart
- packages/quick_actions/quick_actions/example/integration_test/quick_actions_test.dart
- packages/quick_actions/quick_actions/example/test_driver/integration_test.dart
Some tests still had some tags opting tests out of NNBD. These were mostly scrubbed out of the repository when driver gained NNBD support, but these were missed.
Part of https://github.com/flutter/flutter/issues/110017
[exempt from …
> [various] Remove stale NNBD opt-out tags

- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/ios/RunnerTests/ThreadSafeEventChannelTests.m
- packages/camera/camera_avfoundation/ios/Classes/FLTThreadSafeEventChannel.m
- packages/camera/camera_avfoundation/pubspec.yaml
introduced in https://github.com/flutter/flutter/issues/109910
This is the same reason why we can't use weakSelf in [FLTThreadSafeFlutterResult](https://github.com/flutter/plugins/blob/fbdf7e3e9617748166ede491d96ab41322cd8e6d/packages/camera/camera_avfoundation/ios/Classes/FLTThreadSafeFlutterResult.m#L55-L60) - it's only retained within a call stack, not in the heap. So when dispatched back to main, the wrapper has been gone. 
As a temp workaround, I will simply revert the change in `FLTThreadSafeEventChannel` to fix the bug. An alternative workaround is to make `FLTThreadSafeEventChannel` an ivar and keep it around during streaming. I have verified that both works. 
In this particular example, we don't have to worry about strongSelf making engine API being called after engine is torn …
> [camera]revert the weakSelf in FLTThreadSafeEventChannel

- script/tool/README.md
Adds info about some commands requiring Flutter-bundled dart.
Fixes https://github.com/flutter/flutter/issues/109824
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and- …
> Adds info about commands requiring Flutter-bundled dart

- script/tool/CHANGELOG.md
- script/tool/lib/src/readme_check_command.dart
- script/tool/pubspec.yaml
- script/tool/test/readme_check_command_test.dart
- script/tool/test/update_excerpts_command_test.dart
- script/tool/test/util.dart
Ensures that if a REAME uses code excerpting, the package is configured
to drive it. This avoids the (so far common) mistake of adding tags when
the block check fails, but not setting up the package so that they
actually work.
Also adds a link to the wiki for the missing excerpt tag error so that
people find the instructions sooner, rather than adding tags via
guess-and-check.
Fixes https://github.com/flutter/flutter/issues/109231 …
> [tools] Validate code excerpt configuration

- packages/google_maps_flutter/google_maps_flutter_android/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_android/example/integration_test/google_maps_test.dart
- packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart
- packages/google_maps_flutter/google_maps_flutter_android/pubspec.yaml
Fixes the `useAndroidViewSurface` flag for Flutter 3.0+. Because of the
way TLHC rolled out, `useAndroidViewSurface` was no longer doing
anything meaningful, since either way TLHC would actually be used.
This updates that flag to use `initExpensiveAndroidView` to force HC, so
that the switch does something again.
This provides a way to work around the maps TLHC issue tracked in
https://github.com/flutter/flutter/issues/103686
[CLA]: …
> [google_maps_flutter] Update Android view selection

- packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md
- packages/google_sign_in/google_sign_in_platform_interface/lib/google_sign_in_platform_interface.dart
- packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
- packages/google_sign_in/google_sign_in_platform_interface/test/google_sign_in_platform_interface_test.dart
- packages/shared_preferences/shared_preferences_platform_interface/CHANGELOG.md
- packages/shared_preferences/shared_preferences_platform_interface/lib/shared_preferences_platform_interface.dart
- packages/shared_preferences/shared_preferences_platform_interface/pubspec.yaml
- packages/shared_preferences/shared_preferences_platform_interface/test/shared_preferences_platform_interface_test.dart
Switches `google_sign_in` and `shared_preferences` from a legacy custom
system for verifying that implementations use `extends` rather than
`implements` to the now-standard `plugin_platform_interface`,
deprecating the `isMock` approach to overriding it.
Fixes https://github.com/flutter/flutter/issues/98710
Fixes https://github.com/flutter/flutter/issues/98709
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-change …
> [various] Adopt `plugin_platform_interface`

- CODEOWNERS
Transfers the code ownership of shared_preferences's app-facing package to
@tarrinneal.
> Update shared_preferences CODEOWNER

- packages/google_maps_flutter/google_maps_flutter/example/integration_test/google_maps_test.dart
Some integration tests behave slightly differently on Android when using
Hybrid Composition, and need to wait for a change to become true rather
than it being immediately true.
This replicates the changes from `google_maps_flutter_android` to the
app-facing copy of those integration tests.
Fixes tree breakage from publishing
https://github.com/flutter/plugins/pull/6334
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-break …
> [google_maps_flutter] Fix integration tests

- script/tool/README.md
When trying to execute the instructions for the packages repo, it kept failing with:
```
Resolving dependencies...
Because adaptive_scaffold_example depends on code_excerpter from path which doesn't exist (could not find package code_excerpter at "../../../site-shared/packages/code_excerpter"), version solving failed.
```
This was because the submodule wasn't initialized, so the dependencies weren't available.
> Add missing submodule command to setup for packages repo.

- packages/in_app_purchase/in_app_purchase/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase_android/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase_storekit/example/lib/main.dart
Anticipate deprecations from https://github.com/flutter/flutter/pull/110848
Related https://github.com/flutter/flutter/issues/91772
[exempt from …
> [in_app_purchase] Replace `errorColor` to land deprecations

- packages/camera/camera_android/android/build.gradle
Reverts flutter/plugins#6329
camera_android unit tests seem to be failing pretty consistently [in](https://github.com/flutter/plugins/runs/8278228414) [main](https://github.com/flutter/plugins/runs/8278229490).
Attempting to restore the tree by reverting the PR above.
> Revert "[camera]: Bump robolectric from 4.5 to 4.8.2 in /packages/camera/camera_android/android"

- packages/url_launcher/url_launcher_android/CHANGELOG.md
- packages/url_launcher/url_launcher_android/android/build.gradle
- packages/url_launcher/url_launcher_android/pubspec.yaml
See https://github.com/flutter/flutter/issues/111304
Breaks: https://github.com/flutter/flutter/pull/111197/files#diff-9aeff568c87b1d587222c343afb84ef72fc07e0692d50ecb3de670e5606f9505R46
> Revert "[url_launcher]: Bump gradle from 3.4.2 to 7.2.2 in /packages/url_launcher/url_launcher_android/android #6194"

- packages/camera/camera_android/lib/src/android_camera.dart
- packages/camera/camera_avfoundation/lib/src/avfoundation_camera.dart
- packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
The ignores were marking the `.catchError` call, but they need to mark the first argument, the `onError` callback.
Related to https://github.com/flutter/flutter/issues/105750 …
> [camera] Move ignores for body_might_complete_normally_catch_error

- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_client_wrapper.g.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/billing_client_wrapper_test.dart
Based off of https://github.com/flutter/plugins/pull/6132 by @tosaka07
> Added [IMMEDIATE_AND_CHARGE_FULL_PRICE](https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.ProrationMode#IMMEDIATE_AND_CHARGE_FULL_PRICE) to ProrationMode.
> 
> IMMEDIATE_AND_CHARGE_FULL_PRICE is new in Billing Library v4.
> https://developer.android.com/google/play/billing/release-notes#4-0-0-summary-changes
> 
> This library has already been updated to v5, so there is no problem.
> 
> Fixes https://github.com/flutter/flutter/issues/108164
> [in_app_purchase] Add immediateAndChargeFullPrice ProrationMode

- packages/plugin_platform_interface/CHANGELOG.md
- packages/plugin_platform_interface/lib/plugin_platform_interface.dart
- packages/plugin_platform_interface/pubspec.yaml
- packages/plugin_platform_interface/test/plugin_platform_interface_test.dart
This change replaces `PlatformInterface._instanceToken` (an instance field that points from a `PlatformInterface` to its corresponding token) with an expando that maps from `PlatformInterface` to `Object`. There is no change to the public API, and no change to the behavior of users' production code.
This change ensures that if a customer tries to implement `PlatformInterface` using `implements` rather than `extends`, the code in `PlatformInterface._verify` won't try to access the private `_instanceToken` field in `PlatformInterface`.  This is important because an upcoming change to the dart language is going to cause such accesses to throw exceptions rather than deferring to `noSuchMethod` (see https://github.com/dart-lang/language/issues/2020 for details).
Fixes …
> [plugin_platform_interface] Switch `PlatformInterface._instanceToken` to an expando.

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
Anticipate deprecations from https://github.com/flutter/flutter/pull/110848, apparently missed one from https://github.com/flutter/plugins/pull/6377.
Related https://github.com/flutter/flutter/issues/91772
[pub …
> [in_app_purchase] Replace errorColor to land deprecations (Part 2)

- .cirrus.yml
Update Cirrus image to most recent macOS and Xcode, released on Sept 12. …
> [ci] Update Cirrus to macOS Ventura and Xcode 14

- packages/image_picker/image_picker_ios/CHANGELOG.md
- packages/image_picker/image_picker_ios/example/ios/RunnerTests/PickerSaveImageToPathOperationTests.m
- packages/image_picker/image_picker_ios/example/lib/main.dart
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin.m
- packages/image_picker/image_picker_ios/ios/Classes/FLTPHPickerSaveImageToPathOperation.h
- packages/image_picker/image_picker_ios/ios/Classes/FLTPHPickerSaveImageToPathOperation.m
- packages/image_picker/image_picker_ios/pubspec.yaml
Bugfix for picking (multi) images with PHPicker without gallery permissions.
While the current version allows accessing the gallery without permissions, it was still requiring them for returning picked images as a result. 
flutter/flutter#65995
Bug reported in comment under #5915  …
> [image_picker] Allow saving photos picked with PHPicker without permissions

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/v4/src/platform_navigation_delegate.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/v4/src/types/navigation_decision.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/v4/src/types/navigation_request.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/v4/src/types/types.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/src/v4/platform_navigation_delegate_test.dart
- packages/webview_flutter/webview_flutter_platform_interface/test/src/v4/platform_webview_controller_test.mocks.dart
- packages/webview_flutter/webview_flutter_wkwebview/lib/src/v4/src/webkit_webview_controller.dart
- packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/test/v4/webkit_navigation_delegate_test.dart
Replacement of https://github.com/flutter/plugins/pull/6430 and https://github.com/flutter/plugins/pull/6441.
From https://github.com/flutter/plugins/pull/6430: 
> While working on the Android implementation of the v4 webview_flutter platform interface I had to duplicate the function signatures used in the [PlatformNavigationDelegate] several times. I realized that if I had to duplicate them, it is likely developers consuming the interface probably also had to manually duplicate these method  signatures.  
> To reduce code duplication and make the API easier for consumers to use I decided to create and expose these type definitions.
Part of https://github.com/flutter/flutter/issues/94051
[Contributor …
> [webview_flutter] Adds type definitions for common callback signatures in the navigation delegate

- packages/video_player/video_player/CHANGELOG.md
[following repository CHANGELOG style]: …
> [video_player] Fix invalid link in CHANGELOG on pub.dev

- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/example/ios/RunnerTests/VideoPlayerTests.m
- packages/video_player/video_player_avfoundation/example/ios/RunnerUITests/VideoPlayerUITests.m
- packages/video_player/video_player_avfoundation/example/lib/main.dart
- packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
- packages/video_player/video_player_avfoundation/pubspec.yaml
`copyPixelBufferForItemTime` always return nil (`hasNewPixelBufferForItemTime` returning false) on iOS 16 for encrypted video stream. 
There aren't too much info online. It seems to be **by design that only Apple's `AVPlayerLayer` can access those encrypted video stream** on iOS 16. 
For example, [this unresolved issue](https://stackoverflow.com/questions/42839831/fairplay-streaming-calling-copypixelbufferforitemtime-on-avplayeritemvideooutpu) (5 years ago, but could be the same issue under different format): 
> the only way to display your protected video content is by using an AVPlayerLayer
Another hint is that iOS 16 introduced a new API [`AVPlayerLayer::copyDisplayedPixelBuffer`](https://developer.apple.com/documentation/avfoundation/avplayerlayer/4042647-copydisplayedpixelbuffer?langu …
> [video_player]fix ios 16 bug where encrypted video stream is not showing

- packages/file_selector/file_selector/example/lib/open_image_page.dart
- packages/file_selector/file_selector/example/lib/open_multiple_images_page.dart
- packages/file_selector/file_selector/example/lib/open_text_page.dart
- packages/file_selector/file_selector/test/file_selector_test.dart
- packages/file_selector/file_selector_ios/example/lib/open_image_page.dart
- packages/file_selector/file_selector_ios/example/lib/open_multiple_images_page.dart
- packages/file_selector/file_selector_ios/example/lib/open_text_page.dart
- packages/file_selector/file_selector_ios/test/file_selector_ios_test.dart
- packages/file_selector/file_selector_linux/example/lib/open_image_page.dart
- packages/file_selector/file_selector_linux/example/lib/open_multiple_images_page.dart
- packages/file_selector/file_selector_linux/example/lib/open_text_page.dart
- packages/file_selector/file_selector_linux/test/file_selector_linux_test.dart
- packages/file_selector/file_selector_macos/example/lib/open_image_page.dart
- packages/file_selector/file_selector_macos/example/lib/open_multiple_images_page.dart
- packages/file_selector/file_selector_macos/example/lib/open_text_page.dart
- packages/file_selector/file_selector_macos/test/file_selector_macos_test.dart
- packages/file_selector/file_selector_web/example/integration_test/file_selector_web_test.dart
- packages/file_selector/file_selector_web/test/utils_test.dart
- packages/file_selector/file_selector_windows/example/lib/open_image_page.dart
- packages/file_selector/file_selector_windows/example/lib/open_multiple_images_page.dart
- packages/file_selector/file_selector_windows/example/lib/open_text_page.dart
- packages/file_selector/file_selector_windows/test/file_selector_windows_test.dart
Annotate all parameters of XTypeGroup with // ignore: prefer_const_literals_to_create_immutables to prepare this implementation for the const constructor of XTypeGroup. On files that have more than two occurrences, an ignore_for_file was added at the top of the file.
Issue:
[#111906 [file_selector] `XTypeGroup` should be immutable](https://github.com/flutter/flutter/issues/111906)
Related PR:
[[file_selector] Convert XTypeGroup to const](https://github.com/flutter/plugins/pull/6476#issuecomment-1259562629) …
> [file_selector] Annotate all parameters of XTypeGroup with // ignore: prefer_const_literals_to_create_immutables

- .ci/Dockerfile
Updates the base image to a newer base, to get OS updates.
Also does some minor reorganizing and commenting to make it easier to maintain going forward. Removes SDK version 27 as it no longer seems to be necessary (previously it was installed due to CI failures from something that was specifically looking for 27 rather than what was already on the image).
> [ci] Update Dockerfile

- script/tool/CHANGELOG.md
- script/tool/lib/src/fix_command.dart
- script/tool/lib/src/main.dart
- script/tool/test/fix_command_test.dart
Adds a new command to run `dart fix --apply` in target packages. Like `update-release-info`, this is not intended for CI use, but for local development. It's useful when enabling new lint options.
This is the first time a command has been so simple that it is literally just running a single command in all packages without any additional logic. We may at some point want to replace this with a generic "run a provided command string" command instead of having to make commands like this, but since this is the first time it's come up and it's not clear that we'll have other uses for that, this is just adding the specific command and we can re-evaluate if we ever find that we are adding a second command like this.
(We may well also end up adding more complexity here, such as summarizing the …
> [tool] Adds a `fix` command

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/git_version_finder.dart
- script/tool/lib/src/common/package_command.dart
- script/tool/pubspec.yaml
- script/tool/test/common/package_command_test.dart
Per discussion in https://github.com/flutter/flutter/issues/111885, we can use the auto-roller as a mechanism to find out-of-band issues, rather than having them found by post-submit tests. This will make post-submit much faster and much less compute-intensive for most changes.
Fixes https://github.com/flutter/flutter/issues/111885
[Discord]: …
> [tool] Only run postsubmit on changed packages

- script/tool/lib/src/common/package_command.dart
- script/tool/test/common/package_command_test.dart
Improves the initial output when running in a mode that filters by packages that need to be tested so that it clearly indicated when it's using "re-run everything due to a core file change", rather than misleadingly logging that it's only testing changed packages. …
> [tool] Improve changed-package run mode logging

- packages/file_selector/file_selector_platform_interface/CHANGELOG.md
- packages/file_selector/file_selector_platform_interface/lib/src/types/x_type_group/x_type_group.dart
- packages/file_selector/file_selector_platform_interface/pubspec.yaml
- packages/file_selector/file_selector_platform_interface/test/method_channel_file_selector_test.dart
- packages/file_selector/file_selector_platform_interface/test/x_type_group_test.dart
Within the file_selector_platform_interface, XTypeGroup constructor was converted to `const`, meaning that from now on, this object needs to be constructed using `const`.
Issue:
[#111906 [file_selector] `XTypeGroup` should be immutable](https://github.com/flutter/flutter/issues/111906)
Related PR:
[#6463 Annotate all creation of XTypeGroup with // ignore: prefer_const_contructor](https://github.com/flutter/plugins/pull/6463)
[CLA]: …
> [file_selector] Convert XTypeGroup to const

- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/example/ios/RunnerTests/VideoPlayerTests.m
- packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
- packages/video_player/video_player_avfoundation/pubspec.yaml
The issue is that `item.presentationSize` returns the swapped width and height for some video streams (likely due to transform). 
I did lots of research and wasn't able to find any workaround online. Then I thought that each segment of the HLS may have different resolution (e.g. different internet speed), so AVFoundation must be adjusting the `presentationSize` continuously. Fixing aspect ratio could also be part of that adjustment. So I used the same trick as the [previous PR](https://github.com/flutter/plugins/pull/6442) to leverage AVPlayerLayer to do the heavy lifting work for us. 
Apple's video player (i.e. `AVPlayerLayer`) displays the aspect ratio correctly. This makes me think that Apple likely went through the process to fix the aspect ratio based on the transform. 
As discussed …
> [video_player] Fixes a bug where the aspect ratio of some HLS videos are incorrectly inverted

- packages/image_picker/image_picker_windows/CHANGELOG.md
- packages/image_picker/image_picker_windows/lib/image_picker_windows.dart
- packages/image_picker/image_picker_windows/pubspec.yaml
The changes that were made on [#6476](https://github.com/flutter/plugins/pull/6476), affected the image_picker_windows package. So, in this pull request, the previously added `//ignore`'s are removed and converted XTypeGroup to `const` instead of `final`.
The version of `file_selector_platform_interface` was upgraded to 2.2.0 in the `pubspec.yaml` for windows.
Issue:
Fixes https://github.com/flutter/flutter/issues/111906 [file_selector] `XTypeGroup` should be immutable
Related PR's:
[#6476 [file_selector] Convert XTypeGroup to const](https://github.com/flutter/plugins/pull/6476)
[#6504 [image_picker_windows] Annotate all creation of XTypeGroup with // ignore: prefer_const_contructor](https://github.com/flutter/plugins/pull/6504)
If you need help, consider asking for advice on the …
> [image_picker_windows] Use const instead of final for XTypeGroup.

- script/tool/CHANGELOG.md
The last two versions in the CHANGELOG had typos (0.11 not following the full version format, and 0.12 being listed as 12.0). This fixes them prior to publishing.
> [tool] Fix version mistake in CHANGELOG

- packages/camera/camera_android/android/build.gradle
- packages/camera/camera_android_camerax/android/build.gradle
- packages/espresso/android/build.gradle
- packages/flutter_plugin_android_lifecycle/android/build.gradle
- packages/google_maps_flutter/google_maps_flutter_android/android/build.gradle
- packages/google_sign_in/google_sign_in_android/android/build.gradle
- packages/image_picker/image_picker_android/android/build.gradle
- packages/in_app_purchase/in_app_purchase_android/android/build.gradle
- packages/local_auth/local_auth_android/android/build.gradle
- packages/path_provider/path_provider_android/android/build.gradle
- packages/quick_actions/quick_actions_android/android/build.gradle
- packages/shared_preferences/shared_preferences_android/android/build.gradle
- packages/url_launcher/url_launcher_android/android/build.gradle
- packages/video_player/video_player_android/android/build.gradle
- packages/webview_flutter/webview_flutter_android/android/build.gradle
Adds some missing ignores for outdated packages, to reduce warning spam in Cirrus results (and lint output in general). We manage these version via dependabot, rather than lint warnings.
> [various] Add some more Java lint ignores

- packages/quick_actions/quick_actions/CHANGELOG.md
- packages/quick_actions/quick_actions/pubspec.yaml
Updates implementation packages for the recent major version bump.
Fixes https://github.com/flutter/flutter/issues/113225
[exempt from version …
> [quick_actions] Update dependency versions

- packages/shared_preferences/shared_preferences_android/CHANGELOG.md
- packages/shared_preferences/shared_preferences_android/lib/shared_preferences_android.dart
- packages/shared_preferences/shared_preferences_android/pubspec.yaml
Replaced `macOS` with `Android`
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-an …
> [shared_preferences] fix typo

- packages/file_selector/file_selector_platform_interface/CHANGELOG.md
- packages/file_selector/file_selector_platform_interface/lib/src/types/x_type_group/x_type_group.dart
- packages/file_selector/file_selector_platform_interface/pubspec.yaml
- packages/file_selector/file_selector_platform_interface/test/x_type_group_test.dart
- Update file_selector_platform_interface by adding the new property 'uniformTypeIdentifiers'.
- [Rename XTypeGroup's macUTIs #103743](https://github.com/flutter/flutter/issues/103743)
[Discord]: …
> [file_selector] Update file_selector_platform_interface by adding the new property 'uniformTypeIdentifiers' to the XTypeGroup.

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/example/lib/main.dart
- packages/camera/camera/example/pubspec.yaml
- packages/camera/camera/pubspec.yaml
Part of https://github.com/flutter/flutter/issues/111841
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugin …
> [camera] Remove usage of `_ambiguate` method in example

- script/tool/CHANGELOG.md
- script/tool/lib/src/publish_check_command.dart
- script/tool/pubspec.yaml
- script/tool/test/publish_check_command_test.dart
It seems that `dart pub publish --dry-run` is failing in `main` because dependencies for `example` directories are not being fetched, which is causing new analyze errors that weren't being surfaced before. See: https://github.com/dart-lang/pub/issues/3618.
This PR modifies the `publish-check` command to recurse into every example of each package being analyzed, and getting its dependencies before the actual `pub publish` command runs.
Works around: https://github.com/dart-lang/pub/issues/3618
- [~] I listed at least one issue that this PR fixes in the description above. …
> [tool] Get dependencies in package examples before publish check.

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/example/ios/RunnerTests/TranslatorTests.m
- packages/in_app_purchase/in_app_purchase_storekit/ios/Classes/FIAObjectTranslator.m
- packages/in_app_purchase/in_app_purchase_storekit/ios/Classes/InAppPurchasePlugin.m
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/in_app_purchase_storekit_platform.dart
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/types/app_store_purchase_param.dart
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_storekit/test/fakes/fake_storekit_platform.dart
- packages/in_app_purchase/in_app_purchase_storekit/test/in_app_purchase_storekit_platform_test.dart
- packages/in_app_purchase/in_app_purchase_storekit/test/store_kit_wrappers/sk_product_test.dart
- packages/in_app_purchase/in_app_purchase_storekit/test/store_kit_wrappers/sk_test_stub_objects.dart
Make iOS Promotional Offers in in_app_purchase plugin usable. `SKPaymentDiscountWrapper` was not being sent trough the method channel.
This is an update to an old (already closed) [PR here](https://github.com/flutter/plugins/pull/6099)
Resolves: [[in-app-purchase][iOS] Promotional Offers in iOS not working](https://github.com/flutter/flutter/issues/107533#issue-1303299545) …
> [in_app_purchase][iOS] fix iOS promotional offers (SKPaymentDiscountWrapper was not used properly)

- packages/file_selector/file_selector/CHANGELOG.md
- packages/file_selector/file_selector/README.md
- packages/file_selector/file_selector/example/lib/readme_standalone_excerpts.dart
- packages/file_selector/file_selector/pubspec.yaml
Adds the following:
- Table of supported platforms
- The missing GetDirectoryPath method example
_Table of supported platforms_
_GetDirectoryPath method example_
Related issue:
- [[file_selector] Documentation enhancements #111753](https://github.com/flutter/flutter/issues/111753)
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking …
> [file_selector] Include the missing GetDirectoryPath method example and table of supported platforms

- script/tool/lib/src/create_all_plugins_app_command.dart
- script/tool/test/create_all_plugins_app_command_test.dart
This change is a necessary precondition for https://github.com/flutter/plugins/pull/6517.
Adding support for macOS to `in_app_purchase` requires the macOS apps deployment target to be set to 10.15.
This PR makes the necessary changes to the `all-plugins-app` command.
Closes https://github.com/flutter/flutter/issues/113913 …
> [tool] Update tool to set macOS deployment target to 10.15.

- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart
- packages/camera/camera_platform_interface/lib/src/types/video_capture_options.dart
- packages/camera/camera_platform_interface/pubspec.yaml
This has been factored out of https://github.com/flutter/plugins/pull/6290 to isolate the interface changes. They are not wired up yet, as per the instructions at https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-platform-interface-method-parameters. I created a separate options object to make the interface easier to work with. I chose `startVideoCapturing` as a more generic method name that can be applied to both recording and streaming.
Related to https://github.com/flutter/flutter/issues/83634
> [camera] Interface method to allow concurrent recording and streaming of video

- .cirrus.yml
Temporarily disable starqlteue on firebase device lab to keep the roller running.
The starqlteue is having some infra issues. See [Firebase community slack test-lab channel](https://app.slack.com/client/T094HDHDX/C1MTSQ5QT) for discussions.
https://github.com/flutter/flutter/issues/114535 is created to track en-enabling the device. …
> [ci]Temporarily disable starqlteue on firebase device lab

- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/example/integration_test/video_player_test.dart
Added integration test for the aspect ratio bug. I've verified that old code failed this test, and the new code passed it. 
https://github.com/flutter/flutter/issues/109116 …
> [video_player]add integration test for inverted aspect ratio bug

- .ci.yaml
- .ci/targets/mac_darwin_lint_podspecs.yaml
- .ci/targets/mac_lint_podspecs.yaml
This is the first Mac target to be enabled in LUCI, and should be landed after recipes support CL: https://flutter-review.googlesource.com/c/recipes/+/35303
Bug: https://github.com/flutter/flutter/issues/114373
> Add `Mac_x64 darwin_lint_podspecs` to LUCI

- .ci.yaml
- .ci/scripts/create_simulator.sh
- .ci/targets/mac_ios_platform_tests.yaml
Part of https://github.com/flutter/flutter/issues/114373
> Enable Mac ios_platform_tests tests

- .ci.yaml
- .cirrus.yml
This is a follow up of
https://github.com/flutter/plugins/pull/6637
https://github.com/flutter/plugins/pull/6671
This PR enables these three tasks in LUCI prod and disables them from Cirrus:
```
darwin_lint_podspecs
build_all_plugins master
build_all_plugins stable
```
These three tasks have been passing consistently in CI:
https://ci.chromium.org/p/flutter/builders/staging/Mac_x64%20lint_podspecs
https://ci.chromium.org/p/flutter/builders/staging/Mac_x64%20build_all_plugins%20master
https://ci.chromium.org/p/flutter/builders/staging/Mac_x64%20build_all_plugins%20stable
(part of https://github.com/flutter/flutter/issues/114373)
> Switch Mac intel tasks from Cirrus to LUCI

- packages/file_selector/file_selector_platform_interface/CHANGELOG.md
- packages/file_selector/file_selector_platform_interface/lib/src/method_channel/method_channel_file_selector.dart
- packages/file_selector/file_selector_platform_interface/lib/src/platform_interface/file_selector_interface.dart
- packages/file_selector/file_selector_platform_interface/pubspec.yaml
- packages/file_selector/file_selector_platform_interface/test/file_selector_platform_interface_test.dart
- packages/file_selector/file_selector_platform_interface/test/method_channel_file_selector_test.dart
This PR adds the implementation of the method `getDirectoryPaths` to the `file_selector_platform_interface`.
Next, we will proceed this way:
1. Add implementations for Windows, macOS and Linux in parallel. (The Windows implementation will be done when the [Dart migration](https://github.com/flutter/plugins/pull/6568) is ready)
2. Add the new published version to the file_selector package with its example when at least one platform is published.
3. Repeat 2 when the other new implementations are published.
Issue:
[Support for selection of multiple directories, through desktop's native open panel, in 'file_selector' package #74323](https://github.com/flutter/flutter/issues/74323) …
> [file_selector] Add getDirectoryPaths method to the file_selector_platform_interface.

- packages/quick_actions/quick_actions_android/example/android/app/src/androidTest/java/io/flutter/plugins/quickactionsexample/QuickActionsTest.java
Fixes https://github.com/flutter/flutter/issues/110022.
The test checks for the [content description](https://developer.android.com/reference/android/view/View#attr_android:contentDescription) of the app bar, which is not being explicitly set and thus, includes undetermined accessibility information about the app bar. To combat this issue, this changes the search for the expected description to look for containment within the entirety of the content description versus an exact match. …
> [quick_actions] Fix Android integration test flake

- packages/google_sign_in/google_sign_in_android/CHANGELOG.md
- packages/google_sign_in/google_sign_in_android/lib/google_sign_in_android.dart
- packages/google_sign_in/google_sign_in_android/pubspec.yaml
- packages/google_sign_in/google_sign_in_android/test/google_sign_in_android_test.dart
- packages/google_sign_in/google_sign_in_ios/CHANGELOG.md
- packages/google_sign_in/google_sign_in_ios/lib/google_sign_in_ios.dart
- packages/google_sign_in/google_sign_in_ios/pubspec.yaml
- packages/google_sign_in/google_sign_in_ios/test/google_sign_in_ios_test.dart
This PR compliments https://github.com/flutter/plugins/pull/5250 and https://github.com/flutter/plugins/pull/6034 to fully implement passing `serverClientId` to the native libs during channelled call.
Current implementation works fine if the value is provided via the corresponding plist / json file. But if provided via code only – it doesn't work properly. This PR addresses that problem.
Fixes https://github.com/flutter/flutter/issues/110099
[CLA]: …
> [google_sign_in] Correctly passes `serverClientId` to native libs

- .cirrus.yml
- script/install_chromium.sh
Brings over the newer flutter/packages version of install_chromium.sh as part of pre-aligning the repositories for later merging.
Thing imports the script and the .cirrus.yaml template without any changes.
Part of https://github.com/flutter/flutter/issues/113764 …
> [ci] Import flutter/packages install_chromium.sh

- packages/path_provider/path_provider_android/CHANGELOG.md
- packages/path_provider/path_provider_android/android/build.gradle
- packages/path_provider/path_provider_android/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java
- packages/path_provider/path_provider_android/pubspec.yaml
The last necessary use of Guava in the plugin was removed in #5959, but the dependency itself wasn't removed; this cleans up the unnecessary dependency (replacing the Guava-sourced `Nullability` annotation with the version from `androidx.annotations`, which we are already importing).
Fixes https://github.com/flutter/flutter/issues/115462
[Discord]: …
> [path_provider] Remove unused Guava dependency

- packages/google_maps_flutter/google_maps_flutter_ios/example/ios/RunnerUITests/GoogleMapsUITests.m
Re-able the test that triggers system alert as it seems not failing anymore in newest iOS versions.
fixes: https://github.com/flutter/flutter/issues/93325 …
> [google_maps_flutter] ios: re-enable test with popup

- packages/google_maps_flutter/google_maps_flutter_ios/example/ios/RunnerUITests/GoogleMapsUITests.m
Reverts flutter/plugins#5312 to unblock the tree.
Failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_x64%20ios_platform_tests_1_of_4%20stable/17/overview
> Revert "[google_maps_flutter] ios: re-enable test with popup"

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java
- packages/camera/camera_android/android/src/test/java/io/flutter/plugins/camera/CameraPermissionsTest.java
- packages/camera/camera_android/pubspec.yaml
This PR handles a special situation where the grantResults array could be empty when asking for permissions.
Fixes https://github.com/flutter/flutter/issues/116047 …
> [camera] Handle empty grantResults on permission request

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/Camera.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/MethodCallHandlerImpl.java
- packages/camera/camera_android/example/integration_test/camera_test.dart
- packages/camera/camera_android/example/lib/camera_controller.dart
- packages/camera/camera_android/example/pubspec.yaml
- packages/camera/camera_android/lib/src/android_camera.dart
- packages/camera/camera_android/pubspec.yaml
- packages/camera/camera_android/test/android_camera_test.dart
- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/integration_test/camera_test.dart
- packages/camera/camera_avfoundation/example/lib/camera_controller.dart
- packages/camera/camera_avfoundation/ios/Classes/CameraPlugin.m
- packages/camera/camera_avfoundation/ios/Classes/FLTCam.h
- packages/camera/camera_avfoundation/ios/Classes/FLTCam.m
- packages/camera/camera_avfoundation/lib/src/avfoundation_camera.dart
- packages/camera/camera_avfoundation/pubspec.yaml
- packages/camera/camera_avfoundation/test/avfoundation_camera_test.dart
- packages/camera/camera_platform_interface/CHANGELOG.md
- packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
- packages/camera/camera_platform_interface/pubspec.yaml
- packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart
- packages/camera/camera_web/CHANGELOG.md
- packages/camera/camera_web/example/integration_test/camera_web_test.dart
- packages/camera/camera_web/lib/src/camera_web.dart
- packages/camera/camera_web/pubspec.yaml
- packages/camera/camera_windows/CHANGELOG.md
- packages/camera/camera_windows/lib/camera_windows.dart
- packages/camera/camera_windows/pubspec.yaml
- packages/camera/camera_windows/test/camera_windows_test.dart
This re-enables the functionality from https://github.com/flutter/plugins/pull/6290, which was reverted in https://github.com/flutter/plugins/pull/6796 due to a broken test. This PR will attempt to fix the integration test.
Closes https://github.com/flutter/flutter/issues/83634
> [camera] Re-enable ability to concurrently record and stream video

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player/pubspec.yaml
- packages/video_player/video_player/test/video_player_test.dart
- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/example/lib/mini_controller.dart
- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/example/lib/mini_controller.dart
- packages/video_player/video_player_platform_interface/CHANGELOG.md
- packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
- packages/video_player/video_player_platform_interface/pubspec.yaml
Fixes construction of file URIs by using the relevant `Uri` constructor; since file URIs are URIs, they require escaping, so can't be correctly constructed with naive string interpolation.
Fixes https://github.com/flutter/flutter/issues/105950 …
> [video_player] Fix file URI construction

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/package_state_utils.dart
- script/tool/pubspec.yaml
- script/tool/test/common/package_state_utils_test.dart
Pigeon has an usual test structure since it generates test code to run in a dummy plugin; add that structure to the list of recognized tests so that changes to its platform tests won't be flagged by `version-check`.
[exempt from version …
> [tools] Recognize Pigeon tests in version-check

- packages/camera/camera_android/example/integration_test/camera_test.dart
The recently added "recording with image stream" test is very flaky, often throwing on `stop`. This is a speculative fix for that flake based on the documentation of `stop` indicating that it will throw if nothing has been recorded. …
> [camera] Attempt to fix flaky new Android test

- packages/google_maps_flutter/google_maps_flutter_ios/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios/Podfile
- packages/google_maps_flutter/google_maps_flutter_ios/example/ios/RunnerUITests/GoogleMapsUITests.m
Reland https://github.com/flutter/plugins/pull/5312
The accessibility type for the flutter text buttons are changed from buttons to texts.
Fixes https://github.com/flutter/flutter/issues/93325 …
> Reland "[google_maps_flutter] ios: re-enable test with popup #5312"

- packages/camera/camera_android_camerax/lib/src/camera_selector.dart
- packages/camera/camera_android_camerax/lib/src/process_camera_provider.dart
Fix new `unnecessary_parenthesis` diagnostics.
These will get flagged w/ the latest linter.
See, [try failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8794866247739072257/+/u/analyze_flutter_plugins/stdout) and [linter roll PR](https://dart-review.googlesource.com/c/sdk/+/275044).  …
> [camera_android_camerax] `unnecessary_parenthesis` lint fix

- packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart
Fixes timeouts caused by a race condition when loading a page. In pre-4.0 webview_flutter, the widget was passed the initial url, so we were able to call `await pageLoads.stream.first;` before the page was loaded. 
However, these tests would load the url before we could call `await pageLoads.stream.first;`, leading to a timeout.
This could also be responsible for the test crashes, but I'll keep an eye on the CI to make sure.
Edit: Tests passed first time, so this could be the only fixed needed! …
> [webview_flutter_android] Fix timeouts in the integration tests

- script/tool/CHANGELOG.md
- script/tool/lib/src/create_all_packages_app_command.dart
- script/tool/lib/src/format_command.dart
- script/tool/lib/src/main.dart
- script/tool/pubspec.yaml
- script/tool/test/format_command_test.dart
1. When `clang-format` does not run (i.e. failing `chromium/depot_tools/clang-format`, loop through all the `clang-format` executables in the PATH until a working one is found.  If none run then bail with the same error as before.
2. Running `pub global...` fails with `command not found: pub`.  Update `pub global` instructions to `dart pub global`.
Fixes https://github.com/flutter/flutter/issues/117195 …
> [flutter_plugin_tools] If `clang-format` does not run, fall back to other executables in PATH

- packages/video_player/video_player/CHANGELOG.md
- packages/video_player/video_player/pubspec.yaml
- packages/video_player/video_player/test/video_player_test.dart
- packages/video_player/video_player_android/CHANGELOG.md
- packages/video_player/video_player_android/example/pubspec.yaml
- packages/video_player/video_player_android/pubspec.yaml
- packages/video_player/video_player_avfoundation/CHANGELOG.md
- packages/video_player/video_player_avfoundation/example/pubspec.yaml
- packages/video_player/video_player_avfoundation/pubspec.yaml
- packages/video_player/video_player_web/CHANGELOG.md
- packages/video_player/video_player_web/example/pubspec.yaml
- packages/video_player/video_player_web/pubspec.yaml
#6341 did a major version bump of the platform interface to delete the default method channel implementation, but I never updated the other packages in the plugin to allow using it. For the implementation packages, it's a pure no-op. The app-facing package had tests that relied on the `buildView` implementation of the default implementation; this updates the tests to use a fake instead so that those tests pass even without a real default implementation. …
> [video_player] Add compatibility with the current platform interface

- packages/image_picker/image_picker_ios/CHANGELOG.md
- packages/image_picker/image_picker_ios/example/ios/RunnerTests/ImagePickerPluginTests.m
- packages/image_picker/image_picker_ios/example/ios/RunnerTests/PhotoAssetUtilTests.m
- packages/image_picker/image_picker_ios/example/ios/RunnerTests/PickerSaveImageToPathOperationTests.m
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerImageUtil.m
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerMetaDataUtil.m
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPhotoAssetUtil.m
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin.h
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin.m
- packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin_Test.h
- packages/image_picker/image_picker_ios/ios/Classes/FLTPHPickerSaveImageToPathOperation.h
- packages/image_picker/image_picker_ios/ios/Classes/FLTPHPickerSaveImageToPathOperation.m
- packages/image_picker/image_picker_ios/pubspec.yaml
Previously, if there was an error loading the image, the result callback would never be called, and the `callContext` would not be nil'd out.  When the next request happened, the user would get a confusing `multiple_request` error because the last state wasn't cleared out.
https://github.com/flutter/plugins/blob/2cbb314d99d800cb4e1229ce6b304755303bbd64/packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin.m#L273-L277
Now, when there is an error loading an image, pipe an error back to the flutter result instead of silently failing and never calling the result callback.  This also `nil`s out the `callContext` so the next request has a chance of succeeding.
https://github.com/flutter/plugins/blob/2cbb314d99d800cb4e1229ce6b304755303bbd64/packages/image_picker/image_picker_ios …
> [image_picker_ios] Pass through error message from image saving

- packages/camera/camera/CHANGELOG.md
- packages/camera/camera/lib/src/camera_controller.dart
- packages/camera/camera/pubspec.yaml
- packages/camera/camera/test/camera_preview_test.dart
- packages/camera/camera/test/camera_test.dart
- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/example/lib/camera_controller.dart
- packages/camera/camera_android/pubspec.yaml
- packages/camera/camera_avfoundation/CHANGELOG.md
- packages/camera/camera_avfoundation/example/lib/camera_controller.dart
- packages/camera/camera_avfoundation/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/117403.
Removes deprecated [`Optional` type ](https://pub.dev/documentation/quiver/latest/quiver.core/Optional-class.html) from camera plugin to fix failing framework `Linux_plugins` test., e.g. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8794239165172938017/+/u/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/test_stdout. …
> [camera] Remove deprecated Optional type

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/README.md
- packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_android/lib/src/android_webview_controller.dart
- packages/webview_flutter/webview_flutter_android/lib/src/platform_views_service_proxy.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/test/android_webview_controller_test.dart
- packages/webview_flutter/webview_flutter_android/test/android_webview_controller_test.mocks.dart
Work around for https://github.com/flutter/flutter/issues/104889
Fixes https://github.com/flutter/flutter/issues/108106
[exempt from version …
> [webview_flutter_android] Adds support for selecting Hybrid Composition

- packages/webview_flutter/webview_flutter_web/CHANGELOG.md
- packages/webview_flutter/webview_flutter_web/README.md
- packages/webview_flutter/webview_flutter_web/lib/src/web_webview_platform.dart
- packages/webview_flutter/webview_flutter_web/pubspec.yaml
- packages/webview_flutter/webview_flutter_web/test/webview_flutter_web_test.dart
Fixes https://github.com/flutter/flutter/issues/117482
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins- …
> [webview_flutter_web] Adds auto registration of the `WebViewPlatform` implementation

- packages/webview_flutter/webview_flutter_platform_interface/CHANGELOG.md
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_navigation_delegate.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_webview_controller.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_webview_cookie_manager.dart
- packages/webview_flutter/webview_flutter_platform_interface/lib/src/platform_webview_widget.dart
- packages/webview_flutter/webview_flutter_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_platform_interface/test/webview_platform_test.dart
In light of https://github.com/flutter/flutter/issues/117422, the error message when using `webview_flutter` with unit tests is not very helpful. This creates a more actionable error message. …
> [webview_flutter_platform_interface] Improves error message when `WebViewPlatform.instance` is null

- script/tool/CHANGELOG.md
- script/tool/lib/src/format_command.dart
- script/tool/pubspec.yaml
- script/tool/test/format_command_test.dart
`flutter format` is deprecated on `master`, and prints a warning saying to switch to `dart format` instead. This updates `format` to make that switch. `flutter format` is essentially just a passthrough, so no usage changes are needed. …
> [tool] Replace `flutter format`

- script/tool/lib/src/update_excerpts_command.dart
- script/tool/test/update_excerpts_command_test.dart
When determining whether or not to fail with `--fail-on-change`, only look at .md files. In some cases, running the necessary commands (e.g., `flutter pub get`) may change unrelated files, causing fales positive failures. Only changed documentation files should be flagged.
Also log the specific files that were detected as changed, to aid in debugging any future false positives.
Fixes https://github.com/flutter/flutter/issues/111592
Fixes https://github.com/flutter/flutter/issues/111590 …
> [tool] Fix false positives in update-exceprts

- packages/webview_flutter/webview_flutter_android/CHANGELOG.md
- packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/JavaObjectHostApiImpl.java
- packages/webview_flutter/webview_flutter_android/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewHostApiImpl.java
- packages/webview_flutter/webview_flutter_android/android/src/test/java/io/flutter/plugins/webviewflutter/WebViewTest.java
- packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_android/pubspec.yaml
Bug is fixed by not calling `destroy()` when the widget is disposed.
This shouldn't cause a regression since we were calling it incorrectly in 4.0 and pre 4.0 anyways. We could consider offering a `AndroidWebViewController.destoryWebView()` if the community shows interest in using this method.
Fixes the issue https://github.com/flutter/flutter/issues/117887 for WebView …
> [android_webview_controller] Fixes bug where an `AndroidController` couldn't be reused

- packages/path_provider/path_provider/CHANGELOG.md
- packages/path_provider/path_provider/README.md
- packages/path_provider/path_provider/example/integration_test/path_provider_test.dart
- packages/path_provider/path_provider/lib/path_provider.dart
- packages/path_provider/path_provider/pubspec.yaml
- script/configs/exclude_all_plugins_app.yaml
Switches to using the new combined `path_provider_foundation` for iOS and macOS.
Also updates the code documentation to make it less Android and iOS specific. The original goal was to make the documentation for the download directory not be actively wrong for the new implementation, but it seemed like a good time to fix 76427 more generally. (The fact that the docs are kind of a mess because the API itself is kind of a mess is now
https://github.com/flutter/flutter/issues/118712.)
Updates the documentation for `getDownloadsDirectory` to indicate that it doesn't necessarily return a directory that already exists. This seems to be the case for iOS, but was also already potentially true for Linux.
Fixes flutter/flutter#117941
Fixes https://github.com/flutter/flutter/issues/76427
[Contributor …
> [path_provider] Switch to `path_provider_foundation`

- packages/ios_platform_images/CHANGELOG.md
- packages/ios_platform_images/lib/ios_platform_images.dart
- packages/ios_platform_images/pubspec.yaml
In preparation for flutter/flutter#118966
> Ignore deprecated member use on DecoderBufferCallback

- .cirrus.yml
- packages/file_selector/file_selector/example/pubspec.yaml
- packages/file_selector/file_selector_ios/example/pubspec.yaml
- packages/file_selector/file_selector_linux/example/pubspec.yaml
- packages/flutter_plugin_android_lifecycle/example/pubspec.yaml
- packages/path_provider/path_provider_foundation/CHANGELOG.md
- packages/path_provider/path_provider_foundation/pubspec.yaml
- packages/plugin_platform_interface/CHANGELOG.md
- packages/plugin_platform_interface/pubspec.yaml
- packages/webview_flutter/webview_flutter_android/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_web/example/pubspec.yaml
- packages/webview_flutter/webview_flutter_wkwebview/example/pubspec.yaml
- script/tool/CHANGELOG.md
- script/tool/lib/src/pubspec_check_command.dart
- script/tool/pubspec.yaml
- script/tool/test/pubspec_check_command_test.dart
Adds options to `pubspec.yaml` to check that the minimum supported SDK range for Flutter/Dart is at least a given version, to add CI enforcement that we're updating all of our support claims when we update our tested versions (rather than it being something we have to remember to do), and enables it in CI.
As part of enabling it, fixes some violations:
- path_provider_foundation had been temporarily dropped back to 2.10 as part of pushing out a regression fix.
- a number of examples were missing Flutter constraints even though they used Flutter.
- the non-Flutter `plugin_platform_interface` package hadn't been update since I hadn't thought about Dart-only constraints in the past. …
> [tool/ci] Add minimum supported SDK validation

- .ci.yaml
`platform_tests` are our most time-consuming tests; 30 minutes isn't always enough to run them. Increase timeouts to 60 minutes so that we aren't getting timeouts from tests that are still running.
Hopefully this will resolve the recent post-submit failures.
Also disables Windows `platform_tests` for stable in presubmit, matching other platforms.
> [ci] Increase timeouts for platform_tests

- script/tool/CHANGELOG.md
- script/tool/lib/src/common/package_command.dart
- script/tool/pubspec.yaml
- script/tool/test/common/package_command_test.dart
Currently main-branch detection for `--packages-for-branch` looks at branch names, but this no longer works on LUCI which now seems to be checking out specific hashes rather than branches. This updates the behavior so that it will treat any hash that is an ancestor of `main` as being part of `main`, which should allow post-submit detection to work under LUCI.
Fixes https://github.com/flutter/flutter/issues/119330 …
> [tool] Improve main-branch detection

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_android/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/example/lib/main.dart
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
https://github.com/flutter/flutter/pull/119195 will make a few more widgets const. This prepares the examples of the `in_app_purchase` plugin for that change.
I chose to ignore the resulting lint for now to ensure that the examples continue to work on older versions of Flutter. Once the change referenced above is part of the oldest Flutter version supported by the plugins, we can resolve the TODO, remove the ignore, and make the widgets in question const.
> [in_app_purchase] Prep for more const widgets

- .ci.yaml
Adds Intel versions of iOS build-all and ARM versions of iOS platform tests, as part one of swapping them. Once the new tasks propagate, they will be brought out of bringup mode and the old versions removed.
These were on the opposite architectures because of issues with running the platform tests on Cirrus ARM VMs, and then were ported as-is from Cirrus to LUCI, but now that macOS ARM works on LUCI we can switch to the desired configuration.
Also increases sharding from 4 to 5 since the tests have gotten longer over time due to increased testing and more federation, and changes the naming scheme to be more future-proof.
> [ci] Part 1 of swapping iOS platform test arch

- script/tool/lib/src/common/package_command.dart
- script/tool/pubspec.yaml
- script/tool/test/common/package_command_test.dart
Follow-up to https://github.com/flutter/plugins/pull/7038 to try to make it work on LUCI. Looking at the checkout steps of a LUCI run, it looks like we do a full `fetch` of `origin`, but likely only have a `master` branch locally. Rather than rely on a specific local branch name existing, this allows for checking `origin` (and just in case, since it's another common remote name, `upstream`).
Hopefully fixes https://github.com/flutter/flutter/issues/119330
> [tool] More main-branch detection improvement

- analysis_options.yaml
Removes some options that are no longer necessary, further aligning the options with flutter/packages.
This is (at least for now) the last of the diffs that need to be changed on this side; the handful of remaining diffs will be address in flutter/packages.
Part of https://github.com/flutter/flutter/issues/113764
> [ci] Clean up analysis options

- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/FIAPReceiptManager.m
- packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/InAppPurchasePluginTests.m
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
Prevent crash when `appStoreReceiptURL` is nil. Retrieve receipt is documented as nullable in https://developer.apple.com/documentation/foundation/nsbundle/1407276-appstorereceipturl
Fixes https://github.com/flutter/flutter/issues/117842
[Discord]: …
> [in_app_puchase_storekit] handle `appStoreReceiptURL` is nil

- packages/camera/camera_android/example/lib/main.dart
- packages/camera/camera_android/test/android_camera_test.dart
- packages/camera/camera_avfoundation/example/lib/main.dart
- packages/camera/camera_avfoundation/test/avfoundation_camera_test.dart
- packages/google_maps_flutter/google_maps_flutter_android/test/google_maps_flutter_android_test.dart
- packages/google_maps_flutter/google_maps_flutter_ios/test/google_maps_flutter_ios_test.dart
- packages/google_maps_flutter/google_maps_flutter_platform_interface/test/method_channel/method_channel_google_maps_flutter_test.dart
- packages/url_launcher/url_launcher/lib/src/legacy_api.dart
- packages/url_launcher/url_launcher/test/src/legacy_api_test.dart
- packages/url_launcher/url_launcher_platform_interface/lib/link.dart
- packages/video_player/video_player/lib/video_player.dart
- packages/video_player/video_player_android/test/android_video_player_test.dart
- packages/video_player/video_player_avfoundation/test/avfoundation_video_player_test.dart
[following repository CHANGELOG style]: …
> [camera][google_maps_flutter][path_provider] prepare for TestDefaultBinaryMessengerBinding.instance becoming non-nullable

- packages/google_maps_flutter/google_maps_flutter/test/map_creation_test.dart
- packages/local_auth/local_auth/example/lib/main.dart
- packages/local_auth/local_auth_android/example/lib/main.dart
- packages/local_auth/local_auth_ios/example/lib/main.dart
- packages/local_auth/local_auth_windows/example/lib/main.dart
- packages/url_launcher/url_launcher/example/lib/encoding.dart
Similar to https://github.com/flutter/plugins/pull/7030.
https://github.com/flutter/flutter/pull/119673 will make a few more widgets const. This prepares the plugins repo for that change.
I chose to ignore the resulting lint for now to ensure that the plugins continue to work on older versions of Flutter. Once the change referenced above is part of the oldest Flutter version supported by the plugins, we can resolve the TODO, remove the ignore, and make the widgets in question const.
> [various] prepare for more const widgets

- packages/camera/camera_android/CHANGELOG.md
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/Camera.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java
- packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/media/MediaRecorderBuilder.java
- packages/camera/camera_android/android/src/test/java/io/flutter/plugins/camera/features/resolution/ResolutionFeatureTest.java
- packages/camera/camera_android/pubspec.yaml
Lets the resolution feature default to legacy behavior when new behavior using `EncoderProfiles` fails. This is an Android issue that has been fixed in recent build releases, but this temporarily fix the issue while folks are still using older versions.
Loosely based on https://github.com/flutter/plugins/pull/6867 by @MbIXjkee.
Fixes https://github.com/flutter/flutter/issues/109769. …
> [camera_android] Default to legacy recording profile when EncoderProfiles unavailable

- packages/webview_flutter/webview_flutter_web/CHANGELOG.md
- packages/webview_flutter/webview_flutter_web/README.md
- packages/webview_flutter/webview_flutter_web/example/integration_test/webview_flutter_test.dart
- packages/webview_flutter/webview_flutter_web/example/run_test.sh
- packages/webview_flutter/webview_flutter_web/lib/src/content_type.dart
- packages/webview_flutter/webview_flutter_web/lib/src/web_webview_controller.dart
- packages/webview_flutter/webview_flutter_web/pubspec.yaml
- packages/webview_flutter/webview_flutter_web/test/content_type_test.dart
- packages/webview_flutter/webview_flutter_web/test/web_webview_controller_test.dart
- packages/webview_flutter/webview_flutter_web/test/web_webview_controller_test.mocks.dart
This PR:
* Updates `WebWebViewController.loadRequest` to only set the src of the iFrame when `LoadRequestParams.headers` and `LoadRequestParams.body` are empty and is using the HTTP GET request method.
* Parses the `content-type` header of XHR responses to extract the correct MIME-type and charset.
* Sets `width` and `height` of widget the way the Flutter engine wants, to remove distracting warnings from the development console.
Fixes https://github.com/flutter/flutter/issues/118573
Fixes https://github.com/flutter/flutter/issues/118090
[relevant style …
> [webview_flutter_web] Avoids XHR when possible.

- CODEOWNERS
Updates CODEOWNERS for the cross-platform/app-facing portions of plugins based to reflect changes in focus.
> Redistribute ownership of cross-platform plugin components

- packages/local_auth/local_auth/example/android/app/build.gradle
- packages/local_auth/local_auth_android/example/android/app/build.gradle
androidx now requires Java compile version 33. This is currently blocking all pr's and keeping the tree red. This should fix the issue.
> [local_auth_android] update java complie sdk version to green tree

- script/tool/lib/src/update_release_info_command.dart
If you make a fresh branch and have not ever used `git pull` or `git fetch` the tool assumes you have a git reference that does not exist.  In addition to logging the bug with the hope that a stack trace google search can find the bug with a work around I added a comment in the code on the line that is closest to the actual problem but is still present in the printed stack trace.  …
> Update code documentation for failing case no valid object FETCH_HEAD

- packages/google_maps_flutter/google_maps_flutter_android/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/ConvertTest.java
- packages/google_maps_flutter/google_maps_flutter_android/pubspec.yaml
Fixes points losing precision when converting to LatLng. The points were losing precision as they were converted to float instead of double. 
https://github.com/flutter/flutter/issues/94146 …
> [google_maps_flutter_android] Fixes points losing precision when converting to LatLng

- packages/google_sign_in/google_sign_in_android/CHANGELOG.md
- packages/google_sign_in/google_sign_in_android/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/google_sign_in_android/android/src/test/java/io/flutter/plugins/googlesignin/GoogleSignInTest.java
- packages/google_sign_in/google_sign_in_android/pubspec.yaml
1) Use switch instead of if/else and show all possible states
2) Handle the case of synchronous failure in signInSilently()
by checking isComplete() instead of isSuccessful()
> [google_sign_in] Slight cleanup in GoogleSignInPlugin

- packages/camera/camera/example/android/gradle.properties
- packages/camera/camera_android/example/android/gradle.properties
- packages/camera/camera_android_camerax/example/android/gradle.properties
- packages/espresso/example/android/gradle.properties
- packages/flutter_plugin_android_lifecycle/example/android/gradle.properties
- packages/google_maps_flutter/google_maps_flutter/example/android/gradle.properties
- packages/google_maps_flutter/google_maps_flutter_android/example/android/gradle.properties
- packages/google_sign_in/google_sign_in/example/android/gradle.properties
- packages/google_sign_in/google_sign_in_android/example/android/gradle.properties
- packages/image_picker/image_picker/example/android/gradle.properties
- packages/image_picker/image_picker_android/example/android/gradle.properties
- packages/in_app_purchase/in_app_purchase/example/android/gradle.properties
- packages/in_app_purchase/in_app_purchase_android/example/android/gradle.properties
- packages/local_auth/local_auth/example/android/gradle.properties
- packages/local_auth/local_auth_android/example/android/gradle.properties
- packages/path_provider/path_provider/example/android/gradle.properties
- packages/path_provider/path_provider_android/example/android/gradle.properties
- packages/quick_actions/quick_actions/example/android/gradle.properties
- packages/quick_actions/quick_actions_android/example/android/gradle.properties
- packages/shared_preferences/shared_preferences/example/android/gradle.properties
- packages/shared_preferences/shared_preferences_android/example/android/gradle.properties
- packages/url_launcher/url_launcher/example/android/gradle.properties
- packages/url_launcher/url_launcher_android/example/android/gradle.properties
- packages/video_player/video_player/example/android/gradle.properties
- packages/video_player/video_player_android/example/android/gradle.properties
- packages/webview_flutter/webview_flutter/example/android/gradle.properties
- packages/webview_flutter/webview_flutter_android/example/android/gradle.properties
Speculative fix for the intermittent Android OOM build errors. Raises the JVM limit for the Gradle builds of our example apps.
4GB should be enough for anyone!
> [various] Raise JVM limit in example builds

- packages/google_maps_flutter/google_maps_flutter_android/CHANGELOG.md
- packages/google_maps_flutter/google_maps_flutter_android/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/google_maps_flutter_android/android/src/test/java/io/flutter/plugins/googlemaps/GoogleMapControllerTest.java
- packages/google_maps_flutter/google_maps_flutter_android/pubspec.yaml
[google_maps_flutter_android] Fixes initial padding not working while map has not been created yet.
https://github.com/flutter/flutter/issues/43721
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaki …
> [google_maps_flutter_android] Fixes initial padding not working while map has not been created yet.

- packages/in_app_purchase/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase/README.md
- packages/in_app_purchase/in_app_purchase/example/ios/Flutter/AppFrameworkInfo.plist
- packages/in_app_purchase/in_app_purchase/example/ios/Podfile
- packages/in_app_purchase/in_app_purchase/example/ios/Runner.xcodeproj/project.pbxproj
- packages/in_app_purchase/in_app_purchase/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/in_app_purchase/in_app_purchase/example/ios/Runner/Info.plist
- packages/in_app_purchase/in_app_purchase/pubspec.yaml
- packages/in_app_purchase/in_app_purchase_storekit/CHANGELOG.md
- packages/in_app_purchase/in_app_purchase_storekit/darwin/in_app_purchase_storekit.podspec
- packages/in_app_purchase/in_app_purchase_storekit/example/ios/Flutter/AppFrameworkInfo.plist
- packages/in_app_purchase/in_app_purchase_storekit/example/ios/Podfile
- packages/in_app_purchase/in_app_purchase_storekit/example/ios/Runner.xcodeproj/project.pbxproj
- packages/in_app_purchase/in_app_purchase_storekit/example/ios/Runner/Info.plist
- packages/in_app_purchase/in_app_purchase_storekit/example/shared/RunnerTests/TranslatorTests.m
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/types/app_store_product_details.dart
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/types/app_store_purchase_details.dart
- packages/in_app_purchase/in_app_purchase_storekit/lib/src/types/app_store_purchase_param.dart
- packages/in_app_purchase/in_app_purchase_storekit/pubspec.yaml
`in_app_purchase` part of https://github.com/flutter/flutter/issues/101965.
Built the `in_app_purchase` and `in_app_purchase_ios` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.
[Discord]: …
> [in_app_purchase] Update minimum Flutter version to 3.3 and iOS 11

- packages/image_picker/image_picker/CHANGELOG.md
- packages/image_picker/image_picker/README.md
- packages/image_picker/image_picker/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/113603
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins- …
> [image_picker] Update NSPhotoLibraryUsageDescription description in README

- packages/google_sign_in/google_sign_in/CHANGELOG.md
- packages/google_sign_in/google_sign_in/pubspec.yaml
This PR endorses the new major version of the `google_sign_in_web` package (`^0.11.0`), which migrates developers to the new **Google Identity Services SDK**.
This PR bumps the major version of the `google_sign_in` package to `6.0.0`, so users of the web version have a heads up before they land a major change.
The change should be completely transparent in every platform other than web.
* Fixes: https://github.com/flutter/flutter/issues/88084
* All existing tests should pass.
* Deployed a test build of the `example` app:
* https://dit-gis-test.web.app
* The migration guide has already been published in the [README of the `google_sign_in_web` package](https://pub.dev/packages/google_sign_in_web#migrating-to-v011-google-identity-services), and has been linked in the CHANGELOG of this …
> [google_sign_in] Endorses next web package.

- CONTRIBUTING.md
- README.md
This will be landed once the merge is landed, before archiving this repository, to point people to the new location.
> Update READMEs for archiving
