flutter/plugins

- packages/url-launcher/README.md
First draft. A short guide/one-liner which we discussed could replace what is written in the Usage section.
> Update url_launcher README

- packages/path-provider/CHANGELOG.md
- packages/path-provider/android/build.gradle
- packages/path-provider/example/android/app/build.gradle
- packages/path-provider/pubspec.yaml
- packages/shared-preferences/CHANGELOG.md
- packages/shared-preferences/android/build.gradle
- packages/shared-preferences/example/android/app/build.gradle
- packages/shared-preferences/pubspec.yaml
- packages/url-launcher/CHANGELOG.md
- packages/url-launcher/android/build.gradle
- packages/url-launcher/example/android/app/build.gradle
- packages/url-launcher/pubspec.yaml
To match https://github.com/flutter/flutter/pull/9922
> Update all plugins to use Android SDK Build Tools 25.0.3

- packages/url-launcher/CHANGELOG.md
- packages/url-launcher/README.md
- packages/url-launcher/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/10060
> Fix url_launcher README.md

- packages/path-provider/CHANGELOG.md
- packages/path-provider/android/src/main/java/io/flutter/plugins/path_provider/PathProviderPlugin.java
- packages/path-provider/example/lib/main.dart
- packages/path-provider/lib/path_provider.dart
- packages/path-provider/pubspec.yaml
Android supports accessing the "external" storage medium. Support
finding this path in flutter with a method call in path_provider
I am interested in writing a flutter app that will access some files a user may have put on their device manually (android). This necessitates looking up the path for the external storage. Though I could do the same thing in my own package, I figured it would be more useful to have this functionality in the path provider package so it can be more broadly used. Sadly this functionality is restricted to android only, as iOS does not let you escape the app sandbox. If there is some other mechanism you would prefer me to go through instead of just creating a pull request, please let me know.
> Add method for external storage

- packages/shared_preferences/android/build.gradle
- packages/shared_preferences/android/src/main/java/io/flutter/plugins/shared_preferences/SharedPreferencesPlugin.java
When I added this plugin as a dependency, I started getting `Xlint:unchecked` compiler warnings. This stops them.
Due to the position in the flutter architecture (between dart/java) I'm not sure if there's a better approach than just suppressing the warnings at the top.
> shared_preferences: Expand and suppress unchecked warnings

- packages/google_sign_in/example/lib/main.dart
Without this parameter the server responds with a 400 error informing
about the malformed request and displaying the error on the page.
The error message in the json response is:
"Request mask can not be empty. Valid paths are: [person.adresses,
person.age_ranges....
> Add request mask to the example People API url

- packages/firebase_auth/example/lib/main.dart
I think matching the Google sign-in private member might provide more consistency in context between the two plugins. I'm comparing this member: https://github.com/branflake2267/plugins/blob/master/packages/google_sign_in/example/lib/main.dart#L9
> Match the google sign in plugin private member initialization.

- .travis.yml
Currently it's hard to tell which job is which in the Build Jobs list as no env variables are set.
> Add env variables to each matrix entry

- README.md
Another iteration. One of these can be closed. 
This is using the table with a division to separate the FlutterFire plugins.
> Added pub and separated FlutterFire plugins

- packages/firebase_auth/README.md
Adding the Google sign-in dependency instructions.
> Add more instructions to firebase_auth

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/lib/src/database_reference.dart
- packages/firebase_database/lib/src/event.dart
- packages/firebase_database/lib/src/firebase_database.dart
- packages/firebase_database/lib/src/query.dart
- packages/firebase_database/pubspec.yaml
- packages/firebase_database/test/firebase_database_test.dart
Fixes flutter/flutter#10411 
Fixes flutter/flutter#10421
> Improved API support for Firebase Database.

- packages/google_sign_in/android/build.gradle
- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/example/android/app/src/main/java/io/flutter/plugins/googlesigninexample/MainActivity.java
Since auto-managed activities in the GMS Auth API require the
use of `android.support.v4.app.FragmentActivity`, this change
updates the plugin to require their use as well. This shouldn't
be a burden on app authors anymore, since the Flutter engine
now provides `FlutterFragmentActivity`
> Update GoogleSignInPlugin to require the use of support-v4

- packages/battery/pubspec.yaml
- packages/firebase_analytics/pubspec.yaml
- packages/firebase_auth/pubspec.yaml
- packages/firebase_database/pubspec.yaml
- packages/firebase_messaging/pubspec.yaml
- packages/google_sign_in/pubspec.yaml
- packages/path_provider/pubspec.yaml
- packages/shared_preferences/pubspec.yaml
- packages/url_launcher/pubspec.yaml
This fixes recent test failures that only occur on 0.12.22.
We can look into these separately, but in the meantime this
fixes the build.
> Pin package:test to 0.12.21

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/example/ios/Runner/AppDelegate.m
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- packages/google_sign_in/pubspec.yaml
* Ignore "Broken pipe" errors affecting simulator
* Apply suggested workaround in https://github.com/flutter/flutter/issues/9961
* Update to non-deprecated `application:openURL:options:`
> Minor fixes in iOS sign-in plugin

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- packages/google_sign_in/pubspec.yaml
Fixes flutter/flutter#9961
This should resolve error message `uiDelegate must either be a |UIViewController| or implement the |signIn:presentViewController:| and |signIn:dismissViewController:| methods from |GIDSignInUIDelegate|.`
> Revert change to uiDelegate setter that caused a Google Sign In crash on iOS.

- .travis.yml
We currently don't use them and this should speed up our build.
> Don't install Android emulators on Travis

- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- packages/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/test/google_sign_in_test.dart
* Allow `clientId` to be specified in Dart, which will take
precedence over the config-based discovery.
* Only fire "current user changed" stream events when the current
user really did change.
> Updates to Google Sign-In:

- packages/google_sign_in/README.md
It's easier to drag and drop the file. Copy and pasting doesn't work for me, not sure why I used that in the first place.
> Update the Google sign-in readme instructions

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- packages/google_sign_in/ios/google_sign_in.podspec
- packages/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/pubspec.yaml
- packages/google_sign_in/test/google_sign_in_test.dart
* Switch to use GoogleSignIn CocoaPod instead of Google
* Read client ID manually from `GoogleService-Info.plist`,
and don't support passing the client ID from Dart anymore.
https://github.com/flutter/flutter/issues/10819
> GoogleSignIn updates

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
- packages/firebase_database/example/lib/main.dart
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/lib/src/database_reference.dart
- packages/firebase_database/lib/src/firebase_database.dart
- packages/firebase_database/lib/src/query.dart
- packages/firebase_database/pubspec.yaml
- packages/firebase_database/test/firebase_database_test.dart
Fixes flutter/flutter#10821, flutter/flutter#10822, flutter/flutter#10823
> Firebase database query and persistence improvements

- .travis.yml
Travis uses the deprecated `android` CLI to install the Android SDK. Unfortunately, at this point that outdated tool is unable to install the latest version of the "Google Repository" Android SDK component. Switching to managing the Android SDK by hand on Travis. That way, we can use `sdkmanager` (one of the replacements for `android`) and download the latest versions of the Android SDK components.
This change is required to update the plugin dependencies to the latest versions (https://github.com/flutter/plugins/pull/141), which require the latest "Google Repository" version.
> Self-manage Andorid SDK on Travis

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/android/build.gradle
- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/example/android/app/src/main/java/io/flutter/plugins/googlesigninexample/MainActivity.java
- packages/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/pubspec.yaml
- packages/google_sign_in/test/google_sign_in_test.dart
This allows users to use the sign-in plugin in a regular `FlutterActivity` (instead of just a `FlutterFragmentActivity`)
Fixes https://github.com/flutter/flutter/issues/10688.
Fixes https://github.com/flutter/flutter/issues/10690.
In addition to that, this also includes tiny fixes for problems I discovered along the way:
* `signInSilently` will now never throw (after all, an exception is not really silent).
* If the `init` step fails, we'll now attempt to retry init when a new sign-in is triggered. (Previously, if init failed for any reason, you had to restart the app to try signing-in again).
> Manually manage GoogleApiClient

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
- packages/firebase_database/example/android/build.gradle
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/pubspec.yaml
This prevents exceptions when startAt/endAt is used without a key on iOS, and also allows values that don't fit in a Java int on Android.
Fixes flutter/flutter#10899
Fixes flutter/flutter#10900
> Firebase Database fixes for startAt and endAt

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/lib/src/query.dart
- packages/firebase_database/pubspec.yaml
- packages/firebase_database/test/firebase_database_test.dart
This was occurring because `[NSNull null]` and `nil` are not the same on iOS, whereas on Android we can pass null to Firebase without an exception. I'd rather fix the Dart side where we can have a unit test for it, and avoid calling the key versions of methods unless a key string is specified.
Fixes flutter/flutter#10899
> Fix iOS queries when startAt or endAt does not specify key value

- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
This enables other Android plugins to wrap Google sign-in
functionality. The immediate use case for this is the internal
Google SSO-auth plugin, where on Android, it uses the same
client libraries at third-party apps and shares a bunch of
code with third-party sign-in.
> Update GoogleSignInPlugin to use and expose a Delegate

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/example/lib/main.dart
- packages/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/lib/src/common.dart
- packages/google_sign_in/lib/widgets.dart
- packages/google_sign_in/pubspec.yaml
* Add a new `GoogleIdentity` interface, implemented by `GoogleSignInAccount`
* Move GoogleUserCircleAvatar to "widgets" library (exported by
base library for backwards compatibility) and make it take an instance
of `GoogleIdentity`, thus allowing it to be used by other packages that
provide implementations of `GoogleIdentity`
> Updates to google_sign_in:

- packages/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- iOS should not return exception code. Android returns "exception" as code.
- Return null success when user cancels signin
> Fix iOS signin code to make it consistent with Android side

- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- Do not check serial execution for getTokens(). I looked into whether we should be caching tokens and it seems both iOS and Android do this caching already. The tokens have a lifetime of 1-hr by default. Calling getTokens(), even concurrently, should not be a problem.
- Assert serial execution of signIn/signOut methods on iOS just like we are doing on Android.
> GoogleSignIn Plugin fixes

- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/android/build.gradle
- packages/firebase_analytics/example/android/app/build.gradle
- packages/firebase_analytics/pubspec.yaml
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/build.gradle
- packages/firebase_auth/pubspec.yaml
- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/android/build.gradle
- packages/firebase_database/pubspec.yaml
- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/android/build.gradle
- packages/firebase_messaging/pubspec.yaml
- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/android/build.gradle
- packages/firebase_storage/pubspec.yaml
- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/android/build.gradle
- packages/google_sign_in/pubspec.yaml
Updates firebase plugin versions to `11.0.+` and bumps all plugin versions where affected
cc @collinjackson
> use + for patch version for firebase libraries

- packages/google_sign_in/CHANGELOG.md
Replace Firebase with GMS
I haven't published 0.3.1 yet.
> Clarify changelog for google_sign_in

- packages/firebase_analytics/README.md
... instead of 'FirebaseAnalyticsPageRouteObserver'
> Fixed code example to use 'FirebaseAnalyticsObserver'

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/lib/ui/firebase_sorted_list.dart
- packages/firebase_database/pubspec.yaml
_snapshots was not being updated when a change was made.
This resulted in list items displaying stale values. This
change matches what is used in FirebaseList which does
correctly handle onChange.
> Fix FirebaseSortedList onChange handling

- packages/shared_preferences/CHANGELOG.md
- packages/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java
- packages/shared_preferences/ios/Classes/SharedPreferencesPlugin.m
- packages/shared_preferences/lib/shared_preferences.dart
- packages/shared_preferences/pubspec.yaml
- packages/shared_preferences/test/shared_preferences_test.dart
Do what we do on Android and clear the value instead.
Fixes flutter/flutter#11774
> Make iOS null behavior of SharedPreferences not crash

- packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java
Let's make pause() completely harmless if we have not initialized since this flow gets called from multiple places (even without calling start).
> stop() gets called from go to settings dialog

- .travis.yml
- packages/local_auth/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/12241.
Recently (last ~10 days), `sdkmanager` started to print a status bar to the console, which is increasing the size of the log above 4MB. 4MB is the limit at which travis kills a job. This PR suppresses `sdkmanager`'s stdout (which is rather uninteresting) from the logs to fix that issue.
Also bumps `intl` version for `package:local_auth`to resolve a version conflict.
> Fix travis by suppressing sdkmanager's output from log

- packages/image_picker/ios/Classes/ImagePickerPlugin.m
`info` dictionary stores NSValue(with CGRect inside) for UIImagePickerControllerCropRect key, so there is no sense to save this value in `UIImage` variable :)
> Remove pointless UIImagePickerControllerCropRect use from image_picker

- packages/path_provider/ios/Classes/PathProviderPlugin.m
- packages/path_provider/lib/path_provider.dart
No need to check array count here, because `-[NSArray firstObject]` returns nil if there are no elements in array.
> Remove pointless array count check in iOS implementation of path_provider plugin

- packages/firebase_firestore/android/build.gradle
- packages/firebase_firestore/android/settings.gradle
- packages/firebase_firestore/android/src/main/AndroidManifest.xml
Fixes https://github.com/flutter/flutter/issues/12501
Currently an app that declares a dependency on both firebase_database and firebase_firestore will fail during compilation with:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lio/flutter/plugins/firebase/database/BuildConfig;
```
The reason for this is a wrong package ID in the android manifest of firestore.
> Fix the package ID of firestore

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
- packages/firebase_database/example/lib/main.dart
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.h
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/lib/src/database_reference.dart
- packages/firebase_database/lib/src/event.dart
- packages/firebase_database/lib/src/firebase_database.dart
- packages/firebase_database/pubspec.yaml
- packages/firebase_database/test/firebase_database_test.dart
Add Firebase Realtime Database transaction support.
- Dart side initiates the transaction on the native side via
method channel.
- Native side returns snapshot to be updated then blocks for
update from dart side.
- Dart side updates snapshot and passes it back to the native
side.
- The native side releases the block and the transaction continues
on the native side.
> Add transaction support.

- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/README.md
- packages/firebase_messaging/pubspec.yaml
The curl example in the README currently includes `"click_action": "FLUTTER_NOTIFICATION_CLICK"` as part of the `notification` payload, this doesn't open the app when the notification is tapped.
Moved it into the data payload instead for the desired behavior.
> Fix: Set "click_action" in example data payload

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/example/lib/main.dart
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
- packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
I updated deprecated firebase_auth api and added suppress warning for firebase_database according https://github.com/flutter/flutter/issues/11154.
Also I renamed `FirebaseUser.getToken` to `FirebaseUser.getIdToken` - very breaking changes 🎉
> Fix firebase_auth warnings

- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/android/build.gradle
- packages/firebase_admob/pubspec.yaml
- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/android/build.gradle
- packages/firebase_analytics/example/android/app/build.gradle
- packages/firebase_analytics/pubspec.yaml
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/build.gradle
- packages/firebase_auth/pubspec.yaml
- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/android/build.gradle
- packages/firebase_database/pubspec.yaml
- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/android/build.gradle
- packages/firebase_messaging/pubspec.yaml
- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/android/build.gradle
- packages/firebase_storage/pubspec.yaml
- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/android/build.gradle
- packages/google_sign_in/pubspec.yaml
This should allow us to be compatible with new functionality like [Firestore](https://cloud.google.com/firestore/docs/) without having to rev every plugin when a new API is introduced.
Fixes flutter/flutter#12399
> Update GMS to 11.+

- packages/device_info/CHANGELOG.md
- packages/device_info/lib/device_info.dart
- packages/device_info/pubspec.yaml
I remembered why I used the '.toString()' in my last PR: Android passes actual bool-types which should not be directly compared to 'true'... 
The iOs comparison in line 243 still stands since iOS does pass string-representations of bool-values.
> Removed broken type-comparison

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/example/lib/main.dart
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
- packages/image_picker/lib/image_picker.dart
- packages/image_picker/pubspec.yaml
- packages/image_picker/test/image_picker_test.dart
[flutter/flutter/#10149](https://github.com/flutter/flutter/issues/10149)
This makes it possible to specificy a `maxWidth` and `maxHeight` for the `pickImage` method, like so:
```dart
Future<File> imageFile = ImagePicker.pickImage(maxWidth: 400.0, maxHeight: 700.0);
```
The picked image will then be scaled accordingly, while **preserving aspect ratio**.
Let me know if there's something that could be improved on. [This is me doing Objective C](https://cdn-images-1.medium.com/max/455/1*snTXFElFuQLSFDnvZKJ6IA.png), so I'm pretty sure it's not the most idiomatic code possible.
> Add ability to scale images with ImagePicker plugin

- packages/device_info/CHANGELOG.md
- packages/device_info/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java
- packages/device_info/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/12862
> Fix error when returning empty list of supported ABIs

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
- packages/image_picker/lib/image_picker.dart
- packages/image_picker/pubspec.yaml
- packages/image_picker/test/image_picker_test.dart
**(I started over because of the googlebot CLA confusion and ugly change history.)**
This PR makes it possible to control whether the image comes from _gallery_ or _camera_. The old behavior is preserved as the default option, which lets the user decide.
Here are the available options:
```dart
enum ImageSource {
/// Let the user choose an image from a source they prefer.
/// (the old default behavior)
askUser,
/// Opens up the device camera on both Android and iOS.
camera,
/// On Android, presents a grid of images from the users gallery. On iOS,
/// opens the users photo library.
gallery,
}
```
Here's how someone might pick an image from the device camera now:
```dart
Future<File> imageFile = ImagePicker.pickImage(source: ImageSource.camera);
```
> Image source selection support for ImagePicker plugin

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/CloudFirestorePlugin.java
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/lib/cloud_firestore.dart
- packages/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
Adds:
- `DocumentReference.delete()`
- `Query.where`
- `Query.orderBy`
Tested in iOS and Android (si|e)mulators.
For the `Query` methods I had to do some string manipulation to fit everything in existing `parameters` Map, but I'd be happy to refactor if needed.
Fixes flutter/flutter#12802 flutter/flutter#12509 flutter/flutter#12396.
> Firestore updates

- packages/image_picker/README.md
Fixes [flutter/issues/12937](https://github.com/flutter/flutter/issues/12937).
> Document necessary permissions for ImagePicker plugin to avoid crashes on real devices

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
* Added isNull filtering to Firestore Query; 
* Fixed DocumentChange oldIndex and newIndex to be treated as signed integers (iOS)
> Added isNull filtering to Firestore Query

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
Fixes flutter/flutter#13058.
I was going to implement it on the native side, until I saw [this test](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/e57d4a7d75514fcff2c41c541b616813be466494/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java#L248) which showed me that the same result could be achieved by simply taking the DocumentReference's path and appending the collectionPath.
To-do:
> DocumentReference `getCollection()` method

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/lib/ui/firebase_animated_list.dart
- packages/firebase_database/lib/ui/firebase_list.dart
- packages/firebase_database/lib/ui/utils/stream_subscriber_mixin.dart
- packages/firebase_database/pubspec.yaml
setState is getting called after the the firebase list is disposed, which is inducing a memory leak. To fix this, list.clear() is used to clear the subscriptions to the firebase streams in the list.
> Cancel the Firebase stream subscriptions.

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/README.md
- packages/android_alarm_manager/android/src/main/java/io/flutter/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/androidalarmmanager/AndroidAlarmManagerPlugin.java
- packages/android_alarm_manager/example/android/app/build.gradle
- packages/android_alarm_manager/example/android/app/google-services.json
- packages/android_alarm_manager/example/android/app/src/main/AndroidManifest.xml
- packages/android_alarm_manager/example/android/app/src/main/java/io/flutter/androidalarmmanagerexample/Application.java
- packages/android_alarm_manager/example/android/build.gradle
- packages/android_alarm_manager/example/lib/main.dart
- packages/android_alarm_manager/example/pubspec.yaml
This change enables the AlarmService to establish plugin connections when it is started in the absence of a main activity. However, for this to work properly, plugins may not assume that there is a current Activity. In particular plugins should not retain a reference to the Activity gleaned from the `Registrar` passed to `registerWith`. Instead, plugins should query the registrar whenever an Activity is needed, and should use registrar.context() when a Context is needed instead of using the Activity as a Context.
In subsequent PR's I will update the plugin API documentation, and try to update first-party plugins as much as I am able.
Until the above changes are made, most plugins won't work correctly when initialized by a background service.
> [android_alarm_manager] Example uses a firebase plugin, and reinitializes plugins.

- FlutterFire.md
- README.md
Does what it says on the tin — these two packages were missing from `README.md`, and AdMob was missing from `FlutterFire.md`
> Add AdMob and Firestore to README and FlutterFire.md

- packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java
- packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java
Make sure we only reply once from a single instance of local_auth.
Fixes https://github.com/flutter/flutter/issues/13506
> Fix race condition found in local_auth. 

- packages/android_intent/example/android/build.gradle
- packages/battery/example/android/build.gradle
- packages/cloud_firestore/example/android/build.gradle
- packages/connectivity/example/android/build.gradle
- packages/firebase_admob/example/android/build.gradle
- packages/firebase_analytics/example/android/build.gradle
- packages/firebase_auth/example/android/build.gradle
- packages/firebase_database/example/android/build.gradle
- packages/firebase_messaging/example/android/build.gradle
- packages/firebase_storage/example/android/build.gradle
- packages/google_sign_in/example/android/build.gradle
- packages/image_picker/example/android/build.gradle
- packages/local_auth/example/android/build.gradle
- packages/package_info/example/android/build.gradle
- packages/path_provider/example/android/build.gradle
- packages/quick_actions/example/android/build.gradle
- packages/sensors/example/android/build.gradle
- packages/share/example/android/build.gradle
- packages/shared_preferences/example/android/build.gradle
- packages/url_launcher/example/android/build.gradle
Version 2.3.0 of the Android Gradle plugin uses Gradle API that has been removed in Gradle 4. Version 2.3.3 does not (and has been used by the Flutter project template for a long time).
This change affects example projects only, not the plugins themselves.
> Upgrade examples to work with Gradle 4

- packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
- packages/firebase_database/example/lib/main.dart
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/lib/src/firebase_database.dart
- packages/firebase_database/lib/ui/firebase_list.dart
- packages/firebase_database/lib/ui/firebase_sorted_list.dart
- packages/firebase_database/lib/ui/utils/stream_subscriber_mixin.dart
- packages/firebase_database/test/firebase_database_test.dart
Ensure Flutter apps can be notified when a Firebase DB error occurs.
> Basic error event communication

- packages/video_player/android/src/main/java/io/flutter/videoplayer/VideoPlayerPlugin.java
- packages/video_player/example/lib/main.dart
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
- packages/video_player/lib/video_player.dart
Fixes https://github.com/flutter/flutter/issues/13670
> Enable access to the video size

- packages/android_alarm_manager/example/ios/Podfile
- packages/android_alarm_manager/example/pubspec.yaml
Check in `Podfile` with `use_frameworks!` commented out to allow `ipa` build of example project that depends on static library via `google_sign_in` plugin.
Also made example project dependencies real dependencies (rather than dev dependencies).
> Podfile should not use_frameworks with Google signin static lib

- packages/video_player/README.md
Demo GIF image doesn't work on pub site because link is relative rather than absolute. Need to resubmit the readme for the video package.
> Fix GIF image

- README.md
Travis build fails due to: https://github.com/flutter/flutter/issues/13813 , fixed in https://github.com/flutter/flutter/pull/13814
> Add android_alarm_manager package to README

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/pubspec.yaml
Fixes flutter/flutter#12714
Without the break statement, `Query#addDocumentListener` was falling through to `Query#removeListener`.
> Add missing `break`

- packages/firebase_admob/lib/firebase_admob.dart
- packages/firebase_admob/test/firebase_admob_test.dart
The AdMob team advised us to not make the `requestAgent` a public part of the `MobileAdTargetingInfo` class but to set it to "flutter-version".
> Change requestAgent to "flutter-alpha"

- packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/AndroidIntentPlugin.java
- packages/android_intent/example/lib/main.dart
- packages/android_intent/lib/android_intent.dart
Allows to specify an explicit package name when sending an intent.
If there is no package installed in the system with that name or the package cannot handle the intent,  it'll fallback to an implicit intent by removing the specified package from the intent.
> Add support for Android explicit intents

- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/example/lib/main.dart
- packages/firebase_admob/pubspec.yaml
This is a clean redo of PR #312, of which I made a mess when attempting to rebase onto upstream changes. There shouldn't be anything in here other than code changes to the firebase-admob example, a version bump to the pubspec, and a corresponding CHANGLEOG update.
The changes to the example are:
* Load and Show functionality for interstitials has been separated into two separate buttons, which is more in line with our best practices for AdMob.
* Separate, platform-specific ad unit IDs and App IDs have been added.
> Adds platform-specific IDs, new "show interstitial" button to AdMob example

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/pubspec.yaml
When both cloud_firestore and firebase_database plugins are included in project dependencies I get following build error when trying to run my app in iOS simulator:
```
/MyProject/build/ios/Debug-iphonesimulator/Runner.app/Runner
duplicate symbol _getQuery in:
/MyProject/build/ios/Debug-iphonesimulator/cloud_firestore/libcloud_firestore.a(CloudFirestorePlugin.o)
/MyProject/build/ios/Debug-iphonesimulator/firebase_database/libfirebase_database.a(FirebaseDatabasePlugin.o)
ld: 1 duplicate symbol for architecture x86_64
```
This PR simply renames the function in firebase_database plugin.
I'd be happy to update this PR if someone with better knowledge of ObjC can suggest a nicer way to fix this.
Fixes flutter/flutter#12501 for iOS.
> Fixes function name collision in FirebaseDatabase and CloudFirestore plugins

- packages/android_alarm_manager/pubspec.yaml
- packages/camera/pubspec.yaml
- packages/connectivity/pubspec.yaml
- packages/device_info/pubspec.yaml
- packages/package_info/pubspec.yaml
- packages/sensors/pubspec.yaml
- packages/share/pubspec.yaml
- packages/shared_preferences/pubspec.yaml
- packages/url_launcher/pubspec.yaml
- packages/video_player/pubspec.yaml
Specify `environment:` clause in all plugin `pubspec.yaml` files to comply with `pub`lishing requirements.
> Set environment in pubspec.yaml where missing

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/lib/src/database_reference.dart
- packages/firebase_database/lib/src/firebase_database.dart
- packages/firebase_database/lib/src/query.dart
- packages/firebase_database/pubspec.yaml
- packages/firebase_database/test/firebase_database_test.dart
Previous implementation required that we specify a FirebaseApp if we wanted to specify a database URL to use.  However, it is possible to only specify the database URL which doesn't require you to configure a FirebaseApp.  
With this pull request, to specify a different database is just, `new FirebaseDatabase(databaseURL: 'https://examplefirebaseapp-db2.firebaseio.com/');`
> Support for specifying a database URL in firebase_database

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/android/build.gradle
- packages/android_alarm_manager/android/src/main/AndroidManifest.xml
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java
- packages/android_alarm_manager/example/android/app/build.gradle
- packages/android_alarm_manager/example/android/app/google-services.json
- packages/android_alarm_manager/example/android/app/src/main/AndroidManifest.xml
- packages/android_alarm_manager/example/android/app/src/main/java/io/flutter/plugins/androidalarmmanagerexample/Application.java
- packages/android_alarm_manager/example/android/app/src/main/java/io/flutter/plugins/androidalarmmanagerexample/MainActivity.java
- packages/android_alarm_manager/pubspec.yaml
* Refreshed Android project template to match the one created by new Flutter plugin projects (on master branch)
* Moved Java classes to `io.flutter.plugins` "sub"-package to match other plugins.
@zanderso We probably need to regenerate the `google-services.json` file to reflect new package names. Can I ask you to either do that or provide me the necessary permissions?
> Refresh alarm_manager project template. Move Java package

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
Fixes flutter/flutter#13613
Added features:
- `Query` can now have more than one `orderBy` field.
- `startAt`, `startAfter`, `endAt`, and `endBefore` support
- `limit` support
cc @collinjackson @kroikie
> Additional Firestore Query methods

- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
If the image is scaled, the exif params will copied after the resize.
Sorry but it's only for android
> ImagePicker: Preserve Exif with scaling (only android)

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
Small addition to include the Firebase Auth password reset feature, both Android and iOS supported. Basic usage is:
```
await FirebaseAuth.instance.sendPasswordResetEmail(
email: emailAddress,
);
```
This follows the same pattern as other methods in the relevant source files. Throws a platform exception on error (invalid email, no user exists, etc).
> Added password reset function to Firebase Auth object

- packages/video_player/CHANGELOG.md
- packages/video_player/lib/video_player.dart
Fix signature errors to account for strong mode errors in
https://github.com/flutter/flutter/issues/14556
(issues encountered when running flutter gallery in strong mode).
> Fix signature errors to account for strong mode errors

- packages/video_player/CHANGELOG.md
- packages/video_player/lib/video_player.dart
- packages/video_player/pubspec.yaml
Removed use of `List.cast` to avoid an awkward Dart SDK constraint.
Bit of code cleanup.
Bump version for republication.
> Make video plugin ready for republication

- packages/shared_preferences/CHANGELOG.md
- packages/shared_preferences/lib/shared_preferences.dart
- packages/shared_preferences/pubspec.yaml
- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/lib/url_launcher.dart
- packages/url_launcher/pubspec.yaml
* Channels don't preserve type arguments, so we need
to either use containers with dynamic element types
or explicitly cast containers;
* In url_launcher: invokeMethod returns Future<dynamic>
rather than Future<Null>. Use Future<void> instead of
Future<Null>.
Fixes https://github.com/flutter/flutter/issues/14921
> Fix few Dart 2 issues in the Flutter plugins.

- packages/url_launcher/ios/Classes/UrlLauncherPlugin.m
For older phones pre iOS 10 you get the following exception 
'unrecognized selector sent to instance'
This kills the App completely. I fixed this with this patch.
To replicate, just attempt to open a url on any old device / simulator.
Cheers,
Rob
> Fix url_launcher for iOS <10

- packages/android_intent/lib/android_intent.dart
- packages/device_info/lib/device_info.dart
- packages/firebase_core/lib/src/firebase_options.dart
- packages/firebase_database/lib/ui/firebase_animated_list.dart
- packages/video_player/lib/video_player.dart
TBR
`dartfmt` changed in Flutter master (https://github.com/dart-lang/dart_style/pull/673), so travis now complains about formatting errors.
> Fix new formatting errors

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/lib/src/document_snapshot.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
Fixes following exception when getting document snapshot when the document does not exist yet:
```
NoSuchMethodError: The method 'forEach' was called on null.
Receiver: null
Tried calling: forEach(Closure: (dynamic, dynamic) => dynamic)
dart:collection                                            new LinkedHashMap.from
package:cloud_firestore/src/document_snapshot.dart 36:16   _asStringKeyedMap
package:cloud_firestore/src/document_reference.dart 58:7   DocumentReference.get
```
I also added `DocumentSnapshot.exists` to match implementations in other languages (Java/Node.js/ObjC).
> Firestore: Allow null document snapshot data when document does not exist

- .cirrus.yml
Cirrus CI recently added Flutter support by providing [Docker images with Flutter pre-installed](https://hub.docker.com/r/cirrusci/flutter/). It allows to avoid boilerplate of setting up an environment which makes it possible to start tests execution in a few hundred milliseconds from the moment a change is pushed to GitHub.
For this repository particularly I've seen CI times from 12 to 15 minutes for the longest part of the build (building apks). It's 2 to 3 times faster comparing to the current CI setup. 
Unfortunately `flutter_plugin_tools` can't run things in parallel and take advantage of up to 8 cores that Cirrus CI can provide.
Here is [a build for that particular change](https://cirrus-ci.com/build/5640120652791808):
I was testing Flutter support on this repository and decided to …
> Configure Flutter CI

- .cirrus.yml
Right now `cirrusci/flutter:latest` tag points to the latest released version of Flutter. For example, `0.2.0` right now. To make sure we always test agains the latest Flutter available I've added a script to always run `flutter upgrade`.
Another possibility will be to incorporate [Cirrus CI's Container Builder](https://medium.com/cirruslabs/introducing-container-builder-for-cirrus-ci-80b9234f007) into https://github.com/flutter/flutter so successful master builds will publish a Docker container.
to: @Hixie @yjbanov
> Always use the latest Flutter available

- packages/camera/CHANGELOG.md
- packages/camera/lib/camera.dart
- packages/camera/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/15359
> Fix Dart 2 runtime error in the camera plugin

- packages/cloud_firestore/test/cloud_firestore_test.dart
- packages/google_sign_in/example/lib/main.dart
After running `analyze`.
Saw it because #419 was failing `analyze` task.
> Fixed deprecation warnings

- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/example/lib/main.dart
Adds runtime permission requests for image_picker when image source is set to camera on Android.
partially fixes https://github.com/flutter/flutter/issues/13921
> add runtime permission requests for external storage and camera

- .cirrus.yml
- script/incremental_build.sh
Similar to `plugin_tools.sh` but doesn't depend on Travis or any other CI.
+use it for Cirrus CI
to: @Hixie @yjbanov
> Incremental Build Script

- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/pubspec.yaml
This version of the plugin includes https://github.com/flutter/plugins/pull/402 which ads support for specifying the size of a `BannerAd`
> Updated to 0.5.0

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/pubspec.yaml
https://github.com/flutter/flutter/issues/15765
> Cut a new firebase_database version with dart2 runtime cast fix

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/build.gradle
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/lib/cloud_firestore.dart
- packages/cloud_firestore/lib/src/collection_reference.dart
- packages/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
Redux of #343 with the new API courtesy of @mravn-google. Fixes flutter/flutter#13043 et al.
Currently testing on Android. Needs iOS testing.
cc @collinjackson @kroikie @mit-mit
> Extend StandardMessageCodec for Cloud Firestore

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/lib/cloud_firestore.dart
- packages/cloud_firestore/lib/src/batch.dart
- packages/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/lib/src/write_batch.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
Fixes flutter/flutter#14026
I've done some initial testing on Android, including a sync call to an operation followed by an async call.
iOS support is here but needs to be tested.
> Batch support for Firestore

- packages/firebase_admob/README.md
Replace `AnchorType.andhorBottom` with `AnchorType.bottom`.
https://github.com/rkowase/plugins/blob/master/packages/firebase_admob/lib/firebase_admob.dart#L85
```dart
enum AnchorType { bottom, top }
```
> Replace AnchorType.andhorBottom with AnchorType.bottom

- packages/image_picker/CHANGELOG.md
- packages/image_picker/LICENSE
- packages/image_picker/README.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ExifDataCopier.java
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java
- packages/image_picker/example/lib/main.dart
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
- packages/image_picker/lib/image_picker.dart
- packages/image_picker/pubspec.yaml
- packages/image_picker/test/image_picker_test.dart
Changes: 
* Uses the native Android gallery UI for picking images, instead of a custom one
* removes the image source selection dialog on iOS
* **Breaking API change:** now the `source` named parameter for the `pickImage` method is annotated with `@required`.
Issues fixed:
* Fixes flutter/flutter#13706
* Fixes flutter/flutter#11577, except for step 4. Which could be a separate ticket.
* Fixes flutter/flutter#13060, which is an old leftover issue that was actually merged a while ago, but verified working here
Currently, the image picker plugin uses a custom gallery UI from [this library](https://github.com/esafirm/android-image-picker), instead of the native one. I'll guess that the original reason for that is that picking images by using the native gallery can be quite wonky.
While this …
> Image picker plugin: use the native Android gallery / file chooser

- packages/shared_preferences/README.md
- packages/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java
- packages/shared_preferences/example/lib/main.dart
- packages/shared_preferences/ios/Classes/SharedPreferencesPlugin.m
- packages/shared_preferences/lib/shared_preferences.dart
- packages/shared_preferences/test/shared_preferences_test.dart
On Android, SharedPreferences#apply() will silently fail if there is an
issue. Using #commit() ensures we can propogate errors up the future
chain.
Also updated the example to reflect the fact that preference writes are
not instant.
Deprecated commit() as neither platform actually implements it
correctly.
> Make SharedPreferences return failures

- packages/camera/example/ios/Runner.xcodeproj/project.pbxproj
- packages/device_info/example/ios/Runner.xcodeproj/project.pbxproj
- packages/image_picker/example/ios/Runner.xcodeproj/project.pbxproj
- packages/shared_preferences/example/ios/Runner.xcodeproj/project.pbxproj
This PR is one of several (extracted from #386) intended to remove all remaining uses of yourcompany.com from the plugin repo.
> Remove yourcompany.com from iOS product bundle IDs

- packages/cloud_firestore/example/android/app/google-services.json
- packages/cloud_firestore/example/ios/Runner.xcodeproj/project.pbxproj
- packages/cloud_firestore/example/ios/Runner/GoogleService-Info.plist
- packages/cloud_firestore/example/ios/Runner/Info.plist
- packages/cloud_firestore/example/lib/main.dart
- packages/cloud_firestore/lib/cloud_firestore.dart
This PR is one of several (extracted from https://github.com/flutter/plugins/pull/386) intended to remove all remaining uses of `yourcompany.com` from the plugin repo.
Since `yourcompany.com` was previously part of app IDs, the Google services json/plist files and their their source Firebase projects need updating. I do not have access to the original Firebase project used, and so created a new one. (@collinjackson feel free to push back on this, e.g. by sending me updated Google services files generated from the original project.)
For `cloud_firestore` in particular, a few other corrections were made in #386, and replicated here:
- example changed from books to messages
- missing library part declared in main library file
- Apple developer ID removed from iOS
> Remove yourcompany.com from cloud_firestore

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/ios/Classes/FirebaseCorePlugin.m
- packages/firebase_core/pubspec.yaml
This fix is required for Firestore multiple app support.
> Fix FirebaseApp projectID on iOS

- script/incremental_build.sh
Added an additional check and a warning message.
This change addresses an issue experienced in #423.
/cc @goderbauer
> Don't fail an incremental build if can't find a merge base

- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/lib/firebase_admob.dart
- packages/firebase_admob/pubspec.yaml
Fix listeners in firebase_admob. 
```
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'
```
> Fix broken listeners in firebase_admob

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java
- packages/firebase_core/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_core/example/lib/main.dart
- packages/firebase_core/ios/Classes/FirebaseCorePlugin.h
- packages/firebase_core/ios/Classes/FirebaseCorePlugin.m
- packages/firebase_core/lib/firebase_core.dart
- packages/firebase_core/lib/src/firebase_app.dart
- packages/firebase_core/lib/src/firebase_options.dart
- packages/firebase_core/pubspec.yaml
- packages/firebase_core/test/firebase_core_test.dart
Required for #476 
In practice, I doubt anyone would need read the options of an app, it's far more common to set it via `configure()` than read it. So making this API `async` doesn't affect the developer much.
An alternative is that we could make the `options` getter synchronous but throw an exception for the default app unless the developer puts an `await FirebaseApp.configure()` in their code first.
> Support for firebase_core interoperating with native code that configures Firebase apps.

- packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/GoogleMobileMapsPlugin.java
- packages/google_mobile_maps/example/lib/animate_camera.dart
- packages/google_mobile_maps/example/lib/main.dart
- packages/google_mobile_maps/example/lib/move_camera.dart
- packages/google_mobile_maps/example/lib/page.dart
- packages/google_mobile_maps/example/lib/place_marker.dart
- packages/google_mobile_maps/lib/google_mobile_maps.dart
- packages/google_mobile_maps/lib/src/bitmap.dart
- packages/google_mobile_maps/lib/src/controller.dart
- packages/google_mobile_maps/lib/src/marker.dart
* Add marker API
* Simplified example pages
* Consolidated some Java code
> Add marker API

- packages/firebase_admob/README.md
Adding missing argument where it's marked required.
> Add required argument to Firebase admob readme

- packages/video_player/ios/Classes/VideoPlayerPlugin.m
The video_player plugin crashes on iOS whenever it attempts to load an asset image. This only happens when the image has no package. The problem seems to be that `package` in Obj-C is deserialized as a `NSNull` instance instead of `nil`.
> Fix crash on iOS when loading a video from assets without a package

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
> Renamed 'getCollection()' to 'collection()' for DocumentReference

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/ios/cloud_firestore.podspec
- packages/cloud_firestore/pubspec.yaml
- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/ios/firebase_admob.podspec
- packages/firebase_admob/pubspec.yaml
- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/ios/firebase_analytics.podspec
- packages/firebase_analytics/pubspec.yaml
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/ios/firebase_auth.podspec
- packages/firebase_auth/pubspec.yaml
- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/ios/firebase_core.podspec
- packages/firebase_core/pubspec.yaml
- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/ios/firebase_database.podspec
- packages/firebase_database/pubspec.yaml
- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/ios/firebase_messaging.podspec
- packages/firebase_messaging/pubspec.yaml
- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/ios/firebase_storage.podspec
- packages/firebase_storage/pubspec.yaml
- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/ios/google_sign_in.podspec
- packages/google_sign_in/pubspec.yaml
Partial fix of https://github.com/flutter/flutter/issues/15031
Cocoapods 1.4.0 is barely able to build Swift-based Flutter projects that depends on static frameworks. The workarounds required result in errors after archival and submission to the app store.
Cocoapods 1.5.0 appears able to handle this situation without workarounds of any kind (removed partially by this PR, partially by a [companion PR](https://github.com/flutter/flutter/pull/16443) in the `flutter/flutter` repo). It does require `s.static_framework = true` to be added to the `.podspec` file of each plugin that uses static libs like `GoogleSignIn`.
> Simplify podspecs for Cocoapods 1.5.0

- packages/video_player/CHANGELOG.md
- packages/video_player/lib/video_player.dart
- packages/video_player/pubspec.yaml
This fixes https://github.com/flutter/flutter/issues/16444.
> Add constructor VideoPlayerController.file()

- packages/sensors/CHANGELOG.md
- packages/sensors/ios/Classes/SensorsPlugin.m
- packages/sensors/pubspec.yaml
Android side uses `double[]`, iOS side uses `NSArray` to convey (x,y,z) triplets. On Dart, that deserializes to `Float64List` and `List<dynamic>`, respectively. While the former is a subtype of `List<double>`, the latter is not, so it fails at runtime on iOS.
This PR changes iOS side to use `FlutterStandardTypedData`, to make the triplet events deserialize as `Float64List` on both platforms.
Fixes https://github.com/flutter/flutter/issues/16425
> Make iOS sensor events same type as on Android

- packages/cloud_firestore/README.md
Problem:
```
[ +333 ms] I/flutter ( 3394): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +23 ms] I/flutter ( 3394): The following assertion was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
[        ] I/flutter ( 3394): _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#86114):
[        ] I/flutter ( 3394): type 'List<dynamic>' is not a subtype of type 'List<Widget>' where
[        ] I/flutter ( 3394):   List is from dart:core
[        ] I/flutter ( 3394):   List is from dart:core
[        ] I/flutter ( 3394):   Widget is from package:flutter/src/widgets/framework.dart
[   +7 ms] I/flutter ( 3394): 
[        ] I/flutter ( 3394): Either the assertion indicates an error in the framework itself, or we …
```
> Firestore readme fix

- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java
- packages/firebase_storage/example/lib/main.dart
- packages/firebase_storage/ios/Classes/FirebaseStoragePlugin.m
- packages/firebase_storage/lib/firebase_storage.dart
- packages/firebase_storage/pubspec.yaml
- packages/firebase_storage/test/firebase_storage_test.dart
Add StorageMetadata class, getMetadata method on StorageReference, and optional metadata when uploading a file.
> Add some support for StorageMetadata.

- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java
Another day, another set of tests! This makes sure that the `onMethodCall` method and the `switch` case in it behave as expected.
For example, these are the constants for image sources in this plugin:
```java
private static final int SOURCE_CAMERA = 0;
private static final int SOURCE_GALLERY = 1;
```
If somebody were to accidentally flip these the other way around:
```java
private static final int SOURCE_GALLERY = 0;
private static final int SOURCE_CAMERA = 1;
```
These tests would catch that:
I'll try to come up with a clean way of testing the `registerWith` method in a separate PR.
> [Image Picker] - Add contract tests for Android implementation

- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/lib/src/query.dart
- packages/firebase_database/pubspec.yaml
This is a companion for https://github.com/flutter/plugins/pull/353 which fixes null value handling on Android side. There are some minor cleanups on iOS and Dart side as well.
Tested behavior of null `startAt` on Android and it works as expected.
> Allow null value for startAt, endAt and equalTo database queries on Android

- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- packages/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/test/google_sign_in_test.dart
* Adds `isSignedIn` method to `GoogleSignIn`. Uses `hasAuthInKeychain` for iOS. Android side is not implemented yet but the plan is to use `GoogleSignIn.getLastSignedInAccount` per [this][docs] and [this][so].
* Changes `signInSilently()` to `signInSilently({suppressErrors: true})` to allow client code customize  errors handling (also removes special error handling from native side).
Please consider this a proposal open for discussion. There are a couple benefits here as I see it:
* When all errors are suppressed it is very hard for a developer to investigate why in certain scenarios things don't work the way they should.
* `isSignedIn` provides additional visibility and helps in handling different auth scenarios.
**Example scenario:** when device is offline `signInSilently` fails, …
> Add isSignedIn to GoogleSignIn; allow clients to customize error handling

- packages/firebase_remote_config/pubspec.yaml
https://www.dartlang.org/tools/pub/pubspec#sdk-constraints indicates that an environment variable must be set.
> Add environment to Remote Config plugin pubspec

- .cirrus.yml
- .travis.yml
In https://github.com/flutter/plugins/pull/461 java tests for the image_picker plugin were added. This PR runs these tests on Travis and Cirrus CI to ensure they don't break.
Requires https://github.com/flutter/plugin_tools/pull/12 to be submitted and published.
/cc @mravn-google @roughike
> Run java tests on Travis and Cirrus CI

- AUTHORS
- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/RewardedVideoAdWrapper.java
- packages/firebase_admob/ios/Classes/FLTRewardedVideoAdWrapper.m
- packages/firebase_admob/pubspec.yaml
This PR fixes a typo on the rewarded video platform side of the code that was causing the wrong listeners to be called on the failure event.
> Fixed a typo that was causing rewarded video failure event to be called on the wrong listener

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
Add the method to send verification email to user.
Refers to issue [https://github.com/flutter/flutter/issues/12459](https://github.com/flutter/flutter/issues/12459)
> Add send verification mail

- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapBuilder.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapOptionsSink.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/MarkerBuilder.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/MarkerController.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/MarkerOptionsSink.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/OnCameraMoveListener.java
- packages/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_maps_flutter/example/ios/Runner/AppDelegate.h
- packages/google_maps_flutter/example/ios/Runner/AppDelegate.m
- packages/google_maps_flutter/example/lib/map_ui.dart
- packages/google_maps_flutter/example/lib/place_marker.dart
- packages/google_maps_flutter/ios/Classes/GoogleMapController.h
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.h
- packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.m
- packages/google_maps_flutter/ios/Classes/GoogleMapsPlugin.h
- packages/google_maps_flutter/ios/Classes/GoogleMapsPlugin.m
- packages/google_maps_flutter/ios/google_maps_flutter.podspec
- packages/google_maps_flutter/lib/src/bitmap.dart
- packages/google_maps_flutter/lib/src/camera.dart
- packages/google_maps_flutter/lib/src/controller.dart
- packages/google_maps_flutter/lib/src/marker.dart
- packages/google_maps_flutter/lib/src/platform_overlay.dart
- packages/google_maps_flutter/lib/src/ui.dart
* Initial iOS support:
* Showing and configuring GoogleMaps, no texture snapshotting yet.
* Adding and configuring markers.
* Event handling: camera movements and marker taps.
* Dart/Android changes:
* Don't premultiply with screen density on Dart side.
* Reason for camera movement now just a boolean value indicating if it was a user gesture.
* Avoid making null-valued options part of JSON (so we don't have to worry about `[NSNull null]` values on iOS side).
* Example app now also reflects camera move started/camera idle events.
TBD (later PR): unify API coverage, add tests, texture snapshotting on iOS.
> GoogleMaps on iOS

- AUTHORS
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
currentUser() returns a cached instance of user. Using reload we can get a fresh instance
> Add support to reload firebase user

- packages/google_maps_flutter/README.md
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java
- packages/google_maps_flutter/example/lib/animate_camera.dart
- packages/google_maps_flutter/example/lib/main.dart
- packages/google_maps_flutter/example/lib/map_ui.dart
- packages/google_maps_flutter/example/lib/move_camera.dart
- packages/google_maps_flutter/example/lib/place_marker.dart
- packages/google_maps_flutter/ios/Classes/GoogleMapController.h
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.h
- packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.m
- packages/google_maps_flutter/ios/Classes/GoogleMapsPlugin.m
- packages/google_maps_flutter/lib/google_maps_flutter.dart
- packages/google_maps_flutter/lib/src/callbacks.dart
- packages/google_maps_flutter/lib/src/camera.dart
- packages/google_maps_flutter/lib/src/controller.dart
- packages/google_maps_flutter/lib/src/location.dart
- packages/google_maps_flutter/lib/src/marker.dart
- packages/google_maps_flutter/lib/src/platform_overlay.dart
- packages/google_maps_flutter/lib/src/ui.dart
* Add Dartdoc.
* Remove `new`.
* Make map user interface updates return a new camera position immediately so we get an initial camera position, in case we are now tracking that.
* Streamline names of channel methods.
* Normalize `LatLng` constructor arguments, turn into non-`const` constructor.
* Move `Marker.remove()` and `Marker.update(MarkerOptions)` to `GoogleMapController`.
* Hide ID field of `Marker`, making it a typed ID on its own.
* Correct bug: missing use of `Marker.position` data on iOS.
> API documentation and cleanup

- packages/firebase_remote_config/CHANGELOG.md
- packages/firebase_remote_config/android/build.gradle
- packages/firebase_remote_config/ios/Classes/FirebaseRemoteConfigPlugin.m
- packages/firebase_remote_config/pubspec.yaml
- Bump Android version
- iOS returns String status
> Update Remote Config plugin

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/README.md
- packages/cloud_firestore/pubspec.yaml
Must use `await` for set, update, delete and get.
> Add missing await to for transaction in Firestore README

- packages/cloud_firestore/test/cloud_firestore_test.dart
Calling `handlePlatformMessage` while in a mockMethodCallHandler can
lead to race conditions since the first method call hasn't been fully
handled yet.
> Don't do reentrant message channel calls.

- packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
* Fixed a crash when eventSink is called on a null object in the native Android code.
* Added a missing result to some native IOS method calls.
Ready for review.
> Fix for 2 bugs in the Video Player plugin

- AUTHORS
- packages/cloud_firestore/lib/src/transaction.dart
- packages/cloud_firestore/test/cloud_firestore_test.dart
If you `.get` a document that doesn't exist, the result's `data` is `null`. This is expected behavior.
Transactions were attempting to `.cast` this to a Map without null-safety.
This caused an error in transactions when getting a document that doesn't exist.
A unit test was added to verify the fix.
> Adding null-safe handling for Transaction.get in cloud_firestore

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/ios/Classes/UrlLauncherPlugin.m
- packages/url_launcher/pubspec.yaml
Removing these two lines should cause no harm (as the object is anyways deallocated as soon as the animation completes) and prevents a crash that happened when a user dismissed the view controller just before the first page was fully loaded.
> Remove useless code that was causing a crash

- AUTHORS
- packages/sensors/CHANGELOG.md
- packages/sensors/android/src/main/java/io/flutter/plugins/sensors/SensorsPlugin.java
- packages/sensors/example/lib/main.dart
- packages/sensors/ios/Classes/SensorsPlugin.h
- packages/sensors/ios/Classes/SensorsPlugin.m
- packages/sensors/lib/sensors.dart
- packages/sensors/pubspec.yaml
Works great on Android, example code added.
I won't be able to track down a MacOS device / setup Xcode on it for at least a few days, so I'm putting the pull request out there now in case anyone wants to spare me the labor of setting up all of that just to write a couple lines of code. Line 82 in SensorPlugins.m is what needs work.
> Add gravity-independent-accelerometer support to sensors.

- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java
- packages/firebase_messaging/pubspec.yaml
This is a fix for the following issue: https://github.com/flutter/flutter/issues/17839
To sum up: when the Activity is killed (or the Don't keep Activities is set to ON in the Developer options) and the user clicks on a notification, the Dart code will never be notified in the `onLaunch`.
The fix is pretty simple, just call:
```java
registrar.activity().setIntent(intent);
```
In the `onNewIntent` method of the [FirebaseMessagingPlugin.java](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java).
> Firebase Messaging : On Android, when the Activity is killed, the onLaunch is never using the correct Intent

- packages/video_player/CHANGELOG.md
- packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/example/lib/main.dart
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
- packages/video_player/lib/video_player.dart
- packages/video_player/pubspec.yaml
I have added property to know whether video player is currently buffering or not. I need this to show `CircularProgressIndicator` if the video is currently buffering. I haven't tested for the IOS because I don't have the devices so if anyone can test it, please do.
> Add video player buffering status

- packages/cloud_firestore/test/cloud_firestore_test.dart
I fail to see why this change is necessary, but it does seem to fix the [broken build](https://travis-ci.org/flutter/plugins/jobs/384797961).
> Fix test for sync-async semantics

- packages/image_picker/CHANGELOG.md
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
- packages/image_picker/pubspec.yaml
Without this repeated calls to `pickVideo` throw an exception when the request was cancelled during the previous call.
Fixes https://github.com/flutter/flutter/issues/18095.
> Implement imagePickerControllerDidCancel for image_picker on iOS

- packages/video_player/CHANGELOG.md
- packages/video_player/android/build.gradle
- packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/pubspec.yaml
The default Android implementation using the `MediaPlayer` had different playback / codec problems on different devices. We mostly saw problems with a few Samsung phones. 
By using the `ExoPlayer` library playback works fine on all devices we tested so far.
> video_player: use exoplayer for better video compatibility

- .travis.yml
Attempt to resolve compile error inside `cloud_firestore` dependencies on iOS. Cannot reproduce the error locally, speculating that a new version of Xcode might help.
E.g. https://travis-ci.org/flutter/plugins/jobs/389379744
> Upgrade to Xcode 9.3 on Travis

- packages/share/CHANGELOG.md
- packages/share/ios/Classes/SharePlugin.m
- packages/share/ios/share.podspec
- packages/share/pubspec.yaml
* iOS sharing is currently broken
- Can be observed in `0.5.1` by attempting the *Copy* action - no text will be copied.
> Hotfix - iOS Sharing

- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
- packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerDelegateTest.java
This PR is for three bugs relating to image picker.  I found the latter two when fixing the first.  I'm happy to split this up if that's easier.
- (android) image_picker saves both captured images and captured video with a `.png` extension.  I'm not 100% sure that `.jpg` and `.mp4` are correct -- I couldn't find an authoritative source -- but that's what most information seemed to point towards.
- (android) if the initial request from an app is for either video capture or the video gallery, after permission is granted, image_picker redirects to image capture or the image gallery.
- (android) image_picker attempts to resize video if any of the resize parameters (maxWidth, maxHeight) are provided
> image_picker fixes: file suffix, permissions redirect, video resize

- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
imagePicker caused flutter app to crash when picking image from a remote source.
Using a temp file to store the inputStream obtained from the content provider solve the problem.
It actually use a temp file in the cachedDir named cachedImage.jpg.
> use temp image file in cacheDir to allow picking from remote resources

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
- packages/image_picker/pubspec.yaml
`OutputStream.flush` is not guaranteed to move bytes all the way to storage media, so if `OutputStream.close` fails, we need to return `null`.
Sigh. Try-with-resources and `java.nio.file.Files` wft!
Follow-up of https://github.com/flutter/plugins/pull/513
> Ensure we fail if we cannot close file

- packages/video_player/CHANGELOG.md
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
- packages/video_player/pubspec.yaml
Add missing observer removals to prevent crashes on deallocation. Crashes were seen with an iPhone 5.
> video_player: iOS add missing observer removals 

- packages/firebase_performance/CHANGELOG.md
- packages/firebase_performance/README.md
- packages/firebase_performance/lib/src/http_metric.dart
- packages/firebase_performance/lib/src/trace.dart
- packages/firebase_performance/pubspec.yaml
Helps prevent confusion such as:
https://github.com/flutter/flutter/issues/18620#issuecomment-398918148 
https://stackoverflow.com/questions/44591815/unable-to-see-firebase-performance-dashboard-on-console
> Added comments explaining the time it take to see results

- packages/video_player/CHANGELOG.md
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
- packages/video_player/pubspec.yaml
This is the default behaviour of video apps on iOS. 
(fixes https://github.com/flutter/flutter/issues/17911)
I considered setting the category back to `AVAudioSessionCategorySoloAmbient` on `dispose` but this led to race conditions when switching between videos.
> video_player: Allow audio playback in silent mode

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/ios/Classes/UrlLauncherPlugin.m
- packages/url_launcher/lib/url_launcher.dart
- packages/url_launcher/pubspec.yaml
- packages/url_launcher/test/url_launcher_test.dart
Launching from a dark background to a light background webview doesn't automatically update the status bar on iOS.  Adds an optional argument to set the status bar color, and restore the previous value.
Fixes: https://github.com/flutter/flutter/issues/19172
> url_launcher: Add statusBarBrightness field to launch for iOS

- packages/firebase_performance/example/pubspec.yaml
Resolves issue with `packages get` for perf since it used a version of http that was different from flutter_test.
> Bump http version to match flutter_test

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/README.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/example/README.md
- packages/firebase_auth/example/lib/main.dart
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
Update firebase_auth plugin to support phone number authentication.
This PR is a combination of the ideas expressed by @alibitek in [PR](https://github.com/flutter/plugins/pull/329) and @pranjalsatija in [PR](https://github.com/flutter/plugins/pull/484)
Fixes: https://github.com/flutter/flutter/issues/10404
> Add phone auth

- packages/device_info/lib/device_info.dart
- packages/firebase_admob/ios/Classes/FirebaseAdMobPlugin.h
- packages/firebase_database/example/lib/main.dart
- packages/firebase_database/lib/src/firebase_database.dart
- packages/google_maps_flutter/example/lib/map_ui.dart
- packages/google_sign_in/lib/widgets.dart
- packages/path_provider/example/lib/main.dart
- packages/shared_preferences/example/lib/main.dart
A few plugins now have errors in formatting which cause the build to fail. This addresses those formatting errors so other PRs don't have to deal with unrelated formatting errors.
> Fix plugin formatting

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/example/lib/main.dart
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
When a phone number auth code is automatically used to create a credential, the firebase_auth plugin should use that credential to automatically create a user. This fixes the issue of a null user being returned instead.
> Fix auto phone auth

- AUTHORS
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
related issue:
flutter/flutter#19525
> Adding support to setLanguageCode to FirebaseAuth

- AUTHORS
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.h
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
Updated firebase_auth plugin to expose updateEmail.
- defines an updateEmail method on FirebaseAuth with a named email parameter
- passes back exceptions, including failure to update if current user has not signed in recently e.g.:
```
PlatformException(Error 17014, FIRAuthErrorDomain, 
This operation is sensitive and requires recent authentication.
Log in again before retrying this request.)
```
https://firebase.google.com/docs/auth/android/manage-users#set_a_users_email_address
https://firebase.google.com/docs/auth/ios/manage-users#set_a_users_email_address
https://github.com/flutter/flutter/issues/18959
https://github.com/flutter/flutter/issues/17343
> Support updateEmail in firebase_auth

- packages/firebase_auth/README.md
Changes:
* Fix syntax highlighting;
* Fix incomplete README adding GoogleSignIn initialization;
Please review.
> Fix incomplete README for FirebaseAuth

- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java
- packages/android_alarm_manager/example/lib/main.dart
- packages/android_alarm_manager/lib/android_alarm_manager.dart
Fixes issue [#17566](https://github.com/flutter/flutter/issues/17566): alarm_manager plugin stopped working
> Updated `android_alarm_manager` to work after engine refactor.

- packages/location_background/ios/Classes/LocationBackgroundPlugin.m
Depends on flutter/engine#5983
> Change runWithEntrypointAndCallback -> runWithEntrypointAndLibraryUri

- packages/image_picker/android/src/main/AndroidManifest.xml
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerFileProvider.java
Fixes https://github.com/flutter/flutter/issues/20481
> There can only be one declaration for each `FileProvider` subclass. That means to declare multiple file providers without collisions, one must create a (empty) subclass of `android.support.v4.content.FileProvider` and use that as the provider `name` in the manifest.
> 
> In my opinion, `android.support.v4.content.FileProvider` should be reserved for the app itself so that developers can easily add a file provider to their app, without subclassing `FileProvider`. It's also used in the Android documentation and in StackOverflow answers. 
> 
> image_picker and other plugins should subclass `FileProvider` to prevent collisions (also collisions between plugins).
> 
> [This issue](https://github.com/stkent/bugshaker-android/issues/108) …
> image_picker: Use FileProvider subclass to avoid collisions

- packages/cloud_firestore/README.md
Both README and Example app doesn't have an example of a simple Firestore query.
Changelog:
* Add an example of a query to Firestore README
> Add example query to Firestore documentation

- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
The platform is expecting NSURL where it got a string.
Fixes flutter/flutter#16309
> Fixed type error for firebase_auth photoUrl on iOS

- AUTHORS
- packages/firebase_dynamic_links/ios/Classes/FirebaseDynamicLinksPlugin.m
This a fix for this Issue [#19820](https://github.com/flutter/flutter/issues/19820).
The issue only happens in iOS , when the user opens a dynamic link, and after redirecting to the application, the user obtains the link using this code:
> FirebaseDynamicLinks.instance.retrieveDynamicLink ()
The problem is when you call that method again, the expected result must be null since it was previously obtained.
To solve this, after obtaining and returning the link, the _dynamicLink variable is set to null.
> _dynamicLink variable was cleared after user get dynamicLink (iOS)

- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/AdRequestBuilderFactory.java
- packages/firebase_admob/example/lib/main.dart
- packages/firebase_admob/ios/Classes/FLTRequestFactory.m
- packages/firebase_admob/lib/firebase_admob.dart
- packages/firebase_admob/pubspec.yaml
In the light of recent events, namely GDPR, I was missing the functionality to request non-personalized ads in the firebase_admob plugin. This PR adds this option and the respective Android/iOS platform specific code (as described in the Google Mobile Ads SDK).
I also added `nonPersonalizedAds: true` to the example. Unfortunately there currently is no way in the GMA SDK to programmatically check if the requested ad is in fact non-personalized - so no test exists right now. 
This is my first contribution, so it's likely I missed something. Please let me know if that's the case - thanks! 👍 
This feature was requested/asked for in [Issue #17542 [main flutter repo]](https://github.com/flutter/flutter/issues/17542).
> Adds nonPersonalizedAds option to MobileAdTargetingInfo for firebase_admob

- packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
Otherwise the exoplayer MediaPlayer objects continue generating frames after FlutterNativeView is destroyed and onFrameAvailableListener for the video target SurfaceTexture tries to access a missing engine instance.
This is a workaround for widgets not receiving dispose signals when FlutterView is destroyed (https://github.com/flutter/flutter/issues/19358).
https://github.com/flutter/flutter/issues/20989 tracks ensuring that resources are released.
> Release VideoPlayer resources when FlutterView is gone

- packages/google_maps_flutter/README.md
This was a bit confusing, removing until the plugin supports iOS.
> Remove iOS instructions from the maps plugin readme.

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/build.gradle
- packages/image_picker/pubspec.yaml
Partially fixes https://github.com/flutter/flutter/issues/21173
@goderbauer
> image_picker: Depend on full support-v4 library for ease of use

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/build.gradle
- packages/image_picker/pubspec.yaml
If apps use image_picker and another plugin that uses a different
version of support-v4 it should be visible to gradle to allow
resolution to the latest version.
> Use api to allow support-v4 version resolution.

- packages/webview_flutter/android/src/main/AndroidManifest.xml
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFactory.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebviewFlutterPlugin.java
- packages/webview_flutter/example/lib/main.dart
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/test/webview_flutter_test.dart
The focus of this CL is the overall widget/controller structure, and
test plumbing.
The API surface is just the bare minimum at this point (only loadUrl).
> Initial (Android only) implementation of a WebView widget.

- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/FirebaseAdMobPlugin.java
- packages/firebase_admob/ios/Classes/FirebaseAdMobPlugin.m
- packages/firebase_admob/lib/firebase_admob.dart
- packages/firebase_admob/pubspec.yaml
Ad listeners shouldn't necessarily have to be set during Ad initialization.
> listener on MobileAd shouldn't be final

- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java
- packages/firebase_messaging/example/lib/main.dart
- packages/firebase_messaging/pubspec.yaml
The Firebase Messaging plugin for Android only seems to send the custom properties that can be included with a push notification to Flutter - it doesn't send any of the core message components, like the title or body.
For example, if you send this message:
title: My Notification
body: Hello World!
customProperty: foo
The flutter plugin will only receive `{"customProperty": "foo"}`
This is not an issue one the iOS side, which sends the entire apns payload to Flutter.
This change just adds the title and body properties for now, but maybe other properties should be added as well?
> Firebase Messaging: fix Android notification body and title not sent to Flutter

- packages/google_maps_flutter/example/lib/main.dart
This is no longer used since #743, the empty list was just a
left over.
> Remove unused navigatorObservers from the Google Maps example.

- packages/firebase_auth/android/build.gradle
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
**REASON FOR CHANGE**
Flutter apps that include the `firebase_auth` plugin would easily reach the 64K dex limit because of the addition of Guava. The guava library was adding considerable compilation time and size to the final APK. Expectations of new Flutter developers to grasp that they need to add Multi-dex and then Proguard to fix this issue is really silly.
**CHANGE MADE**
Replaced usages of guava's: `ImmutableList` and `ImmutableMap` with platform `Collections.unmodifiableList()` and `Collections.unmodifiableMap()`.
This simple change makes a huge difference.
> Removed Google Guava dependency from firebase_auth.

- packages/video_player/CHANGELOG.md
- packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/QueuingEventSink.java
- packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/lib/video_player.dart
- packages/video_player/pubspec.yaml
This eliminates [the races](https://github.com/flutter/flutter/issues/21483) in VideoPlayer plugin initialization.
> Rebuild VideoPlayer once VideoPlayerController finishes initialization.

- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFactory.java
- packages/webview_flutter/example/lib/main.dart
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/test/webview_flutter_test.dart
Adding just these 2 parameters to set up the skeleton for webview
settings and initial parameters.
Settings (like javaScriptMode) are set and updated by rebuilding the
widget.
initialUrl is a covinience parameter for simple use cases, as the
WebView's loadUrl method cannot be modeled nicely as a widget parameter
(e.g when the widget is rebuilt with the same url value there is no nice
way to tell if you should load that url again or not).
These kind of "edge triggers" fit in the WevView's controller.
initialUrl is completely ignored when the widget is rebuilt.
>  Add an initialUrl and a javaScriptMode parameters to WebView

- packages/google_maps_flutter/example/lib/main.dart
- packages/google_maps_flutter/example/lib/scrolling_map.dart
- packages/google_maps_flutter/lib/google_maps_flutter.dart
- packages/google_maps_flutter/lib/src/google_map.dart
These gesture recognizers participates in gesture arenas on behalf of
the map.
This allows fine grain control over which gestures are dispatched to
the map.
> Add a gestureRecognizers parameter to GoogleMap.

- packages/video_player/CHANGELOG.md
- packages/video_player/lib/video_player.dart
- packages/video_player/pubspec.yaml
- packages/video_player/test/video_player_test.dart
This fixes a bug introduced in https://github.com/flutter/plugins/pull/767: if a State is attached to a new widget it never switched to the new controller.
Also this change makes sure to remove listeners during deinitialization.
> Update VideoPlayer widget when the attached controller changes

- packages/video_player/lib/video_player.dart
Users should not access the texture ID directly.
> Mark textureId as @visibleForTesting.

- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
These significantly simplify the code for GoogleSignIn Android since it uses connectionless `GoogleSignInClient`.
> Switch over to new GoogleSignIn APIs

- packages/video_player/lib/video_player.dart
This change is fully backwards-compatible. The reason I'm doing it is that Flutter is converting to the new `mixin` syntax, which forbids extending mixins.
See also: https://github.com/flutter/flutter/pull/22290
> use WidgetsBindingObserver as a mixin

- packages/shared_preferences/CHANGELOG.md
- packages/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java
- packages/shared_preferences/pubspec.yaml
This is the result of security review. We don't want apps to maliciously store values that will be interpreted differently when read.
> Ban string values which clash with special prefixes

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/example/lib/main.dart
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/test/firebase_auth_test.dart
Required functionality in recent project. Also moved updateProfile in dart code from `FirebaseAuth` to `FirebaseUser` I believe this is the correctly place. So release changelog should be updated to reflect this breaking change.
> Add updatePassword functionality to firebase_auth plugin.

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- packages/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/pubspec.yaml
This is needed for when the returned token is invalid. The app has to be able to clear the authentication cache.
> Add ability to clear auth cache on Android

- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
`FieldValue.arrayUnion([values1, value2, value3]).` causes `java.lang.IllegalArgumentException: Invalid data. Nested arrays are not supported`
This is caused by supplying a List to as a parameter which expects varargs in the plugin.
To fix this I have convert the list to object array when using FieldValue.
> Updating arrays in Firestore always throws an Exception on Android

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
allows to recover the account creation date, and the last sign in date of an user.
With them, you can determine if a user logs in for the first time.
(and then, create a welcome/ setup page, for example)
this metadata field was available in both native API, as shown in the documentation.
https://developers.google.com/android/reference/com/google/firebase/auth/FirebaseUser.html#getMetadata()
I implemented its access in the Dart library.
example usage:
```dart
final FirebaseAuth _auth = FirebaseAuth.instance;
FirebaseUser _currentUser = await _auth.currentUser();
if (user.metadata.creationTimestamp ==  user.metadata.lastSignInTimestamp)
...
```
> [Firebase Auth] added access to User metadata

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/build.gradle
- packages/firebase_core/example/android/build.gradle
- packages/firebase_core/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/firebase_core/pubspec.yaml
In an effort to bump the Android dependencies of all Firebase plugins it would be cleaner to bump core independently since all other firebase plugins depend on this one.
> Bump firebase_core Android dependencies to latest

- packages/google_maps_flutter/lib/src/marker.dart
Did this to align with the android SDK and also open up a way to associate meta data with a marker, such as linking to the underlying model associated to a marker.
> Added getter for Marker ID in maps package

- packages/google_maps_flutter/lib/src/controller.dart
Add a method to clear all the markers currently on the map. There is currently a method to add, update, and remove a single marker, but not a method to remove all markers.
> Add clearMarkers() functionality to GoogleMapController

- packages/local_auth/CHANGELOG.md
- packages/local_auth/README.md
- packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java
- packages/local_auth/example/lib/main.dart
- packages/local_auth/ios/Classes/LocalAuthPlugin.m
- packages/local_auth/lib/local_auth.dart
- packages/local_auth/pubspec.yaml
Should resolve Issue https://github.com/flutter/flutter/issues/22727 
Two new functions were added to the **local_auth** plugin
* `bool canCheckBiometrics` > if device is able to do local auth (with biometrics)
* `List<BiometricType> getAvailableBiometrics` > list of **enrolled** biometrics
Enum BiometricType:
* face
* fingerprint
* _iris (not yet implemented)_
@mehmetf here's the fix according to your mail. Thanks!
> Add biometry type detection to local_auth plugin

- packages/video_player/CHANGELOG.md
- packages/video_player/lib/video_player.dart
- packages/video_player/pubspec.yaml
Since the audio player plugin is not maintained we use the video player to play some mp3 files. It's working fine in iOS but crashing on Android because of a null exception. This fixes it.
> video_player: Fixed null exception when file has no width or height.

- packages/cloud_firestore/README.md
https://docs.flutter.io/flutter/widgets/StreamBuilder-class.html
I had some problems with using just `if (snapshot.hasData)`, i thought other users might benefit from the correct usage.
> Correct usage of StreamBuilder

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/pubspec.yaml
The following code causes the snapshot variable to be nil in the callback path.  However the code assumes it is not nil and crashes :)
- (id<FIRListenerRegistration>)
addSnapshotListenerInternalWithOptions:(FSTListenOptions *)internalOptions
listener:(FIRDocumentSnapshotBlock)listener {
FIRFirestore *firestore = self.firestore;
FSTQuery *query = [FSTQuery queryWithPath:self.key.path()];
const DocumentKey key = self.key;
FSTViewSnapshotHandler snapshotHandler = ^(FSTViewSnapshot *snapshot, NSError *error) {
if (error) {
listener(nil, error);
ret
> Fix a crash in the snapshot callback

- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java
- packages/firebase_messaging/example/android/build.gradle
- packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
- packages/firebase_messaging/lib/firebase_messaging.dart
- packages/firebase_messaging/pubspec.yaml
- packages/firebase_messaging/test/firebase_messaging_test.dart
intends to fix flutter/flutter#17699 and fix flutter/flutter#20378
Removing local cache of getToken() in the dart part of the plugin. Now getToken() calls directly its counterparts in the iOS and Android implementations. This enables obtaining its value without calling configure() or having to wait for a new token refresh.
replaces PR #789 
@Hixie 
@philipgiuliani
@calebisstupid
@beardo01
@muirandy
> [firebase_messaging] changing getToken to rely on platform's getToken (2)

- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java
Previously activityState was getting set based on all activity lifecycle
events, which caused bugs if the registrar activity was recreated.
Fixes flutter/flutter#21497
> Only update state for the registrar's activity

- packages/quick_actions/CHANGELOG.md
- packages/quick_actions/android/src/main/java/io/flutter/plugins/quickactions/QuickActionsPlugin.java
- packages/quick_actions/pubspec.yaml
https://github.com/flutter/flutter/issues/18864
> Allow quick_actions to register more than once

- packages/local_auth/android/build.gradle
The 'support-v4' package is a meta package with all support library packages included. This plugin only uses classes from 'support-compat', so this can be used instead.
> local_auth: Use minimal support library

- packages/firebase_analytics/lib/firebase_analytics.dart
See the below reference guide links, setting userID to null is equivalent to signing a user out.
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setUserId(java.lang.String)
https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#setuserid
> [firebase_analytics] Allow setUserID input to be null

- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/pubspec.yaml
Bumping version of firebase_analytics plugin so change from [PR](https://github.com/flutter/plugins/pull/888) can be published.
> Bump firebase_analytics version to 1.0.6

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/android/build.gradle
- packages/google_sign_in/pubspec.yaml
Increasing the dependency for `com.google.android.gms:play-services-auth` to `16.0.1` in `google_sign_in`.
> Increase play-services-auth dependency

- packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/BarcodeDetector.java
- packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/CloudLabelDetector.java
- packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/FaceDetector.java
- packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/LabelDetector.java
- packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/TextRecognizer.java
If you attempt to use a Detector multiple times on Android without calling `detector.close()` eventually the app will crash. This happens because a new detector is instantiated for each `detectInImage` is called. I'm assuming the crash is from running out of memory (I get a seg fault error) because each detector loads a hefty model. 
iOS version doesn't have a close method, so I'm assuming it handles it's models differently.
My solution for this problem keeps one instance in memory to reuse. However, if the user wants to create a detector with different options, I close the previous instance and instantiate a new detector. 
The other option would be to give each instantiated detector a handle, but closing and instantiating a new one doesn't take very long if there is a use case where …
> Fix crash when repeating detection

- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
It was used for permission checking, I just included equivalent
permisison checking code and avoided the support library dependency.
> Don't depend on the Android support library in google_maps_flutter.

- packages/webview_flutter/lib/webview_flutter.dart
The double selection crash was fixed, but we are left with 2 other issues:
* The text selection dialog is not responding to touches.
* The text selection handles are not showing.
> Shuffle text selection TODOs.

- packages/device_info/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java
Using activity() causes a crash if the plugin is registered before the activity.
Fixes https://github.com/flutter/flutter/issues/24633
> Use context() instead of activity()

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/build.gradle
- packages/firebase_auth/android/gradle/wrapper/gradle-wrapper.properties
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/test/firebase_auth_test.dart
This standardises the error responses from the platform implementations. All functions in `FirebaseAuth` and `FirebaseUser` are now documented with error codes.
Fixes: flutter/flutter#18312 and Fixes: flutter/flutter#20223
This PR is based on #678 so includes the changes there.
**Example:**
```
PlatformException(ERROR_USER_NOT_FOUND, There is no user record corresponding to this identifier. The user may have been deleted., null)
PlatformException(ERROR_WRONG_PASSWORD, The password is invalid or the user does not have a password., null)
PlatformException(ERROR_NETWORK_REQUEST_FAILED, Network error (such as timeout, interrupted connection or unreachable host) has occurred., null)
```
Other changes include:
* Added missing `linkWithTwitterCredential` method.
* Updated deprecated API …
> Fixes error handling in firebase_auth on Android and iOS

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/example/pubspec.yaml
- packages/android_alarm_manager/pubspec.yaml
Update internal dependencies for alarm manager.
Looks like this is needed in order to get #917 to go green.
> [android_alarm_manager] bump firebase_auth dependencies

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/pubspec.yaml
Doing this to prevent confusion with the 0.0.1 google_maps_flutter package
which was accidentally published by a third-party.
> Bump google_maps_flutter version to 0.0.2 (pre release).

- packages/google_maps_flutter/ios/Classes/GoogleMapController.h
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/ios/Classes/GoogleMapsPlugin.h
The refactoring in #892 left the callbacks defined in `FLTGoogleMapDelegate` unhooked.
Fixes flutter/flutter#24520.
This change also removes the `FLTGoogleMapDelegate` protocol, it was used to
delegate map callbacks from the map controller to `FLTGoogleMapsPlugin`
which was the owner of the only method channel. As we now have a method
channel per map controller there is no need for a delegate.
This also renames `didTapInfoWindow` to `didTapInfoWindowForMarker` in
`FLTGoogleMapController`. This was just a typo when the code was first
introduced, and fixes flutter/flutter#20178.
Additionally this change cleans up the no longer used `addToView` and
`removeFromView` method from `FLTGoogleMapController`. These were
used by the overlay-based implementation, in the `UiKitView`
implementation the …
> Re-hook the Google Map callbacks on iOS(and some cleanups).

- packages/google_maps_flutter/ios/Classes/GoogleMapController.h
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
These are remains from the overlay-based implementation.
> Remove unused map id fields.

- packages/google_maps_flutter/lib/google_maps_flutter.dart
This was done in #463, not sure why, but I don't think we should export
it (and it makes Dartdoc complain).
> Don't export dart:async by the Google Maps plugin.

- packages/google_maps_flutter/README.md
This was temporarily removed in #925 while the plugin was accidentally
published by a third party.
> Bring back the google_maps_flutter pub badge.

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/pubspec.yaml
The `_registrar` field was never set in `FLTGoogleMapController`.
This made asset lookup return nil in `interepretMapOptions` resulting in
custom marker images not working.
> Keep a reference to the plugin registrar in `FLTGoogleMapController`.

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
- packages/camera/pubspec.yaml
Update the camera to use the physical device's orientation instead of
the UI orientation. Fixes issue where captured media is orientated to
match the screen UI at the time, instead of the actual device rotation.
Fixes flutter/flutter#18391
> Camera uses the device orientation on Android

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/pubspec.yaml
This is the latest version currently available for pub health checks.
We should increase the requirement once pub updates its Flutter version
(to make sure we're running with the recent Skia texture fixes).
> [google_maps_flutter] Relax Flutter version requirement to 0.11.9

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java
- packages/webview_flutter/ios/Classes/WebViewFlutterPlugin.h
- packages/webview_flutter/ios/Classes/WebViewFlutterPlugin.m
- packages/webview_flutter/pubspec.yaml
iOS build was failing on case-sensitive filesystems as the plugin name "WebviewFlutter" didn't match the case of "WebViewFlutterPlugin.h".
> Fixes: 'webview_flutter/WebviewFlutterPlugin.h' file not found

- packages/webview_flutter/pubspec.yaml
Apparently if the description is shorter than 60 characters you lose
maintaenance points on the pub website.
> Make the description for webview_flutter longer.

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/example/lib/main.dart
- packages/webview_flutter/ios/Classes/FlutterWebView.m
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/pubspec.yaml
- packages/webview_flutter/test/webview_flutter_test.dart
Add four methods below.
* `canGoBack` ... return true if WebView has previous page.
* `canGoForward` ... return true if WebView has next page.
* `goBack` ... navigate to previous page if it has previous page.
* `goForward` ... navigate to next page if it has next page.
| iOS | Android |
|:--:|:--:|
|![move in ios](https://user-images.githubusercontent.com/600512/49512252-b8ac8480-f8d0-11e8-82ac-58ebeee0c99f.gif) | ![move in android](https://user-images.githubusercontent.com/600512/49512265-c530dd00-f8d0-11e8-8098-153384769dba.gif)|
> Add navigation methods to webview_flutter

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/ios/Classes/FlutterWebView.m
- packages/webview_flutter/pubspec.yaml
If `initialUrl` is null or unspecified, it will be treated as `NSNull` (not `nil`) on objc and crash on calling `loadUrl`.
So. add checking `initialUrl` and convert `NSNull` to `nil`.
> Fix initialUrl null check for webview_flutter

- packages/android_alarm_manager/README.md
- packages/android_alarm_manager/pubspec.yaml
The Android_Alarm_Manager-Plugin is not working for me because it has `firebase_auth` as a dependency, but the dependency seems to be not needed. It's only being used in the example, which has its own `pubspec.yaml` file.
In the readme, there was also the initialization for the plugin missing, which has now been added.
> Remove firebase_auth dependency from android_alarm_manager library and add initialize step to readme

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/example/ios/Flutter/Debug.xcconfig
- packages/webview_flutter/example/ios/Flutter/Release.xcconfig
- packages/webview_flutter/example/lib/main.dart
- packages/webview_flutter/ios/Classes/FlutterWebView.m
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/pubspec.yaml
- packages/webview_flutter/test/webview_flutter_test.dart
This allows Flutter to query to WebView to find out what URL it is currently displaying.
> Add currentUrl accessor to WebView plugin.

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
- packages/camera/pubspec.yaml
This fixes https://github.com/flutter/flutter/issues/25105.
The error was caused by the following:
> In the plugin the currentOrientation property is set to the constant ORIENTATION_UNKNOWN by default, which results in -1. When your orientation updates, it is set to the actual value. The setOrientationHint function only accepts 0, 90, 180 and 270 as argument. When calculating the orientation it adds the 1 or -1 (depending on whether you are using the back or front camera). That resulted in 271, which isn't accepted and caused your error. 
Fixed it by checking the value in ``getMediaOrientation()``.  If the orientation is unknown, it will be set to 0.
> [camera] Fix issue with crash when the physical device's orientation is unknown on Android.

- .cirrus.yml
Cirrus puts the PR description and commit message in environment
variables.
These messages tend to have non ASCII characters sometimes (like
emojis), which triggers a Gradle bug (gradle/gradle#3117) resulting
in Gradle crashing without a helpful error message.
The real solution to this problem should be fixing the Gradle bug.
The better workaround on the Flutter side would be to set a UTF8 locale
on the Cirrus machine, but I have yet figured out how to do it.
For now to avoid more people from hitting this I'm working around by
temporarily unsetting the Cirrus environment variables with the PR
description and commit message.
A non ASCII character to make sure it works: 😄
More details (including my failed attempts to set a UTF8 locale on Cirrus) here: …
> Workaround the Gradle crash due to non ASCII characters.

- LICENSE
The comments are preventing GitHub's license detection from working (see https://github.com/flutter/packages/blob/master/LICENSE as an example where it's working)
> Remove comments from license file

- packages/camera/CHANGELOG.md
- packages/camera/ios/Classes/CameraPlugin.m
- packages/camera/pubspec.yaml
This patch works by calculating the device's physical orientation from
accelerometer data. This is a tricky approach and I'd rather avoid it,
but it looks like a necessary evil based on a few reasons.
1. The specific callback we're registering doesn't give us any EXIF data
or data on the photo's orientation.
https://developer.apple.com/documentation/avfoundation/avcapturephotocapturedelegate/1778647-captureoutput?language=objc
2. There is a better callback to use that does give us this data, but
it's only supported on ios 11.0+ and the camera plugin supports
10.0+.
https://developer.apple.com/documentation/avfoundation/avcapturephotocapturedelegate/2873949-captureoutput?language=objc
3. There's a straightforward iOS API that's supposed to give the
physical device orientation that would …
> Save photo orientation on iOS

- packages/image_picker/CHANGELOG.md
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
- packages/image_picker/pubspec.yaml
fix an IOS crash when the image picker got tapped multiple times. flutter/flutter#20214
When the image in the imagePicker was tapped multiple times, the delegate method didFinishPickingMediaWithInfo gets called multiple times. _result is set to nil at the end of the didFinishPickingMediaWithInfo call.
When the second didFinishPickingMediaWithInfo gets triggered, because _result is nil, crash is caused.
We can also fix it by putting the code after selection inside the completion handler, it will cause a little delay in image showing up after completion. So directly checking if _result is nil and stop the process would be more efficient.
> Fix image picker crash on IOS

- packages/url_launcher/lib/url_launcher.dart
There are numbers of users having problem on launch universal links on iOS. 
It is most likely due to the unawareness of forceSafariVC is true by default and safariVC will not handle universal links. 
Adding document to explain this particular usage.
> Update dart doc for forceSafariVC for the usage of universal links on iOS

- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
There is a crash due to Result already being submitted when startPreview() throws an error. This is because do result.error() in the catch block and then continue on to do result.success() later. If there is an error we should return early.
> Fix Crash When StartPreview Error

- packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/lib/src/channel.dart
- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
- packages/in_app_purchase/test/billing_client_wrappers/billing_client_wrapper_test.dart
- packages/in_app_purchase/test/fake_in_app_purchase_platform.dart
- packages/in_app_purchase/test/in_app_purchase_connection/app_store_connection_test.dart
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
- packages/in_app_purchase/test/store_kit_wrappers/sk_payment_queue_wrapper_test.dart
- packages/in_app_purchase/test/stub_in_app_purchase_platform.dart
Rename `PlatformViewsController` to `StubInAppPurchasePlatform` to more
accurately describe what it's stubbing. Remove the overcomplicated
`Channel` class and just set a mock handler on the `const MethodChannel`
used by the entire plugin itself.
> [IAP] Clean up Dart unit tests

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java
- packages/url_launcher/example/lib/main.dart
- packages/url_launcher/ios/Classes/UrlLauncherPlugin.m
- packages/url_launcher/lib/url_launcher.dart
- packages/url_launcher/pubspec.yaml
- packages/url_launcher/test/url_launcher_test.dart
Added a setting `universalLinksOnly` for IOS with version >= 10.0
With setting this to true, user can now force the URL Launcher to launch universal links only when the app for the universal link is installed. If the app is not installed, a Platform exception will be thrown. By catching the exception, other actions can be performed. E.g. open the URL destination in a Safari View Controller. 
This is an improvement requested in https://github.com/flutter/flutter/issues/25991
Updated the version to 4.1.0 because there is a breaking change updating `launch` to return bool from void
> Url launcher ios universallinksonly

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
- packages/image_picker/pubspec.yaml
Some devices use different path for downloaded images. Those devices will crash when trying the access the public_download URI. 
Directly use default downloaded image URI instead of hard coding the string fixes the crash.
https://github.com/flutter/flutter/issues/21863
> Fix a crash when selecting downloaded images on certain devices

- packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java
- packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java
- packages/in_app_purchase/example/android/app/build.gradle
- packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/InAppPurchasePluginTest.java
- packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/TranslatorTest.java
- packages/in_app_purchase/lib/billing_client_wrappers.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/sku_details_wrapper.dart
- packages/in_app_purchase/test/billing_client_wrappers/billing_client_wrapper_test.dart
- packages/in_app_purchase/test/billing_client_wrappers/sku_details_wrapper_test.dart
Adds the `queryProductsAsync` API and associated classes to
`billing_client_wrappers/`.
Brings in `json_serializable` as a build step to generate the Dart
platform channel parsing boilerplate. This dependency is still very
experimental and may be abandoned if the extra build step ends up being
a maitenance burden greater than maintaining the boilerplate. At this
point I expect it to be worth the trouble given the sheer amount of data
classes and deserialization that's going to happen in this plugin.
flutter/flutter#26325
> [IAP] Fetch SkuDetails from Google Play

- .ci/Dockerfile
- .cirrus.yml
This was ripped off #1091.
CI was failing on multiple packages when trying to build apks with:
```
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
platforms;android-27 Android SDK Platform 27
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
Using Android SDK: /opt/android-sdk-linux
```
This tweaks the docker file to also install Android SDK 27 accept licenses for it, which fixes the CI failure.
The patch was authored by …
> Include Android SDK 27 in the docker image and accept licenses

- packages/in_app_purchase/README.md
- packages/in_app_purchase/analysis_options.yaml
- packages/in_app_purchase/build.yaml
- packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/enum_converters.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/enum_converters.g.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/sku_details_wrapper.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/sku_details_wrapper.g.dart
- packages/in_app_purchase/pubspec.yaml
- packages/in_app_purchase/test/billing_client_wrappers/billing_client_wrapper_test.dart
- packages/in_app_purchase/test/billing_client_wrappers/sku_details_wrapper_test.dart
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
Brings in `json_serializable` as a build step to generate the Dart
platform channel parsing boilerplate. This dependency is still very
experimental and may be abandoned if the extra build step ends up being
a maitenance burden greater than maintaining the boilerplate. At this
point I expect it to be worth the trouble given the sheer amount of data
classes and deserialization that's going to happen in this plugin.
Also converts `SkuType` and `BillingResponse` to enums.
> [IAP] Generate boilerplate serializers

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/lib/url_launcher.dart
- packages/url_launcher/pubspec.yaml
This is a fix for the comments https://github.com/flutter/flutter/issues/25991#issuecomment-457834526 and https://github.com/flutter/flutter/issues/25991#issuecomment-458002938 which mentioned that the `launch` api returns null instead of a boolean.   https://github.com/flutter/flutter/issues/25991
> Updated `launch` to use async and await, fixed the incorrect return value by `launch` method.

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/README.md
- packages/android_alarm_manager/android/build.gradle
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmBroadcastReceiver.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java
- packages/android_alarm_manager/example/android/app/src/main/AndroidManifest.xml
- packages/android_alarm_manager/example/pubspec.yaml
- packages/android_alarm_manager/pubspec.yaml
* Updated android_alarm_manager to fix issues with "background start not
allowed" when attempting to start AlarmService while backgrounded.
* Switched to using a combination of BroadcastReceiver and
JobIntentService from using a Service (launching a Service from an
alarm Intent causes the "Background start not allowed" on Android 8+)
* Alarm events received before the AlarmService isolate is finished
initializing are now queued and processed once the isolate is
initialized.
* Updated CHANGELOG.md and README.md with new setup steps.
* Bumped version to 0.4.0.
Fixes flutter/flutter#26846.
> android_alarm_manager background execution bug fixes

- packages/shared_preferences/CHANGELOG.md
- packages/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java
- packages/shared_preferences/pubspec.yaml
Use string to save double for shared_preference instead of converting it to float.
This will fix: https://github.com/flutter/flutter/issues/27222
> Use string to save double for shared_preference(Android).

- packages/device_info/lib/device_info.dart
Fix broken documentation link to AndroidBuildVersionCodes
> Fix broken documentation link to AndroidBuildVersionCodes

- packages/cloud_firestore/android/build.gradle
- packages/cloud_functions/android/build.gradle
- packages/firebase_dynamic_links/android/build.gradle
- packages/firebase_messaging/android/build.gradle
- packages/firebase_ml_vision/android/build.gradle
- packages/firebase_remote_config/android/build.gradle
- packages/firebase_storage/android/build.gradle
Apparently some dependencies like android.support.annotation were implicitly available, but that doesn't seem to be true anymore with AndroidX.
Tracked in flutter/flutter#23995.
Related to https://github.com/flutter/plugins/pull/1115
> A few additional Androix dependencies

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
- packages/image_picker/pubspec.yaml
Resolves https://github.com/flutter/flutter/issues/19819
When the `image_picker` is called before another call is finished it should return an error with the `MethodResult` object that came with the last method call. But instead it uses the `MethodResult` object from the first method call. When finishing up the first method call, the `pendingResult` (`MethodResult` object of the first call) property will already be set to null.
> [image_picker] Fixed a crash that would occur when called in quick succession on Android

- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_product_wrapper.dart
- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_product_wrapper.g.dart
- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_request_maker.dart
- packages/in_app_purchase/test/store_kit_wrappers/sk_product_test.dart
- packages/in_app_purchase/test/store_kit_wrappers/sk_request_test.dart
Replacing the manually coded fromMap methods with auto generated methods using JSON Serializer.
> Use json serializer for skproduct wrapper and related classes.

- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/JavaScriptChannel.java
Platform implementation of the method channel API for adding and removing JavaScript channels.
#1116 adds the Dart side support, the current PR will land first.
flutter/flutter#24837
> WebView JavasScript channels Android implementation.

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/example/lib/main.dart
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/pubspec.yaml
- packages/webview_flutter/test/webview_flutter_test.dart
Allows JavaScript code running in the WebView to send messages that will be received by the Flutter app's Dart code.
To keep the PRs smaller this does not include the platform side implementations which will be sent in following PRs.
Right now there are no return values on the JavaScript side, we could think of returning a JavaScript promise (or a promise equivalent) in the future, but as a first step I start without it (`evaluateJavascript` can be used to pass messages in the other direction so this shouldn't be a blocking limitation).
I believe that if we end up adding a return value on the JavaScript side this could be done without making a breaking change.
Dart:
```dart
WebView(
javascriptChannels: <JavascriptChannel>[
JavascriptChannel(name: 'Print', onMessageReceived: (String msg) …
```
> Add WebView JavaScript channels (Dart side).

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/README.md
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/RebootBroadcastReceiver.java
- packages/android_alarm_manager/example/android/app/src/main/AndroidManifest.xml
- packages/android_alarm_manager/lib/android_alarm_manager.dart
- packages/android_alarm_manager/pubspec.yaml
Android doesn't automatically reschedule alarms after a reboot, so
alarms set using this plugin would have to be scheduled manually after
each reboot. With this change, alarms scheduled with the 'rescheduleOnReboot'
flag set to true will be rescheduled at boot.
> Added support for persisting alarms across reboots

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/pubspec.yaml
A temporary workaround to fix the camera positioning issue mentioned in https://github.com/flutter/flutter/issues/24806
> Workaround to fix the camera positioning issue on the google map view

- packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/Stubs.m
- packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/TranslatorTest.m
- packages/in_app_purchase/ios/Classes/FIAObjectTranslator.h
- packages/in_app_purchase/ios/Classes/FIAObjectTranslator.m
- packages/in_app_purchase/lib/src/billing_client_wrappers/sku_details_wrapper.g.dart
- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_product_wrapper.dart
- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_product_wrapper.g.dart
- packages/in_app_purchase/test/store_kit_wrappers/sk_product_test.dart
- packages/in_app_purchase/test/store_kit_wrappers/sk_request_test.dart
To make to code simple, NSLocale has not been fully exposed.
Expose the NSLocale inside the priceLocale layer to match the SKProduct composition; this makes future changes regarding priceLocale to be non-breaking changes.
> Expose nslocale and expose currencySymbol instead of currencyCode to match android

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- packages/google_sign_in/pubspec.yaml
Fix https://github.com/flutter/flutter/issues/12734
When users are setting up the google sign in plugin, if for some reason, the `<key>CFBundleURLTypes</key>` is not properly set, we do not provide a clear enough error message to make their debugging life happier. 
We would still like to crash the app since the crash would be a good reminder for the users to set up any necessary properties to use this plugin, and the users should not ship the product without fixing the issue that causes the exception. 
After this fix, the error message will be shown as 
```
flutter: PlatformException(google_sign_in, Your app is missing support for the following URL schemes: com.googleusercontent.apps.479882132969-9i9aqik3jfjd7qhci1nqf0bm2g71rm1u, NSInvalidArgumentException)
*** First throw call stack:
(
0 …
```
> Expose exception on the signIn method in Google sign in.

- packages/local_auth/ios/Classes/LocalAuthPlugin.m
Now in local_auth, the biometrics logic under ios11 is not working, fix it.
This would fix: https://github.com/flutter/flutter/issues/27366
https://github.com/flutter/flutter/issues/25635
> Fix biometrics check error below ios11.

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java
- packages/image_picker/pubspec.yaml
Fixing https://github.com/flutter/flutter/issues/21972
> Fixed image picker crash when used with android alarm manager

- packages/in_app_purchase/pubspec.yaml
- packages/location_background/pubspec.yaml
- script/check_publish.sh
Skip publish checks on `publish_to: none` packages so that CI doesn't
fail with this change.
Related to flutter/flutter#27258
Works around dart-lang/pub#2004
> Mark some packages as unpublishable

- packages/firebase_performance/CHANGELOG.md
- packages/firebase_performance/ios/Classes/FirebasePerformancePlugin.m
- packages/firebase_performance/pubspec.yaml
Fixes https://github.com/flutter/flutter/issues/24518
> Fix bug where HttpMetric/Trace dictionaries weren't being initialized on iOS

- packages/firebase_ml_vision/CHANGELOG.md
- packages/firebase_ml_vision/ios/firebase_ml_vision.podspec
- packages/firebase_ml_vision/pubspec.yaml
When using `firebase_ml_vision` plugin, you would receive this error after running `pod update`:
```
*** Terminating app due to uncaught exception 'FIRAnalyticsVersionMismatch', reason:
'Google Analytics for Firebase version (50300000) does not match with Google App Measurement 
(50500000) version. Please update.'
```
We solve this by setting the compatible `GoogleAppMeasurement` version in plugin podspec.
Fixes https://github.com/flutter/flutter/issues/23259
> Set GoogleAppMeasurement dependency version

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/pubspec.yaml
- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/pubspec.yaml
The reference from the method channel to the webview/maps instance was never cleared on Android, which leaked memory as even after disposing the platform view the view was not released.
https://github.com/flutter/flutter/issues/24145
> Remove the method channel's reference to webview/maps on dispose.

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/ios/Classes/UrlLauncherPlugin.m
- packages/url_launcher/pubspec.yaml
Fixing some unnoticed issues from #924. Moved the deallocation of the `currentSession` object to a closure that is called when the Safari VC is dismissed. Now it is deallocated if the `closeWebView` function is called, or if the user manually dismissed the VC.
I didn't notice any Android issues while testing. I think sometimes the simulator can take a while to launch a Web View and if it takes longer than 5 seconds it appears like there is a bug, but it is working fine for me.
> closeWebView fixes for url_launcher

- packages/in_app_purchase/android/build.gradle
- packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java
- packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/InAppPurchasePluginTest.java
- packages/in_app_purchase/lib/src/billing_client_wrappers/sku_details_wrapper.g.dart
The call requires passing in a fully constructed `SkuDetail`. We could
fetch it again at runtime here, but for now I'm opting for caching
fetched SkuDetails and requiring them to be fetched before this call
instead to mirror how the iOS side is working.
flutter/flutter#26327
> [IAP] Add Java call for launchBillingFlow

- packages/camera/CHANGELOG.md
- packages/camera/ios/Classes/CameraPlugin.m
- packages/camera/pubspec.yaml
- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/pubspec.yaml
- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/ios/Classes/FirebaseAdMobPlugin.m
- packages/firebase_admob/pubspec.yaml
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/pubspec.yaml
- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/ios/Classes/FirebaseCorePlugin.m
- packages/firebase_core/pubspec.yaml
- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/pubspec.yaml
- packages/firebase_dynamic_links/CHANGELOG.md
- packages/firebase_dynamic_links/ios/Classes/FirebaseDynamicLinksPlugin.m
- packages/firebase_dynamic_links/pubspec.yaml
- packages/firebase_ml_vision/CHANGELOG.md
- packages/firebase_ml_vision/ios/Classes/FirebaseMlVisionPlugin.m
- packages/firebase_ml_vision/pubspec.yaml
- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/ios/Classes/FirebaseStoragePlugin.m
- packages/firebase_storage/pubspec.yaml
- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m
- packages/google_sign_in/pubspec.yaml
Fixing https://github.com/flutter/flutter/issues/27361 and https://github.com/flutter/flutter/issues/27960
Used static c function instead of category.
The plugins effected are 
cloud_firestore
firebase_admob
firebase_auth
firebase_core
firebase_database
firebase_dynamiclink
firebase_mlvision
firebase_storage
google_signin
camera
> Remove categories

- packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/InAppPurchasePluginTest.m
- packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/PaymentQueueTest.m
- packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/Stubs.h
- packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/Stubs.m
- packages/in_app_purchase/ios/Classes/FIAPaymentQueueHandler.h
- packages/in_app_purchase/ios/Classes/FIAPaymentQueueHandler.m
- packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.h
- packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m
The objective-c portion of add payment flow.
Since there is no dart code in this PR, it could be hard to trace what is going on. Included 2 purchase flows below to better explain.
A regular flow of a user to process a purchase will be as such:
1. User queries the products by `-[InAppPurchasePlugin startProductRequest:result:]`
2. User creates a payment object using productID which is found in the result of the 1st step.
3. User make a payment calling `-[InAppPurchasePlugin addPayment:result:]` using the payment object gotten from step 2.
4. `updatedTransaction` in dart waiting for the transaction to be at state of 'purchased'
5. User finish the transaction by calling `-[InAppPurchasePlugin finishTransaction:result:]` with the transaction gotten from step 4.
A app store purchase flow will …
> Iap make payment objc

- packages/webview_flutter/lib/webview_flutter.dart
I copy `JavascriptChannel` from the document, but it has an error.
I hope to update the document.
> Bugfix documents: webview_flutter JavascriptChannel, Example is not updated.

- packages/firebase_messaging/CHANGELOG.md
Remove a leftover conflict marker from https://github.com/flutter/plugins/commit/c96eb1bf358a3d6e3cf7847bb921c114168210c1
> Remove left over conflict marker

- packages/cloud_functions/CHANGELOG.md
- packages/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/cloudfunctions/cloudfunctions/CloudFunctionsPlugin.java
- packages/cloud_functions/ios/Classes/CloudFunctionsPlugin.m
- packages/cloud_functions/lib/cloud_functions.dart
- packages/cloud_functions/pubspec.yaml
- packages/cloud_functions/test/cloud_functions_test.dart
> cloud functions multiple app support

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/README.md
- packages/android_alarm_manager/example/android/app/src/main/AndroidManifest.xml
- packages/android_alarm_manager/pubspec.yaml
The WAKE_LOCK permission is required by the [JobIntentService](https://developer.android.com/reference/android/support/v4/app/JobIntentService) on pre-O versions. Without this permission, a `java.lang.SecurityException` is thrown. 
Fixes documentation issue which arose from flutter/flutter#27921
> Update android_alarm_manager with instructions on setting WAKE_LOCK permissions

- packages/video_player/ios/Classes/VideoPlayerPlugin.m
This avoids platform dependent compilations errors and is the official recommendation by Apple: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html
Also remove a couple of unused vars.
> [video_player] Cast the NSInteger to long and use %ld formatter

- packages/google_maps_flutter/example/lib/scrolling_map.dart
Unfortunately we can't fix this and still be compatible with stable, so
for now this is just being disabled to unbreak CI.
> Disable analyzer error

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
- packages/camera/pubspec.yaml
- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java
- packages/google_maps_flutter/pubspec.yaml
Background FlutterViews do not have an activity, the Maps and Camera
plugins are foreground only and assumed and activity is available which
can result in a crash when the plugin is registered by a background
FlutterView.
We workaround by just not registering the plugins if there is no
activity.
Similar to https://github.com/flutter/plugins/pull/1125
> Don't register the Maps and Camera plugin for background FlutterViews.

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/pubspec.yaml
Only applications that use the MyLocation feature needs to add the
location permission to the Android manifest, but in some configurations
Gradle fails the build if the permission is not included.
Fixes https://github.com/flutter/flutter/issues/28339
> Skip Gradle's static permission check for the Maps MyLocation feature.

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/pubspec.yaml
- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/pubspec.yaml
- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/ios/Classes/FirebaseStoragePlugin.m
- packages/firebase_storage/pubspec.yaml
When `getFlutterError` was introduced, some plugins started to throw exceptions for successful operations. I originally faced that with `firebase_database`, but I can see the same happened to `cloud_firestore`.
As you can see in the code, either the caller would have to be changed to check for `error == nil` before calling it, or we can do it inside `getFlutterError` and keep the plugin original code.
I checked the other plugins, and apparently they don't need the same change as they already do the check or use the `getFlutterError` differently.
Some of the formatting of the error code was slightly changed and I restored it to what it was, please let me know if that's ok or if that change was intentional.
intends to
fix flutter/flutter#28344
fix flutter/flutter#28065
fix …
> [cloud_firestore,firebase_database,firebase_storage] handling error nil on getFlutterError

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/ios/Classes/FirebaseCorePlugin.m
- packages/firebase_core/pubspec.yaml
- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
- packages/firebase_database/pubspec.yaml
After I removed categories in https://github.com/flutter/plugins/pull/1226, I missed the nil check. 
This PR is to add those nil checks to make the static method behave as the same as the category functions if the parameter is nil, this is a similar fix following up https://github.com/flutter/plugins/pull/1274
> [firebase_core][firebase_database]Add nil check for some static methods to avoid unwanted behaviors

- packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java
- packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java
- packages/in_app_purchase/example/android/app/build.gradle
- packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/InAppPurchasePluginTest.java
- packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/TranslatorTest.java
Actually responds in the onPurchasesUpdated() handler automatically
called when purchase updates are received.
Exposes BillingClient#queryPurchases, which is meant to be used to get
recently purchased items from the on disk Play cache.
Also exposes BillingClient#queryPurchaseHistoryAsync, which returns the
most recent purchase of the user for each SKU of the given type.
This patch also contains some updates to the Gradle script so that the
example app version is set independently of the Flutter SDK version.
> [in_app_purchase] Java API for querying purchases

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/README.md
- packages/firebase_auth/example/lib/main.dart
- packages/firebase_auth/example/lib/register_page.dart
- packages/firebase_auth/example/lib/signin_page.dart
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/pubspec.yaml
This is an improvement of the documentation and the example for [flutter/flutter#16217](https://github.com/flutter/flutter/issues/16217)
Added a registration flow and a sign in with email&password flow in the example app.
Separated the example app into 2 parts: registration and SignIn/SignOut.
Updated README, added a list of supported authentication methods and an example of registration.
> [firebase_auth] update example app and README

- packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java
- packages/in_app_purchase/example/android/app/build.gradle
- packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/InAppPurchasePluginTest.java
- packages/in_app_purchase/example/keystore.example.properties
- packages/in_app_purchase/example/lib/main.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/enum_converters.g.dart
Some refactoring split out from a future patch on querying the purchase
history.
1. Moved all Android app-specific information to the keystore.properties
file. I initially didn't put everything there because normally the
keystore file only has signing information. But the app ID, verison
name, and version code all do need to be potentially modified in the
example to get it up and running. They're not inherently sensitive
like the signing information is but it probably makes sense to keep
them out of source control for the plugin repo too.
2. Fixed the MethodChannel argument naming for some of the new methods.
3. Added a missing `BillingResponse` code.
4. Changed the `BillingClient#_callbacks` to be a map of lists instead
of a list of maps. The OnPurchasesUpdated() listener is a singleton …
> [in_app_purchase] Minor bugfixes and code cleanup

- packages/google_maps_flutter/README.md
The sample code doesn't work.  It needs an icon specified for the FloatingActionButton.
> [google_maps_flutter] The FloatingActionButton requires an icon

- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
When the user picks a png that has transparent pixels, these are then lost (made black). This was caused by always saving the image as JPEG when resizing. 
At first I always saved the image as PNG, but that did not work very well for Android, where the JPEG format carried important rotation (EXIF) information. So for Android I am deciding the output format based on the file extension. For iOS things are a bit simpler and we can just always save as png.
> [image_picker]Fixed losing transparency of PNGs

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/build.gradle
- packages/google_maps_flutter/example/android/app/src/main/AndroidManifest.xml
- packages/google_maps_flutter/pubspec.yaml
Addresses https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library
Also removed the need to legacy override in manifest
> Update play-services-maps from 15.+ to 16.1.0

- AUTHORS
- packages/firebase_performance/ios/Classes/FirebasePerformancePlugin.m
The args for trace and metric attributes are the wrong way around, attribute value is where the key should be and vice-versa. This PR swaps them around for both.
- Fixed a bug where attributes for `Traces` and `HttpMetrics` were incorrectly using the attribute value as the attributes' name.
> [firebase_performance] Fix incorrect setting of Trace & HttpMetric attributes

- packages/firebase_performance/CHANGELOG.md
- packages/firebase_performance/ios/Classes/FirebasePerformancePlugin.m
- packages/firebase_performance/pubspec.yaml
(My `AUTHORS` file change is on another PR: https://github.com/flutter/plugins/pull/1277)
The Trace API `incrementCounterNamed` has been deprecated for some time (since Firebase iOS SDK v5.0.0 - May 2018, we're now on 5.17.0). This PR switches to using the replacement metrics API; specifically `setIntValue` (not increment as formerly used - as we're only setting the value once).
Ideally the `firebase_performance.podspec` for Performance should be specifying a version of the Pod to use; but as none of the other Firebase packages do this I can't change this one without causing duplication build issues. The same applies if a newer version of the Firebase iOS SDK is released with breaking changes; as none of the podspecs are version locked they will always install the latest version. …
> [firebase_performance] remove deprecated trace counter API usage

- packages/firebase_dynamic_links/CHANGELOG.md
- packages/firebase_dynamic_links/pubspec.yaml
Version bump for https://github.com/flutter/plugins/pull/1142
> [firebase_dynamic_links] Version bump for firebase_dynamic_links PR #1142

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/example/lib/map_ui.dart
- packages/google_maps_flutter/lib/src/controller.dart
- packages/google_maps_flutter/lib/src/google_map.dart
- packages/google_maps_flutter/pubspec.yaml
This facilitates better interaction with the map
than adding a listener to the controller.
> [google_maps_flutter]ChangeNotifier is replaced with granular callbacks

- AUTHORS
- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java
- packages/firebase_analytics/ios/Classes/FirebaseAnalyticsPlugin.m
- packages/firebase_analytics/lib/firebase_analytics.dart
- packages/firebase_analytics/pubspec.yaml
- packages/firebase_analytics/test/firebase_analytics_test.dart
This PR adds support for the missing resetAnalyticsData method to the firebase_analytics package.
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#resetAnalyticsData()
> [firebase_analytics] Add resetAnalyticsData method

- packages/cloud_functions/CHANGELOG.md
- packages/cloud_functions/example/pubspec.yaml
- packages/cloud_functions/ios/Classes/CloudFunctionsPlugin.m
- packages/cloud_functions/ios/cloud_functions.podspec
- packages/cloud_functions/pubspec.yaml
Recently Cloud Functions changed their API in a breaking fashion, which caused build errors for some users. Also fixes a regression in the new region handling that didn't handle the default case gracefully.
Fixes flutter/flutter#28433
Fixes flutter/flutter#28578
I verified manually that the iOS app works properly.
> [cloud_functions] Specify version for CocoaPod and handle null regions gracefully

- packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java
- packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/TranslatorTest.java
- packages/in_app_purchase/lib/billing_client_wrappers.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/purchase_wrapper.dart
- packages/in_app_purchase/lib/src/billing_client_wrappers/purchase_wrapper.g.dart
- packages/in_app_purchase/lib/src/in_app_purchase_connection/google_play_connection.dart
- packages/in_app_purchase/test/billing_client_wrappers/billing_client_wrapper_test.dart
- packages/in_app_purchase/test/billing_client_wrappers/purchase_wrapper_test.dart
- packages/in_app_purchase/test/billing_client_wrappers/sku_details_wrapper_test.dart
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
1. Wires the Purchase data class and serializers in to Dart.
2. BillingClient now requires a callback for responding to purchase
updates to be passed in at construction time.
3. Exposes `BillingClient#queryPurchases` and
`BillingClient#queryPurchaseHistory`.
For now GooglePlayConnection passes in a lambda that does nothing to
`BillingClient`. This will need to be fixed when all the connections are
updated.
> [in_app_purchase] Adds Dart BillingClient APIs for loading purchases

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/pubspec.yaml
The longpress handler should not be exposed to the semantics tree since it doesn't do anything. It will just confuse screenreaders.
> Exclude longPress from semantics

- packages/image_picker/android/src/main/AndroidManifest.xml
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
- packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerDelegateTest.java
fixed https://github.com/flutter/flutter/issues/19806
> [image_picker] remove unnecessary camera permmision

- packages/webview_flutter/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- packages/webview_flutter/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- packages/webview_flutter/ios/Classes/FLTWKNavigationDelegate.h
- packages/webview_flutter/ios/Classes/FLTWKNavigationDelegate.m
- packages/webview_flutter/ios/Classes/FlutterWebView.m
This is the iOS implementation of the navigation delegate method channel.
The Dart and Android implementations are in https://github.com/flutter/plugins/pull/1236
Splitting off the iOS to keep a reasonable change size.
This PR will be merged first.
https://github.com/flutter/flutter/issues/25329
> Allow specifying a navigation delegate (iOS implementation).

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
- packages/image_picker/pubspec.yaml
fixed https://github.com/flutter/flutter/issues/23500
> [image_picker] delete original file if scaled

- packages/package_info/CHANGELOG.md
- packages/package_info/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java
- packages/package_info/pubspec.yaml
fixed https://github.com/flutter/flutter/issues/28155
> [package_info] calling new method for BuildNumber in new android versions

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
- packages/image_picker/pubspec.yaml
fixed https://github.com/flutter/flutter/issues/26940
fixed https://github.com/flutter/flutter/issues/21547
> [image_picker] fix error if pick image from yandex disk(dropbox)

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/pubspec.yaml
Fixes flutter/flutter#15837
iOS only
In addition to making our iOS plugin usage of the API match the [docs](https://firebase.google.com/docs/firestore/query-data/listen), this also fixes a case where we were returning from method call twice in an error case.
on Android we check if the error is not null per the example code.
> [cloud_firestore] ios ceck for nil snapshot in cloud_firestore error handling instead of checking for non-nil error

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/example/pubspec.yaml
- packages/cloud_firestore/example/test_driver/cloud_firestore.dart
- packages/cloud_firestore/example/test_driver/cloud_firestore_test.dart
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/pubspec.yaml
Fixes a `NoSuchMethodError` in getDocuments(), introduced in #1339
Adds a simple driver test for the fix.
Fixes flutter/flutter#29423
> [cloud_firestore] fix NoSuchMethodError regression and add test

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/example/pubspec.yaml
- packages/firebase_auth/example/test/firebase_auth.dart
- packages/firebase_auth/example/test/firebase_auth_test.dart
- packages/firebase_auth/example/test_driver/firebase_auth_test.dart
- packages/firebase_auth/pubspec.yaml
This checks in an E2E plugin test and widget test for firebase_auth so that we can add regression tests for improvements that we make.
> [firebase_auth] Add a driver test

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
- packages/image_picker/pubspec.yaml
google photo version 4.10.0.233345822 on Android 9 return Uri with authority "com.google.android.apps.photos.contentprovider". for backward compatibility I changed equals to startsWith.
> [image_picker] update Uri Authority for GooglePhotos

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/pubspec.yaml
- packages/webview_flutter/test/webview_flutter_test.dart
discussed with @amirh - refactor `WebViewController` to hold a reference to the `WebView` widget. Basically to make it less error prone/less code to add more web callback handlers to the widget for later PRs.
> [webview_flutter] Refactor WebViewController to have a reference to the widget, to minimize necessary update calls.

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/ios/firebase_crashlytics.podspec
- packages/firebase_crashlytics/pubspec.yaml
`[!] The 'Pods-Runner' target has transitive dependencies that include static binaries:
(/Users/leofarias/Documents/Projects/brand-app/ios/Pods/Crashlytics/iOS/Crashlytics.framework and
/Users/leofarias/Documents/Projects/brand-app/ios/Pods/Fabric/iOS/Fabric.framework)`
Whenever building the plugin using swift I am getting the error above.
`s.static_framework = true` seems to do the trick
> [firebase_crashlytics] Support compatibility with Swift plugins

- .opensource/project.json
Add Crashlytics plugin to the list of Firebase Flutter open source libraries. This change will list it here:
https://firebaseopensource.com/projects/flutter/plugins/
> Add Crashlytics plugin to opensource list

- packages/google_maps_flutter/test/marker_updates_test.dart
Currently the maps plugin is updating over the platform channel all markers instead of just the ones that were actually changed.
This adds a failing test (that's currently skipped) that should pass once the bug is fixed.
https://github.com/flutter/flutter/issues/27823
- [] All existing and new tests are passing. …
> [google_maps_flutter] Add failing test verifying that only changed markers are updated

- packages/firebase_dynamic_links/CHANGELOG.md
- packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java
- packages/firebase_dynamic_links/ios/Classes/FirebaseDynamicLinksPlugin.m
- packages/firebase_dynamic_links/pubspec.yaml
As in link, there is a case of nil at the completion of handleUniversalLink.
https://github.com/firebase/firebase-ios-sdk/issues/2303
Also, even if  sleep,  cause an error, so fixed it to tell
it to the dart side.
https://github.com/flutter/flutter/issues/27810
> [firebase_dynamic_links] sometimes got error NSPOSIXErrorDomain Code=53 in ios

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
In firebase_auth PhoneCodeAuthRetrievalTimeout callback never called. This is due to a typo and which is fixed in this PR.
https://github.com/flutter/flutter/issues/22725
> [firebase_auth]Fix PhoneCodeAuthRetrievalTimeout callback never called

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/README.md
- packages/firebase_crashlytics/pubspec.yaml
Seems like the API has changed but not the code example.
reportInDevMode -> enableInDevMode
README change. Code example 
- [x ] No, this is *not* a breaking change.
> [firebase_crashlytics] Update README code example

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
- packages/camera/pubspec.yaml
setRepeatingRequest calls checkNotClosed
if the session is closed, it throws an IllegalStateException which is not caught in the catch block.
I think we should look for the root reason that, why the session is closed before it is even started?!
https://github.com/flutter/flutter/issues/29925 …
> [camera] Fixes (#29925)

- packages/webview_flutter/example/pubspec.yaml
- packages/webview_flutter/example/test_driver/webview.dart
- packages/webview_flutter/example/test_driver/webview_test.dart
- packages/webview_flutter/pubspec.yaml
Add initial flutter driver based e2e tests for webview_flutter.
@collinjackson a few notes for stuff I ran into while writing this:
* I'm not using the example app at all other than it's iOS project setup, not a big deal but might make sense to consider supporting such an integration test out of the `example/` folder.
* I couldn't use the WidgetTester as it is asserting that the platform is flutter_tester, maybe we should change that?
* Because I couldn't use the widget tester I used `runApp()` directly in each test, while it works it's not starting each test from a clean widget tree state(that's why I included global keys for the widgets to ensure their state is lost). I also experimented with doing `runApp(Container())` in `setUp()` but I think it didn't work as nothing was waiting for …
> [webview_flutter] Add initial e2e tests

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/lib/src/document_change.dart
- packages/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore/lib/src/document_snapshot.dart
- packages/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/lib/src/query_snapshot.dart
- packages/cloud_firestore/lib/src/transaction.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
Add SnapshotMetadata to DocumentSnapshot. SnapshotMetadata has two boolean field hasPendingWrites and isFromCache. This PR enables to know snapshot is from server or local cache.
> [cloud_firestore] Add metadata field to DocumentSnapshot

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/JavaScriptChannel.java
- packages/webview_flutter/pubspec.yaml
The Android's webview's JavascriptInterface doesn't promise to invoke
the interface's Java method on the main thread, since postMessage is
sending a message over the platform channel we need to make sure it's
doing so from the platform thread.
- [] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]). …
> Make sure to post javascript channel messages from the platform thread.

- AUTHORS
- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/lib/observer.dart
- packages/firebase_analytics/pubspec.yaml
- packages/firebase_analytics/test/observer_test.dart
Currently only standard push and pops were automatically logged to Firebase. However, this resulted in missing screen_view events for apps with more complex navigation.
/
> [firebase_analytics] Added Navigator.pushReplacement screen tracking

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/build.gradle
- packages/cloud_firestore/example/android/app/build.gradle
- packages/cloud_firestore/pubspec.yaml
Update `firebase-firestore` dependency to `18.2.0`. Previously, using `setData` method on `DocumentReference` would result in a crash.
Resolves https://github.com/flutter/flutter/issues/28082
> [cloud_firestore] Update firebase-firestore to 18.2.0

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/example/lib/main.dart
- packages/google_sign_in/pubspec.yaml
*I was using the example code when I bumped into the issue. Since `null` is being sent at some point to the `Text` widget, it is creating an error in the app. *
*[google_sign_in](https://github.com/flutter/flutter/issues/22028)*
> [google_sign_in] Handle `null` check in example app

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/android/build.gradle
- packages/firebase_crashlytics/pubspec.yaml
Rely on firebase_core to set up Firebase Analytics dependency instead of setting it ourselves. This stops firebase_crashlytics from conflicting with other Firebase plugins on Android. 
Fixes flutter/flutter#30037
[CLA]: …
> [firebase_crashlytics] Rely on firebase_core to set up Firebase Analytics dependency

- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/lib/src/controller.dart
- packages/google_maps_flutter/lib/src/google_map.dart
Deliver the tap event in the map with the LatLng object where it happened. 
Enables something like this:
GoogleMap(
onMapTapped: (LatLng location) {
showDialog(context: context, builder: (BuildContext context) {
return AlertDialog(
title: new Text("Map tapped!"),
content: new Text("You tapped in " + location.latitude.toString() + ", " + location.longitude.toString()),
actions: <Widget>[
// usually buttons at the bottom of the dialog
new FlatButton(
child: new Text("Close"),
onPressed: () {
Navigator.of(context).pop();
},
),
],
);
});
},
)
> [google_maps_flutter]add support for map tapping

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/build.gradle
- packages/firebase_core/example/android/settings.gradle
- packages/firebase_core/pubspec.yaml
[Firebase now supports Gradle BoM](https://firebase.google.com/docs/android/setup) (Bill of Materials). This allows a single Firebase version to determine the appropriate version number of specific Firebase dependencies.
Since all other FlutterFire plugins depend on `firebase_core` this will be the first of the FlutterFire plugins to be updated to BoM then all others will follow once this change is merged.
NOTE: Users of FlutterFire will have to add `enableFeaturePreview('IMPROVED_POM_SUPPORT')` to their Android app's settings.gradle file till Flutter moves over to Gradle 5+
> [firebase_core] Use Gradle BoM with firebase_core

- packages/connectivity/CHANGELOG.md
- packages/connectivity/example/pubspec.yaml
- packages/connectivity/example/test_driver/connectivity.dart
- packages/connectivity/example/test_driver/connectivity_test.dart
- packages/connectivity/pubspec.yaml
Add test driver to the plugin.
> [connectivity]Added integration test.

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/build.gradle
- packages/cloud_firestore/example/android/settings.gradle
- packages/cloud_firestore/pubspec.yaml
- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/build.gradle
- packages/firebase_core/example/android/settings.gradle
- packages/firebase_core/pubspec.yaml
fixes: https://github.com/flutter/flutter/issues/30606
Due to BoM handling being different on Gradle 4 and 5, this removes `firebase-bom` usage and these dependencies will be applied manually going forward till a more stable BoM solution is found.
> Remove BoM to avoid Gradle issues

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/build.gradle
- packages/firebase_core/pubspec.yaml
This change brings firebase_core back to the firebase-core Android dependency that it had at 0.3.1+1.
Fixes https://github.com/flutter/flutter/issues/30634
Fixes https://github.com/flutter/flutter/issues/30631
Fixes https://github.com/flutter/flutter/issues/30629
Fixes https://github.com/flutter/flutter/issues/30573
> [firebase_core] fix BoM-related build incompatibility regression

- packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
This mirrors an internal change where Firebase team is deprecating instance token calls. This is not a breaking change.
> Migrate firebase messaging plugin away from token

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/pubspec.yaml
Enabling iOS a11y by default on Google Map. Google Map SDK disables the a11y by default (https://developers.google.com/maps/documentation/ios-sdk/map#accessibility). We will enable it for our plugins.
[CLA]: …
> [Google_map]Enable iOS a11y by default.

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
- packages/image_picker/pubspec.yaml
Currently, `getPathFromLocalUri` returns a string purely consisting of integers when the user selects a photo from Google Photos through the sidebar entry. This fixes the issue by returning `null`, which causes `getPathFromUri` to fallback to `getPathFromRemoteUri` (which returns the correct path, see  https://github.com/flutter/flutter/issues/29667#issuecomment-480462248).
* Fixes https://github.com/flutter/flutter/issues/29667 …
> [image_picker] Fix invalid path being returned from Google Photos

- packages/image_picker/CHANGELOG.md
- packages/image_picker/ios/image_picker.podspec
- packages/image_picker/pubspec.yaml
Flutter requires minimum iOS to be 8.0 so the plugin should be the same.
> [Image_picker] ios minimum deployment target to 8.0.

- packages/video_player/CHANGELOG.md
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
- packages/video_player/pubspec.yaml
Fixes the `implicit-retain-self` warnings that otherwise prints whenever you build this project:
```
video_player-0.10.0+4/ios/Classes/VideoPlayerPlugin.m:89:55: warning: block implicitly retains 'self'; explicitly mention 'self' to
indicate this is intended behavior [-Wimplicit-retain-self]
if (_isLooping) {
^
self->
video_player-0.10.0+4/ios/Classes/VideoPlayerPlugin.m:93:57: warning: block implicitly retains 'self'; explicitly mention 'self' to
indicate this is intended behavior [-Wimplicit-retain-self]
if (_eventSink) {
^
self->
video_player-0.10.0+4/ios/Classes/VideoPlayerPlugin.m:94:55: warning: block implicitly retains 'self'; explicitly mention 'self' to
indicate this is intended behavior [-Wimplicit-retain-self]
_eventSink(@{@"event" : @"completed"});
^
self-> …
```
> [video_player] Explicitly indicate that self should be retained

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/ios/Classes/GoogleMapMarkerController.m
- packages/google_maps_flutter/pubspec.yaml
- Android Bitmaps scale images to account for dpi.
- iOS UIImages do not, we need to account for that.
> BitmapDescriptor#fromBytes should be consistent across platforms

- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/lib/observer.dart
- packages/firebase_analytics/pubspec.yaml
Some code examples in firebase_analytics contain errors, e.g. brackets in the wrong place. This PR makes examples launchable.
> [firebase_analytics] Fixes errors in firebase_analytics docs

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/pubspec.yaml
`firebase_crashlytics` should  keep debug traces readable in debug mode.
- [] I updated CHANGELOG.md to add a description of the change.
> [firebase_crashlytics] Do not break debug log formatting.

- packages/firebase_admob/CHANGELOG.md
- packages/firebase_admob/README.md
- packages/firebase_admob/example/ios/Runner/Info.plist
- packages/firebase_admob/pubspec.yaml
Update documentation to add app id in Info.plist. It is required starting in version 7.42.0. See  https://firebase.google.com/docs/admob/ios/quick-start#update_your_infoplist.
Does your PR require plugin user to manually update their apps to accommodate your change? …
> [firebase_admob] Update documentation to add iOS Admob ID & add iOS Admob ID in example project

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/ios/firebase_auth.podspec
- packages/firebase_auth/pubspec.yaml
See discussion in https://github.com/flutter/plugins/commit/8bdd77661c1cfc899eaad9cd14b9222611f49a39
Changes to firebase_auth require a "~> 5.4" version of FirebaseAuth CocoaPod to ensure that `FIRAuthErrorUserInfoNameKey` is available.
> Update firebase_auth CocoaPod dependency

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/ios/firebase_auth.podspec
- packages/firebase_auth/pubspec.yaml
This is necessary to pick up the FirebaseAuth 5.4 CocoaPod.
This will actually achieve what I was trying to achieve in https://github.com/flutter/plugins/pull/1503
See discussion in 8bdd776
> [firebase_auth] Increase iOS Firebase/Auth CocoaPods dependency to 5.19

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
- packages/image_picker/pubspec.yaml
On Android, the MainActivity can be killed and restarted after launching the image picker for various of reasons. this can be tested by selecting `don't keep activities alive' option in the developer options in phone's setting app.
This PR first prevents the crash by not trying to access the already nulled pendingResult.
I will also finalize a solution to retrieve the lost data due to this issue and provide a PR for that later.
Directly fixing the crashing in flutter/flutter#17950
Possibly: flutter/flutter#23788, flutter/flutter#21102,
flutter/flutter#18700
Does your PR require plugin users to manually update their …
> [Image_picker] Android: fix a crash when the MainActivity is destroyed after selecting the image/video. 

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/example/lib/main.dart
- packages/webview_flutter/pubspec.yaml
WebView example should be StatefulWidget ,or the completer may produce null/waitingState snapshot to the future builder, which will make the forward/ backward action buttons disable.
not found
> [webview_flutter]bugfix:webview example should be statefulWidget

- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/example/pubspec.yaml
- packages/firebase_analytics/example/test_driver/firebase_analytics.dart
- packages/firebase_analytics/example/test_driver/firebase_analytics_test.dart
- packages/firebase_analytics/pubspec.yaml
Starting point for integration testing. I don't know how to check the results yet, so just making sure that exceptions aren't thrown.
> [firebase_analytics] Initial integration test

- packages/connectivity/CHANGELOG.md
- packages/connectivity/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java
- packages/connectivity/pubspec.yaml
When running Android Lint on a project using the connectivity plugin, Lint gives the following error:
`The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing registrar.context() to registrar.context().getApplicationContext()`
This applies the suggested change.
https://github.com/flutter/flutter/issues/28928
> [connectivity] Fixes lint error by using getApplicationContext()

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/pubspec.yaml
The previous example was printing `Instance of 'JavascriptMessage'`. To print the actual message, we need to access it through the `message` property.
> [webview_flutter] Fixed documentation for usage example of JavaScript message

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
- packages/camera/example/lib/main.dart
- packages/camera/pubspec.yaml
Remove activity lifecycle calls to close/open the camera. This will require the user to handle when to dispose/initialize a new `CameraController`. Right now there seems to be a crash when the same activity is not found when `onResumed` is called. 
https://github.com/flutter/flutter/issues/19595
https://github.com/flutter/plugins/pull/1191 …
> [camera] Remove activity lifecycle

- packages/firebase_performance/CHANGELOG.md
- packages/firebase_performance/README.md
- packages/firebase_performance/android/src/main/java/io/flutter/plugins/firebaseperformance/FirebasePerformancePlugin.java
- packages/firebase_performance/example/lib/main.dart
- packages/firebase_performance/example/test_driver/firebase_performance.dart
- packages/firebase_performance/ios/Classes/FirebasePerformancePlugin.m
- packages/firebase_performance/lib/src/trace.dart
- packages/firebase_performance/pubspec.yaml
- packages/firebase_performance/test/firebase_performance_test.dart
Add `incrementMetric` and mark `incrementCounter` as deprecated.
`incrementCounter` is deprecated in the Java SDK and it's been replaced with `incrementMetric`. Let's make `firebase_performance` match that.
See: https://firebase.google.com/docs/reference/android/com/google/firebase/perf/metrics/Trace.html#incrementCounter(java.lang.String,%20long)
Fixes flutter/flutter#29775
> [firebase_performance] Deprecate incrementCounter in favor of incrementMetric

- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmBroadcastReceiver.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/RebootBroadcastReceiver.java
I started reading through android_alarm_manager to determine how it would work with the new Android plugin API but I had a difficult time tracing the execution paths and interpreting the intent of the code. So I decided to go through and document everything I could to make better sense of it. I'd like to commit those comments and minor refactorings so that hopefully it's a little more clear for everyone.
Added comments and refactored android_alarm_manager plugin for clarity.
- Added many comments, both on public members and within private source code.
- Moved all static behavior above instance behavior in `AlarmService` to clearly demonstrate how much behavior has been defined statically (which I think we very much want to move to instance behavior).
- Renamed some methods to shift them …
> [android_alarm_manager] Added comments and refactored android_alarm_manager plugin for clarity.

- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/README.md
- packages/firebase_messaging/pubspec.yaml
Remove obsolete instruction which asks devs to remove `use_frameworks!` from their `ios/podfile`
https://github.com/flutter/flutter/issues/31466
https://github.com/flutter/flutter/issues/25172
https://github.com/flutter/flutter/issues/9694
> [firebase_messaging] remove obsolete docs instruction

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/example/test_driver/cloud_firestore.dart
- packages/cloud_firestore/example/test_driver/cloud_firestore_test.dart
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/lib/src/field_value.dart
- packages/cloud_firestore/lib/src/firestore_message_codec.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
This PR adds support for incrementing using `FieldValue`.
Example usage:
```dart
final DocumentReference ref = firestore.collection('mycollection').document();
await ref.setData(<String, dynamic>{
'value': 1,
'created_at': FieldValue.serverTimestamp(),
});
await ref.updateData(<String, dynamic>{
'value': FieldValue.increment(1),
});
DocumentSnapshot snapshot = await ref.get();
expect(snapshot.data['value'], 2);
```
I thought about naming the API `incrementDouble/incrementInteger` but leaning towards overloading `increment`. I'd love to get feedback on this.
Fixes flutter/flutter#31034
> [cloud_firestore] Support for FieldValue.increment

- packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart
- packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
Previously this was consuming the purchases in the background and
ignoring the output.
Also some minor code cleanup.
> [in_app_purchase] Add auto-consume errors to PurchaseDetails

- packages/image_picker/CHANGELOG.md
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
- packages/image_picker/pubspec.yaml
Returning `.description` on a `NSURL` gave back an url that starts with `file:///`, when passing this url to the `File` object it constructed a path like `/file:///foo/bar/baz.ext`.
This fixes this logic to use `.path` instead, which returns the path to the file.
Here is some more background to how I found this: https://github.com/firebase/firebase-ios-sdk/pull/2458/files#r276273826 …
> [image_picker] Fix path of returned File objects when picking videos

- AUTHORS
- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
- packages/image_picker/pubspec.yaml
Using correct temp file suffix on android.
Thanks @ozeksi on https://github.com/flutter/plugins/pull/1150 for the original contribution!
This could be the fix for https://github.com/flutter/flutter/issues/17165
[CLA]: …
> [image_picker] correct suffix on android.

- packages/firebase_ml_vision/CHANGELOG.md
- packages/firebase_ml_vision/pubspec.yaml
- packages/firebase_ml_vision/test/firebase_ml_vision_test.dart
- packages/share/CHANGELOG.md
- packages/share/pubspec.yaml
- packages/share/test/share_test.dart
Fixes analyzer warnings for two plugins in flutter/plugins due to introduction of const Rect constructor.
* firebase_ml_vision
* share
I'm not using the const constructor yet since the presence of const Rect isn't assured.
> [firebase_ml_vision] [share] Fix analyzer warnings from const Rect constructor.

- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/example/test_driver/cloud_firestore.dart
Slight mistake that occured in https://github.com/flutter/plugins/pull/1491.
As version `0.10.0` has not even been rolled out to Pub yet, I do not think that I need to bump the version.
Still, I am wondering why `0.10.0` is still not on Pub as it has been 3 days.
> [cloud_firestore] Fix wrong FieldValue

- packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
Previously `GooglePlayConnection#queryPastPurchases` was calling through
to `BillingClientWrapper#queryPastPurchaseHistory`, which includes
purchases that are no longer owned. Switch that out for
`BillingClientWrapper#queryPurchases` instead since that's a better fit
for the unified API.
Also update the BillingClientWrapper docs to try and make this
distinction more clear.
[Flutter …
> [in_app_purchase] Only fetch owned purchases

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/ios/Classes/JsonConversions.m
- packages/google_maps_flutter/pubspec.yaml
Support Color's alpha channel when converting to UIColor on iOS. This allows polylines and other overlays to be added in the future (e.g. circles and polygons) to be translucent, to match the behavior on Android.
Tested manually using a translucent polyline in the iOS simulator.
> [google_maps_flutter] Support Color's alpha channel when converting to UIColor on iOS

- packages/video_player/CHANGELOG.md
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
- packages/video_player/pubspec.yaml
1. When a player has not initialized it's presentationSize is
returned as CGSizeZero.
2. The enum type must be AVPlayerItemStatusFailed not AVPlayerStatusFailed
3. Fix a few other IDE warnings.
Fixes https://github.com/flutter/flutter/issues/19197
> [video_player] Fix player initialization and other warnings

- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/example/test_driver/firebase_storage.dart
- packages/firebase_storage/ios/Classes/FirebaseStoragePlugin.m
- packages/firebase_storage/pubspec.yaml
- `putFile` should use `putFile` iOS SDK method correctly
- `putFile` should auto-detect Content-Type automatically by file extension if not specified
I tested at this sample on **iOS**:
https://github.com/flutter/plugins/blob/master/packages/firebase_storage/example/lib/main.dart.
This uses `putFile` here:
https://github.com/flutter/plugins/blob/04d6f52e3b09193462a18a38a7249da92b901ba5/packages/firebase_storage/example/lib/main.dart#L66
Uploaded file:
https://firebasestorage.googleapis.com/v0/b/flutter-firebase-plugins.appspot.com/o/text%2Ffoob3d87700-3260-11e9-d838-d7a1f7b2a3d4.txt
`contentType` is `application/octet-stream`, but this is unintended value because `putFile` should auto-detect `contentType` as written this document.
> The putFile: method automatically infers the content …
> [firebase_storage] Fix putFile method's Content-Type auto-detection for iOS

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/pubspec.yaml
- packages/firebase_crashlytics/test/firebase_crashlytics_test.dart
Update our handling of the struct to work on both flutter stable and
master. Tested on both master and stable. The plugin itself works on
both, but our unit tests now only run on master.
flutter/flutter#31962
[CLA]: …
> [firebase_crashlytics] Migrate FlutterErrorDetails

- CODEOWNERS
- packages/path_provider/CHANGELOG.md
- packages/path_provider/example/pubspec.yaml
- packages/path_provider/example/test_driver/path_provider.dart
- packages/path_provider/example/test_driver/path_provider_test.dart
- packages/path_provider/pubspec.yaml
Fixes flutter/flutter#32042
This is not a breaking change but I'm updating the version to 1.0 since the plugin is mature enough for that.
> [path_provider] Release as 1.0 and add integration tests

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/android/build.gradle
- packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
- packages/firebase_auth/example/lib/signin_page.dart
- packages/firebase_auth/lib/src/auth_provider/phone_auth_provider.dart
- packages/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/pubspec.yaml
This is a fix to issue https://github.com/flutter/flutter/issues/22304.
The plugin demands auth credential while logging in with facebook, google, emailPassword. Which gives developer the option to create new account with it or link it to the existing user. But the phone auth used to behave differently, it directly used to sign in and create new user which was preventing developers to link it to the existing user. Thus this PR removes that behaviour and gives ability to extract phone auth cred and use it as required.
I have used Gson to parse and send the PhoneAuthCredential to the dart side. Not sure if its a good idea, suggestions are welcomed.
Note: This automatic signing in for phone auth was not enabled on the IOS side thus no changes have been made to the IOS code, let me know if I …
> [firebase_auth] Removed automatic signing in behaviour when signing in with phone auth.

- packages/firebase_dynamic_links/CHANGELOG.md
- packages/firebase_dynamic_links/README.md
- packages/firebase_dynamic_links/android/build.gradle
- packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java
- packages/firebase_dynamic_links/example/lib/main.dart
- packages/firebase_dynamic_links/ios/Classes/FirebaseDynamicLinksPlugin.m
- packages/firebase_dynamic_links/lib/src/dynamic_link_parameters.dart
- packages/firebase_dynamic_links/pubspec.yaml
- packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart
> Updates to dynamic links plugin to remove deprecated API usage and update Android dependencies.

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/build.gradle
- packages/firebase_core/pubspec.yaml
Since all the other plugins have a dependency on firebase_core, using 0.4.0 to get them to agree on newer versions of Android dependencies.
> Update firebase_core dependency

- packages/cloud_functions/CHANGELOG.md
- packages/cloud_functions/example/test/cloud_functions.dart
- packages/cloud_functions/pubspec.yaml
When I run the cloud_functions timeout integration test locally on Android, it doesn't timeout even though the timeout value is very short. I guess this is just how the native SDK works.
> Remove flaky timeout test

- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java
- packages/firebase_messaging/pubspec.yaml
Fixes an error in the logs when calling `configure` if the user's token could not be read. Instead, a warning message is logged.
> [firebase_messaging] more graceful handling of failed token read on startup

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/ios/firebase_auth.podspec
- packages/firebase_auth/pubspec.yaml
Most of our Flutterfire plugins don't specify a particular version, but right now we're using the optimistic operator with `Firebase/Auth`, '~> 5.19'. This change gets us onto Firebase 6.x, which should increase the chance of find compatible pods for other plugins that are using 6.x stuff in the future.
I think I need to get Cirrus to run `pod repo update` and pick up 6.0 before this change will pass tests. The CocoaPods just went live a few hours ago.
> [firebase_auth] Update to latest CocoaPod

- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/ios/Classes/FirebaseAnalyticsPlugin.m
- packages/firebase_analytics/ios/firebase_analytics.podspec
- packages/firebase_analytics/pubspec.yaml
Fixes flutter/flutter#32252.
Resolves compile errors due to removal of the `FIRAnalyticsConfiguration` class in CocoaPod version 6.0.
> Fix break in firebase_analytics CocoaPod

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/example/lib/consumable_store.dart
- packages/in_app_purchase/example/lib/main.dart
- packages/in_app_purchase/example/pubspec.yaml
- packages/in_app_purchase/pubspec.yaml
Also changes how the example app handles state to avoid bugs with
consumables not getting updated based on purchasing. Previously the app
was relying on FutureBuilders, but these didn't handle state updates
over time and across Widgets correctly. …
> [in_app_purchase] Add consumable demo

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/lib/src/firebase_user.dart
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
Detail to this PR is mentioned at https://github.com/flutter/flutter/issues/32317
> Migrated linkWithCredential function to FirebaseUser object instead of FirebaseAuth

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java
- packages/image_picker/pubspec.yaml
The MediaScanConnection.scanFile callback is invoked on a background thread.
However, MethodChannel results must be provided on the platform thread.
Fixes https://github.com/flutter/flutter/issues/32315
> Return image picker method call results on the platform thread

- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
- packages/firebase_messaging/pubspec.yaml
fixes https://github.com/flutter/flutter/issues/25650
fixes https://github.com/flutter/flutter/issues/29714
To use this right now do:
```yaml
firebase_messaging: #^4.0.0+1
git:
url: git://github.com/jaumard/plugins
ref: feature/iosFirebaseMessagingDataMessages
path: packages/firebase_messaging
```
> [Firebase messaging] iOS direct data messages

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart
- packages/in_app_purchase/pubspec.yaml
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
Previously the code was failing to propagate errors from BillingClient
if there were no actual purchases to attach them to.
Also updates the error code. This situation can arise in more situations
than just restoring purchases.
flutter/flutter#31417 …
> [in_app_purchase] Fix issue with empty purchase updates

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/InAppPurchasePlugin.java
- packages/in_app_purchase/example/android/app/build.gradle
- packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/InAppPurchasePluginTest.java
- packages/in_app_purchase/pubspec.yaml
Theoretically this API should only be called once, but there's an open
issue that suggests that in some cases this is being triggered multiple
times. Check for multiple calls and bail instead of sending multiple
replies.
flutter/flutter#31417
Fixes flutter/flutter#32462 …
> [in_app_purchase] Guard against dupe onBillingSetupFinished calls

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/lib/src/in_app_purchase/app_store_connection.dart
- packages/in_app_purchase/lib/src/in_app_purchase/google_play_connection.dart
- packages/in_app_purchase/lib/src/in_app_purchase/in_app_purchase_connection.dart
- packages/in_app_purchase/pubspec.yaml
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
Previously the buy methods were just returning `void`, so the immediate
response of `BillingClient#launchBillingFlow` was unaccessible. Change
it to return a `Future<bool>` and return whether or not the launch flow
succeeded in google_play_connection. Always return true in
app_store_connection since there's no equivalent status there.
flutter/flutter#31417
Fixes flutter/flutter#32518
flutter/flutter/issues/32512 …
> [in_app_purchase] Propagate launchBillingFlow failures

- packages/video_player/CHANGELOG.md
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
- packages/video_player/pubspec.yaml
During network playback (HTTP), the duration may take a little longer to determine. 
Until it is determined, the player must not be considered "initialized", else div/0 will occur during the progress indicator display. …
> [video_player] Prevent Div/0 during network playback initialization.

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseAppRegistrar.java
- packages/firebase_core/ios/Classes/FirebaseCorePlugin.m
- packages/firebase_core/pubspec.yaml
Update user agent name of `firebase_core` plugin. Setting it to `flutter-fire-core` to be consistent with other libraries.
Eg: in the [Firebase Android SDK](https://github.com/firebase/firebase-android-sdk/blob/3097f24b2f251e32275a1a1efbcfadc68c678875/firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java#L153) where `fire-core` is used.
> Adjust user agent name

- script/check_hard_coded_version.sh
Not sure how I didn't catch this in my earlier testing, but this prevents failures when a plugin doesn't have a hard coded version.
> Fix to check_hard_coded_version script

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/JavaScriptChannel.java
- packages/webview_flutter/example/test_driver/webview.dart
- packages/webview_flutter/pubspec.yaml
The Android JavaScriptChannel wasn't checking correctly if messages are
received on the main thread and took the branch that assumes we are on
the main thread.
https://github.com/flutter/engine/pull/8830 causes this behavior to fail
(which is good). So now we can also add an e2e test that fails with the
buggy behavior.
[issue …
> [webview_flutter] Fix wrong main thread checking condition.

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
- packages/camera/pubspec.yaml
Enable camera plugin to compile with earlier android sdks with custom AndroidManifest settings. 
Catching `CameraAccessException`s in the `onMethodCall` prevented compilation on <21. This separates handling them into another method. 
Original PR: https://github.com/flutter/plugins/pull/1482
Fixes https://github.com/flutter/flutter/issues/30854 …
> [camera] Enable camera plugin to compile with earlier android apis with custom AndroidManifest settings

- packages/video_player/CHANGELOG.md
- packages/video_player/ios/Classes/VideoPlayerPlugin.m
- packages/video_player/pubspec.yaml
`seekToTime:` has been deprecated, and `seekToTime:completionHandler:` was added in iOS 5.0 so it should be supported on all platforms.
- [n/a] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]). …
> [video_player] avoid deprecated seekToTime API

- packages/webview_flutter/lib/platform_interface.dart
- packages/webview_flutter/lib/src/webview_android.dart
- packages/webview_flutter/lib/src/webview_cupertino.dart
- packages/webview_flutter/lib/src/webview_ios.dart
- packages/webview_flutter/lib/src/webview_method_channel.dart
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/test/webview_flutter_test.dart
The goal of this PR is to allow separate packages to extend the plugin to work on more platforms.
This is done by abstracting all the platform specific logic behind the `WebViewPlatform` and `WebViewBuilder` interfaces(in `platform_interface.dart`), and adding a static `WebView.platformBuilder` field that can be set to change the the platform specific code.
For example, in order to extend the webview to support Fuchsia, a `fuchsia_webview_flutter` plugin can implement  `WebViewBuilder` and `WebViewPlatform`(reference implementations available in `webview_android.dart` and `webview_cupertino.dart`).
When running on Fuchsia the plugin(or the app developer if the plugin doesn't have the right hooks) can then set itself as the implementation for the webview by running:
```dart …
```
> Allow changing the webview's platform specific implementation

- packages/image_picker/CHANGELOG.md
- packages/image_picker/example/ios/image_picker_exampleTests/MetaDataUtilTests.m
- packages/image_picker/example/ios/image_picker_exampleTests/PhotoAssetUtilTests.m
- packages/image_picker/example/lib/main.dart
- packages/image_picker/ios/Classes/ImagePickerMetaDataUtil.h
- packages/image_picker/ios/Classes/ImagePickerMetaDataUtil.m
- packages/image_picker/ios/Classes/ImagePickerPhotoAssetUtil.h
- packages/image_picker/ios/Classes/ImagePickerPhotoAssetUtil.m
- packages/image_picker/pubspec.yaml
Follow up https://github.com/flutter/plugins/pull/1586. Copying over all the metadata, including GPS, orientation and more.
Note that because orientation is copied, we have to revert the orientation that iOS has done on the picked image to make the image show up in a correct way on the phone.
flutter/flutter#31751 …
> [image_picker] ios: copy all meta data from the original image.

- packages/image_picker/CHANGELOG.md
- packages/image_picker/example/ios/Runner.xcodeproj/project.pbxproj
- packages/image_picker/example/ios/image_picker_exampleTests/MetaDataUtilTests.m
- packages/image_picker/example/ios/image_picker_exampleTests/PhotoAssetUtilTests.m
- packages/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.h
- packages/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.m
- packages/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.h
- packages/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.m
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
- packages/image_picker/pubspec.yaml
Certain classes/types in the image picker iOS implementation are not following the official naming convention described here https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingBasics.html#//apple_ref/doc/uid/20001281-1002226-BBCJECED. 
(2 or 3 letters prefix before a class/type name to avoid conflicts between other frameworks)
This PR added FLT to all the Classes, Enums, Typedefs, and Constants in this plugin.
N/A …
> [image_picker] Rename iOS class according to the official Objective-C naming convention.

- packages/local_auth/CHANGELOG.md
- packages/local_auth/android/build.gradle
- packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java
- packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java
- packages/local_auth/example/android/app/src/main/java/io/flutter/plugins/localauthexample/MainActivity.java
- packages/local_auth/pubspec.yaml
Migrates the LocalAuth plugin on Android to Biometric API for showing the fingerprint dialog. This will allow us to implement more biometric authentication schemes (and others such as PIN) in the future.
https://github.com/flutter/flutter/issues/18690
This is a breaking change because it requires Flutter applications on Android to extend a FragmentActivity rather than a regular Activity. The fix is to use `FlutterFragmentActivity` instead of `FlutterActivity`. The y version has been bumped due to this.
> Change LocalAuth to use Biometric API

- packages/firebase_ml_vision/CHANGELOG.md
- packages/firebase_ml_vision/example/lib/main.dart
- packages/firebase_ml_vision/pubspec.yaml
This updates the sample to adapt to the ImageStream listener API changes
in flutter/flutter#32936
This is similar to the change we did to Google Maps in https://github.com/flutter/plugins/pull/1640, unfortunately in the firebase_ml_vision case where we commented out the sample that used the ImageStream listener API. Unfortunately in the firebase_ml_vision case, there's no point in the sample without the ImageStream listener(you need it to pick an image), so I'm just updating the sample to the new API knowing that it won't compile on stable until the breaking change makes it there.
https://github.com/flutter/flutter/issues/33440 discuss the more general issue of how breaking framework changes are affecting plugins.
Before you create this PR confirm that it meets all requirements listed …
> [firebase_ml_vision] Update sample to use new ImageStreamListener API

- packages/video_player/CHANGELOG.md
- packages/video_player/example/lib/main.dart
- packages/video_player/pubspec.yaml
Just a simple fix to make the example work again. The tab count value was 2 for 3 children.
I also added some text widget to know what the type of the video and where it come from. (source and extension infos)
[CLA]: …
> [video_player] Fixed example and add texts

- packages/cloud_firestore/test/cloud_firestore_test.dart
- packages/connectivity/test/connectivity_test.dart
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/pubspec.yaml
- packages/firebase_auth/test/firebase_auth_test.dart
- packages/firebase_database/CHANGELOG.md
- packages/firebase_database/pubspec.yaml
- packages/firebase_database/test/firebase_database_test.dart
- packages/sensors/CHANGELOG.md
- packages/sensors/pubspec.yaml
- packages/sensors/test/sensors_test.dart
- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/pubspec.yaml
- packages/webview_flutter/test/webview_flutter_test.dart
https://github.com/flutter/flutter/pull/30406 deprecated the usage of static `BinaryMessages` methods. As we cannot use the new `defaultBinaryMessages` mechanism before it makes it to stable, for now, we suppress the warnings.
* https://github.com/flutter/flutter/issues/33446 - tracking updating the code when it makes it to stable.
* https://github.com/flutter/flutter/issues/33440 - this should have been caught on presubmit/post-submit.
> suppress deprecation warning for BinaryMessages

- packages/webview_flutter/lib/platform_interface.dart
- packages/webview_flutter/lib/src/webview_android.dart
- packages/webview_flutter/lib/src/webview_cupertino.dart
- packages/webview_flutter/lib/src/webview_method_channel.dart
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/test/webview_flutter_test.dart
As a temporary step we passed these objects as maps that were sent across the method channel. This PR replaces the maps with proper Dart objects.
> [webview_flutter] platform_interface: Use Dart objects for creationParams and webSettings.

- packages/firebase_dynamic_links/CHANGELOG.md
- packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java
- packages/firebase_dynamic_links/example/lib/main.dart
- packages/firebase_dynamic_links/pubspec.yaml
On Android there is a different behavior than in iOS which I think is the expected one.
1. When clicking on a link while the app is running and then trying to get the link via a call to "retrieveDynamicLink" the result is null.
2. Calling to "retrieveDynamicLink" doesn't clean the old value which makes it impossible for the application to know if/when the user has clicked a link or it is a  result of an old click.
To solve the first problem I added a check for the existence of a dynamic link on every new intent instead of the current behavior that checks only on the fluter activity intent.
In addition (for the second problem) I added a cleanup for the old link  every time it was retrieved
successfully by the user.
This PR matches the behavior on iOS.
The `retrieveDynamicLinks` will now …
> [firebase_dynamic_links] support clicking on link while app is running.

- packages/shared_preferences/CHANGELOG.md
- packages/shared_preferences/android/build.gradle
- packages/shared_preferences/example/android/app/gradle/wrapper/gradle-wrapper.properties
- packages/shared_preferences/example/android/build.gradle
- packages/shared_preferences/example/android/gradle/wrapper/gradle-wrapper.properties
This is a partial landing of #1595, updating the Gradle to match Android Studio 3.4.
If there are no issues, we'll go ahead and update all the other plugins.
> [shared_preferences] Updated Gradle tooling to match Android Studio 3.4.

- packages/shared_preferences/CHANGELOG.md
- packages/shared_preferences/pubspec.yaml
There was a merge conflict in #1653 that was missed by the tests/bots. This fixes the version number in pubspec.yaml so that we can publish the latest.
> Fixes merge conflict in shared_preferences release of 0.5.2+2

- packages/webview_flutter/lib/platform_interface.dart
- packages/webview_flutter/lib/src/webview_android.dart
- packages/webview_flutter/lib/src/webview_cupertino.dart
- packages/webview_flutter/lib/src/webview_method_channel.dart
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/test/webview_flutter_test.dart
This is a followup for #1618 and #1624, and moves all of the `plugins.flutter.io/webview` method channel calls behind the platform channel, which allows a third party package to provide a new platform implementation for all of these methods.
See the description for #1618 for more details.
The last remaining part is the `plugins.flutter.io/cookie_manager` channel which I'm leaving for a followup PR.
> [webview_flutter] Move the method channel behind the platform interface

- packages/local_auth/CHANGELOG.md
- packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java
- packages/local_auth/pubspec.yaml
Two bug fixes:
- The thread passed to FP needs to be UI thread. Callbacks are executed on that thread and we also don't want any synchronization issues.
- We should not be calling .error() then .success() on the same result object. This does not cause any exceptions but it is bad form.
> [local_auth] The thread for executor needs to be UI thread.

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/lib/platform_interface.dart
- packages/webview_flutter/lib/src/webview_android.dart
- packages/webview_flutter/lib/src/webview_cupertino.dart
- packages/webview_flutter/lib/src/webview_method_channel.dart
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/pubspec.yaml
- packages/webview_flutter/test/webview_flutter_test.dart
This is a followup for #1618, #1624, and #1645, and moves the `plugins.flutter.io/cookie_manager` method channel behind the platform interface which allows a third party package to provide a new platform implementation the cooke manager.
See the description for #1618 for more details.
Following this PR all platform specific code can be replaced by an external package.
Before this PR we had a `WebViewBuilder` class(which had the build method) and a `WebViewPlatform` class (which abstracted what's currently done on the webview method channel).
A `WebViewPlatform` instance existed per `WebView` instance, and `WebViewBuilder` needs to exist once.
As `clearCookies` is not associated with a `WebView` instance I added it to what was previously named `WebViewBuilder` and renamed both classes:
* …
> Move clearCookies behind the platform abstraction

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/FlutterFirebaseAppRegistrar.java
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/pubspec.yaml
In coming versions of the Flutter engine calls to the Dart side from the Java side must be done on the UI thread. The Firestore plugin implements transactions by making calls to the Dart side from the Java side. This change ensures that those calls are made on the UI thread.
Resolves: https://github.com/flutter/flutter/issues/32657
> [cloud_firestore] Invoke on ui thread only

- .cirrus.yml
Fixes test failures on the plugins iOS builder
```
Warning: CocoaPods minimum required version 1.6.0 or greater not installed. Skipping pod install.
CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To upgrade:
brew upgrade cocoapods
pod setup
```
> Ensure that CocoaPods on Cirrus is always the latest version.

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/build.gradle
- packages/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseAppRegistrar.java
- packages/firebase_core/ios/Classes/.gitignore
- packages/firebase_core/ios/Classes/FirebaseCorePlugin.m
- packages/firebase_core/ios/firebase_core.podspec
- packages/firebase_core/pubspec.yaml
* Automate the retrieval of the plugin's version for user agent reporting to Firebase.
> [firebase_core] Automate version retrieval

- packages/firebase_core/CHANGELOG.md
- packages/firebase_core/android/build.gradle
- packages/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseAppRegistrar.java
- packages/firebase_core/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_core/ios/Classes/.gitignore
- packages/firebase_core/ios/Classes/FirebaseCorePlugin.m
- packages/firebase_core/ios/firebase_core.podspec
- packages/firebase_core/pubspec.yaml
This PR reverts firebase_core to the 0.4.0+3 release due to a build issue with the 0.4.0+4 release that was not caught by our CI.
The automatic version checking feature will be re-landed once the build issue is resolved.
Fixes flutter/flutter#34410 flutter/flutter#34385 flutter/flutter#34393
See also https://github.com/flutter/plugins/pull/1736 which has some suggestions for additional improvements to automatic version checking.
> [firebase_core] roll back to 0.4.0+3

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/pubspec.yaml
- packages/firebase_crashlytics/test/firebase_crashlytics_test.dart
This change is support for parsing stacktrace without character index.
On debug build stacktrace like
```
package:flutter/src/widgets/framework.dart 3825:27  StatefulElement.build
```
but, on release build stacktrace like
```
package:flutter/src/widgets/framework.dart 3825  StatefulElement.build
```
Nothing. …
> [firebase_crashlytics] Fix parsing stacktrace

- packages/cloud_functions/CHANGELOG.md
- packages/cloud_functions/ios/Classes/CloudFunctionsPlugin.m
- packages/cloud_functions/pubspec.yaml
As suggested in #1070 this removes a reference to an internal header file.
> [cloud_functions] Remove unused header reference

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/FirebaseCrashlyticsPlugin.java
- packages/firebase_crashlytics/pubspec.yaml
Fixing the message of the exception used when reporting dart errors to Firebase Crashlytics. Previously all errors used the same message "Dart Error" which caused every reported error to appear as the same error in the Firebase Crashlytics console. After this change the exception message will include the message from the dart code.
flutter/flutter#31370
[CLA]: …
> [firebase_crashlyitcs] On Android, use actual the Dart exception name instead of "Dart error."

- packages/firebase_performance/CHANGELOG.md
- packages/firebase_performance/android/src/main/java/io/flutter/plugins/firebaseperformance/FirebasePerformancePlugin.java
- packages/firebase_performance/ios/Classes/FirebasePerformancePlugin.m
- packages/firebase_performance/pubspec.yaml
This clears the maps that hold all the `Trace`s and `HttpMetric`s when the `FirebasePerformance` object is created.
Fixes https://github.com/flutter/flutter/issues/34165
> [firebase_performance] Fix bug that prevented plugin to work with hot restart

- script/incremental_build.sh
This PR stops running `incremental_build.sh` script when there are no changes in `packages/'. 
Typically cirrus would run on all packages, but this often causes timeouts in PRs: 
https://github.com/flutter/plugins/pull/1764
https://github.com/flutter/plugins/pull/1725
When on `master` branch, it will still run on all packages: 
https://github.com/flutter/plugins/pull/1768/files#diff-786bf7969139ce4398c295bd601799d4L16
> [script] Don't run incremental build when there are no changes in packages

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/PolylineController.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/PolylinesController.java
- packages/google_maps_flutter/pubspec.yaml
This PR sets the width of the polyline properly according to the device density. 
The polyline width on Android devices does not respect the device density 
> Set device density to polylines

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/pubspec.yaml
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
Fix an issue where the type is incorrectly passed to `PurchasesResultWrapper.fromJson`
https://github.com/flutter/flutter/issues/34040
> [in_app_purchase]fix the type casting issue

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
- packages/in_app_purchase/pubspec.yaml
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
Fix the update purchase listener regression introduced in 0.2.0+1. Also removed related tests.
The type should not be assert checked because it is always <dynamic, dynamic> coming from the platform and the assertion will always return false.
https://github.com/flutter/flutter/issues/34040
[pub …
> [in_app_purchase]fix the regression introduced in 0.2.0+1

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/example/test_driver/cloud_firestore.dart
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/pubspec.yaml
Currently, a query with `orderBy('cake.flavor')` will return no documents when using any document pagination method (`startAtDocument` etc.).  
This happens because the internal method, which gets the data from the documents to fill in the `startAt` methods, will try to do something like `map['cake.flavor']`, which will return nothing.  
It should really be retrieving the field's value using `map['cake']['flavor']`, which this pull request adds.
I am not sure about the iOS implementation, however, CI should tell me as I added an integration test (after the index is added).
@collinjackson The query in the integration test [requires an index](https://console.firebase.google.com/project/flutter-firestore/database/firestore/indexes?create_composite=ClJwcm9qZWN0cy9mbHV0dGVyLWZpcmVzdG9yZS9kYXRhY …
> [cloud_firestore] Support for map fields in document pagination

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/pubspec.yaml
Polygons do not work on iOS because there is a bug in the controller so they never get added to the map.
31094 - feature request
- [-] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
> [google_maps_flutter] Fix incorrect polygon argument name in google maps controller

- packages/image_picker/CHANGELOG.md
- packages/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.m
- packages/image_picker/pubspec.yaml
Our internal build system is allergic to modules. We try to avoid them as much as we can and in here it seems harmless to change upstream code.
> [image_picker] Don't use modules

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/example/test_driver/crashlytics.dart
- packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/pubspec.yaml
- packages/firebase_crashlytics/test/firebase_crashlytics_test.dart
In the 'prepareKeys()' method the keys needed to be added to a map that is being returned. In the method there's an iteration over the keys, but the keys are not added to the resulting map. This leads to the issue that custom keys are not being reported to Crashlytics. This PR fixes that.
Fixes flutter/flutter#32873 …
> [firebase_crashlytics] make sure the keys are actually added to the returned map

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/example/test_driver/cloud_firestore.dart
- packages/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/lib/src/transaction.dart
- packages/cloud_firestore/pubspec.yaml
- packages/firebase_database/CHANGELOG.md
Several improvements to transactions
1. `Transaction` methods no longer cause errors when you fail to `await`. Fixes flutter/flutter#34747
1. Add an integration test for rapid calls to `FieldValue.increment`. We also seen reports of FieldValue.increment causing crashes (flutter/flutter#35269) so I'm checking in a test for this. Test is passing for me, so I'm curious what devices it fails on.
> [cloud_firestore] Transactions improvements

- packages/path_provider/CHANGELOG.md
- packages/path_provider/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java
- packages/path_provider/example/test_driver/path_provider.dart
- packages/path_provider/lib/path_provider.dart
- packages/path_provider/pubspec.yaml
> [path_provider] Update to use getExternalFilesDir

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/README.md
- packages/firebase_crashlytics/pubspec.yaml
This section will give feedback on when the installation goes fine, plus informing user that `firebase` takes a while to display the collected crashes into the Firebase Console, since the time is quite long (almost a day) i think it's better to give a feedback here. …
> [firebase_crashlytics] Update README with advice on testing installation

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/README.md
- packages/in_app_purchase/pubspec.yaml
I made the following fixes to the code samples in the documentation, as they contained some syntax errors / errors: 
* Remove explicit typing in `_subscription` callback
* Remove `const` modifier for `_kIds` list
* Fix not found ids check typos
* Migrate loop iterator from `:` to `in`
In noticed a few glitches in the docs for the `in_app_purchase` plugin when integrating with an up-to-date flutter app.  …
> [in_app_purchase] Readme updates

- packages/image_picker/CHANGELOG.md
- packages/image_picker/example/ios/image_picker_exampleTests/ImageUtilTests.m
- packages/image_picker/ios/Classes/FLTImagePickerImageUtil.h
- packages/image_picker/ios/Classes/FLTImagePickerImageUtil.m
- packages/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.m
- packages/image_picker/pubspec.yaml
We were using struct for GIFInfo, objective-c doesn't support struct with objective-c object as a member in ARC mode. We should avoid it.
Also removed an extra `;` in the import statement.
[CLA]: …
> [image_picker]use class instead of struct for GIFInfo on iOS

- packages/firebase_messaging/CHANGELOG.md
- packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java
- packages/firebase_messaging/example/test_driver/firebase_messaging.dart
- packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
- packages/firebase_messaging/lib/firebase_messaging.dart
- packages/firebase_messaging/pubspec.yaml
- packages/firebase_messaging/test/firebase_messaging_test.dart
Per suggestion https://github.com/flutter/plugins/pull/1816#discussion_r301165836 update these methods to report success or failure.
> [firebase_messaging] Change signature of subscribe/unsubscribe

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/build.gradle
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java
- packages/image_picker/pubspec.yaml
Removed cursor and added MimeTypeMap.getFileExtensionFromUrl to prevent crash occurring in some scenarios.
*App is crashing in some scenarios while image picked from the file manager or other sources. In a line:182 while getting the mimeType for an image it was causing the app to crash as sometimes there is no mime type available for the image. Now, to get image extension cursor is removed and now extension will be taken from MimeTypeMap.getFileExtensionFromUrl*
*Fixes flutter/flutter#35632* …
> [image_picker] Removed cursor to prevent crash

- packages/image_picker/CHANGELOG.md
- packages/image_picker/README.md
- packages/image_picker/pubspec.yaml
Update `RetrieveLostDataResponse` type to correct `LostDataResponse`.
The RetrieveLostDataResponse type doesn't exist as part of the standard image_picker library
None
> [image_picker] Update README example

- packages/connectivity/CHANGELOG.md
- packages/connectivity/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java
- packages/connectivity/pubspec.yaml
Regards to the issue https://issuetracker.google.com/issues/37137911 this PR do not use ConnectivityManager.EXTRA_NETWORK_INFO to determine current network state.
> [Connectivity][Android] Updated check network info logic

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/ios/Classes/FIAObjectTranslator.m
I added a converting process because UserInfo of NSError contains a value of a type not supported by flutter like `NSError` and `NSURL`.
https://flutter.dev/docs/development/platform-integration/platform-channels#platform-channel-data-types-support-and-codecs
https://github.com/flutter/flutter/issues/35554 …
> [in_app_purchase] iOS: Support unsupported UserInfo value types on NSError.

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java
- packages/url_launcher/example/lib/main.dart
- packages/url_launcher/lib/url_launcher.dart
- packages/url_launcher/pubspec.yaml
- packages/url_launcher/test/url_launcher_test.dart
As we all known, like JavaScript, android webview is disable DOM storage by default.
To enable it, this PR provides an option to enable DOM storage in android webview.
Not created
> [url_launcher]: add option to enable DOM storage in android webview

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/android/build.gradle
- packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java
- packages/google_sign_in/pubspec.yaml
This reverts commit 19bdccee76eb1063063fa5300b885d3cc70c9019.
PR https://github.com/flutter/plugins/pull/844
@ened The previous PR broke some example apps in the repo because they have not been migrated to AndroidX yet. We have to keep this commit reverted until we migrate example apps to androidX
> Revert "[google_sign_in] Added NonNull annotations, reduce Guava usage (#844)

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_transaction_wrappers.dart
- packages/in_app_purchase/lib/src/store_kit_wrappers/sk_product_wrapper.dart
- packages/in_app_purchase/pubspec.yaml
We need to override `hashCode` if overriding ==, some of the classes are missing this override.
> [in_app_purchase] add missing `hashCode` implementation

- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java
- packages/firebase_storage/example/pubspec.yaml
- packages/firebase_storage/lib/src/storage_reference.dart
- packages/firebase_storage/pubspec.yaml
Fix auto-detection of Content-Type for Android.
https://github.com/flutter/flutter/issues/32181
> [firebase_storage] Fix Content-Type auto-detection for Android

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/FirebaseCrashlyticsPlugin.java
- packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/pubspec.yaml
- packages/firebase_crashlytics/test/firebase_crashlytics_test.dart
Currently, the stacktrace parser can't handle it when there is a method without a class in dart - it instead throws its own exception and loses the original one!
This PR handles the case where there is no class name. 
There is a slight caveat to the fix on Android - firebase reporting uses a StackTraceElement which requires a class (which makes sense in Java since you can't have Class-less methods), so on Android class-less methods are reported as `.<functionName>` whereas on iOS they are simply reported as `<className>`.
I don't think this is a big problem as there seem to be other differences between how the stacktraces are reported on Android and iOS anyways.
i.e. iOS: 
Android:
* flutter/flutter#32178
Before you create this PR confirm that it meets all requirements listed below by …
> [firebase_crashlytics] Handle case where function isn't in class for stack

- packages/firebase_dynamic_links/CHANGELOG.md
- packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java
- packages/firebase_dynamic_links/pubspec.yaml
Some apps do not have an activity available when they register plugins. We should still register the plugin and leave it up to the intent listener to grab the latest intent.
> [firebase_dynamic_links] Allow FDL plugin to be registered without an activity

- packages/camera/README.md
- packages/camera/lib/new/camera.dart
- packages/camera/lib/new/src/camera_controller.dart
- packages/camera/lib/new/src/camera_testing.dart
- packages/camera/lib/new/src/common/camera_channel.dart
- packages/camera/lib/new/src/common/camera_interface.dart
- packages/camera/lib/new/src/common/camera_mixins.dart
- packages/camera/lib/new/src/common/native_texture.dart
- packages/camera/pubspec.yaml
- packages/camera/test/camera_test.dart
Beginning of refactor of the camera plugin. This only implements the camera interface and shared classes (e.g. camera mixins, `CameraChannel` & `CameraTesting` )
This also adds the `publish_to: none` to the `pubspec.yaml` until the refactor is finished.
https://github.com/flutter/flutter/issues/31225
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter- …
> [camera] Dart Interface for camera refactor

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapBuilder.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapOptionsSink.java
- packages/google_maps_flutter/example/lib/map_ui.dart
- packages/google_maps_flutter/example/test_driver/google_map_inspector.dart
- packages/google_maps_flutter/example/test_driver/google_maps.dart
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/lib/src/google_map.dart
- packages/google_maps_flutter/pubspec.yaml
- packages/google_maps_flutter/test/fake_maps_controllers.dart
- packages/google_maps_flutter/test/google_map_test.dart
Add support for `mapToolbarEnabled` property
> [google_maps_flutter] Add map toolbar support

- packages/android_alarm_manager/lib/android_alarm_manager.dart
Fixes [flutter/flutter#7115](https://github.com/flutter/flutter/issues/27115)
> [android_alarm_manager] add support for specifying startAt time for AlarmManager.periodic()

- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
Apparently the automatic method swizzling stopped working somewhere between v1.5.4-hotfix.2 and v1.7.8+hotfix.2 (it would be great to narrow that down further)
See https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification
Fixes flutter/flutter#35267
Unfortunately I don't have a good solution to test for this yet, but have manually tested.
The disadvantage of this change as written is that it may result in firebase_auth users getting warnings about "missing Push Notification Entitlement" even after https://github.com/flutter/flutter/issues/9984 is fixed. But since that has affected every iOS Flutter submission up to this point, it seems like a low priority.
> [firebase_auth] Register for iOS notifications to support phone auth

- packages/local_auth/CHANGELOG.md
- packages/local_auth/README.md
- packages/local_auth/pubspec.yaml
README has an incorrect syntax on one of the Usage sections.
> [local_auth] Fix usage syntax on README

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/ThreadedInputConnectionProxyAdapterView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFactory.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java
- packages/webview_flutter/pubspec.yaml
This patch follows the same hacks that WebView does on Android<N to set
up an InputConnection in onCreateInputConnection on the IME thread.
Previously WebView was asserting that the InputConnection code was being
run on the IME thread and then failing.
Of some extra and specific concern to this is that our webviews are
rendered inside of virtual displays. There is some extra logic in the
plugin to handle restarting the input connection and using the correct
cached connection on resize events because of this. It relies on
engine changes contained in flutter/flutter@b1a8637 (currently only on
master) in order to be called for the resize logic. When used on dev
this still brings up the keyboard when the webview isn't resized by the
keyboard pre N, but fails to fix the issue when bringing up …
> [webview_flutter] Basic fix for input pre N

- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/example/lib/main.dart
- packages/firebase_analytics/lib/firebase_analytics.dart
- packages/firebase_analytics/pubspec.yaml
- packages/firebase_analytics/test/firebase_analytics_test.dart
This PR:
- add some named events for firebase analytics.
- updated `logShare` to require a third parameter.
- update the list of reserved event names.
- include some constants that are in the documentation, but are not used. (yet?)
> [firebase_analytics] add missing named events tracking

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/README.md
- packages/firebase_auth/pubspec.yaml
- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/README.md
- packages/google_sign_in/pubspec.yaml
Document the importance of the OAuth consent screen page for google_sign_in and firebase_auth.
Fixes flutter/flutter#36041, flutter/flutter#33393, flutter/flutter#25909
> [firebase_auth] [google_sign_in] Update consent screen docs

- AUTHORS
- packages/firebase_remote_config/CHANGELOG.md
- packages/firebase_remote_config/example/test_driver/firebase_remote_config.dart
- packages/firebase_remote_config/lib/src/remote_config.dart
- packages/firebase_remote_config/lib/src/remote_config_value.dart
- packages/firebase_remote_config/pubspec.yaml
- packages/firebase_remote_config/test/firebase_remote_config_test.dart
Value source is parsed incorrectly
- Source enum names mismatch when transferred via MethodChannel. 
- For some reason `ValueSource.valueStatic` was omitted in this getter https://github.com/flutter/plugins/blob/master/packages/firebase_remote_config/lib/src/remote_config_value.dart#L15
--
[pub …
> [firebase_remote_config] fix config value source parsing

- packages/image_picker/CHANGELOG.md
- packages/image_picker/ios/Classes/ImagePickerPlugin.m
- packages/image_picker/pubspec.yaml
This PR resolves the description given in the title. image_picker hangs on iOS simulator after being rejected for the camera being unavailable.
[flutter/flutter #18095](https://github.com/flutter/flutter/issues/18095) describes very similar behaviour, except with respect to the gallery and video picker.
[flutter/plugins #595](https://github.com/flutter/plugins/pull/595) introduced the `FLTImagePickerPlugin#imagePickerControllerDidCancel` method, however it is never actually called anywhere in the code base. This PR simply makes use of it.
[Flutter Style …
> [image_picker] Fix image_picker Hanging After Attempting to Open Unavailable Camera on iOS Simulator

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java
- packages/webview_flutter/pubspec.yaml
Adds logic to `InputAwareWebView#clearFocus` to reset input creation
back to the container view's thread whenever the WebView is unfocused.
Fixes issue where Flutter UIs could no longer receive InputConnections
because WebView was causing all connections to happen on WebView's IME
thread.
Manually tested using mklim/plugins@928c790.
flutter/flutter#19718 …
> [webview_flutter] Support Flutter `TextInput`s

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/RebootBroadcastReceiver.java
- packages/android_alarm_manager/pubspec.yaml
- This PR fixes a possible crash on APIs below 19 when requesting an exact time alarm.
- I did some clean up as the IDE was complaining about it.
> [android alarm manager] Fix crash below API 19

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java
- packages/webview_flutter/pubspec.yaml
Fixes bug where the InputConnection proxy view was persisting across
multiple WebView creation calls.
Manually tested with mklim/plugins@3e033be.
flutter/flutter#19718
> [webview_flutter] Fix input bug on route changes

- CODEOWNERS
As we're mainly using this to control notification updating to reflect
the current status of PR triage ownership.
> Update CODEWNERS for google_maps_flutter and webview_flutter

- packages/share/CHANGELOG.md
- packages/share/android/src/main/java/io/flutter/plugins/share/SharePlugin.java
- packages/share/example/lib/main.dart
- packages/share/ios/Classes/SharePlugin.m
- packages/share/lib/share.dart
- packages/share/pubspec.yaml
- packages/share/test/share_test.dart
This PR adds an optional parameter to share plugin to accept `subject` in case user selects email client as sharing app.
No issues found regarding this functionality.
> [share] Add subject as optional parameter

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java
- packages/url_launcher/example/lib/main.dart
- packages/url_launcher/lib/url_launcher.dart
- packages/url_launcher/pubspec.yaml
- packages/url_launcher/test/url_launcher_test.dart
This PR enables the developer to send headers to the Android browser.
This enables the developer to keep the app session in the browser when the same authentication header is used in the app http requests and the in the web site.
- [ X I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
> [url_launcher] add support for android headers

- packages/image_picker/CHANGELOG.md
- packages/image_picker/example/ios/image_picker_exampleTests/PhotoAssetUtilTests.m
- packages/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.h
- packages/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.m
- packages/image_picker/pubspec.yaml
When the ` [info objectForKey:UIImagePickerControllerReferenceURL];` returns nil and adding the nil result to the asset array causes null pointer exception.
https://github.com/flutter/flutter/issues/34691
[CLA]: …
> [image_picker] Fix a crash when user takes a photo using devices under iOS 11.

- packages/quick_actions/CHANGELOG.md
- packages/quick_actions/android/src/main/AndroidManifest.xml
- packages/quick_actions/android/src/main/java/io/flutter/plugins/quickactions/QuickActionsPlugin.java
- packages/quick_actions/example/android/app/src/main/AndroidManifest.xml
- packages/quick_actions/example/android/app/src/main/res/drawable/ic_launcher_background.xml
- packages/quick_actions/example/android/app/src/main/res/values/styles.xml
- packages/quick_actions/example/lib/main.dart
- packages/quick_actions/pubspec.yaml
- Fixes action forwarding by removing extra Activity.
- Report shortcut usage to Android framework.
- Improves example.
> [quick_actions] Fixes Android action forwarding

- CODEOWNERS
After this change, the only plugins that lack CODEOWNERS are device_info, local_auth, sensors, and share
> Add some more CODEOWNERS

- AUTHORS
- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/pubspec.yaml
The function `getIdToken()` takes a refresh parameter. 
This parameter is ignored on iOS, and hardcoded refresh = true is used. This PR fixes that.
No changes required on Android, the refresh parameter is properly taken in account. …
> [firebase_auth] Fix getIdToken refresh param on iOS

- packages/firebase_ml_vision/CHANGELOG.md
- packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/TextRecognizer.java
- packages/firebase_ml_vision/example/lib/camera_preview_scanner.dart
- packages/firebase_ml_vision/example/lib/detector_painters.dart
- packages/firebase_ml_vision/example/lib/picture_scanner.dart
- packages/firebase_ml_vision/ios/Classes/TextRecognizer.m
- packages/firebase_ml_vision/lib/src/firebase_vision.dart
- packages/firebase_ml_vision/lib/src/text_recognizer.dart
- packages/firebase_ml_vision/pubspec.yaml
- packages/firebase_ml_vision/test/firebase_ml_vision_test.dart
Add support for cloud text recognizer to firebase_ml_vision plugin.
No related issues. 
> [firebase_ml_vision] Add support for cloud text recognizer

- packages/camera/lib/new/src/camera_controller.dart
- packages/camera/lib/new/src/common/camera_interface.dart
- packages/camera/test/camera_test.dart
To keep [backwards compatibility](https://github.com/flutter/plugins/blob/master/packages/camera/lib/camera.dart#L227), this implements the initialize method and CameraController maintains a singular static instance in the new interface. As per comment: https://github.com/flutter/plugins/pull/1832#discussion_r302288544 …
> [camera] Implement initialize and add documentation

- packages/share/CHANGELOG.md
- packages/share/lib/share.dart
- packages/share/pubspec.yaml
- packages/share/test/share_test.dart
I was also wondering if there are plans to upgrade to Dart `2.2.2`. That would allow for putting the `sharePositionOrigin` parameters inside the map literal.
> [share] Specify explicit type for invokeMethod & const for Rect

- script/common.sh
This pacakge should be removed entirely soon, so remove it from CI so we
don't spend further time on analyzer failures.
> [location_background] Ignore for CI

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java
- packages/android_alarm_manager/lib/android_alarm_manager.dart
- packages/android_alarm_manager/pubspec.yaml
Added support for setting alarms which work when the phone is in doze mode
> [android_alarm_manager] Added support for setting alarms which work when the phone is in doze mode

- packages/path_provider/CHANGELOG.md
- packages/path_provider/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java
- packages/path_provider/lib/path_provider.dart
- packages/path_provider/pubspec.yaml
This PR enables the plugin to use `getApplicationSupportDirectory` on android.
on iOS apple says : https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html
> Put app-created support files in the Library/Application support/ directory. In general, this directory includes files that the app uses to run but that should remain hidden from the user. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle.
This is very close of the usage of `getFilesDir` on Android. It is private to the app, there is no sync and the app can use to save files that are not temporary (cache).
Before you create this PR confirm that it meets …
> [path_provider] Add support to access getApplicationSupportDirectory on Android

- packages/location_background/CHANGELOG.md
- packages/location_background/README.md
- packages/location_background/pubspec.yaml
This plugin is no longer being actively maintained by the Flutter team. After merging this PR and publishing it, I'll remove the plugin in a follow-up PR.
> Final release of the location_background plugin.

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/README.md
- packages/webview_flutter/pubspec.yaml
> [webview_flutter] Add keyboard info to the README

- packages/firebase_crashlytics/CHANGELOG.md
- packages/firebase_crashlytics/README.md
- packages/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/FirebaseCrashlyticsPlugin.java
- packages/firebase_crashlytics/example/test_driver/crashlytics.dart
- packages/firebase_crashlytics/ios/Classes/FirebaseCrashlyticsPlugin.m
- packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/pubspec.yaml
- packages/firebase_crashlytics/test/firebase_crashlytics_test.dart
The initial issue I was facing was that `firebase_crashlytics` would throw an unhandled exception on e.g. `RenderFlex` exceptions without a stack trace (and the stack trace formatting was unreadable + the exceptions was missing information):
```
Error caught by Crashlytics plugin:
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): Cannot create a Trace from null.
#0      new Trace.from (package:stack_trace/src/trace.dart:105:7)
#1      Trace.format (package:stack_trace/src/trace.dart:71:21)
#2      Crashlytics.onError (package:firebase_crashlytics/src/firebase_crashlytics.dart:37:19)
<asynchronous suspension>
```
Along the way of fixing this behavior, I noticed that the `README.md` file was outdated and did not even contain the [**breaking change** from …
> [firebase_crashlytics] Fix Printing, README, Changelog & log FlutterErrorDetails.informationCollector

- packages/cloud_firestore/pubspec.yaml
Left out of https://github.com/flutter/plugins/pull/1907
Adding tests to prevent this in the future: https://github.com/flutter/plugin_tools/pull/49
> Bump cloud_firestore version for release

- packages/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
- packages/cloud_firestore/example/lib/main.dart
- packages/cloud_firestore/example/test_driver/cloud_firestore.dart
- packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
- packages/cloud_firestore/lib/src/query_snapshot.dart
- packages/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/test/cloud_firestore_test.dart
Bring `cloud_firestore` plugin in line with native SDKs by exposing the metadata of QuerySnapshot.
Fixes: https://github.com/flutter/flutter/issues/35550
> [cloud_firestore] Add metadata to QuerySnapshot

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/example/test/firebase_auth.dart
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/pubspec.yaml
Avoids an exception when `additionalProviderInfo` is `nil` or has `nil` fields.
Fixes flutter/flutter#37133
This is already tested by our integration tests, but our test CI isn't failing on exceptions that kill the app on iOS, which is how this slipped through. Once that is fixed, test failures like this will prevent PRs from being merged. (flutter/flutter#37141, https://github.com/flutter/plugin_tools/pull/50)
For the moment we can confirm that the test failure is fixed by just looking at the test logs.
> [firebase_auth] Fixes exceptions when signing in on iOS

- packages/cloud_functions/lib/src/cloud_functions.dart
The `origin` attribute isn't in the constructor on other platforms, and isn't testing so let's not expose it.
Follow-on to #1887 which hasn't been released yet, hoping to get this merged in to 0.4.1 so we don't have to do a breaking change.
> [cloud_functions] Hide the origin attribute of CloudFunctions constructor.

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/lib/google_sign_in.dart
- packages/google_sign_in/pubspec.yaml
Prevents `PlatformException` from leaking in debug mode, as Dart is not able to support an exception thrown in a future because the event loop that handles the future is not able to see the caller's stack trace.
flutter/flutter#37343
flutter/flutter#26705
dart-lang/sdk#37268 …
> [google_sign_in] Fixes PlataformException leaking in debug mode (#37343)

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/android/build.gradle
- packages/url_launcher/android/src/main/AndroidManifest.xml
- packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java
- packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java
- packages/url_launcher/example/android/build.gradle
- packages/url_launcher/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/url_launcher/pubspec.yaml
This PR :
- Updates AGP and Gradle versions.
- Splits WebViewActivity and the plugin class to improve separation of concerns.
The separation of classes and files provides encapsulation for constants used in the WebViewActivity.
> [url_launcher] Split Activity and plugin files

- packages/firebase_storage/CHANGELOG.md
- packages/firebase_storage/README.md
- packages/firebase_storage/lib/src/upload_task.dart
- packages/firebase_storage/pubspec.yaml
It is generally pretty annoying to see prints in your logs from sources you do not control and in this case, any user could manually add print statements (or even better, other kinds of notifications) very easily.  
More importantly, this actually becomes *a problem* when running multiple uploads simultaneously. Here is a list of issues I encountered:
1. There is no indication as to which upload the print statement is referring to, it is just a continuous stream of `EVENT StorageTaskEventType.progress` and `EVENT StorageTaskEventType.success`.
1. There is no way to disable these prints if I do not want them to clutter my logs.
1. This does impact performance and that is a problem when considering the previous point.
1. They seem to be delayed? I am not entirely sure about this, but I …
> [firebase_storage] Remove StorageTaskEvent prints

- packages/firebase_in_app_messaging/CHANGELOG.md
- packages/firebase_in_app_messaging/android/build.gradle
- packages/firebase_in_app_messaging/example/android/app/build.gradle
- packages/firebase_in_app_messaging/example/android/build.gradle
- packages/firebase_in_app_messaging/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/firebase_in_app_messaging/example/pubspec.yaml
- packages/firebase_in_app_messaging/pubspec.yaml
This PR updates AGP, gradle and inappmessaging-display dependencies on Android
> [firebase_inappmessaging] update AGP, gradle and inappmessaging-display

- packages/firebase_analytics/CHANGELOG.md
- packages/firebase_analytics/android/build.gradle
- packages/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java
- packages/firebase_analytics/example/android/build.gradle
- packages/firebase_analytics/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/firebase_analytics/example/lib/main.dart
- packages/firebase_analytics/example/test_driver/firebase_analytics.dart
- packages/firebase_analytics/lib/firebase_analytics.dart
- packages/firebase_analytics/pubspec.yaml
- packages/firebase_analytics/test/firebase_analytics_test.dart
This PR
- Updates AGP and Gradle.
- Removes deprecated method.
- Remove redundant castings.
> [Firebase Analytics] Update AGP, remove deprecated method and remove castings

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/PolylineBuilder.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/PolylinesController.java
- packages/google_maps_flutter/pubspec.yaml
*Currently when you start GoogleMaps widget first time, the widget won't take device display metrics into account and only when you reload state of the widget the metrics are applied to polyline width.  **As far as I know, this issue is only on Android platform.***
*flutter/flutter#36754*
> [google_maps] Set correct polyline width when building polylines.

- packages/connectivity/CHANGELOG.md
- packages/connectivity/README.md
- packages/connectivity/pubspec.yaml
Update the Readme for the Connectivity plugin to include information about changes in iOS 13.
Specifically the tightening of security around SSID and BSSID information.
Apple's email announcing the change:
Apple's documentation about [CNCopyCurrentNetworkInfo](https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo)
Resolves: [#35322](https://github.com/flutter/flutter/issues/35332)
A followup issue has been created for "fixing" the iOS 13 functionality at [#37804](https://github.com/flutter/flutter/issues/37804)
- [ X ] I read the [Contributor Guide] and followed the process …
> [connectivity] update the connectivity readme to include info about changes in iOS 13

- packages/camera/example/lib/main.dart
Permission requests force app to go into background triggering a controller.dispose() before the controller is even initialized. After the permission is granted, you end up with an exception.
We should not dispose or reinit a controller if it is not inited yet.
> [camera] Fix permissions bug in sample code.

- packages/shared_preferences/lib/shared_preferences.dart
- packages/shared_preferences/test/shared_preferences_test.dart
This is not a breaking change.
The rationale is that some apps call SharedPreferences.getInstance() from multiple widgets. If these calls come back to back before the map definition manages to come back from native, you end up getting different instances of SharedPreferences which is very very bad.
> [shared_preferences] Allow getInstance() to be reentrant

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/build.gradle
- packages/image_picker/pubspec.yaml
It's not recommended to depend on the `legacy-support-v4` artifact any longer as we should depend on the relevant sub-artifacts instead to reduce the transitive dependencies.
The `image_picker` package only uses classes from the `androidx.core` package, so we can safely replace the `androidx.legacy:legacy-support-v4` dependency with `androidx.core:core`.
This simple change is part of the PR #1878.
> [image_picker] Depend on AndroidX Core instead of Legacy Support v4

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/DisplayListenerProxy.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/webview_flutter/example/test_driver/webview.dart
- packages/webview_flutter/pubspec.yaml
Works around an Android WebView bug that was causing a crash by filtering some DisplayListener invocations.
Older Android WebView versions had assumed that when `DisplayListener#onDisplayChanged` is invoked, the display ID it is provided is of a valid display. However it turns out that when a display is removed Android may call onDisplayChanged with the ID of the removed display, in this case the Android WebView code tries to fetch and use the display with this ID and crashes with an NPE.
The issue was fixed in the Android WebView code in https://chromium-review.googlesource.com/517913 which is available starting WebView version 58.0.3029.125 however older webviews in the wild still have this issue.
Since Flutter removes virtual displays whenever a platform view is resized the webview …
> [webview_flutter] Filter onChanged events for invalid displays

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/README.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java
- packages/webview_flutter/pubspec.yaml
WebView is incorrectly dropping some input events as unhandled.
Previously we were restarting the input connection to try and work
around this, but that causes a long tail of bugs in various SDK and
WebView versions. Stop the events from bubbling instead since they still
appear to be correctly handled despite being marked wrong.
Long term we should figure out why this is happening in WebView and
figure out a deeper fix for this issue, but this workaround solves the
linked bugs in the immediate short term.
Fixes flutter/flutter#36978.
Fixes flutter/flutter#35867.
Does your PR require plugin users to manually update …
> [webview_flutter] Fix double tap on resize issue

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AndroidAlarmManagerPlugin.java
- packages/android_alarm_manager/lib/android_alarm_manager.dart
- packages/android_alarm_manager/pubspec.yaml
Added  a static `oneShotAt` method to AndroidAlarmManager to run `callback` at a given DateTime `time`.
None
> [android_alarm_manager] Added oneShotAt method to schedule a alarm at a given time

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java
- packages/camera/pubspec.yaml
If using FragmentActivity, the requestCode used for startActivityForResult needs to be below 65536. See https://stackoverflow.com/questions/25529865/java-lang-illegalargumentexception-can-only-use-lower-16-bits-for-requestcode.
> Request code needs to be below 2^16 for FragmentActivity

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/build.gradle
- packages/google_maps_flutter/pubspec.yaml
This library says that it is AndroidX compatible but the Android google-services-maps dependencies have not been upgraded to an AndroidX compatible version
In the checklist below, I am unsure if you would class this as a breaking change and if the version bump is correct.
For me it was causing an incompatibility with flutter image_picker
https://github.com/flutter/flutter/issues/27194
- [N/A] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]). …
> [flutter_google_maps] Upgrade google-services-maps v17.0.0 - AndroidX compatible

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/DisplayListenerProxy.java
- packages/webview_flutter/pubspec.yaml
Follow up on https://github.com/flutter/plugins/pull/1964
> [webview_flutter] Workaround display listeners bug on all Android versions prior to P

- packages/firebase_auth/CHANGELOG.md
- packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
- packages/firebase_auth/pubspec.yaml
Reduces a few compiler warnings in the firebase_auth plugin that were caused by using `[NSNumber numberWithInt]` when `numberWithLong` would have worked as well.
> [firebase_auth] use long datatype for timestamps (iOS)

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/example/test_driver/webview.dart
- packages/webview_flutter/ios/Classes/FlutterWebView.m
- packages/webview_flutter/lib/platform_interface.dart
- packages/webview_flutter/lib/src/webview_method_channel.dart
- packages/webview_flutter/lib/webview_flutter.dart
- packages/webview_flutter/pubspec.yaml
Reverts flutter/plugins#1979
The change broke Fuchsia, as [FuchsiaWebViewController](https://fuchsia.googlesource.com/topaz/+/refs/heads/master/public/dart/fuchsia_webview_flutter/lib/src/fuchsia_webview_platform_controller.dart#20) implements WebViewPlatformController so it doesn't get the no-op implementation of getTitle. We could change the FuchsiaWebViewController implementation to extend WebViewPlatformController so we can add new methods without requiring roll coordination.
I'm reverting temporarily until we resolve the roll issue.
> Revert "[webview_flutter] Add a getTitle method to WebViewController"

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java
- packages/android_alarm_manager/lib/android_alarm_manager.dart
- packages/android_alarm_manager/pubspec.yaml
Added ability to get `id` in the `callback`.
[#31658 Getting alarm ID in callback ](https://github.com/flutter/flutter/issues/31658)
> [android_alarm_manager] Added ability to get id in the callback

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/Convert.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapBuilder.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
- packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapOptionsSink.java
- packages/google_maps_flutter/example/test_driver/google_map_inspector.dart
- packages/google_maps_flutter/example/test_driver/google_maps.dart
- packages/google_maps_flutter/ios/Classes/GoogleMapController.h
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/lib/src/google_map.dart
- packages/google_maps_flutter/pubspec.yaml
- packages/google_maps_flutter/test/fake_maps_controllers.dart
- packages/google_maps_flutter/test/google_map_test.dart
Adds a toggle for the Google Maps Traffic layer.
https://github.com/flutter/flutter/issues/25334
> [google_maps_flutter] Adds support for displaying the traffic layer

- packages/video_player/CHANGELOG.md
- packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
- packages/video_player/lib/video_player.dart
- packages/video_player/pubspec.yaml
- packages/video_player/test/video_player_test.dart
Passes down the suggested video format for use when URLs do not include a file path.
https://github.com/flutter/flutter/issues/39076
> [video_player] Added `formatHint` to to override video format on Android

- packages/camera/test/camera_test.dart
- packages/camera/test/support_android/support_android_test.dart
- packages/connectivity/test/connectivity_test.dart
- packages/google_maps_flutter/test/circle_updates_test.dart
- packages/google_maps_flutter/test/google_map_test.dart
- packages/google_maps_flutter/test/marker_updates_test.dart
- packages/google_maps_flutter/test/polygon_updates_test.dart
- packages/google_maps_flutter/test/polyline_updates_test.dart
- packages/google_sign_in/test/google_sign_in_test.dart
- packages/image_picker/test/image_picker_test.dart
- packages/in_app_purchase/test/billing_client_wrappers/billing_client_wrapper_test.dart
- packages/in_app_purchase/test/in_app_purchase_connection/app_store_connection_test.dart
- packages/in_app_purchase/test/in_app_purchase_connection/google_play_connection_test.dart
- packages/in_app_purchase/test/store_kit_wrappers/sk_methodchannel_apis_test.dart
- packages/path_provider/test/path_provider_test.dart
- packages/quick_actions/test/quick_actions_test.dart
- packages/share/test/share_test.dart
- packages/shared_preferences/test/shared_preferences_test.dart
- packages/url_launcher/test/url_launcher_test.dart
- packages/webview_flutter/test/webview_flutter_test.dart
This is a tests only change so I did not increment versions.
> Add explicit initialization of TestWidgets binding to all breaking unit tests

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerCache.java
- packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerCacheTest.java
- packages/image_picker/pubspec.yaml
Image picker retrieveImage broke after https://github.com/flutter/plugins/pull/1877
This PR is to fix the crash.
Also added tests for the fix.
https://github.com/flutter/flutter/issues/38025
[CLA]: …
> [Image_picker] fix `retrieveImage` breakage, added tests.

- packages/instrumentation_adapter/CHANGELOG.md
- packages/instrumentation_adapter/README.md
- packages/instrumentation_adapter/android/build.gradle
- packages/instrumentation_adapter/pubspec.yaml
* Update instructions about using androidx.
* Use the latest stable release of androidx library.
* Also formatted the README.md.
> [instrumentation_adapter] Update documentation about using androidx

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java
- packages/camera/example/lib/main.dart
- packages/camera/pubspec.yaml
This PR fixes a crash when pause/resume methods are called in APIs lower than 24 on Android.
> fix android crash when pausing or resuming video on APIs lower than 24.

- packages/android_intent/CHANGELOG.md
- packages/android_intent/README.md
- packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/AndroidIntentPlugin.java
- packages/android_intent/example/lib/main.dart
- packages/android_intent/pubspec.yaml
This PR includes addition of "action_application_details_settings" action to open App info settings.
I was working on Handling denied permissions in one of my projects where i wanted to redirect user to app info settings to enable permissions in case the permissions were denied permanently (that is clicked 'Do not ask again checkbox') …
> [android_intent] Add action_application_details_settings

- packages/instrumentation_adapter/CHANGELOG.md
- packages/instrumentation_adapter/README.md
- packages/instrumentation_adapter/lib/instrumentation_adapter.dart
The instrumentation_adapter plugin doesn't support iOS yet, but we'd like to start sharing integration test code between iOS and Android.
Our existing plugin integration tests are using `test()` from `package:test` rather than `testWidgets()`. This won't work with the instrumentation_adapter plugin -- they need to be converted over to use `testWidgets` to ensure that the tests results are reported properly. But `testWidgets()` only works when the `TestWidgetsFlutterBinding` is initialized, and the Flutter driver extension uses a binding that doesn't extend `TestWidgetsFlutterBinding`.
By emulating the Flutter driver extension in the instrumentation_adapter, we can ensure that existing tests can be converted to Flutter plugins CI using the `flutter_plugin_tools drive-examples` command by …
> [instrumentation_adapter] Add support for running tests with Flutter driver

- packages/instrumentation_adapter/pubspec.yaml
This pubspec.yaml didn't get updated due to a merge conflict.
Updates the version to match the CHANGELOG
> [instrumentation_adapter] update for release

- packages/local_auth/CHANGELOG.md
- packages/local_auth/android/build.gradle
- packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java
- packages/local_auth/lib/local_auth.dart
- packages/local_auth/pubspec.yaml
- packages/local_auth/test/local_auth_test.dart
* Do not require confirmation for face unlock on Android bringing the behavior in line with iOS.
* Up the biometric version to beta01.
* Handle no device credential error (fixes the TODO in code).
> [local_auth] Avoid user confirmation on face unlock

- packages/camera/CHANGELOG.md
- packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraUtils.java
- packages/camera/pubspec.yaml
This PR fixes a possible NullPointerException when the device has only front-facing cameras.
There are two versions of `CamcorderProfile.get`, the one currently in use will return null in case there is no back-facing camera. The second version uses the `cameraId` to avoid returning null.
More: https://developer.android.com/reference/android/media/CamcorderProfile.html#get(int,%20int)
https://github.com/flutter/flutter/issues/40164
1) Create an android emulator with only a front-facing camera 
2) Run the current version
You …
> [Camera] Fixes NullPointerException

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/example/lib/padding.dart
- packages/google_maps_flutter/pubspec.yaml
> [google_maps_flutter] Prefer const constructors.

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/ios/Classes/GoogleMapController.m
- packages/google_maps_flutter/pubspec.yaml
On iOS currently, when `myLocationEnabled` is initialized to `false` and later updated to `true`, we still see the `myLocation` button even though `myLocationButton` is always set to `false`.
As a developer, I would not expect setting `myLocationEnabled` to true to automatically show the `myLocationButton` as that should be controlled independently. …
> [google_maps_flutter] Fix iOS MyLocationButton on iOS

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/example/ios/Runner.xcodeproj/project.pbxproj
- packages/android_alarm_manager/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/android_alarm_manager/pubspec.yaml
> [android_alarm_manager] Update and migrate iOS example project

- packages/android_intent/CHANGELOG.md
- packages/android_intent/example/ios/Runner.xcodeproj/project.pbxproj
- packages/android_intent/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/android_intent/pubspec.yaml
> [android_intent] Update and migrate iOS example project

- packages/camera/CHANGELOG.md
- packages/camera/example/ios/Runner.xcodeproj/project.pbxproj
- packages/camera/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/camera/pubspec.yaml
1. Looks like this was last run with `use_frameworks!`?  Let CocoaPods build as libraries instead of frameworks.
> [camera] Update and migrate iOS example project

- packages/in_app_purchase/CHANGELOG.md
- packages/in_app_purchase/example/ios/Runner.xcodeproj/project.pbxproj
- packages/in_app_purchase/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/in_app_purchase/pubspec.yaml
> [in_app_purchase] Update and migrate iOS example project

- packages/url_launcher/CHANGELOG.md
- packages/url_launcher/example/ios/Runner.xcodeproj/project.pbxproj
- packages/url_launcher/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/url_launcher/pubspec.yaml
> [url_launcher] Update and migrate iOS example project

- packages/video_player/CHANGELOG.md
- packages/video_player/example/ios/Runner.xcodeproj/project.pbxproj
- packages/video_player/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/video_player/pubspec.yaml
> [video_player] Update and migrate iOS example project

- packages/connectivity/CHANGELOG.md
- packages/connectivity/example/ios/Runner.xcodeproj/project.pbxproj
- packages/connectivity/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/connectivity/pubspec.yaml
> [connectivity] Update and migrate iOS example project

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_sign_in/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/google_sign_in/pubspec.yaml
> [google_sign_in]  Update and migrate iOS example project

- packages/package_info/CHANGELOG.md
- packages/package_info/example/ios/Runner.xcodeproj/project.pbxproj
- packages/package_info/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/package_info/pubspec.yaml
> [package_info] Update and migrate iOS example project

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/google_maps_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/google_maps_flutter/pubspec.yaml
> [google_maps_flutter] Update and migrate iOS example project

- packages/device_info/CHANGELOG.md
- packages/device_info/example/ios/Runner.xcodeproj/project.pbxproj
- packages/device_info/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/device_info/pubspec.yaml
> [device_info] Update and migrate iOS example project

- packages/image_picker/CHANGELOG.md
- packages/image_picker/example/ios/Runner.xcodeproj/project.pbxproj
- packages/image_picker/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/image_picker/pubspec.yaml
> [image_picker] Update and migrate iOS example project

- packages/local_auth/CHANGELOG.md
- packages/local_auth/example/ios/Runner.xcodeproj/project.pbxproj
- packages/local_auth/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/local_auth/pubspec.yaml
> [local_auth] Update and migrate iOS example project

- .cirrus.yml
- packages/camera/CHANGELOG.md
- packages/camera/ios/Tests/CameraPluginTests.m
- packages/camera/ios/camera.podspec
- packages/camera/pubspec.yaml
- script/build_all_plugins_app.sh
- script/check_publish.sh
- script/incremental_build.sh
- script/lint_darwin_plugins.sh
- Explicitly set `VALID_ARCHS` to architectures included in the Flutter universal binary.  This is the CocoaPods-suggested workaround to prevent tests from running on the i386 simulator.  See https://github.com/CocoaPods/CocoaPods/pull/8159.
Fixes https://github.com/flutter/flutter/issues/41439.
See also https://github.com/flutter/flutter/issues/41007.
- Add a test_spec to the podspec so the CocoaPods linter will test them.  These tests fail before the `s.platform` and `s.pod_target_xcconfig` changes.
- Add Cirrus script to lint and test plugins with iOS …
> [camera] Define clang modules in for iOS

- packages/google_maps_flutter/CHANGELOG.md
- packages/google_maps_flutter/lib/src/circle.dart
- packages/google_maps_flutter/lib/src/marker.dart
- packages/google_maps_flutter/lib/src/polygon.dart
- packages/google_maps_flutter/lib/src/polyline.dart
- packages/google_maps_flutter/pubspec.yaml
- packages/google_maps_flutter/test/fake_maps_controllers.dart
- packages/google_maps_flutter/test/polygon_updates_test.dart
- packages/google_maps_flutter/test/polyline_updates_test.dart
Create a clone of cached elements in GoogleMap (Polyline, Polygon, etc.) to detect modifications if these objects are mutated instead of modified by copy.
https://github.com/flutter/flutter/issues/39737
> [google_maps_flutter] Clone cached elements in GoogleMap

- packages/device_info/CHANGELOG.md
- packages/device_info/ios/device_info.podspec
- packages/device_info/pubspec.yaml
- script/lint_darwin_plugins.sh
Fixes https://github.com/flutter/flutter/issues/41884.
See also https://github.com/flutter/flutter/issues/41007.
- Remove device_info from the list of packages to skip when linting the podspec.  This will at minimum make sure device_info can be imported into a project without compilation errors.
> [device_info] Define clang module for iOS

- packages/sensors/CHANGELOG.md
- packages/sensors/example/ios/Runner.xcodeproj/project.pbxproj
- packages/sensors/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/sensors/pubspec.yaml
> [sensors] Update and migrate iOS example project

- packages/share/CHANGELOG.md
- packages/share/example/ios/Runner.xcodeproj/project.pbxproj
- packages/share/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/share/pubspec.yaml
> [share] Update and migrate iOS example project

- packages/connectivity/CHANGELOG.md
- packages/connectivity/ios/connectivity.podspec
- script/lint_darwin_plugins.sh
Fixes https://github.com/flutter/flutter/issues/41883.
See also https://github.com/flutter/flutter/issues/41007.
- Remove connectivity from the list of packages to skip when linting the podspec.  This will at minimum make sure connectivity can be imported into a project without compilation errors.
> [connectivity] Define clang module for iOS

- packages/android_alarm_manager/CHANGELOG.md
- packages/android_alarm_manager/ios/Classes/AndroidAlarmManagerPlugin.m
- packages/android_alarm_manager/ios/android_alarm_manager.podspec
- script/lint_darwin_plugins.sh
- Fix incompatible-pointer-types build warning where FlutterJSON**Message**Codec was passed into a parameter wanting a Flutter**Method**Codec.
```
AndroidAlarmManagerPlugin.m:12:51: warning: incompatible pointer types sending 'FlutterJSONMessageCodec * _Nonnull' to parameter of type 'NSObject<FlutterMethodCodec> * _Nonnull' [-Wincompatible-pointer-types]
```
Fixes https://github.com/flutter/flutter/issues/41855.
See also …
> [android_alarm_manager] Define clang module for iOS

- packages/instrumentation_adapter/CHANGELOG.md
- packages/instrumentation_adapter/ios/instrumentation_adapter.podspec
- script/lint_darwin_plugins.sh
- Remove instrumentation_adapter from the list of packages to skip when linting the podspec.  This will at minimum make sure instrumentation_adapter can be imported into a project without compilation errors.
> [instrumentation_adapter] Define clang module for iOS

- packages/android_intent/CHANGELOG.md
- packages/android_intent/ios/android_intent.podspec
- packages/android_intent/pubspec.yaml
- script/lint_darwin_plugins.sh
- Remove android_intent from the list of packages to skip when linting the podspec.  This will at minimum make sure android_intent can be imported into a project without compilation errors.
> [android_intent] Define clang module for iOS

- packages/url_launcher/url_launcher_web/README.md
Fixes the example of how to depend on `url_launcher_web` in its `README.md`
> [url_launcher_web] Fix README.md pubspec example

- packages/video_player/test/video_player_test.dart
Adds a FakeVideoPlayerPlatform which allows to unit test the Dart code by mocking the platform side.
Adds simple test cases for VideoPlayerController initialization.
> [video_player] Basic test for VideoPlayerController initialization

- packages/video_player/CHANGELOG.md
- packages/video_player/lib/video_player.dart
- packages/video_player/pubspec.yaml
- packages/video_player/test/video_player_test.dart
This hint is only valid in the network path.
> BugFix: `formatHint` was meant for network streams.

- packages/local_auth/CHANGELOG.md
- packages/local_auth/ios/local_auth.podspec
- script/lint_darwin_plugins.sh
- Remove local_auth from the list of packages to skip when linting the podspec.  This will at minimum make sure local_auth can be imported into a project without compilation errors.
> [local_auth] Define clang module for iOS

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/android/gradle.properties
- packages/url_launcher/url_launcher/example/android/gradle.properties
- packages/url_launcher/url_launcher/pubspec.yaml
Fixes bug where androidx app (e.g. `firebase_dynamic_links`) won't build with this plugin by enabling androidx and jetifier in the android `gradle.properties`.
This PR fixes the failing test in the [flutterfire](https://github.com/FirebaseExtended/flutterfire) repo where the `firebase_dynamic_links` example app won't build. The `firebase_dynamic_links` plugin uses androidx and this plugin needs to support the use case.
https://cirrus-ci.com/task/5767379681804288 …
> [url_launcher] Enable androidx and jetifier in android gradle properties

- packages/url_launcher/url_launcher/CHANGELOG.md
- packages/url_launcher/url_launcher/ios/url_launcher.podspec
- packages/url_launcher/url_launcher/pubspec.yaml
- script/lint_darwin_plugins.sh
- Add mechanism to skip dummy multi-platform podspecs so url_launcher_web could be skipped during lint script.
- Fix bug in lint script that was separating files by spaces instead of newlines, so wasn't running the podspecs individually.
- Remove url_launcher from the list of packages to skip when linting the podspec.  This will at minimum make sure url_launcher can be imported into a project …
> [url_launcher] Define clang module for iOS

- packages/shared_preferences/CHANGELOG.md
- packages/shared_preferences/ios/shared_preferences.podspec
- packages/shared_preferences/pubspec.yaml
- script/lint_darwin_plugins.sh
- Remove shared_preferences from the list of packages to skip when linting the podspec.  This will at minimum make sure shared_preferences can be imported into a project without compilation errors.
> [shared_preferences] Define clang module for iOS

- packages/sensors/CHANGELOG.md
- packages/sensors/ios/sensors.podspec
- script/lint_darwin_plugins.sh
- Remove sensors from the list of packages to skip when linting the podspec.  This will at minimum make sure sensors can be imported into a project without compilation errors.
> [sensors] Define clang module for iOS

- packages/package_info/CHANGELOG.md
- packages/package_info/ios/package_info.podspec
- script/lint_darwin_plugins.sh
- Remove package_info from the list of packages to skip when linting the podspec.  This will at minimum make sure package_info can be imported into a project without compilation errors.
> [package_info] Define clang module for iOS

- packages/quick_actions/CHANGELOG.md
- packages/quick_actions/ios/quick_actions.podspec
- packages/quick_actions/pubspec.yaml
- script/lint_darwin_plugins.sh
Note: there are quite a few warnings in this plugin due to UIApplicationShortcutItem being introduced in iOS 9.0 but the deployment target being 8.0, which means iOS 8 devices will crash if this plugin is used.  I didn't try to fix them in this PR.
```
QuickActionsPlugin.m:44:35: 'UIApplicationShortcutItem' is only available on iOS 9.0 or newer
QuickActionsPlugin.m:67:14: 'UIApplicationShortcutIcon' is only available on iOS 9.0 or newer
```
See …
> [quick_actions] Define clang module for iOS

- packages/path_provider/CHANGELOG.md
- packages/path_provider/ios/path_provider.podspec
- packages/path_provider/pubspec.yaml
- script/lint_darwin_plugins.sh
- Remove path_provider from the list of packages to skip when linting the podspec.  This will at minimum make sure path_provider can be imported into a project without compilation errors.
> [path_provider] Define clang module for iOS

- packages/e2e/CHANGELOG.md
- packages/e2e/README.md
- packages/e2e/pubspec.yaml
Clarifies the purpose of the package and fixes some references to the binding name.
> [e2e] update README

- packages/video_player/CHANGELOG.md
- packages/video_player/ios/video_player.podspec
- packages/video_player/pubspec.yaml
- script/lint_darwin_plugins.sh
- Remove video_player from the list of packages to skip when linting the podspec.  This will at minimum make sure video_player can be imported into a project without compilation errors.
> [video_player] Define clang module for iOS

- packages/google_sign_in/CHANGELOG.md
- packages/google_sign_in/ios/google_sign_in.podspec
- script/lint_darwin_plugins.sh
- Remove google_sign_in from the list of packages to skip when linting the podspec.  This will at minimum make sure google_sign_in can be imported into a project without compilation errors.
> [google_sign_in] Define clang module for iOS

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/ios/Classes/FlutterWebView.m
- packages/webview_flutter/ios/webview_flutter.podspec
- packages/webview_flutter/pubspec.yaml
- script/lint_darwin_plugins.sh
- Fix analyzer warnings
```
FlutterWebView.m:52:5: Instance variable used while 'self' is not set to the result of '[(super or self) init...]'
FlutterWebView.m:89:3: Returning 'self' while it is not set to the result of '[(super or self) init...]'
```
- Remove webview_flutter from the list of packages to skip when linting the podspec.  This will at minimum make sure webview_flutter can be …
> [webview_flutter] Define clang module for iOS

- packages/battery/CHANGELOG.md
- packages/battery/ios/battery.podspec
- packages/battery/pubspec.yaml
- script/lint_darwin_plugins.sh
- Remove battery from the list of packages to skip when linting the podspec.  This will at minimum make sure battery can be imported into a project without compilation errors.
> [battery] Define clang module for iOS

- script/lint_darwin_plugins.sh
Add the `--analyzer` flag during linting to run clang analyzer.
Skip packages with known analyzer warnings.
I tested this by faking out a change in every package locally and confirmed this script still passes.
Fixes https://github.com/flutter/flutter/issues/41443.
> Run clang analyzer on iOS and macOS code in CI test when packages change

- packages/battery/example/pubspec.yaml
The v1 embedder Activity can actually work with 1.6.7
> [battery] relax the example app minimal required Flutter version 

- packages/image_picker/CHANGELOG.md
- packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
- packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java
- packages/image_picker/pubspec.yaml
Use context cast application in ImagePickerPlugin#onCreate,when depend module context type is application, but depend on aar context type is acitivity, finally cause ClassCastException.
[flutter/flutter#41558](https://github.com/flutter/flutter/issues/41558)
> [image_picker] fix crash when aar from 'flutter build aar'

- packages/webview_flutter/CHANGELOG.md
- packages/webview_flutter/android/build.gradle
- packages/webview_flutter/android/gradle.properties
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterCookieManager.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFactory.java
- packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java
- packages/webview_flutter/example/android/app/build.gradle
- packages/webview_flutter/example/android/app/src/androidTestDebug/java/io/flutter/plugins/webviewflutterexample/EmbeddingV1ActivityTest.java
- packages/webview_flutter/example/android/app/src/androidTestDebug/java/io/flutter/plugins/webviewflutterexample/MainActivityTest.java
- packages/webview_flutter/example/android/app/src/main/AndroidManifest.xml
- packages/webview_flutter/example/android/app/src/main/java/io/flutter/plugins/webviewflutterexample/EmbeddingV1Activity.java
- packages/webview_flutter/example/android/app/src/main/java/io/flutter/plugins/webviewflutterexample/MainActivity.java
- packages/webview_flutter/example/android/gradle.properties
- packages/webview_flutter/example/android/settings_aar.gradle
- packages/webview_flutter/example/pubspec.yaml
- packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart
- packages/webview_flutter/example/test_driver/webview_flutter_e2e_test.dart
- packages/webview_flutter/pubspec.yaml
This depends on a new bugfix on the engine for text input to work with
the new embedding (flutter/engine#13015).
This also introduces some interesting and strange new failure cases.
With the new embedding, a FlutterView can be attached and detached from
the plugin at any point. It "should never" but technically can happen
that the plugin gets into a state where there is an active proxy adapter
view but no valid FlutterView to use for input proxying. For now I've
mostly added error logs and guards against NPEs detecting whenever we've
gotten into one of this situations. But I think we should probably
rigorously test this in an a2a specific situation to truly vet for a2a
support.
Fixes flutter/flutter#41851.
Before you create this PR confirm that it meets all requirements listed below by …
> [flutter_webview] Migrate to the new embedding
