packages/firebase_analytics/android/build.gradle
packages/firebase_analytics/example/android/app/build.gradle
packages/firebase_auth/example/android/app/build.gradle
packages/firebase_storage/example/android/app/build.gradle
packages/google_sign_in/android/build.gradle
packages/google_sign_in/example/android/app/build.gradle
packages/google_sign_in/test/google_sign_in_test.dart
packages/image_picker/example/android/app/build.gradle
packages/share/example/android/app/build.gradle

Travis failure is expected until config is completed.

Prepare travis: skip failing test and unify build-tool versions

---

packages/firebase_auth/android/build.gradle
packages/firebase_database/android/build.gradle
packages/firebase_messaging/android/build.gradle
packages/firebase_storage/android/build.gradle
packages/image_picker/android/build.gradle
packages/share/android/build.gradle

Travis is expected to fail until config is complete.

Update buildtools of more packages

---

packages/google_sign_in/lib/google_sign_in.dart
packages/google_sign_in/pubspec.yaml

can we say "sign in" one more time?

Don't try to sign in if you already are signed in on Google Sign In.

---

FlutterFire.md
packages/battery/README.md
packages/firebase_analytics/CHANGELOG.md
packages/firebase_analytics/README.md
packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/README.md
packages/firebase_database/CHANGELOG.md
packages/firebase_database/README.md
packages/firebase_messaging/CHANGELOG.md
packages/firebase_messaging/README.md
packages/firebase_storage/README.md
packages/google_sign_in/README.md
packages/image_picker/README.md
packages/path-provider/README.md
packages/share/README.md
packages/shared-preferences/README.md
packages/url-launcher/README.md

Fixes https://github.com/flutter/flutter/issues/10027

FlutterFire plugin readme updates

---

packages/firebase_database/example/lib/main.dart
packages/firebase_database/lib/ui/firebase_animated_list.dart
packages/firebase_database/lib/ui/firebase_list.dart
packages/firebase_database/lib/ui/firebase_sorted_list.dart
packages/firebase_database/lib/ui/utils/stream_subscriber_mixin.dart

This should address the database reading issues we've been seeing in the codelab/memechat, and expands API support a bit. Priority and sorting are out of scope for this PR, but coming soon.
Working on adding some tests, but would like reviews in the meantime.

FirebaseAnimatedList client-side sorting, and other database plugin improvements

---

packages/google_sign_in/README.md

Fixing changes that have occured.

Fixing changes to the api.

---

packages/google_sign_in/README.md

Some adjustments to the example api section.

Readme example wording adjustments

---

packages/firebase_database/CHANGELOG.md
packages/firebase_database/lib/firebase_database.dart
packages/firebase_database/lib/ui/firebase_animated_list.dart
packages/firebase_database/lib/ui/firebase_list.dart
packages/firebase_database/lib/ui/firebase_sorted_list.dart
packages/firebase_database/lib/ui/utils/stream_subscriber_mixin.dart
packages/firebase_database/pubspec.yaml

See https://github.com/astashov/dartdocs.org/issues/47.

Fix analyzer warnings in firebase_database

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/android/src/main/java/io/flutter/firebase_auth/FirebaseAuthPlugin.java
packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
packages/firebase_auth/lib/firebase_auth.dart
packages/firebase_auth/pubspec.yaml

Added support for createUserWithEmailAndPassword, signInWithEmailAndPassword, and signOut
* Update CHANGELOG.md
* Update pubspec.yaml

Adding support for more Firebase methods

---

packages/firebase_database/lib/src/database_reference.dart

Adding the ServerValue.TIMESTAMP to insert serverside timestamp.

Adding ServerValue.TIMESTAMP

---

README.md

I'm adding a list of the plugins.

List of plugins

---

.travis.yml
packages/firebase_database/lib/src/query.dart
packages/google_sign_in/example/lib/main.dart
packages/image_picker/example/lib/main.dart

Will require https://github.com/flutter/plugins/pull/79 (analyzer fixes for firebase_database) to be submitted first.

Run analyzer on Travis

---

packages/google_sign_in/README.md

The instructions are missing the pubspec.yaml declaration.

Add more instructions to google_sign_in

---

packages/firebase_auth/example/ios/Runner/Info.plist
packages/google_sign_in/example/ios/Runner/Info.plist

Updating the comments in the example info.plist attributes.
I've removed one of the unneeded attributes, and pushed attributes to the bottom for easy location and copy. I can move them up higher if desired.

Update the example Info.plist comments regarding Google Sign-in

---

README.md

Add pub links to root README.md

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/pubspec.yaml

Bump version of firebase_auth for release

---

packages/google_sign_in/CHANGELOG.md
packages/google_sign_in/lib/google_sign_in.dart
packages/google_sign_in/pubspec.yaml
packages/google_sign_in/test/google_sign_in_test.dart

Fixes https://github.com/flutter/flutter/issues/10050.

Limit effect of sign-in skipping (#55) to sign-in methods. Also fix tests (#10050).

---

packages/shared_preferences/CHANGELOG.md
packages/shared_preferences/README.md
packages/shared_preferences/lib/shared_preferences.dart
packages/shared_preferences/pubspec.yaml
packages/shared_preferences/test/shared_preferences_test.dart

Inspired by https://stackoverflow.com/questions/44357053/flutter-test-missingpluginexception/44360235#44360235

Add a shared preferences test and explain how to test

---

packages/android_intent/README.md

Fixes https://github.com/flutter/flutter/issues/10545

Fix link to url_launcher

---

packages/firebase_database/lib/src/query.dart

Small doc fix

---

packages/firebase_analytics/README.md
packages/firebase_auth/README.md
packages/firebase_database/README.md
packages/firebase_messaging/README.md
packages/firebase_storage/README.md

Fixes https://github.com/flutter/flutter/issues/10427

Crosslink FlutterFire plugins

---

README.md

Fixes https://github.com/flutter/flutter/issues/10724

Add sensors plugin to README of plugins

---

packages/firebase_auth/android/src/main/java/io/flutter/firebaseauth/FirebaseAuthPlugin.java
packages/firebase_auth/example/android/app/src/main/java/io/flutter/plugins/firebaseauthexample/MainActivity.java
packages/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_auth/example/ios/Runner.xcworkspace/xcshareddata/Runner.xcscmblueprint
packages/firebase_auth/example/lib/main.dart
packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
packages/firebase_auth/lib/firebase_auth.dart
packages/firebase_auth/pubspec.yaml
packages/firebase_auth/test/firebase_auth_test.dart

Expose idToken and add more unit tests to firebase_auth plugin

---

packages/image_picker/CHANGELOG.md
packages/image_picker/example/ios/Runner.xcodeproj/project.pbxproj
packages/image_picker/ios/Classes/ImagePickerPlugin.m
packages/image_picker/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/10752
UI on iPad:

Fix for crash on iPad when showing the Gallery/Camera selection dialog

---

packages/firebase_database/CHANGELOG.md
packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
packages/firebase_database/pubspec.yaml

Fixes flutter/flutter#10411
We have a test for this, but it only tested that the Dart code was doing the right thing. Until we have full integration tests for plugins it will be hard to test the native side.
I checked Android and offline persistence works fine there.

Fix Firebase database offline syncing on iOS

---

packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m

Convert round doubles to ints in Firebase Database iOS plugin

---

packages/firebase_auth/LICENSE
packages/package_info/LICENSE

Replace "Your Company" with correct values.

Fix LICENSE files

---

packages/image_picker/ios/Classes/ImagePickerPlugin.m

See https://github.com/flutter/flutter/issues/9961.

Remove workaround for image_picker

---

packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java

https://github.com/flutter/flutter/issues/11104

Fix #11104

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_database/CHANGELOG.md
packages/firebase_storage/CHANGELOG.md

This change has no code, just changelog

Update firebase_storage changelog for release.

---

packages/local_auth/README.md

A bit more terse README

---

packages/firebase_analytics/android/src/main/java/io/flutter/firebaseanalytics/FirebaseAnalyticsPlugin.java
packages/firebase_analytics/example/lib/main.dart

Support for long values on Android Firebase Analytics

---

packages/firebase_analytics/CHANGELOG.md
packages/firebase_analytics/README.md
packages/firebase_analytics/example/lib/main.dart
packages/firebase_analytics/example/lib/tabs_page.dart
packages/firebase_analytics/lib/firebase_analytics.dart
packages/firebase_analytics/lib/observer.dart
packages/firebase_analytics/pubspec.yaml
packages/firebase_analytics/test/observer_test.dart

Fixes https://github.com/flutter/flutter/issues/11216.
Requires https://github.com/flutter/flutter/pull/11236 (Travis failures are expected until it's submitted).

Automatically log PageRoute transitions

---

packages/firebase_database/CHANGELOG.md
packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
packages/firebase_database/lib/src/query.dart
packages/firebase_database/pubspec.yaml
packages/firebase_database/test/firebase_database_test.dart

Fixes https://github.com/flutter/flutter/issues/11247
Also fixes a Future that was never completed on `keepSynced` platform calls.

Avoid lingering firebase database node listeners

---

packages/image_picker/CHANGELOG.md
packages/image_picker/README.md
packages/image_picker/android/build.gradle
packages/image_picker/pubspec.yaml

Cf https://github.com/flutter/flutter/issues/9881

Avoid manual configuration of repos when consuming image_picker

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/android/src/main/java/io/flutter/firebaseauth/FirebaseAuthPlugin.java
packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
packages/firebase_auth/lib/firebase_auth.dart
packages/firebase_auth/pubspec.yaml
packages/firebase_auth/test/firebase_auth_test.dart

Implements signInWithFacebook function for firebase_auth requiring a Facebook accessToken.

Implements signInWithFacebook function for firebase_auth

---

packages/android_intent/android/build.gradle
packages/battery/android/build.gradle
packages/connectivity/android/build.gradle
packages/device_info/android/build.gradle
packages/firebase_admob/android/build.gradle
packages/firebase_analytics/android/build.gradle
packages/firebase_auth/android/build.gradle
packages/firebase_database/android/build.gradle
packages/firebase_messaging/android/build.gradle
packages/firebase_storage/android/build.gradle
packages/google_sign_in/android/build.gradle
packages/image_picker/android/build.gradle
packages/local_auth/android/build.gradle
packages/package_info/android/build.gradle
packages/path_provider/android/build.gradle
packages/quick_actions/android/build.gradle
packages/sensors/android/build.gradle
packages/share/android/build.gradle
packages/shared_preferences/android/build.gradle
packages/url_launcher/android/build.gradle

Cf change to plugin template: https://github.com/flutter/flutter/pull/11447

Made plugins add their repos to consuming projects

---

README.md

Add device info and local auth

Update README.md adding device_info

---

packages/firebase_auth/README.md

What do you think handling this by a future?

Update firebase auth readme.

---

packages/connectivity/README.md

clarify connectivity works for both ios and android

---

packages/firebase_admob/README.md

makes it easier to update as the plugin is updated

add docs to admob readme

---

packages/firebase_database/CHANGELOG.md
packages/firebase_database/example/lib/main.dart
packages/firebase_database/lib/ui/firebase_animated_list.dart
packages/firebase_database/pubspec.yaml

See: https://github.com/flutter/flutter/issues/11760

Firebase animated list index

---

README.md

Fixes https://github.com/flutter/flutter/issues/11823

Clarify contribution guidelines for this repo

---

packages/connectivity/CHANGELOG.md
packages/connectivity/README.md
packages/connectivity/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java
packages/connectivity/example/lib/main.dart
packages/connectivity/ios/Classes/ConnectivityPlugin.m
packages/connectivity/lib/connectivity.dart
packages/connectivity/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/11704

onConnectionChanged support for Connectivity plugin

---

packages/firebase_analytics/lib/observer.dart

Fix the docs for FirebaseAnalyticsObserver.

Firebase Analytics fix FirebaseAnalyticsObserver

---

packages/firebase_firestore/CHANGELOG.md
packages/firebase_firestore/pubspec.yaml

Update homepage link for Firestore
TBR @filiph

Update GMS to 11.+

---

packages/firebase_firestore/README.md

It's Cloud Firestore I'm told :)

Update name based on feedback

---

packages/firebase_firestore/pubspec.yaml

Changelog was already edited in #232
TBR @filiph

Release updated README and homepage link for Firestore

---

packages/firebase_auth/pubspec.yaml

Rev version number in prep for publishing changes from https://github.com/flutter/plugins/pull/214. Changelog was already updated in that PR.

Update firebase_auth pubspec.yaml

---

packages/url_launcher/CHANGELOG.md
packages/url_launcher/example/ios/Runner.xcodeproj/project.pbxproj
packages/url_launcher/ios/Classes/UrlLauncherPlugin.m
packages/url_launcher/pubspec.yaml

https://github.com/flutter/flutter/issues/11584
(drive-by update to cocoapods for example)

iOS url launcher to use SafariServices instead of changing to Safari app

---

packages/battery/pubspec.yaml
packages/firebase_admob/pubspec.yaml
packages/firebase_analytics/pubspec.yaml
packages/firebase_auth/pubspec.yaml
packages/firebase_database/pubspec.yaml
packages/firebase_firestore/pubspec.yaml
packages/firebase_messaging/pubspec.yaml
packages/firebase_storage/pubspec.yaml
packages/google_sign_in/pubspec.yaml
packages/path_provider/pubspec.yaml
packages/shared_preferences/pubspec.yaml
packages/url_launcher/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/12673

Update plugins to match the test package used by the Flutter framework

---

packages/android_intent/README.md
packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/AndroidIntentPlugin.java
packages/android_intent/example/android/app/src/main/AndroidManifest.xml
packages/android_intent/example/lib/main.dart

Add support for the most commonly used structured values: primitive arrays, typed lists, and nested maps.
Fixes flutter/flutter#12680.

Add support for structured values

---

packages/local_auth/README.md
packages/local_auth/example/ios/Runner/Info.plist

See discussion here: https://forums.developer.apple.com/thread/91253

Show users how to get rid of 'upgrade your app for face id' dialog.

---

packages/firebase_database/example/android/build.gradle

Firebase dependencies on Android requires Google Maven.

Update firebase_database example dependency

---

packages/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java

Fixes https://github.com/flutter/flutter/issues/12449

Fix Android implementation of setDouble in shared_preferences

---

packages/cloud_firestore/pubspec.yaml
packages/cloud_firestore/test/cloud_firestore_test.dart
packages/firebase_admob/pubspec.yaml
packages/firebase_admob/test/firebase_admob_test.dart
packages/firebase_auth/pubspec.yaml
packages/firebase_auth/test/firebase_auth_test.dart
packages/firebase_database/pubspec.yaml
packages/firebase_database/test/firebase_database_test.dart
packages/firebase_storage/pubspec.yaml
packages/firebase_storage/test/firebase_storage_test.dart
packages/google_sign_in/pubspec.yaml
packages/google_sign_in/test/google_sign_in_test.dart
packages/image_picker/pubspec.yaml
packages/image_picker/test/image_picker_test.dart
packages/path_provider/pubspec.yaml
packages/path_provider/test/path_provider_test.dart
packages/shared_preferences/pubspec.yaml
packages/shared_preferences/test/shared_preferences_test.dart
packages/url_launcher/pubspec.yaml
packages/url_launcher/test/url_launcher_test.dart

Cf. https://github.com/flutter/flutter/pull/12942

Port failing tests to use isMethodCall

---

packages/firebase_admob/android/build.gradle
packages/firebase_admob/example/android/build.gradle
packages/firebase_analytics/android/build.gradle
packages/firebase_analytics/example/android/build.gradle
packages/firebase_auth/android/build.gradle
packages/firebase_database/android/build.gradle
packages/firebase_messaging/android/build.gradle
packages/firebase_messaging/example/android/build.gradle
packages/firebase_storage/android/build.gradle
packages/firebase_storage/example/android/build.gradle
packages/google_sign_in/android/build.gradle

Fixes https://github.com/flutter/flutter/issues/12945

Use consistent version constraints for Firebase/GMS libraries in all plugins

---

packages/android_alarm_manager/README.md
packages/android_alarm_manager/android/src/main/java/io/flutter/androidalarmmanager/AlarmService.java
packages/android_alarm_manager/android/src/main/java/io/flutter/androidalarmmanager/AndroidAlarmManagerPlugin.java
packages/android_alarm_manager/example/android/app/src/main/AndroidManifest.xml
packages/android_alarm_manager/example/android/app/src/main/java/io/flutter/androidalarmmanagerexample/MainActivity.java
packages/android_alarm_manager/example/lib/main.dart
packages/android_alarm_manager/lib/android_alarm_manager.dart

Cache and re-use the Isolate (by way of a FlutterNativeView) from the main activity if there is one. When the main activity comes up, provide an API for giving it the Isolate that was cached.

[android_alarm_manager] Re-use main activity isolate

---

packages/url_launcher/CHANGELOG.md
packages/url_launcher/README.md
packages/url_launcher/android/src/main/AndroidManifest.xml
packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java
packages/url_launcher/example/lib/main.dart
packages/url_launcher/ios/Classes/UrlLauncherPlugin.m
packages/url_launcher/lib/url_launcher.dart
packages/url_launcher/pubspec.yaml
packages/url_launcher/test/url_launcher_test.dart

This will fix https://github.com/flutter/flutter/issues/13059.

Add options to URLLauncher to use WebView and SafariVC

---

packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java

Misc Fixes:
1. gallery cancel throw exception
2. camera could not save image properly
3. camera cancel throw exception
4. after cancel, could not launch camera again.
can you please review and merge?  Thank you.

misc fixes: cancel throw exception, camera does not save properly

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/lib/src/document_change.dart
packages/cloud_firestore/lib/src/document_snapshot.dart
packages/cloud_firestore/lib/src/firestore.dart
packages/cloud_firestore/lib/src/query_snapshot.dart
packages/cloud_firestore/pubspec.yaml
packages/cloud_firestore/test/cloud_firestore_test.dart

Improve Firestore's DocumentSnapshot API and add more tests

---

packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java

Also handle browser history using back button properly.

Handle URL links within the webview.

---

packages/firebase_database/lib/ui/firebase_sorted_list.dart

Attempted fix of https://github.com/flutter/flutter/issues/13295

Cancel subscriptions on FirebaseSortedList.clear

---

packages/android_alarm_manager/android/src/main/java/io/flutter/androidalarmmanager/AlarmService.java

Build is failing right now (https://travis-ci.org/flutter/plugins/jobs/310442836), so I'll merge this TBR.

Update to new engine API

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/lib/cloud_firestore.dart
packages/cloud_firestore/lib/src/document_reference.dart
packages/cloud_firestore/lib/src/set_options.dart
packages/cloud_firestore/pubspec.yaml
packages/cloud_firestore/test/cloud_firestore_test.dart

This is required for the todo list app: https://github.com/flutter/udacity-course/pull/26

Support for update and merge writes

---

packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java

Instead of retaining a reference to an activity, retains a reference to the plugin registry, which is kept updated about whether there is currently an activity.

[google_sign_in] Removes the assumption that there is always an Activity

---

packages/firebase_admob/CHANGELOG.md
packages/firebase_analytics/CHANGELOG.md
packages/firebase_auth/CHANGELOG.md
packages/firebase_database/CHANGELOG.md
packages/firebase_messaging/CHANGELOG.md
packages/firebase_storage/CHANGELOG.md

Update change logs to reflect GMS dependency changes

---

packages/firebase_database/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj

Manually adds `flutter_assets` folder to iOS project where the automatic update failed.

Add flutter_assets to project.pbxproj

---

packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/AndroidIntentPlugin.java
packages/battery/android/src/main/java/io/flutter/plugins/battery/BatteryPlugin.java
packages/connectivity/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java
packages/package_info/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java
packages/path_provider/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java
packages/quick_actions/android/src/main/java/io/flutter/plugins/quickactions/QuickActionsPlugin.java
packages/sensors/android/src/main/java/io/flutter/plugins/sensors/SensorsPlugin.java
packages/share/android/src/main/java/io/flutter/plugins/share/SharePlugin.java
packages/shared_preferences/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java
packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java

Migrating the "easy" ones in this patch. Still need to migrate:
* cloud_firestore
* firebase_*
* image_picker
* local_auth
* video_player

Work on removing foreground Activity assumption

---

.travis.yml
packages/battery/CHANGELOG.md
packages/battery/android/.gitignore
packages/battery/android/build.gradle
packages/battery/example/android/.gitignore
packages/battery/example/android/app/build.gradle
packages/battery/example/android/build.gradle
packages/battery/example/android/gradle/wrapper/gradle-wrapper.properties
packages/battery/pubspec.yaml

Update Gradle dependencies, following new Flutter project template.

Gradle upgrade for battery plugin

---

packages/firebase_core/CHANGELOG.md
packages/firebase_core/android/build.gradle
packages/firebase_core/android/src/main/java/com/yourcompany/firebasecore/FirebaseCorePlugin.java
packages/firebase_core/lib/src/firebase_app.dart
packages/firebase_core/pubspec.yaml
packages/firebase_database/CHANGELOG.md
packages/firebase_database/android/build.gradle
packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
packages/firebase_database/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_database/example/lib/main.dart
packages/firebase_database/example/pubspec.yaml
packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
packages/firebase_database/lib/firebase_database.dart
packages/firebase_database/lib/src/database_reference.dart
packages/firebase_database/lib/src/firebase_database.dart
packages/firebase_database/lib/src/query.dart
packages/firebase_database/pubspec.yaml
packages/firebase_database/test/firebase_database_test.dart

Requires flutter/plugins#310
Fixes flutter/flutter#13108

Multiple database support for firebase_database

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/lib/src/document_reference.dart
packages/cloud_firestore/pubspec.yaml
packages/cloud_firestore/test/cloud_firestore_test.dart

Add the get method to DocumentReference to allow retrieval of an individual document.
Resolves: https://github.com/flutter/flutter/issues/12866

Add Firestore DocumentReference get

---

AUTHORS
CONTRIBUTING.md

While contributing to Flutter I noticed that there is a lack of documentation mentionting what you need to do to ensure your code means the set quality standards: formatting, static analysis, testing.
I had to figure it out by looking at what Travis CI does via the `./script/plugins_tools.sh` script https://github.com/flutter/plugins/blob/master/.travis.yml#L20
An alternative to the changes in the commit would be:
`./script/plugin_tools.sh format --plugins=plugin_name`
`./script/plugin_tools.sh analyze --plugins=plugin_name`
`./script/plugin_tools.sh test plugins=plugin_name`
Is this a better way as it reuses the bash script? Works in Linux and macOS
But what if people want to run Flutter in Windows without bash installed?

Add verify changes to CONTRIBUTING.md

---

packages/camera/CHANGELOG.md
packages/camera/android/build.gradle
packages/camera/android/src/main/AndroidManifest.xml
packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
packages/camera/pubspec.yaml
packages/video_player/CHANGELOG.md
packages/video_player/android/build.gradle
packages/video_player/android/src/main/AndroidManifest.xml
packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
packages/video_player/example/android/app/src/main/java/io/flutter/plugins/videoplayerexample/MainActivity.java
packages/video_player/pubspec.yaml

Move Android classes to io.flutter.plugins.
Reflect Android template refresh in changelog and version.
Remove lints from video player plugin's Java implementation.
Update change log and version, getting ready to republish.
Subsumes https://github.com/flutter/plugins/pull/347

Clean up video and camera

---

packages/package_info/README.md
packages/package_info/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java
packages/package_info/example/ios/Runner.xcodeproj/project.pbxproj
packages/package_info/example/lib/main.dart
packages/package_info/ios/Classes/PackageInfoPlugin.m
packages/package_info/lib/package_info.dart

- add packageName for iOS/Android
- update README.md

package_info update

---

packages/package_info/CHANGELOG.md
packages/package_info/pubspec.yaml

Getting ready for republication.

Update package_info metadata

---

packages/android_intent/CHANGELOG.md
packages/android_intent/pubspec.yaml
packages/battery/CHANGELOG.md
packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/pubspec.yaml
packages/connectivity/CHANGELOG.md
packages/device_info/CHANGELOG.md
packages/device_info/pubspec.yaml
packages/image_picker/CHANGELOG.md
packages/image_picker/pubspec.yaml
packages/local_auth/CHANGELOG.md
packages/local_auth/pubspec.yaml
packages/path_provider/CHANGELOG.md
packages/path_provider/pubspec.yaml
packages/quick_actions/CHANGELOG.md
packages/quick_actions/pubspec.yaml
packages/sensors/CHANGELOG.md
packages/share/CHANGELOG.md
packages/share/pubspec.yaml
packages/shared_preferences/CHANGELOG.md
packages/shared_preferences/pubspec.yaml
packages/url_launcher/CHANGELOG.md
packages/url_launcher/pubspec.yaml

Getting ready to republish those in need.

Update metadata, non-Firebase plugins

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/android/build.gradle
packages/firebase_auth/android/src/main/AndroidManifest.xml
packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
packages/firebase_auth/example/android/app/build.gradle
packages/firebase_auth/example/android/app/google-services.json
packages/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_auth/example/ios/Runner/GoogleService-Info.plist
packages/firebase_auth/example/ios/Runner/Info.plist
packages/firebase_auth/pubspec.yaml

Move firebase_auth to io.flutter.plugins org

---

packages/firebase_analytics/CHANGELOG.md
packages/firebase_analytics/android/build.gradle
packages/firebase_analytics/android/src/main/AndroidManifest.xml
packages/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java
packages/firebase_analytics/example/android/app/build.gradle
packages/firebase_analytics/example/android/app/google-services.json
packages/firebase_analytics/example/android/app/src/main/AndroidManifest.xml
packages/firebase_analytics/example/android/app/src/main/java/io/flutter/plugins/firebaseanalyticsexample/MainActivity.java
packages/firebase_analytics/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_analytics/example/ios/Runner/GoogleService-Info.plist
packages/firebase_analytics/pubspec.yaml

Similar to the majority of the other plugins. (Remaining to follow).

Move firebase_analytics to the io.flutter.plugins org

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/lib/src/query.dart
packages/cloud_firestore/pubspec.yaml

Finishes implementing the iOS part of #369

Build fixes for cloud_firestore

---

packages/package_info/CHANGELOG.md
packages/package_info/README.md
packages/package_info/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java
packages/package_info/example/lib/main.dart
packages/package_info/ios/Classes/PackageInfoPlugin.m
packages/package_info/lib/package_info.dart
packages/package_info/pubspec.yaml

Upgrade to 0.2.0
Add class PackageInfo
Provide singleton method getInstance to fetch all information once.

refactor package_info

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
packages/cloud_firestore/example/lib/main.dart
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.h
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/lib/src/firestore.dart
packages/cloud_firestore/pubspec.yaml
packages/cloud_firestore/test/cloud_firestore_test.dart

Initial design of Firestore transaction support. iOS and tests are still in progress. Adding this PR to validate design.

Firestore transactions

---

packages/firebase_analytics/CHANGELOG.md
packages/firebase_analytics/README.md
packages/firebase_analytics/pubspec.yaml

Update 'Firebase Analytics' to 'Google Analytics for Firebase' as per https://firebase.google.com/docs/analytics/

Clarify Google Analytics

---

packages/firebase_storage/CHANGELOG.md
packages/firebase_storage/lib/firebase_storage.dart
packages/firebase_storage/pubspec.yaml

Quick one line change to allow access to the full path component of the storage ref

add getPath to storage ref object

---

packages/camera/CHANGELOG.md
packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
packages/camera/pubspec.yaml

This should hopefully fix https://github.com/flutter/flutter/issues/14274

Camera: Improve ressource cleanup on Android

---

packages/firebase_messaging/CHANGELOG.md
packages/firebase_messaging/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_messaging/example/lib/main.dart
packages/firebase_messaging/pubspec.yaml

Bumping version number to be able to republish, even though there are no changes to the plugin itself.

Fix dart 2 type error in firebase messaging example

---

packages/battery/pubspec.yaml
packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/lib/src/firestore.dart
packages/cloud_firestore/pubspec.yaml
packages/firebase_analytics/pubspec.yaml
packages/firebase_analytics/test/firebase_analytics_test.dart
packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/lib/firebase_auth.dart
packages/firebase_auth/pubspec.yaml
packages/firebase_messaging/pubspec.yaml
packages/firebase_messaging/test/firebase_messaging_test.dart
packages/firebase_storage/CHANGELOG.md
packages/firebase_storage/lib/firebase_storage.dart
packages/firebase_storage/pubspec.yaml
packages/google_sign_in/test/google_sign_in_test.dart

Fixes https://github.com/flutter/flutter/issues/15027

Fix Dart 2 issues in firebase plugins

---

packages/image_picker/CHANGELOG.md
packages/image_picker/pubspec.yaml

From comments on https://github.com/flutter/plugins/pull/424

bump minor version and add changelog entry

---

packages/android_alarm_manager/README.md

Update for rename of "io.flutter.androidalarmmanager.AlarmService" to "io.flutter.plugins.androidalarmmanager.AlarmService"

[AndroidAlarmManager] Update README.md

---

packages/firebase_messaging/lib/firebase_messaging.dart

Fixes https://github.com/flutter/flutter/issues/15735

Fix Dart 2 runtime type error in msg handler

---

packages/firebase_messaging/CHANGELOG.md
packages/firebase_messaging/pubspec.yaml

Bump version for re-publication

---

packages/camera/CHANGELOG.md
packages/camera/lib/camera.dart
packages/camera/pubspec.yaml

Follow-up on https://github.com/flutter/plugins/pull/417

Fix Dart 2 runtime type errors

---

packages/image_picker/lib/image_picker.dart
packages/image_picker/pubspec.yaml

[As discussed here](https://github.com/flutter/plugins/pull/423#discussion_r178078187)
cc @goderbauer

[Image Picker] Import foundation for the @required annotations

---

packages/google_sign_in/example/android/app/google-services.json
packages/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/example/ios/Runner/GoogleService-Info.plist
packages/google_sign_in/example/ios/Runner/Info.plist
packages/google_sign_in/example/lib/main.dart

This PR is one of several (extracted from #386) intended to remove all remaining uses of yourcompany.com from the plugin repo.
Since yourcompany.com was previously part of app IDs, the Google services json/plist files and their their source Firebase projects need updating. I do not have access to the original Firebase project used, and so created a new one. (@collinjackson feel free to push back on this, e.g. by sending me updated Google services files generated from the original project.)
Also fixed a Dart 2 runtime type error.

Remove yourcompany.com from google_sign_in

---

packages/firebase_database/example/android/app/google-services.json
packages/firebase_database/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_database/example/ios/Runner/GoogleService-Info.plist
packages/firebase_database/example/lib/main.dart
packages/firebase_database/example/pubspec.yaml

This PR is one of several (extracted from #386) intended to remove all remaining uses of yourcompany.com from the plugin repo.
Since yourcompany.com was previously part of app IDs, the Google services json/plist files and their their source Firebase projects need updating. I do not have access to the original Firebase project used, and so created a new one. (@collinjackson feel free to push back on this, e.g. by sending me updated Google services files generated from the original project.)
Also removed dependency on `firebase_auth` for this one.

Remove yourcompany.com from firebase_database

---

packages/firebase_storage/example/android/app/google-services.json
packages/firebase_storage/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_storage/example/ios/Runner/GoogleService-Info.plist

This PR is one of several (extracted from #386) intended to remove all remaining uses of yourcompany.com from the plugin repo.
Since yourcompany.com was previously part of app IDs, the Google services json/plist files and their their source Firebase projects need updating. I do not have access to the original Firebase project used, and so created a new one. (@collinjackson feel free to push back on this, e.g. by sending me updated Google services files generated from the original project.)

Remove yourcompany.com from firebase_storage

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/pubspec.yaml

Reflect Flutter SDK dependency, silently bumped at version 0.3.1.

Bump Flutter SDK requirement

---

analysis_options.yaml

- rename the analysis options file (the new preferred name is `analysis_options.yaml`)

rename the analysis options file

---

packages/firebase_database/CHANGELOG.md
packages/firebase_database/example/pubspec.yaml
packages/firebase_database/lib/firebase_database.dart
packages/firebase_database/lib/ui/firebase_animated_list.dart
packages/firebase_database/lib/ui/firebase_list.dart
packages/firebase_database/lib/ui/firebase_sorted_list.dart
packages/firebase_database/pubspec.yaml

* Update dependency on `firebase_core`
* Remove dependency on `meta`, use `flutter/foundation.dart` instead.
Addresses https://github.com/flutter/flutter/issues/15309#issuecomment-378790154

Fix firebase_database dependencies

---

packages/shared_preferences/CHANGELOG.md
packages/shared_preferences/lib/shared_preferences.dart
packages/shared_preferences/pubspec.yaml

Metadata for https://github.com/flutter/plugins/pull/467

Make shared preferences ready for publication

---

packages/firebase_admob/README.md

Readme.md should use gender enum constants

---

packages/video_player/CHANGELOG.md
packages/video_player/pubspec.yaml

Video player now makes use of a Flutter SDK API available from v0.2.5.

Bump Flutter SDK constraint

---

packages/cloud_firestore/example/lib/main.dart
packages/cloud_firestore/test/cloud_firestore_test.dart
packages/firebase_analytics/example/lib/main.dart
packages/firebase_database/example/lib/main.dart
packages/firebase_messaging/example/lib/main.dart
packages/firebase_storage/example/lib/main.dart
packages/google_mobile_maps/example/lib/animate_camera.dart
packages/google_mobile_maps/example/lib/move_camera.dart
packages/google_mobile_maps/example/lib/place_marker.dart
packages/image_picker/example/lib/main.dart
packages/shared_preferences/example/lib/main.dart
packages/video_player/example/lib/main.dart

Fixes analyzer items related to the use of `const` where applicable, cf. https://travis-ci.org/flutter/plugins/jobs/364997921

Use const constructors where possible

---

packages/firebase_analytics/CHANGELOG.md
packages/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java
packages/firebase_analytics/ios/Classes/FirebaseAnalyticsPlugin.m
packages/firebase_analytics/lib/firebase_analytics.dart
packages/firebase_analytics/pubspec.yaml
packages/firebase_messaging/CHANGELOG.md
packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java
packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
packages/firebase_messaging/lib/firebase_messaging.dart
packages/firebase_messaging/pubspec.yaml
packages/firebase_storage/CHANGELOG.md
packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java
packages/firebase_storage/ios/Classes/FirebaseStoragePlugin.m
packages/firebase_storage/lib/firebase_storage.dart
packages/firebase_storage/pubspec.yaml
packages/firebase_storage/test/firebase_storage_test.dart

Updated plugin channel names to 'plugins.flutter.io/<plugin>'

---

packages/firebase_admob/README.md

Add some more properties to the example for using the AdMob ads.

AdMob Readme Enhancement

---

packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/Convert.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/GoogleMapBuilder.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/GoogleMapController.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/GoogleMapOptionsSink.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/GoogleMobileMapsPlugin.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/MarkerBuilder.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/MarkerController.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/MarkerOptionsSink.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/OnCameraMoveListener.java
packages/google_mobile_maps/android/src/main/java/io/flutter/plugins/googlemobilemaps/OnMarkerTappedListener.java
packages/google_mobile_maps/example/lib/animate_camera.dart
packages/google_mobile_maps/example/lib/main.dart
packages/google_mobile_maps/example/lib/map_ui.dart
packages/google_mobile_maps/example/lib/move_camera.dart
packages/google_mobile_maps/example/lib/page.dart
packages/google_mobile_maps/example/lib/place_marker.dart
packages/google_mobile_maps/ios/Classes/GoogleMobileMapsPlugin.h
packages/google_mobile_maps/lib/google_mobile_maps.dart
packages/google_mobile_maps/lib/src/callbacks.dart
packages/google_mobile_maps/lib/src/controller.dart
packages/google_mobile_maps/lib/src/marker.dart
packages/google_mobile_maps/lib/src/platform_overlay.dart
packages/google_mobile_maps/lib/src/ui.dart

* Add callbacks for marker taps and camera movements.
* Refactor Android code to confine channel and JSON handling to main plugin class.
* Further refactor to follow Java's file-per-type convention.

Add GoogleMap callbacks

---

packages/google_sign_in/CHANGELOG.md
packages/google_sign_in/pubspec.yaml

... to republish after https://github.com/flutter/plugins/pull/511

Update metadata for pub

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
packages/firebase_auth/lib/firebase_auth.dart
packages/firebase_auth/pubspec.yaml

This enables linking an existing Firebase user with Facebook.

Add link with facebook credential

---

packages/firebase_auth/test/firebase_auth_test.dart

Add test to cover new functionality of #527

Add test for Facebook link

---

packages/google_maps_flutter/README.md
packages/google_maps_flutter/example/android/app/src/main/AndroidManifest.xml
packages/google_maps_flutter/example/ios/Runner/AppDelegate.m

* Removed API key that can be used only by me.
* Fixed error in path to manifest file.
* Reworked readme example code to make it a complete Dart sample.

Review comments

---

packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m

https://github.com/firebase/firebase-ios-sdk/pull/1123
This pull request made breaking changes to the firebase/firebase-ios-sdk api
Update api calls into the sdk to fix.

update firebase auth plugin for breaking changes

---

packages/video_player/ios/Classes/VideoPlayerPlugin.m

Some HLS do not have tracks, item was not set to player and it was not played. Fixed that by initializing AVPlayer with AVPlayerItem.

Supports HLS video on iOS

---

packages/google_maps_flutter/example/lib/map_ui.dart
packages/google_maps_flutter/example/lib/place_marker.dart

Fixes https://github.com/flutter/flutter/issues/17475

google_maps_flutter: Remove listeners on State.dispose

---

packages/google_sign_in/CHANGELOG.md
packages/google_sign_in/README.md
packages/google_sign_in/lib/google_sign_in.dart
packages/google_sign_in/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/13761

Document Google OAuth scopes

---

packages/google_sign_in/.gitignore

Update .gitignore to new `dart_tool` pub cache

---

packages/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_maps_flutter/ios/google_maps_flutter.podspec

Make `google_maps_flutter` work in Swift-based Flutter apps.
Cf https://github.com/flutter/flutter/issues/73#issuecomment-394668427

Add static_framework to Google Maps pod

---

packages/firebase_dynamic_links/CHANGELOG.md
packages/firebase_dynamic_links/lib/src/dynamic_link_parameters.dart
packages/firebase_dynamic_links/lib/src/ios_parameters.dart
packages/firebase_dynamic_links/lib/src/navigation_info_parameters.dart
packages/firebase_dynamic_links/lib/src/short_dynamic_link.dart
packages/firebase_dynamic_links/pubspec.yaml

Fixed dynamic link dartdoc generation

---

packages/image_picker/CHANGELOG.md
packages/image_picker/pubspec.yaml

Cf https://github.com/flutter/plugins/pull/600

Update metadata for republish

---

packages/firebase_database/test/firebase_database_test.dart
packages/google_sign_in/test/google_sign_in_test.dart
packages/url_launcher/test/url_launcher_test.dart

Remove the incorrect usage of `isInstanceOf` in some plugin tests.

Fix CI breakage

---

packages/firebase_ml_vision/README.md
packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/BarcodeDetector.java
packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/Detector.java
packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/FaceDetector.java
packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/FirebaseMlVisionPlugin.java
packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/LabelDetector.java
packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/TextDetector.java
packages/firebase_ml_vision/example/android/app/src/main/AndroidManifest.xml
packages/firebase_ml_vision/example/lib/detector_painters.dart
packages/firebase_ml_vision/example/lib/main.dart
packages/firebase_ml_vision/ios/Classes/BarcodeDetector.m
packages/firebase_ml_vision/ios/Classes/FaceDetector.m
packages/firebase_ml_vision/ios/Classes/FirebaseMlVisionPlugin.h
packages/firebase_ml_vision/ios/Classes/FirebaseMlVisionPlugin.m
packages/firebase_ml_vision/ios/Classes/LabelDetector.m
packages/firebase_ml_vision/ios/Classes/TextDetector.m
packages/firebase_ml_vision/ios/firebase_ml_vision.podspec
packages/firebase_ml_vision/lib/firebase_ml_vision.dart
packages/firebase_ml_vision/lib/src/barcode_detector.dart
packages/firebase_ml_vision/lib/src/face_detector.dart
packages/firebase_ml_vision/lib/src/firebase_vision.dart
packages/firebase_ml_vision/lib/src/label_detector.dart
packages/firebase_ml_vision/test/firebase_ml_vision_test.dart

Just placeholder code. Not meant to be published to pub.

Setup placeholder code to add other on-device detectors

---

packages/firebase_database/CHANGELOG.md
packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java
packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m
packages/firebase_database/lib/firebase_database.dart
packages/firebase_database/lib/src/database_reference.dart
packages/firebase_database/lib/src/on_disconnect.dart
packages/firebase_database/pubspec.yaml
packages/firebase_database/test/firebase_database_test.dart

Based on [PR](https://github.com/flutter/plugins/pull/578) from @rmarau.

On disconnect

---

packages/firebase_ml_vision/README.md
packages/firebase_ml_vision/lib/src/face_detector.dart
packages/firebase_ml_vision/test/firebase_ml_vision_test.dart

https://github.com/bparrishMines/plugins/blob/readme_metadata/packages/firebase_ml_vision/README.md

Update README with new detectors

---

packages/google_maps_flutter/example/lib/map_ui.dart
packages/google_sign_in/lib/widgets.dart
packages/path_provider/example/lib/main.dart
packages/shared_preferences/example/lib/main.dart

I was previously using the wrong version of clang-format. I switched to the correct version 5.0.0 so now formatting should be stable.

Fix formatting

---

AUTHORS
packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
packages/firebase_auth/lib/firebase_auth.dart
packages/firebase_auth/pubspec.yaml
packages/firebase_auth/test/firebase_auth_test.dart

related issue:
FirebaseUser.delete() - flutter/flutter#15907

Adding support for FirebaseUser.delete()

---

analysis_options.yaml

to match https://github.com/flutter/flutter/pull/20099

Enable lint unnecessary_statements. Codebase is compliant.

---

packages/firebase_dynamic_links/CHANGELOG.md
packages/firebase_dynamic_links/README.md
packages/firebase_dynamic_links/ios/firebase_dynamic_links.podspec
packages/firebase_dynamic_links/lib/src/firebase_dynamic_links.dart
packages/firebase_dynamic_links/pubspec.yaml

Updates version and a few comments for PR https://github.com/flutter/plugins/pull/686

Document that retrieving dynamic link always return null after first attempt

---

packages/url_launcher/CHANGELOG.md
packages/url_launcher/ios/Classes/UrlLauncherPlugin.m
packages/url_launcher/lib/url_launcher.dart
packages/url_launcher/pubspec.yaml
packages/url_launcher/test/url_launcher_test.dart

Depends on a change introduced in https://github.com/flutter/flutter/releases/tag/v0.5.6
TODO: manual verification
cc @mehmetf

Move SystemChrome update to platform side

---

packages/camera/CHANGELOG.md
packages/camera/pubspec.yaml

Bump the version for change https://github.com/flutter/plugins/pull/645

Bump camera version

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/pubspec.yaml

Version bump for https://github.com/flutter/plugins/pull/795

Bump version for #795

---

packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java

Check if activity is finishing before start authenticating.

Check activity isFinishing before authentication

---

.opensource/project.json

Add page names for firebaseopensource.com

---

packages/firebase_database/CHANGELOG.md
packages/firebase_database/android/build.gradle
packages/firebase_database/example/android/build.gradle
packages/firebase_database/example/android/gradle/wrapper/gradle-wrapper.properties
packages/firebase_database/example/pubspec.yaml
packages/firebase_database/pubspec.yaml

Firebase Android dependencies must be on latest to work together so bumping Android dependencies to latest.

bump firebase_database android dependencies to latest

---

packages/firebase_storage/CHANGELOG.md
packages/firebase_storage/android/build.gradle
packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java
packages/firebase_storage/example/android/build.gradle
packages/firebase_storage/example/android/gradle/wrapper/gradle-wrapper.properties
packages/firebase_storage/example/pubspec.yaml
packages/firebase_storage/pubspec.yaml

Since Firebase Android dependencies need to be latest to work together, I'm bumping Android dependencies to latest here.

Bump firebase_storage Android dependencies to latest

---

packages/video_player/CHANGELOG.md
packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
packages/video_player/pubspec.yaml

The constructors that were being used are now marked deprecated, which gives users warnings when they build using this plugin. 
/cc @mit-mit

Use exoplayer's prefered API for MediaSources

---

packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java

fix formatting issue in video_player plugin.

fixing formatting

---

packages/firebase_analytics/CHANGELOG.md
packages/firebase_analytics/lib/firebase_analytics.dart
packages/firebase_analytics/pubspec.yaml

SIGN_UP_METHOD was deprecated. Use METHOD in logSignUp
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Param#SIGN_UP_METHOD

Use METHOD value instead of SIGN_UP_METHOD

---

packages/firebase_analytics/pubspec.yaml

Will land TBR @jonahwilliams to unbreak CI
/cc @mklim

Pin mockito to 3.0.0 to unbreak CI

---

packages/android_alarm_manager/example/android/gradle/wrapper/gradle-wrapper.properties
packages/android_intent/example/android/gradle/wrapper/gradle-wrapper.properties
packages/battery/example/android/gradle/wrapper/gradle-wrapper.properties
packages/camera/example/android/gradle/wrapper/gradle-wrapper.properties
packages/connectivity/example/android/gradle/wrapper/gradle-wrapper.properties
packages/device_info/example/android/gradle/wrapper/gradle-wrapper.properties
packages/firebase_admob/android/gradle/wrapper/gradle-wrapper.properties
packages/google_maps_flutter/example/android/gradle/wrapper/gradle-wrapper.properties
packages/image_picker/example/android/gradle/wrapper/gradle-wrapper.properties
packages/in_app_purchase/example/android/gradle/wrapper/gradle-wrapper.properties
packages/local_auth/example/android/gradle/wrapper/gradle-wrapper.properties
packages/location_background/example/android/gradle/wrapper/gradle-wrapper.properties
packages/package_info/example/android/gradle/wrapper/gradle-wrapper.properties
packages/path_provider/example/android/gradle/wrapper/gradle-wrapper.properties
packages/quick_actions/example/android/gradle/wrapper/gradle-wrapper.properties
packages/sensors/example/android/gradle/wrapper/gradle-wrapper.properties
packages/share/example/android/gradle/wrapper/gradle-wrapper.properties
packages/shared_preferences/example/android/gradle/wrapper/gradle-wrapper.properties
packages/url_launcher/example/android/gradle/wrapper/gradle-wrapper.properties
packages/video_player/android/gradle/wrapper/gradle-wrapper.properties
packages/video_player/example/android/gradle/wrapper/gradle-wrapper.properties
packages/webview_flutter/example/android/gradle/wrapper/gradle-wrapper.properties

@dnfield Splitting the previous PR #817 to make review easier.

Set all gradle-wrapper versions to 4.10.2

---

packages/google_maps_flutter/README.md

Adds instructions for iOS and notes that this is a developers preview.

Update Google Maps Plugin README.

---

packages/android_alarm_manager/example/android/build.gradle
packages/cloud_firestore/example/android/build.gradle
packages/cloud_functions/example/android/build.gradle
packages/firebase_admob/example/android/build.gradle
packages/firebase_analytics/example/android/build.gradle
packages/firebase_auth/README.md
packages/firebase_auth/example/android/build.gradle
packages/firebase_database/example/android/build.gradle
packages/firebase_dynamic_links/example/android/build.gradle
packages/firebase_messaging/example/android/build.gradle
packages/firebase_ml_vision/example/android/build.gradle
packages/firebase_performance/example/android/build.gradle
packages/firebase_remote_config/README.md
packages/firebase_remote_config/example/android/build.gradle
packages/firebase_storage/example/android/build.gradle

https://github.com/google/play-services-plugins/tree/master/google-services-plugin
The plugin now highlights dependency conflicts a lot better.
@dnfield the final chunk

Upgrade Google services plugin to 4.2.0

---

packages/google_maps_flutter/README.md

the pub plugin referenced here is unofficial and make people confused

Delete reference to the pub plugin

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/pubspec.yaml

Also updates the minimal required Flutter SDK to one that has platform
views support.

Bump google_maps_flutter's version to 0.0.3.

---

packages/webview_flutter/pubspec.yaml

We need a version that supports platform views.

Set a minimal Flutter version for the webview plugin.

---

packages/google_maps_flutter/README.md

Don't recommend to add maps as a git dependency any more.

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/pubspec.yaml

Just so we can publish the fixed README to pub.

Bump maps plugin version.

---

README.md

I have added: 
```
google_maps_flutter
web_view_flutter
```
I didn't add:
```
in_app_purchase
location_background
```
cause they are not published yet!
and added underscore to `device info` =>  `device_info`

add new plugins reference to README.md

---

packages/url_launcher/CHANGELOG.md
packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java
packages/url_launcher/example/lib/main.dart
packages/url_launcher/pubspec.yaml

fix: startActivity by context should add flag -- Intent.FLAG_ACTIVITY_NEW_TASK

fix: url_launcher can't launcher for Android

---

packages/camera/example/android/build.gradle
packages/image_picker/android/build.gradle
packages/video_player/example/android/build.gradle

Caused upstream by https://issuetracker.google.com/issues/120759347

Temporarily add exoplayer repo accidentally deleted from jcenter

---

packages/webview_flutter/pubspec.yaml

I failed to do so when merging master into #974

Bump webview_flutter's version.

---

packages/camera/CHANGELOG.md
packages/camera/pubspec.yaml

Follow-up to https://github.com/flutter/plugins/pull/1046

Bump camera plugin version and update changelog.

---

.cirrus.yml

update to Mojave Xcode 10 to support IOS 12 apis

cirrues update to mojave-xcode-10.1

---

packages/cloud_firestore/example/ios/Runner.xcodeproj/project.pbxproj
packages/cloud_firestore/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
packages/cloud_firestore/ios/cloud_firestore.podspec
packages/firebase_analytics/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_analytics/ios/firebase_analytics.podspec
packages/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_auth/ios/firebase_auth.podspec
packages/firebase_database/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_database/ios/firebase_database.podspec
packages/firebase_ml_vision/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_remote_config/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_remote_config/ios/firebase_remote_config.podspec
packages/firebase_storage/example/ios/Runner.xcodeproj/project.pbxproj
packages/firebase_storage/ios/firebase_storage.podspec

8.0 is the minimum version supported by Flutter.

Update all plugins to minimum iOS 8.0

---

packages/in_app_purchase/example/pubspec.yaml
packages/in_app_purchase/pubspec.yaml

[IAP] Update dev deps to match flutter_driver

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/README.md
packages/firebase_auth/pubspec.yaml

Helping to address https://github.com/flutter/flutter/issues/27119 by fixing the example to match the new API

Updating the example to match the new API

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java
packages/firebase_auth/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/27132

Fix Firebase phone auth on Android

---

packages/connectivity/CHANGELOG.md
packages/connectivity/lib/connectivity.dart
packages/connectivity/pubspec.yaml
packages/connectivity/test/connectivity_test.dart

Fixes flutter/flutter#27643
Required for merging #895

Add unit tests to connectivity plugin

---

packages/video_player/pubspec.yaml

New release to add additional documentation (see #1214).

Bump video_player version to 0.10.0+2

---

packages/android_alarm_manager/CHANGELOG.md
packages/android_alarm_manager/android/build.gradle
packages/android_alarm_manager/pubspec.yaml

[android_alarm_manager] Include missing dependency

---

packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/TranslatorTest.m
packages/in_app_purchase/ios/Classes/FIAObjectTranslator.h
packages/in_app_purchase/ios/Classes/FIAObjectTranslator.m
packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m

Part of the effort to fix https://github.com/flutter/flutter/issues/27960

[In_app_purchase]remove categories

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/lib/src/document_reference.dart
packages/cloud_firestore/lib/src/transaction.dart
packages/cloud_firestore/pubspec.yaml
packages/cloud_firestore/test/cloud_firestore_test.dart
packages/firebase_messaging/example/ios/Runner.xcodeproj/project.pbxproj

fix firestore multiple app support for DocumentSnapshot and transactions

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
packages/cloud_firestore/pubspec.yaml

Fixes flutter/flutter#22442
Fixes flutter/flutter#17663

Fix IllegalStateException for cloud_firestore transactions

---

packages/firebase_core/CHANGELOG.md
packages/firebase_core/lib/src/firebase_app.dart
packages/firebase_core/pubspec.yaml
packages/firebase_core/test/firebase_core_test.dart

Remove assertion for firebase_core that can interfere with hot-restart

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/pubspec.yaml

Fix iOS transactions when getting a snapshot that doesn't exist

---

packages/firebase_ml_vision/README.md

https://github.com/flutter/plugins/blob/master/packages/firebase_ml_vision/lib/src/barcode_detector.dart#L12

Fixed typo `BarcodeValueType`

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/pubspec.yaml

Fix cloud_firestore dates on some iOS devices

---

packages/firebase_storage/CHANGELOG.md
packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java
packages/firebase_storage/ios/Classes/FirebaseStoragePlugin.m
packages/firebase_storage/lib/src/firebase_storage.dart
packages/firebase_storage/pubspec.yaml
packages/firebase_storage/test/firebase_storage_test.dart

Fixes flutter/flutter#20458
I think it could use an example/test that exercises the native side

[firebase_storage] Support for getReferenceFromUrl

---

packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/MarkersController.java
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterCookieManager.java
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/JavaScriptChannel.java
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFactory.java
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java

Also filed https://github.com/flutter/flutter/issues/28595 to add a presubmit check for this.

Add missing license headers

---

packages/image_picker/CHANGELOG.md
packages/image_picker/pubspec.yaml

[image_picker] Update pub info for #742

---

packages/firebase_ml_vision/example/README.md

[firebase_ml_vision] Incorrect link for including the ML Model pods into the example project

---

CODEOWNERS

Also sorted list in https://github.com/flutter/plugins/pull/1300/commits/552ce42243d1da301a4b45a0ec8aa1ffde09cdbb

Add my name to firebase_performance and firebase_dynamic_links owners

---

packages/connectivity/README.md

[connectivity] Update README.md

---

packages/image_picker/CHANGELOG.md
packages/image_picker/pubspec.yaml

Describes changes from flutter/plugins#1268.

[image_picker] Update versioning for #1268

---

CONTRIBUTING.md

We do not use travis-ci anymore

Change build link in contributors site to cirrus

---

packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebViewClient.java
packages/webview_flutter/example/lib/main.dart
packages/webview_flutter/ios/Classes/FLTWKNavigationDelegate.m
packages/webview_flutter/lib/webview_flutter.dart
packages/webview_flutter/test/webview_flutter_test.dart

Fixes https://github.com/flutter/flutter/issues/27910

[webview_flutter] Add a page loaded callback

---

packages/shared_preferences/CHANGELOG.md
packages/shared_preferences/pubspec.yaml

[shared_preferences] Update shared_preferences CHANGELOG for release

---

.cirrus.yml

I'll re-enable Android testing once the bots are happy.
I filed the failure as flutter/flutter#29571

Disable Android emulator testing for now to fix tests

---

packages/webview_flutter/CHANGELOG.md
packages/webview_flutter/pubspec.yaml

Followup to https://github.com/flutter/plugins/pull/1335

[webview_flutter] Update changelog and bump versions.

---

CONTRIBUTING.md

Update CONTRIBUTING.md with test info

---

packages/firebase_crashlytics/example/README.md
packages/firebase_crashlytics/ios/firebase_crashlytics.podspec

Remove some extra white spaces.

[firebase_crashlytics]Remove white spaces to make git happy

---

FlutterFire.md

Include Crashlytics plugin in the list of FlutterFire plugins.

Add Crashlytics plugin to FlutterFire docs

---

packages/android_alarm_manager/CHANGELOG.md
packages/android_alarm_manager/pubspec.yaml

Fixes incorrect version from https://github.com/flutter/plugins/pull/1337.

Bump version to 0.4.1+5

---

README.md

Add firebase_crashlytics plugin detail.

[firebase_crashlytics] Add firebase_crashlytics for Readme.

---

AUTHORS
packages/firebase_analytics/CHANGELOG.md
packages/firebase_analytics/lib/firebase_analytics.dart
packages/firebase_analytics/pubspec.yaml
packages/firebase_analytics/test/firebase_analytics_test.dart

[firebase_analytics] Add 'loginMethod' parameter to logLogin()

---

packages/webview_flutter/example/test_driver/webview.dart

Adds the same `pumpWidget` utility we settled on in #1409.

[webview_flutter] Use a pumpWidget utility in e2e tests

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/lib/src/google_map.dart
packages/google_maps_flutter/pubspec.yaml

Adds a key parameter to the GoogleMap widget.

[google_maps_flutter] Add a key parameter to the GoogleMap widget

---

packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
packages/google_maps_flutter/example/test_driver/google_map_inspector.dart
packages/google_maps_flutter/example/test_driver/google_maps.dart
packages/google_maps_flutter/ios/Classes/GoogleMapController.m

Adds tests for google maps plugin zoom levels

[google_maps] Maps zoom level tests

---

packages/firebase_database/example/lib/main.dart
packages/firebase_storage/example/lib/main.dart
packages/google_sign_in/example/lib/main.dart
packages/shared_preferences/example/lib/main.dart

Fix formatting on the main.dart files in example apps for firebase_database, firebase_storage, google_sign_in, shared_preference

Fix formatting in main.dart of firebase_database, firebase_storage, google_sign_in, shared_preference

---

packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
packages/google_maps_flutter/example/test_driver/google_map_inspector.dart
packages/google_maps_flutter/example/test_driver/google_maps.dart
packages/google_maps_flutter/ios/Classes/GoogleMapController.m

Add maps tests for rotate tilt and zoom

[google_maps] Add tests for rotate tilt and zoom gestures

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/android/build.gradle
packages/google_maps_flutter/example/android/build.gradle
packages/google_maps_flutter/pubspec.yaml

Updates the android gradle version.

[google_maps] Update android gradle version

---

packages/battery/CHANGELOG.md
packages/battery/README.md
packages/battery/pubspec.yaml

`Battery.batteryLevel` returns a `Future`.
- [N/A] All existing and new tests are passing.

[battery] Update example in README.md

---

packages/image_picker/CHANGELOG.md
packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
packages/image_picker/pubspec.yaml

On android, we delete the original image after scaling. It causes a fatal issue when user picks an image from gallery. We should never delete an image from user's gallery! This PR fixes the issue.
https://github.com/flutter/flutter/issues/29594 …

[Image_picker]Android: fix original image deleted after scaling.

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/pubspec.yaml

Forgot to identify them being missed in https://github.com/flutter/plugins/pull/985

Update changelog and pubspec for onTap

---

packages/image_picker/CHANGELOG.md
packages/image_picker/ios/Classes/ImagePickerPlugin.m
packages/image_picker/pubspec.yaml

Under iOS, the camera permissions have not been correctly checked. If the user did not allow camera access, the camera view was launched and displayed a black screen. It was then also possible to make a photo of the black screen and use it. The camera view controller is now only launched, when the user has granted permissions. Otherwise it will not launch and flutter will also receive an error.
https://github.com/flutter/flutter/issues/30378 …

[image_picker] Check camera permissions and return error

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/android/build.gradle
packages/cloud_firestore/example/android/settings.gradle
packages/cloud_firestore/example/pubspec.yaml
packages/cloud_firestore/pubspec.yaml

Update Android dependencies to use Gradle BoM to have better consistency across Firebase Android dependencies.

[cloud_firestore] Use Gradle BoM with cloud_firestore

---

packages/cloud_firestore/CHANGELOG.md

Removes white spaces to make the git happy.

[cloud_firestore]remove white spaces.

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/example/test_driver/cloud_firestore.dart
packages/cloud_firestore/pubspec.yaml
packages/firebase_database/CHANGELOG.md
packages/firebase_database/example/lib/main.dart
packages/firebase_database/example/pubspec.yaml
packages/firebase_database/example/test_driver/firebase_database.dart
packages/firebase_database/example/test_driver/firebase_database_test.dart
packages/firebase_database/pubspec.yaml

Integration tests for cloud_firestore and firebase_database transactions

---

packages/package_info/CHANGELOG.md
packages/package_info/example/pubspec.yaml
packages/package_info/example/test_driver/package_info.dart
packages/package_info/example/test_driver/package_info_test.dart
packages/package_info/pubspec.yaml

Create integration test for package_info

[package_info] Integration tests.

---

packages/image_picker/CHANGELOG.md
packages/image_picker/pubspec.yaml

The previous change is not a breaking change.

[image_picker]version fix.

---

packages/firebase_analytics/CHANGELOG.md
packages/firebase_analytics/README.md
packages/firebase_analytics/pubspec.yaml

Surfacing the `firebase_analytics` example code on the README in a way that should be easy to access from [Pub](https://pub.dartlang.org).
N/A

Adding links to the firebase_analytics  example

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
packages/firebase_auth/ios/firebase_auth.podspec
packages/firebase_auth/pubspec.yaml

This is mirroring a change Firebase team has done in Google. It is not a breaking change.

[firebase_auth] Migrate FlutterAuthPlugin from deprecated APIs

---

packages/firebase_storage/CHANGELOG.md
packages/firebase_storage/example/pubspec.yaml
packages/firebase_storage/example/test_driver/firebase_storage.dart
packages/firebase_storage/example/test_driver/firebase_storage_test.dart
packages/firebase_storage/pubspec.yaml

Basically does the same thing as the example app but written as a test that can run on CI.

[firebase_storage] Initial integration testing

---

packages/webview_flutter/CHANGELOG.md
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
packages/webview_flutter/example/test_driver/webview.dart
packages/webview_flutter/ios/Classes/FlutterWebView.m
packages/webview_flutter/lib/webview_flutter.dart
packages/webview_flutter/pubspec.yaml
packages/webview_flutter/test/webview_flutter_test.dart

WebView controller allows setting headers.
flutter/flutter#25831

[webview_flutter] controller headers loadurl

---

CODEOWNERS

Adding me, @kroikie, @bparrishMines, and @iskakaushik to some plugins that we seem to be maintaining. Please let me know if I'm mistaken and I'll remove you.

Some additions to CODEOWNERS

---

packages/image_picker/CHANGELOG.md
packages/image_picker/example/lib/main.dart
packages/image_picker/pubspec.yaml

Fixes the example app loading video error.
https://github.com/flutter/plugins/pull/1505#issuecomment-485220511

[image_picker] example app video load error fix.

---

packages/in_app_purchase/lib/src/billing_client_wrappers/README.md
packages/in_app_purchase/lib/src/in_app_purchase/README.md
packages/in_app_purchase/lib/src/in_app_purchase/in_app_purchase_connection.dart
packages/in_app_purchase/lib/src/in_app_purchase/purchase_details.dart
packages/in_app_purchase/lib/src/store_kit_wrappers/README.md

[in_app_purchase] Minor doc updates

---

packages/firebase_ml_vision/CHANGELOG.md
packages/firebase_ml_vision/README.md
packages/firebase_ml_vision/pubspec.yaml

Updates ML Vision README to match latest version
Fixes https://github.com/flutter/flutter/issues/22791#event-2286540171

[firebase_ml_vision] Update Firebase ML Vision documentation

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
packages/google_maps_flutter/pubspec.yaml

* fixes https://github.com/flutter/flutter/issues/31930

[google_maps_flutter] Android: update myLocationButton preference on map load

---

packages/in_app_purchase/README.md
packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/PaymentQueueTest.m
packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/Stubs.h
packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/Stubs.m
packages/in_app_purchase/example/ios/in_app_purchase_pluginTests/TranslatorTest.m
packages/in_app_purchase/ios/Classes/FIAObjectTranslator.h
packages/in_app_purchase/ios/Classes/FIAObjectTranslator.m
packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m
packages/in_app_purchase/lib/src/billing_client_wrappers/purchase_wrapper.g.dart
packages/in_app_purchase/lib/src/billing_client_wrappers/sku_details_wrapper.g.dart
packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.g.dart
packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_transaction_wrappers.g.dart
packages/in_app_purchase/lib/src/store_kit_wrappers/sk_product_wrapper.dart
packages/in_app_purchase/lib/src/store_kit_wrappers/sk_product_wrapper.g.dart
packages/in_app_purchase/test/store_kit_wrappers/sk_product_test.dart
packages/in_app_purchase/test/store_kit_wrappers/sk_test_stub_objects.dart

Not supporting downloads right now, but there's some dangling unit tests
and members that still reference them. Remove them and regenerate the
mapping classes. …

[in_app_purchase] Remove extraneous download logic

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/ios/cloud_firestore.podspec
packages/cloud_firestore/pubspec.yaml

May help fixing iOS compile errors "error: no known class method for selector 'fieldValueForDoubleIncrement:'"
Fixes flutter/flutter#32195

[cloud_firestore] Update CocoaPod versions dependency

---

packages/android_intent/CHANGELOG.md
packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/AndroidIntentPlugin.java
packages/android_intent/lib/android_intent.dart
packages/android_intent/pubspec.yaml

This change is necessary if you want to start a launcher activity for another APK.
Internal b/132161358

[android_intent] Add the component name to the intent.

---

packages/cloud_functions/CHANGELOG.md
packages/cloud_functions/ios/cloud_functions.podspec
packages/cloud_functions/pubspec.yaml

In flutter/plugins#1572 we updated Android dependencies to the latest release but we need to update the iOS dependencies to match.
Fixes flutter/flutter#32632

[cloud_functions] Update iOS dependencies to latest to match Android

---

packages/camera/CHANGELOG.md
packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java
packages/camera/pubspec.yaml

Fix bug preventing video recording

[camera] Fix bug preventing video recording with audio

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
packages/google_maps_flutter/example/lib/main.dart
packages/google_maps_flutter/example/lib/map_click.dart
packages/google_maps_flutter/ios/Classes/GoogleMapController.m
packages/google_maps_flutter/lib/src/controller.dart
packages/google_maps_flutter/lib/src/google_map.dart
packages/google_maps_flutter/pubspec.yaml

Adds long press / long click support to GoogleMap
None

[google_maps_flutter] Adds long press / long click support to GoogleMap

---

packages/cloud_functions/README.md

* Replace `call` with `getHttpsCallable` under Usage section in readme. 
- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x ] All existing and new tests are passing.
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [x ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x ] I read and followed the [Flutter Style Guide].
- [ x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x ] I signed the [CLA].
- [ x] I am willing to follow-up on review comments in …

 [cloud_functions]:Replace `call` with `getHttpsCallable` under Usage section in readme

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/example/lib/place_marker.dart
packages/google_maps_flutter/example/test_driver/google_maps.dart
packages/google_maps_flutter/pubspec.yaml

This updates the sample to adapt to the ImageStream listener API changes
in https://github.com/flutter/flutter/pull/32936
As we cannot use the new API before it makes it to stable I'm commenting
out the sample for now(if we update it now it won't compile on stable,
and if we leave it as is it breaks CI on master).
Tracking issue: https://github.com/flutter/flutter/issues/33438
[Flutter …

[google_maps_flutter] Update and comment out the 'set marker icon' sample.

---

packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java

[android_alarm_manager] Move method channel usage to the platform main thread

---

packages/connectivity/CHANGELOG.md
packages/connectivity/lib/connectivity.dart
packages/connectivity/pubspec.yaml

[connectivity]Adding missing type params.

---

packages/device_info/CHANGELOG.md
packages/device_info/example/pubspec.yaml
packages/device_info/lib/device_info.dart
packages/device_info/pubspec.yaml

Also bumped min flutter version to 1.5.0

[Device_info] Replace invokeMethod with invokeMapMethod and some refactoring around this change.

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/android/build.gradle
packages/cloud_firestore/android/src/main/AndroidManifest.xml
packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/FlutterFirebaseAppRegistrar.java
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/pubspec.yaml

Add ability for Firestore plugin to submit Flutter user agent: `flutter-firebase_cloud_firestore`

[cloud_firestore] Add user agent submission to Firestore plugin

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/FlutterFirebaseAppRegistrar.java
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/lib/src/firestore.dart
packages/cloud_firestore/lib/src/transaction.dart
packages/cloud_firestore/pubspec.yaml

[cloud_firestore]bump up flutter version to 1.5 and use invokeMapMethod instead of invokeMethod

---

packages/cloud_firestore/CHANGELOG.md
packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java
packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/FlutterFirebaseAppRegistrar.java
packages/cloud_firestore/example/test_driver/cloud_firestore.dart
packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m
packages/cloud_firestore/lib/cloud_firestore.dart
packages/cloud_firestore/lib/src/document_reference.dart
packages/cloud_firestore/lib/src/query.dart
packages/cloud_firestore/lib/src/source.dart
packages/cloud_firestore/pubspec.yaml
packages/cloud_firestore/test/cloud_firestore_test.dart

Added source support in order to get doc(s) from server / cache / both ( default).
https://github.com/flutter/flutter/issues/19078

[cloud_firestore] Added source support

---

packages/path_provider/CHANGELOG.md
packages/path_provider/ios/Classes/PathProviderPlugin.m
packages/path_provider/pubspec.yaml

For arm32, arm64 compatibility

[path_provider] Cast NSInteger to long

---

packages/firebase_crashlytics/test/firebase_crashlytics_test.dart

Fix [Cirrus](https://cirrus-ci.com/task/6033229551763456) breakage caused by Crashlytics test.

Fix firebase_crashlytics analyze errors

---

packages/firebase_auth/example/lib/register_page.dart
packages/firebase_auth/example/lib/signin_page.dart

Fix [Cirrus](https://cirrus-ci.com/task/6033229551763456) breakage caused by firebase_auth plugin.

Fix firebase_auth analyze issues

---

packages/local_auth/CHANGELOG.md
packages/local_auth/README.md
packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/AuthenticationHelper.java
packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java
packages/local_auth/example/android/build.gradle
packages/local_auth/example/android/gradle/wrapper/gradle-wrapper.properties
packages/local_auth/example/lib/main.dart
packages/local_auth/lib/error_codes.dart
packages/local_auth/pubspec.yaml

* Fixes crash on API<28 while invoking  `authenticateWithBiometrics` as previously used **getMainExecutor()** was not available for FragmentActivity for API<28.
* `authenticateWithBiometrics` used to return result also when incorrect Biometric ID was provided, due to which authentication status was not changing for incorrect tries followed by correct one. This issue is fixed by returning result only when Biometric Prompt is closed.
* Added two more exceptions `LockedOut` and `PermanentlyLockedOut` to detect API being locked out due to maximum incorrect attempts.
Does your PR require plugin users to manually update …

[local_auth] Fixed crash on API<28 while invoking authenticateWithBiometrics

---

packages/firebase_core/CHANGELOG.md
packages/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseAppRegistrar.java
packages/firebase_core/ios/Classes/FirebaseCorePlugin.m
packages/firebase_core/lib/src/firebase_app.dart
packages/firebase_core/pubspec.yaml

[firebase_core] replace invokeMethod with invokeMapMethod, add type parameters to invokeMethod calls,  bump min Flutter version to 1.5.0

---

AUTHORS
packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
packages/firebase_auth/pubspec.yaml

The updatePhoneNumberCredential on iOS was attempting to get the credentials from the call.arguments instead of the getCredential method and was crashing because the arguments weren't in the format expected. This PR gets the credential from the getCredential method instead of trying to access them directly in the call.arguments.
None
None …

[firebase_auth] Fix iOS updatePhoneNumberCredential crash

---

packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java

See https://github.com/flutter/plugins/pull/1641

[android_alarm_manager] Wait in onHandleWork until the Dart callback returns a result

---

packages/local_auth/CHANGELOG.md
packages/local_auth/lib/local_auth.dart
packages/local_auth/pubspec.yaml

[local_auth]Add missing template type parameter to `invokeMethod` calls. Bump minimum Flutter versi

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
packages/google_maps_flutter/example/assets/night_mode.json
packages/google_maps_flutter/example/lib/map_ui.dart
packages/google_maps_flutter/example/test_driver/google_maps.dart
packages/google_maps_flutter/ios/Classes/GoogleMapController.h
packages/google_maps_flutter/ios/Classes/GoogleMapController.m
packages/google_maps_flutter/lib/src/controller.dart
packages/google_maps_flutter/lib/src/ui.dart
packages/google_maps_flutter/pubspec.yaml

- supports both Android and iOS
- fixes: https://github.com/flutter/flutter/issues/24147

[google_maps_flutter] Add support for styling google maps

---

packages/location_background/CHANGELOG.md
packages/location_background/lib/location_background_plugin.dart
packages/location_background/pubspec.yaml

revert https://github.com/flutter/plugins/pull/1690

Revert "1690"

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/README.md
packages/firebase_auth/pubspec.yaml

[firebase_auth] Document support email requirement in README

---

packages/connectivity/CHANGELOG.md
packages/connectivity/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java
packages/connectivity/pubspec.yaml

- When Android has Mobile data and USB Tethering enabled,
getActiveNetworkInfo().getType() returns 5, which corresponds to
TYPE_MOBILE_HIPRI as per
https://developer.android.com/reference/android/net/ConnectivityManager.html#TYPE_MOBILE_HIPRI
- The plugin currently doesn't check this and defaults to none, while
the device has an active network connection.
- Check this case and return mobile to fix this.
Tests:
- Unit and Integration test passes
- (Manual) Enable mobile-data and USB Tethering and see if Flutter plugin
reports status correctly
Does your PR require plugin users to manually update their apps to …

[connectivity] android: Respect case TYPE_MOBILE_HIPRI

---

CONTRIBUTING.md

Add a note about mockito to contribution guide
Relates to flutter/flutter#34284

Add a note about mockito to contribution guide

---

packages/google_maps_flutter/example/android.iml
packages/google_maps_flutter/example/google_maps_flutter_example.iml
packages/google_maps_flutter/example/google_maps_flutter_example_android.iml
packages/google_maps_flutter/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_maps_flutter/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
packages/google_maps_flutter/example/ios/Runner.xcworkspace/contents.xcworkspacedata

Deleted some xcode and idea files in https://github.com/flutter/plugins/pull/1674, re-adding them

re-add deleted files

---

packages/firebase_ml_vision/example/test_driver/barcode_detector.dart
packages/firebase_ml_vision/example/test_driver/face_detector.dart
packages/firebase_ml_vision/example/test_driver/firebase_ml_vision.dart
packages/firebase_ml_vision/example/test_driver/image_labeler.dart
packages/firebase_ml_vision/example/test_driver/text_recognizer.dart

Separate integration tests by Detector. This is in preparation for writing extensive tests for this plugin. …

[firebase_ml_vision] Separate integration tests

---

README.md

Update link references from `flutter.io` and `pub.dartlang.org` to `flutter.dev` and `pub.dev`
This is a text-only change to update the site links to the new canonical references. 
[CLA]: …

[none] Update README.md

---

packages/local_auth/CHANGELOG.md
packages/local_auth/README.md
packages/local_auth/pubspec.yaml

No code change. README update to clarify what type of activity is required. Resolves https://github.com/flutter/flutter/issues/33429

Update README to reflect the requirement to use fragment activity

---

script/incremental_build.sh

Addresses https://github.com/flutter/flutter/issues/35412

re-enable version check

---

packages/android_intent/CHANGELOG.md
packages/android_intent/pubspec.yaml
packages/battery/CHANGELOG.md
packages/battery/android/gradle/wrapper/gradle-wrapper.properties
packages/battery/pubspec.yaml
packages/shared_preferences/CHANGELOG.md
packages/shared_preferences/android/gradle/wrapper/gradle-wrapper.properties
packages/shared_preferences/pubspec.yaml

Fixes errors:
```
Failed to apply plugin [id 'com.android.library']
> Minimum supported Gradle version is .... Current version is ... If using the gradle wrapper, try editing the distributionUrl in
```
This is required to build AARs via the new command I'm working on. …

[android_intent] [battery] [shared_preferences] Fix Gradle version

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/pubspec.yaml

Adding a CHANGELOG entry that was left out of #1826. TBR @cyanglaz

[firebase_auth] CHANGELOG entry and update pubspec.yaml for release

---

packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java

[webview_flutter] Fix typo

---

packages/shared_preferences/CHANGELOG.md
packages/shared_preferences/pubspec.yaml

goes with https://github.com/flutter/plugins/pull/1308

Update CHANGELOG and pubspec.yaml for release

---

packages/webview_flutter/ios/Classes/FlutterWebView.m

Didn't bump a version and update change as I haven't published the version where this typo was introduced yet.

[webview_flutter] fix typo in comment

---

.cirrus.yml

This also fetches master that will populate `FETCH_HEAD`
See https://github.com/flutter/plugins/pull/1864

[ci] Use the same upgrade script on Mac

---

CODEOWNERS
FlutterFire.md
README.md

Adds `firebase_in_app_messaging` plugin to the README.

[firebase_in_app_messaging] add firebase_in_app_messaging in README

---

packages/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/android/gradle/wrapper/gradle-wrapper.properties
packages/in_app_purchase/pubspec.yaml

[in_app_purchase] Use correct Gradle distribution

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/example/android/app/build.gradle
packages/firebase_auth/example/android/app/google-services.json
packages/firebase_auth/example/ios/Runner/GoogleService-Info.plist
packages/firebase_auth/example/pubspec.yaml
packages/firebase_auth/example/test/firebase_auth.dart
packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
packages/firebase_auth/lib/src/firebase_user.dart
packages/firebase_auth/pubspec.yaml

Adds integration testing
Fixes flutter/flutter#37160

[firebase_auth] Fixes for iOS auth crash on failed sign-in

---

packages/firebase_auth/CHANGELOG.md
packages/firebase_auth/README.md
packages/firebase_auth/pubspec.yaml

Updates the instructions to match the recently landed breaking change.
fixes flutter/flutter#37146

[firebase_auth] update README

---

.gitignore

"This is a generated file; do not edit or check into version control."

[all] Add new generated file to .gitignore

---

packages/webview_flutter/CHANGELOG.md
packages/webview_flutter/ios/Classes/FlutterWebView.m
packages/webview_flutter/pubspec.yaml

[webview_flutter] Remove noisy log messages on iOS

---

packages/webview_flutter/CHANGELOG.md
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
packages/webview_flutter/example/test_driver/webview.dart
packages/webview_flutter/ios/Classes/FlutterWebView.m
packages/webview_flutter/lib/platform_interface.dart
packages/webview_flutter/lib/src/webview_method_channel.dart
packages/webview_flutter/lib/webview_flutter.dart
packages/webview_flutter/pubspec.yaml

Allows inspecting the title of the currently loaded page.
https://github.com/flutter/flutter/issues/37177

[webview_flutter] Add a getTitle method to WebViewController

---

packages/image_picker/CHANGELOG.md
packages/image_picker/example/ios/image_picker_exampleTests/MetaDataUtilTests.m
packages/image_picker/example/ios/image_picker_exampleTests/PhotoAssetUtilTests.m
packages/image_picker/ios/Classes/FLTImagePickerImageUtil.m
packages/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.h
packages/image_picker/ios/Classes/FLTImagePickerMetaDataUtil.m
packages/image_picker/ios/Classes/FLTImagePickerPhotoAssetUtil.m
packages/image_picker/pubspec.yaml

1. On IOS, after scaling the image is wrongly rotated. It is due to the UIImage automatically rotated after scaling. In this PR, we always pre-set the orientation to be "up" so the scaling won't mess up with the pixels.
2. Also removed some code that is not required anymore.
3. Some trivial XCUnitTest code fix.
https://github.com/flutter/flutter/issues/37688 …

[image_picker] Image picker rotation fix on iOS after scaling.

---

packages/firebase_admob/CHANGELOG.md
packages/firebase_admob/README.md
packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/FirebaseAdMobPlugin.java
packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/MobileAd.java
packages/firebase_admob/example/lib/main.dart
packages/firebase_admob/ios/Classes/FLTMobileAd.h
packages/firebase_admob/ios/Classes/FLTMobileAd.m
packages/firebase_admob/ios/Classes/FirebaseAdMobPlugin.m
packages/firebase_admob/lib/firebase_admob.dart
packages/firebase_admob/pubspec.yaml
packages/firebase_admob/test/firebase_admob_test.dart

Adding the ability to horizontally adjust the ads banner location by specifying an offset from the centre.
* This PR allows the user of firebase_admob to specify an offset in pixels from the horizontal centre of the banner using 
- horizontalCenterOffset
The current behaviour allows the user only to specify an anchor top or bottom with an offset from the anchor. But it doesn't allow an offset from the horizontal centre. This PR will add that ability.
The motivation behind the change is to support split screen layout for tablets where ads banner could reside on one side of the screen.
Does your PR require plugin users …

[firebase_admob] Banner Ad Horizontal Positioning

---

packages/video_player/CHANGELOG.md
packages/video_player/example/lib/main.dart
packages/video_player/pubspec.yaml

Fixes build failure:
https://cirrus-ci.com/task/5368564837515264
info - 'ButtonTheme.bar' is deprecated and shouldn't be used at example/lib/main.dart:249:9 - (deprecated_member_use)

[video_player] Fix deprecated member use

---

packages/sensors/test/sensors_test.dart

#2005 updated unit tests for most plugins to fix a breaking change but one plugin wasn't included.

Fix unit test for sensors

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/example/lib/padding.dart
packages/google_maps_flutter/pubspec.yaml

Not sure why this is just starting to happen now but it's causing the tests to fail.

[google_maps_flutter] Fix analyzer failures relating to prefer_const_constructors

---

packages/instrumentation_adapter/CHANGELOG.md
packages/instrumentation_adapter/example/android/gradle.properties
packages/instrumentation_adapter/pubspec.yaml

Migrate the example app to AndroidX
Log: https://api.cirrus-ci.com/v1/task/5954826887757824/logs/main.log

[instrumentation_adapter] Migrate example to AndroidX

---

packages/in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart

Formatting was failing:
```
These files are not formatted correctly (see diff below):
in_app_purchase/lib/src/billing_client_wrappers/billing_client_wrapper.dart
To fix run "pub global activate flutter_plugin_tools && pub global run flutter_plugin_tools format" or copy-paste this command into your terminal:
```
Update dart and run `pub global run flutter_plugin_tools format`

Run flutter_plugin_tools format

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
packages/google_maps_flutter/example/android/build.gradle
packages/google_maps_flutter/example/android/gradle.properties
packages/google_maps_flutter/example/android/gradle/wrapper/gradle-wrapper.properties
packages/google_maps_flutter/example/test_driver/google_maps.dart
packages/google_maps_flutter/pubspec.yaml

Override a default method to work around flutter/flutter#40126. The root
cause of the issue has already been fixed in master and there is a
potential workaround available to apps already, but this is an extra
low-risk change that should prevent the crash for any affected users
while the fix is still rolling out to stable.
flutter/flutter#40126 …

[google_maps_flutter] Avoid AbstractMethod crash

---

.ci/Dockerfile

Plus force rebuilding if the image

Use stable Flutter image as base

---

packages/android_intent/example/pubspec.yaml
packages/android_intent/pubspec.yaml

The previous minimum was too low to support the V2 embedding at compile
time. 
flutter/flutter#41831

[android_intent] Bump the Flutter SDK min version

---

packages/battery/example/pubspec.yaml
packages/battery/pubspec.yaml

This is needed as the e2e test is using package e2e.
@collinjackson as e2e tests that live under `tests/` are actually running as part of the example app their dependencies need to be specified in `example/pubspec.yaml`. Additionally to keep the analyzer happy these dependencies also need to be specified in the root `pubspec.yaml`.
Do we like this folder structure?
- x ] No, this is *not* a breaking change. …

[battery] add e2e dependency to the example app

---

.cirrus.yml

This reverts commit c155379d137603821410a0851ff691713b5ba38b.
Does your PR require plugin users to manually update their apps to accommodate your …

Revert "Enable testing on both master and stable (#2197)"

---

packages/flutter_plugin_android_lifecycle/README.md

[flutter_plugin_android_lifecycle] Update README with new plugin name

---

packages/url_launcher/url_launcher/CHANGELOG.md
packages/url_launcher/url_launcher/android/build.gradle
packages/url_launcher/url_launcher/android/src/main/AndroidManifest.xml
packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/MethodCallHandlerImpl.java
packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncher.java
packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java
packages/url_launcher/url_launcher/android/src/test/java/io/flutter/plugins/urllauncher/MethodCallHandlerImplTest.java
packages/url_launcher/url_launcher/example/android/app/build.gradle
packages/url_launcher/url_launcher/example/android/app/src/androidTestDebug/java/io/flutter/plugins/urllauncherexample/EmbeddingV1ActivityTest.java
packages/url_launcher/url_launcher/example/android/app/src/androidTestDebug/java/io/flutter/plugins/urllauncherexample/MainActivityTest.java
packages/url_launcher/url_launcher/example/android/app/src/main/AndroidManifest.xml
packages/url_launcher/url_launcher/example/android/app/src/main/java/io/flutter/plugins/urllauncherexample/EmbeddingV1Activity.java
packages/url_launcher/url_launcher/example/android/app/src/main/java/io/flutter/plugins/urllauncherexample/MainActivity.java
packages/url_launcher/url_launcher/example/android/gradle.properties
packages/url_launcher/url_launcher/example/pubspec.yaml
packages/url_launcher/url_launcher/example/test_driver/url_launcher_e2e.dart
packages/url_launcher/url_launcher/example/test_driver/url_launcher_e2e_test.dart
packages/url_launcher/url_launcher/pubspec.yaml

This is identical to the original PR, except it correctly increments the Flutter SDK version to the latest stable and fixes some minor Java style nits.
Fixes flutter/flutter#41849

[url_launcher] Re-land v2 embedding support

---

.cirrus.yml
packages/package_info/example/android/app/gradle.properties

CI needs to use the latest stable version for testing on iOS

Ensure that when testing on stable Cirrus is upgraded to latest on iOS

---

packages/battery/CHANGELOG.md
packages/battery/android/build.gradle
packages/battery/pubspec.yaml

Android: Use android.arch.lifecycle instead of androidx.lifecycle:lifecycle in `build.gradle` to support apps that has not been migrated to AndroidX. …

[battery]Use android.arch.lifecycle instead of androidx.lifecycle:lifecycle in

---

packages/camera/CHANGELOG.md
packages/camera/android/build.gradle
packages/camera/android/gradle.properties
packages/camera/pubspec.yaml

Android: Use android.arch.lifecycle instead of androidx.lifecycle:lifecycle in build.gradle to support apps that has not been migrated to AndroidX. …

[camera]remove androidx constraint

---

packages/url_launcher/url_launcher/CHANGELOG.md
packages/url_launcher/url_launcher/android/build.gradle
packages/url_launcher/url_launcher/android/gradle.properties
packages/url_launcher/url_launcher/pubspec.yaml

We introduced a constraint that the app uses the plugin has to be migrated to androidx.
This patch removes the constraint. …

[url_launcher]remove AndroidX constraint

---

packages/e2e/CHANGELOG.md
packages/e2e/README.md
packages/e2e/pubspec.yaml

Updates README with some documentation updates.

[e2e] update README

---

packages/flutter_plugin_android_lifecycle/CHANGELOG.md
packages/flutter_plugin_android_lifecycle/README.md
packages/flutter_plugin_android_lifecycle/android/src/main/java/io/flutter/embedding/engine/plugins/lifecycle/FlutterLifecycleAdapter.java
packages/flutter_plugin_android_lifecycle/example/android/app/src/main/java/io/flutter/plugins/flutter_plugin_android_lifecycle_example/MainActivity.java
packages/flutter_plugin_android_lifecycle/pubspec.yaml

Adapt's the plugin to the changes made in https://github.com/flutter/engine/pull/13280 and https://github.com/flutter/engine/pull/13402.
This only provides an accessor for the activity lifecycle and is one for the service lifecycle as I'm trying to land it fast to fix CI.   https://github.com/flutter/flutter/issues/43741 tracks adding the service lifecycle getter (it's trivial to add, but testing is not completely trivial). …

[flutter_plugin_android_lifecycle] Adapt the FlutterLifecycleAdapter to the new embedding API

---

packages/connectivity/connectivity_macos/README.md
packages/connectivity/connectivity_macos/pubspec.yaml

Fix according to `flutter pub publish --dry-run` feedback
- [] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [] All existing and new tests are passing.
- [] I updated CHANGELOG.md to add a description of the change.

[connecitivity_macos] Fix warnings to publish

---

packages/path_provider/path_provider_macos/README.md
packages/path_provider/path_provider_macos/pubspec.yaml

Fix according to `flutter pub publish --dry-run` feedback
- [] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [] All existing and new tests are passing.
- [] I updated CHANGELOG.md to add a description of the change.

[path_provider_macos] Fix publish warnings

---

packages/shared_preferences/shared_preferences_web/CHANGELOG.md
packages/shared_preferences/shared_preferences_web/ios/shared_preferences_web.podspec
packages/shared_preferences/shared_preferences_web/pubspec.yaml

Prepare `shared_preferences_web` to be endorsed by `shared_preferences`.

[shared_preferences_web] Prepare to be endorsed

---

packages/google_sign_in/google_sign_in_web/CHANGELOG.md
packages/google_sign_in/google_sign_in_web/pubspec.yaml

Prepares `google_sign_in_web` to be the endorsed implementation.

[google_sign_in_web] Prepare for endorsement.

---

packages/url_launcher/url_launcher/pubspec.yaml
script/build_all_plugins_app.sh
script/check_publish.sh

Follow-up to https://github.com/flutter/plugins/pull/2399 removing the dependency override.

[url_launcher] remove temporary dependency override

---

packages/video_player/video_player_web/CHANGELOG.md
packages/video_player/video_player_web/android/.gitignore
packages/video_player/video_player_web/android/build.gradle
packages/video_player/video_player_web/android/gradle.properties
packages/video_player/video_player_web/android/gradle/wrapper/gradle-wrapper.properties
packages/video_player/video_player_web/android/settings.gradle
packages/video_player/video_player_web/android/src/main/AndroidManifest.xml
packages/video_player/video_player_web/android/src/main/java/io/flutter/plugins/video_player_web/VideoPlayerWebPlugin.java
packages/video_player/video_player_web/pubspec.yaml

Adding an `android/` folder as a temporary mitigation for:
https://github.com/flutter/flutter/issues/46304
https://github.com/flutter/flutter/issues/46790
https://github.com/flutter/flutter/issues/46898

[video_player_web] add a no-op android folder

---

packages/url_launcher/url_launcher_macos/CHANGELOG.md
packages/url_launcher/url_launcher_macos/android/gradle/wrapper/gradle-wrapper.properties
packages/url_launcher/url_launcher_macos/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/47751

Update Gradle version

---

packages/espresso/CHANGELOG.md
packages/espresso/README.md
packages/espresso/pubspec.yaml

Updates documentation to reflect some learnings from getting the shared_preferences test up in https://github.com/flutter/plugins/pull/2460

Updates to espresso docs

---

packages/flutter_plugin_android_lifecycle/CHANGELOG.md
packages/flutter_plugin_android_lifecycle/android/build.gradle
packages/flutter_plugin_android_lifecycle/android/src/main/java/io/flutter/embedding/engine/plugins/lifecycle/FlutterLifecycleAdapter.java
packages/flutter_plugin_android_lifecycle/android/src/test/java/io/flutter/embedding/engine/plugins/lifecycle/FlutterLifecycleAdapterTest.java
packages/flutter_plugin_android_lifecycle/pubspec.yaml

The reflection was added to make the plugin compatible with previous
versions of Flutter. Now that the latest stable has updated we can
update the code to be safer and avoid potential issues with code
shrinking in release builds.
Also removes a Gradle workaround that was only required for pre 1.12
versions of Flutter.
Fixes https://github.com/flutter/flutter/issues/48622.
https://github.com/flutter/flutter/issues/42348 …

[flutter_plugin_android_lifecycle] Stop reflecting

---

packages/in_app_purchase/example/lib/main.dart

This triggers an analysis warning that makes CI red.

[in_app_purchase] Remove unused method from example app

---

packages/sensors/CHANGELOG.md
packages/sensors/README.md
packages/sensors/pubspec.yaml

Update readme to fix typo in example for user accelerometer event
Update readme to fix typo in example for user accelerometer event
none

[sensors] Update readme documentation

---

packages/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/lib/src/location.dart
packages/google_maps_flutter/pubspec.yaml

Trivial change to documentation on LatLngBounds. Fixing typo.

[google_maps_flutter] Fixed typo in LatLngBounds constructor

---

packages/shared_preferences/shared_preferences/CHANGELOG.md
packages/shared_preferences/shared_preferences/README.md
packages/shared_preferences/shared_preferences/pubspec.yaml

There's a typo in the main readme file. I fixed it.
Not sure if I should update version and changelog, as this is not code related.
None

[shared_preferences] fix typo in readme

---

packages/google_sign_in/google_sign_in_web/CHANGELOG.md
packages/google_sign_in/google_sign_in_web/README.md
packages/google_sign_in/google_sign_in_web/pubspec.yaml

* Add information about the "Authorized JavaScript origins", and how to
set them up in the Google APIs console.
Fixes https://github.com/flutter/flutter/issues/49539

[google_sign_in_web] Add more detailed setup instructions.

---

packages/connectivity/connectivity_platform_interface/CHANGELOG.md
packages/connectivity/connectivity_platform_interface/LICENSE
packages/connectivity/connectivity_platform_interface/README.md
packages/connectivity/connectivity_platform_interface/lib/connectivity_platform_interface.dart
packages/connectivity/connectivity_platform_interface/lib/method_channel_connectivity.dart
packages/connectivity/connectivity_platform_interface/pubspec.yaml
packages/connectivity/connectivity_platform_interface/test/method_channel_connectivity_test.dart

Adds a platform interface to `Connectivity` to set it up for Federation.
Part of https://github.com/flutter/flutter/issues/46307

[Connectivity] Adds platform interface to connectivity plugin

---

packages/in_app_purchase/pubspec.yaml

I didn't update the in_app_purchase plugin version properly in https://github.com/flutter/plugins/pull/2509. This PR is to fix the version.

[in_app_purchase] Fix version.

---

packages/e2e/CHANGELOG.md
packages/e2e/lib/_extension_io.dart
packages/e2e/lib/_extension_web.dart
packages/e2e/lib/e2e.dart
packages/e2e/pubspec.yaml

In order to use different e2e package for Flutter Web engine integration tests we need to add some
web specific parts to the code. These can be found here as a demo: [PR](https://github.com/flutter/flutter/pull/49833)
In this particular change we are registering flutter driver commands to the browser. They will be accessed as window.$flutter_command
https://github.com/flutter/flutter/issues/50212 …

[e2e] e2e web changes part1: registering web extension.

---

packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java

fix break on switch

---

.gitignore

Adds Flutter/ephemeral and GeneratedPluginRegistrant.swift to gitignore

Updates gitignore with unwanted macos files

---

packages/flutter_plugin_android_lifecycle/CHANGELOG.md
packages/flutter_plugin_android_lifecycle/android/gradle/wrapper/gradle-wrapper.properties
packages/flutter_plugin_android_lifecycle/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/48724

[flutter-plugin-android-lifecycle] Update Gradle version

---

packages/connectivity/connectivity_platform_interface/CHANGELOG.md
packages/connectivity/connectivity_platform_interface/lib/src/enums.dart
packages/connectivity/connectivity_platform_interface/lib/src/utils.dart
packages/connectivity/connectivity_platform_interface/pubspec.yaml

Revert "[connectivity_platform_interface] Add `ConnectivityResult.unknown`."

---

packages/share/CHANGELOG.md
packages/share/example/android/gradle/wrapper/gradle-wrapper.properties
packages/share/pubspec.yaml

[share] plugin: Update gradle version of example for Android
Fixes [TAG] Warnings and errors caused as generated on Android Studio build terminal while buidling.

[share] plugin: Update gradle version of example for Android

---

packages/google_sign_in/google_sign_in/CHANGELOG.md
packages/google_sign_in/google_sign_in/ios/Classes/FLTGoogleSignInPlugin.m
packages/google_sign_in/google_sign_in/pubspec.yaml

Removed unused variable introduced by #2127.

[google_sign_in] Remove unused variable

---

packages/google_maps_flutter/google_maps_flutter/pubspec.yaml

Fix the version discrepancy in pubspec.

[google_map_flutter] fix google map version in pubspec.

---

packages/image_picker/CHANGELOG.md
packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java
packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java
packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java
packages/image_picker/example/lib/main.dart
packages/image_picker/ios/Classes/FLTImagePickerPlugin.h
packages/image_picker/ios/Classes/FLTImagePickerPlugin.m
packages/image_picker/ios/Tests/ImagePickerPluginTests.m
packages/image_picker/lib/image_picker.dart
packages/image_picker/pubspec.yaml
packages/image_picker/test/image_picker_test.dart

Add a new feature to let user select preferred camera device.
https://github.com/flutter/flutter/issues/24880

[image_picker] Image picker select preferred camera device (rear, front)

---

packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/pubspec.yaml

bump the version and the CHANGELOG in order
flutter/flutter#55340

[video_player] Update version and changelog

---

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java
packages/google_maps_flutter/google_maps_flutter/pubspec.yaml

Map plugins crashes when exiting app while using the `FragmentActivity`. 
We are calling `MapView.onDestroy` at an inappropriate location which caused sone undefined behavior. `MapView.onDestroy` should only be called in the corresponding `onDestroy` method in from the activity or fragment. According to https://developers.google.com/android/reference/com/google/android/gms/maps/MapView#onDestroy%28%29 "You must call this method from the parent Activity/Fragment's corresponding method."
Also added some house keeping code to remove all the listeners when disposing. 
Fixes https://github.com/flutter/flutter/issues/55406 …

[google_maps_flutter] fix crash and remove listeners

---

packages/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/ios/Classes/FIAPaymentQueueHandler.h
packages/in_app_purchase/ios/Classes/FIAPaymentQueueHandler.m
packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m
packages/in_app_purchase/ios/Tests/InAppPurchasePluginTest.m
packages/in_app_purchase/ios/in_app_purchase.podspec
packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart
packages/in_app_purchase/pubspec.yaml
packages/in_app_purchase/test/store_kit_wrappers/sk_methodchannel_apis_test.dart

I have seen users wanting this method to be exposed here https://github.com/flutter/flutter/issues/45425#issuecomment-570057858 which I think makes sense.
https://github.com/flutter/flutter/issues/45425
[CLA]: …

[in_app_purchase] Expose SKPaymentQueue.transactions to dart

---

.cirrus.yml

Pin image version. Plus don't specify simulator explicitly and use the default one.

[ci] Use Xcode 11.3.1

---

packages/url_launcher/url_launcher/example/macos/Flutter/ephemeral/Flutter-Generated.xcconfig

Nothing in macos/Flutter/ephemeral should be checked in; somehow this
file was included by accident.
None

[url_launcher] Remove an ephemeral file from macOS example

---

packages/image_picker/image_picker_platform_interface/CHANGELOG.md
packages/image_picker/image_picker_platform_interface/LICENSE
packages/image_picker/image_picker_platform_interface/README.md
packages/image_picker/image_picker_platform_interface/lib/image_picker_platform_interface.dart
packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart
packages/image_picker/image_picker_platform_interface/lib/src/platform_interface/image_picker_platform.dart
packages/image_picker/image_picker_platform_interface/lib/src/types/camera_device.dart
packages/image_picker/image_picker_platform_interface/lib/src/types/image_source.dart
packages/image_picker/image_picker_platform_interface/lib/src/types/lost_data_response.dart
packages/image_picker/image_picker_platform_interface/lib/src/types/retrieve_type.dart
packages/image_picker/image_picker_platform_interface/lib/src/types/types.dart
packages/image_picker/image_picker_platform_interface/pubspec.yaml
packages/image_picker/image_picker_platform_interface/test/method_channel_image_picker_test.dart
script/build_all_plugins_app.sh

This PR adds the image_picker_platform_interface package with the current API used by the plugin.
* Part of: https://github.com/flutter/flutter/issues/36281

[image_picker_platform_interface] Create image_picker_platform_interface package.

---

packages/url_launcher/url_launcher_web/CHANGELOG.md
packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart
packages/url_launcher/url_launcher_web/pubspec.yaml
packages/url_launcher/url_launcher_web/test/url_launcher_web_test.dart

Unit tests in this package have been reported as "flaky" by our internal tools.
This change should make tests less flaky, by mocking (and not relying in) actual browser behavior.
n/a
[CLA]: …

[url_launcher_web] Refactor unit tests to reduce flakiness.

---

packages/image_picker/image_picker/CHANGELOG.md
packages/image_picker/image_picker/lib/image_picker.dart
packages/image_picker/image_picker/pubspec.yaml

This PR migrates the implementation of the plugin to use the platform API defined in the `platform_interface` package, and removes all the duplicate code that now lives in said package.
* Part of: https://github.com/flutter/flutter/issues/36281 …

[image_picker] Port core plugin to platform_interface APIs.

---

packages/video_player/video_player_platform_interface/CHANGELOG.md
packages/video_player/video_player_platform_interface/lib/messages.dart
packages/video_player/video_player_platform_interface/pubspec.yaml

In order for https://github.com/flutter/plugins/pull/2544 to land; extra testing classes need to be made available.

[video_player]: added test class to fix video_player unit tests

---

packages/e2e/README.md

Typo in e2e README.md

---

.ci/Dockerfile-LinuxDesktop

Updates the set of packages installed on the Linux desktop Docker image to account for the switch to CMake:
- Adds the `file` utility, which is used by the CMake bundling step. The previous set of tools was intended to support both the old Make build and the new CMake build, but this missing tool broke the CMake-based build.
- Remove `make` and `rsync` now that the transition has happened and they are no longer used.
https://github.com/flutter/flutter/issues/52751 …

Update Linux desktop Dockerfile for CMake switch

---

packages/webview_flutter/CHANGELOG.md
packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart
packages/webview_flutter/pubspec.yaml

This is an attempt to fix https://github.com/flutter/flutter/issues/57041
We suspect the padding gotten programmatically might affect the size of the web view in some devices. 
We are not certain this will fix the flake as we have been able to reproduce the flakes locally; however, this is a harmless change if the tests are still passing at the same success rate.
https://github.com/flutter/flutter/issues/57041 …

[webview_flutter] use hard coded values in `setAndGetScrollPosition` test

---

packages/camera/CHANGELOG.md
packages/camera/README.md
packages/camera/pubspec.yaml

Make the example actually runable by ensuring that flutter widget bindings are initialized. The current version fails on startup.

[camera] Fix bug in example

---

.ci/Dockerfile-LinuxDesktop

Once the switch to GTK lands, libgtk-3-dev will be needed for building.
Part of https://github.com/flutter/flutter/issues/54860

Update Linux desktop Dockerfile for GTK switch

---

packages/e2e/pubspec.yaml

[e2e] Bump version to 0.6.0

---

packages/url_launcher/url_launcher_web/CHANGELOG.md
packages/url_launcher/url_launcher_web/README.md
packages/url_launcher/url_launcher_web/pubspec.yaml

fixed url_launcher link in url_launcher_web README. It was being sent to 404 not found
Fixes https://github.com/flutter/flutter/issues/57819

fixed url_launcher link in url_launcher_web README 

---

packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/Messages.java
packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerOptions.java
packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
packages/video_player/video_player/example/lib/main.dart
packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m
packages/video_player/video_player/ios/Classes/messages.h
packages/video_player/video_player/ios/Classes/messages.m
packages/video_player/video_player/lib/video_player.dart
packages/video_player/video_player/pigeons/messages.dart
packages/video_player/video_player/pubspec.yaml
packages/video_player/video_player/test/video_player_test.dart

This reverts commit 77fbfcd801f7717b681c9b9981bd31c2ce10a2c4.
The original PR made CI timed out on post submit https://cirrus-ci.com/task/6297593099583488?command=main#L88

Revert "[video_player] Set audio mix options (#2922)"

---

CODEOWNERS

- Remove myself from code owner as I'm not actively working on it.
- Add @dnfield .
N/A

[e2e] Update code onwer.

---

packages/battery/CHANGELOG.md
packages/battery/README.md
packages/battery/pubspec.yaml
packages/integration_test/lib/integration_test.dart

https://github.com/flutter/plugins/commit/6eda8db6516ac89551450db9483ff88471f95779 accidentally removed some commits on head, so relanding them here:
- [battery] Fixed typo in README.md (#2944)
- [integration_test] Remove debugging statement (#2963)

Rebase previous commits

---

packages/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/ios/Classes/InAppPurchasePlugin.m
packages/in_app_purchase/ios/Tests/InAppPurchasePluginTest.m
packages/in_app_purchase/pubspec.yaml

Fixes https://github.com/flutter/flutter/issues/62779

[in_app_purchase] Fix typo on `simulatesAskToBuyInSandBox`

---

packages/shared_preferences/shared_preferences/CHANGELOG.md
packages/shared_preferences/shared_preferences/lib/shared_preferences.dart
packages/shared_preferences/shared_preferences/pubspec.yaml

Adds endorsement, and manual registration, of
shared_preferences_windows.
Fixes flutter/flutter#41719

[shared_preferences] Endorse Windows

---

packages/url_launcher/url_launcher_web/CHANGELOG.md
packages/url_launcher/url_launcher_web/LICENSE
packages/url_launcher/url_launcher_web/lib/third_party/platform_detect/LICENSE
packages/url_launcher/url_launcher_web/lib/third_party/platform_detect/README.md
packages/url_launcher/url_launcher_web/lib/third_party/platform_detect/browser.dart
packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart
packages/url_launcher/url_launcher_web/pubspec.yaml

This PR improves the attribution of package:platform_detect's code in this package.

[url_launcher_web] Improve attribution of package:platform_detect

---

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter/README.md
packages/google_maps_flutter/google_maps_flutter/pubspec.yaml

Webview took most of the energy

Remove `io.flutter.embedded_views_preview` from README

---

packages/webview_flutter/CHANGELOG.md
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/InputAwareWebView.java
packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewFlutterPlugin.java
packages/webview_flutter/pubspec.yaml

- Handle deprecation & unchecked warning as error
- Avoiding uses or overrides a deprecated API
- Avoiding uses unchecked or unsafe Object Type Casting
flutter/flutter#65970

[webview_flutter] Android Code Inspection and Clean up

---

packages/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/android/src/main/java/io/flutter/plugins/inapppurchase/MethodCallHandlerImpl.java
packages/in_app_purchase/pubspec.yaml

- Avoiding uses unchecked or unsafe Object Type Casting
flutter/flutter#65970

[in_app_purchase] Android Code Inspection and Clean up

---

packages/android_alarm_manager/example/README.md
packages/android_intent/example/README.md
packages/battery/battery/example/README.md
packages/device_info/device_info/example/README.md
packages/google_maps_flutter/google_maps_flutter/example/README.md
packages/google_sign_in/google_sign_in/example/README.md
packages/image_picker/image_picker/example/README.md
packages/local_auth/example/README.md
packages/package_info/example/README.md
packages/path_provider/path_provider/example/README.md
packages/path_provider/path_provider_macos/example/README.md
packages/path_provider/path_provider_windows/example/README.md
packages/quick_actions/example/README.md
packages/sensors/example/README.md
packages/share/example/README.md
packages/shared_preferences/shared_preferences/example/README.md
packages/shared_preferences/shared_preferences_linux/example/README.md
packages/shared_preferences/shared_preferences_macos/example/README.md
packages/url_launcher/url_launcher/example/README.md
packages/url_launcher/url_launcher_macos/example/README.md
packages/video_player/video_player/example/README.md
packages/webview_flutter/example/README.md

Fix links in package example readmes

---

packages/google_sign_in/google_sign_in/CHANGELOG.md

Fix a merge mistake in https://github.com/flutter/plugins/pull/3042/files?file-filters%5B%5D=.md where the CHANGELOG message was erased.

[google_sign_in] Fix merge mistake.

---

packages/webview_flutter/CHANGELOG.md
packages/webview_flutter/README.md
packages/webview_flutter/pubspec.yaml

I tried using the snippet, and realized that it's wrong...

[webview_flutter] Fix example in readme

---

packages/wifi_info_flutter/wifi_info_flutter/pubspec.yaml
packages/wifi_info_flutter/wifi_info_flutter_platform_interface/CHANGELOG.md
packages/wifi_info_flutter/wifi_info_flutter_platform_interface/pubspec.yaml

Make the plugins ready to be published

[wifi_info_flutter_platform_interface] Ready to publish

---

packages/integration_test/CHANGELOG.md
packages/integration_test/pubspec.yaml

broaden the constraint on package:vm_service

---

packages/image_picker/image_picker/CHANGELOG.md
packages/image_picker/image_picker/lib/image_picker.dart
packages/image_picker/image_picker/pubspec.yaml
packages/image_picker/image_picker_platform_interface/CHANGELOG.md
packages/image_picker/image_picker_platform_interface/lib/src/platform_interface/image_picker_platform.dart
packages/image_picker/image_picker_platform_interface/pubspec.yaml

Updated the documentation to explain when HEIC images are supported on which operating systems.
[Issue 25741](https://github.com/flutter/flutter/issues/25741)

[image_picker] Update documentation to include information about support HEIC images.

---

packages/device_info/device_info/CHANGELOG.md
packages/device_info/device_info/README.md
packages/device_info/device_info/pubspec.yaml
packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/README.md
packages/video_player/video_player/pubspec.yaml

Announce 1.0 release for video_player and device_info

[video_player][device_info] announce 1.0

---

packages/image_picker/image_picker/CHANGELOG.md
packages/image_picker/image_picker/pubspec.yaml
packages/image_picker/image_picker_for_web/CHANGELOG.md
packages/image_picker/image_picker_for_web/pubspec.yaml
packages/image_picker/image_picker_platform_interface/CHANGELOG.md
packages/image_picker/image_picker_platform_interface/pubspec.yaml
packages/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/pubspec.yaml
packages/integration_test/CHANGELOG.md
packages/integration_test/pubspec.yaml
packages/ios_platform_images/CHANGELOG.md
packages/ios_platform_images/pubspec.yaml
packages/local_auth/CHANGELOG.md
packages/local_auth/pubspec.yaml
packages/package_info/CHANGELOG.md
packages/package_info/pubspec.yaml
packages/path_provider/path_provider/CHANGELOG.md
packages/path_provider/path_provider/pubspec.yaml
packages/path_provider/path_provider_linux/CHANGELOG.md
packages/path_provider/path_provider_linux/pubspec.yaml
packages/path_provider/path_provider_macos/CHANGELOG.md
packages/path_provider/path_provider_macos/pubspec.yaml
packages/path_provider/path_provider_platform_interface/CHANGELOG.md
packages/path_provider/path_provider_platform_interface/pubspec.yaml
packages/path_provider/path_provider_windows/CHANGELOG.md
packages/path_provider/path_provider_windows/pubspec.yaml

Align plugins with new templates, removing unused upper constraint
https://github.com/flutter/flutter/pull/68437

Update Flutter SDK constraint to match templates; plugins I-P

---

packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/pubspec.yaml
packages/video_player/video_player/test/video_player_test.dart

[video_player] Fix video player test

---

packages/image_picker/image_picker/pubspec.yaml

Fix version mismatch introduced in https://github.com/flutter/plugins/commit/a7dd76950e5b240d2d878504a6f010ef24717e34

[image_picker] fix version

---

packages/camera/camera/CHANGELOG.md
packages/camera/camera/pubspec.yaml

Combine release messages and versions for below commits:
https://github.com/flutter/plugins/commit/100c7470d4066b1d0f8f7e4ec6d7c943e736f970
https://github.com/flutter/plugins/commit/71a831790220f898bf8120c8a23840ac6e742db5
https://github.com/flutter/plugins/commit/da1b4638b750a5ff832d7be86a42831c42c6d6c0
https://github.com/flutter/plugins/commit/831344490984b1feec007afc9c8595d80b6c13f4
https://github.com/flutter/plugins/commit/5916f55664e1772a4c3f0c02c5c71fc11e491b76
https://github.com/flutter/plugins/commit/980b674cb4020c1927917426211a87e275346d5e
https://github.com/flutter/plugins/commit/d0b7109f6b00a0eda03506fed2c74cc123ffc6f3
https://github.com/flutter/plugins/commit/6d18db83f00f4861ffe485aba2d1f8aa08845ce6

[camera] combine release messages and versions

---

.cirrus.yml
packages/image_picker/image_picker/CHANGELOG.md
packages/image_picker/image_picker/example/ios/RunnerUITests/ImagePickerFromGalleryUITests.m
packages/image_picker/image_picker/pubspec.yaml

Reverts flutter/plugins#3304
@jmagman @fkorotkov Looks like the post submit was failing, revert and I'll further investigate.

Revert "[ci][image_picker]enable xcode 12/iOS 14 for all tasks except lint"

---

packages/path_provider/path_provider/CHANGELOG.md
packages/path_provider/path_provider/pubspec.yaml

Needed for https://github.com/flutter/flutter/pull/74671

[path_provider] drop uuid

---

packages/cross_file/CHANGELOG.md
packages/cross_file/lib/src/types/base.dart
packages/cross_file/lib/src/types/html.dart
packages/cross_file/lib/src/types/interface.dart
packages/cross_file/lib/src/types/io.dart
packages/cross_file/lib/src/web_helpers/web_helpers.dart
packages/cross_file/pubspec.yaml
packages/cross_file/test/x_file_html_test.dart
packages/cross_file/test/x_file_io_test.dart
script/build_all_plugins_app.sh
script/nnbd_plugins.sh

This reverts commit 4aacf970f3891c9cf23c768ca1c8bec04c42b35a.
Reverting the change didn't do anything for the CI, so this PR relands the change that was previously removed.

Reland "[cross_file] Migrate to null-safety. (#3452)"

---

packages/url_launcher/url_launcher/CHANGELOG.md
packages/url_launcher/url_launcher/README.md
packages/url_launcher/url_launcher/pubspec.yaml

Correct statement in description about which platforms url_launcher supports

[url_launcher] Update description in pubspec.yaml

---

README.md

Makes it easier for people to find related issues.

Add plugin issue query to README

---

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter/pubspec.yaml

Version wasn't updated in https://github.com/flutter/plugins/pull/3434

[google_maps_flutter] fix version

---

packages/android_alarm_manager/example/pubspec.yaml
packages/android_intent/example/pubspec.yaml
packages/battery/battery/example/pubspec.yaml
packages/camera/camera/example/pubspec.yaml
packages/connectivity/connectivity/example/pubspec.yaml
packages/connectivity/connectivity_macos/example/pubspec.yaml
packages/device_info/device_info/example/pubspec.yaml
packages/google_maps_flutter/google_maps_flutter/example/pubspec.yaml
packages/google_sign_in/extension_google_sign_in_as_googleapis_auth/example/pubspec.yaml
packages/google_sign_in/google_sign_in/example/pubspec.yaml
packages/image_picker/image_picker/example/pubspec.yaml
packages/in_app_purchase/example/pubspec.yaml
packages/integration_test/example/pubspec.yaml
packages/local_auth/example/pubspec.yaml
packages/package_info/example/pubspec.yaml
packages/path_provider/path_provider/example/pubspec.yaml
packages/path_provider/path_provider_macos/example/pubspec.yaml
packages/path_provider/path_provider_windows/example/pubspec.yaml
packages/quick_actions/example/pubspec.yaml
packages/sensors/example/pubspec.yaml
packages/share/example/pubspec.yaml
packages/shared_preferences/shared_preferences/example/pubspec.yaml
packages/shared_preferences/shared_preferences_linux/example/pubspec.yaml
packages/shared_preferences/shared_preferences_macos/example/pubspec.yaml
packages/url_launcher/url_launcher/example/pubspec.yaml
packages/url_launcher/url_launcher_linux/example/pubspec.yaml
packages/url_launcher/url_launcher_macos/example/pubspec.yaml
packages/url_launcher/url_launcher_windows/example/pubspec.yaml
packages/video_player/video_player/example/pubspec.yaml

Align example pubspecs with new templates, removing unused upper constraint
https://github.com/flutter/flutter/pull/68437

Update example pubspecs to match templates

---

packages/path_provider/path_provider_linux/CHANGELOG.md
packages/path_provider/path_provider_linux/example/pubspec.yaml
packages/path_provider/path_provider_linux/pubspec.yaml
packages/path_provider/path_provider_macos/CHANGELOG.md
packages/path_provider/path_provider_macos/example/pubspec.yaml
packages/path_provider/path_provider_macos/pubspec.yaml
packages/path_provider/path_provider_platform_interface/pubspec.yaml
packages/path_provider/path_provider_windows/CHANGELOG.md
packages/path_provider/path_provider_windows/example/pubspec.yaml
packages/path_provider/path_provider_windows/pubspec.yaml

Makes all platform packages stable null-safe releases.

[path_provider] Bump platform packages to NNBD stable

---

packages/connectivity/connectivity_platform_interface/CHANGELOG.md
packages/connectivity/connectivity_platform_interface/pubspec.yaml

Release NNBD as stable version

[connectivity_platform_interface] nnbd stable release

---

packages/connectivity/connectivity_macos/CHANGELOG.md
packages/connectivity/connectivity_macos/example/lib/main.dart
packages/connectivity/connectivity_macos/example/pubspec.yaml
packages/connectivity/connectivity_macos/example/test_driver/integration_test/connectivity_test.dart
packages/connectivity/connectivity_macos/example/test_driver/test/integration_test.dart
packages/connectivity/connectivity_macos/pubspec.yaml

Move the plugin to stable version

[connectivity_macos] move NNBD to stable

---

packages/device_info/device_info_platform_interface/CHANGELOG.md
packages/device_info/device_info_platform_interface/pubspec.yaml

[device_info_platform_interface] null safety stable release

---

packages/android_intent/example/pubspec.yaml
packages/android_intent/pubspec.yaml

Needs to be increased due removal of `ios` stub folder to allow publishing. …

[android_intent] Fix Flutter SDK version

---

packages/wifi_info_flutter/wifi_info_flutter_platform_interface/CHANGELOG.md
packages/wifi_info_flutter/wifi_info_flutter_platform_interface/pubspec.yaml

Release the null safety version to stable

[wifi_info_flutter_platform_interface] null safety stable release

---

.cirrus.yml
packages/android_alarm_manager/example/integration_test/android_alarm_manager_test.dart
packages/android_alarm_manager/example/pubspec.yaml
packages/android_alarm_manager/example/test_driver/integration_test.dart

Set up ci runs only on master
Make android alarm manager runs integration test with null safety

set ci runs on master and enable integration test on android alarm manager

---

.cirrus.yml

Updates the way the script checks for the availability of encrypted variables to account for changes in Cirrus behavior.
Fixes https://github.com/flutter/flutter/issues/76805

Fix Cirrus script for firebase testlab tests

---

.ci/Dockerfile

As recommended in https://github.com/flutter/website/pull/5466 after [this change](https://github.com/flutter/flutter/pull/77926/files#diff-b4a579d589fdf15fc4d4688009d8f189f4a88888d0b68bf64f2e1ccb9588dcccR29) to the Linux App template.
This should fix the `build_all_plugins_linux CHANNEL:master ` check which is currently broken in `master`.
🔴
[CLA]: …

[ci] Add libgcrypt to Docker image.

---

packages/quick_actions/quick_actions_platform_interface/LICENSE

Update the contents of the LICENSE file from the quick_actions_platform_interface package to comply to the current specification.
This should move the tree back to green (see flutter/flutter#78699).
[CLA]: …

[quick_actions_platform_interface] Update license file

---

.gitignore
packages/battery/battery/example/ios/Podfile
packages/camera/camera/example/ios/Podfile
packages/connectivity/connectivity/example/ios/Podfile
packages/device_info/device_info/example/ios/Podfile
packages/google_maps_flutter/google_maps_flutter/example/ios/Podfile
packages/google_sign_in/google_sign_in/example/ios/Podfile
packages/integration_test/example/ios/Podfile
packages/ios_platform_images/example/ios/Podfile
packages/local_auth/example/ios/Podfile
packages/package_info/example/ios/Podfile
packages/path_provider/path_provider/example/ios/Podfile
packages/quick_actions/quick_actions/example/ios/Podfile
packages/sensors/example/ios/Podfile
packages/share/example/ios/Podfile
packages/shared_preferences/shared_preferences/example/ios/Podfile
packages/url_launcher/url_launcher/example/ios/Podfile
packages/video_player/video_player/example/ios/Podfile
packages/wifi_info_flutter/wifi_info_flutter/example/ios/Podfile

Removes the podfile in gitignore, also add all podfiles.  …

[all] remove podfile in gitignore and update all podfiles

---

packages/in_app_purchase/in_app_purchase/README.md

Minor PR that fixes two spelling mistakes in the README.md file.
- I encountered the mistakes while looking into another issue. I decided to make a quick PR to fix the mistakes and skip creating a separate issue for these two small mistakes.
- Only fixes two minor spelling mistakes in the README which I feel don't require a separate release.
- Only fixes two minor spelling mistakes in the README which I feel don't require a separate release. …

[in_app_purchase] Fixed some minor spelling mistakes in README

---

packages/in_app_purchase/in_app_purchase/example/README.md

Update the instructions on how to setup the in_app_purchase example App. …

[in_app_purchase] Update instructions on setting up example App

---

packages/google_sign_in/google_sign_in_web/lib/src/generated/gapiauth2.dart

Continuation of https://github.com/flutter/plugins/pull/3756, which missed one question mark.

Drop redundant ? for dynamic

---

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter/pubspec.yaml

Fix a wrong version introduced in https://github.com/flutter/plugins/pull/3784

[google_map_flutter] fix version

---

CONTRIBUTING.md

Fixes https://github.com/flutter/plugins/pull/3801#discussion_r616951720

fix incorrect `MD` in CONTRIBUTING.md

---

script/tool/CHANGELOG.md
script/tool/LICENSE
script/tool/README.md
script/tool/pubspec.yaml

Re-adds the LICENSE and CHANGELOG, and updates the README and pubspec,
in preparation for pushing an updated version of the package.
We are still using flutter_plugin_tools in flutter/packages, so this
allows us to use updates (e.g., license checks, fixed version checks) in
that repository as well. The README has been updated to note that it is
no longer intended for general use, and we will (if it allows
publishing) continue to mark the package as discontinued to reflect
that. …

Prep the flutter_plugin_tools for publishing

---

.ci/dev/try_builders.json

Windows bots are currently broken for building Flutter desktop apps; see https://github.com/flutter/flutter/issues/82032 and related issues.
This temporarily disables the tests; most PRs do not affect Windows, so we don't need the whole tree to continue to be closed while that's resolved.
https://github.com/flutter/flutter/issues/82032 …

Temporarily disable Windows tests

---

.ci/dev/try_builders.json

Revert "Temporarily disable Windows tests"

---

packages/in_app_purchase/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/in_app_purchase/example/pubspec.yaml
packages/in_app_purchase/in_app_purchase/pubspec.yaml
packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml

The plugin's iOS folder has been removed due to federation. This is to support no iOS folder: 
```
pubspec.yaml allows Flutter SDK version prior to 1.20.0, which does not support having no `ios/` folder.
Please consider increasing the Flutter SDK requirement to ^1.20.0 or higher (environment.sdk.flutter) or create an `ios/` folder.
```
[CLA]: …

[in_app_purchase] update min Flutter version to 1.20.0

---

packages/webview_flutter/README.md

I have forgotten to remove this section in https://github.com/flutter/plugins/pull/3894

Remove section from WebView readme

---

packages/webview_flutter/CHANGELOG.md
packages/webview_flutter/pubspec.yaml

The published version of 2.0.6 is not compatible with the current
Flutter stable (2.2) and earlier due to an issue with how Dart 2.14
(on the current Flutter master) creates archives. See
https://github.com/dart-lang/pub/issues/3001
This is a no-op change to allow republishing from stable.
Fixes https://github.com/flutter/flutter/issues/82803
[breaking …

[webview_flutter] Bump version for republishing

---

packages/in_app_purchase/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/in_app_purchase/README.md
packages/in_app_purchase/in_app_purchase/pubspec.yaml

This PR moves the in_app_purchase plugin to stable by updating the version to 1.0.0 and remove references of beta version from the README.md. …

[in_app_purchase] Move to stable release

---

.cirrus.yml
packages/connectivity/connectivity_for_web/example/pubspec.yaml
packages/file_selector/file_selector_web/example/pubspec.yaml
packages/google_sign_in/google_sign_in_web/example/pubspec.yaml
packages/url_launcher/url_launcher_web/example/pubspec.yaml

Now that null-safe integration_tests is available on stable, stop
skipping those tests. Update the Flutter requirements in those tests to
reflect the current versioning.
Also recombine the analyze tasks that were split to allow analyze to run
on stable.
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-change …

Enable web integration tests on stable

---

packages/url_launcher/url_launcher_platform_interface/CHANGELOG.md
packages/url_launcher/url_launcher_platform_interface/lib/link.dart
packages/url_launcher/url_launcher_platform_interface/pubspec.yaml
packages/url_launcher/url_launcher_platform_interface/test/link_test.dart

[url_launcher] Migrate pushRouteNameToFramework to ChannelBuffers

---

packages/flutter_plugin_android_lifecycle/example/integration_test/flutter_plugin_android_lifecycle_test.dart

Enables null safety for the integration test now that it's supported on
master.

[flutter_plugin_android_lifecycle] Migrate integration test to NNBD

---

packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/example/ios/Podfile
packages/video_player/video_player/example/ios/Runner.xcodeproj/project.pbxproj
packages/video_player/video_player/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
packages/video_player/video_player/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/video_player/video_player/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
packages/video_player/video_player/example/ios/RunnerTests/Info.plist
packages/video_player/video_player/example/ios/RunnerTests/VideoPlayerTests.m
packages/video_player/video_player/example/ios/RunnerUITests/Info.plist
packages/video_player/video_player/example/ios/RunnerUITests/VideoPlayerUITests.m

Add `RunnerTests` XCTest and `RunnerUITest` XCUITest iOS targets to example app.
- Add unit test that creates the plugin and asserts it's not nil, proving linking is set up correctly.
- Add UI test that navigates between tabs.
video_player part of https://github.com/flutter/flutter/issues/83357
https://cirrus-ci.com/task/4666430638522368?logs=xctest#L1674
```
Test Suite 'VideoPlayerTests' started at 2021-05-27 15:10:49.592
Test Case '-[VideoPlayerTests testPlugin]' started.
Test Case '-[VideoPlayerTests testPlugin]' passed (0.008 seconds).
Test Suite 'VideoPlayerTests' passed at 2021-05-27 15:10:49.617.
```
```
Test Case '-[VideoPlayerUITests testTabs]' passed (10.934 seconds).
Test Suite 'VideoPlayerUITests' passed at 2021-05-27 15:11:04.763.
Executed 1 test, with 0 failures (0 …
```

[video_player] Add iOS unit and UI tests

---

packages/google_sign_in/google_sign_in/CHANGELOG.md
packages/google_sign_in/google_sign_in/example/ios/Podfile
packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/project.pbxproj
packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
packages/google_sign_in/google_sign_in/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/google_sign_in/google_sign_in/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
packages/google_sign_in/google_sign_in/example/ios/RunnerTests/GoogleSignInTests.m
packages/google_sign_in/google_sign_in/example/ios/RunnerTests/Info.plist
packages/google_sign_in/google_sign_in/example/ios/RunnerUITests/GoogleSignInUITests.m
packages/google_sign_in/google_sign_in/example/ios/RunnerUITests/Info.plist

Add `RunnerTests` XCTest and `RunnerUITest` XCUITest iOS targets to example app.
- Add unit test that creates the plugin and asserts it's not nil, proving linking is set up correctly.
- Add UI test that just hits the SIGN IN button and accepts the permission prompt.  I couldn't get past https://github.com/flutter/flutter/issues/83759 to do anything more interesting.
google_sign_in part of https://github.com/flutter/flutter/issues/83357
https://cirrus-ci.com/task/5498520523243520?logs=xctest#L1514
```
Test Suite 'GoogleSignInUITests' passed at 2021-06-01 19:08:04.465.
Executed 1 test, with 0 failures (0 unexpected) in 7.616 (7.617) seconds
Test Suite 'RunnerUITests.xctest' passed at 2021-06-01 19:08:04.466.
Executed 1 test, with 0 failures (0 unexpected) in 7.616 (7.619) seconds
```
``` …
```

[google_sign_in] Add iOS unit and UI tests

---

script/tool/test/publish_plugin_command_test.dart

In each library where an import is removed, the library uses some elements
provided by the import, BUT there is another import which provides all of the
same elements, and at least one more which the library uses.
In this change, we remove the imports which can be simply removed in favor of
the other already present imports.
See https://github.com/dart-lang/sdk/issues/44569 for more information.
https://github.com/flutter/flutter/issues/74381 is _improved_ by this issue. Not fixed.
[Contributor …

Remove "unnecessary" imports.

---

analysis_options.yaml

There are many violations of this new Hint. If we do not ignore them, the flutter roll breaks.
Related to https://github.com/flutter/flutter/issues/74381
None. …

Ignore upcoming unnecessary_imports analysis

---

packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java
packages/in_app_purchase/in_app_purchase_android/android/src/test/java/io/flutter/plugins/inapppurchase/TranslatorTest.java
packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.dart
packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.g.dart
packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/purchase_wrapper_test.dart

This PR adds the obfuscatedAccountId and obfuscatedProfileId to the PurchaseWrapper of a Google Play Purchase.
It contains documentation about how these id's can be set on the purchase.
Fixes #83651 …

[in_app_purchase] Added userIds to google play purchase

---

.ci/Dockerfile
.cirrus.yml

Re-merges the Dockerfiles now that https://github.com/flutter/flutter/issues/84717
has been addressed, and ensures that we are controlling the base image that we use,
rather than it changing automatically on rebuild.
Part of https://github.com/flutter/flutter/issues/84712
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-chan …

Pin base image used in CI Dockerfile

---

packages/image_picker/image_picker/CHANGELOG.md
packages/image_picker/image_picker/README.md
packages/image_picker/image_picker/pubspec.yaml

Migrated example in the README in the README to null-safety. 
`image_picker/example` already has null-safety.
[Discord]: …

[image_picker] Migrate README example to null-safety

---

packages/in_app_purchase/in_app_purchase_platform_interface/CHANGELOG.md
packages/in_app_purchase/in_app_purchase_platform_interface/lib/src/types/purchase_status.dart
packages/in_app_purchase/in_app_purchase_platform_interface/pubspec.yaml

[in_app_purchase_platform_interface] Fixed restoring purchases link

---

.cirrus.yml
script/tool/README.md

Update CI and README to call the tool via bin/flutter_plugin_tools.dart
rather than lib/src/main.dart to avoid a warning line on every run.
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#fo …

Update tool commands

---

packages/image_picker/image_picker/example/lib/main.dart

Fixes https://github.com/flutter/flutter/issues/84773

[image_picker] remove unused imports from example

---

packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
packages/in_app_purchase/in_app_purchase_android/pubspec.yaml

0.1.3 was published in an earlier commit https://github.com/flutter/plugins/commit/ff87585717e3cbf44d857035fb327a9f7836ecd2, so we can't publish 0.1.3 at the commit where the payment proxy was added in https://github.com/flutter/plugins/pull/4055
Thus introduce a new version for the payment proxy change in https://github.com/flutter/plugins/pull/4055 …

[in_app_purchase_android] fix version for 'add payment proxy': pull/4055

---

.cirrus.yml

Issue: https://github.com/flutter/flutter/issues/84667

Update cirrus gcp credentials

---

packages/in_app_purchase/in_app_purchase/example/android/build.gradle
packages/in_app_purchase/in_app_purchase/example/android/gradle/wrapper/gradle-wrapper.properties

The gradle and gradle tool version have been upgraded in in_app_purchase_android https://github.com/flutter/plugins/commit/e83a6833c98f13009c73cb19cc5da5e85dbb130f, which caused a version mismatch in the in_app_purchase plugin
[Discord]: …

[in_app_purchase] update gradle tool to 4.1.0

---

CONTRIBUTING.md

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.* …

Add a link to the new wiki page about plugin and package PRs

---

.github/workflows/release.yml

The wait interval for "release" job was too short so it generates too much output, which caused the GitHub UI to freeze.
This PR makes the wait interval longer, to 3 mins.
Workaround for https://github.com/flutter/flutter/issues/85127
- [ x I listed at least one issue that this PR fixes in the description above. …

[ci] increase auto publish job wait interval to 3 mins.

---

.github/workflows/release.yml

Only allow the "release" action run under flutter org to avoid failing on other folks.
Fixes https://github.com/flutter/flutter/issues/85175
[the …

[ci] Set release action owner as flutter

---

.ci.yaml

Update .ci.yaml documentation link

---

README.md

Add release status badge to README

Add release status badge to README

---

packages/in_app_purchase/in_app_purchase_ios/CHANGELOG.md
packages/in_app_purchase/in_app_purchase_ios/example/ios/RunnerTests/TranslatorTests.m
packages/in_app_purchase/in_app_purchase_ios/ios/Classes/FIAObjectTranslator.m
packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_product_wrapper.dart
packages/in_app_purchase/in_app_purchase_ios/lib/src/store_kit_wrappers/sk_product_wrapper.g.dart
packages/in_app_purchase/in_app_purchase_ios/pubspec.yaml
packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_methodchannel_apis_test.dart
packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_product_test.dart
packages/in_app_purchase/in_app_purchase_ios/test/store_kit_wrappers/sk_test_stub_objects.dart

Adds countryCode to the SKPriceLocaleWrapper
NSLocale contains a lot of objects and we decided only to add objects that are requested by customers.
This fixes flutter/flutter#85515 …

[in_app_purchase] Added country code to sk product wrapper

---

script/tool/test/analyze_command_test.dart
script/tool/test/common/plugin_command_test.dart
script/tool/test/create_all_plugins_app_command_test.dart
script/tool/test/publish_plugin_command_test.dart
script/tool/test/pubspec_check_command_test.dart
script/tool/test/test_command_test.dart
script/tool/test/version_check_command_test.dart
script/tool/test/xctest_command_test.dart

- Updates the remaining tests (other than one that still needs to be
converted to the new base command, which will be fixed then) that
aren't using runCapturingPrint to do so to reduce test log spam.
- Simplifies and standardizes the matcher used for ToolExit in tests. …

[flutter_plugin_tools] Minor test cleanup

---

packages/camera/camera_web/example/integration_test/camera_test.dart
packages/camera/camera_web/example/integration_test/camera_web_test.dart
packages/camera/camera_web/lib/src/camera.dart
packages/camera/camera_web/lib/src/camera_web.dart

Adds `buildPreview` implementation of the camera platform interface.
- Added `getViewType` to `Camera`.
- Returns the registered view type of the camera.
- Added `buildPreview` implementation.
- Returns an `HtmlElementView` with a view type of the given camera.
[Discord]: …

[camera_web] Add `buildPreview` implementation

---

packages/in_app_purchase/in_app_purchase_android/README.md

Removed the code block start tag which broke the formatting of the README markdown.
Fixes flutter/flutter#87185
- Not necessary to release a separate version for this small documentation change.
- Not necessary to release a separate version for this small documentation change.
- Small documentation fix which doesn't require unit-tests.
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.m …

[in_app_purchase] Correct mistake with markdown in README.md

---

packages/camera/camera_web/lib/src/camera.dart

Added comments to explain how setting the flash mode affects the camera torch mode constraint as suggested in https://github.com/flutter/plugins/pull/4222#discussion_r685373028. …

[camera_web] Add `setFlashMode` comments

---

packages/camera/camera_web/README.md

Updated the web plugin README with usage, example, limitations on the web platform and missing implementation. …

[camera_web] Update the web plugin README

---

packages/android_alarm_manager/android/gradle.properties
packages/android_intent/android/gradle.properties
packages/battery/battery/android/gradle.properties
packages/camera/camera/android/gradle.properties
packages/connectivity/connectivity/android/gradle.properties
packages/device_info/device_info/android/gradle.properties
packages/espresso/android/gradle.properties
packages/flutter_plugin_android_lifecycle/android/gradle.properties
packages/google_maps_flutter/google_maps_flutter/android/gradle.properties
packages/google_sign_in/google_sign_in/android/gradle.properties
packages/image_picker/image_picker/android/gradle.properties
packages/in_app_purchase/in_app_purchase_android/android/gradle.properties
packages/local_auth/android/gradle.properties
packages/package_info/android/gradle.properties
packages/path_provider/path_provider/android/gradle.properties
packages/quick_actions/quick_actions/android/gradle.properties
packages/sensors/android/gradle.properties
packages/share/android/gradle.properties
packages/shared_preferences/shared_preferences/android/gradle.properties
packages/url_launcher/url_launcher/android/gradle.properties
packages/video_player/video_player/android/gradle.properties
packages/wifi_info_flutter/wifi_info_flutter/android/gradle.properties

The plugin-level gradle.properties file is not used, only the app-level
file, so these are cruft.

Remove gradle.properties from plugins

---

.github/workflows/release.yml

This extra permission is required so the `release` github action is able to publish a tag into the repo, after publishing a plugin.
Fixes https://github.com/flutter/flutter/issues/90095
(Tested in flutter/packages)
[Discord]: …

[ci] Grant contents: write permission to release.yml

---

packages/webview_flutter/webview_flutter/CHANGELOG.md
packages/webview_flutter/webview_flutter/pubspec.yaml
script/configs/exclude_all_plugins_app.yaml

This morning PR #4366 was merged into master, however the PR didn't include an updated version number in the pubspec.yaml nor release information in the CHANGELOG. 
This PR will be fixing this mistake and updates the version of the app_facing package to 2.1.0 and adds related release notes to the CHANGELOG.
- Related to issue: https://github.com/flutter/flutter/issues/86286 …

[webview_flutter] Update version number app_facing package

---

packages/android_intent/pubspec.yaml
packages/file_selector/file_selector_web/example/pubspec.yaml

Updates the build_runner dependency to one that is compatible with the latest test package. These are only dev dependencies and have no impact on consumers.
Fixes https://github.com/flutter/flutter/issues/92933 …

update build_runner dependencies in android_intent and file_selector example

---

packages/file_selector/file_selector_web/example/pubspec.yaml

(It took less time to create this PR than to create an issue to "remove unused dependency")
* Spotted in: https://github.com/flutter/plugins/pull/4467 …

[ci] Remove unused dep from file_selector.

---

.github/workflows/mirror.yml

This is to prepare for the migration of master to main.
Bug: https://github.com/flutter/flutter/issues/90476 …

Add mirroring of master to main branch.

---

.cirrus.yml

Currently most of our Cirrus task runs are about 20 minutes or less, but
there are a few consistent outliers:
- One Android shard takes ~40 minutes, and another takes 25-30.
- The Web platform tests take ~40 minutes.
This increases Android sharding from 4 to 5, and web sharding from 1 (no
sharding) to 2 to improve overall test run times. …

[ci] Increase Android and Web sharding

---

packages/path_provider/path_provider_linux/CHANGELOG.md
packages/path_provider/path_provider_linux/pubspec.yaml
packages/path_provider/path_provider_windows/CHANGELOG.md
packages/path_provider/path_provider_windows/pubspec.yaml
packages/shared_preferences/shared_preferences_linux/CHANGELOG.md
packages/shared_preferences/shared_preferences_linux/pubspec.yaml
packages/shared_preferences/shared_preferences_windows/CHANGELOG.md
packages/shared_preferences/shared_preferences_windows/pubspec.yaml

This workaround has not been needed since Flutter 1.20, and all plugins
now require at least Flutter 2.0, so it can be safely removed.
Part of https://github.com/flutter/flutter/issues/57497 …

Remove "pluginClass: none" from pubspecs

---

packages/path_provider/path_provider/pubspec.yaml

Now that the iOS and Android implementation packages are published,
switch to them and re-enable publishing. …

[path_provider] Publish fully federated version

---

script/configs/exclude_native_unit_android.yaml

Fixes https://github.com/flutter/flutter/issues/93286
Reverts flutter/plugins#4487

Enable camera/quick_actions tests 

---

packages/camera/camera/CHANGELOG.md
packages/camera/camera/pubspec.yaml

https://github.com/flutter/plugins/pull/4423 incorrectly added changelog
entries to an already-published version instead of bumping the version,
whcih was missed during review.
This moves those entries to a new version, so that they will be a) published
and b) associated with the correct version in the CHANGELOG.
Fixes https://github.com/flutter/flutter/issues/93659
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-brea …

[camera] Fix version and CHANGELOG

---

packages/image_picker/image_picker/CHANGELOG.md
packages/image_picker/image_picker/example/ios/Podfile
packages/image_picker/image_picker/example/ios/Runner.xcodeproj/project.pbxproj
packages/image_picker/image_picker/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

RunnerUITests crashes at runtime because `Flutter` is correctly not embedded in the bundle.  XCUITest targets should not be linking against development frameworks.
Remove `inherit! :search_paths` from `Podfile` and remove the base Flutter xcconfig configuration.
https://github.com/flutter/flutter/issues/93325#issuecomment-966527981 …

[image_picker] Fix iOS RunnerUITests search paths

---

packages/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java
packages/local_auth/android/src/test/java/io/flutter/plugins/localauth/LocalAuthTest.java

[local_auth] Fix activity leak in LocalAuthPlugin

---

.github/labeler.yml

Not all iOS implementation packages use `_ios` now. This adds `_storekit` and `_wkwebview` as known patterns for iOS implementation packages so that they will be labelled correctly. …

[ci] Update labeler for special cases

---

packages/webview_flutter/webview_flutter_android/CHANGELOG.md
packages/webview_flutter/webview_flutter_android/README.md
packages/webview_flutter/webview_flutter_android/pubspec.yaml

Added some additional information on how to generate the pigeon communication layer and the mockito mock objects. …

[webview_flutter] Added contributing section to the README.md

---

packages/quick_actions/analysis_options.yaml
packages/quick_actions/quick_actions/CHANGELOG.md
packages/quick_actions/quick_actions/example/integration_test/quick_actions_test.dart
packages/quick_actions/quick_actions/example/lib/main.dart
packages/quick_actions/quick_actions/test/quick_actions_test.dart
packages/quick_actions/quick_actions_platform_interface/CHANGELOG.md
packages/quick_actions/quick_actions_platform_interface/lib/method_channel/method_channel_quick_actions.dart
packages/quick_actions/quick_actions_platform_interface/lib/platform_interface/quick_actions_platform.dart
packages/quick_actions/quick_actions_platform_interface/lib/types/quick_action_handler.dart
packages/quick_actions/quick_actions_platform_interface/test/method_channel_quick_actions_test.dart
packages/quick_actions/quick_actions_platform_interface/test/quick_actions_platform_interface_test.dart
script/configs/custom_analysis.yaml

Removes the use of the legacy analysis options, and fixes the resulting analysis issues.
No version change: No changes that should affect behavior or package clients.
[exempt …

[quick_actions] Migrate to new analysis options

---

packages/url_launcher/url_launcher/CHANGELOG.md
packages/url_launcher/url_launcher/pubspec.yaml

Restores the app-facing package to a publishable state now that _android
and _ios implementation packages are published.
Part of flutter/flutter#68498 …

[url_launcher] Publish fully federated version

---

packages/local_auth/CHANGELOG.md
packages/local_auth/analysis_options.yaml
packages/local_auth/example/lib/main.dart
packages/local_auth/example/pubspec.yaml
packages/local_auth/lib/local_auth.dart
packages/local_auth/pubspec.yaml
packages/local_auth/test/local_auth_test.dart
script/configs/custom_analysis.yaml

Removes the legacy analysis options and fixes all violations. Most fixes were automated `dart fix --apply` changes. …

[local_auth] Switch to new analysis options

---

packages/camera/camera_platform_interface/CHANGELOG.md
packages/camera/camera_platform_interface/analysis_options.yaml
packages/camera/camera_platform_interface/lib/camera_platform_interface.dart
packages/camera/camera_platform_interface/lib/src/events/camera_event.dart
packages/camera/camera_platform_interface/lib/src/events/device_event.dart
packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
packages/camera/camera_platform_interface/lib/src/types/camera_description.dart
packages/camera/camera_platform_interface/lib/src/types/exposure_mode.dart
packages/camera/camera_platform_interface/lib/src/types/focus_mode.dart
packages/camera/camera_platform_interface/lib/src/types/types.dart
packages/camera/camera_platform_interface/lib/src/utils/utils.dart
packages/camera/camera_platform_interface/pubspec.yaml
packages/camera/camera_platform_interface/test/camera_platform_interface_test.dart
packages/camera/camera_platform_interface/test/events/camera_event_test.dart
packages/camera/camera_platform_interface/test/events/device_event_test.dart
packages/camera/camera_platform_interface/test/method_channel/method_channel_camera_test.dart
packages/camera/camera_platform_interface/test/types/camera_description_test.dart
packages/camera/camera_platform_interface/test/types/camera_exception_test.dart
packages/camera/camera_platform_interface/test/types/exposure_mode_test.dart
packages/camera/camera_platform_interface/test/types/flash_mode_test.dart
packages/camera/camera_platform_interface/test/types/focus_mode_test.dart
packages/camera/camera_platform_interface/test/types/resolution_preset_test.dart
packages/camera/camera_platform_interface/test/utils/method_channel_mock.dart
packages/camera/camera_platform_interface/test/utils/utils_test.dart
script/configs/custom_analysis.yaml

Switches camera_platform_interface from the legacy analysis options to the new ones, fixing all violations they flag. …

[camera] Switch platform interface to new analysis options

---

.github/workflows/mirror.yml

This is to make main the default branch.
Bug: https://github.com/flutter/flutter/issues/90476 …

Swap the mirroring order.

---

.github/workflows/release.yml

Part of switching default from `master` to `main`
[following repository CHANGELOG style]: …

[ci] Switch release action to 'main'

---

.github/workflows/mirror.yml

Cherry-picks #4650 to `main`, so that mirroring to `master` actually happens.
[following …

Swap the mirroring order

---

packages/plugin_platform_interface/CHANGELOG.md
packages/plugin_platform_interface/README.md
packages/plugin_platform_interface/pubspec.yaml
packages/plugin_platform_interface/test/plugin_platform_interface_test.dart

Updates the example to use the new `verify` method, and makes discussion
of testing more generalized since it applies to uses like `Fake` as
well. …

[plugin_platform_interface] Update README and add a test

---

.cirrus.yml

The default branch is now `main`, so that should be the default base
revision for the tooling to compare against.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and …

[ci] Switch the fetch head to 'main'

---

.ci.yaml

This is also changing the name of some of the tests and will need some
propagation time which is already being considered in the migration
window.
Bug: https://github.com/flutter/flutter/issues/90476
[pub …

Run tests only on main branch.

---

packages/camera/camera_web/CHANGELOG.md
packages/camera/camera_web/lib/src/camera_web.dart

No version change: No change to plugin functionality

[camera_web] Update camera_web to support Dart's new async requestFullscreen API

---

packages/video_player/video_player/CHANGELOG.md
packages/video_player/video_player/pubspec.yaml

Publishes the change from in-package Android and iOS implementations
to federated implementations. …

[video_player] Publish fully federation version

---

.github/workflows/scorecards-analysis.yml

Scorecards is failing because it relies on an environment variable that
do not exist on cron jobs. Since we are running the workflow on every PR
we can safely delete the the scheduled one. …

Remove the on schedule event on scorecards.

---

packages/url_launcher/url_launcher/CHANGELOG.md
packages/url_launcher/url_launcher/README.md
packages/url_launcher/url_launcher/pubspec.yaml

Update for documentation on readme file:
- describes file:/ scheme usage, related to platforms: macOS, linux and Windows.
- link update to `Uri` class documentation
Fixes https://github.com/flutter/flutter/issues/97422
[Discord]: …

[url_launcher] Documentation improvement for file scheme to readme

---

packages/ios_platform_images/CHANGELOG.md
packages/ios_platform_images/analysis_options.yaml
packages/ios_platform_images/example/lib/main.dart
packages/ios_platform_images/example/pubspec.yaml
packages/ios_platform_images/example/test/widget_test.dart
packages/ios_platform_images/lib/ios_platform_images.dart
packages/ios_platform_images/pubspec.yaml
packages/ios_platform_images/test/ios_platform_images_test.dart
script/configs/custom_analysis.yaml

[ios_platform_images] Switch to new analysis options

---

packages/path_provider/path_provider/example/pubspec.yaml
packages/path_provider/path_provider/pubspec.yaml
packages/path_provider/path_provider_android/example/pubspec.yaml
packages/path_provider/path_provider_android/pubspec.yaml
packages/path_provider/path_provider_ios/example/pubspec.yaml
packages/path_provider/path_provider_ios/pubspec.yaml
packages/path_provider/path_provider_linux/pubspec.yaml
packages/path_provider/path_provider_macos/pubspec.yaml
packages/path_provider/path_provider_platform_interface/pubspec.yaml
packages/path_provider/path_provider_windows/example/pubspec.yaml
packages/path_provider/path_provider_windows/pubspec.yaml

Remove use of deprecated pedantic package
No version change: Removing cruft
No CHANGELOG change: Removing cruft …

[path_provider] Remove use of deprecated pedantic package

---

packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit/web_kit.dart
packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit_webview_widget.dart
packages/webview_flutter/webview_flutter_wkwebview/test/src/web_kit_webview_widget_test.dart
packages/webview_flutter/webview_flutter_wkwebview/test/src/web_kit_webview_widget_test.mocks.dart

Adds support for JavaScript channels to the new iOS implementation. 
No version change:
Part of https://github.com/flutter/flutter/issues/93732 and doesn't make any changes to the current implementation.
No CHANGELOG change: Incremental unused code doesn't need to be noted in the CHANGELOG. …

Adds support for JavaScript channels to the new iOS implementation of `webview_flutter_wkwebview`.

---

packages/video_player/video_player_platform_interface/test/video_player_options_test.dart

Add missing license header introduced in https://github.com/flutter/plugins/pull/4807
No CHANGELOG change: This is a license header only change in a test file so version updates and tests are not necessary.
[pub …

[video_player] fix license header

---

packages/in_app_purchase/in_app_purchase_android/CHANGELOG.md
packages/in_app_purchase/in_app_purchase_android/analysis_options.yaml
packages/in_app_purchase/in_app_purchase_android/example/lib/consumable_store.dart
packages/in_app_purchase/in_app_purchase_android/example/lib/main.dart
packages/in_app_purchase/in_app_purchase_android/example/pubspec.yaml
packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/billing_client_wrapper.dart
packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.dart
packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/sku_details_wrapper.dart
packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform.dart
packages/in_app_purchase/in_app_purchase_android/lib/src/in_app_purchase_android_platform_addition.dart
packages/in_app_purchase/in_app_purchase_android/lib/src/types/google_play_product_details.dart
packages/in_app_purchase/in_app_purchase_android/lib/src/types/google_play_purchase_details.dart
packages/in_app_purchase/in_app_purchase_android/pubspec.yaml
packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/billing_client_wrapper_test.dart
packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/purchase_wrapper_test.dart
packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/sku_details_wrapper_deprecated_test.dart
packages/in_app_purchase/in_app_purchase_android/test/billing_client_wrappers/sku_details_wrapper_test.dart
packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_addition_test.dart
packages/in_app_purchase/in_app_purchase_android/test/in_app_purchase_android_platform_test.dart
packages/in_app_purchase/in_app_purchase_android/test/stub_in_app_purchase_platform.dart
script/configs/custom_analysis.yaml

[in_app_purchase] Update Android to new analysis options

---

.cirrus.yml

https://github.com/flutter/flutter/issues/99283

[cirrus] Refresh GCP service account

---

packages/in_app_purchase/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/in_app_purchase/analysis_options.yaml
packages/in_app_purchase/in_app_purchase/example/lib/consumable_store.dart
packages/in_app_purchase/in_app_purchase/example/lib/main.dart
packages/in_app_purchase/in_app_purchase/example/pubspec.yaml
packages/in_app_purchase/in_app_purchase/lib/in_app_purchase.dart
packages/in_app_purchase/in_app_purchase/pubspec.yaml
packages/in_app_purchase/in_app_purchase/test/in_app_purchase_test.dart
script/configs/custom_analysis.yaml

[in_app_purchase] Update app-facing package to new analysis options

---

packages/quick_actions/quick_actions/CHANGELOG.md
packages/quick_actions/quick_actions/pubspec.yaml

Restores the package to a publishable state using the new federated
implementations.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugi …

[quick_actions] Publish federated version

---

packages/camera/camera/CHANGELOG.md
packages/camera/camera/example/ios/Runner.xcodeproj/project.pbxproj
packages/camera/camera/example/ios/RunnerTests/QueueUtilsTests.m
packages/camera/camera/ios/Classes/CameraPlugin.m
packages/camera/camera/ios/Classes/CameraPlugin.modulemap
packages/camera/camera/ios/Classes/FLTCam.m
packages/camera/camera/ios/Classes/FLTThreadSafeEventChannel.m
packages/camera/camera/ios/Classes/FLTThreadSafeFlutterResult.m
packages/camera/camera/ios/Classes/FLTThreadSafeMethodChannel.m
packages/camera/camera/ios/Classes/FLTThreadSafeTextureRegistry.m
packages/camera/camera/ios/Classes/QueueUtils.h
packages/camera/camera/ios/Classes/QueueUtils.m

Removes QueueHelper class and use function instead. 
Also renamed file to `QueueUtils` to be consistent with `CameraTestUtils`
NA
No version change: just minor code cleanup.  …

[camera]remove QueueHelper class

---

packages/file_selector/file_selector/CHANGELOG.md
packages/file_selector/file_selector/README.md
packages/file_selector/file_selector/example/macos/Runner.xcodeproj/project.pbxproj
packages/file_selector/file_selector/example/macos/Runner.xcworkspace/contents.xcworkspacedata
packages/file_selector/file_selector/example/macos/Runner/DebugProfile.entitlements
packages/file_selector/file_selector/example/macos/Runner/Release.entitlements
packages/file_selector/file_selector/pubspec.yaml

When adding the macOS example to the app-facing package during
endorsement, I forgot to add the necessary entitlements to make it work
correctly. This adds the missing entitlement.
It also adds discussion of entitlements to the app-facing README, which
is currently only in the much less discoverable implementation package
README.
[Discord]: …

[file_selector] Update macOS README and example

---

.github/workflows/scorecards-analysis.yml

Plugins do not have dependabot enabled yet and the action workflows
haven't been getting updates. The current error getting the branch name
was fixed a few weeks ago. …

Update scorecard versions.

---

packages/webview_flutter/webview_flutter_wkwebview/lib/src/foundation/foundation.dart
packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit/web_kit.dart
packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit_webview_widget.dart
packages/webview_flutter/webview_flutter_wkwebview/test/src/web_kit_webview_widget_test.dart
packages/webview_flutter/webview_flutter_wkwebview/test/src/web_kit_webview_widget_test.mocks.dart

No version change:
Part of https://github.com/flutter/flutter/issues/93732 and doesn't make any changes to the current implementation.
No CHANGELOG change: Incremental unused code doesn't need to be noted in the CHANGELOG.
[Discord]: …

[webview_flutter_wkwebview] Add progress tracking support for flutter/flutter#93732

---

packages/camera/camera/CHANGELOG.md
packages/camera/camera/example/lib/main.dart
packages/camera/camera/example/test/main_test.dart
packages/camera/camera/pubspec.yaml

This migrates the deprecated Scaffold methods to ScaffoldMessenger in example code from the camera plugin.
These are being removed in https://github.com/flutter/flutter/pull/98549
Part of https://github.com/flutter/flutter/issues/98537
Added a test to validate the snackbar method presents as expected. There were no tests previously. …

[camera] Migrate deprecated Scaffold methods to ScaffoldMessenger

---

packages/image_picker/image_picker/CHANGELOG.md
packages/image_picker/image_picker/pubspec.yaml

Restores plugin to publishable state now that the federated mobile
implementations have been published. …

[image_picker] Publish federated version

---

CODEOWNERS

Add CODEOWNERS for iOS plugin implementations.
Also fix two incorrect Android paths. …

Add iOS path CODEOWNERS

---

packages/local_auth/local_auth_ios/CHANGELOG.md
packages/local_auth/local_auth_ios/ios/Classes/FLTLocalAuthPlugin.m
packages/local_auth/local_auth_ios/lib/types/auth_messages_ios.dart
packages/local_auth/local_auth_ios/pubspec.yaml
packages/local_auth/local_auth_ios/test/local_auth_test.dart

Add support localizedFallbackTitle in IOSAuthMessages.
[#34638](https://github.com/flutter/flutter/issues/34638)
[#3806](https://github.com/flutter/plugins/pull/3806)
Fixes [#96390](https://github.com/flutter/flutter/issues/96390)
[Discord]: …

[local_auth] support localizedFallbackTitle in IOSAuthMessages

---

CODEOWNERS

Added gaaclarke as codeowner

---

.ci/Dockerfile

This PR pins the hash for the Dockerfile dependency to ensure a trusted source for the dependency.
Fixes issue: https://github.com/flutter/plugins/security/code-scanning/3 …

Pin dockerfile version

---

.ci.yaml

Remove UWP test as it is not supported on flutter tool anymore
See: https://github.com/flutter/flutter/commit/944fcda67f294981dfe2b57991c32afc724f34c2
fixes: https://github.com/flutter/flutter/issues/102690
[pub …

ci: remove uwp test

---

.ci.yaml

https://github.com/flutter/flutter/issues/100259

[ci.yaml] Remove explicit caches

---

.github/dependabot.yml

Dependabot prefixes have a maximum of 15 chars ([docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message)).
This PR shortens the prefixes introduced here: https://github.com/flutter/plugins/pull/5440 so the dependabot action doesn't fail.
(Needs to land on red) …

[ci] Shorten dependabot prefixes to comply with config spec.

---

packages/camera/camera_web/example/integration_test/camera_test.dart
packages/camera/camera_web/example/integration_test/camera_web_test.dart
packages/camera/camera_web/example/pubspec.yaml

While testing other package, I noticed that `camera_web` was using a fairly old version of `package:mocktail`. Updated to latest published one.
No CHANGELOG change: This is purely an internal test change, shouldn't affect external users.
(Fixes: N/A, opportunistic commit while running tests for `package:cross_file`) …

[camera] Update mocktail to latest.

---

.github/workflows/mirror.yml
.github/workflows/pull_request_label.yml
.github/workflows/release.yml

Adding read-only as default permissions for several workflow items which needed top-level permissions defined in order to resolve security findings.
Resolves security issues:
- https://github.com/flutter/plugins/security/code-scanning/7
- https://github.com/flutter/plugins/security/code-scanning/6
- https://github.com/flutter/plugins/security/code-scanning/5
- https://github.com/flutter/plugins/security/code-scanning/4 …

[github workflow] Resolve token-permissions security alerts

---

CODEOWNERS

`espresso` and `flutter_plugin_android_lifecycle` missed getting owners in the initial assignment.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-upda …

Add more Android plugin owners

---

.cirrus.yml

https://github.com/flutter/plugins/runs/6680879371

Update firebase testlab key

---

.github/workflows/mirror.yml

This reverts commit 7cad5998706043997a6bb046061e818ccbaf3cf6.

Revert "All the workflows have been migrated to use main. (#5874)"

---

.github/dependabot.yml

Revert "[github_actions] Add automatic updating of github-actions"

---

.github/dependabot.yml

Reopening the automatic updating of github actions hashes

[github_actions] Add automatic updating of github-actions

---

packages/google_maps_flutter/google_maps_flutter_web/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter_web/README.md
packages/google_maps_flutter/google_maps_flutter_web/pubspec.yaml

When stacked, issues with mouse occur. This need to be documented.
This documents this issue and its limitation https://github.com/flutter/flutter/issues/73830 …

[google_maps_flutter_web ] Update README.md to discuss mouse issue when stacked

---

packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
packages/webview_flutter/webview_flutter_wkwebview/example/ios/RunnerTests/FWFInstanceManagerTests.m
packages/webview_flutter/webview_flutter_wkwebview/ios/Classes/FWFInstanceManager.m
packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml

Full fix for bug fixed in https://github.com/flutter/plugins/pull/6125 …

[webview_flutter_wkwebview] Prevent crash from released deallocCallback

---

packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/google_maps_controller_test.dart
packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/google_maps_plugin_test.dart
packages/google_maps_flutter/google_maps_flutter_web/example/pubspec.yaml

Updates for https://github.com/dart-lang/mockito/commit/d9f8e2f7a8e86afcde5a8f69aa4a1f3717d89052

migrate to new mockito API

---

packages/local_auth/local_auth/CHANGELOG.md
packages/local_auth/local_auth/README.md
packages/local_auth/local_auth/example/android/app/src/main/AndroidManifest.xml
packages/local_auth/local_auth/pubspec.yaml
packages/local_auth/local_auth_android/example/android/app/src/main/AndroidManifest.xml

Replacing deprecated `android.permission.USE_FINGERPRINT` permission with `android.permission.USE_BIOMETRIC`
Fixes https://github.com/flutter/flutter/issues/106298
Part of https://github.com/flutter/flutter/issues/78137
No change in flutter/tests
[Discord]: …

[local_auth] Replace `USE_FINGERPRINT` to `USE_BIOMETRIC` post deprecation in example and README

---

script/tool/lib/src/firebase_test_lab_command.dart
script/tool/test/firebase_test_lab_command_test.dart

The logs for cirrus tests will be moved to the GCP flutter-infra-staging project to prepare for security hardening.
This addresses work for a flutter infra OKR. …

Move Cirrus task logs to flutter-infra-staging project

---

.cirrus.yml

Bug:[#109367](https://github.com/flutter/flutter/issues/109367)
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.* …

Updating expiring cirrus key.

---

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter/pubspec.yaml

Restored the app-facing package to publishable state, using the
newly-published federated mobile implementations. …

[google_maps_flutter] Publish federation

---

packages/camera/camera_avfoundation/CHANGELOG.md
packages/camera/camera_avfoundation/example/ios/RunnerTests/CameraOrientationTests.m
packages/camera/camera_avfoundation/ios/Classes/CameraPlugin.m
packages/camera/camera_avfoundation/ios/Classes/CameraPlugin_Test.h
packages/camera/camera_avfoundation/ios/Classes/FLTCam.m
packages/camera/camera_avfoundation/ios/Classes/FLTSavePhotoDelegate.m
packages/camera/camera_avfoundation/ios/Classes/FLTThreadSafeEventChannel.m
packages/camera/camera_avfoundation/ios/Classes/FLTThreadSafeFlutterResult.m
packages/camera/camera_avfoundation/ios/Classes/FLTThreadSafeMethodChannel.m
packages/camera/camera_avfoundation/ios/Classes/FLTThreadSafeTextureRegistry.m
packages/camera/camera_avfoundation/pubspec.yaml

This is to fix a crash when reopening the app. More detailed discussion can be found [here](https://github.com/flutter/flutter/issues/109143#issuecomment-1215996900) where I explained why `orientationChange` is identified as the root cause. 
Also went through all other usages of "strong self", but I don't think it's worth writing unit tests for them, since writing weak self is a pretty standard practice. But still, I want to write the test for `CameraPlugin::orientationChanged` since it is believed to be the cause. 
Fixes https://github.com/flutter/flutter/issues/109143
If you …

[camera]use weak self to fix a crash due to orientation change

---

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter/pubspec.yaml

Quick update to version number to fix previously merged pr
NA
[exempt …

[google_maps_flutter] update to correct version

---

CODEOWNERS
packages/file_selector/file_selector/CHANGELOG.md
packages/file_selector/file_selector/README.md
packages/file_selector/file_selector/example/linux/.gitignore
packages/file_selector/file_selector/example/linux/CMakeLists.txt
packages/file_selector/file_selector/example/linux/flutter/CMakeLists.txt
packages/file_selector/file_selector/example/linux/flutter/generated_plugins.cmake
packages/file_selector/file_selector/example/linux/main.cc
packages/file_selector/file_selector/example/linux/my_application.cc
packages/file_selector/file_selector/example/linux/my_application.h
packages/file_selector/file_selector/pubspec.yaml

Endorses `file_selector_linux` now that it's part of flutter/plugins.
Fixes https://github.com/flutter/flutter/issues/70221
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#versi …

[file_selector] Endorse Linux implementation

---

CODEOWNERS

Implementation added in https://github.com/flutter/plugins/pull/5448 …

[ci] Add file_selector_ios CODEOWNER

---

packages/image_picker/image_picker_windows/example/windows/flutter/generated_plugins.cmake
packages/path_provider/path_provider/example/linux/flutter/generated_plugins.cmake
packages/path_provider/path_provider/example/windows/flutter/generated_plugins.cmake
packages/path_provider/path_provider_linux/example/linux/flutter/generated_plugins.cmake
packages/shared_preferences/shared_preferences/example/linux/flutter/generated_plugins.cmake
packages/shared_preferences/shared_preferences/example/windows/flutter/generated_plugins.cmake
packages/shared_preferences/shared_preferences_linux/example/linux/flutter/generated_plugins.cmake
packages/shared_preferences/shared_preferences_windows/example/windows/flutter/generated_plugins.cmake
packages/url_launcher/url_launcher_linux/example/linux/flutter/generated_plugins.cmake
packages/url_launcher/url_launcher_windows/example/windows/flutter/generated_plugins.cmake

This updates the generated boilerplate from running `flutter pub get` in each subdirectory.

Commit generated `cmake` boilerplate

---

packages/in_app_purchase/in_app_purchase/example/lib/main.dart
packages/in_app_purchase/in_app_purchase_android/example/lib/main.dart
packages/in_app_purchase/in_app_purchase_storekit/example/lib/main.dart

This is to enable https://github.com/flutter/flutter/pull/110162 to land.
Related to https://github.com/flutter/flutter/issues/91772
[exempt from …

[in_app_purchase] Migrate `ThemeData.errorColor`

---

script/tool/lib/src/firebase_test_lab_command.dart
script/tool/test/firebase_test_lab_command_test.dart

This is required to avoid x-gcp writes from tasks running on cirrus. …

Upload firebase test result to a buket in flutter-cirrus.

---

.cirrus.yml
script/tool_runner.sh

Make this environment variable consistent with flutter/packages (in [this PR](https://github.com/flutter/packages/pull/2577))
Fixes https://github.com/flutter/flutter/issues/111126 …

[ci] Rename PLUGIN_SHARDING to PACKAGE_SHARDING.

---

README.md

This PR adds an OpenSSF Scorecard badge to the README of the repo, similar to the one we have in flutter/packages. …

[misc] Add OpenSSF Scorecard badge to README.

---

packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit/web_kit.dart
packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit/web_kit_api_impls.dart
packages/webview_flutter/webview_flutter_wkwebview/pubspec.yaml

Update of https://github.com/flutter/plugins/pull/6288
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins- …

[webview_flutter_wkwebview] Fixes typo in an internal method name, from `setCookieForInsances` to `setCookieForInstances`

---

.github/workflows/scorecards-analysis.yml

A manual update is required to allow getting an oidc token to sign the results. …

Manual update of scorecards to 2.0.3

---

analysis_options.yaml

Replaces deprecated analysis options with their modern equivalents.

Update deprecated analysis options

---

packages/file_selector/file_selector/example/ios/Flutter/Debug.xcconfig
packages/file_selector/file_selector/example/ios/Flutter/Release.xcconfig
packages/file_selector/file_selector/example/ios/Podfile

Checks in a few files/changes that are generated when building the example for iOS, which weren't landed with the original iOS support PR.
Avoids having local changes whenever running `pub get` or building examples in this package. …

[file_selector] Add all iOS files to example app

---

packages/in_app_purchase/in_app_purchase/CHANGELOG.md
packages/in_app_purchase/in_app_purchase/pubspec.yaml

Bumps `in_app_purchase_android` minimum version to 0.2.3. This version of `in_app_purchase_android` upgrades the Google Play Billing Library from 3.0.2 to 5.0, which is a requirement for the Google Play store: https://developer.android.com/google/play/billing/deprecation-faq
Successor to https://github.com/flutter/plugins/pull/6525 …

[in_app_purchase] Bumps `in_app_purchase_android` minimum version to 0.2.3

---

analysis_options.yaml
packages/google_sign_in/google_sign_in_web/lib/src/generated/gapiauth2.dart
packages/in_app_purchase/in_app_purchase_storekit/test/fakes/fake_storekit_platform.dart

The strict- values are meant to be used via the language key
See https://dart.dev/guides/language/analysis-options

Fix strict language checks

---

packages/webview_flutter/webview_flutter_wkwebview/lib/src/v4/src/webkit_webview_controller.dart
packages/webview_flutter/webview_flutter_wkwebview/test/v4/webkit_webview_widget_test.dart

Part of https://github.com/flutter/flutter/issues/94051
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins …

[webview_flutter_wkwebvew] Sets key value in UiKitView

---

FlutterFire.md

Fixes https://github.com/flutter/flutter/issues/116942
Updates link to FlutterFire to point to the current repo.
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-chan …

Update FlutterFire link

---

packages/webview_flutter/webview_flutter/CHANGELOG.md
packages/webview_flutter/webview_flutter/lib/webview_flutter.dart
packages/webview_flutter/webview_flutter/pubspec.yaml
packages/webview_flutter/webview_flutter/test/webview_flutter_test.dart

Fixes https://github.com/flutter/flutter/issues/117556
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins- …

[webview_flutter] Exposes `WebResourceErrorType`

---

packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
packages/google_maps_flutter/google_maps_flutter/README.md
packages/google_maps_flutter/google_maps_flutter/example/lib/readme_sample.dart
packages/google_maps_flutter/google_maps_flutter/pubspec.yaml

**Changelogs**
- Added a missing bracket at the end of the sample code.
- Added missing imports to the same sample code.
**Issue fixed**
Syntax issue in the code sample to copy. …

[google_maps_flutter] Fixed minor syntax error in the README.md

---

CODEOWNERS

Update `image_picker_ios` CODEOWNER

---

CODEOWNERS

Update CODEOWNERs.
google_sign_in_ios to @vashworth 
local_auth_ios to @LouiseHsu

Change `google_sign_in_ios` and `local_auth_ios ` owners

---

packages/espresso/CHANGELOG.md
packages/espresso/android/build.gradle
packages/espresso/pubspec.yaml

Taking over dependabot update https://github.com/flutter/plugins/pull/6934 …

[Espresso] Update expressio dependencies 

---

packages/url_launcher/url_launcher/CHANGELOG.md
packages/url_launcher/url_launcher/README.md
packages/url_launcher/url_launcher/example/ios/Flutter/AppFrameworkInfo.plist
packages/url_launcher/url_launcher/example/ios/Podfile
packages/url_launcher/url_launcher/example/ios/Runner.xcodeproj/project.pbxproj
packages/url_launcher/url_launcher/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/url_launcher/url_launcher/example/ios/Runner/Info.plist
packages/url_launcher/url_launcher/pubspec.yaml
packages/url_launcher/url_launcher_ios/CHANGELOG.md
packages/url_launcher/url_launcher_ios/example/ios/Flutter/AppFrameworkInfo.plist
packages/url_launcher/url_launcher_ios/example/ios/Podfile
packages/url_launcher/url_launcher_ios/example/ios/Runner.xcodeproj/project.pbxproj
packages/url_launcher/url_launcher_ios/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/url_launcher/url_launcher_ios/example/ios/Runner/Info.plist
packages/url_launcher/url_launcher_ios/example/lib/main.dart
packages/url_launcher/url_launcher_ios/example/pubspec.yaml
packages/url_launcher/url_launcher_ios/ios/Classes/FLTURLLauncherPlugin.m
packages/url_launcher/url_launcher_ios/ios/url_launcher_ios.podspec
packages/url_launcher/url_launcher_ios/pubspec.yaml

`url_launcher_ios` part of https://github.com/flutter/flutter/issues/101965.
Built the `url_launcher` and `url_launcher_ios` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.
[Discord]: …

[url_launcher_ios] Update minimum Flutter version to 3.3 and iOS 11

---

packages/path_provider/path_provider_linux/CHANGELOG.md
packages/path_provider/path_provider_linux/pubspec.yaml

`xdg_directories` 0.2.0 was update to 1.0 to reflect that it has a stable API, with no other changes. This updates the constraint to allow either 0.2.x or 1.x to avoid dependency conflicts in the future. …

[file_selector] Relax xdg_directories constraint

---

packages/ios_platform_images/CHANGELOG.md
packages/ios_platform_images/README.md
packages/ios_platform_images/example/ios/Flutter/AppFrameworkInfo.plist
packages/ios_platform_images/example/ios/Podfile
packages/ios_platform_images/example/ios/Runner.xcodeproj/project.pbxproj
packages/ios_platform_images/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
packages/ios_platform_images/example/ios/Runner/Info.plist
packages/ios_platform_images/ios/ios_platform_images.podspec
packages/ios_platform_images/pubspec.yaml

`ios_platform_images` part of https://github.com/flutter/flutter/issues/101965.
Built the `ios_platform_images` example projects on Flutter 3.3. and let the tool auto-migrate various Xcode project/Podfile files.
[pub …

[ios_platform_images] Update minimum version to iOS 11

---

packages/espresso/CHANGELOG.md
packages/espresso/android/build.gradle
packages/espresso/pubspec.yaml

Bumps the version of several dependencies. Combines the following PRs into a single release:
https://github.com/flutter/plugins/pull/6926
https://github.com/flutter/plugins/pull/6927
https://github.com/flutter/plugins/pull/6928
https://github.com/flutter/plugins/pull/6929
https://github.com/flutter/plugins/pull/6930
https://github.com/flutter/plugins/pull/6932
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-chang …

[espresso] Update some dependencies
